### ISSUE TITLE
The Readme file is empty

### ISSUE THREAD

**Issue by atrah22** [ARM-software/armnn#1]
Hello,

The readme file is empty.  How to build armnn library?
I came accross this tutorial of armnn-mnist (https://github.com/ARM-software/ML-examples/tree/master/armnn-mnist). But without the armnn library i cannot run the mnist example.

**Comment by mjb67** [comment]
Hi @atrah22 thanks for your question.
Our documentation will be ready soon. Sorry for the delay.

**Comment by MatthewARM** [comment]
Hi @atrah22 not all of the documentation is ready yet but you can find build instructions at https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment/configuring-the-arm-nn-sdk-build-environment-single-page

**Comment by atrah22** [comment]
Hello @MatthewARM,
This build instructions are for linux OS. Will there be any build isntructions soon for Android OS ? I was looking to build applicaitons for android OS.

**Comment by MatthewARM** [comment]
Hi @atrah22, we'll see what we can do about providing documentation for that use case.

To help me understand precisely what you mean, are you intending to build an application apk that uses ArmNN? Are you going to use a Caffe model with it?

**Comment by atrah22** [comment]
Yes right.

I will use armNN to accelerate a CNN (pretrained Caffe model) usng ARM Mali GPU.

**Comment by MatthewARM** [comment]
Great. We have tested it that way, but we don't have specific build instructions using the Android NDK yet. However, ArmNN uses a standard Cmake build system, so you can adapt the instructions at https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-android-with-a-standalone-toolchain

**Comment by tsyu** [comment]
Hi @MatthewARM, 

In the build instructions you mentioned before:

Your platform or board must have:
At least 4GB of RAM.

Seriously?  I thought memory requirement should relates to model selection, and should have small memory footprint for simple models.

**Comment by MatthewARM** [comment]
I'm aware of people using ArmNN on boards with much less RAM than that.

**Comment by tsyu** [comment]
Thanks!
I'm also wondering how this project relates to ARM-software/android-nn-driver.
They're both noted "Arm NN" in official slides, but this one looks more generic.
Will they merge in the future?

**Comment by MatthewARM** [comment]
Hi @tsyu the android-nn-driver component uses the ArmNN core library to provide an implementation of the android.hardware.neuralnetworks@1.0 HAL interface.

In other words it is a vendor driver for Mali for the Android NNAPI. You need it if you are phone OEM using Mali to accelerate the Android NNAPI. You don't need it if you are writing a program that targets the ArmNN API directly.

They won't merge, but you can think of the android-nn-driver as a separate, optional, component of the ArmNN product.

**Comment by tsyu** [comment]
Thank you, @MatthewARM!
I'll try both on HiKey 960.

**Comment by atrah22** [comment]
Hello,
I followed https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment/configuring-the-arm-nn-sdk-build-environment-single-page .
When i enter "make" command, it still searches for libboost in the "/usr/lib/x86_64-linux-gnu" directory. However, I clearly put "-DBOOST_ROOT=~/boost_1_64_0 " argument for cmake. And also I used -fPIC on the cxx flags to build boost.
The make command error is stated below:
[  3%] Built target armnnUtils
[  4%] Linking CXX shared library libarmnn.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_log.a(attribute_name.o): relocation R_X86_64_32 against `_ZZN5boost3log12v2s_mt_posix3aux14lazy_singletonINS1_14attribute_name10repositoryENS_10shared_ptrIS5_EEE3getEvE29_boost_log_once_block_flag_43' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_log.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libarmnn.so] Error 1
make[1]: *** [CMakeFiles/armnn.dir/all] Error 2
make: *** [all] Error 2

**Comment by tsyu** [comment]
I think at least "cross-compile" should be mentioned in that guide (boost part).

**Comment by tsyu** [comment]
Hi @atrah22, 
You should add your cross-compiler with cmake, like:
-DCMAKE_CXX_COMPILER=aarch64-linux-gnu-c++ -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc
Or it will use /usr/bin/c++ and /usr/bin/gcc

Hi @MatthewARM, 
Which toolchain do you recommend?
I used a randomly picked gcc-linaro-aarch64-linux-gnu-4.9-2014.09_linux but failed to build armnn.

**Comment by atrah22** [comment]
@tsyu, Thankyou.
Now I am used the following command for cmake to build for Android OS, aarch64 arm:
cmake -DARMCOMPUTE_ROOT=/home/atul/git_work/ARM/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=/home/atul/git_work/ARM/ComputeLibrary/build -DBOOST_LIBRARYDIR=/home/atul/boost_1_64_0/stage/lib -DCAFFE_GENERATED_SOURCES=/home/atul/git_work/caffe/caffe/.build_release/src -DBUILD_CAFFE_PARSER=1 -DARMCOMPUTECL=1 -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=/home/atul/git_work/Android/android-ndk-r16b -DCMAKE_CXX_COMPILER=aarch64-linux-android-g++ -DCMAKE_C_COMPILER=aarch64-linux-android-gcc ..

Now the error is on hpp files like below ( @MatthewARM )
[  1%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/Logging.cpp.o
[  2%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/Permute.cpp.o
[  3%] Linking CXX static library libarmnnUtils.a
[  3%] Built target armnnUtils
Scanning dependencies of target armnn
[  4%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/ClWorkloadFactory.cpp.o
In file included from /home/atul/git_work/ARM/armnn/include/armnn/IRuntime.hpp:12:0,
                 from /home/atul/git_work/ARM/armnn/src/armnn/backends/ClWorkloadFactory.hpp:9,
                 from /home/atul/git_work/ARM/armnn/src/armnn/backends/ClWorkloadFactory.cpp:5:
/home/atul/git_work/ARM/armnn/include/armnn/TypesUtils.hpp: In function 'constexpr const char* armnn::GetStatusAsCString(armnn::Status)':
/home/atul/git_work/ARM/armnn/include/armnn/TypesUtils.hpp:24:1: error: body of constexpr function 'constexpr const char* armnn::GetStatusAsCString(armnn::Status)' not a return-statement
 }

**Comment by tsyu** [comment]
Same error here.  I'm trying newer gcc version (4.9 -> 5 or 6)

**Comment by atrah22** [comment]
Hello @tsyu , I solved it.

I  used clang++ instead of g++ and the error went away.
cmake -DARMCOMPUTE_ROOT=/home/atul/git_work/ARM/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=/home/atul/git_work/ARM/ComputeLibrary/build -DBOOST_LIBRARYDIR=/home/atul/boost_1_64_0/stage/lib -DCAFFE_GENERATED_SOURCES=/home/atul/git_work/caffe/caffe/.build_release/src -DBUILD_CAFFE_PARSER=1 -DARMCOMPUTECL=1 -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=/home/atul/git_work/Android/android-ndk-r16b -DCMAKE_CXX_COMPILER=aarch64-linux-android-c++ -DCMAKE_C_COMPILER=aarch64-linux-android-clang ..

However, I have a new problem regarding finding the libOpenCL.so file (It is by default considering the x86_64-lunx-gnu/libOpenCL.so file). I have the libOpenCL.so file for my device. How to include this libOpenCL file instead of the linux onw?

**Comment by tsyu** [comment]
I think it's intended to link against ComputeLibrary/opencl-1.2-stubs, but once find_library() found your host libOpenCL.so, the host one was chosen:
cmake/GlobalConfig.cmake:
if(ARMCOMPUTECL)
...

    find_library(OPENCL_LIBRARIES OpenCL)
    if (NOT OPENCL_LIBRARIES)
        # Link against libOpenCL in opencl-1.2-stubs, but don't search there at runtime
        link_libraries(-L${ARMCOMPUTE_BUILD_DIR}/opencl-1.2-stubs)  # Should use this
        set(OPENCL_LIBRARIES OpenCL)
    endif()
--
Modifying this to always link the stubs work for me, but I think better fix is required.

**Comment by atrah22** [comment]
@tsyu ,

Yes that worked. Finally I am left with 1 error at 100% Linkin CXX executable UnitTests!

[ 99%] Building CXX object CMakeFiles/UnitTests.dir/src/armnn/backends/test/MemCopyTests.cpp.o
[100%] Linking CXX executable UnitTests
/home/atul/boost_1_64_0/stage/lib/libboost_unit_test_framework.a(unit_test_main.o): In function `main':
unit_test_main.cpp:(.text.startup+0x8): undefined reference to `init_unit_test()'
unit_test_main.cpp:(.text.startup+0xc): undefined reference to `init_unit_test()'
libarmnn.so: undefined reference to `stdout'
libarmnn.so: undefined reference to `__android_log_write'
clang50++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [UnitTests] Error 1
make[1]: *** [CMakeFiles/UnitTests.dir/all] Error 2
make: *** [all] Error 2

**Comment by tsyu** [comment]
Hi @atrah22, 
I'm using gcc-6, not ndk clang.  And I did not see your last error here.

**Comment by atrah22** [comment]
gcc-6 for linux OS?
I am using Android OS. I am using ndk-16b and it only has gcc 4.9

**Comment by Wayne-pw** [comment]
Hi  @atrah22,
I'm using android-ndk-r16 with "cmake -DARMCOMPUTE_ROOT=/home/atul/git_work/ARM/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=/home/atul/git_work/ARM/ComputeLibrary/build -DBOOST_LIBRARYDIR=/home/atul/boost_1_64_0/stage/lib -DCAFFE_GENERATED_SOURCES=/home/atul/git_work/caffe/caffe/.build_release/src -DBUILD_CAFFE_PARSER=1 -DARMCOMPUTECL=1 -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=/home/atul/git_work/Android/android-ndk-r16b -DCMAKE_CXX_COMPILER=aarch64-linux-android-clang++ -DCMAKE_C_COMPILER=aarch64-linux-android-clang ..",but there are some new mistakes
Android: Did not detect API level from
    android-ndk-r16/bin/clang  or android-ndk-r16/sysroot/usr/include/android/api-level.h
Call Stack (most recent call first):
  cmake-3.10.2/Modules/CMakeDetermineSystem.cmake:130 (include)
  CMakeLists.txt:2 (project)
CMake Error at cmake-3.10.2/Modules/Platform/Android-Determine.cmake:195 (message):
  Android: The API specified by CMAKE_SYSTEM_VERSION='' is not an integer.
Call Stack (most recent call first):
  cmake-3.10.2/Modules/CMakeDetermineSystem.cmake:130 (include)
  CMakeLists.txt:2 (project)

Have you ever had this problem？

**Comment by atrah22** [comment]
@Wayne-pw ,
Yes. Just delete the build folder and remake the build folder and use cmake again.

**Comment by Wayne-pw** [comment]
excuse me @atrah22, I want to know caffe compile with clang?

**Comment by madtom1999** [comment]
I'm using https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe (from the README.md) and when I try and build boost (the latest stable) I am at a loss as to where to put the build options mentioned in https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe/setting-up-the-build-dependencies.

**Comment by MatthewARM** [comment]
Hi @madtom1999 those options are passed to b2 when building boost, you can see the full documentation for building boost here: https://www.boost.org/doc/libs/1_64_0/more/getting_started/unix-variants.html#invoke-b2

I'm going to close this issue as I think the discussion has run its course, and there is now content in the  Readme file. Those still having build problems please raise new specific issues, thanks!

**Comment by mike2ning** [comment]
hi，I arm porting arm nn to embedded platforms(imx6d ,linux), refer to Configuring the Arm NN SDK build environment for Caffe step by step and I have some doubts as below:

1,all of source code need to compile by arm-linux-gnueabihf-gcc/g++ (GCC-4.9) ?

2,arm-nn can only run embedded platforms arm64 not arm32?

3,arm-nn can run embedded platforms with embedded linux system?

**Comment by phamyphen** [comment]
@atrah22,
Have you solved below issues for Andorid OS?
libarmnn.so: undefined reference to `__android_log_write'

**Comment by joonsung90** [comment]
@phamyphen,
The error means you need liblog (android) library for the building.
You can manually add -llog in the command line to resolve the error OR
check cmake's parameters "-DCMAKE_SYSTEM_NAME". In the default setting, it might be Linux ("-DCMAKE_SYSTEM_NAME=Linux"). Please change it from Linux to Android. (like "-DCMAKE_SYSTEM_NAME=Android"). (This variable forces to add "-llog" option)

**Comment by mvhsin** [comment]
Hi @atrah22,
I met the same error as
"recompile with -fPIC
/libboost_log.a: error adding symbols: Bad value" 
And I am using "gcc-linaro-7.2.1-2017.11-i686_arm-linux-gnueabihf", may I know how do you solve the problem?

Thanks,
Shelly

**Comment by MatthewARM** [comment]
Hi @mvhsin you need to add `cxxflags=-fPIC` to your b2 command line. If you are still having trouble please could you open a new issue in order to improve visibility and tracking?

**Comment by mvhsin** [comment]
Thank you @MatthewARM!
I found my problem is that gcc version is different with boost and armnn.
Now it’s fixed. Thanks for your message!

**Comment by MatthewARM** [comment]
@mvhsin You're welcome, good luck with your project.
