### ISSUE TITLE
how to build armnn for arm32

### ISSUE THREAD

**Issue by yanghaiping1993** [ARM-software/armnn#100]

**Comment by yanghaiping1993** [comment]
@MatthewARM how to build armnn for arm32?

**Comment by MatthewARM** [comment]
Hi @yanghaiping1993 it's pretty much the same as building for aarch64. Do you need it for Android or Linux?

**Comment by yanghaiping1993** [comment]
@MatthewARM I will do it in Linux，and compile the 32  bit excutable file, and push it in my arm board to do test

**Comment by MatthewARM** [comment]
Hi @yanghaiping1993 I think there's more than one way of doing this, but this is what I do:
Create a file called `boost-arm.jam` containing:
`using gcc : arm : arm-linux-gnueabihf-g++ ;`

Then do:
`./bootstrap.sh`
`./b2 --user-config=/home/MatthewARM/gits/devenv/boost-arm.jam toolset=gcc-arm -a link=static cxxflags=-fPIC --with-filesystem --with-test --with-log --with-program_options -j16 --prefix=/home/MatthewARMA/gits/devenv/install/arm/boost --with-python install`

I then get:
`    - 32-bit                   : yes (cached)`
`    - arm                      : yes (cached)`

If it is wrong, and it says "cached", try deleting bin.v2/project-cache.jam and trying again.
Al
l the best,
Matthew

**Comment by yanghaiping1993** [comment]
@MatthewARM  I deleted the build folder all, and rebuild it ,it works well ,thx!
