### ISSUE TITLE
Armnn Error: Unsupported operation Split in tensorflow::GraphDef

### ISSUE THREAD

**Issue by wutao9999555** [ARM-software/armnn#101]
We are trying to use armnn run ShuffleNetV2 tensorflow model but get the error as “Armnn Error: Unsupported operation Split in tensorflow::GraphDef”; version is ArmNN v20180800.
BTW: Looks like in CaffeSupport.md, split op is supported, but not for TFParse.
Please advice on how to resolve the problem. Thanks!

**Comment by wutao9999555** [comment]
Hello, 
Any update or suggestion for this issue?
Thanks!

**Comment by MatthewARM** [comment]
Hi @wutao9999555 I've been looking in to this and although the first layer that is not supported is Split, it seems there are other layers that are also not supported by the parser. If we just added Split, the error message would change to the next unsupported layer.

Some of the missing layers are already on our roadmap, some aren't.

At this stage the most constructive thing I could suggest would be for you to help integrate the easy bits (ie. the layers for which there is already support present). Contributions to ArmNN are accepted under the MIT license, so you can try to add in the missing bits of the parser and we will review your submissions.

The latest development branch of ArmNN is here: https://review.mlplatform.org/#/admin/projects/ml/armnn

I will note down your request for "Tensorflow ShuffleNetV2 Support" on our roadmap.

**Comment by MatthewARM** [comment]
Closing this ticket as support for Split in Tensorflow was added in the 19.02 release. @wutao9999555 I hope everything is going well and please get back in touch if you are still having problems.
