### ISSUE TITLE
Arm NN support Cortex R platform

### ISSUE THREAD

**Issue by sbalpande1990** [ARM-software/armnn#102]
Hi,

I have few query  on Arm nn supports platform are follows

1. Cortex R does not support at all, or it is support but expected that performance will be not sufficient for any NN?

2. Does ARMNN will not run without NEON extension?

Thanks and Regards,
Swapnil

**Comment by MatthewARM** [comment]
Hi @sbalpande1990 the CpuAcc backend of ArmNN needs NEON. The CpuRef backend of ArmNN is just for testing, it won't give good performance.

Can I ask you to describe a bit more about your use-case? E.g. what sort of Cortex-R core are you running on and how much RAM do you have? If ArmNN won't work for you in its current form we might be able to figure something else out, or at least feed in your requests to our roadmap.

All the best,
Matthew

**Comment by sbalpande1990** [comment]
Hi MatthewARM,

We have developed CNN classifier code and wanted to port on ARM platform. The platform should have support to ARM nn library for optimize the algorithm performance. 

We are planing to use Cortex R5 processor.

Moreover we need to understand about the ARMNN compatibility with Cortex R5 platform or not. 

Did any one tested the ARM NN framework on Cortex R5?

Regards,
Swapnil

**Comment by MatthewARM** [comment]
Hi @sbalpande1990 Cortex-R5 doesn't have NEON, so the CpuAcc path in ArmNN won't work.

No one has ever compiled ArmNN for a Cortex-R series processor. It's theoretically possible to make it work on Cortex-R52 with NEON, but there would be some modifications needed in the build system at the very least.

I hope that helps, and I'm sorry the answer is broadly negative. I hope that you can find a solution for your use-case, and if you have any more questions please ask them.

Best regards,
Matthew

**Comment by MatthewARM** [comment]
@sbalpande1990 if you would like to talk to someone at Arm about your application, I can put you in touch with the right person? If you want to follow this route, please email me at matthew.bentham@arm.com
