### ISSUE TITLE
Unsupported operation "pad" in tensorflow::GraphDef

### ISSUE THREAD

**Issue by mibrahimali** [ARM-software/armnn#108]
i`m trying to test ResNet-50 with Armnn SDK but it fails due to unsupported layer "pad". i tried solution given in #90 but i think the layer still exit after optimization. is there any information when this layer will be supported by Armnn TF parser  ?

note: i`m using ArmNN V18.11 and ComputeLib V18.11

**Comment by MatthewARM** [comment]
We have added that to the development branch recently: https://review.mlplatform.org/#/c/ml/armnn/+/345/ and it will be part of the next release.
