### ISSUE TITLE
Depthwise Separable  convolution 2D support 

### ISSUE THREAD

**Issue by sbalpande1990** [ARM-software/armnn#109]
Hi,

We have developed  and tested a neural net with the ARM-NN library using Neon on Cortex-A53. 

But the results are not promising to the extent. We need more optimization on net. When we have looking at ARM-NN supported function, we found that "separable convolution 2d" operation not supported. 

We are expecting that depth wise separable  convolution 2D operation gives us good optimization on net.

So Is any plan to support this function in future or any other alternative you can provide to us.

Regards,
Swapnil

**Comment by MatthewARM** [comment]
Hi @sbalpande1990 I believe you can implement depthwise separable convolution using a depthwise convolution followed by a 1x1 convolution. This is how we do it for Mobilenets as represented in Tensorflow, Tensorflow Lite, and via Android NNAPI. 

Are you doing it this way and the performance is not good? Would you be willing to share any information about the configuration (shapes, etc.) of the convolutions you are doing to help guide our optimisation?

**Comment by sbalpande1990** [comment]
Hi Matthew,

Yes we are able to build with depthwise convolution followed by a 1x1 convolution. 

Thanks for your input.

Regards,
Swapnil
