### ISSUE TITLE
Arm NN SDK support for CMSIS-NN?

### ISSUE THREAD

**Issue by sbochkar** [ARM-software/armnn#11]
I'm trying to run the examples/tutorials for Arm NN SDK on a Cortex M7.

The landing page for [Arm NN SDK](https://developer.arm.com/products/processors/machine-learning/arm-nn) suggests it is possible through the use of CMSIS-NN neural network kernels. However, from Arm NN SDK source code, I do not see how it is possible to do that.

The only functionality I want is the ability to parse Caffe models.

Can someone confirm if it is doable? If not, is it something that will be supported in the feature? Thanks a lot!

**Comment by MatthewARM** [comment]
Hi @sbochkar sorry for the delay answering your question. Arm NN for CMSIS-NN is not available yet and I'm sorry that I cannot confirm when it will be ready.

If you could comment about the sort of device you are intending to use, the amount of RAM available, and the how big the neural network is I can make sure that information is made available to the development team.  If not, I completely understand.

Best regards,
Matthew
