### ISSUE TITLE
Unknown DataType DT_BOOL for node phase_train/_4__cf__5  at function ConvertTfTensorDataType

### ISSUE THREAD

**Issue by WIll-Xu35** [ARM-software/armnn#110]
Hi all,

Recently I am trying to put tensorflow version of mobilefacenet on an arm board using armnn. After I remove all the training nodes from the network and try to put it on chip, it raises an error: Unknown DataType DT_BOOL for node phase_train/_4__cf__5  at function ConvertTfTensorDataType

I checked the network and found this node (op type Const) in BN layer and it should be related to training and should have been removed by tensorflow's graph transform tool.

Any idea how I can solve this problem?

Thanks

**Comment by MatthewARM** [comment]
Hi @WIll-Xu35 could you share the transform graph command you are using? And possibly a link to the model?

Many thanks,
Matthew

**Comment by WIll-Xu35** [comment]
Hi @MatthewARM. Thank you for your reply.

I tried two open source pretrained model of mobilefacenet, one is from https://github.com/yangxue0827/MobileFaceNet_Tensorflow/tree/master/output/ckpt_best/tinymobilefacenet_best_ckpt, the other is from https://github.com/sirius-ai/MobileFaceNet_TF.

And the command I used is :
bazel build tensorflow/tools/graph_transforms:transform_graph
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=mobilefacenet.pb \
--out_graph=mobilefacenet_optimized.pb \
--inputs='input' \
--outputs='embeddings' \
--transforms='
  strip_unused_nodes(type=float, shape="1,112,112,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms'

It seems that all the swtich ops are not touched during the transform and the phase_train/_4__cf__5 is one of the inputs to those switches. (it is of a different name in the model from https://github.com/sirius-ai/MobileFaceNet_TF, but it also starts with phase_train)

I also tried to add 'op = Switch' to parameters of remove_nodes, but the new pb file generated is exactly the same as not adding 'op = Switch'.

Thank you so much for your help!

**Comment by MatthewARM** [comment]
Hi @WIll-Xu35 thanks for the information. I'm afraid this model is using conditions (ie. switch nodes) which ArmNN does not yet support. This is something we are looking at adding support for during 2019. If you would like to track the progress of ArmNN (and perhaps contribute?) you can use our master development Gerrit repository at https://review.mlplatform.org

All the best,
Matthew

**Comment by WIll-Xu35** [comment]
@MatthewARM I forget to mention this: #15 

I think I'm actually facing the same problem as in issue 15. We both have remaining switch nodes and control inputs from 'phase train'. And we are both using face recognition models (facenet and mobilefacenet)

And you mentioned that a possible workaround is disconnecting phase train and switch nodes, can you give some hints on how to accomplish this?

Much appreciated.

**Comment by WIll-Xu35** [comment]
Hi @MatthewARM 

Thank you very much for your suggestions and analysis. I'll follow your development work.

The chip I'm using is RK3399. I'm not sure whether I'll need NEON acceleration, but I'm pretty sure OpenCL acceleration is required.

**Comment by MatthewARM** [comment]
Hi @WIll-Xu35 that's got 2x Cortex-A72 and 4x Cortex-53, with an Arm Mail T860 GPU.  For this chip NEON (via the ArmNN CpuAcc backend) will work well, but you should run some simple test cases to make sure that the OpenCL support is sufficient for the ArmNN GpuAcc backend, as it might depend on the version of the Mali OpenCL driver that you are using.
