### ISSUE TITLE
Error about Configuring the Arm NN SDK build environment for TensorFlow

### ISSUE THREAD

**Issue by tanjiarui** [ARM-software/armnn#114]
This is a very foolish problem. I doubt somebody recklessly typing that! In the [document](https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow/building-the-environment), step 4, -DTF_GENERATED_SOURCES should be the location of your tensorflow generated source files instead of the location of your protobuf generated source files.

**Comment by MatthewARM** [comment]
Hi @tanjiarui thanks for raising this. The description is intended to mean "the files generated using the protobuf compiler".  I'll raise this as an issue with the documentation team for them to clarify.

It would probably be simpler if it just said "the output directory used in step 3".

Thanks,
Matthew
