### ISSUE TITLE
Unsupported operation Sum in tensorflow::GraphDef

### ISSUE THREAD

**Issue by Younghee02** [ARM-software/armnn#117]
Hello.
I'm trying to us Armnn run network tensorflow  model.
but there is an error,  Unsupported operation Sum in tensorflow::GraphDef.
Do you have any plan to support Sum operation?

unsing Armnn v18.11

**Comment by MatthewARM** [comment]
Hi @Younghee02 I don't think we have that on our current plans, but I can add it to our roadmap. Do you know exactly which Tensorflow operator it is?

https://www.tensorflow.org/probability/api_docs/python/tfp/sts/Sum
or
https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum

Many thanks,
Matthew

**Comment by Colm-in-Arm** [comment]
Hi @Younghee02,

If you still need this operator you can open a new issue specifying which of the two Tensorflow operator it is. In the meantime I'll close this issue.

Colm.
