### ISSUE TITLE
ARM-NN vs Manual optimization of a fixed CNN network

### ISSUE THREAD

**Issue by rahulkodinya** [ARM-software/armnn#118]
I need to accelerate the inference of a CNN network ( similar to LeNet ) for an octa-core Cortex A73 CPU.

Same Inference is invoked **a Million times for each 4x4 pixel group in a 16 megapixel image**. I am looking forward to manually apply following techniques for optimization:
1) Perform Inter-layer optimizations by localizing producer-consumer operations in tiles of the images. Network structure is fixed.
2) Create 8 threads to process 1/8 Million inferences.
3) Merge multiple inferences in order to achieve maximum throughput from NEON.

I am not sure if the performance on ARM-NN will be similar with the optimization with above techniques. **Please guide !!**

**Comment by MatthewARM** [comment]
Hi @rahulkodinya I've had a bit of a think about this and I think the answer is that it depends if you are currently memory-bound or compute-bound for performance:

1. ArmNN doesn't (currently) perform inter-layer optimisation for LeNet so hand optimising here will save memory bandwidth. This will help if you are currently memory-bandwidth.
2. ArmNN with the Compute Library NEON backend will use 8xA73 cores quite efficiently in a LeNet-style network.
3. ArmNN will happily handle a large batch size for batching up large numbers of inferences. 

Hope that helps,
Matthew

**Comment by rahulkodinya** [comment]
Thanks Matthew.
