### ISSUE TITLE
TensorflowLiteParser UnitTest error

### ISSUE THREAD

**Issue by kwangchoon** [ARM-software/armnn#120]
< Build conditions >
android-ndk-r16b-linux-x86_64.zip
boost_1_64_0.tar.bz2
tensorflow : checkout 1.12
protobuf : checkout v3.5.2
flatbuffers : checkout v1.10.0
ComputeLibrary : checkout v18.11
armnn : checkout v18.11

The following ArmNN library files were built the armnn/build directory:
libarmnn.so
libarmnnTfLiteParser.so
libarmnnTfParser.so
libarmnnUtils.a

To check that your build of the Arm NN SDK is working correctly, 
I ran the unit tests on Galaxy-N9 (SM-N960N).

Running 1200 test cases...
unknown location(0): fatal error: in "TensorflowLiteParser/ParseReLu": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Activations.cpp(71): last checkpoint: "ParseReLu" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseReLu6": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Activations.cpp(81): last checkpoint: "ParseReLu6" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/AvgPoolLite1DOutput": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/AvgPool2D.cpp(99): last checkpoint: "AvgPoolLite1DOutput" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/AvgPoolLiteFloat1DOutput": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/AvgPool2D.cpp(104): last checkpoint: "AvgPoolLiteFloat1DOutput" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/AvgPoolLite2DOutput": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/AvgPool2D.cpp(109): last checkpoint: "AvgPoolLite2DOutput" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/IncorrectDataTypeError": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/AvgPool2D.cpp(114): last checkpoint: "IncorrectDataTypeError" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseConcatenationNegativeDim": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Concatenation.cpp(101): last checkpoint: "ParseConcatenationNegativeDim" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseConcatenationNCHW": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Concatenation.cpp(114): last checkpoint: "ParseConcatenationNCHW" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseConcatenationNHWC": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Concatenation.cpp(127): last checkpoint: "ParseConcatenationNHWC" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseConcatenationDim1": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Concatenation.cpp(140): last checkpoint: "ParseConcatenationDim1" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseConcatenationDim3": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Concatenation.cpp(158): last checkpoint: "ParseConcatenationDim3" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseSimpleConv2D": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Conv2D.cpp(90): last checkpoint: "ParseSimpleConv2D" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseConv2DWithBias": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Conv2D.cpp(220): last checkpoint: "ParseConv2DWithBias" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseConv2D_112x112_out": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Conv2D.cpp(265): last checkpoint: "ParseConv2D_112x112_out" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseConv2DAndReluWithBias": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Conv2D.cpp(287): last checkpoint: "ParseConv2DAndReluWithBias" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseConv2DAndRelu6WithBias": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Conv2D.cpp(330): last checkpoint: "ParseConv2DAndRelu6WithBias" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseDepthwiseConv2DSame": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/DepthwiseConvolution2D.cpp(134): last checkpoint: "ParseDepthwiseConv2DSame" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseDepthwiseConv2DValid": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/DepthwiseConvolution2D.cpp(161): last checkpoint: "ParseDepthwiseConv2DValid" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseDepthwiseConv2DSameBias": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/DepthwiseConvolution2D.cpp(186): last checkpoint: "ParseDepthwiseConv2DSameBias" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/FullyConnectedWithNoBias": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/FullyConnected.cpp(126): last checkpoint: "FullyConnectedWithNoBias" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseFullyConnectedWithBias": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/FullyConnected.cpp(146): last checkpoint: "ParseFullyConnectedWithBias" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/MaxPoolLiteUint1DOutput": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/MaxPool2D.cpp(99): last checkpoint: "MaxPoolLiteUint1DOutput" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/MaxPoolLiteFloat1DOutput": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/MaxPool2D.cpp(104): last checkpoint: "MaxPoolLiteFloat1DOutput" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/MaxPoolLiteUint2DOutput": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/MaxPool2D.cpp(109): last checkpoint: "MaxPoolLiteUint2DOutput" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/MaxPoolIncorrectDataTypeError": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/MaxPool2D.cpp(114): last checkpoint: "MaxPoolIncorrectDataTypeError" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseReshapeWithReshapeDims": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Reshape.cpp(86): last checkpoint: "ParseReshapeWithReshapeDims" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseReshapeWithReshapeDimsFlatten": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Reshape.cpp(101): last checkpoint: "ParseReshapeWithReshapeDimsFlatten" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseReshapeWithReshapeDimsFlattenTwoDims": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Reshape.cpp(116): last checkpoint: "ParseReshapeWithReshapeDimsFlattenTwoDims" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseReshapeWithReshapeDimsFlattenOneDim": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Reshape.cpp(131): last checkpoint: "ParseReshapeWithReshapeDimsFlattenOneDim" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseSoftmaxLite": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Softmax.cpp(72): last checkpoint: "ParseSoftmaxLite" fixture entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseSqueezeWithSqueezeDims": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Squeeze.cpp(85): last checkpoint: "ParseSqueezeWithSqueezeDims" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseSqueezeWithoutSqueezeDims": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Squeeze.cpp(99): last checkpoint: "ParseSqueezeWithoutSqueezeDims" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ParseSqueezeInvalidInput": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Squeeze.cpp(115): last checkpoint
unknown location(0): fatal error: in "TensorflowLiteParser/ParseSqueezeInvalidSqueezeDims": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Squeeze.cpp(127): last checkpoint
unknown location(0): fatal error: in "TensorflowLiteParser/ParseSqueezeNegativeSqueezeDims": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/Squeeze.cpp(140): last checkpoint
unknown location(0): fatal error: in "TensorflowLiteParser/LoadModelFromBinary": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/LoadModel.cpp(186): last checkpoint: "LoadModelFromBinary" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/LoadModelFromFile": armnn::ParseException: Buffer doesn't conform to the expected Tensorflow Lite flatbuffers format. size:0  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1354]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/LoadModel.cpp(205): last checkpoint
unknown location(0): fatal error: in "TensorflowLiteParser/GetBufferCheckContents": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetBuffer.cpp(101): last checkpoint: "GetBufferCheckContents" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetBufferCheckEmpty": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetBuffer.cpp(109): last checkpoint: "GetBufferCheckEmpty" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetBufferCheckParseException": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetBuffer.cpp(119): last checkpoint: "GetBufferCheckParseException" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/EmptyNetworkHasNoInputsAndOutputs": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/InputOutputTensorNames.cpp(24): last checkpoint: "EmptyNetworkHasNoInputsAndOutputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/MissingTensorsThrowException": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/InputOutputTensorNames.cpp(51): last checkpoint
unknown location(0): fatal error: in "TensorflowLiteParser/InvalidTensorsThrowException": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/InputOutputTensorNames.cpp(74): last checkpoint
unknown location(0): fatal error: in "TensorflowLiteParser/GetValidInputOutputTensorNames": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/InputOutputTensorNames.cpp(120): last checkpoint: "GetValidInputOutputTensorNames" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/ThrowIfSubgraphIdInvalidForInOutNames": armnn::Exception: LoadNetwork failed while reading binary input
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/InputOutputTensorNames.cpp(129): last checkpoint: "ThrowIfSubgraphIdInvalidForInOutNames" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetEmptyInputTensorIds": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetTensorIds.cpp(92): last checkpoint: "GetEmptyInputTensorIds" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetEmptyOutputTensorIds": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetTensorIds.cpp(101): last checkpoint: "GetEmptyOutputTensorIds" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetInputTensorIds": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetTensorIds.cpp(110): last checkpoint: "GetInputTensorIds" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetOutputTensorIds": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetTensorIds.cpp(119): last checkpoint: "GetOutputTensorIds" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetInputTensorIdsInvalidSubGraph": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetTensorIds.cpp(138): last checkpoint: "GetInputTensorIdsInvalidSubGraph" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetOutputTensorIdsInvalidSubGraph": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetTensorIds.cpp(144): last checkpoint: "GetOutputTensorIdsInvalidSubGraph" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetInputTensorIdsInvalidOperator": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetTensorIds.cpp(150): last checkpoint: "GetInputTensorIdsInvalidOperator" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetOutputTensorIdsInvalidOperator": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetTensorIds.cpp(156): last checkpoint: "GetOutputTensorIdsInvalidOperator" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetEmptySubgraphInputs": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetSubgraphInputsOutputs.cpp(154): last checkpoint: "GetEmptySubgraphInputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetEmptySubgraphOutputs": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetSubgraphInputsOutputs.cpp(161): last checkpoint: "GetEmptySubgraphOutputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetSubgraphInputs": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetSubgraphInputsOutputs.cpp(168): last checkpoint: "GetSubgraphInputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetSubgraphOutputsSimpleQuantized": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetSubgraphInputsOutputs.cpp(178): last checkpoint: "GetSubgraphOutputsSimpleQuantized" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetSubgraphInputsEmptyMinMax": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetSubgraphInputsOutputs.cpp(188): last checkpoint: "GetSubgraphInputsEmptyMinMax" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetSubgraphOutputs": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetSubgraphInputsOutputs.cpp(198): last checkpoint: "GetSubgraphOutputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetSubgraphInputsInvalidSubgraph": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetSubgraphInputsOutputs.cpp(218): last checkpoint: "GetSubgraphInputsInvalidSubgraph" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetSubgraphOutputsInvalidSubgraph": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetSubgraphInputsOutputs.cpp(224): last checkpoint: "GetSubgraphOutputsInvalidSubgraph" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetEmptyInputs": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(153): last checkpoint: "GetEmptyInputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetEmptyOutputs": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(160): last checkpoint: "GetEmptyOutputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetInputs": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(167): last checkpoint: "GetInputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetOutputs": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(176): last checkpoint: "GetOutputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetInputsMultipleInputs": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(185): last checkpoint: "GetInputsMultipleInputs" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetOutputs2": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(196): last checkpoint: "GetOutputs2" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetInputsInvalidSubgraph": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(215): last checkpoint: "GetInputsInvalidSubgraph" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetOutputsInvalidSubgraph": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(221): last checkpoint: "GetOutputsInvalidSubgraph" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetInputsInvalidOperator": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(227): last checkpoint: "GetInputsInvalidOperator" entry.
unknown location(0): fatal error: in "TensorflowLiteParser/GetOutputsInvalidOperator": armnn::InvalidArgumentException: Invalid (null) binary content  at function LoadModelFromBinary [/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1345]
/home/xxx/armnn-devenv/armnn/src/armnnTfLiteParser/test/GetInputsOutputs.cpp(233): last checkpoint: "GetOutputsInvalidOperator" entry.

*** 71 failures are detected in the test module "UnitTests"

What's the problem?

**Comment by MatthewARM** [comment]
Hi @kwangchoon I think that it is failing to load the Tensorflow Lite schema file "schema.fbs", could you try copying it to the phone and setting the ARMNN_TF_LITE_SCHEMA_PATH environment variable to the full path to the schema.fbs file.

I'm looking in to a way to make this easier and less error prone.

**Comment by Surmeh** [comment]
Hi @kwangchoon, the guide for TensorFlow Lite is https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite. Please let us know if you have problems building ArmNN using it.

**Comment by kwangchoon** [comment]
The information you provided is a build method for x86 systems. I need a working build method for ARM.

**Comment by Surmeh** [comment]
Hi @kwangchoon, the guide is for native compilation on an Armv7-A or Armv8-A CPU, and optionally an Arm Mali GPU using the OpenCL driver. We currently don't have a guide same as BuildGuideAndroidNDK.md for TensorFlow Lite.

I hope this helps.

**Comment by MatthewARM** [comment]
Hi @kwangchoon you need the "schema.fbs" file when building the Tensorflow Lite Parser, and when running the unit tests it has to be available via the ARMNN_TF_LITE_SCHEMA_PATH environment variable.

I have committed https://review.mlplatform.org/#/c/ml/armnn/+/524/ to our development branch, which makes it unnecessary to set ARMNN_TF_LITE_SCHEMA_PATH or copy the file. This change will be part of our next release.

**Comment by kwangchoon** [comment]
Hi @Surmeh, your point is really helpful. In the next release, could you share a way to build with Android NDK. Native compilation is difficult to apply to Android phone.

Hi @MatthewARM , thank you. The next release is expected..

**Comment by mehreenjabeen** [comment]
Hi,
I have installed pyarmnn on rpi3 via cross-compilation  and now I am trying to run this example https://developer.arm.com/documentation/102470/0100/Running-the-application. However, i am getting this error 
RuntimeError: Buffer doesn't conform to the expected Tensorflow Lite flatbuffers format. size:130  at function LoadModelFromBinary

Any pointer on this?
