### ISSUE TITLE
Cross-compile armNN and use mali gpu on the arm board, caffe cpu_only? 

### ISSUE THREAD

**Issue by helloyongyang** [ARM-software/armnn#122]
I want to Cross-compile armNN and use mali gpu on the arm board. In my caffe makefile, do I need comment cpu_only := 1 to use mali gpu? 

# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

I knew that I should use "scons opencl=1 embed_kernels=1" to enable the cpu on arm. But I want to know how should I set "CPU_ONLY := " in my caffe makeflie.
Thanks!

**Comment by Surmeh** [comment]
Hi @helloyongyang, please follow the [BuildGuideCrossCompilation.md](https://github.com/ARM-software/armnn/blob/branches/armnn_18_11/BuildGuideCrossCompilation.md) guide to cross-compile ArmNN for arm64.

If you're compiling using make, no changes are required to the makefile. Please refer "http://caffe.berkeleyvision.org/installation.html#compilation". 

For building compute library for GPU, please set it to the following: neon=0 opencl=1 embed_kernels=1.
And when building ArmNN, set it to -DARMCOMPUTENEON=0  -DARMCOMPUTECL=1

I hope this helps, good luck.
Surabhi

**Comment by helloyongyang** [comment]
Thanks! @Surmeh 

the BuildGuideCrossCompilation.md guide say:

Adjust Makefile.config as necessary for your environment, for example:
  #CPU only version:
  CPU_ONLY := 1

If I need to build compute library for OpenCL, is CPU_ONLY also =1 ?
Sorry for disturbing you.

**Comment by Surmeh** [comment]
Hi @helloyongyang, to build Compute Library for OpenCL, you need to comment out CPU_ONLY =1.

Hope this helps.
