### ISSUE TITLE
Unable to run script armnn/scripts/get_compute_library.sh

### ISSUE THREAD

**Issue by vinayonchip** [ARM-software/armnn#127]
Inorder to complete the requirement of Complete Library based on the following NOTE I get the following error. How to solve it.

**Note** : Arm NN needs to be built against a particular version of ARM's Compute Library. The get_compute_library.sh in the scripts subdirectory will clone the compute library from the review.mlplatform.org github repository into a directory alongside armnn named 'clframework' and checkouts the correct revision.

Error:
./get_compute_library.sh 
setting GITHUB_USERNAME: vinay use -g command line option to change
+++ Cloning clframework
Cloning into 'clframework'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning CL Framework failed
+++ Command exited with code 128. Please fix the above errors and re-run

**Comment by MatthewARM** [comment]
Hi @vinayonchip I can see what is going wrong here, the script requires that you have an account on our Gerrit server.  That seems unnecessary, I'll see if I can make it use an anonymous checkout.

**Comment by MatthewARM** [comment]
Hi @vinar would you be able to try this patch to see if it fixes your problem?

````
diff --git a/scripts/get_compute_library.sh b/scripts/get_compute_library.sh
index 6385011..e93f9f3 100755
--- a/scripts/get_compute_library.sh
+++ b/scripts/get_compute_library.sh
@@ -56,7 +56,7 @@ fi
 
 if [ ! -d clframework ]; then
 echo "+++ Cloning clframework"
-  git clone ssh://$GITHUB_USERNAME@review.mlplatform.org:29418/ml/ComputeLibrary clframework
+  git clone https://review.mlplatform.org/ml/ComputeLibrary clframework
   AssertZeroExitCode "Cloning CL Framework failed"
 fi
 pushd clframework > /dev/null
@@ -65,15 +65,15 @@ pushd clframework > /dev/null
 
 # For pinnning to a ref use this:
 # CLFRAMEWORKREVISION="branches/arm_compute_18_11" # Release 18.11
-# git fetch ssh://$GITHUB_USERNAME@review.mlplatform.org:29418/ml/ComputeLibrary $CLFRAMEWORKREVISION && git checkout FETCH_HEAD
+# git fetch  https://review.mlplatform.org/ml/ComputeLibrary $CLFRAMEWORKREVISION && git checkout FETCH_HEAD
 
 # For pinning to a revision use this:
 CLFRAMEWORKREVISION="e413d255b18fad1553bd3550a98f707c9c6e8aec" # commit on master after the fix for NEGEMMConvolutionLayer
-git fetch ssh://$GITHUB_USERNAME@review.mlplatform.org:29418/ml/ComputeLibrary && git checkout ${CLFRAMEWORKREVISION}
+git fetch https://review.mlplatform.org/ml/ComputeLibrary && git checkout ${CLFRAMEWORKREVISION}
 AssertZeroExitCode
 
 # Set commit hook so we can submit reviews to gerrit
-scp -p -P 29418 $GITHUB_USERNAME@review.mlplatform.org:hooks/commit-msg .git/hooks/
+(curl -Lo `git rev-parse --git-dir`/hooks/commit-msg https://review.mlplatform.org/tools/hooks/commit-msg; chmod +x `git rev-parse --git-dir`/hooks/commit-msg)
 AssertZeroExitCode
 
 popd > /dev/null # out of clframework
````

**Comment by vinayonchip** [comment]
Thanks @MatthewARM It worked ...! Hope this solves other build issues.
