### ISSUE TITLE
How can I resize inputTensor with TfLiteParser?

### ISSUE THREAD

**Issue by mcdman007** [ARM-software/armnn#128]
Hi, I am trying to apply armnn + TfLiteParser.
Our system is running TfLite and uses the resizeInputTensor function to reduce the inputTensor in TfLite.
I want to resize the input tensor after reading the same tflite model from armnnTfLiteParser, but I have not found a way to do it.
Please let me know if there is a possible way.

**Comment by MatthewARM** [comment]
Hi sorry @mcdman007 we don't have this feature yet. I'll note your interest in it for the road map.

**Comment by mcdman007** [comment]
Hi @MatteoArm. Thank you for your reply.

**Comment by choice17** [comment]
Hi, I am implementing mtcnn in armnn where pnet needs dynamic changing of input tensor shape, any update about the resizeInputTensor similar to tensorflowlite Interpreter::ResizeInputTensor?

**Comment by MatthewARM** [comment]
Hi @choice17 it's proving hard to implement as the memory layout is connected to lots of things in both Arm NN and Compute Library. We are working on it but it's not going to be soon.

**Comment by jokerspy** [comment]
Hi, same here trying to use model with dynamic input shape. Hope to see this feature supported soon. At the mean time, is there any workaround I could use to apply this kind of models with ArmNN for now? Thanks
