### ISSUE TITLE
Deeplab

### ISSUE THREAD

**Issue by ilous12** [ARM-software/armnn#132]
When I tried to run deeplabv3+, I saw below. How can I fix on armnn?

> terminating with uncaught exception of type armnn::ParseException: Node 'sub_2' has Control Input '^Assert/Assert' for input #2 which is unsupported.  at function GetTfInputNodes [/home/mvoip/armnn-devenv/armnn/src/armnnTfParser/TfParser.cpp:565]

**Comment by MatthewARM** [comment]
Hi @ilous12 the master development branch of ArmNN (see https://review.mlplatform.org/#/admin/projects/ml/armnn) has this patch:  https://review.mlplatform.org/#/c/ml/armnn/+/435/ which should fix that particular error message, however it is likely that something else in the model will be unsupported by ArmNN. 

You can read the latest documentation for what is supported in the Tensorflow parser:  https://git.mlplatform.org/ml/armnn.git/about/src/armnnTfParser/TensorFlowSupport.md

**Comment by ilous12** [comment]
Thanks @MatthewARM 
I saw your commit.
I expected to build "https://review.mlplatform.org/#/admin/projects/ml/armnn", but failed

Can you check your dev-master build status? thanks.

**Comment by MatthewARM** [comment]
Hi @ilous12 you will also need a development version of Compute Library, which you can get by running scripts/get_compute_library.sh (which will put it in a directory called clframework in your current working directory.

Alternatively check inside get_comptue_library.sh at line 71 to find the git hash of Compute Library that you need.

**Comment by MatthewARM** [comment]
Closing this ticket as I believe the discussion has moved to Issue #133. Please reopen if I am mistaken.
