### ISSUE TITLE
UnitTest report CL runtime error

### ISSUE THREAD

**Issue by albert18711** [ARM-software/armnn#136]
Hello~

I'm trying to compile ArmNN on JUNO r2 (Armv8-a) right now.

Following the instruction here: https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite

I enable the opencl and embed_kernel option while building ComputeLibrary, but got a lot of CL runtime error when running UnitTest. Here are some of them:

Running 912 test cases...
unknown location(0): fatal error: in "EndToEnd/ErrorOnLoadNetwork": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -1001
/home/dcslab/armnn-tflite/armnn/src/armnn/test/EndToEndTest.cpp(50): last checkpoint: "ErrorOnLoadNetwork" entry.
unknown location(0): fatal error: in "Profiler/RuntimeLoadNetwork": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -1001

I have no idea why i get such error. Please give me some help.

**Comment by MatthewARM** [comment]
Hi @albert18711 possibly there is something wrong with OpenCL itself. Could you send us the output of `clinfo`?

Many thanks,
Matthew

**Comment by albert18711** [comment]
i get the message below
`Number of platforms 0`

i believe Mali GPU is included in ARM v8-A...
Does that mean i have to install related drivers? Is there any tutorial for that?

Thanks for the reply

**Comment by MatthewARM** [comment]
hi @albert18711 there are Mali drivers for Juno here: https://developer.arm.com/products/software/mali-drivers I believe there are also some available via Debian packages, but I've not tried them.

You may be able to get support for this from the Juno community forums.

All the best,
Matthew

**Comment by MatthewARM** [comment]
Hi @albert18711 I hope you managed to get this working. I'll close this issue now but please get back in touch if you still have problems.
