### ISSUE TITLE
Unsupported operation Neg in tensorflow::GraphDef

### ISSUE THREAD

**Issue by Cola-Code** [ARM-software/armnn#137]
So, how could i add this support? Is there any plan for support of the ops such as Abs and Sub?

**Comment by MatthewARM** [comment]
Hi @Cola-Code,

Sub has been added in the latest master code at https://review.mlplatform.org.

I suggest you try the latest master code first, then follow the pattern of existing operators to add extra ones. We'll happily discuss with you any tricky bits, and we are currently improving the documentation for contributors at: https://www.mlplatform.org/contributing/

I've just checked our plans and currently Neg and Abs are not prioritised very high. Can I ask what sort of model you are using? Or a little more about your use case?

Many thanks,
Matthew

**Comment by Cola-Code** [comment]
I want to deploy a tensorflow MTCNN model on ARM NN.And the modes i used has Abs and Sub.

Does the code can be got free?

**Comment by MatthewARM** [comment]
Good luck!
