### ISSUE TITLE
Unsupported operation StridedSlice in tensorflow::GraphDef TfParser.cpp:3221

### ISSUE THREAD

**Issue by 1loop** [ARM-software/armnn#138]
Working with the armnn & ComputeLibrary dev master code (mlplatform.org)

Looks like StridedSlice is implemented in armnn/InternalTypes.cpp

I'm also wondering whether any of the other following ops are not yet supported in the TF parser or InternalTypes:

```
Add
BiasAdd
ConcatV2
Const
Conv2D
FusedBatchNorm
Identity
LeakyRelu
Mul
Pad
Placeholder
ResizeNearestNeighbor
Shape
StridedSlice
```

**Comment by MatthewARM** [comment]
Hi @1loop there are several operators that are available through the ArmNN API, but are not yet understood if you use the ArmNN Tensorflow Parser. The Tensorflow Parser list can be found here: 

https://github.com/ARM-software/armnn/blob/branches/armnn_18_11/src/armnnTfParser/TensorFlowSupport.md

**Comment by 1loop** [comment]
Hi @MatthewARM thanks for replying.
I've already consulted the documentation files, 
it might be a bit outdated (definitely outdated vs the dev branch but that's fair enough).
At the moment it seems like LeakyRelu, ResizeNearestNeighbor and StridedSlice
are the ops that are either not supported by the TFParser or not implemented in ArmCL.

We can change the LeakyRelu, ResizeNearestNeighbor ops in our network architecture (but we'd rather not) however the StridedSlice op is kind of necessary.

We also have the option of using an ONNX parser, would you recommend that one instead? Asking re the dev branches and future implementation directions :)

**Comment by MatthewARM** [comment]
Hi @1loop I would say that the ONNX parser is less mature than the Tensorflow parser, but that ONNX models seem to usually be a bit simpler than the corresponding Tensorflow model, if that makes sense.

In your case I think that the Tensorflow parser is right now close to what you need. We've got no work scheduled to add StridedSlice to the Tensorflow parser (we added it for Android NNAPI) but we would happily accept patches that add it.

If you're using the master branch, the corresponding docs are here, they should be up to date: https://git.mlplatform.org/ml/armnn.git/about/src/armnnTfParser/TensorFlowSupport.md

**Comment by Surmeh** [comment]
Hi @1loop, I hope all your questions have been answered, so closing this ticket. Feel free to open another one if you have any more questions.

**Comment by 009deep** [comment]
@1loop  I am facing the same issue. DO you know whether `stridedslice` is related to particaular version of tensorflow? Did you find solution?
