### ISSUE TITLE
Quantized vs float comparison in TfLite MobileNet V1

### ISSUE THREAD

**Issue by liviolima80** [ARM-software/armnn#143]
Dear all,
I performed some benchmarks comparing quantized models versus float models for different versions of  MobileNet V1 TfLite model. The hardware I used is a Freescale IMX6Q board with 4 cortex A9 @ 1 GHz. I used the master branch of armnn and ComputeLibrary downloaded from review.mlplatform.org and compiled with only NEON aceleration. I downloaded all the models from the official TensorflowLite repository. 

The table below shows the results, where the second column is the processing time for quantized models in ms, the third column is the processing time for float models in ms and the last column is the time boost factor of the quantized model compared to the float one.

The expectation was that the quantized models run faster than the float models, but instead is the opposite. What is the reason of these results? Are the results reasonable?

Thanks   

MobileNet_v1_1.0_224 | 990 | 406 | 2,43842365
MobileNet_v1_1.0_192 | 720 | 263 | 2,73764259
MobileNet_v1_1.0_160 | 527 | 204 | 2,58333333
MobileNet_v1_1.0_128 | 262 | 142 | 1,84507042
MobileNet_v1_0.75_224 | 768 | 262 | 2,93129771
MobileNet_v1_0.75_192 | 554 | 173 | 3,20231214
MobileNet_v1_0.75_160 | 405 | 131 | 3,09160305
MobileNet_v1_0.75_128 | 216 | 91 | 2,37362637
MobileNet_v1_0.50_224 | 442 | 144 | 3,06944444
MobileNet_v1_0.50_192 | 324 | 98 | 3,30612245
MobileNet_v1_0.50_160 | 232 | 74 | 3,13513514
MobileNet_v1_0.50_128 | 119 | 57 | 2,0877193
MobileNet_v1_0.25_224 | 219 | 64 | 3,421875
MobileNet_v1_0.25_192 | 162 | 46 | 3,52173913
MobileNet_v1_0.25_160 | 117 | 36 | 3,25
MobileNet_v1_0.25_128 | 63 | 26 | 2,42307692

**Comment by GeorgeARM** [comment]
Hello @liviolima80,

Suppose this is for armv7 architecture. That should explain the performance difference as we don't have optimized assembly kernels for quantized kernels for armv7 while we do for fp32. We are planning to include some in the near future.
Hope this helps.

**Comment by depthwise** [comment]
Likewise, I'm unable to obtain any speedup on quantized TFLite MobileNet v1 1.0 on aarch64, running on Odroid C2. Quantized model is slower, though by nowhere near as much. For comparison, TFLite itself cranks out 15.44 inferences per second on this board, compared to ARM NN's 9.96 inferences per second in quantized mode. I'm kind of wondering if I'm "holding it wrong".

**Comment by MatthewARM** [comment]
@depthwise every board is different, but I'm getting figures around 70-80ms per inference for Mobilenet v1 1.0 224, with 8-bit quantized format, for 4x A53 @1.8Ghz in the latest master of ArmNN.

The quantized model is slightly faster than the floating point model for me, but not by much. The Cortex-A53 has pretty good floating-point support, and lacks the 8-bit dot-product instruction that you get on recent big CPUs, also Mobilenet is not memory-bound anywhere. Slightly faster but not massively so would be expected in this case.

Hope this helps,
Matthew

**Comment by depthwise** [comment]
Thanks for the confirmation. There's always a risk that I'm "holding it wrong", but it seems like your own testing confirms my suspicions.

The good news (for ARM) is, there seems to be some headroom remaining then. TFLite is not known for highly optimized implementations of anything, and they manage to be substantially faster on the same exact model on the same exact board, even though they're _way_ slower on fp32. Knowing what you know about ARM architecture, you folks gotta be able to beat them. :1st_place_medal: 

P.S. I'm also using the tip-of-tree version of ARM NN from cgit repo.

**Comment by MatthewARM** [comment]
OK thanks @depthwise I'll pass your feedback on internally. If Tensorflow Lite can hit 15.44 inferences / second (about 65ms?) then there must be something that we can do to at least match it.

**Comment by MatthewARM** [comment]
I've just checked and there will be work on int8 performance for CPU in the near future.

**Comment by alexcohn** [comment]
My experiment on a moderate ARM64 device (Xiaomi A2 phone) shows around 200ms for float model **mobilenet_v1_1.0_224.tflite**, and 130ms for same, converted with `--post_training_quantize`. Enabling of NNAPI reverses the order: 120ms for float, 130ms for quantized.

What is more puzzling, same model with quantized input works slower: 185ms (it fails with NNAPI, but that's a different story). This is the *convert* command:

    tflite_convert --output_file=mobilenet_v1_1.0_224_qinput.tflite --graph_def_file=mobilenet_v1_1.0_224_frozen.pb --inference_input_type=QUANTIZED_UINT8 --input_arrays=input --output_arrays=MobilenetV1/Predictions/Reshape_1 --std_dev_values=255 --mean_values=0 --default_ranges_min=0 --default_ranges_max=7
