### ISSUE TITLE
Can I load a network once and and then run it manytimes?

### ISSUE THREAD

**Issue by Cola-Code** [ARM-software/armnn#144]
I need to run a network many times for different inputs. Can i do like the below?

input = malloc(size);
output = malloc(size);
tensor_in = Construct tensor from (input_tensor_name, input.data)
tensor_out = Construct tensor from (output_tensor_name, output.data)
create and LoadNetwork
for (loop = 0; loop < input_cnt; loop++)
{
      input.data = <copy from input_file[loop]>;
      EnqueueWorkload;
      Save Output;
}

**Comment by MatthewARM** [comment]
Yes, that's the right way to do it.

Hope that helps,
Matthew
