### ISSUE TITLE
MobileNetSsd Tensorflow Models

### ISSUE THREAD

**Issue by liviolima80** [ARM-software/armnn#146]
Hi all,
I'd like to know if anyone succesfully run MobileNetSsd with Tensorflow models using armnnTfLiteParser or armnnTfParser. 

Last version of armnn has an example for running a TfLite MobileNetSsd model. I tried to test two different pre converted models from here
- https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_ssd_tflite_v1.zip
- https://storage.googleapis.com/download.tensorflow.org/models/tflite/pets_ssd_mobilenet_v1_0.75_quant_2018_06_29.zip

but both have the same error

Failed to parse operator #63 within subgraph #0 error: Custom options for op: 5 is not supported. It has 217 bytes of custom options.  at function CreateNetworkFromModel [....../armnn/src/armnnTfLiteParser/TfLiteParser.cpp:551]

I also tried to run the same example using Tf parser with frozen graph model downloaded from official Tensorflow repository (http://download.tensorflow.org/models/object_detection/) but i have the following error:

Armnn Error: Cycle detected in graph  at function LoadGraphDef [..../armnn/src/armnnTfParser/TfParser.cpp:3274]

Anyone has similar problems?

**Comment by MatthewARM** [comment]
Hi @liviolima80 we are in the process of adding support for Tensorflow Lite MobileNet-SSD. ArmNN Version 18.11 that you can get on Github does not support the Detection Postprocess layer (which is probably operator 63 from the tflite file). The latest master code is always at https://review.mlplatform.org/#/admin/projects/ml/armnn and when it is passing all of our tests for the new features we will push it to Github.

The Tensorflow version of the model uses loops (Tensorflow flow control operations) which we do not yet support.

Hope this helps,
Matthew

**Comment by liviolima80** [comment]
Thank you @MatthewARM ,
do you have an idea of when the next release of Armnn will be available on github?
