### ISSUE TITLE
tflite::TensorType_INT64 not supported?

### ISSUE THREAD

**Issue by ens-lg4** [ARM-software/armnn#150]
When trying to load ResNet50 v.1.5 model into ArmNN using TFlite parser I was greeted with the following:

```
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unsupported data type 4 = INT64 for tensor: ArgMax.  at function ToTensorInfo [.../src/armnnTfLiteParser/TfLiteParser.cpp:317]
```

Checking the `enum class DataType` from file `include/armnn/Types.hpp` confirmed that this type is, indeed, not supported by the code I'm looking at (I'm running the development version of ArmNN from `https://review.mlplatform.org/ml/armnn`).

This specific ArgMax doesn't have to be INT64 (there are only 1001 classes in the previous layer of this model), so it probably can be hacked around (the parser reading long ints, truncating them and returning short ones?).
However there may be models around for which INT64 is a requirement and they just won't work without proper INT64 support.

**Comment by MatthewARM** [comment]
Hi @ens-lg4 thanks for this. I'll put it on the roadmap and in the meantime if you want to look into it your suggestion of truncating to 32-bit int seems good.

**Comment by psyhtest** [comment]
Note there is a new way to reproduce it with our [ArmNN Docker image for MLPerf image classification models](https://github.com/ARM-software/armnn-mlperf/blob/master/docker/image-classification-armnn-tflite.debian-9/README.md):
```
$ docker run --rm ctuning/image-classification-armnn-tflite.debian-9 \
"ck run armnn-mlperf:program:image-classification-armnn-tflite --dep_add_tags.weights=resnet,with-argmax"
...
Loading graph...                             
terminate called after throwing an instance of 'armnn::ParseException'     
  what():  Unsupported data type 4 = INT64 for tensor: ArgMax.  at function ToTensorInfo [/home/dvdt/CK_TOOLS/lib-armnn-19.05-gcc-6.3.0-rel.19.05-tflite-linux-64/src/src/armnnTfLiteParser/TfLiteParser.cpp
:321]
./tmp-_upjwrfe.sh: line 44:    92 Aborted                 (core dumped) ./classification
```

**Comment by matthewsloyanARM** [comment]
Hi @ens-lg4, 

I am closing this issue as INT64 support has been added to the `enum class DataType` and to the TFLite Parser. It was added in this patch d4619e28a4cde423d5b4086a98c31f97b52a68d7.

If you have any questions feel free to reopen this ticket or create a new one. Thank you!

Kind regards,

Matthew
