### ISSUE TITLE
ARM NN Converter Tool Usage

### ISSUE THREAD

**Issue by Azutoz** [ARM-software/armnn#151]
Hi
I am trying to convert mobilenet_v1.pb using the ArmNNConverter tool provided in the new release.
I was able to generate an output. 
Is there any documentation for the API to be used with this output? And how do I verify if the output generated output is valid?
Thankyou.

**Comment by FinnWilliamsArm** [comment]
Hello  @Azutoz 
You should be able to run the outputted armnn file using Execute Network. You can then compare the output of the armnn network with Execute Network’s output of the original network.

**Comment by MatthewARM** [comment]
To add to Finn's answer, the API you can use to load the model is under `include/armnnDeserializer` and some Doxygen documentation is inline with the definitions.

Hope that helps,
Matthew

**Comment by Azutoz** [comment]
Thankyou for your feedback @MatthewARM & @FinnWilliamsArm 
1. I am not able to run the Execute Network due to this error :
flatbuffers::Vector::return_type flatbuffers::Vector<flatbuffers::Offset<armnnSerializer::AnyLayer> >::Get(flatbuffers::uoffset_t) const [T = flatbuffers::Offset<armnnSerializer::AnyLayer>]: assertion "i < size()" failed
Aborted

The command that I am using is as follows:
./ExecuteNetwork -f tensorflow-binary -m mobilenet_v1_1.0_224_frozen.pb -i input -o MobilenetV1/Predictions/Reshape_1 -d imageArray.txt -s 1,224,224,3 -y int -z int

Can you please guide me on how to use this executable?

2. Also, right now I am building armnn for aarch64, and hence the ArmNNConverter Tool also for aarch64, was it meant to be used this way, or the right way to take advantage of it is by using it on x86 PC ?
If yes, then how?

Thankyou again

**Comment by MatthewARM** [comment]
Hi @Azutoz you can run the converter tool wherever you like. x86 PC or on an Arm device should both work the same way.

I don't know why the model would fail to parse, and it's a bit weird that it would fail an Assertion rather than properly reporting an error. I'll have to get back to you on that one.

**Comment by MatthewARM** [comment]
Hi @Azutoz 
I just noticed you have `./ExecuteNetwork -f tensorflow-binary -m mobilenet_v1_1.0_224_frozen.pb -i input -o MobilenetV1/Predictions/Reshape_1 -d imageArray.txt -s 1,224,224,3 -y int -z int`

Which is loading  a *tensorfow-binary* file, but then you get:

`flatbuffers::Vector::return_type flatbuffers::Vector<flatbuffers::OffsetarmnnSerializer::AnyLayer >::Get(flatbuffers::uoffset_t) const [T = flatbuffers::OffsetarmnnSerializer::AnyLayer]: assertion "i < size()" failed
Aborted`

Which is an error from the *armnn-binary* deserializer. Can you confirm that's exactly what you're seeing? As it might indicate that ExecuteNetwork is trying to use the wrong file reader.

**Comment by Azutoz** [comment]
You're right
The command I'm using is 
./ExecuteNetwork -f armnn-binary -m mobilenet.armnn -i input -o MobilenetV1/Predictions/Reshape_1 -d imageArray.txt -s 1,224,224,3
But, I'm STILL getting that error.

Thankyou for letting me know about x86 build, I will try that.

Let me know if there is a sample model that we can run ArmNNConverter and ExecuteNetwork on.
Thankyou.

**Comment by TelmoARM** [comment]
Hi @Azutoz ,

I wasn't able to reproduce this issue. I've tried it with aarch64 using the latest code from mlplatform and on a x86 build with the 19.02 Release code. 

I was able to:
-  run mobilenet_v1_1.0_224_frozen.pb through ExecuteNetwork as a tensorflow-binary file format
-  convert the mobilenet_v1_1.0_224_frozen.pb using ArmnnConverter tool into a .armnn file
-  run the converted .armnn file through ExecuteNetwork as a .armnn-binary file format

**Comment by MatthewARM** [comment]
Closing this issue based on @TelmoARM's comment. Please reopen it @Azutoz if you are still seeing problems with the latest release.

**Comment by xiaotongnii** [comment]
./ArmnnConverter -f onnx-binary -m v1.onnx -i input -s 1,3,224,224 -o output -p v1.armnn
