### ISSUE TITLE
error while building armnn with serializer support using Android NDK

### ISSUE THREAD

**Issue by kletechuni** [ARM-software/armnn#152]
Hi
To enable the serializer support in armnn , 
should we build the flatbuffer with NDK cross compiler or with normal gcc or clang compiler ?

I tried building the armnn with serializer support by building the flatbuffer library using android ndk
But i got the below error,

```
[ 66%] Generating src/armnnSerializer/ArmnnSchema_generated.h
/home/armnn/flatbuffers/flatc: 1: /home/armnn/flatbuffers/flatc: Syntax error: word unexpected (expecting ")")
make[2]: *** [src/armnnSerializer/ArmnnSchema_generated.h] Error 2
make[1]: *** [CMakeFiles/armnnSerializer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I used below command to build the armnn

```
CXX=aarch64-linux-android-clang++ \
 CC=aarch64-linux-android-clang \
 CXX_FLAGS="-fPIE -fPIC" \
 cmake .. \
  -DCMAKE_SYSTEM_NAME=Android \
  -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
  -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$HOME/armnn-devenv/toolchains/aarch64-android-r17b/ \
  -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
  -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
  -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
  -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
  -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 \
  -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1 \
  -BUILD_ARMNN_SERIALIZER=1\
  -FLATC_DIR=$HOME/flatbuffers \
  -FLATBUFFERS_ROOT=$HOME/flatbuffers \
  -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/
```

**Comment by MatthewARM** [comment]
Hi @kletechuni I've not seen that error before. It's coming from the flatbuffers schema compiler. Which version of flatbuffers are you using?

**Comment by MatthewARM** [comment]
Hi @kletechuni possibly this is an error in the latest development code of flatbuffers, can you retry with flatbuffers v1.10.0?

**Comment by praisonjoshua** [comment]
Ok we'll look into it and get back.

**Comment by VinayKarnam** [comment]
Hi @MatthewARM 
We tried building with flatbuffer v1.10.0 but still we are getting the same error. 
should we build the flatbuffer with NDK cross compiler or with normal gcc or clang compiler ?
We built the flatbuffer with android NDK cross compiler.

**Comment by MatthewARM** [comment]
Hi @VinayKarnam, in your case `/home/armnn/flatbuffers/flatc` should be built for the **host** (which I guess is x86_64). You will also need ``libflatbuffers.a`` built for the **target** in order to successfully link the  serialiser library.

If it's trying to run an android binary version of ``flatc`` during the build, that would explain why it's not working. But it doesn't explain why it's such a weird error message. :-(

**Comment by VinayKarnam** [comment]
Ok thank you very much
