### ISSUE TITLE
some questions about Unit Tests

### ISSUE THREAD

**Issue by georgeokelly** [ARM-software/armnn#153]
Hi
When I try to run the ArmNN unit tests on an Android device, the `adb push` command doesn't work like:

```
glow@ubuntu:~/armnn-devenv/armnn/build$ adb push libarmnnTfParser.so /data/local/tmp/

```
It has no output for a while so I have to stop it and the device is connected. 
```
glow@ubuntu:~$ adb devices
List of devices attached 
62ec1a6	device
```
Besides, I also try to run tests with cross-compiled one on **Termux**, a terminal emulator and Linux environment for Android. But `./UnitTests` cannot be executed.

How could I solve these issues so that I could know the performance of Armnn on my devices?

**Comment by MatthewARM** [comment]
Hi @georgeokelly does `adb push` work to push anything at all? What version of adb are you using and what version of Android does your device have?

All the best,
Matthew

**Comment by georgeokelly** [comment]
Hi, I find the `adb push` can't work on this device at all. 
Thank you for your reply.
