### ISSUE TITLE
Is transpose operation in onnx supported?

### ISSUE THREAD

**Issue by peteryang1** [ARM-software/armnn#154]
I found the onnx parser cannot parse transpose op, it seems the armnn backend doesn't support this operation also.

Is there any chance supporting this op or can I found a way to deal with it in current backend?

Thanks!

**Comment by MatthewARM** [comment]
Hi @peteryang1 did you find a workaround? It would also be useful to know what kind of model you need Transpose for, if you can provide that information for our roadmap.

All the best,
Matthew

**Comment by peteryang1** [comment]
I added a parser to onnx parser, using the permute layer to parse the transpose node in onnx. It seems fine when I tested it.
thanks for the help.
