### ISSUE TITLE
Error while building armnn with TfLite on Raspberry, Ubuntu 16.04

### ISSUE THREAD

**Issue by damiangajewski** [ARM-software/armnn#158]
I've got an error while building armnn on Raspberry. I've done everything like in this instruction: https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite/single-page

But while compiling armnn I have an error:
[ 69%] Building CXX object CMakeFiles/armnnTfParser.dir/home/ubuntu/armnn-tflite/tensorflow-protobuf/tensorflow/core/util/test_log.pb.cc.o
[ 69%] Linking CXX shared library libarmnnTfParser.so
[ 69%] Built target armnnTfParser
[ 69%] Building CXX object CMakeFiles/armnnTfLiteParser.dir/src/armnnTfLiteParser/TfLiteParser.cpp.o
[ 69%] Linking CXX shared library libarmnnTfLiteParser.so

usr/bin/ld: /home/ubuntu/armnn-tflite/flatbuffers/libflatbuffers.a(util.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN11flatbuffers11LoadFileRawEPKcbPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/ubuntu/armnn-tflite/flatbuffers/libflatbuffers.a(util.cpp.o): In function `flatbuffers::SetLoadFileFunction(bool (*)(char const*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*))':
util.cpp:(.text+0xa78): dangerous relocation: unsupported relocation
/usr/bin/ld: /home/ubuntu/armnn-tflite/flatbuffers/libflatbuffers.a(util.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN11flatbuffers13FileExistsRawEPKc' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/ubuntu/armnn-tflite/flatbuffers/libflatbuffers.a(util.cpp.o): In function `flatbuffers::SetFileExistsFunction(bool (*)(char const*))':
util.cpp:(.text+0xaa4): dangerous relocation: unsupported relocation
/usr/bin/ld: /home/ubuntu/armnn-tflite/flatbuffers/libflatbuffers.a(util.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN11flatbuffers13ClassicLocaleD1Ev' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/ubuntu/armnn-tflite/flatbuffers/libflatbuffers.a(util.cpp.o): In function `_GLOBAL__sub_I__ZN11flatbuffers13FileExistsRawEPKc':
util.cpp:(.text.startup+0x24): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
CMakeFiles/armnnTfLiteParser.dir/build.make:106: recipe for target 'libarmnnTfLiteParser.so' failed
make[2]: *** [libarmnnTfLiteParser.so] Error 1
CMakeFiles/Makefile2:175: recipe for target 'CMakeFiles/armnnTfLiteParser.dir/all' failed
make[1]: *** [CMakeFiles/armnnTfLiteParser.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I've also tried to add flags to cmake:
CXX_FLAGS="-fPIE -fPIC" cmake .. -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build -DBOOST_ROOT=$BASEDIR/boost -DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf -DBUILD_TF_PARSER=1 -DPROTOBUF_ROOT=$BASEDIR/protobuf-host -DBUILD_TF_LITE_PARSER=1 -DTF_LITE_GENERATED_PATH=$BASEDIR/tensorflow/tensorflow/lite/schema -DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers -DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers/libflatbuffers.a -DARMCOMPUTENEON=1

But result was same. Please help me. Thanks.

**Comment by damiangajewski** [comment]
Ok I've solved it by adding cxx flags to flatbuffers compilation.

**Comment by MatthewARM** [comment]
Thanks @damiangajewski was the documentation wrong? Do we need to fix something?

**Comment by romrayster** [comment]
@MatthewARM : the documentation on the [arm page](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite/single-page ) is not fully correct: 
The right command is for building the flatbuffers library is: 
` cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fPIC" ..`
as mentioned [here.](https://github.com/ARM-software/armnn/issues/171#issuecomment-483176706)

In the official arm documentation, the fPIC flag is missing which causes an relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol ... error
