### ISSUE TITLE
ArmNNConverter Tool Verification

### ISSUE THREAD

**Issue by Azutoz** [ARM-software/armnn#159]
Hi,
I'm facing this issue while trying to run ExecuteNetwork on an armnn-binary format model which I got as an output from running ArmNNConverter on mobilenet.pb.
This is the error I am getting:
flatbuffers::Vector::return_type flatbuffers::Vector<flatbuffers::OffsetarmnnSerializer::AnyLayer >::Get(flatbuffers::uoffset_t) const [T = flatbuffers::OffsetarmnnSerializer::AnyLayer]: assertion "i < size()" failed
Aborted
The command that I am using is as follows:
./ExecuteNetwork -f armnn-binary -m mobilenet.armnn -i input -o MobilenetV1/Predictions/Reshape_1 -d imageArray.txt -s 1,224,224,3 

Can you please guide me on how to use this executable?

I have a few more doubts regarding the ArmNNConverter Tool
1. Right now I am building armnn for aarch64, and hence the ArmNNConverter Tool also for aarch64, was it meant to be used this way, or the right way to take advantage of it is by using it on x86 PC ?
If yes, then how?
2. Is there any sample model in armnn-format that you provide to run & verify the ArmNNConverter? Because a lot of the models are still not supported by the converter(Deserializer), it would be helpful if we had a sample model that we could use to understand this converter.

PLEASE provide some guidance for all of the above questions.
Thankyou

**Comment by MatthewARM** [comment]
Hi @Azutoz I see that this is the same question as in #151, I hope we can help you on that thread.
