### ISSUE TITLE
Porting Error (S9/Mate-10)

### ISSUE THREAD

**Issue by zesty4** [ARM-software/armnn#16]
I am testing your ARMNN API on a galaxy s9 and a Mate-10 smartphone.
However, when I run the Unitests program, the following error occurs.

Running 226 test cases ...
Invalid address 0x7E7B96E920 passed to free: value not allocated
Aborted

The current Android MALI-G7X series
S9, MATE-10 DRIVER has not been updated?

Thank you

**Comment by MatthewARM** [comment]
Hi @zesty4 thanks for reporting this, we'll look into it.

To help us diagnose the problem, what options have you used when building ArmNN? Which modules have you built, out of Compute Library OpenCL, Compute Library NEON, ArmNN Tensorflow Parser, and ArmNN Caffe Parser?

Many thanks,
Matthew

**Comment by zesty4** [comment]
Hi Matthew ,
I used the ndk16b build version,
In version arm_compute_library_18.05, I gave the CAFFE_PARSER option.
arm_compute_library has tested neon, neon + cl, and cl versions, but has seen errors in the last posting message.
However, we have succeeded Unitests on the hikey-960 board and are conducting the yolo-> caffe model convert.

If you check the above,
Thank you.

**Comment by zesty4** [comment]
Hi Surabhi, 

Quick response Thank you.
The way you told me is similar to the builder tree I did.
However, the ACL library uses a prebuilt version, and the suspicion is the boost part, and I will inform you by testing again (S9 / MATE) with the method that I gave.

**Comment by pcub** [comment]
I am following instructions given in https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md by compiling armnn with android-ndk16b
when start compiling:

> -- Looking for valgrind/memcheck.h
> -- Looking for valgrind/memcheck.h - found

however, in the end of compile:
it says 

> */armnn/src/armnn/test/RuntimeTests.cpp:17:10: fatal error: 
>       'valgrind/memcheck.h' file not found #include <valgrind/memcheck.h>

NOTE: #include <valgrind/memcheck.h> works in different cpp project

when I add (download valgrind source code) valgrind include dir into above header files
compiler also says 

> */toolchain/aarch64-linux-android-ndk-r16b/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lpthread
> clang50++: error: linker command failed with exit code 1 (use -v to see invocation)

what is the problem?

**Comment by pcub** [comment]
I followed the https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md
however, compiler gives following error:

> */toolchain/aarch64-linux-android-ndk-r16b/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: libarmnnUtils.a(Logging.cpp.o): undefined reference to symbol '__android_log_write'
> */toolchain/aarch64-linux-android-ndk-r16b/bin/../sysroot/usr/lib/liblog.so: error adding symbols: DSO missing from command line
> clang50++: error: linker command failed with exit code 1 (use -v to see invocation)
> 

these solutions (https://stackoverflow.com/questions/4455941/undefined-reference-to-android-log-print) don't work

what is the problem?

**Comment by Surmeh** [comment]
Hi @pcub,

Thanks for pointing this out, we'll fix the documentation in our future release.

As a workaround, when building ArmNN, if you replace -DCMAKE_SYSTEM_NAME=Linux with -DCMAKE_SYSTEM_NAME=Android, the error goes away. 

I hope this helps,
Surabhi

**Comment by pcub** [comment]
It does not help

**Comment by TelmoARM** [comment]
Hi pcub,

Could you provide some more information with the error you are currently getting? Surabhi was able to get this working by changing the  `-DCMAKE_SYSTEM_NAME=Linux` to `-DCMAKE_SYSTEM_NAME=Android`

Thanks,
Telmo

**Comment by Surmeh** [comment]
Hi @pcub,

Did you manage to solve the problem? Let me know if you need further help on this.

Thanks,
Surabhi

**Comment by pcub** [comment]
Thanks guys, currently I am not working on that, I will inform if I need to work on that part.

**Comment by MatthewARM** [comment]
Hi @pcub thank you, please reopen this ticket or create a new issue if you have any more problems.
