### ISSUE TITLE
Benefits of offline parser support

### ISSUE THREAD

**Issue by AnPay** [ARM-software/armnn#163]
Hello
Thanks for providing an offline support for parsing.I would like to understand if it has any impact on inference/execution time or only saves parsing time while model loading.
Thanks

**Comment by MatthewARM** [comment]
Hi @AnPay it should be _exactly_ the same model as produced by the original parser, so it shouldn't change inference/execution time.

Hope that helps,
Matthew

**Comment by AnPay** [comment]
Thanks @MatthewARM .
So does it mean, as earlier the parsing was done on runtime, since now its done offline it will save model loading time?
Is there any other reason behind offline parser support?

**Comment by Azutoz** [comment]
Could you please elaborate on the benefits and purpose of the offline parser support?
Thankyou

**Comment by Azutoz** [comment]
@MatthewARM 
Could you please elaborate on the purpose and benefits of the offline converter tool?
Thankyou

**Comment by MatthewARM** [comment]
Hi @Azutoz we've got some plans for adding more graph optimisation features to the converter, but at the moment it just provides an alternative deployment format for your models, so that you don't have to deploy the large model parsers.

The Tensorflow parser can be as large as 6MB, whereas libarmnnSerializer.so is only around 400kb.

**Comment by AnPay** [comment]
Hi @MatthewARM 
What I can see is time taken to serialize a tf model and to deserialize the same i.e. Getroot<> function takes different time. Is that normal or its an overhead with offline conversion?
Time taken to serialize is 100ms
Time taken to deserialize(GetRoot<> function) the serialized data is ~1000ms

**Comment by AnPay** [comment]
GetSerializedGraph is not the issue. Copying binaryContent into a vector is taking a long time.
`std::vector<uint8_t> content((std::istreambuf_iterator<char>(binaryContent)), std::istreambuf_iterator<char>());`
Around 1000ms+
Any ideas?

**Comment by MatthewARM** [comment]
Hi @AnPay where is that code specifically? Perhaps you can use a memory map instead of copying it?

**Comment by AnPay** [comment]
Thanks for the reply @MatthewARM 
The code is in "./src/armnnDeserializer/Deserializer.cpp"                                                        
`armnn::INetworkPtr Deserializer::CreateNetworkFromBinary(std::istream& binaryContent)
{
ResetParser();
std::vector<uint8_t> content((std::istreambuf_iterator<char>(binaryContent)), std::istreambuf_iterator<char>());
GraphPtr graph = LoadGraphFromBinary(content.data(), content.size());
return CreateNetworkFromGraph(graph);
}
`

**Comment by AnPay** [comment]
Could reduce the time using read() function. Any specific intentions behind using istreambuf_iterator?

**Comment by MatthewARM** [comment]
Hi @AnPay it looks easy to add another version of that routine that would take a raw pointer (and a size). Then in your program you could memory map it and just pass the pointer to the Deserializer.

The istream version is intended for use with files, etc. where there isn't necessarily random access. In which case we need to read it into a buffer to produce a raw pointer than can be consumed by flatbuffers.

Hope that helps,
Matthew

**Comment by AnPay** [comment]
Thanks @MatthewARM 
I am reading a file. Using read() function was significantly faster than istreambuf_iterator.
The intention of this post was to know the benefits of offline parser and consequent overhead if any.
Acc to my understanding, it's meant for reducing the size of library in device.
It doesn't affect the model loading time or execution time in anyway. If we profile a tf model and a converted model, the performance should be same in terms of reading the binary file, loading network and graph execution.
Correct me if I am wrong.

**Comment by MatthewARM** [comment]
Hi @AnPay you are correct, it won't affect the execution time in any way, and if the loading time is any different from the other parsers I would expect the difference to be small.

All the best,
Matthew
