### ISSUE TITLE
Strange issue with MemCopyWorkload

### ISSUE THREAD

**Issue by NatalCoder** [ARM-software/armnn#166]
Hi,

I am running mobilenet v1 1.0 224 via armnn. I am getting a strange issue wrt to this in the MemCopy layer after softmax. I printed the following parameters in that layer.

CopyMemGenericWorkload execute
There is only one pair of source and destination
SRC: 
NumberOfDimensions: 1 NumberOfElements: 1001
 DST:
  NumberOfDimensions: 2 NumberOfElements: 1001
SRC stride: 
NumberOfDimensions: 2 NumberOfElements: 16128
 DST stride: 
 NumberOfDimensions: 2 NumberOfElements: 16016
srcBatches: 1 srcChannels: 1 srcHeight: 1 srcWidth: 1001
srcBatchStride: 0 srcChannelStride: 0 srcHeightStride: 4032 srcWidthStride: 4
dstBatches: 1 dstChannels: 1 dstHeight: 1 dstWidth: 1001
dstBatchStride: 0 dstChannelStride: 0 dstHeightStride: 4004 dstWidthStride: 4
copyLength: 4004 copyHeight: 1 copyChannels: 1 copyBatches: 1

With the same parameters, I am getting huge difference in execution times of this layer. One execution takes around 14ms and another execution is taking around 40ms. I have tested this on multiple runs just to confirm the observation and this keeps on happening. 

Can you tell me some reasons why memcpy layer might behave differently under the exact same circumstances?

Thanks in advance!

**Comment by MatthewARM** [comment]
Hi @NatalCoder my first guess would be a system performance issue. Watch out for other processes also doing a lot of memory accesses, or doing CPU activity. General system performance things like CPU temperature, clock speed, etc. will also be a factor.

You might need to use a system-level profiler such as DS-5 to really see what is going on.

Hope that helps,
Matthew

**Comment by MatthewARM** [comment]
Hi @NatalCoder hope you were able to sort this, if you are still having trouble please reopen this ticket.
