### ISSUE TITLE
How to set multithreads in  the CpuAcc optimisationMode?

### ISSUE THREAD

**Issue by WenguoLi** [ARM-software/armnn#167]
How to set multithreads in  the CpuAcc optimisationMode?
Is there  an api of armnn?

Thanks !

**Comment by MatthewARM** [comment]
Hi @WenguoLi I think this question has been asked on Github before - I'll see if I can dig it out. 

The answer is basically that threading defaults to the number of cores, but you can tweak it with a Compute Library API.

**Comment by MatthewARM** [comment]
Hi the answer is in issue #75 

Hope that helps,
Matthew

**Comment by WenguoLi** [comment]
Thanks .
