### ISSUE TITLE
The effect of data layout

### ISSUE THREAD

**Issue by Cola-Code** [ARM-software/armnn#168]
In my thought, the data layout(NHWC or NCHW) would effect the algorithm of some ops, and this would lead to different performance. Is this understanding right? And for neon backend, which layout is best?

**Comment by MatthewARM** [comment]
Hi @Cola-Code NHWC is best for both the OpenCL and NEON backends at this time.

**Comment by MatthewARM** [comment]
I believe that there's some test programs in the Compute Library that can show you the difference that it makes, but I don't know the details. If you're interested, it would be best to ask on their Github.

**Comment by Cola-Code** [comment]
@MatthewARM , ok, i got it. Thanks very much!

**Comment by MatthewARM** [comment]
Thanks and good luck!
