### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by mengzhuo** [ARM-software/armnn#17]
How to build it on  Debian box?

**Comment by MatthewARM** [comment]
Hi @mengzhuo could you give a bit more information? For example, are you compiling on x86_64 Debian targeting aarch64 Debian? Or compiling on aarch64 Debian?

Thanks,
Matthew

**Comment by mengzhuo** [comment]
Thanks for reply.
I want to build armnn on aarch64 Debian for my Hikey960/970.

p.s. is it possible to access NPU of Hikey970 (Kirin 970)  without HiAI sdk?

**Comment by MatthewARM** [comment]
Hi @mengzhuo at the moment ArmNN supports running on NEON-enabled CPUs, and OpenCL-enabled Mali GPUs.

For the Hisilicon NPU you will need to ask Hisilicon for support.

To build natively on aarch64 Debian you can follow the instructions at: https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe/configuring-the-arm-nn-sdk-build-environment-single-page

**Comment by MatthewARM** [comment]
Hi @mengzhuo I hope that answered your question. Please get back in touch if you need more information.
