### ISSUE TITLE
How to switch fp32 to Int8 while testing TfMobileNet-Armnn on arm cpu/gpu?

### ISSUE THREAD

**Issue by AaronLiu92** [ARM-software/armnn#171]
I want to ask about how to switch fp32 to Int8 while testing TfMobileNet-Armnn on arm cpu/gpu. ty

**Comment by MatthewARM** [comment]
Hi @AaronLiu92 you can use TfLiteMobilenetQuantized-Armnn instead which uses the mobilenet_v1_1.0_224_quant.tflite model. You can download the model here: https://www.tensorflow.org/lite/guide/hosted_models

**Comment by AaronLiu92** [comment]
when i am configuring the Arm NN SDK build using CMake for Tensorflowlite, i got this error, anyway to solve it? thanks

[ 62%] Linking CXX shared library libarmnnTfParser.so
[ 62%] Built target armnnTfParser
[ 62%] Building CXX object CMakeFiles/armnnTfLiteParser.dir/src/armnnTfLiteParser/TfLiteParser.cpp.o
[ 62%] Linking CXX shared library libarmnnTfLiteParser.so
/usr/bin/ld: /home/firefly/Desktop/flatbuffers/libflatbuffers.a(util.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol `__stack_chk_guard@@GLIBC_2.17' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/firefly/Desktop/flatbuffers/libflatbuffers.a(util.cpp.o)(.text+0x18): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `__stack_chk_guard@@GLIBC_2.17'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/armnnTfLiteParser.dir/build.make:106: recipe for target 'libarmnnTfLiteParser.so' failed
make[2]: *** [libarmnnTfLiteParser.so] Error 1
CMakeFiles/Makefile2:175: recipe for target 'CMakeFiles/armnnTfLiteParser.dir/all' failed
make[1]: *** [CMakeFiles/armnnTfLiteParser.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AaronLiu92** [comment]
@MatthewARM  when i am configuring the Arm NN SDK build using CMake for Tensorflowlite, i got this error, anyway to solve it? thanks

[ 62%] Linking CXX shared library libarmnnTfParser.so
[ 62%] Built target armnnTfParser
[ 62%] Building CXX object CMakeFiles/armnnTfLiteParser.dir/src/armnnTfLiteParser/TfLiteParser.cpp.o
[ 62%] Linking CXX shared library libarmnnTfLiteParser.so
/usr/bin/ld: /home/firefly/Desktop/flatbuffers/libflatbuffers.a(util.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol __stack_chk_guard@@GLIBC_2.17' can not be used when making a shared object; recompile with -fPIC /usr/bin/ld: /home/firefly/Desktop/flatbuffers/libflatbuffers.a(util.cpp.o)(.text+0x18): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol __stack_chk_guard@@GLIBC_2.17'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/armnnTfLiteParser.dir/build.make:106: recipe for target 'libarmnnTfLiteParser.so' failed
make[2]: *** [libarmnnTfLiteParser.so] Error 1
CMakeFiles/Makefile2:175: recipe for target 'CMakeFiles/armnnTfLiteParser.dir/all' failed
make[1]: *** [CMakeFiles/armnnTfLiteParser.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MatthewARM** [comment]
Hi you need to add -fPIC to the compiler flags while building libflatbuffers.a.

Hope that helps,
Matthew

**Comment by AaronLiu92** [comment]
@MatthewARM  I did these before:

$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
$ make

In order to compiler by '-fPIC', which file should i edit or what command should i add after 'cmake' or 'make'? Thanks!

**Comment by AaronLiu92** [comment]
@MatthewARM  build successfully by adding   -DCMAKE_CXX_FLAGS="-fPIC"  after cmake command. Thanks Matthew!
