### ISSUE TITLE
Errors when running UnitTests

### ISSUE THREAD

**Issue by pineapple121** [ARM-software/armnn#173]
@MatthewARM, Hi, I managed to build Arm NN and copy the build folder to my arm64 linux machine,  I'm just following the build instructions from [https://github.com/ARM-software/armnn/blob/branches/armnn_19_02/BuildGuideCrossCompilation.md](url) and running the UnitTests, at first it shows "Permission Denied" when I run the UnitTests, after I switch to root or sudo ./UnitTests, it shows"command not found", so I modify it's permission with command “chmod 777 ./UnitTests”, then run it, success. But a lot of failures are detected, such as

unknown location(0): fatal error: in "Compute_ArmComputeCl/SimpleConvertFp16ToFp32": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(338): last checkpoint: "SimpleConvertFp16ToFp32" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/SimpleConvertFp32ToFp16": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(340): last checkpoint: "SimpleConvertFp32ToFp16" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/AdditionAfterMaxPool": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(342): last checkpoint: "AdditionAfterMaxPool" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MaximumSimple": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(345): last checkpoint: "MaximumSimple" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MaximumBroadcast1Element": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(346): last checkpoint: "MaximumBroadcast1Element" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MaximumBroadcast1DVector": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(347): last checkpoint: "MaximumBroadcast1DVector" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MaximumUint8": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(348): last checkpoint: "MaximumUint8" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MaximumBroadcast1ElementUint8": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(349): last checkpoint: "MaximumBroadcast1ElementUint8" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MaximumBroadcast1DVectorUint8": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(350): last checkpoint: "MaximumBroadcast1DVectorUint8" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanUint8Simple": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(353): last checkpoint: "MeanUint8Simple" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanUint8SimpleAxis": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(354): last checkpoint: "MeanUint8SimpleAxis" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanUint8KeepDims": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(355): last checkpoint: "MeanUint8KeepDims" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanUint8MultipleDims": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(356): last checkpoint: "MeanUint8MultipleDims" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanVtsUint8": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(357): last checkpoint: "MeanVtsUint8" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanFloatSimple": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(359): last checkpoint: "MeanFloatSimple" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanFloatSimpleAxis": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(360): last checkpoint: "MeanFloatSimpleAxis" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanFloatKeepDims": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(361): last checkpoint: "MeanFloatKeepDims" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanFloatMultipleDims": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(362): last checkpoint: "MeanFloatMultipleDims" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanVtsFloat1": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(363): last checkpoint: "MeanVtsFloat1" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanVtsFloat2": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(364): last checkpoint: "MeanVtsFloat2" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MeanVtsFloat3": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(365): last checkpoint: "MeanVtsFloat3" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MinimumBroadcast1Element1": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(368): last checkpoint: "MinimumBroadcast1Element1" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MinimumBroadcast1Element2": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(369): last checkpoint: "MinimumBroadcast1Element2" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/MinimumBroadcast1DVectorUint8": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(370): last checkpoint: "MinimumBroadcast1DVectorUint8" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/SimpleGreater": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(373): last checkpoint: "SimpleGreater" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/GreaterBroadcast1Element": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(374): last checkpoint: "GreaterBroadcast1Element" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/GreaterBroadcast1DVector": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(375): last checkpoint: "GreaterBroadcast1DVector" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/GreaterUint8": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(376): last checkpoint: "GreaterUint8" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/GreaterBroadcast1ElementUint8": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(377): last checkpoint: "GreaterBroadcast1ElementUint8" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/GreaterBroadcast1DVectorUint8": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(378): last checkpoint: "GreaterBroadcast1DVectorUint8" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/SpaceToBatchNdSimpleFloat32": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(381): last checkpoint: "SpaceToBatchNdSimpleFloat32" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/SpaceToBatchNdMultiChannelsFloat32": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(382): last checkpoint: "SpaceToBatchNdMultiChannelsFloat32" fixture entry.
unknown location(0): fatal error: in "Compute_ArmComputeCl/SpaceToBatchNdMultiBlockFloat32": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -5
/home/ubuntu/ARM/armnn/src/backends/cl/test/ClLayerTests.cpp(383): last checkpoint: "SpaceToBatchNdMultiBlockFloat32" fixture entry.

*** 465 failures are detected in the test module "UnitTests

Can you help me ?
Thanks,
Marco

**Comment by MatthewARM** [comment]
Hi @pineapple121, OpenCL isn't working. If your test platform should be able to support the OpenCL requirements of the Compute Library, documented here: https://arm-software.github.io/ComputeLibrary/v19.02/index.xhtml#S3_8_cl_requirements then perhaps there is a system configuration issue. If your test platform does not support OpenCL, you should either build Arm NN without OpenCL support, or you should ignore the failing OpenCL unit tests.

Hope that helps,
Matthew

**Comment by pineapple121** [comment]
@MatthewARM ,thank you for your reply.  I rebuild Arm NN and Compute Library without OpenCL support,  there are still some mistakes while I running the UnitTests, but much less than before,only 76, like this:

Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
unknown location(0): fatal error: in "NeonRuntime/RuntimeValidateCpuAccDeviceSupportLayerNoFallback": armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetDeviceInfo. CL error code: -6
/home/ubuntu/ARM/armnn/src/backends/neon/test/NeonRuntimeTests.cpp(16): last checkpoint: "RuntimeValidateCpuAccDeviceSupportLayerNoFallback" entry.

*** 76 failures are detected in the test module "UnitTests"

should I just ignore these failing tests ?
Thanks,
Marco

**Comment by pineapple121** [comment]
Hi， @MatthewARM ，I just figured out these problem, I Installed GPU drivers and enable OpenCL on by board, then run the UnitTests without any errors!

Running 978 test cases...

*** No errors detected

Thank you so much,
Marco

**Comment by MatthewARM** [comment]
Great @pineapple121 that's good to know. Good luck with everything!
