### ISSUE TITLE
Building Problem

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/armnn#174]
Hi. I am trying to build ARM NN environment for ONNX. I followed the steps at: https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx/test-your-build

Everything was working fine until now... and suddendly after giving these commands: 
$ cd $BASEDIR/armnn
$ mkdir build
$ cd build
$ cmake .. -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build -DBOOST_ROOT=$BASEDIR/boost -DPROTOBUF_ROOT=$BASEDIR/protobuf-host -DBUILD_ONNX_PARSER=1 -DONNX_GENERATED_SOURCES=$BASEDIR/onnx 
$ make

I got this error : 
![image](https://user-images.githubusercontent.com/39409379/55883052-e28af600-5ba5-11e9-9235-e20e93b4b950.png)

Any suggestion please?

**Comment by MatthewARM** [comment]
Hi @GAnto85 looks like you are doing a native build on x86_64 of armnn, which is then failing to link to an aarch64 build of Compute Library.

If you are trying to cross-compile Arm NN you can find one way of doing it here: https://github.com/ARM-software/armnn/blob/branches/armnn_19_02/BuildGuideCrossCompilation.md

**Comment by GAnto85** [comment]
Can i build it for armv7a using arm-linux-gnueabihf-g++ ? The FPGAs that i'm using have Zynq-7000 SoC with Cortex A9.

**Comment by GAnto85** [comment]
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_79532/fast"
/usr/bin/make -f CMakeFiles/cmTC_79532.dir/build.make CMakeFiles/cmTC_79532.dir/build
make[1]: Entering directory '/home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_79532.dir/CheckSymbolExists.c.o
/usr/bin/aarch64-linux-gnu-gcc    -fPIE   -o CMakeFiles/cmTC_79532.dir/CheckSymbolExists.c.o   -c /home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_79532
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_79532.dir/link.txt --verbose=1
/usr/bin/aarch64-linux-gnu-gcc       CMakeFiles/cmTC_79532.dir/CheckSymbolExists.c.o  -o cmTC_79532 -rdynamic 
CMakeFiles/cmTC_79532.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x14): undefined reference to `pthread_create'
CheckSymbolExists.c:(.text+0x18): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_79532.dir/build.make:97: recipe for target 'cmTC_79532' failed
make[1]: *** [cmTC_79532] Error 1
make[1]: Leaving directory '/home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_79532/fast' failed
make: *** [cmTC_79532/fast] Error 2

File /home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_3e8e8/fast"
/usr/bin/make -f CMakeFiles/cmTC_3e8e8.dir/build.make CMakeFiles/cmTC_3e8e8.dir/build
make[1]: Entering directory '/home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3e8e8.dir/CheckFunctionExists.c.o
/usr/bin/aarch64-linux-gnu-gcc    -DCHECK_FUNCTION_EXISTS=pthread_create -fPIE   -o CMakeFiles/cmTC_3e8e8.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_3e8e8
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3e8e8.dir/link.txt --verbose=1
/usr/bin/aarch64-linux-gnu-gcc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_3e8e8.dir/CheckFunctionExists.c.o  -o cmTC_3e8e8 -rdynamic -lpthreads 
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_3e8e8.dir/build.make:97: recipe for target 'cmTC_3e8e8' failed
make[1]: *** [cmTC_3e8e8] Error 1
make[1]: Leaving directory '/home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_3e8e8/fast' failed
make: *** [cmTC_3e8e8/fast] Error 2


Determining if the include file valgrind/memcheck.h exists failed with the following output:
Change Dir: /home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_fc712/fast"
/usr/bin/make -f CMakeFiles/cmTC_fc712.dir/build.make CMakeFiles/cmTC_fc712.dir/build
make[1]: Entering directory '/home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_fc712.dir/CheckIncludeFile.c.o
/usr/bin/aarch64-linux-gnu-gcc    -fPIE   -o CMakeFiles/cmTC_fc712.dir/CheckIncludeFile.c.o   -c /home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:31: fatal error: valgrind/memcheck.h: No such file or directory
compilation terminated.
CMakeFiles/cmTC_fc712.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_fc712.dir/CheckIncludeFile.c.o' failed
make[1]: *** [CMakeFiles/cmTC_fc712.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '/home/nur/arm_onnx/armnn/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_fc712/fast' failed
make: *** [cmTC_fc712/fast] Error 2

**Comment by MatthewARM** [comment]
Hi @GAnto85 yes it will build ok for armv7, just remember to build the dependencies for armv7 also.

I wouldn't worry about the cmake errors in the second log. That log will contain "errors' from cmake steps even if everything is ok. As long as you can build ArmNN it will be fine.

**Comment by GAnto85** [comment]
Thank you !!

**Comment by GAnto85** [comment]
> Hi @GAnto85 looks like you are doing a native build on x86_64 of armnn, which is then failing to link to an aarch64 build of Compute Library.
> 
> If you are trying to cross-compile Arm NN you can find one way of doing it here: https://github.com/ARM-software/armnn/blob/branches/armnn_19_02/BuildGuideCrossCompilation.md

I'm following that guide. I think i gotta change something when building ARM NN because i need ONNX parser instead of Caffe parser right?

**Comment by GAnto85** [comment]
![image](https://user-images.githubusercontent.com/39409379/56095884-8398ea00-5ee1-11e9-99f6-acabfb3a4a95.png)
