### ISSUE TITLE
run UnitTest error: libarmnnCaffeParser.so no such file

### ISSUE THREAD

**Issue by Huster-SC** [ARM-software/armnn#175]
There is  libarmnnCaffeParser.so in build folder, but it comes 
error while loading shared libraries: libarmnnCaffeParser.so: cannot open shared object file: No such file or directory when I run UnitTest. 
 How should I solve it?

**Comment by MatthewARM** [comment]
Most likely the library location isn't on the search path for some reason. Maybe you have moved the library, but not into a folder on the standard library search order defined in /etc/ld.so.conf

You can check this with `ldd`. For missing entries the line will say "not found".

```
MatthewARM@workstation:~/build-x86_64/release/armnn$ ldd UnitTests 
	linux-vdso.so.1 (0x00007ffe2a5d1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f70f496a000)
	libarmnnTfParser.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnTfParser.so (0x00007f70f430d000)
	libarmnnTfLiteParser.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnTfLiteParser.so (0x00007f70f40b0000)
	libarmnnCaffeParser.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnCaffeParser.so (0x00007f70f3da9000)
	libarmnnSerializer.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnSerializer.so (0x00007f70f3b5a000)
	libarmnnOnnxParser.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnOnnxParser.so (0x00007f70f38f7000)
	libarmnn.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnn.so (0x00007f70f346f000)
	libprotobuf.so => /home/MatthewARM/install/x86_64/protobuf/lib/libprotobuf.so (0x00007f70f2bf0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f70f2867000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70f24c9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f70f22b1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f70f1ec0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f70f56a8000)
```

The standard library search order can be overriden using the LD_LIBRARY_PATH environment variable. If you are following our cross-compilation guide at https://github.com/ARM-software/armnn/blob/branches/armnn_19_02/BuildGuideCrossCompilation.md#unittests then setting LD_LIBRARY_PATH is included under the section "Run Unit Tests".

Hope that helps,
Matthew

**Comment by Huster-SC** [comment]
> Most likely the library location isn't on the search path for some reason. Maybe you have moved the library, but not into a folder on the standard library search order defined in /etc/ld.so.conf
> 
> You can check this with `ldd`. For missing entries the line will say "not found".
> 
> ```
> MatthewARM@workstation:~/build-x86_64/release/armnn$ ldd UnitTests 
> 	linux-vdso.so.1 (0x00007ffe2a5d1000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f70f496a000)
> 	libarmnnTfParser.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnTfParser.so (0x00007f70f430d000)
> 	libarmnnTfLiteParser.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnTfLiteParser.so (0x00007f70f40b0000)
> 	libarmnnCaffeParser.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnCaffeParser.so (0x00007f70f3da9000)
> 	libarmnnSerializer.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnSerializer.so (0x00007f70f3b5a000)
> 	libarmnnOnnxParser.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnnOnnxParser.so (0x00007f70f38f7000)
> 	libarmnn.so => /home/MatthewARM/build-x86_64/release/armnn/libarmnn.so (0x00007f70f346f000)
> 	libprotobuf.so => /home/MatthewARM/install/x86_64/protobuf/lib/libprotobuf.so (0x00007f70f2bf0000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f70f2867000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70f24c9000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f70f22b1000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f70f1ec0000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f70f56a8000)
> ```
> The standard library search order can be overriden using the LD_LIBRARY_PATH environment variable. If you are following our cross-compilation guide at https://github.com/ARM-software/armnn/blob/branches/armnn_19_02/BuildGuideCrossCompilation.md#unittests then setting LD_LIBRARY_PATH is included under the section "Run Unit Tests".
> 
> Hope that helps,
> Matthew

Very helpful! I have solved it. Thanks a lot! BTW, Should I prepare libOpenCL.so by myself?

**Comment by MatthewARM** [comment]
Yes libOpenCL.so is a prerequisite, not part if Arm NN. Good luck!
