### ISSUE TITLE
MobilenetV2SSD on GPU, slower in Armnn than Android NN api?

### ISSUE THREAD

**Issue by lwu025** [ARM-software/armnn#177]
I'm now try to deploy MobilenetV2SSD on my board (with Mali-T864 GPU).
I have tried the TensorflowLite + Android NN API approach, the benchmark tool shows me that it will take about 100ms per frame on GPU.

Then I noticed that I can bypass android layer by passing my tflite model to Arm NN directly. Theoretically, this way should be faster than TensorflowLite->AndroidNN->ArmAndroidNNDriver->ArmNN approach. 

I modified the MNIST example to run my MobileNetV2SSD model in tflite format, and the ran (same device but on Ubuntu 16.04, not android) with GpuAcc setting. It turns out that the time is 150ms per second, which is much slower than the AndroidNN approach.

Does anyone have any idea? or have similar issue?

More about my model:
MobileNetV2SSD
Input: Preprocessor/sub
Output: concate, concate_1

More about my android nn approach:
OS: Android 8.1 (nnapi 1.0)
Tensorflow Lite: 1.13.0

More about my Arm nn approach:
Arm NN: 19.02

More about my device:
Dual Cortex-A72 + Quad Cortex-A53, 64-bit CPU
Mali-T864 GPU

**Comment by MatthewARM** [comment]
I'd try with CpuAcc. It's quite possible that the Mali T864 is slower than the CPU in this configuration.

**Comment by nullbyte91** [comment]
Hi @MatthewARM,

I can see the same thing with ARM Mali-T88x as well as. What you mean by Configuration in this context. Do you mean ARM CPU more powerful than ARM Mali GPU? Correct me if I'm wrong.

**Comment by MatthewARM** [comment]
Hi @nullbyte91 and @lwu025 yes, I mean it is possible your CPU is more powerful than your GPU. It would depend on the number of shader cores, the clock speeds, and the amount of dedicated memory bandwidth that the GPU can access.

You may be able to get this information from your SoC manufacturer, or by running some OpenCL benchmarks.

**Comment by MatthewARM** [comment]
@lwu025 also it would be good to try with more recent Arm NN - the performance in 19.08 is much better than 19.02

**Comment by Colm-in-Arm** [comment]
Hi @lwu025,

Is this still an issue you'd like to work with us on? If I hear nothing back I'll close this in a week or so.

Colm.
