### ISSUE TITLE
Problem with load multiple models 

### ISSUE THREAD

**Issue by waynexhsieh** [ARM-software/armnn#178]
Hi
I try to load multiple models and some models run on GPU (OpenCL) and others run on cpu (Neon)

`armnn::IOptimizedNetworkPtr optNet1 = 
armnn::Optimize(*network1, {armnn::Compute::CpuAcc}, mRuntime->GetDeviceSpec());`
`armnn::IOptimizedNetworkPtr optNet2 = 
armnn::Optimize(*network2, {armnn::Compute::GpuAcc}, mRuntime->GetDeviceSpec());`
`armnn::IOptimizedNetworkPtr optNet3 = 
armnn::Optimize(*network3, {armnn::Compute::GpuAcc}, mRuntime->GetDeviceSpec());`
`Runtime->LoadNetwork(networkIdentifier1, std::move(optNet1));`
`Runtime->LoadNetwork(networkIdentifier2, std::move(optNet2));`
`Runtime->LoadNetwork(networkIdentifier3, std::move(optNet3));`

`ret = Runtime->EnqueueWorkload(networkIdentifier1, ...)`
`ret = Runtime->EnqueueWorkload(networkIdentifier2, ...)`
`ret = Runtime->EnqueueWorkload(networkIdentifier3, ...)`

I use two thread to run models simultaneously, one thread run on GPU and the other run on CPU

The process randomly crash and error message is as fololow:
`libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 6529 (RenderThread)`

Any help on how to solve this?
I use ArmNN 18.11 version, os: Android

Regards
Wayne

**Comment by MatthewARM** [comment]
Hi @Wayne try with the master branch, we have made various multi threading improvements over the last 5 months since 18.11

**Comment by MatthewARM** [comment]
Hi @waynexhsieh if this is still a problem, could you post more of the stack backtrace at the crash so we can see where it is going wrong?

Many thanks,
Matthew

**Comment by MatthewARM** [comment]
Closing his old issue. If it's still a problem please get back in touch.

**Comment by Shelton-N** [comment]
@MatthewARM Now, ARMNN　can support multiple model to inference at the same time ?
