### ISSUE TITLE
BatchToSpaceNdLayer, defination of output shape is different from Tensorflow.

### ISSUE THREAD

**Issue by lwu025** [ARM-software/armnn#179]
Hi, I'm tring to run deeplabv3+ (in tflite format converted from tensorflow format) using armnn. 
However, I got error message that:
BatchToSpaceLayer: TensorShape set on OutputSlot[0] does not match the inferred shape. : [1,65,65,728] != [1,64,64,728]

Then I took a look at the definition of BatchToSpaceNd here[https://www.tensorflow.org/api_docs/python/tf/batch_to_space_nd](url)
It show that the spatial shape of dimension i should be: input_shape[i]*block_shape[i-1]-crops[i-1,0]-crops[i-1,0]

My input shape = [4,33,33,728](NHWC), with block_shape=[2,2], crop=[[0,1],[0,1]]
Therefore, my output should have height and width = 33*2-0-1 = 65, therefore output shape [1,65,65,728]

However in [armnn](https://github.com/ARM-software/armnn/blob/120196d394eb5af4b28f78396d1a225ca47cf274/src/armnn/layers/BatchToSpaceNdLayer.cpp) line 56 to line 120
outputHeight = block_shape[0] * ( input_height - CropsTotal)
In my case: 2*(33-0-1) = 64, therefore output shape [1,64,64,728]

Is this a bug? and how to walk around this error?

**Comment by MatthewARM** [comment]
Hi @lwu025 it could be a bug, we developed BatchToSpaceNd to meet the needs of the Android NNAPI and it's possible that it doesn't work for all tflite usages.

Are you OK to try fixing it? We accept patches, and there's a contributor guide at https://github.com/ARM-software/armnn/blob/master/ContributorGuide.md

**Comment by MatthewARM** [comment]
Believed to be fixed by 3ee1422c824e9dc513566179bcdc0c98657ab0c7
