### ISSUE TITLE
Can't open the website.

### ISSUE THREAD

**Issue by putiancaijunyu** [ARM-software/armnn#18]
https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment

**Comment by Surmeh** [comment]
Hi @putiancaijunyu, can you try this link: https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe/configuring-the-arm-nn-sdk-build-environment-single-page

**Comment by MatthewARM** [comment]
Thanks for spotting this, @putiancaijunyu the link has now been fixed.

**Comment by putiancaijunyu** [comment]
I can access https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe/configuring-the-arm-nn-sdk-build-environment-single-page.
Thanks.
