### ISSUE TITLE
question about TfmobileNetV2Quantized-Armnn result

### ISSUE THREAD

**Issue by AaronLiu92** [ARM-software/armnn#180]
Hello there, i just build armnn Tensorflow & TensorflowLite Environment, now i have 2 questions:
1. I saw many models are compiled inside tests folder, how to compile other Tf/TfLite models which is not consist in tests folders. For example, TfMobileNetV2-Armnn?

2. After i implement TfLiteMobilenetV2Quantized-Armnn model, the result showing like this:

firefly@firefly:~/armnn/build/tests$ ./TfLiteMobilenetV2Quantized-Armnn -m ./ -d ./ -c GpuAcc -i 3
ArmNN v20190200

= Prediction values for test #0
Top(1) prediction is 209 with confidence: 1305.38%
Top(2) prediction is 168 with confidence: 880.144%
Top(3) prediction is 167 with confidence: 741.694%
Top(4) prediction is 159 with confidence: 613.134%
Top(5) prediction is 152 with confidence: 464.795%
= Prediction values for test #1
Top(1) prediction is 282 with confidence: 1394.38%
Top(2) prediction is 52 with confidence: 405.459%
Top(3) prediction is 39 with confidence: 227.453%
Top(4) prediction is 27 with confidence: 217.564%
Top(5) prediction is 13 with confidence: 148.339%
= Prediction values for test #2
Top(1) prediction is 4 with confidence: 1305.38%
Top(2) prediction is 3 with confidence: 1157.04%
Top(3) prediction is 1 with confidence: 108.782%
Top(4) prediction is 0 with confidence: -29.6678%
Total time for 3 test cases: 0.380 seconds
Average time per test case: 126.593 ms
Overall accuracy: 0.333

I want to know why the result is much more than 100%? and when i testing MobileNetV1 (not quantized), the overall accuracy is 100%, but when i change to V2Quantized, the overall accuracy is now 0.333.  Can someone help me with those problems? Thanks!

**Comment by MatthewARM** [comment]
Hi @AaronLiu92 I can't be sure what's going wrong here, but I suspect that you might not be preparing the input tensor data correctly, and you're almost certainly interpreting the output tensor correctly - for quantised input and output you need to use the quantisation parameters from the model to convert between floating-point and 8-bit data.

It looks like perhaps you are trying to copy one of the existing tests, and use it to test a new model? I would suggest you start with something a bit simpler to get used to the API, like samples/SimpleSample.cpp, or one of our getting-started guides such as https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/deploying-a-tensorflow-mnist-model-on-arm-nn

Unfortunately I don't think we have a getting-started guide that uses the TfLite parser yet, but the general steps are the same.

Hope that helps,
Matthew

**Comment by Colm-in-Arm** [comment]
Hi @AaronLiu92 ,

We now have a TfLite getting-started guide
https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite

and a how-to using TfLite and mobilenet-v1
https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/deploying-a-quantized-tensorflow-lite-mobilenet-v1-model-using-the-arm-nn-sdk

Hopefully there should be enough in those to help you create your own test. If you have further problems please open a new issue.

Colm.
