### ISSUE TITLE
libprotobuf.so.18: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/armnn#181]
Hi all, 
I built ARMNN on my x86_64 ubuntu 16.04. 
I crosscompiled it to be executed on an ULTRASCALE+ with architecture aarch64. 
I copied the folder armnn/build into the board's storage and i'm trying to run  "./UnitTests" from there. 
I keep getting this :  
libprotobuf.so.18: cannot open shared object file: No such file or directory
even though i added such library to "/usr/lib"   and " /lib/"  and added these paths in the file /etc/ld.so.conf.d/libarmnn.conf  and exectuted "sudo ldconfig".
Maybe i should copy the whole armnn-devenv folder into the board? Or what i did is enough?
Any suggestion? Thanks.

**Comment by MatthewARM** [comment]
Hi @GAnto85 you should be able to figure out which library is missing by running "ldd" on UnitTests, like this:

$ ldd UnitTests 
	linux-vdso.so.1 (0x00007ffeb9bf3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f54196fc000)
	libarmnnTfParser.so => /home/matben01/gits/devenv/build-x86_64/release/armnn/libarmnnTfParser.so (0x00007f541909f000)
	libarmnnTfLiteParser.so => /home/matben01/gits/devenv/build-x86_64/release/armnn/libarmnnTfLiteParser.so (0x00007f5418e42000)
	libarmnnCaffeParser.so => not found
	libarmnnSerializer.so => /home/matben01/gits/devenv/build-x86_64/release/armnn/libarmnnSerializer.so (0x00007f5418bf3000)
	libarmnnOnnxParser.so => /home/matben01/gits/devenv/build-x86_64/release/armnn/libarmnnOnnxParser.so (0x00007f5418990000)
	libarmnn.so => /home/matben01/gits/devenv/build-x86_64/release/armnn/libarmnn.so (0x00007f5418508000)
	libprotobuf.so => /home/matben01/gits/devenv/install/x86_64/protobuf/lib/libprotobuf.so (0x00007f5417c89000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5417900000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5417562000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f541734a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5416f59000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f541a43a000)

In this examples, I am missing "libarmnnCaffeParser.so".

If you would like to provide the output of "ldd UnitTests" on your target board, I should be able to help further.

In your case I suspect that you have libprotobuf.so, but you are missing one of the things that it depends on.

**Comment by GAnto85** [comment]
Hello , thank you for your help. 
![image](https://user-images.githubusercontent.com/39409379/56575414-f2eb9980-65c5-11e9-870c-dc1a3fad2a54.png)

**Comment by MatthewARM** [comment]
Hi @GAnto85 thanks, that at least confirms that it's libprotobuf itself that's the problem, not an indirect dependency.

Where is libprotobuf.so.18 on your board? Could it be that you have libprotobuf.so but not libprotobuf.so.18?

**Comment by GAnto85** [comment]
Here 
![image](https://user-images.githubusercontent.com/39409379/56575622-7dcc9400-65c6-11e9-96b3-9ca52981014d.png)

**Comment by GAnto85** [comment]
I've used this bash script to build all the libraries on my laptop:

**Comment by GAnto85** [comment]
I found out what was wrong. There were 2 different files libprotobuf.so.18. First one in pkg/host/lib and second one in pkg/install/lib.  First one was wrong and second one works.
![image](https://user-images.githubusercontent.com/39409379/56577148-8e7f0900-65ca-11e9-9034-e02af474faea.png)

**Comment by MatthewARM** [comment]
@GAnto85 thanks. Hope it goes more smoothly from now on!
