### ISSUE TITLE
ARMNN OnnxParser example compile

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/armnn#182]
Hi all, 
i succesfully built ARMNn with OnnxParser and ran the UnitTests. 
The next step for me is making my own net and run it. About making the net there is no problem at all, the problem for me at the moment is compiling. I admit i'm not good at it so i am looking for some advice. 
For now i just want to compile the OnnxMobileNet-Armnn  test in the folder "test".  
In order to compile it i am opening a terminal inside the folder "OnnxMobileNet-Armnn" and i'm writing the following command on the terminal:

aarch64-linux-gnu-g++ OnnxMobileNet-Armnn.cpp -I ../../src/armnnUtils/ -I ../../src/backends/backendsCommon/  -I ../../include/ -std=c++11 -L /home/nur/armnn-devenv/armnn/build/  -llibarmnn.so -llibarmnnUtils.a -llibarmnnOnnxParser.so -o MOBILENET

I am including a few folders required to compile it and the libraries.
 I am getting this error : 

In file included from ../InferenceTest.hpp:9:0,
                 from OnnxMobileNet-Armnn.cpp:5:
../InferenceModel.hpp:20:46: fatal error: backendsCommon/BackendRegistry.hpp: No such file or directory
compilation terminated.

This is weird because i included that directory.  Anybody knows what's going on? Thanks!

**Comment by GAnto85** [comment]
I fixed that issue but something else came up: 

![image](https://user-images.githubusercontent.com/39409379/56650448-5be71600-6687-11e9-8390-363296e76955.png)

I'm trying to compile the code with this makefile:

ARMNN_LIB=${HOME}/armnn-devenv/armnn/build  
ARMNN_LIB2=${HOME}/armnn-devenv/pkg/install/lib
ARMNN_INC=${HOME}/armnn-devenv/armnn/include -I${HOME}/armnn-devenv/armnn/src/armnnUtils 
ARMNN_INC2=${HOME}/armnn-devenv/armnn/src/backends -I${HOME}/armnn-devenv/armnn/src/

all: OnnxMobileNet-Armnn

OnnxMobileNet-Armnn: OnnxMobileNet-Armnn.cpp 
	aarch64-linux-gnu-g++ -O3 -std=c++14 -I$(ARMNN_INC) -I$(ARMNN_INC2) OnnxMobileNet-Armnn.cpp -o OnnxMobileNet-Armnn -L$(ARMNN_LIB) -larmnn -larmnnOnnxParser -larmnnUtils -L$(ARMNN_LIB2) -lprotobuf -lpthread


clean:
	-rm -f OnnxMobileNet-Armnn

test: OnnxMobileNet-Armnn
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(ARMNN_LIB) ./OnnxMobileNet-Armnn

**Comment by GAnto85** [comment]
I resolved the previous error including a Flag in the compiler but now i got this :
![image](https://user-images.githubusercontent.com/39409379/56662358-108f3080-66a4-11e9-993a-0e9aec1e5e7d.png)
Seems like the linker is failing at something.

**Comment by MatthewARM** [comment]
Hi @GAnto85 You also need to link in the boost libraries, by using "-l" flags, or by specifying the paths to the boost libraries on the linker line. Exactly what you need to add depends on how and where your boost libraries were built.

I must say that using our test programs as a way of getting started with ArmNN is probably not the easiest way of doing it. I would start with "SimpleSample.cpp" in the armnn/samples directory.

Good luck with everything,
Matthew

**Comment by GAnto85** [comment]
Ok i'll try it. 
Meanwhile i managed to link all the libraries required by looking at the CMakeLists. There's only one library i can't find anywhere (inferenceTest):


if (BUILD_ONNX_PARSER)
    macro(OnnxParserTest testName sources)
        add_executable_ex(${testName} ${sources})
        target_include_directories(${testName} PRIVATE ../src/armnnUtils)
        target_include_directories(${testName} PRIVATE ../src/backends)

        target_link_libraries(${testName} inferenceTest)              <<<<-------------------
        target_link_libraries(${testName} armnnOnnxParser)
        target_link_libraries(${testName} armnn)
        target_link_libraries(${testName} ${CMAKE_THREAD_LIBS_INIT})
        if(OPENCL_LIBRARIES)
            target_link_libraries(${testName} ${OPENCL_LIBRARIES})
        endif()
        target_link_libraries(${testName}
            ${Boost_SYSTEM_LIBRARY}
            ${Boost_FILESYSTEM_LIBRARY}
            ${Boost_PROGRAM_OPTIONS_LIBRARY})
        addDllCopyCommands(${testName})
    endmacro()

It's defined here i think:

set(inference_test_sources
    ClassifierTestCaseData.hpp
    InferenceModel.hpp
    InferenceTest.hpp
    InferenceTest.inl
    InferenceTest.cpp
    InferenceTestImage.hpp
    InferenceTestImage.cpp)
add_library_ex(inferenceTest STATIC ${inference_test_sources})
target_include_directories(inferenceTest PRIVATE ../src/armnnUtils)
target_include_directories(inferenceTest PRIVATE ../src/backends)

**Comment by MatthewARM** [comment]
Hi @GAnto85 looks like you are on the right track.

Basically for your application code that uses Arm NN, you should not need any of the CMake code that comes with Arm NN. The CMake system is just there to build and install the Arm NN library itself. After that you should just use its /include files and link to it like any other library.

What you are trying to do is reuse bits of the Arm NN internal testing framework as a way of building your application. While this will work I'm sure it's worth the effort, I would suggest that you start with something simple and work up.

**Comment by GAnto85** [comment]
Hello !! Thank you for your reply. I managed to compile and run my own application on Wednesday!! I am parsing mobilenetv2 from a onnx file. I just have to find some functions to preprocess and load an image in the input tensor and then i gotta find a way to link the label list to the output vector in order to choose the right class being classified.
I'm gonna try it now , it shouldn't be too hard!

**Comment by MatthewARM** [comment]
Awesome, good luck!

**Comment by GAnto85** [comment]
Hello! I've got segmentation fault ... I paste the code here :
//
// Copyright © 2017 Arm Ltd. All rights reserved.
// See LICENSE file in the project root for full license information.
//

#include <iostream>
#include <string>
#include <fstream>
#include <vector>
#include <memory>
#include <array>
#include <algorithm>
#include "armnn/ArmNN.hpp"
#include "InferenceTestImage.hpp"
#include "../InferenceModel.hpp"
#include "Permute.hpp"
#include "armnn/Exceptions.hpp"
#include "armnn/Tensor.hpp"
#include "armnn/INetwork.hpp"
#include "armnnOnnxParser/IOnnxParser.hpp"



// Helper function to make input tensors
armnn::InputTensors MakeInputTensors(const std::pair<armnn::LayerBindingId,
    armnn::TensorInfo>& input,
    const void* inputTensorData)
{
    return { { input.first, armnn::ConstTensor(input.second, inputTensorData) } };
}

// Helper function to make output tensors
armnn::OutputTensors MakeOutputTensors(const std::pair<armnn::LayerBindingId,
    armnn::TensorInfo>& output,
    void* outputTensorData)
{
    return { { output.first, armnn::Tensor(output.second, outputTensorData) } };
}

int main(int argc, char** argv)
{   

    // Load image 
    const std::string path = "image.jpg";
    InferenceTestImage image(path.c_str());
    std::vector<float> input = image.Resize(224, 224, CHECK_LOCATION(), InferenceTestImage::ResizingMethods::BilinearAndNormalized, 
                                                {{0.485f, 0.456f, 0.406f}}, {{0.229f, 0.224f, 0.225f}});
                               
    std::cout<<"input size: "<<input.size()<<std::endl;   
                                     
   // if DataFormat = NCHW
    const armnn::PermutationVector NHWCToArmNN = { 0, 2, 3, 1 };
    armnn::TensorShape dstShape({1, 3, 224, 224});
    std::vector<float> tempImage(input.size());
    armnnUtils::Permute(dstShape, NHWCToArmNN, input.data(), tempImage.data(), sizeof(float));
    input.swap(tempImage);
        
    std::cout<<"Image loaded \n";                                          
   
    // Import the Onnx model. Note: use CreateNetworkFromBinaryFile for .pb files.
    armnnOnnxParser::IOnnxParserPtr parser = armnnOnnxParser::IOnnxParser::Create();
    armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("mobilenetv2-1.0.onnx");
    
    std::cout<<"Onnx model imported \n";

    // Find the binding points for the input and output nodes
    armnnOnnxParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo("data");
    armnnOnnxParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("mobilenetv20_output_flatten0_reshape0");

    std::cout<<"Binding points set \n";

    // Optimize the network for a specific runtime compute device, e.g. CpuAcc, GpuAcc
    armnn::IRuntime::CreationOptions options;
    armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);
    armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuRef}, runtime->GetDeviceSpec());
    
    // Load the optimized network onto the runtime device
    armnn::NetworkId networkIdentifier;
    runtime->LoadNetwork(networkIdentifier, std::move(optNet));
    
    std::cout<<"Network loaded \n";

    // Run a single inference on the image
    std::array<float,1000> output;
    armnn::Status ret = runtime->EnqueueWorkload(networkIdentifier,
                                                 MakeInputTensors(inputBindingInfo, &input),
                                                 MakeOutputTensors(outputBindingInfo, &output));
                                                 
    std::cout<<"Inference done \n";                                            

    // Convert 1-hot output to an integer label and print
   // int label = std::distance(output.begin(), std::max_element(output.begin(), output.end()));
   // std::cout << "Predicted: " << label << std::endl;
    //std::cout << "   Actual: " << input->label << std::endl;
    return 0;
}

![image](https://user-images.githubusercontent.com/39409379/56907568-d27b7d80-6aa4-11e9-82c9-5186f844d7e7.png)

**Comment by MatthewARM** [comment]
Hi @GAnto85 most likely armnn::Optimize failed and 'optNet' is a NULL pointer.

You should turn on debug logging by calling ConfigureLogging from include/armnn/Utils.hpp to get more information. 

Good luck!

Matthew

**Comment by GAnto85** [comment]
Hello Matthew. The debug only adds the string ArmNN v20190200 on the standard output. I checked the optNet pointer and is not NULL. 
![image](https://user-images.githubusercontent.com/39409379/56911799-25a5fe00-6aae-11e9-9a19-92acd3001989.png)

Something happens inside EnqueueWorkLoad. I checked the input size again and it is correct. Same goes for the binding points. 
For further investigation i should modify LoadedNetwork.cpp but this file is part of the ArmNN library. Should i recompile it and add the object file to libarmnn.so (if possible) ? I'm really ignorant on compilers and this stuff :D

**Comment by GAnto85** [comment]
Done. The issue was about the input and output tensors. Somehow they cannot be created with the method used on the mnist tf example.

**Comment by chudegao** [comment]
> Done. The issue was about the input and output tensors. Somehow they cannot be created with the method used on the mnist tf example.

Hi @GAnto85 , I'm looking for onnx example of armnn. Would you like to share your onnx example. Thanks.
