### ISSUE TITLE
Gpu optimization on Ultrascale+MPSoC

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/armnn#183]
Hi everyone! 
I am running armnn on ultrascale+MPSoc with Mali gpu. 

If i set my optimizer for Cpu , it works correctly:
armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuAcc}, runtime->GetDeviceSpec());

Instead, if i enable the optimization for Gpu, optNet will be a NULL pointer and obviously it goes on segmentation fault.
armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::GpuAcc}, runtime->GetDeviceSpec()); 

Do you know why this is happening?

**Comment by MatthewARM** [comment]
Hi @GAnto85 you should turn on logging (see armnn/Utils.hpp) to see the reason for failing to optimise the network.

I believe the reason for you is that the Mali-400 GPU in the Ultrascale+ does not support OpenCL, which is needed for Arm NN GPU acceleration.

**Comment by MatthewARM** [comment]
Ah I can see from your other post that logging is not being helpful for you - can you show how you are calling armnn::ConfigureLogging?

**Comment by GAnto85** [comment]
Yes sure! Here is the main code:
int main(int argc, char** argv)
{   

    armnn::ConfigureLogging(true, false, armnn::LogSeverity::Debug);

    
    // Load image 
    const std::string path = argv[1];
    InferenceTestImage image(path.c_str());
    std::vector<float> input = image.Resize(224, 224, CHECK_LOCATION(), InferenceTestImage::ResizingMethods::BilinearAndNormalized, 
                                                {{0.485f, 0.456f, 0.406f}}, {{0.229f, 0.224f, 0.225f}});
 
                               
    //std::cout<<"input size: "<<input.size()<<std::endl;      
    
                                     
   // if DataFormat = NCHW
    const armnn::PermutationVector NHWCToArmNN = { 0, 2, 3, 1 };
    armnn::TensorShape dstShape({1, 3, 224, 224});
    std::vector<float> tempImage(input.size());
    armnnUtils::Permute(dstShape, NHWCToArmNN, input.data(), tempImage.data(), sizeof(float));
    input.swap(tempImage);
    

    std::cout<<"Image loaded \n";                                          
   
    // Import the Onnx model. Note: use CreateNetworkFromBinaryFile for .pb files.
    armnnOnnxParser::IOnnxParserPtr parser = armnnOnnxParser::IOnnxParser::Create();
    armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("mobilenetv2-1.0.onnx");
    
    std::cout<<"Onnx model imported \n";

    // Find the binding points for the input and output nodes
    armnnOnnxParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo("data");
    armnnOnnxParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("mobilenetv20_output_flatten0_reshape0");


    //std::cout<<"Binding points set \n";
    


    // Optimize the network for a specific runtime compute device, e.g. CpuAcc, GpuAcc
    armnn::IRuntime::CreationOptions options;
    armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);
    armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::GpuAcc}, runtime->GetDeviceSpec());
    
    if(optNet != NULL)
      printf("optNet is NULL \n");
    
    // Load the optimized network onto the runtime device
    armnn::NetworkId networkIdentifier;
    runtime->LoadNetwork(networkIdentifier, std::move(optNet));
    
    std::cout<<"Network loaded \n";

    // Run a single inference on the image
    std::array<float,1000> output;

 
    armnn::InputTensors inputTensors{{0, armnn::ConstTensor(runtime->GetInputTensorInfo(networkIdentifier, 0),
                                                            input.data())}};
    armnn::OutputTensors outputTensors{{0, armnn::Tensor(runtime->GetOutputTensorInfo(networkIdentifier, 0),
                                                         output.data())}};
                                              
    armnn::Status ret = runtime->EnqueueWorkload(networkIdentifier, inputTensors, outputTensors);
                                                 
    std::cout<<"Inference done \n";                                            

    // Classification
    int maxout = std::distance(output.begin(), std::max_element(output.begin(), output.end()));
    maxout++;
    //std::cout << "Max output: " << maxout << std::endl;
    
    Classify(maxout);
   
    
     
    return 0;
}

**Comment by MatthewARM** [comment]
Hmm, that looks correct, and I would have expected you to see error messages about OpenCL not working. I'll raise that issue internally.

In any case, GPU acceleration will not work on a Mali-400MP2.

**Comment by GAnto85** [comment]
Thank you for the info! Saved me a lot of work!

**Comment by GAnto85** [comment]
Yes it gives me an error by the way:
ArmNN v20190200

ERROR: None of the preferred backends [GpuAcc ] are supported. Current platform provides [CpuAcc CpuRef ]
