### ISSUE TITLE
Onnx parser errors

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/armnn#184]
Hi all, i used the onnx parser succesfully on mobilenetv2-1.0. Now i'm trying to use it with other onnx files but it fails, as the following image shows:

![image](https://user-images.githubusercontent.com/39409379/57143194-9e62ce00-6dbe-11e9-9d25-44dee0e69281.png)

It seems like the weights are missing but i checked and they are included in the onnx files.
Any suggestion please? Thanks.

**Comment by GAnto85** [comment]
![image](https://user-images.githubusercontent.com/39409379/57154393-0faf7a80-6dd9-11e9-9fee-41f1117bd468.png)

**Comment by MatthewARM** [comment]
Hi @GAnto85 our ONNX support is quite basic, most likely your model is using features in ONNX that are not supported by our parser. Have you checked the documentation in the ONNX parser directory? It should list exactly what features are tested and known to be working.

**Comment by GAnto85** [comment]
Hi Matthew, i've seen the readme file with the supported functions. The parser is getting stuck at the first convolution, which is a normal 3x3, same as mobilenet first convolution.

**Comment by MatthewARM** [comment]
Ah, just a thought, this could be due to "raw data" - which version are you using? Is it a version that includes this patch? https://review.mlplatform.org/#/c/ml/armnn/+/1024/

**Comment by GAnto85** [comment]
Wow, thank you so much. I replaced those lines in the code and now it works perfectly without those 2 fields. 
The only problem left is the low compatibility with the most used nets due to the absence of operators. I was wondering if i could manually try to add some easy operator such as "concat" at least.

**Comment by MatthewARM** [comment]
Thanks @GAnto85 that would be super helpful. Please read the contributor guide (linked to from the Readme.md) and if you would like you can join the armnn-dev mailing list to discuss your changes.

**Comment by MatthewARM** [comment]
Closing this old issue as the originally reported problem has been fixed. Hope things are going well @GAnto85.
