### ISSUE TITLE
Does ARM NN support caffe multiple output?

### ISSUE THREAD

**Issue by helloworldstone** [ARM-software/armnn#186]
Hello! I use arm nn to run a caffe model.This caffe model has three output blobs, such as prob1,prob2 and prob3. How can I set the GetNetworkOutputBindingInfo  parameter?

Is there a sequence for prob1 ,prob2 and prob3 ?

Shoud I set outputBindingInfo like this : 

armnnCaffeParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("prob1");
    armnnCaffeParser::BindingPointInfo outputBindingInfo2 = parser->GetNetworkOutputBindingInfo("prob2");
    armnnCaffeParser::BindingPointInfo outputBindingInfo3 = parser->GetNetworkOutputBindingInfo("prob3");

Thank you !

**Comment by MatthewARM** [comment]
Hi @helloworldstone yes that's correct. You also need to pass all of the output names in a vector when you call "CreateNetworkFromBinaryFile".

All the best,
Matthew

**Comment by helloworldstone** [comment]
Thank you!
