### ISSUE TITLE
Want ArmnnConverter to run on desktop

### ISSUE THREAD

**Issue by avanilkumar** [ARM-software/armnn#187]
Hi
I want ArmnnConverter to run on desktop.  **Want to know if that is feasible.**
I feel it will be advantage to have ArmnnConverter as desktop app as it can help in serialization with out need of mobile.
When I build it with out cross compilation. I am facing this error.
Linking CXX executable ArmnnConverter
/usr/bin/ld: cannot find -llog

**Comment by MatthewARM** [comment]
Hi @avanilkumar Hope you were able to solve the problem. Do we need to change our documentation to help others avoid this?
