### ISSUE TITLE
Different data get the same result

### ISSUE THREAD

**Issue by ym710336735** [ARM-software/armnn#188]
When I run my own model on the armnn platform, I have a problem. No matter how I change the input data, the output is always the same result.By the way, I get my trained my model on tensorflow.

**Comment by MatthewARM** [comment]
Hi @ym710336735 I think there can only be 3 possibilities here:
1. Something going wrong passing the inputs to Arm NN
2. Something going wrong reading the output from ArmNN
3. Degenerate weights (e.g. all zeroes).

If I were you I would set the "debug" option in OptimizerOptions to true. This will then print out the value of tensors in the model, and you can see where something is going wrong.

Hope that helps,
Matthew

**Comment by MatthewARM** [comment]
@ym710336735 were you able to figure out what was going wrong?

**Comment by ym710336735** [comment]
yes,the input is wrong,all the input are same


Matthew Bentham <notifications@github.com> 于2019年10月14日周一 下午5:32写道：

**Comment by MatthewARM** [comment]
Thanks, do you still need help?
