### ISSUE TITLE
error at ParseDepthwiseConv2D function

### ISSUE THREAD

**Issue by mcdman007** [ARM-software/armnn#190]
Hi.

We are trying to use our dnn model that created with tflite.

But, we are facing the error like below.
`what():  Failed to parse operator #67 within subgraph #0 error: CHECKED_NON_NEGATIVE(options->depth_multiplier) = 32 is not valid, not in {1}.  at function ParseDepthwiseConv2D `
`input tensor [ 1 64 64 1 ]
output tensor [ 1 32 32 32 ]`

Armnn is only supporting the depth_multiplier as 1.

So, do you plan to support that depth_multiplier has various values?

Thank you.

**Comment by MatthewARM** [comment]
Hi @mcdman007 it looks like this code in the armnnTfliteParser is a bit out of date. Compute Library  supports depth multiplier now, but the parser code has not been updated.

I'll put it on our backlog for implementation, but if you would like to have a go at doing it yourself, the proper way of exporting Depthwise Convolution to Arm NN can be seen here: https://github.com/ARM-software/android-nn-driver/blob/branches/android-nn-driver_19_02/1.0/HalPolicy.cpp#L454

**Comment by mcdman007** [comment]
Hi @MatthewARM .
Thank you. I will try it.

**Comment by MatthewARM** [comment]
Believed to be fixef by d6a9dee3fe584921d24a264176468898d38a6202 
and e0200da9300ab0586d1d0b8c855ae1679f2084ab

Hope this helps.
