### ISSUE TITLE
Can't load Caffe models

### ISSUE THREAD

**Issue by ipapadop** [ARM-software/armnn#191]
I have trouble loading Caffe models.

Specifically, I am getting errors that either the requested output does not exist or that the `Data` layer is not supported. Specifically: `Unsupported layer type 'Data'`

Which version of Caffe are you testing against?

**Comment by ipapadop** [comment]
Omitting the input layer name, I am then getting errors trying to access any other layer. E.g., I used alexnet from caffe (https://github.com/BVLC/caffe/tree/master/models/bvlc_alexnet) and modified https://github.com/ARM-software/ML-examples/blob/master/armnn-mnist/mnist_caffe.cpp accordingly.

It seems that protobuf does not populate the necessary structures as printing https://github.com/ARM-software/armnn/blob/7f2c35a82ec11be50b3478bd15207320bbf3bd57/src/armnnCaffeParser/RecordByRecordCaffeParser.cpp#L596 does not output anything.

**Comment by Shada** [comment]
Have you baked the .caffemodel and .protobuf files into a single network file?

The .caffemodel contains the trained weights, while the .protobuf file contains the model definition. The CaffeParser expects only one network file, so they have to be combined.

**Comment by ipapadop** [comment]
I am assuming you mean the `.prototxt` file; as I mentioned I am using off-the-shelf AlexNet.

Caffe provides a `deploy.prototxt` file, but I don't see any way to combine it with the `.caffemodel` file.

Does Arm NN have any tools to do that? Or can you point me to one?

**Comment by Shada** [comment]
Yeah, sorry, I meant the .prototxt file.

I don't think ArmNN provides a tool, at least not yet.
But you can use the following python code to create a network file.

`import caffe`
`net = caffe.Net("deploy.prototxt", "trained.caffemodel", caffe.TEST)`
`net.save("outputfile.caffemodel")`

You should then be able to load `outputfile.caffemodel` in Arm NN.

**Comment by ipapadop** [comment]
OK, thanks. That gets me further, but fails trying to parse for the `conv1` layer (first layer after `data`):
```
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Data blob at index 0 in layer conv1 has an unexpected size. Expected 34848 elements but got 0 elements.  at function GetDataFromBlob [armnnCaffeParser/CaffeParser.cpp:116]
```

**Comment by MatthewARM** [comment]
Sorry @ipapadop I can't guess what's going on here. We test the Caffè parser with Alexnet regularly (using the little Python code to convert the model), so it's either a version difference or something else in the environment that is causing it to go wrong for you.

My only suggestion is that maybe if you try a few more models we can find a pattern to the ones that work and the ones that don't?

**Comment by ipapadop** [comment]
I have retried all of the above with the latest ArmNN. It appears that the problems I was facing have been resolved.

Thanks!
