### ISSUE TITLE
Unsupported operation PadV2 in tensorflow::GraphDef

### ISSUE THREAD

**Issue by petertorelli** [ARM-software/armnn#192]
Similar to #108: is there a dev branch for PadV2?

It appears to not be supported in tag 19.02, but there is a ticket from 5 months ago saying it was merged:

https://review.mlplatform.org/c/ml/ComputeLibrary/+/437

I see this when loading the original [Kaiming He ResNet-50 v1.0](https://github.com/KaimingHe/deep-residual-networks) model after converting from Caffe to saved_model.pb (via mmdnn) to frozen_graph.pb in order to use the Armnn SDK. I followed the transform_graph optimization steps in #108 from the [Arm SDK page here](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/optimizing-neural-networks-for-mobile-and-embedded-devices-with-tensorflow/generate-an-optimized-32-bit-model)). 

Thanks.

**Comment by MikeJKelly** [comment]
Hi Peter,

It is supported in the CL however it has not been added to ArmNN yet, I've added it to our backlog for implementation. 

Best regards,
Mike

**Comment by MatthewARM** [comment]
Hi @petertorelli are you loading the Tensorflow model directly in Arm NN, or are you converting to Tensorflow Lite first?

I recommend converting to Tensorflow Lite as it optimises the model, as long as the model is supported by the converter.

PadV2 is now supported at the Arm NN graph API level, but has not yet been integrated in the Tensorflow or Tensorflow Lite parsers. If you prefer one over the other, I'll see if it can be prioritised.

**Comment by petertorelli** [comment]
Hi Matthew,

The problem was resolved (on CPUs) by converting to TFLite and then using the Arm NN TFLite API loader. I probably should have closed this ticket.

Thank you,
Peter

**Comment by MatthewARM** [comment]
Thanks!
