### ISSUE TITLE
 Unsupported operation Cast in tensorflow::GraphDef

### ISSUE THREAD

**Issue by Decode2Code** [ARM-software/armnn#194]
Hello.
I'm trying to use Armnn run network tensorflow model.
but there is an error, Unsupported operation Cast in tensorflow::GraphDef.
Do you have any plan to support Cast operation?

I looked at my model and I guess I might need Switch, RandomUniform and Merge operations as well. Do you have any plan to support these operations in near future.

**Comment by MatthewARM** [comment]
Hi @Decode2Code, we should be getting Cast working sometime soon. Switch and Merge are control-flow operations which we are planning to support eventually but it's hard to say when they will be ready. RandomUniform is usually just used in training - have you optimized your tensorflow network for inference?

**Comment by Colm-in-Arm** [comment]
Hi @Decode2Code,

Do you still need these operators? If I hear nothing back I'll close this in a week or so.

Colm.
