### ISSUE TITLE
Build armnn 19.05 failed using Android NDK 

### ISSUE THREAD

**Issue by helloworldstone** [ARM-software/armnn#197]
Hello! 
I have builded arm nn 19.02 successfully using Android NDK by this article: 
https://github.com/ARM-software/armnn/blob/branches/armnn_19_05/BuildGuideAndroidNDK.md.
And I have builded arm compute library 19.05 successfully.
But when I  build arm nn 19.05 using Android NDK by this article: https://github.com/ARM-software/armnn/blob/branches/armnn_19_05/BuildGuideAndroidNDK.md.It failed!
Error information as follows:

**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ARMCOMPUTE_CORE_LIBRARY_DEBUG
    linked by target "armnn" in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05
ARMCOMPUTE_CORE_LIBRARY_RELEASE
    linked by target "armnn" in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05
ARMCOMPUTE_INCLUDE
   used as include directory in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05
   ......
   used as include directory in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05/src/backends/reference/workloads
   used as include directory in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05/src/backends/reference/test
ARMCOMPUTE_LIBRARY_DEBUG
    linked by target "armnn" in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05
ARMCOMPUTE_LIBRARY_RELEASE
    linked by target "armnn" in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05
HALF_INCLUDE
   used as include directory in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05
   ......
   used as include directory in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05/src/backends/reference/test
OPENCL_INCLUDE
   used as include directory in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05
   ......
   used as include directory in directory /cloud/slave/ARM_NN/armnn-branches-armnn_19_05/src/backends/reference/test
-- Configuring incomplete, errors occurred!
See also "/cloud/slave/ARM_NN/armnn-branches-armnn_19_05/build/CMakeFiles/CMakeOutput.log".
See also "/cloud/slave/ARM_NN/armnn-branches-armnn_19_05/build/CMakeFiles/CMakeError.log".**

**Comment by MatthewARM** [comment]
It can't find the Compute Library - can you check if libarm_compute_core.so and libarm_compute.so are present in the Compute Library build directory, and that the path is correctly specified on your CMake command line?

**Comment by helloworldstone** [comment]
Yes，it's my fault. The path is not correctly specified.
