### ISSUE TITLE
ArmNN API fails image classification with ONNX Resnet model

### ISSUE THREAD

**Issue by bellycat77** [ARM-software/armnn#199]
I use CK software.
There are 2 installed ONNX models:
 - NHWC `$ ck install package --tags=onnx,model,resnet,converted,nhwc`
 - NCHW `$ ck install package --tags=onnx,model,resnet,converted,nchw`

When I run `program:image-classification-armnn-onnx` and choose NHWC variant - program fails with the message:
```
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unsupported operation Transpose for node 'resnet_model/conv2d/Conv2D__6'  at function LoadGraph [/home/ivan/CK-TOOLS/lib-armnn-19.05-llvm-6.0.0-1ubuntu2-onnx-rel.19.05-tflite-linux-64/src/src/armnnOnnxParser/OnnxParser.cpp:625]
./tmp-xcwgaoc8.sh: line 40: 19595 Aborted                 (core dumped) ./classification
```

When I run `program:image-classification-armnn-onnx` and choose NCHW variant - program fails with the message:
```
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unsupported operation ReduceMean for node 'resnet_model/Mean'  at function LoadGraph [/home/ivan/CK-TOOLS/lib-armnn-19.05-llvm-6.0.0-1ubuntu2-onnx-rel.19.05-tflite-linux-64/src/src/armnnOnnxParser/OnnxParser.cpp:625]

```

**Comment by psyhtest** [comment]
For more information on installing CK with ArmNN, please see [ArmNN-MLPerf](https://github.com/ARM-software/armnn-mlperf#gs) instructions.

**Comment by psyhtest** [comment]
We know that ONNX is support is [quite basic](https://github.com/ARM-software/armnn/issues/184#issuecomment-489256445) but both MobileNet (this issue) and ResNet (#200) are in MLPerf Inference, so it would be good to prioritise them. (Not to mention that using the ONNX version of SSD-ResNet might be the only viable option to support this model on ArmNN.)

**Comment by matthewsloyanARM** [comment]
Hi @bellycat77,

Thank you for reaching out! Based on the updated `README.md` found [here](https://github.com/ARM-software/armnn/tree/master#how-to-get-involved) under the "How to get involved" section we will be closing GitHub issues labeled with "Feature Request". Instead, we will be tracking the issue and adding the "Help wanted" label. All the issues with this label can be found [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). We would much appreciate your help to add these features. If you would like to add this or any feature to Arm NN feel free to reopen this ticket and let us know you are working on it with a quick comment. We will then track the updates and help you get your additions into our codebase.

Below you will find our contributors guide which will show you how you can submit a patch to us. If you have any questions feel free to ask here or by creating a new Issue, thank you!

https://www.mlplatform.org/contributing

Kind regards,

Matthew
