### ISSUE TITLE
armnn sdk compile question

### ISSUE THREAD

**Issue by Wayne-pw** [ARM-software/armnn#2]
hello
     I compile armnn SDK according to the https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment/configuring-the-arm-nn-sdk-build-environment-single-page，but there was some mistakes。
    /usr/bin/ld: ComputeLibrary-master/build/libarm_compute-static.a(ITensorAllocator.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ComputeLibrary-master/build/libarm_compute-static.a(ITensorAllocator.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ComputeLibrary-master/build/libarm_compute-static.a(ITensorAllocator.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ComputeLibrary-master/build/libarm_compute-static.a(ITensorAllocator.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ComputeLibrary-master/build/libarm_compute-static.a(ITensorAllocator.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ComputeLibrary-master/build/libarm_compute-static.a(ITensorAllocator.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ComputeLibrary-master/build/libarm_compute-static.a(ITensorAllocator.o): Relocations in generic ELF (EM: 40)
ComputeLibrary-master/build/libarm_compute-static.a: error adding symbols: File in wrong format
     ComputeLibrary-master compiled with arm-linux-gnueabihf-gcc-4.9.1, armnn-master compiled with gcc-5.4
     armnn-master  requires other compilers to compile?
                                                                                                                                                 thank you!

**Comment by MatthewARM** [comment]
Hi @Wayne-pw it looks like you might be trying to cross-compile Compute Library for a 32-bit Arm v7 target (arm-linux-gnueabihf) but the instructions are for a native aarch64 Arm v8 build. Possibly you need to use a different toolchain, or attempt to build it natively on your target platform?

**Comment by Wayne-pw** [comment]
hi @MatthewARM 
    I tried to compile ComputeLibrary with aarch64-linux-gnu-gcc，armnn-master compiled with gcc or aarch64-linux-androideabi-clang？ caffe and boost recompile with aarch64-linux-androideabi-clang?
  I tried to close caffe_parse，there are some other questions:
armnn/boost_1_64_0/stage/lib/libboost_unit_test_framework.a(unit_test_main.o): In function `boost::unit_test::unit_test_main(boost::unit_test::test_suite* (*)(int, char**), int, char**)':
unit_test_main.cpp:(.text+0xec): undefined reference to `stdin'
unit_test_main.cpp:(.text+0xf0): undefined reference to `stdin'
unit_test_main.cpp:(.text+0xf8): undefined reference to `_IO_getc'
armnn/boost_1_64_0/stage/lib/libboost_unit_test_framework.a(execution_monitor.o): In function `boost::detail::signal_handler::~signal_handler()':
execution_monitor.cpp:(.text+0x104): undefined reference to `__errno_location'
armnn/boost_1_64_0/stage/lib/libboost_unit_test_framework.a(execution_monitor.o): In function `boost::system_error::system_error(char const*)':
execution_monitor.cpp:(.text+0x390): undefined reference to `__errno_location'
armnn/boost_1_64_0/stage/lib/libboost_unit_test_framework.a(execution_monitor.o): In function `boost::execution_monitor::catch_signals(boost::function<int ()> const&)':
execution_monitor.cpp:(.text+0xf08): undefined reference to `__sigsetjmp'
libarmnn.so: undefined reference to `std::basic_streambuf<char, std::char_traits<char> >::seekpos(std::fpos<__mbstate_t>, std::_Ios_Openmode)'
libarmnn.so: undefined reference to `stdout'
libarmnn.so: undefined reference to `__assert_fail'

How do you solve these problems?
                                                                                                                      thank you

**Comment by MatthewARM** [comment]
Hi @Wayne-pw I think you are mixing stuff compiled for Linux, with stuff compiled for Android. You should clean out your build folders and try to compile everything for Linux, with just one tool chain.

**Comment by Wayne-pw** [comment]
I want to re-compile the codes for Android.Should I cross compile caffe and boost using Android compiler such as aarch64-linux-androideabi-clang?

**Comment by MatthewARM** [comment]
Hi @Wayne-pw you definitely need boost, compute library, protobuf and ArmNN compiled with the android compiler.
You don't need to recompile Caffe itself as the armnnCaffeParser just needs some generated source files from Caffe.

**Comment by MatthewARM** [comment]
I'll close this issue as it seems the problem was mixing dependencies built for Linux and Android.
