### ISSUE TITLE
Quesry on network creation / testing

### ISSUE THREAD

**Issue by mkamrao** [ARM-software/armnn#20]
Hi

In the tests that are provided, they seem to be expecting the network models in either Caffe or Tensorflow formats. I have below queries:

1. Can we use our own trained network models (other than Caffe or TensorFlow) and use ARM NN to test it

2. Are there any APIs, to create a network on our own by designing the network using various Layers (without using the Caffe or TensorFlow models)

It would be very helpful, if you could clarify on the above and point to any examples.

Thank you
Kamrao

**Comment by MatthewARM** [comment]
Hi @mkamrao 

1. If you have a model trained in a different framework, then you can use the ArmNN API directly to load it into ArmNN. You can use the code in our Caffe and Tensorflow parsers as an example of how to do this. The header file that you will need for adding layers is armnn/include/armnn/INetwork.h

2. Although you can create a network directly, at this time ArmNN has no facility for training a model. You need to provide all of the weights and other trained parameters.

I hope this helps,

Matthew

**Comment by mkamrao** [comment]
Hi Matthew

Thank you, for the response.

1. I think it would be little difficult for users to understand and make out from the Caffe, TF parsers and implement relevant portions from it. It would really help if there is an example for a generic framework/model (other than Caffe, TF), so that users could use it for any of their trained models.

2. I was not referring to training, but was mentioning about inference by creating a network, by having access to individual layer APIs (such as Convolution etc.) to create a graph/network (something similar to ARM Compute library). Is the access to APIs available, if so could you please point to that.

Thank you
Kamrao

**Comment by MatthewARM** [comment]
Hi @mkamrao,

1. Thanks for your feedback. We'll see whether an API example can be provided in a future release.
2. Ah, thanks for the clarification. In that case, you should look in armnn/include/armnn/INetwork.h

Hope that helps,
Matthew

**Comment by mkamrao** [comment]
Hi Matthew

Thanks, for the inputs.

In followup to above query, is there an documentation explaining the C++ APIs for the Layers needed for a network creation (for inference) i.e. adding various layers to the network, create/load the network, run the network for inference etc.

It would be great, if you could point me to any example implementation/pseudo code of any network created using the C++ layer APIs for inference.

Kamrao

**Comment by MatthewARM** [comment]
Hi @mkamrao, 

We don't have any example code for building the network, but we do have Doxygen reference documentation for the API. There is a Doxyfile at docs/Doxyfile which you can use to generate html documentation like this:
`doxygen docs/Doxyfile`

The class that you need to use is called `INetwork` and you will find the generated documentation at `armnn/docs/html/classarmnn_1_1_i_network.html`

This guide is relevant: https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/deploying-a-tensorflow-mnist-model-on-arm-nn/import-graph although it uses the Tensorflow parser to create the network, everything after that point will be the same whether you are using the Tensorflow parser or directly using the API

**Comment by mkamrao** [comment]
Hi Matthew

Thanks for the info on the documentation. Good to know that the C++ APIs for layers are available to create a network.

The guide that you have mentioned also provides information on how to load the network, optimize it and run on the target which is quite useful.

However, it is not clear from the documentation or the guide on how we could create a base network object, add the individual layers to it to create a network. It would really help, if you could provide a example network that is created using the individual layer C++ APIs (similar to the network creation examples provided with ARM Compute Library). This would save us a lot of time from debugging and also allow us to focus on creating the application(s).

Thanks in advance
Kamrao

**Comment by uu-kameshm** [comment]
Hi Matthew

Is there any update on my query above (example for how we could create a base network object, add the individual layers to it to create a network for inference).

Thanks
Kamesh

**Comment by MatthewARM** [comment]
Hi Karmrao, sorry for the delay in replying to you.

At the moment there is no example of how to use the network construction API. We will look into providing an example in a future release.

In the meantime, perhaps the unit test cases at src/armnn/test/GraphTests.cpp can help you get started.

**Comment by uu-kameshm** [comment]
Hi Matthew

Thank you, Is there any idea on when the next release can be expected.

Kamrao

**Comment by MatthewARM** [comment]
Hi Kamrao,

We aim to do a release every three months. The next release will be in August. However, it may not be possible to add new example code in the next release as it will depend on our other commitments.

I hope you understand,
Matthew

**Comment by MatthewARM** [comment]
Hi @uu-kameshm I hope the various sources of information mentioned above have been helpful. Please let us know if you have any further problems.
