### ISSUE TITLE
ArmNN API fails image classification with ONNX Mobilenet model

### ISSUE THREAD

**Issue by bellycat77** [ARM-software/armnn#200]
I use CK software.
There are 2 installed ONNX Mobilenet models:

 - NHWC `$ ck install package --tags=onnx,model,mobilenet,converted,nhwc`
 - NCHW `$ ck install package --tags=onnx,model,mobilenet,converted,nchw`

When I run `program:image-classification-armnn-onnx` and choose NHWC variant - program fails with the message:
```
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unsupported operation Cast for node 'MobilenetV1/Predictions/Reshape__201'  at function LoadGraph [/home/ivan/CK-TOOLS/lib-armnn-19.05-llvm-6.0.0-1ubuntu2-onnx-rel.19.05-tflite-linux-64/src/src/armnnOnnxParser/OnnxParser.cpp:625]
```

When I run `program:image-classification-armnn-onnx` and choose NCHW variant - program fails with a similar message:
```
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unsupported operation Cast for node 'MobilenetV1/Predictions/Reshape__203'  at function LoadGraph [/home/ivan/CK-TOOLS/lib-armnn-19.05-llvm-6.0.0-1ubuntu2-onnx-rel.19.05-tflite-linux-64/src/src/armnnOnnxParser/OnnxParser.cpp:625]
```

For more information on installing CK with ArmNN, please see [ArmNN-MLPerf](https://github.com/ARM-software/armnn-mlperf#gs) instructions.

**Comment by MatthewARM** [comment]
Thanks @bellycat77, so you would like the 'cast' operator to be supported by the ONNX parser?

**Comment by bellycat77** [comment]
Yes, of course. Thanks

**Comment by mseth10** [comment]
Any updates on when more operators will be supported in ONNX runtime? Current operator support is limited https://arm-software.github.io/armnn/latest/parsers.xhtml#S5_onnx_parser 

I am getting similar error for ResNet50_v2 model exported from Apache MXNet.
```
RuntimeError: Unsupported operation Gemm for node 'resnetv20_dense0_fwd'  at function LoadGraph [/home/ubuntu/armnn-dist/armnn/src/armnnOnnxParser/OnnxParser.cpp:708]
```
@MatthewARM

**Comment by FrancisMurtagh-arm** [comment]
Hi @mseth10 

Is it the Dense operator you are missing?
https://mxnet.apache.org/versions/1.8.0/api/python/docs/api/gluon/nn/index.html#mxnet.gluon.nn.Dense
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense

I'll add an internal ticket for us to implement but can't say when that will happen.

We are open to contributions if you are so inclined, this is our guide:
https://www.mlplatform.org/contributing/

Thanks,
Francis.

**Comment by matthewsloyanARM** [comment]
Hi @bellycat77 and @mseth10,

Thank you for reaching out! Based on the updated `README.md` found [here](https://github.com/ARM-software/armnn/tree/master#how-to-get-involved) under the "How to get involved" section we will be closing GitHub issues labeled with "Feature Request". Instead, we will be tracking the issue and adding the "Help wanted" label. All the issues with this label can be found [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). We would much appreciate your help to add these features. If you would like to add this or any feature to Arm NN feel free to reopen this ticket and let us know you are working on it with a quick comment. We will then track the updates and help you get your additions into our codebase.

Below you will find our contributors guide which will show you how you can submit a patch to us. If you have any questions feel free to ask here or by creating a new Issue, thank you!

https://www.mlplatform.org/contributing

Kind regards,

Matthew
