### ISSUE TITLE
what():  Unknown binding input for layer 'data'.  at function GetBindingInfo

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#201]
I am trying to load my Caffe network using the Caffe parser. As suggested in another issue, first I did
```
import caffe
net = caffe.Net("deploy.prototxt", "trained.caffemodel", caffe.TEST)
net.save("outputfile.caffemodel")
```
and then

```
armnnCaffeParser::ICaffeParserPtr parser = armnnCaffeParser::ICaffeParser::Create();
armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("outputfile.caffemodel",
                                { }, // input taken from file if empty
                                { "prob" }); // output node

// Find the binding points for the input and output nodes
armnnCaffeParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo("data");
armnnCaffeParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("prob");
```

However I got the following error:

**terminate called after throwing an instance of 'armnn::InvalidArgumentException'
  what():  Unknown binding input for layer 'data'.  at function GetBindingInfo**

What could be the reason?

**Comment by MatthewARM** [comment]
Is the input layer in your model called 'data'?

**Comment by MatthewARM** [comment]
When you call parser->GetNetworkInputBindingInfo("data"); it needs to be passed the name of the blob that you are using as an input

**Comment by FSetragno** [comment]
This is the beginning of my prototxt file:

```
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 215
  dim: 320
}
```

**Comment by FSetragno** [comment]
Should I use another format for the input layer?

**Comment by MatthewARM** [comment]
Hi sorry @FSetragno I can't think what's going on here, if the input layer is called "data" then GetNetworkInputBindingInfo should return the correct index.

Maybe for some reason the parser isn't auto-detecting the input layer. Please could you try this:
```armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("outputfile.caffemodel",
                                {  "data" },
                                { "prob" }); // output node
```

**Comment by MatthewARM** [comment]
@FSetragno  can you try "input" instead of "data"? I've just run the Caffe parser in a debugger and debugger where we have:

```
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 215
  dim: 320
}
```
in the prototxt, I can see that at CaffeParser.cpp:375, layerParam.name().c_str() is returning "input".

I can't explain this, it must be something strange about how the input layer works in Caffe protocol buffers.

In any case, it would explain why "data" is not working for you, and "input" should be used instead.

Hope this helps,
Matthew

**Comment by FSetragno** [comment]
> Hi sorry @FSetragno I can't think what's going on here, if the input layer is called "data" then GetNetworkInputBindingInfo should return the correct index.
> 
> Maybe for some reason the parser isn't auto-detecting the input layer. Please could you try this:
> 
> ```
> armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("outputfile.caffemodel",
>                                 {  "data" },
>                                 { "prob" }); // output node
> ```

This produces an error:

**no matching function for call to ‘armnnCaffeParser::ICaffeParser::CreateNetworkFromBinaryFile(const char [29], <brace-enclosed initializer list>, <brace-enclosed initializer list>)’**

**Comment by MatthewARM** [comment]
Hi sorry @FSetragno I wasn't clear in https://github.com/ARM-software/armnn/issues/201#issuecomment-499957313.

Due to reasons I don't understand, the layer name in Caffe is "input", not "data". So you need:

```
armnnCaffeParser::ICaffeParserPtr parser = armnnCaffeParser::ICaffeParser::Create();
armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("outputfile.caffemodel",
                                { }, // input taken from file if empty
                                { "prob" }); // output node

// Find the binding points for the input and output nodes
armnnCaffeParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo("input");
armnnCaffeParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("prob");
```

Ie. from your original code, just change "data" to "input" in the call to GetNetworkInputBindingInfo.

**Comment by FSetragno** [comment]
Changing "data" to "input" seems to solve the issue. Thank you.

**Comment by MatthewARM** [comment]
Thanks, I'll close this since your problem is resolved, but I'll try to make sure we don't lose this knowledge.
