### ISSUE TITLE
Where to find the dependencies for armnn/tests?

### ISSUE THREAD

**Issue by zengzengsun** [ARM-software/armnn#202]
I want to do experiment with armnn/tests. But when I add "-DBUILD_TESTS=1" flag to build the tests, cmake error occurs:
CMake Error at tests/CMakeLists.txt:4 (include_directories):
  include_directories given empty-string as include directory.

The 4th line actually is: "include_directories(SYSTEM "${THIRD_PARTY_INCLUDE_DIRS}")"

I think this error is related with what the readme said: "
The armnn/tests directory contains tests used during Arm NN development. Many of them depend on third-party IP, model protobufs and image files not distributed with Arm NN. The dependencies of some of the tests are available freely on the Internet, for those who wish to experiment."

Am I right? If so, could anyone tell me where to get those dependencies?

Thanks a lot!

Best Regards

**Comment by MikeJKelly** [comment]
Hi zengzengsun,

the THIRD_PARTY_INCLUDE_DIRS should be set by line 12 of the root CMakeList.txt file to be "set(THIRD_PARTY_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/third-party)" 

Where are you building this from? Do you have a third-party directory in your root director?

Best regards,
Mike

**Comment by zengzengsun** [comment]
@MikeJKelly 
Thank you very much, Mike~
I updated arm-nn to latest one and the problem is resolved.
I want to test the tflite models with arm-nn like using "TfLiteMnasNet-Armnn".
Do you know where I can download the models like "mnasnet_1.3_224.tflite" and related test data?

**Comment by Surmeh** [comment]
Hi @zengzengsun, the TFLite Mnasnet model can be found https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/hosted_models.md. You can use any test image for the categories mentioned in the TfLiteMnasNet-Armnn.cpp.
I hope this helps. I'm closing this as the original question has been answered, please open a new one if you require further help.

Thanks,
Surabhi
