### ISSUE TITLE
Error in building ComputeLibrary

### ISSUE THREAD

**Issue by rakshithhv** [ARM-software/armnn#204]
I'm working on ubuntu and the following error occurs when trying to build the compute library:

~/armnn-devenv/ComputeLibrary$  scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC" \
>   benchmark_tests=0 validation_tests=0 os=android -j16
scons: Reading SConscript files ...
Mkdir("build")
ERROR: Compiler ' aarch64-linux-android-clang++' not found

**Comment by MatthewARM** [comment]
Hi @rakshithhv you should probably ask this on the Compute Library github, but it looks to me like you need the compiler on your PATH?

That step is documented in https://github.com/ARM-software/armnn/blob/branches/armnn_19_05/BuildGuideAndroidNDK.md, section "Download the Android NDK and make a standalone toolchain".

Good luck,
Matthew

**Comment by rakshithhv** [comment]
Thaank you @MatthewARM that was very helpful.
