### ISSUE TITLE
CMake error while building ArmNN

### ISSUE THREAD

**Issue by rakshithhv** [ARM-software/armnn#205]
I'm using Android NDK to build ArmNN by following the instructions given in [https://github.com/ARM-software/armnn/blob/branches/armnn_19_05/BuildGuideAndroidNDK.md](url).
The following error is displayed while trying to build ArmNN.

CXX=aarch64-linux-android-clang++ \
>  CC=aarch64-linux-android-clang \
>  CXX_FLAGS="-fPIE -fPIC" \
>  cmake .. \
>   -DCMAKE_SYSTEM_NAME=Android \
>   -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
>   -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$HOME/armnn-devenv/toolchains/aarch64-android-r17b/ \
>   -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
>   -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
>   -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
>   -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
>   -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 \
>   -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1 \
>   -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/
CMake Warning at cmake/modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  cmake/modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  cmake/GlobalConfig.cmake:110 (find_package)
  CMakeLists.txt:15 (include)

CMake Warning at cmake/modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  cmake/modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  cmake/GlobalConfig.cmake:110 (find_package)
  CMakeLists.txt:15 (include)

CMake Warning at cmake/modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  cmake/modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  cmake/GlobalConfig.cmake:110 (find_package)
  CMakeLists.txt:15 (include)

CMake Warning at cmake/modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  cmake/modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  cmake/GlobalConfig.cmake:110 (find_package)
  CMakeLists.txt:15 (include)

CMake Warning at cmake/modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  cmake/modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  cmake/modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  cmake/GlobalConfig.cmake:110 (find_package)
  CMakeLists.txt:15 (include)

CMake Error at cmake/modules/FindBoost.cmake:2048 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/GlobalConfig.cmake:110 (find_package)
  CMakeLists.txt:15 (include)

-- Caffe parser support is disabled
-- Tensorflow Lite parser support is disabled
-- Armnn Serializer support is disabled
-- ArmNN Quantizer support is disabled
Including backend common library into the build: /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon/common.cmake
Including backend common library into the build: /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon/common.cmake
Including backend into the build: /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/backend.cmake
Including backend into the build: /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/backend.cmake
Including backend into the build: /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/backend.cmake
Adding object library dependency to armnn: armnnAclCommon
Adding object library dependency to armnn: armnnBackendsCommon
Adding object library dependency to armnn: armnnClBackend
Adding object library dependency to armnn: armnnClBackendWorkloads
Adding object library dependency to armnn: armnnNeonBackend
Adding object library dependency to armnn: armnnNeonBackendWorkloads
Adding object library dependency to armnn: armnnRefBackend
Adding object library dependency to armnn: armnnRefBackendWorkloads
Adding object library dependency to UnitTests: armnnAclCommonUnitTests
Adding object library dependency to UnitTests: armnnBackendsCommonUnitTests
Adding object library dependency to UnitTests: armnnClBackendUnitTests
Adding object library dependency to UnitTests: armnnNeonBackendUnitTests
Adding object library dependency to UnitTests: armnnRefBackendUnitTests
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/samples
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/samples
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/samples
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/samples
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/samples
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/samples
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnTfLiteParser
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnTfLiteParser
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnTfLiteParser
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnTfLiteParser
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnTfLiteParser
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnTfLiteParser
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnSerializer
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnSerializer
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnSerializer
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnSerializer
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnSerializer
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/armnnSerializer
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/aclCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/backendsCommon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/cl/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/neon/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/workloads
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/test
   used as include directory in directory /home/rakshith_hv/armnn-devenv/armnn/src/backends/reference/test

-- Configuring incomplete, errors occurred!
See also "/home/rakshith_hv/armnn-devenv/armnn/build/CMakeFiles/CMakeOutput.log".
See also "/home/rakshith_hv/armnn-devenv/armnn/build/CMakeFiles/CMakeError.log".

**Comment by MatthewARM** [comment]
Hi @rakshithhv it can't find the Boost include files. Have you followed the steps at https://github.com/ARM-software/armnn/blob/branches/armnn_19_05/BuildGuideAndroidNDK.md#build-the-boost-c-libraries?

If you've followed those steps and are still having problems, I'm afraid you'll need to debug why CMake can't find boost. The variable BOOST_ROOT should be set to a path that contains `include` and `lib` directories which contain the boost libraries that you want to use. If you're following the instructions exactly, then this will be in $HOME/armnn-devenv/boost/install

**Comment by lmglmg** [comment]
I fixed this issue by adding `-DCMAKE_FIND_ROOT_PATH=[path to boost installation]` to the cmake invocation. To me, it seems that Android NDK clears the default CMAKE_FIND_ROOT_PATH when building and then `find_path` method in `FindBoost.cmake` could not find those files.

**Comment by Colm-in-Arm** [comment]
Hi @rakshithhv,

Is this still an issue you'd like to work with us on? If I hear nothing back I'll close this in a week or so.

Colm.
