### ISSUE TITLE
Simple script to build armnn

### ISSUE THREAD

**Issue by perise** [ARM-software/armnn#206]
the step by step instructions are too many step. can we give a script to build armnn on different platforms? One click with some selections will easy our life

**Comment by psyhtest** [comment]
Hi @perise,

May I suggest you take a look at the [ArmNN-MLPerf](https://github.com/ARM-software/armnn-mlperf/) repository where we describe how to build ArmNN and run MLPerf Inference workloads with a few simple commands via the [Collective Knowledge](https://cknowledge.org) framework?

**Comment by Colm-in-Arm** [comment]
Hi @perise,

Did you manage to complete the setup? There is also a Docker solution in review right now which might make things easier for you. If I hear nothing back I'll close this in a week or so.

Colm.
