### ISSUE TITLE
ARMNN Quantizer

### ISSUE THREAD

**Issue by ShyamW** [ARM-software/armnn#208]
Hello,

I am trying to quantize this simple_mnist_tf.pb network using the ARMNNQuantizer tool. I have tried to add paramters when cmaking the arm library, but it does not seem to be making the ARMNNQuantizer executable. I am running this command under the build directory:

`cmake .. -DBUILD_ARMNN_QUANTIZER=YES -DBUILD_ARMNN_SERIALIZER=YES -DFLATBUFFERS_INCLUDE_PATH=~/Documents/flatbuffers/include/ -DFLATBUFFERS_LIBRARY=~/Documents/flatbuffers/libflatbuffers.a  -DARMCOMPUTE_ROOT=~/Documents/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=~/Documents/ComputeLibrary/build -DBOOST_ROOT=/usr -DTF_GENERATED_SOURCES=~/Documents/gen  -DBUILD_TF_PARSER=1 -DPROTOBUF_ROOT=/usr`

Here is the tensorflow network binary and the cmakelists.txt
[files.zip](https://github.com/ARM-software/armnn/files/3263021/files.zip)

Does anyone have any advice on how to quantize this network?

**The output of the cmake command is:**

-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   filesystem
--   log
--   program_options
--   date_time
--   log_setup
--   thread
--   regex
--   chrono
--   atomic
-- Flatbuffers headers are located at: /home/a0227521local/Documents/flatbuffers/include
-- Flatbuffers library located at: /home/a0227521local/Documents/flatbuffers/libflatbuffers.a
-- Caffe parser support is disabled
-- Tensorflow Lite parser support is disabled

->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>We JUST ADDED THE QUANTIZER EXECUTABLE!!!!

Including backend common library into the build: /home/a0227521local/Documents/armnn/src/backends/aclCommon/common.cmake
Including backend common library into the build: /home/a0227521local/Documents/armnn/src/backends/backendsCommon/common.cmake
Including backend into the build: /home/a0227521local/Documents/armnn/src/backends/cl/backend.cmake
CL backend is disabled
Including backend into the build: /home/a0227521local/Documents/armnn/src/backends/neon/backend.cmake
NEON backend is disabled
Including backend into the build: /home/a0227521local/Documents/armnn/src/backends/reference/backend.cmake
Adding object library dependency to armnn: armnnBackendsCommon
Adding object library dependency to armnn: armnnClBackend
Adding object library dependency to armnn: armnnNeonBackend
Adding object library dependency to armnn: armnnRefBackend
Adding object library dependency to armnn: armnnRefBackendWorkloads
Adding object library dependency to UnitTests: armnnBackendsCommonUnitTests
Adding object library dependency to UnitTests: armnnRefBackendUnitTests
-- Configuring done
-- Generating done
-- Build files have been written to: /home/a0227521local/Documents/armnn

**And the output after make is:**

[  5%] Built target armnnUtils
[ 24%] Built target armnnRefBackendWorkloads
[ 27%] Built target armnnBackendsCommon
[ 27%] Built target armnnClBackend
[ 28%] Built target armnnNeonBackend
[ 29%] Built target armnnRefBackend
[ 54%] Built target armnn
[ 72%] Built target armnnTfParser
[ 74%] Built target armnnRefBackendUnitTests
[ 78%] Built target armnnBackendsCommonUnitTests
[100%] Built target UnitTests

**Comment by MatthewARM** [comment]
Hi @ShyamW I'm not sure why this is going wrong. It could be that CMake has cached the value of the BUILD_ARMNN_SERIALIZER and BUILD_ARMNN_QUANTIZER variables, and is not using the values you are specifying on the command line. I suggest that you try deleting `CMakeCache.txt` and try again.

Please let me know how you get on - if that doesn't work I'll try to think of something else.

**Comment by ShyamW** [comment]
Ok, I just tried to remove the CMakeCache.txt file, and I still have the same issue. I know that the correct values are being passed to the Cmakefile since the string "->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>We JUST ADDED THE QUANTIZER EXECUTABLE!!!!" is being printed.

Thank you so much for your help so far. Any thoughts are appreciated

**Comment by MatthewARM** [comment]
Hi @ShyamW I'm still working on this... Could you let me know exactly which branch / commit of Arm NN you are using? Many thanks.

**Comment by MatthewARM** [comment]
Hi @ShyamW I think I'm beginning to understand what's going on, it might be to do with the flatbuffers compiler.

Can you insert a debug message into src/armnnSerializer/CMakeLists.txt and where it runs "flatc" print out the path that it's using?

Many thanks,
Matthew

**Comment by MatthewARM** [comment]
Hi @ShyamW I've pushed a patch here: https://review.mlplatform.org/c/ml/armnn/+/1319. Feel free to have a look but I'm now less confident it's related to your issue. When I tried your cmake line it was failing to find the flatbuffers compiler, but it was producing an error message. In your output it looks like it's not simply not processing anything atl all in src/armnnSerializer or src/armnnQuantizer.

**Comment by ShyamW** [comment]
> Hi @ShyamW I think I'm beginning to understand what's going on, it might be to do with the flatbuffers compiler.
> 
> Can you insert a debug message into src/armnnSerializer/CMakeLists.txt and where it runs "flatc" print out the path that it's using?
> 
> Many thanks,
> Matthew

I don't have a CMakeLists.txt file under src/armnnSerializer. I'm built off of branch armnn_19_02, but I tried this before and had the same issue on master. I will try the patch.

Thanks!

**Comment by MatthewARM** [comment]
Please do try to upgrade to 19.05 as there have been loads of improvements in the Quantizer.

**Comment by MohiniMohiniMohini** [comment]
Hi @MatthewARM 
I'm facing the same issue.  With latest code (git clone http://github.com/ARM-software/armnn.git) and the same cmake options mentioned below. Where shall I find the armConverter and/or armnnQuantizer generated after make?

cd /home/admin1/ && git clone http://github.com/ARM-software/armnn.git
cd /home/admin1/armnn && \
    mkdir build && cd build && \
    export CXX=aarch64-linux-gnu-g++ && \
    export CC=aarch64-linux-gnu-gcc && \
    cmake .. \
    -DARMCOMPUTE_ROOT=/home/admin1/armnn-devenv/ComputeLibrary \
    -DARMCOMPUTE_BUILD_DIR=/home/admin1/armnn-devenv/ComputeLibrary/build/ \
    -DBOOST_ROOT=/home/admin1/armnn-devenv/boost_arm64_install/ \
    -DBoost_SYSTEM_LIBRARY=/home/admin1/armnn-devenv/boost_arm64_install/lib/libboost_system.a \
    -DBoost_FILESYSTEM_LIBRARY=/home/admin1/armnn-devenv/boost_arm64_install/lib/libboost_filesystem.a \
    -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 -DBUILD_ARMNN_QUANTIZER=1 -DBUILD_ARMNN_SERIALIZER=1 \
    -DCAFFE_GENERATED_SOURCES=/home/admin1/armnn-devenv/caffe/build/include \
    -DBUILD_CAFFE_PARSER=1 \
    -DPROTOBUF_ROOT=/home/admin1/armnn-devenv/google/x86_64_pb_install/ \
    -DPROTOBUF_LIBRARY_DEBUG=/home/admin1/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.15.0.1 \
    -DPROTOBUF_LIBRARY_RELEASE=/home/admin1/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.15.0.1 \
    -DSAMPLE_DYNAMIC_BACKEND=1 \
    -DDYNAMIC_BACKEND_PATHS=/home/admin1/armnn/src/dynamic/sample \
    -DFLATBUFFERS_ROOT=/home/admin1/armnn-devenv/flatbuffers-1.11.0/arm64_build \
    -DFLATBUFFERS_INCLUDE_PATH=/home/admin1/armnn-devenv/flatbuffers-1.11.0/arm64_build/include \
    -DFLATC=/home/admin1/armnn-devenv/flatbuffers-1.11.0/x86_build/bin/flatc \
    && make -j32

**Comment by keidav01** [comment]
Hi @MohiniMohiniMohini 

An executable should be generated on the top level of your build output directory - ArmnnQuantizer, ArmnnConverter.

Are you not seeing this?

**Comment by MohiniMohiniMohini** [comment]
HI @keidav01 
Yes, it did generate. However I'm not able to execute it to convert a caffe model to .armnn model.

I get "exec error for the binary generated" when I do ./ArmnnConverter on my linux x86 64 bit system

I've tried using qemu to execute this binary. But I get "/lib/ld-linux-aarch64.so.1: No such file or directory" error.

How did you use the ArmnnConverter and ArmnnQuantizer binaries?

**Comment by keidav01** [comment]
From how I understand your response, you seem to be building on x86_64, and attempting to execute the output files ( ArmnnQuantizer ) on aarch64 through Qemu. If you just execute these locally on your x86 machine, they should work. 

If this is not the case, can you please send me the full command you've used for the quantizer and converter please?

Also, could you run an ldd on the ArmnnQuantizer as well please?

**Comment by MohiniMohiniMohini** [comment]
I'm using cross-compilation steps mentioned to build on x86_64. After building successfully I tried ./ArmnnConverter (w/o any arguments) and it said "exec error". So the binary could not be executed on x86_64.

So I installed Qemu to try and run these on x86_64 system as aarch64 which resuilts in "/lib/ld-linux-aarch64.so.1: No such file or directory" error.

About ldd:
"ldd ArmnnQuantizer
not a dynamic executable"

**Comment by keidav01** [comment]
Two possible solutions would be to: 
- Follow this guide for installing the missing library files when running Qemu and try again: https://ughe.github.io/2018/07/19/qemu-aarch64

- Remove the cross-compilation step and build for CpuRef only on x86_64 natively (i.e. with ARMCOMPUTENEON and ARMCOMPUTECL turned off in Cmake). The quantizer should not need CL or NEON, so run your model conversion and quantization in order to attain the model and once you have gotten your model, repeat the cross compilation with CL and NEON turned back on.

**Comment by keidav01** [comment]
I think if you follow this guide for installing the missing library files when running Qemu and try again it should work: https://ughe.github.io/2018/07/19/qemu-aarch64

I was going to suggesting removing the cross-compilation step altogether and build for CpuRef only on x86_64 (i.e. with ARMCOMPUTENEON and ARMCOMPUTECL turned off), but unfortunately I do not think we have any build guides available for this.

**Comment by MohiniMohiniMohini** [comment]
Hi @keidav01,
I came across [this ](https://ughe.github.io/2018/07/19/qemu-aarch64) link but did not try thinking I'm going not in the right direction as no one else faced similar issues. Anyway, now in that direction, the binary can be executed however, I'm facing following error:

terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unsupported layer type 'AnnotatedData'
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted

Its input data layer with type: AnnotatedData and layer name: data.

**Comment by keidav01** [comment]
Hey @MohiniMohiniMohini 

That's great! Could you please tell me what operators/layers are being used in your model (if the list is not exhaustive)?

Is this a custom model?

**Comment by MohiniMohiniMohini** [comment]
Hi @keidav01 
I figured out the reason for that error. I need to use the SSD caffe and not BVLC caffe. I'm working on that.

Also, can you please check this command for me?
./ArmnnConverter -f caffe-binary -m /path-to-caffe-model/ssd.caffemodel -i AnnotatedData -o detection_out -p ssd.armnn

The problem could be that, the last layer detection_out does not have weights and is not included in the weights file. Will it still work?

**Comment by keidav01** [comment]
Are you sure the input and output names are correct for the model? 

You may or may not know that you can use [https://lutzroeder.github.io/netron/](url) to visualise the model and verify the names easily.

**Comment by MohiniMohiniMohini** [comment]
Hi @keidav01 ,

Yes, the layer names are correct. I do use netron to visualize models.
I'm using [Pelee SSD](https://github.com/Robert-JunWang/Pelee) and [this](https://drive.google.com/file/d/1KJHKYQ2nChZXlxroZRpg-tRsksTXUhe9/view) is the model to convert to armnn. I'm also using SSD caffe. If I visualize the Pelee weight file from the link, the first layer is AnotatedData and last layer as mbox_loss however the prototxt has data and detection_out as first and the last layers respectively.
Not sure how is the model gonna be converted only with the weight file correctly.
