### ISSUE TITLE
Mnasnet Model Performance Armnn vs Tensorflow lite 

### ISSUE THREAD

**Issue by kiki-good** [ARM-software/armnn#209]
Hi:

I used Armnn v19.02 release and did the following measurements and comparisons for the inference performance on Mnasnet models between Armnn(Tensorflow lite parser) and Native Tensorflow Lite.  As you can see in the graph, the results shows worse performance in Armnn than Tensorflow lite. It happens in both Cortex A15 and A7. Note: Only CPU, No GPU.

I also did the benchmark for other Tensorflow lite float models, however, showing better performance in Armnn comparing with Tensorflow lite. For example, Mobilenet v2 1.4 224.

So, I am wondering why Mnasnet is slower than Tensorflow lite ?  Is it because recent added operator for Mnasnet is not fully optimised ?  Any idea ?

![Armnn_Performance_Mnasnet](https://user-images.githubusercontent.com/24479391/59137208-7860b880-897e-11e9-9569-d927a2cf17da.jpg)

**Comment by james-conroy-arm** [comment]
Hi kiki-good, I am looking into this now for you.

Could you please confirm that the better performing models (Mobilenet v2 1.4 224) were tested on the same hardware as MnasNet i.e. Cortex-A15 and Cortex-A7? Do you have any higher-end Cortex CPUs that you could compare the MnasNet results with?

Which revision of ArmNN and Compute Library are you using?

I've looked at the MnasNet model. It mainly consists of Conv2D, FusedBatchNorm, DepthwiseConv2dNative and Relu - all supported by ArmNN.

Cheers,
James

**Comment by kiki-good** [comment]
Hi James:

> Could you please confirm that the better performing models (Mobilenet v2 1.4 224) were tested on the same hardware as MnasNet i.e. Cortex-A15 and Cortex-A7

Yes, these tests run on the same hardware (both Cortex-A15 and Cortex A7)

> Do you have any higher-end Cortex CPUs that you could compare the MnasNet results with?

Please let me know what specific higher-end Cortex CPUs you are referring to ? Should it be 64bit ? 

>Which revision of ArmNN and Compute Library are you using?

As mentioned, ArmNN release v19.02 with Arm Compute library v19.02 are used. The reason Arm Compute library v19.02 is used is that ArmNN v19.02 release says it requires v19.02 Arm Compute library at https://github.com/ARM-software/armnn/blob/branches/armnn_19_02/scripts/get_compute_library.sh

> I've looked at the MnasNet model. It mainly consists of Conv2D, FusedBatchNorm, DepthwiseConv2dNative and Relu - all supported by ArmNN.

Yes, for Mnasnet, v19.02 supports it but it is not supported in v18.11 since I get the following errors in v18.11 when inferencing Mnasnet model:

```
1. Failed to parse operator #57 within subgraph #0 error: Operator not supported. subgraph:0 operator:57 opcode_index:0 opcode:0 / ADD
2. Failed to parse operator #62 within subgraph #0 error: Operator not supported. subgraph:0 operator:62 opcode_index:4 opcode:40 / MEAN
```

**Comment by james-conroy-arm** [comment]
Hi @kiki-good,

The versions of ArmNN and Compute Library you are using look fine - all of the operators are supported in the v19.02 release. Thanks for confirming this revision information. The v18.11 error messages you were receiving were due to unsupported operators in the Tensorflow Lite parser.

I would suggest testing MnasNet on a ARMv8-A 64-bit CPU, if possible (e.g. ARM Cortex A53/A57). ArmNN operators are not as well optimised for 32-bit, and in particular 5x5 convolutions and dilated convolutions have further optimisations for the 64-bit Arm architecture. MnasNet features these two types of convolutions.

Cheers,
James

**Comment by james-conroy-arm** [comment]
Hi @kiki-good ,

I have since received some more information from the Compute Library team about your issue. We do not presently optimise 5x5 depthwise dilated convolutions for either 32-bit or 64-bit. We are however working on adding these optimisations soon, which will enhance the MnasNet performance for ArmNN.

May I ask which device(s) are you using, and your use case?

Thanks,
James

**Comment by kiki-good** [comment]
Hi James:

Thanks for the further confirmation.

Could you let me know once these optimizations are done ? 

I am the maintainer of this https://github.com/renesas-rz/meta-renesas-ai
and we use the model for image classification at the moment.

The devices I am using is Renesas RZ/G1

Thanks
Jmqiao

**Comment by james-conroy-arm** [comment]
Hi Jmqiao,

I am currently tracking these optimizations internally and I will update you when they are completed. I think they should be ready for the 19.08 release.

Interesting! We like what you have done with Yocto for ArmNN :)

Cheers,
James

**Comment by james-conroy-arm** [comment]
Hi Jmqiao,

As of our 19.08 release of ArmNN (https://github.com/ARM-software/armnn/releases/tag/v19.08) and Compute Library (https://github.com/ARM-software/ComputeLibrary/releases/tag/v19.08), we now support 5x5 depthwise dilated convolutions. We are interested in seeing how this has improved your MnasNet model performance.

Cheers,
James

**Comment by patersonc** [comment]
Hello @james-conroy-arm 

We've finally got around to updating to v19.08 and re-testing the Mnasnet models.
Performance is now much better on both Arm32 and Arm64 platforms.

![image](https://user-images.githubusercontent.com/24474678/69045043-f628f580-09ed-11ea-8e26-71f3a8e3176d.png)

Thank you for your efforts!

Kind regards, Chris

**Comment by james-conroy-arm** [comment]
Many thanks for the performance numbers Chris.

Cheers,
James

**Comment by kiki-good** [comment]
Closed the issue since performance indeed improved in v19.08
