### ISSUE TITLE
hardware platforms

### ISSUE THREAD

**Issue by uu-kameshm** [ARM-software/armnn#21]
Hi

I see from the documentation that the ARM NN SDK supports Cortex-A, Mali GPUs (ARM Compute Library).
I have below queries:

1. Does this SDK version in Github support Cortex-M CPUs as well (using the CMSIS Library)?

2. When we run the application (that makes use of ARM NN SDK), does it select the underlying hardware automatically (from Cortex-A/Mali GPU etc. available) and run on them? 

3. Could you please suggest the hardware platforms (on which you might have already verified)
for testing functionality of applications using ARM NN SDK for 
- Cortex-A CPUs
- Mali GPUs
- Cortex-M CPUs 

Could you please help clarify on the above.

Thanks
Kamesh

**Comment by Surmeh** [comment]
Hi @uu-kameshm,

1. Cortex-M support is not available in Arm NN at the moment. For running neural networks on Cortex-M you can use CMSIS-NN directly: https://github.com/ARM-software/CMSIS_5.

2. Currently, the hardware can be selected by specifying compute device, e.g. CpuAcc, GpuAcc. 
Please follow the instructions: https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/deploying-a-tensorflow-mnist-model-on-arm-nn/optimize-and-load-onto-compute-device. 
We are working towards having the compute device automatically selected.

3. The hardware platforms we've verified are but not limited to:
Cortex-A CPUs - A53, A73, A55
Mali GPUs - G71 & G72

I hope this clarifies your query,
Surabhi

**Comment by uu-kameshm** [comment]
Hi Surabhi

Thanks, for the reponse.

By hardware platforms, I meant the suggested h/w reference platforms on which the ARM NN might have been already tested (like Raspberry Pi for ARM Cortex-A etc.).

Could you please suggest few h/w reference platforms/boards for Cortex-A and Mali GPUs.

Kamesh

**Comment by Surmeh** [comment]
Hi @uu-kameshm, we have verified ArmNN on Mate9, Mate9-pro, Mate10, Samsung Galaxy S9 and Hikey960. We don't test it on Raspberry Pi regularly, but other people have used it without problems.

Surabhi

**Comment by Surmeh** [comment]
Hi @uu-kameshm I hope that answered your question. Please get back in touch if you need more information.

**Comment by uu-kameshm** [comment]
Hi Surabhi

Thanks for the information. I have few other follow up queries.

1.For the above h/w platforms, could you please mention on which ones ARM NN for Cortex-A CPUs  was tested and on which ones Mali GPUs was tested specifically. 

2.I understand that the OS on the phones could be Android, but could you please let me know which OS was used for Hikey960?

Thank you
Kamesh

**Comment by TelmoARM** [comment]
Hi Kamesh,

Here are the answers to your questions:

1. Cortex-A CPUs: A53, A73, A55
   Mali GPUs: G71 & G72
	
2. The OS we test on the Hikey960 are:
    - Debian Linux 9.0
	- Android 8.1
	
Let us know if you require any more information.

Thanks.
Telmo

**Comment by MatthewARM** [comment]
Hi @dizcza, ArmNN doesn't have any support for CMSIS-NN or Cortex-M at this time.

We're doing some investigations into how inference on Cortex-M can be supported with higher-level tools, and in the meantime you can use CMSIS-NN directly.

All the best,
Matthew
