### ISSUE TITLE
Loading custom images

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#211]
In the mnist_caffe example, the neural network input is defined as

```
std::unique_ptr<MnistImage> input = loadMnistImage(dataDir, testImageIndex);
...
armnn::Status ret = runtime->EnqueueWorkload(networkIdentifier,
                                                 MakeInputTensors(inputBindingInfo, &input->image[0]),
                                                 MakeOutputTensors(outputBindingInfo, &output[0]));
```
Where the MakeInputTensor() function is defined as

```
armnn::InputTensors MakeInputTensors(const std::pair<armnn::LayerBindingId,
    armnn::TensorInfo>& input,
    const void* inputTensorData)
{
    return { { input.first, armnn::ConstTensor(input.second, inputTensorData) } };
}

```
What is the correct procedure to load generic images (not only MNIST)? Is there some documentation available?

**Comment by MatthewARM** [comment]
Hi @FSet89 we have the the developer material at https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides, and other  the documentation links in the main Readme file (https://github.com/ARM-software/armnn/blob/branches/armnn_19_05/README.md). The worked examples in the developer material should illustrate how input data is prepared for Arm NN.

Other than that, the only documentation resource is the API documentation in-line in the code in Doxygen format.  In your case you should look at the documentation for ConstTensor in include/armnn/Tensor.hpp at line 158.

Arm NN is only an ML inference engine, it doesn't perform any kind of image manipulation. You just provide it with floating-point or quantized data as required by your network. In this sense, the EnqueueWorkload method can be seen as a replacement for the 'Forward()' method in the Caffe C++ API. Preparing the ConstTensors for input is equivalent to preparing the Blobs, and most code should port fairly straightforwardly.

Hope that helps,
Matthew

**Comment by FSet89** [comment]
Just for testing purposes, is it sufficient to declare a `float input[SIZE] `and to call `MakeInputTensors()` using this input as in the MNIST example?

**Comment by MatthewARM** [comment]
And put the input tensor data into the array? Sounds good to me.
