### ISSUE TITLE
Inference time very high with custom caffe network

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#212]
I am testing armnn on a Rockchip RK3399 based SBC running Ubuntu 18_04. I have a trained Caffe network similar to Googlenet but with less inception layers and neurons. The inference time using pycaffe and openblas with 2 threads is 0.083 s (~12 FPS).
I compiled the following code based on the MNIST example and providing an empty array as input:

```
// Helper function to make input tensors
armnn::InputTensors MakeInputTensors(const std::pair<armnn::LayerBindingId,
    armnn::TensorInfo>& input,
    const void* inputTensorData)
{
    return { { input.first, armnn::ConstTensor(input.second, inputTensorData) } };
}

// Helper function to make output tensors
armnn::OutputTensors MakeOutputTensors(const std::pair<armnn::LayerBindingId,
    armnn::TensorInfo>& output,
    void* outputTensorData)
{
    return { { output.first, armnn::Tensor(output.second, outputTensorData) } };
}

int main(int argc, char** argv)
{
    float image[1][320][215][3] = {};

	// Import the Caffe model. Note: use CreateNetworkFromTextFile for text files.
    armnnCaffeParser::ICaffeParserPtr parser = armnnCaffeParser::ICaffeParser::Create();
    armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("mymodel.caffemodel",
                                                                   {  }, // input taken from file if empty
                                                                   { "prob" }); // output node

    // Find the binding points for the input and output nodes
    armnnCaffeParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo("input");
    armnnCaffeParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("prob");



    // Optimize the network for a specific runtime compute device, e.g. CpuAcc, GpuAcc
    //armnn::IRuntimePtr runtime = armnn::IRuntime::Create(armnn::Compute::CpuAcc);
    armnn::IRuntime::CreationOptions options;
    armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);
    armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuRef}, runtime->GetDeviceSpec());

    // Load the optimized network onto the runtime device
    armnn::NetworkId networkIdentifier;
    runtime->LoadNetwork(networkIdentifier, std::move(optNet));

    // Run a single inference on the test image
    std::array<float, 2> output;

    for(int i=0; i<100; i++){
        clock_t begin = clock();
        armnn::Status ret = runtime->EnqueueWorkload(networkIdentifier,
                                                     MakeInputTensors(inputBindingInfo, image),
                                                     MakeOutputTensors(outputBindingInfo, &output[0]));

        clock_t end = clock();
        double elapsed_secs = double(end - begin) / CLOCKS_PER_SEC;
        std::cout << elapsed_secs << std::endl;
    }
	return 0;
}
```

The inference time is inexplicably  high, more than 4 seconds. What am I doing wrong? Armnn was compiled with NEON support.

**Comment by MikeJKelly** [comment]
HI,
It looks like you're selecting the reference backend when you Optimize you network:

armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuRef}, runtime->GetDeviceSpec());

Can you change this to use CpuAcc? It should be a lot faster:

armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuAcc}, runtime->GetDeviceSpec());

**Comment by FSet89** [comment]
You are right, the inference time dropped to 0.1s! Not as fast as my reference, but at least it is close. Can you explain me the meaning of this change? Thank you!

**Comment by MatthewARM** [comment]
RK3399 has a Mali T860-MP4 so if you can get OpenCL working on your board you could also check to see if the GpuAcc backend is faster? It may or may not be "depending" on how things are set up.

To really get a boost you could try using our recently added 'Quantizer' tool to convert the network to 8-bit? You'd have to re-check the accuracy of the results to make sure any difference was acceptable, but that can make a massive improvement to speed.

**Comment by MatthewARM** [comment]
Also, make sure you are using the ArmNN profiler, this will show you where the time is going on a layer by layer basis.  There's some documentation for how to enable it in IRuntime.hpp and IProfiler.hpp, if you need any help please let us know.

**Comment by FSet89** [comment]
I tried the quantizer (using a network without normalization, since it is not supported yet). The inference time is the same wrt the .armnn non-quantized model. Moreover, the inference time on the quantized model is much less stable, oscillating between 66 and 190 ms. I am using ExecuteNetwork to perform these tests.

**Comment by Colm-in-Arm** [comment]
Hi @FSet89,

Are you happy that this issue is resolved? If I hear nothing back I'll close this in a week or so.

Colm.
