### ISSUE TITLE
Error using ArmnnQuantizer

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#213]
I compiled armnn including the quantizer. I ran the following command:

`./ArmnnQuantizer -f mymodel.caffemodel -d . -o mymodel_quantized.caffemodel`

But I got the following error:

**terminate called after throwing an instance of 'armnn::ParseException'
  what():  Buffer doesn't conform to the expected Armnn flatbuffers format. size:1113591  at function LoadGraphFromBinary [/home/user/armnn/src/armnnDeserializer/Deserializer.cpp:577]
Aborted**

What is the proper method to call the quantizer?

**Comment by MatthewARM** [comment]
ArmnnQuantiser only reads/writes .armnn format models. It can't write to a .caffemodel because Caffe doesn't support quantisation.

You just need to convert your .caffemodel to .armnn format first (using ArmnnConverter) then run ArmnnQuantizer on the .armnn file.

**Comment by FSet89** [comment]
Thank you. I converted the model to armnn format. Now I am getting another error with the quantozer:

**terminate called after throwing an instance of 'armnn::UnimplementedException'
  what():  VisitNormalizationLayer
Aborted**

**Comment by MatthewARM** [comment]
Ooh, that sounds like a bug. I'll get someone to look into it.

**Comment by arovir01** [comment]
There seems to be no implementation for QuantizerVisitor::VisitNormalizationLayer()

**Comment by FSet89** [comment]
Is there a workaround for this?

**Comment by MatthewARM** [comment]
Hi @FSet89 there's no workaround as such, but you could try to fix it yourself. In src/armnn/QuantizerVisitor.hpp you would add an overload for VisitNormalizationLayer, and in src/armnn/QuanzerVisitor.cpp you would provide an implementation. For the implementation you can follow the pattern of another unary layer such as RsqrtLayer.

**Comment by FSet89** [comment]
So isn't armnn currently supporting the quantization at all? Or is this problem related just to some networks? Can I test the quantization in some way?

**Comment by MatthewARM** [comment]
Hi @FSet89 it's not quantizing "NormalizationLayer". We're looking into it.

**Comment by arovir01** [comment]
This is now fixed in the master branch.
