### ISSUE TITLE
Quantized SSD MobileNet TfLite model outputs incorrect detections

### ISSUE THREAD

**Issue by saeejithnair** [ARM-software/armnn#214]
Hi,

I converted the **Quantized SSD MobileNet** model (obtained from [https://github.com/ARM-software/armnn/blob/branches/armnn_19_05/src/armnnTfLiteParser/TensorFlowLiteSupport.md](https://github.com/ARM-software/armnn/blob/branches/armnn_19_05/src/armnnTfLiteParser/TensorFlowLiteSupport.md)) to a TfLite flatbuffer and tried performing inference using **TfLiteMobileNetSsd-Armnn** with a generic cat image from the internet. However, this fails because the network outputs 5 detections whereas the test expects 1. 

```
root@imx8mmevk:~# TfLiteMobileNetSsd-Armnn -m ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18/ -d data/
ArmNN v20190200

WARNING: Layer of type Activation is not supported on requested backend CpuAcc for data type Unsigned8 (reason: Neon: Logistic Activations unsupported with QAsymm8 data type.), falling back to the next backend.
WARNING: Layer of type DetectionPostProcess is not supported on requested backend CpuAcc for data type Unsigned8 (reason: IsDetectionPostProcessSupported is not implemented [/usr/src/debug/armnn/19.02-r1/git/src/backends/backendsCommon/LayerSupportBase.cpp:124]), falling back to the next backend.
Number of detections is incorrect: Expected (1) but got (5)
Total time for 1 test cases: 0.226 seconds
Average time per test case: 225.980 ms
One or more test cases failed
```

To dig further into the issue, I implemented my own application which takes in an image, does a forward pass on a Quantized MobileNetSSD v1 model using ArmNN's TfLite parser, and prints the output results. Surprisingly, the detections being output by ArmNN are correctly classified but the bounding boxes are completely off - and most of them even have negative coordinates!

```
root@imx8mmevk:~# ./ArmNN_ObjectDetection ./models/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tflite 
ArmNN v20190200

WARNING: Layer of type Activation is not supported on requested backend CpuAcc for data type Unsigned8 (reason: Neon: Logistic Activations unsupported with QAsymm8 data type.), falling back to the next backend.
WARNING: Layer of type DetectionPostProcess is not supported on requested backend CpuAcc for data type Unsigned8 (reason: IsDetectionPostProcessSupported is not implemented [/mnt/i.MX8/mini/fsl-arm-yocto-bsp/bld-xwayland/workspace/sources/armnn/src/backends/backendsCommon/LayerSupportBase.cpp:124]), falling back to the next backend.
 [ DEBUG ] Loaded image and converted it to ArmNN input format
 [ DEBUG ] ArmNN input and output tensors created
 [ DEBUG ] ArmNN inference forward pass completed
 [ DEBUG ] Input frame size has cols=800, rows=600

 [ DEBUG ] Processing outputs from network ./models/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tflite
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 0: top=-4.818478
 [ DEBUG ] ProcessResult processed detection 0. Class: 16, Confidence: 81.250000%, bbox: (left=8.498233, top=-4.818478, right=166.472916, bottom=179.789627)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 1: top=-49.444794
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 1: left=-23.549093
 [ DEBUG ] ProcessResult processed detection 1. Class: 16, Confidence: 75.390625%, bbox: (left=-23.549093, top=-49.444794, right=175.295746, bottom=163.656891)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 2: left=-148.378845
 [ DEBUG ] ProcessResult processed detection 2. Class: 16, Confidence: 74.218750%, bbox: (left=-148.378845, top=16.524876, right=373.317871, bottom=72.485466)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 3: top=-188.953629
 [ DEBUG ] ProcessResult processed detection 3. Class: 16, Confidence: 64.062500%, bbox: (left=20.490427, top=-188.953629, right=75.490601, bottom=399.951233)
 [ DEBUG ] Performing NMS suppression
 [ DEBUG ] Number of objects detected after NMS = 1
 [ DEBUG ] ArmNN output results parsed into detections
 [ DEBUG ] DNN INFERENCE completed using (ARMNN):	
 [ DEBUG ] Total time taken for inference: 221.165986

 [ DEBUG ] Printing post-NMS detected ROIs in frame

<----------- Detection #0 ----------->
Predicted class: 16
Prediction confidence: 81.25 %
Bounding box (type cv::Rect) - X_topLeft:21, Y_topLeft: -8, Width: 418, Height: 368
 [ DEBUG ] Creating VideoWriter object... gstreamer pipeline... outputting to display...

```
Both issues also occur when using the pre-converted starter model prescribed by Tensorflow [https://www.tensorflow.org/lite/models/object_detection/overview#starter_model](https://www.tensorflow.org/lite/models/object_detection/overview#starter_model). The following output is from performing inference using the pre-converted starter model

```
root@imx8mmevk:~# ./ArmNN_ObjectDetection ./models/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite 
ArmNN v20190200

WARNING: Layer of type Activation is not supported on requested backend CpuAcc for data type Unsigned8 (reason: Neon: Logistic Activations unsupported with QAsymm8 data type.), falling back to the next backend.
WARNING: Layer of type DetectionPostProcess is not supported on requested backend CpuAcc for data type Unsigned8 (reason: IsDetectionPostProcessSupported is not implemented [/mnt/i.MX8/mini/fsl-arm-yocto-bsp/bld-xwayland/workspace/sources/armnn/src/backends/backendsCommon/LayerSupportBase.cpp:124]), falling back to the next backend.
 [ DEBUG ] Loaded image and converted it to ArmNN input format
 [ DEBUG ] ArmNN input and output tensors created
 [ DEBUG ] ArmNN inference forward pass completed
 [ DEBUG ] Input frame size has cols=800, rows=600

 [ DEBUG ] Processing outputs from network ./models/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 0: top=-6.685394
 [ DEBUG ] ProcessResult processed detection 0. Class: 16, Confidence: 75.781250%, bbox: (left=42.183277, top=-6.685394, right=161.491180, bottom=151.886490)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 1: left=-41.886475
 [ DEBUG ] ProcessResult processed detection 1. Class: 16, Confidence: 73.046875%, bbox: (left=-41.886475, top=1.109481, right=308.195648, bottom=61.537373)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 2: top=-34.132595
 [ DEBUG ] ProcessResult processed detection 2. Class: 16, Confidence: 68.750000%, bbox: (left=14.107998, top=-34.132595, right=146.943008, bottom=136.924423)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 3: top=-35.377563
 [ DEBUG ] ProcessResult processed detection 3. Class: 16, Confidence: 50.000000%, bbox: (left=18.972836, top=-35.377563, right=261.778717, bottom=72.811447)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 4: top=-144.906601
 [ DEBUG ] ProcessResult processed detection 4. Class: 16, Confidence: 44.921875%, bbox: (left=26.549604, top=-144.906601, right=80.648392, bottom=350.753510)
 [ DEBUG ] ProcessResult processed detection 5. Class: 36, Confidence: 15.625000%, bbox: (left=109.871719, top=122.026382, right=126.310303, bottom=146.048264)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 6: top=-49.675114
 [ DEBUG ] ProcessResult processed detection 6. Class: 16, Confidence: 14.453125%, bbox: (left=24.582218, top=-49.675114, right=216.758728, bottom=23.036142)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 7: left=-6.480072
 [ DEBUG ] ProcessResult processed detection 7. Class: 16, Confidence: 12.109375%, bbox: (left=-6.480072, top=12.824424, right=87.363533, bottom=220.132599)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 8: top=-29.030186
 [ DEBUG ] ProcessResult processed detection 8. Class: 16, Confidence: 12.109375%, bbox: (left=33.146889, top=-29.030186, right=114.196098, bottom=173.680511)
 [ DEBUG ] ERROR: OUTPUT BOUNDING BOX HAS NEGATIVE COORDINATE - Detection 9: left=-39.509235
 [ DEBUG ] ProcessResult processed detection 9. Class: 16, Confidence: 10.937500%, bbox: (left=-39.509235, top=2.167259, right=113.008286, bottom=122.492188)
 [ DEBUG ] Performing NMS suppression
 [ DEBUG ] Number of objects detected after NMS = 1
 [ DEBUG ] ArmNN output results parsed into detections
 [ DEBUG ] DNN INFERENCE completed using (ARMNN):	
 [ DEBUG ] Total time taken for inference: 190.924228

 [ DEBUG ] Printing post-NMS detected ROIs in frame

<----------- Detection #0 ----------->
Predicted class: 16
Prediction confidence: 75.7812 %
Bounding box (type cv::Rect) - X_topLeft:112, Y_topLeft: -12, Width: 317, Height: 316
 [ DEBUG ] Creating VideoWriter object... gstreamer pipeline... outputting to display...
```

Any idea what could be going wrong? My preprocessing stage involves converting from OpenCV's BGR to RGB, resizing it to a 300x300, normalizing it as floats, and then quantizing the normalized data using qParams from the input binding info. It would be tremendously helpful if someone could suggest a way to obtain correct results from MobileNetSSD using ArmNN. 

Thanks!

**Comment by Burton2000** [comment]
You say that classification is correct so seems strange that bbox coordinates wouldn't be correct. Could you check you are interpreting the bbox outputs from the network correctly? What are the raw outputs from the network are they also negative?

The bbox outputs are fractions of the 300x300 input image size so 0.5 would represent pixel 150 etc. Also Maybe something goes wrong when you translate these outputs to your 800x600 original image?

**Comment by saeejithnair** [comment]
Hi @Burton2000, yup I verified that it's an issue with the actual output from the network and not the subsequent interpretation/result-processing. I did a comparison between results obtained with TensorflowLite's interpreter vs ArmNN (using identical models, images, and pre-processing steps). The raw results are as follows:

**Inference performed on coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite using Tensorflow Lite interpreter**

> $ python3 object_detection.py --image ./testImage.jpg --graph ./detect.tflite --labels ./labelmap.txt --show_image True
> Input tensor type checked, floating_model= False
> time spent: 73.04763793945312
> num_boxes: 10.0
> detected boxes: [[[ 0.02252617  0.08912674  0.98623836  0.97961044]
>   [ 0.5845882   0.03529426  1.0093133   0.9939711 ]
>   [ 0.26971373  0.00158674  0.9895148   0.78058034]
>   [ 0.08890253  0.5270627   0.9628015   1.007478  ]
>   [-0.01298752 -0.00022386  0.8116777   0.2947901 ]
>   [-0.00359672 -0.00537446  0.84606653  0.57154167]
>   [ 0.00714596  0.0006981   0.36680257  0.31266576]
>   [ 0.0141484   0.04133621  0.44563985  0.9701822 ]
>   [ 0.7454701   0.01394281  0.99340373  0.93508697]
>   [ 0.515813   -0.00017194  0.7781726   0.19767901]]]
> detected classes: [[16. 64. 64. 16.  0. 16. 42. 64. 64. 15.]]
> detected scores: [[0.75       0.26171875 0.234375   0.1640625  0.15625    0.1484375
>   0.125      0.125      0.125      0.12109375]]
> 

After scaling the output coords for the best detection and drawing a bounding box on the input image, we see
![Tensorflow_output_1](https://user-images.githubusercontent.com/16181437/59534279-d0864600-8ebb-11e9-892c-f13d6235f508.png)

Trying the same thing with ArmNN, I got
**Inference performed on coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite using ArmNN**
> root@imx8mmevk:~# ./Armnn_incorrect ./models/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite ./testImage.jpg 
> ArmNN v20190200
> 
> WARNING: Layer of type Activation is not supported on requested backend CpuAcc for data type Unsigned8 (reason: Neon: Logistic Activations unsupported with QAsymm8 data type.), falling back to the next backend.
> WARNING: Layer of type DetectionPostProcess is not supported on requested backend CpuAcc for data type Unsigned8 (reason: IsDetectionPostProcessSupported is not implemented [/mnt/i.MX8/mini/fsl-arm-yocto-bsp/bld-xwayland/workspace/sources/armnn/src/backends/backendsCommon/LayerSupportBase.cpp:124]), falling back to the next backend.
>  [ DEBUG ] Loaded image and converted it to ArmNN input format
>  [ DEBUG ] ArmNN input and output tensors created
>  [ DEBUG ] ArmNN inference forward pass completed
>  [ DEBUG ] Input frame size has cols=300, rows=300
> 
>  [ DEBUG ] Processing outputs from network ./models/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite
>  [ DEBUG ] num_boxes: 10
>  [ DEBUG ] Detected boxes raw output:
>  [ DEBUG ] [-0.021557, 0.179806, 0.490568, 0.559082]
>  [ DEBUG ] [0.006832, -0.094947, 0.201991, 1.035682]
>  [ DEBUG ] [-0.108064, 0.061922, 0.462126, 0.497762]
>  [ DEBUG ] [-0.462620, 0.121735, 1.138169, 0.299236]
>  [ DEBUG ] [-0.123716, 0.047695, 0.248496, 0.909869]
>  [ DEBUG ] [-0.165584, 0.080528, 0.076787, 0.741689]
>  [ DEBUG ] [0.335040, -0.112198, 0.504308, 0.265944]
>  [ DEBUG ] [0.422189, -0.164619, 0.627471, 0.093570]
>  [ DEBUG ] [0.328970, 0.003361, 0.557065, 0.245785]
>  [ DEBUG ] [-0.101255, 0.099362, 0.574447, 0.373830]
>  [ DEBUG ] detected classes: [16, 16, 16, 16, 16, 16, 64, 64, 42, 16]
>  [ DEBUG ] detected scores: [0.824219, 0.785156, 0.710938, 0.523438, 0.523438, 0.148438, 0.148438, 0.144531, 0.132812, 0.132812]
>  [ DEBUG ] Performing NMS suppression
>  [ DEBUG ] Number of objects detected after NMS = 1
>  [ DEBUG ] ArmNN output results parsed into detections
>  [ DEBUG ] DNN INFERENCE completed using (ARMNN):	
>  [ DEBUG ] Total time taken for inference: 166.478361
> 
>  [ DEBUG ] Printing post-NMS detected ROIs in frame
> 
> <----------- Detection #0 ----------->
> Predicted class: 16
> Prediction confidence: 82.4219 %
> Bounding box (type cv::Rect) - X_topLeft:53, Y_topLeft: -6, Width: 113, Height: 153
> Saved jpg file with resized data.
>  [ DEBUG ] Creating VideoWriter object... gstreamer pipeline... outputting to display...
> 

And the visualized output...
![Armnn_output](https://user-images.githubusercontent.com/16181437/59534470-65893f00-8ebc-11e9-9df8-d8741d278446.jpg)

I don't think the underlying issue here are the negative coordinates since that also occurs for low confidence detections using the TensorflowLite interpreter. **The actual problem seems to be that ArmNN is outputting completely different results when using identical models.** I hope this data clarifies the issue I'm struggling with - please do let me know if there's anything I can clarify further! Thanks!

**Comment by saeejithnair** [comment]
### UPDATE: CpuAcc seems to be the issue

I tried running it using only CpuRef (**no CpuAcc**) and the outputs seem reasonable (they match the results output by TensorflowLite's interpreter more closely). 

> root@imx8mmevk:~# ./Armnn_incorrect ./models/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite ./testImage.jpg 
> ArmNN v20190200
> 
>  [ DEBUG ] Loaded image and converted it to ArmNN input format
>  [ DEBUG ] ArmNN input and output tensors created
>  [ DEBUG ] ArmNN inference forward pass completed
>  [ DEBUG ] Input frame size has cols=300, rows=300
> 
>  [ DEBUG ] Processing outputs from network ./models/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite
>  [ DEBUG ] num_boxes: 10
>  [ DEBUG ] Detected boxes raw output:
>  [ DEBUG ] [0.030082, 0.103605, 0.978682, 0.980125]
>  [ DEBUG ] [0.538158, 0.030954, 1.003624, 0.991784]
>  [ DEBUG ] [0.289888, 0.004357, 0.987291, 0.795761]
>  [ DEBUG ] [-0.000198, -0.001732, 0.681421, 0.294697]
>  [ DEBUG ] [-0.018241, 0.002734, 0.916298, 0.529979]
>  [ DEBUG ] [0.747765, 0.013943, 0.995699, 0.935087]
>  [ DEBUG ] [0.025808, 0.080273, 0.561065, 0.913498]
>  [ DEBUG ] [0.007035, 0.000967, 0.372421, 0.317905]
>  [ DEBUG ] [0.242686, 0.758083, 0.931034, 0.996114]
>  [ DEBUG ] [0.624867, -0.007226, 1.012444, 0.484046]
>  [ DEBUG ] detected classes: [16, 64, 64, 42, 64, 64, 16, 42, 19, 64]
>  [ DEBUG ] detected scores: [0.750000, 0.281250, 0.242188, 0.167969, 0.156250, 0.132812, 0.125000, 0.125000, 0.113281, 0.101562]
>  [ DEBUG ] Performing NMS suppression
>  [ DEBUG ] Number of objects detected after NMS = 1
>  [ DEBUG ] ArmNN output results parsed into detections
>  [ DEBUG ] DNN INFERENCE completed using (ARMNN):	
>  [ DEBUG ] Total time taken for inference: 16762.305228
> 
>  [ DEBUG ] Printing post-NMS detected ROIs in frame
> 
> <----------- Detection #0 ----------->
> Predicted class: 16
> Prediction confidence: 75 %
> Bounding box (type cv::Rect) - X_topLeft:31, Y_topLeft: 9, Width: 262, Height: 284
> Saved jpg file with resized data.
>  [ DEBUG ] Creating VideoWriter object... gstreamer pipeline... outputting to display...
> 

Could there be a bug in terms of losing information when ArmNN falls back to CpuRef from CpuAcc? It's thrown warnings about the Activation and DetectionPostProcess layer not being supported for uint8_t but I figured that it would just continue computations in a non-accelerated manner. 

I'm running on an [NXP i.MX 8M Mini EVK](https://www.nxp.com/support/developer-resources/evaluation-and-development-boards/i.mx-evaluation-and-development-boards/evaluation-kit-for-thebr-i.mx-8m-mini-applications-processor:8MMINILPD4-EVK) with the following configurations:
```
root@imx8mmevk:~# uname -a
Linux imx8mmevk 4.14.78-imx_4.14.78_1.0.0_ga+g94da7bdc489b #1 SMP PREEMPT Sun May 26 00:38:14 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```
```
Build Configuration:
BB_VERSION           = "1.38.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "imx8mmevk"
DISTRO               = "fsl-imx-xwayland"
DISTRO_VERSION       = "4.14-sumo"
TUNE_FEATURES        = "aarch64"
TARGET_FPU           = ""
```

**Comment by Burton2000** [comment]
Thanks for all the info, yep I also have had issues when running SSD Mobilenet with CpuAcc so yes I think there is a bug here when using this backend.

**Comment by MatthewARM** [comment]
Thanks, I'll ask someone from the Compute Library team to have a look

**Comment by saeejithnair** [comment]
Hi @MatthewARM, any updates?

**Comment by morgolock** [comment]
Hi @saeejithnair 

Apologies for the delay in the reply. We identified the problem and we are working on the solution.

We'll let you know as soon as we have a fix.

In the meantime one of the things you could try is this patch:


[memstrat.txt](https://github.com/ARM-software/armnn/files/3355093/memstrat.txt)

**Comment by morgolock** [comment]
Hi @saeejithnair 

Please take a look at the following patch fixing the problem: https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/1620/

There was a bug in Arm Compute Library, the concatenation layer was not setting up the valid region of the output tensor properly.

**Comment by saeejithnair** [comment]
@morgolock Awesome, thank you so much! I built and tested the patch and it seems to be working well now

**Comment by dasol92** [comment]
@saeejithnair Hi. I have a similar issue running **TfLiteMobileNetSsd-Armnn** in ArmNN 19.11
```
root@imx8mqevk:/opt/armnn# TfLiteMobileNetSsd-Armnn --m models -d data
ArmNN v20191100

WARNING: Layer of type DetectionPostProcess is not supported on requested backend CpuAcc for input data type QAsymm8 and output data type Float32 (reason: IsDetectionPostProcessSupported is not implemented [/home/dskim/workdir2/armnn-devenv/armnn/src/backends/backendsCommon/LayerSupportBase.cpp:171]), falling back to the next backend.
Number of detections is incorrect: Expected (1) but got (10)
Total time for 1 test cases: 0.134 seconds
Average time per test case: 134.276 ms
One or more test cases failed
```

Despite applying the patch (https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/1620/), the results are still "Number of detections is incorrect: Expected (1) but got (10)" , there are no output display.

How did you solve? @saeejithnair, I'd appreciate it if you could explain the following in more detail.
> To dig further into the issue, I implemented my own application which takes in an image, does a forward pass on a Quantized MobileNetSSD v1 model using ArmNN's TfLite parser, and prints the output results.

**Comment by saeejithnair** [comment]
Hi @dasol92, if I remember correctly, the issue you're seeing shouldn't have anything to do with the patch. The ArmNN test cases are internal ARM unit tests built for specific models and input images. Using anything else will result in a "failed test case". 

Instead of using the prebuilt ArmNN test case binaries, I'd suggest building a simple application of your own using the ArmNN parser & backend and overlaying the results onto the input image to visualize the inference results.
