### ISSUE TITLE
Armnn Error: Could not initialize the CL runtime

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#215]
I compiled armnn with OpenCL support and I installed OpenCL with
`apt install ocl-icd-opencl-dev`
I tried to run ExecuteNetwork with GpuAcc but I got the following error:
**Armnn Error: Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -1001**
Did I miss something?

**Comment by MikeJKelly** [comment]
Hi FSet89,

what kind of Arm GPU do you have? That error code is CL_PLATFORM_NOT_FOUND_KHR "No valid ICDs found" which could indicates that the CL runtime can't find a valid device.

**Comment by FSet89** [comment]
I have a Mali T860MP4. I didn't install any driver. I found [this library](https://github.com/rockchip-linux/libmali) that maybe can be useful but I don't know how to install it.

**Comment by FSet89** [comment]
I got the same error running arm_compute_benchmark in Compute Library (built without OpenCL support): 
**terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs**

**Comment by MatthewARM** [comment]
Hi @FSet89 I don't know the details of getting OpenCL working on Rockchip platforms, is that something you can get help with on the Rockchip forums? You'll need working OpenCL before the Arm Compute OpenCL code will work.

You might also have some luck asking on the Mali developer community forums.

All the best,
Matthew

**Comment by MatthewARM** [comment]
Closing this. Seems to be an issue with OpenCL installation, not Arm NN
