### ISSUE TITLE
ExecuteNetwork throws error on quantized network

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#217]
I managed to quantize my Caffe network using ArmnnConverter and ArmnnQuantizer. I tried to run ExecuteNetwork on the quantized network but I got the following error:

```
./ExecuteNetwork -f armnn-binary -m mymodel_q.armnn -c CpuAcc -d test_data.txt -i input -o prob
```

**WARNING: Layer of type Normalization is not supported on requested backend CpuAcc for data type Unsigned8 (reason: in validate_arguments src/core/NEON/kernels/NENormalizationLayerKernel.cpp:46: ITensor data type QASYMM8 not supported by this kernel), falling back to the next backend.
ERROR: Layer of type Normalization is not supported on any preferred backend [CpuAcc ]
Armnn Error: Optimize returned nullptr**

Please note that ExecuteNetwork works with the non-quantized network (both the .caffemodel and the .armnn files)

**Comment by arovir01** [comment]
It seems NormalizationLayer does not support QASYMM8 on NEON, only F16 and F32. Try executing with "-c CpuAcc -c CpuRef", so it can fall back to running the normalization workload on the reference backend.

**Comment by FSet89** [comment]
It works but it seems that only CpuRef is used since the inference time is very high. By the way, why is the non-quantized model working with the normalization layer?

**Comment by arovir01** [comment]
CpuRef should only be used for the NormalizationLayer, not the whole network. The order of preference is important, though, so please make sure that CpuAcc is first and CpuRef is second in the list of arguments.

The NEON backend supports floating point types for normalization, therefore I would expect the non-quantized model to run fully on CpuAcc.

**Comment by FSet89** [comment]
`./ExecuteNetwork -f caffe-binary -m mymodel.caffemodel -c CpuAcc -c CpuRef -d test_data.txt -i input -o prob `
**ArmNN v20190500

prob: 0.481831 0.518169 

Inference time: 72.57 ms**


`./ExecuteNetwork -f armnn-binary -m mymodel_quantized.armnn -c CpuAcc -c CpuRef -d test_data.txt -i input -o prob `
**ArmNN v20190500

WARNING: Layer of type Normalization is not supported on requested backend CpuAcc for data type Unsigned8 (reason: in validate_arguments src/core/NEON/kernels/NENormalizationLayerKernel.cpp:46: ITensor data type QASYMM8 not supported by this kernel), falling back to the next backend.
WARNING: Layer of type Normalization is not supported on requested backend CpuAcc for data type Unsigned8 (reason: in validate_arguments src/core/NEON/kernels/NENormalizationLayerKernel.cpp:46: ITensor data type QASYMM8 not supported by this kernel), falling back to the next backend.
Quantization parameters for Softmax layer (Scale: 0.00392157 and Offset: 0) are incorrect and have been updated to Scale: 0.00390625 and Offset: 0
prob: 0.000000 0.000000 

Inference time: 370.64 ms**

**Comment by Colm-in-Arm** [comment]
Hi @FSet89,

Is this still an issue you'd like to work with us on? If I hear nothing back I'll close this in a week or so.

Colm.
