### ISSUE TITLE
Cross compile library

### ISSUE THREAD

**Issue by eleICoto** [ARM-software/armnn#222]
Right now, I have finished building armnn library for my ZCU104, but I'm using vivado sdk as an ide to build my software, so what file should I extract so that I can build armnn software in another toolchain environment.
Thanks

**Comment by MatthewARM** [comment]
Hi @eleICoto the Arm NN build system uses CMake but the code is portable, I guess you could do one of the following:
* Generate Makefiles using CMake then import them into your IDE
* Write a new build system compatible with your IDE following the CMake build system as a model
* Use CMake to generate a compatible build system for your IDE

Hope that helps,
Matthew

**Comment by MatthewARM** [comment]
There are some generic cross-compilation instructions here: https://github.com/ARM-software/armnn/blob/branches/armnn_19_05/BuildGuideCrossCompilation.md#build-armnn basically if all you want to do is override the compiler, you can do that with environment variables.

**Comment by eleICoto** [comment]
@MatthewARM Thanks for your reply, but I fairly new to this kind make and cmake flow, the IDE I'm using is like this 
![image](https://user-images.githubusercontent.com/35992646/60714680-2182da80-9f4e-11e9-9c18-2496361e696a.png)
The makefile is generated by IDE, which I can use GUI to config make setting
![image](https://user-images.githubusercontent.com/35992646/60714762-4414f380-9f4e-11e9-89a0-258fccdff811.png)
The setting I frequently use is this two
Directories
![image](https://user-images.githubusercontent.com/35992646/60714973-96561480-9f4e-11e9-92dd-4bf4dae016d3.png)
Libraries
![image](https://user-images.githubusercontent.com/35992646/60715042-b554a680-9f4e-11e9-9742-7f5023a17e63.png)
Which indicate the -i and -l command in makefile

So right now, I already have the linker library but what file should provide to include library? 

About the instructions page you give to me, do you mean all the file listed in this command is required in order to compile armnn function?
![image](https://user-images.githubusercontent.com/35992646/60715452-9e628400-9f4f-11e9-9e41-1b7c241b94d2.png)

**Comment by MatthewARM** [comment]
Hi @eleICoto the options listed there are for Compute Library CPU and GPU support, and the Caffe parser.

If you don't have OpenCL support then you don't need ARMCOMPUTECL, and if you don't want the Caffe parser you don't need BUILD_CAFFE_PARSER or the PROTOBUF options. 

You do need BOOST and the Compute Library (for NEON support).

Maybe there's something under "Builders" that would let you use an external build system, rather than the build system built into your IDE? Perhaps you can do the CMake step outside your IDE and then configure your IDE to just run "make" to do the build? There are many possibilities.

Another idea would be to ask on the forums / support channel for the IDE whether anyone has good ideas about how to use it with CMake.

Good luck,
Matthew

**Comment by eleICoto** [comment]
@MatthewARM Thanks for your advice, I will post another thread on forums/support to see if there are any ideas

**Comment by eleICoto** [comment]
@MatthewARM Hello, follow your great advice I have been able to cross compile ARM NN code in my IDE. But there is a minor problem, what does this file "libprotobuf.so.15" do? Beside "libarmnn.so" and "libarmnnCaffeParser.so",  "libprotobuf.so.15" is also require for cross compile and code execute.
Thanks a lot.

**Comment by MatthewARM** [comment]
Hi @eleICoto great news and well done!

libpotobuf.so.15 is the protobuf runtime library. That is needed for decoding Tensorflow or Caffe files.

**Comment by eleICoto** [comment]
@MatthewARM Thanks a lot.
For anyone who also has this problem, simply use the include folder as an include folder and copy the three .so file mentioned above to linker library path, then the compiler can compile armnn function.
