### ISSUE TITLE
QSYMM16 build error in master branch

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#224]
I am building armnn (master branch) and I am getting this error:

**armnn/src/backends/aclCommon/ArmComputeTensorUtils.cpp: In function ‘arm_compute::DataType armnn::armcomputetensorutils::GetArmComputeDataType(armnn::DataType)’:
armnn/src/backends/aclCommon/ArmComputeTensorUtils.cpp:27:43: error: ‘QSYMM16’ is not a member of ‘arm_compute::DataType’
             return arm_compute::DataType::QSYMM16;
                                           ^~~~~~~
src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/build.make:62: recipe for target 'src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/ArmComputeTensorUtils.cpp.o' failed
make[2]: *** [src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/ArmComputeTensorUtils.cpp.o] Error 1
CMakeFiles/Makefile2:1005: recipe for target 'src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/all' failed
make[1]: *** [src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2**

**Comment by MatthewARM** [comment]
Hi @FSet89 most likely your compute library is too old, can you get commit 3689fcd5915cd902cb4ea5f618f2a6e42f6dc4a1 ?

There's a script to update the compute library at armnn/scripts/get_compute_library.sh and it's worth running every now and again if you are tracking master.

**Comment by FSet89** [comment]
I cloned Compute Library a few days ago (master branch), I'm not sure that's the problem. I will try with the script.

**Comment by MatthewARM** [comment]
I don't think that the Compute Library team update the master regularly on Github, I think their latest code is only on review.mlplatform.org.

**Comment by MatthewARM** [comment]
@FSet89 Hopefully this is all sorted? I'll close this issue but if you're still having problems please reopen it.
