### ISSUE TITLE
Could not find output layer in quantized network

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#225]
I quantized my custom network and I ran ExecuteNetwork both on the original and quantized model. I got this error only on the quantized model:
`
./ExecuteNetwork -f caffe-binary -m mymodel_quantized.caffemodel -c CpuAcc -i input  -d test_data.txt -o prob `

**ArmNN v20190500
Armnn Error: Couldn't find requested output layer 'prob' in graph**

**Comment by arovir01** [comment]
I presume you have verified that the output layer is indeed called 'prob' and not something else?

**Comment by FSet89** [comment]
yes, the inference command works with the same non-quantized network

**Comment by MatthewARM** [comment]
yes, I think the output name must have changed. It's worth checking. 

Out of interest, which quantisation tooling are you using with Caffe?

**Comment by FSet89** [comment]
The one provided in armnn:

```
cd armnn/build
./ArmnnConverter -f caffe-binary -m mymodel.caffemodel -i input  -o prob -p ./mymodel_converted.armnn
./ArmnnQuantizer -f mymodel_converted.armnn -d . -o mymodel_quantized.caffemodel
```
How can I check that the name has changed in the caffemodel?

**Comment by MatthewARM** [comment]
Ah that's interesting, "./ArmnnQuantizer -f mymodel_converted.armnn -d . -o mymodel_quantized.caffemodel" will have written the model in .armnn format (Arm NN has no code for creating caffe files, only for reading them). You're then reading it as a caffe-binary model (should be armnn-binary), but the error message is misleading.

Can you retry with "./ExecuteNetwork -f armnn-binary -m mymodel_quantized.caffemodel -c CpuAcc -i input -d test_data.txt -o prob" ?

We'll have to look in to why the error message is wrong.

**Comment by FSet89** [comment]
I got the following:

**WARNING: Layer of type Normalization is not supported on requested backend CpuAcc for data type Unsigned8 (reason: in validate_arguments src/core/NEON/kernels/NENormalizationLayerKernel.cpp:46: ITensor data type QASYMM8 not supported by this kernel), falling back to the next backend.
ERROR: Layer of type Normalization is not supported on any preferred backend [CpuAcc ]
Armnn Error: Optimize returned nullptr**

**Comment by MatthewARM** [comment]
Ah yes, there's no quantised NormalizationLayer in Compute Library (as per #217) so you'll need to enable the CpuRef backend.

**Comment by FSet89** [comment]
using armnn-binary and enabling CpuRef solves the issue. The inference time is high, I think that's because CpuRef is called.

**Comment by MatthewARM** [comment]
Cool.

We'll have to think about what to do with those NormalizationLayers. In more advanced quantisation tools (e.g. tflite_convert) the normalisation layers are folded into the quantisation parameters.
