### ISSUE TITLE
include <malloc.h> not as portable as include <stdlib.h>

### ISSUE THREAD

**Issue by ens-lg4** [ARM-software/armnn#227]
Could you please replace the `#include <malloc.h>` command in `src/armnn/test/FloatingPointConverterTest.cpp` by `#include <stdlib.h>`?

This should increase the portability for systems that do not have `malloc.h` (`stdlib.h` imports `malloc.h` when it is needed).

Many thanks in advance!

**Comment by MatthewARM** [comment]
Sure, no problem.

Rather than wait for us to do small stuff like this you can always send a patch to https://review.mlplatform.org/admin/repos/ml/armnn

**Comment by arovir01** [comment]
I don't think we even use anything from malloc.h in that test, so we might just as well remove the include altogether.

________________________________

**Comment by MatthewARM** [comment]
Yeah, looks like iostream and algorithm are also unnecessary!

**Comment by james-conroy-arm** [comment]
Try this ArmNN link if the one above doesn't work for you: https://review.mlplatform.org/#/admin/projects/ml/armnn

**Comment by MatthewARM** [comment]
Review is at https://review.mlplatform.org/#/c/ml/armnn/+/1539/

**Comment by MatthewARM** [comment]
Fixed in master towards 19.08
