### ISSUE TITLE
Change the memory policy 

### ISSUE THREAD

**Issue by ValentinoPeluso** [ARM-software/armnn#228]
Hi, 
In Arm Compute Library, it is possible to select different memory policies. 
For instance, this can be done using the following line of code:
```
arm_compute::MEMInfo::set_policy(arm_compute::MemoryPolicy::MINIMIZE);
```

How can we change the memory policy in ARM NN?

**Comment by MatthewARM** [comment]
ArmNN doesn't touch the MEMInfo API (leaves it all at defaults) so you can just call set_policy in your program before creating the Arm NN Runtime.
