### ISSUE TITLE
Compatibility : experimental/filesystem unavailable in some versions of LLVM compiler/library

### ISSUE THREAD

**Issue by ens-lg4** [ARM-software/armnn#229]
Dear developers,

I noticed that some versions of LLVM (including the MacOS derivatives) do not have support for `#include <experimental/filesystem>` in their version of `libc++` library.  Which causes the compilation of `armnnTfLiteParser/test/Activations.cpp.o` to fail.

So on a Mac I either had to compile without TFlite support or turn off the unit tests.
However it seems that the functionality from `#include <experimental/filesystem>` is not actually used, since when I commented out this line, the compilation just continued. Could this `#include` line be removed?

**Comment by MatthewARM** [comment]
Yep, happy for unused stuff to be removed. `experimental/filesystem` should not be included, as we're using `boost/filesystem` anyway and only in `test/LoadModel.cpp`. I'll happily +2 a change on this, otherwise I'll get round to it in the next couple of days.

**Comment by MatthewARM** [comment]
FIxed by aab709b3598b07223ba2da1ab8a18f95e30ff70d
