### ISSUE TITLE
Mixed up header file names for SoftmaxLayer.hpp and Pooling2dLayer.hpp

### ISSUE THREAD

**Issue by YayuNi** [ARM-software/armnn#23]
Pooling2dLayer class declaration is placed in SoftmaxLayer.hpp, while SoftmaxLayer class declaration is placed in Pooling2dLayer.hpp.

**Comment by Surmeh** [comment]
Thanks for pointing this out @YayuNi. We'll provide a fix in the future release.

Surabhi
