### ISSUE TITLE
CLTuner with ArmNN Problem

### ISSUE THREAD

**Issue by waynexhsieh** [ARM-software/armnn#230]
How can I use CLTuner with ArmNN?
I always fail with set IGpuAccTunedParameters to the CreationOptions
Is there any sample how to use CLTuner with ArmNN?

**Comment by MatthewARM** [comment]
Hi @waynexhsieh I don't think we have an example, however the Android NNAPI driver uses the tuner interface, so it could be helpful.

https://github.com/ARM-software/android-nn-driver/blob/9972b4012765ba659a4a693d3e918c89f71eda7c/ArmnnDevice.cpp#L61

The steps are:
1. create an `armnn:IGpuAccTunedParameters` with the options you want
2. load the tuning file
3. put the `armnn:IGpuAccTunedParameters` into the `m_GpuAccTunedParameters` of your `armnn::IRuntime::CreationOptions`
4. Call `armnn::IRuntime::Create` as usual

**Comment by waynexhsieh** [comment]
Hi @MatthewARM  , thank you for your support. I have a question:

ArmNN can use fp16 quantize mode with set reduceFp32ToFp16=true, does cltuner improve fp16 mode performance?

**Comment by MatthewARM** [comment]
Hi @waynexhsieh definitely yes!

**Comment by MatthewARM** [comment]
Closing as the question has been answered.
