### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by ShyamW** [ARM-software/armnn#231]
Just wondering, when I say model.run() are multiple threads executing? In other words, can I have multiple threads calling that at the same time? @MatthewARM

**Comment by MatthewARM** [comment]
Hi @ShyamW currently you can run multiple models at the same time, but you can't run the same model in multiple threads. Does that help? 

It's not a fundamental limitation as such, just that at the moment some memory is owned by the model, so could get trashed by multiple threads using it at once.
