### ISSUE TITLE
Prelu layer support in armnnCaffeParser

### ISSUE THREAD

**Issue by gobotix** [ARM-software/armnn#232]
Hi,
I've been trying to load a Caffe model with a Prelu layer. 
I built the latest ComputeLibrary and Armnn, however, it seems support hasn't been added to the armnnCaffeParser yet. When will this be added?

The following error is found when parsing the network:
`terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unsupported layer type: 'PReLU' for layer 142  at function LoadNetParam [/armnn/src/armnnCaffeParser/CaffeParser.cpp:1722]`

Thanks,
Ben

**Comment by MatthewARM** [comment]
Hi @gobotix we're hoping to fit that into the 19.11 release (November 2019)

**Comment by gobotix** [comment]
That's great but unfortunately I need a lot sooner :-) I've tried to add a method myself to parse it, but when parsing the network it complains that the layer isn't connected correctly.

> terminate called after throwing an instance of 'armnn::LayerValidationException'
>   what():  Input connection #1 must be connected for Prelu layer 142  at function ValidateTensorShapesFromInputs [/home/ben/Code/arm/armnn/src/armnn/layers/PreluLayer.cpp:100]

I've created this method for parsing the layer CaffeParser.cpp, are there any obvious errors as it looks like it is connected correctly:
void CaffeParserBase::ParsePReluLayer(const LayerParameter& layerParam)
```
{
    ValidateNumInputsOutputs(layerParam, 1, 1);

    const string& name = layerParam.name();


    const TensorInfo& inputInfo = GetArmnnOutputSlotForCaffeTop(layerParam.bottom(0)).GetTensorInfo();
    IConnectableLayer* const newLayer = m_Network->AddPreluLayer(name.c_str());
  
    GetArmnnOutputSlotForCaffeTop(layerParam.bottom(0)).Connect(newLayer->GetInputSlot(0));
    newLayer->GetOutputSlot(0).SetTensorInfo(inputInfo);
    SetArmnnOutputSlotForCaffeTop(layerParam.top(0), newLayer->GetOutputSlot(0));
}

```

**Comment by MatthewARM** [comment]
Prelu is quite new, we've only just added it. Having a look, it seems that the "alpha" parameter (I don't know what this is called in Caffe) is taken via a connection. So you need to find the blob representing alpha in the Caffe model and connect it up to input '1'.

**Comment by gobotix** [comment]
I've had a stab but for some reason my input and output sizes of the Prelu layer are not correct and the validate function fails with:

> terminate called after throwing an instance of 'armnn::LayerValidationException'
>   what():  PreluLayer: TensorShape set on OutputSlot[0] does not match the inferred shape. : [11,64,32,32] != [11,64,32,64]
> Aborted (core dumped)
> 

```
void CaffeParserBase::ParsePReluLayer(const LayerParameter& layerParam)
{
    ValidateNumInputsOutputs(layerParam, 1, 1);

    const string& name = layerParam.name();
    const TensorInfo& inputInfo = GetArmnnOutputSlotForCaffeTop(layerParam.bottom(0)).GetTensorInfo();


    armnn::TensorInfo info2 = inputInfo;
	armnn::TensorShape shape2 = info2.GetShape();
	std::cout << "Tensor: " << name << std::endl;
	std::cout << " -  " << "TensorInfo: Dims():" << shape2.GetNumDimensions() << std::endl;
	std::cout << " -  " << "TensorInfo: NumElements():" << shape2.GetNumElements() << std::endl;
	std::cout << " -  " << "TensorInfo: GetShape():" << shape2 << std::endl;
	std::cout << " -  " << "TensorInfo: GetNumBytes():" << info2.GetNumBytes() << std::endl;
	    IConnectableLayer* const newLayer = m_Network->AddPreluLayer(name.c_str());
  
    // connect the alpha values through a constTensor to the 2nd input (1)
    const BlobProto& blob = layerParam.blobs(boost::numeric_cast<int>(0));
    size_t blobSize = boost::numeric_cast<size_t>(blob.data_size());

  

    unsigned int shape[]  = {static_cast<unsigned int>(blobSize)};
    vector<float> alphaData( blobSize);

    std::cout<<"blobsize:" << blobSize  << " batchSize:"<< inputInfo.GetShape()[0] << " PreluInput0 size:" << inputInfo.GetShape()[1] << std::endl;
    GetDataFromBlob(layerParam, alphaData, 0);
    TensorInfo alphaOutputInfo(1, shape, armnn::DataType::Float32);
    ConstTensor alpha(alphaOutputInfo, alphaData);
    std::string nameAlpha = "alphaData_";
    nameAlpha+=name.c_str();
    IConnectableLayer* const alphaLayer =  m_Network->AddConstantLayer(alpha, nameAlpha.c_str());
    alphaLayer->GetOutputSlot(0).Connect(newLayer->GetInputSlot(1));

    alphaLayer->GetOutputSlot(0).SetTensorInfo(alphaOutputInfo);
    newLayer->GetInputSlot(1).GetConnection()->SetTensorInfo(alphaOutputInfo);

    // connect the first input
    GetArmnnOutputSlotForCaffeTop(layerParam.bottom(0)).Connect(newLayer->GetInputSlot(0));
    newLayer->GetOutputSlot(0).SetTensorInfo(inputInfo);
    SetArmnnOutputSlotForCaffeTop(layerParam.top(0), newLayer->GetOutputSlot(0));

}
```

Apologies in advance but I'm new to armNN ... and I haven't been able to find much documentation on how to use these layers apart from in the CaffeParser.cpp...

**Comment by MatthewARM** [comment]
@gobotix no need to apologise, this stuff is very new and there's practically no documentation.

We're putting in Prelu to meet the specification of the Android NNAPI: https://android.googlesource.com/platform/hardware/interfaces/+/refs/heads/master/neuralnetworks/1.2/types.hal#3697 perhaps the Android version and the Caffe version have some minor incompatibility that we can work around?

It looks to me like you're setting the same shape on the input and output of your Prelu (`newLayer->GetOutputSlot(0).SetTensorInfo(inputInfo);`) if "broadcasting" is happening then this won't be true. Broadcasting will happen if the size of one of the dimensions of the alpha tensor is greater than one, and the corresponding dimension in the input tensor has size 1. In this case, the input tensor will be 'replicated' to fill in that dimension.

I think there's some utility code in the parser already to handle this stuff.

**Comment by gobotix** [comment]
Hi,
So I think I have the Alpha blob being correctly resized according to batch size and passed to the PReLU layer as ConstTensor... This assumes the blob dim size of the trained alpha values are same number of elements as the "channel" dimension. Which I think works for our application but not sure if works for all. Also I haven't handled the channel_shared flag or Filler_Parameter if used.

I'll provide the code once done some further validation testing...

**Comment by td-embeans** [comment]
Hello friends, 

I have tried the second referenced code with my MTCNN model. Currently I have only trying the P-Net layer model to complete validation. 

I am getting this below error : 

root@h3ulcb:~# ./mnist_caffe 
CaffeParserBase::ParseInputLayer
CaffeParserBase::ParseConvLayer
Tensor: PReLU1
 -  TensorInfo: Dims():4
 -  TensorInfo: NumElements():1000
 -  TensorInfo: GetShape():[1,10,10,10]
 -  TensorInfo: GetNumBytes():4000
blobsize:10 batchSize:1 P[   36.365487] audit: type=1701 audit(1567153800.475:3): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=4075 comm="mn1
reluInput0 size:10
CaffeParserBase::ParsePoolingLayer
CaffeParserBase::ParseConvLayer
Tensor: PReLU2
 -  TensorInfo: Dims():4
 -  TensorInfo: NumElements():144
 -  TensorInfo: GetShape():[1,16,3,3]
 -  TensorInfo: GetNumBytes():576
blobsize:16 batchSize:1 PreluInput0 size:16
CaffeParserBase::ParseConvLayer
Tensor: PReLU3
 -  TensorInfo: Dims():4
 -  TensorInfo: NumElements():32
 -  TensorInfo: GetShape():[1,32,1,1]
 -  TensorInfo: GetNumBytes():128
blobsize:32 batchSize:1 PreluInput0 size:32
CaffeParserBase::ParseSplitLayer
CaffeParserBase::ParseConvLayer
CaffeParserBase::ParseSoftmaxLayer
create net
bind
terminate called after throwing an instance of 'armnn::LayerValidationException'
  what():  PreluLayer: TensorShape set on OutputSlot[0] does not match the inferred shape. : [1,16,3,3] != [1,16,3,16]
Aborted (core dumped)

I am understanding the Android reference you have given here and trying to look into the original code in the Caffe parser from caffe repo code. Any help will be welcome. 

Regards
TD

**Comment by td-embeans** [comment]
Any update on this ?

**Comment by MikeJKelly** [comment]
Hi td-embeans,

it looks like your output shape doesn't match up. The size of the output should be the maximum size along each dimension of the input operands, it starts with the trailing dimensions and works its way back. 

In this case it looks like your input is [1,16,3,3] and your alpha is [16] so your output will be [1,16,3,16]. 

If you want an output of [1,16,3,3] you could maybe give it an alpha tensor of [16,1,1]?

Yours
Mike

**Comment by Colm-in-Arm** [comment]
Hi @td-embeans,

Is this still an issue you'd like to work with us on? If I hear nothing back I'll close this in a week or so.

Colm.

**Comment by gobotix** [comment]
I wrote the PRELU parser myself but it doesn't handle all variants of it so would prefer a full version provided by yourselves if you are going to provide it as part of the CaffeParser?

**Comment by Colm-in-Arm** [comment]
Hi @gobotix,

There are no short term plans to add PRELU to the Caffe parser. We would welcome your version of it. It would go through the review process and we can help fill in the gaps.

Colm.

**Comment by giovanichiachia** [comment]
Hi @gobotix 

Your updated code would be of great help for us to build upon. Could you please share it?

Regards,
Giovani

**Comment by giovanichiachia** [comment]
> I've had a stab but for some reason my input and output sizes of the Prelu layer are not correct and the validate function fails with:
> 
> > terminate called after throwing an instance of 'armnn::LayerValidationException'
> > what():  PreluLayer: TensorShape set on OutputSlot[0] does not match the inferred shape. : [11,64,32,32] != [11,64,32,64]
> > Aborted (core dumped)
> 
> ```
> void CaffeParserBase::ParsePReluLayer(const LayerParameter& layerParam)
> {
>     ValidateNumInputsOutputs(layerParam, 1, 1);
> 
>     const string& name = layerParam.name();
>     const TensorInfo& inputInfo = GetArmnnOutputSlotForCaffeTop(layerParam.bottom(0)).GetTensorInfo();
> 
> 
>     armnn::TensorInfo info2 = inputInfo;
> 	armnn::TensorShape shape2 = info2.GetShape();
> 	std::cout << "Tensor: " << name << std::endl;
> 	std::cout << " -  " << "TensorInfo: Dims():" << shape2.GetNumDimensions() << std::endl;
> 	std::cout << " -  " << "TensorInfo: NumElements():" << shape2.GetNumElements() << std::endl;
> 	std::cout << " -  " << "TensorInfo: GetShape():" << shape2 << std::endl;
> 	std::cout << " -  " << "TensorInfo: GetNumBytes():" << info2.GetNumBytes() << std::endl;
> 	    IConnectableLayer* const newLayer = m_Network->AddPreluLayer(name.c_str());
>   
>     // connect the alpha values through a constTensor to the 2nd input (1)
>     const BlobProto& blob = layerParam.blobs(boost::numeric_cast<int>(0));
>     size_t blobSize = boost::numeric_cast<size_t>(blob.data_size());
> 
>   
> 
>     unsigned int shape[]  = {static_cast<unsigned int>(blobSize)};
>     vector<float> alphaData( blobSize);
> 
>     std::cout<<"blobsize:" << blobSize  << " batchSize:"<< inputInfo.GetShape()[0] << " PreluInput0 size:" << inputInfo.GetShape()[1] << std::endl;
>     GetDataFromBlob(layerParam, alphaData, 0);
>     TensorInfo alphaOutputInfo(1, shape, armnn::DataType::Float32);
>     ConstTensor alpha(alphaOutputInfo, alphaData);
>     std::string nameAlpha = "alphaData_";
>     nameAlpha+=name.c_str();
>     IConnectableLayer* const alphaLayer =  m_Network->AddConstantLayer(alpha, nameAlpha.c_str());
>     alphaLayer->GetOutputSlot(0).Connect(newLayer->GetInputSlot(1));
> 
>     alphaLayer->GetOutputSlot(0).SetTensorInfo(alphaOutputInfo);
>     newLayer->GetInputSlot(1).GetConnection()->SetTensorInfo(alphaOutputInfo);
> 
>     // connect the first input
>     GetArmnnOutputSlotForCaffeTop(layerParam.bottom(0)).Connect(newLayer->GetInputSlot(0));
>     newLayer->GetOutputSlot(0).SetTensorInfo(inputInfo);
>     SetArmnnOutputSlotForCaffeTop(layerParam.top(0), newLayer->GetOutputSlot(0));
> 
> }
> ```
> 
> Apologies in advance but I'm new to armNN ... and I haven't been able to find much documentation on how to use these layers apart from in the CaffeParser.cpp...

Here's a working version of the code @gobotix posted before.

`void CaffeParserBase::ParsePReluLayer(const LayerParameter& layerParam)
{
    ValidateNumInputsOutputs(layerParam, 1, 1);

    const string& name = layerParam.name();
    const TensorInfo& inputInfo = GetArmnnOutputSlotForCaffeTop(
        layerParam.bottom(0)).GetTensorInfo();

    armnn::TensorInfo info2 = inputInfo;
    armnn::TensorShape shape2 = info2.GetShape();

    IConnectableLayer* const newLayer = m_Network->AddPreluLayer(name.c_str());

    // connect the alpha values through a constTensor to the 2nd input (1)
    const BlobProto& blob = layerParam.blobs(boost::numeric_cast<int>(0));
    size_t blobSize = boost::numeric_cast<size_t>(blob.data_size());

    const unsigned int shape[4]  = {
        static_cast<unsigned int>(1),
        static_cast<unsigned int>(blobSize),
        static_cast<unsigned int>(1),
        static_cast<unsigned int>(1)};

    vector<float> alphaData(blobSize);

    GetDataFromBlob(layerParam, alphaData, 0);
    TensorInfo alphaOutputInfo(4, shape, armnn::DataType::Float32);
    ConstTensor alpha(alphaOutputInfo, alphaData);
    std::string nameAlpha = "alphaData_";
    nameAlpha+=name.c_str();
    IConnectableLayer* const alphaLayer =  m_Network->AddConstantLayer(
        alpha, nameAlpha.c_str());
    alphaLayer->GetOutputSlot(0).Connect(newLayer->GetInputSlot(1));

    alphaLayer->GetOutputSlot(0).SetTensorInfo(alphaOutputInfo);
    newLayer->GetInputSlot(1).GetConnection()->SetTensorInfo(alphaOutputInfo);

    // connect the first input
    GetArmnnOutputSlotForCaffeTop(layerParam.bottom(0)).Connect(
        newLayer->GetInputSlot(0));
    newLayer->GetOutputSlot(0).SetTensorInfo(inputInfo);
    SetArmnnOutputSlotForCaffeTop(
        layerParam.top(0), newLayer->GetOutputSlot(0));

}`

**Comment by giovanichiachia** [comment]
Here is a working version of the code @gobotix posted before.

``void CaffeParserBase::ParsePReluLayer(const LayerParameter& layerParam)
{
    ValidateNumInputsOutputs(layerParam, 1, 1);

    const string& name = layerParam.name();
    const TensorInfo& inputInfo = GetArmnnOutputSlotForCaffeTop(
        layerParam.bottom(0)).GetTensorInfo();

    armnn::TensorInfo info2 = inputInfo;
    armnn::TensorShape shape2 = info2.GetShape();

    IConnectableLayer* const newLayer = m_Network->AddPreluLayer(name.c_str());

    // connect the alpha values through a constTensor to the 2nd input (1)
    const BlobProto& blob = layerParam.blobs(boost::numeric_cast<int>(0));
    size_t blobSize = boost::numeric_cast<size_t>(blob.data_size());

    const unsigned int shape[4]  = {
        static_cast<unsigned int>(1),
        static_cast<unsigned int>(blobSize),
        static_cast<unsigned int>(1),
        static_cast<unsigned int>(1)};

    vector<float> alphaData(blobSize);

    GetDataFromBlob(layerParam, alphaData, 0);
    TensorInfo alphaOutputInfo(4, shape, armnn::DataType::Float32);
    ConstTensor alpha(alphaOutputInfo, alphaData);
    std::string nameAlpha = "alphaData_";
    nameAlpha+=name.c_str();
    IConnectableLayer* const alphaLayer =  m_Network->AddConstantLayer(
        alpha, nameAlpha.c_str());
    alphaLayer->GetOutputSlot(0).Connect(newLayer->GetInputSlot(1));

    alphaLayer->GetOutputSlot(0).SetTensorInfo(alphaOutputInfo);
    newLayer->GetInputSlot(1).GetConnection()->SetTensorInfo(alphaOutputInfo);

    // connect the first input
    GetArmnnOutputSlotForCaffeTop(layerParam.bottom(0)).Connect(
        newLayer->GetInputSlot(0));
    newLayer->GetOutputSlot(0).SetTensorInfo(inputInfo);
    SetArmnnOutputSlotForCaffeTop(
        layerParam.top(0), newLayer->GetOutputSlot(0));

}

**Comment by matthewsloyanARM** [comment]
Hi @gobotix, @td-embeans and @giovanichiachia, 

Unfortunately with the upcoming Arm NN release (21.05) we will be deprecating the Arm NN Caffe Parser, so we won't be able to make this contribution. Based on this I will close this Issue and remove the "Help wanted" label.

We appreciate all your efforts and your work on this. If you would like to help again with the development of Arm NN feel free to take a look at the help wanted section [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). You can also find our contributors guide [here](https://www.mlplatform.org/contributing) which will show you how you can submit a patch to us. Thank you, all the best!

Kind regards, 

Matthew
