### ISSUE TITLE
YOLO anchor

### ISSUE THREAD

**Issue by eleICoto** [ARM-software/armnn#233]
Is there any way that I can inference a YOLOV2 anchor using armnn?

**Comment by MatthewARM** [comment]
Hi @eleICoto maybe, I don't think we support the whole YOLOv2 model though (missing "ExtractImagePatches") so it might need some work on the model to get something compatible. Alternatively I think we work OK with YOLO v2 Tiny?

**Comment by eleICoto** [comment]
Hi @MatthewARM That would be awesome, right now I have managed to get the anchor output but I stuck with the post-process, do you have any idea that I can solve this problem? And how can I get more tutorial about armnn? The example on minst is quite not enough for me to figure out how armnn work with caffe model. 
Thanks!

**Comment by MatthewARM** [comment]
Hi @eleICoto can you provide the model? And a link to the version of Caffe that you are using?

There are three main sources of documentation:
* Reference documentation in the code (Doxygen, Readme files, etc)
* How-to guides on developer.arm.com
* Examples at https://github.com/ARM-software/ML-examples

Hope that helps,
Matthew

**Comment by MatthewARM** [comment]
Hi @eleICoto I hope everything is going well. I'll close this old issue but if you have any further questions please get back in touch.
