### ISSUE TITLE
Cross compile x86_64 flatbuffers problem

### ISSUE THREAD

**Issue by dorforer** [ARM-software/armnn#235]
Hello!
I'm trying to cross compile my armnn to use libarmnnTfLiteParse,
all packages work good but flatbuffers.
I've tried to cross compile it using:
`CXX=aarch64-linux-gnu-g++ CC=aarch64-linux-gnu-gcc CXX_FLAGS="-fPIC" cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release`
But when I compile the armnn package I get the error:
`/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld:flatbuffers/libflatbuffers.a(util.cpp.o): Relocations in generic ELF (EM: 62)
`
and:
`flatbuffers/libflatbuffers.a: error adding symbols: File in wrong format
`
Does anyone encountered this problem?

**Comment by arovir01** [comment]
Does -DFLATBUFFERS_ROOT point to the correct folder in your build command?

**Comment by dorforer** [comment]
I did, but apparently I did not do the correct cross compile of that package,
so I built it on my arm board and transferred it to x86 computer, an it worked.
