### ISSUE TITLE
EnqueueWorkload blocks process every once in a while

### ISSUE THREAD

**Issue by dorforer** [ARM-software/armnn#236]
I'm running a tflite model on an Arm Mali-T760 with gpu acceleration (with the cpuRef or cpuAcc optimization the network seems to run without any problems). I run the tflite network using "EnqueueWorkload" function, the function works and gives good results for a while but then gets stuck and its thread is blocked (like some kind of infinity loop or deadlock).

It gerts stuck on: output->Execute(); in LoadedNetwork.cpp file.
After deep debugging I found out that the block happens after the final layer in  CopyMemGenericWorkload class inside WorloadUtils.hpp in the function "CopyTensorContentsGeneric" on line:

        `srcData = static_cast<const uint8_t *>(srcTensor->Map());`

I'm looking for any hints about the my problematic inputs or the hardware / kernel.

Thanks in advance, Dor

**Comment by MatthewARM** [comment]
Ah, if it's hanging in "Map()", that's the synchronisation point for OpenCL - ie. the OpenCL code on the GPU has to finish before the CPU can "Map" and read the results.

You might be able to see error messages from the Mali driver if you run `dmesg`. If it's a Mali issue then we may have to hook in the GPU support team. Do you know which version of the driver you are using?

If you turn on ArmNN's debugging  ("m_Debug=true" in OptimizerOptions) then ArmNN will call Map() on every intermediate value in the network. Then the problematic one would have to be the layer immediately preceding where it hangs.

**Comment by gobotix** [comment]
Hi,
I think I have a similar issue. When I try to run 2 separate threads in 2 different loaded network IDs it hangs. GDB is showing a mutex wait, why would have 2 seperate threads on two seperate networks cause it to hang? Note it only does this using CpuACC neon backend and not the GPU backend (using mali Opencl).

I've included GDB back trace below for 2 threads... any ideas?
Thanks,
Ben

> #0  0x0000007fb7d1f5f0 in __lll_lock_wait (futex=futex@entry=0x5555f31b18, private=0) at lowlevellock.c:43
#1  0x0000007fb7d187d4 in __GI___pthread_mutex_lock (mutex=0x5555f31b18) at pthread_mutex_lock.c:78
#2  0x0000007fb71897a8 in arm_compute::CPPScheduler::run_workloads(std::vector<std::function<void (arm_compute::ThreadInfo const&)>, std::allocator<std::function<void (arm_compute::ThreadInfo const&)> > >&) () at /home/od/Code/arm/armnnBuild/libarmnn.so
#3  0x0000007fb718927c in arm_compute::CPPScheduler::schedule(arm_compute::ICPPKernel*, arm_compute::IScheduler::Hints const&) ()
    at /home/od/Code/arm/armnnBuild/libarmnn.so
#4  0x0000007fb7216b60 in arm_compute::(anonymous namespace)::Fallback<float, float>::run() ()
    at /home/od/Code/arm/armnnBuild/libarmnn.so
#5  0x0000007fb7217be4 in arm_compute::NEGEMMAssemblyDispatch::run() () at /home/od/Code/arm/armnnBuild/libarmnn.so
#6  0x0000007fb7211d5c in arm_compute::NEGEMM::run() () at /home/od/Code/arm/armnnBuild/libarmnn.so
#7  0x0000007fb723f034 in arm_compute::NEWinogradConvolutionLayer::run() () at /home/od/Code/arm/armnnBuild/libarmnn.so
#8  0x0000007fb70710c0 in armnn::NeonConvolution2dWorkload::Execute() const () at /home/od/Code/arm/armnnBuild/libarmnn.so
#9  0x0000007fb6fb0d8c in armnn::LoadedNetwork::Execute() () at /home/od/Code/arm/armnnBuild/libarmnn.so
#10 0x0000007fb6fb3480 in armnn::LoadedNetwork::EnqueueWorkload(std::vector<std::pair<int, armnn::ConstTensor>, std::allocator<std::pair<int, armnn::ConstTensor> > > const&, std::vector<std::pair<int, armnn::Tensor>, std::allocator<std::pair<int, armnn::Tensor> > > const&) () at /home/od/Code/arm/armnnBuild/libarmnn.so
#11 0x0000005555563698 in PnetStage::get_proposals(cv::Mat const&, float, unsigned long) (this=this@entry=0x5555f2f5b0, img=..., scale=<optimized out>, level=level@entry=0) at /home/od/Code/arm/aa/minipipe/PnetStageCaffe.cpp:298
#12 0x0000005555563b30 in PnetStage::infer(cv::Mat const&) (this=0x5555f2f5b0, img=...)
    at /home/od/Code/arm/aa/minipipe/PnetStageCaffe.cpp:43
#13 0x0000005555560eb4 in MiniPipe::operator()() (this=0x55567c8248) at /home/od/Code/arm/aa/minipipe/mainAndroidTest.cpp:84
#14 0x0000005555561850 in std::__invoke_impl<void, MiniPipe>(std::__invoke_other, MiniPipe&&) (__f=...)
    at /usr/include/c++/7/bits/invoke.h:60
#15 0x0000005555561850 in std::__invoke<MiniPipe>(MiniPipe&&) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#16 0x0000005555561850 in std::thread::_Invoker<std::tuple<MiniPipe> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=<optimized out>)
    at /usr/include/c++/7/thread:234
#17 0x0000005555561850 in std::thread::_Invoker<std::tuple<MiniPipe> >::operator()() (this=<optimized out>)
    at /usr/include/c++/7/thread:243
#18 0x0000005555561850 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<MiniPipe> > >::_M_run() (this=<optimized out>)
    at /usr/include/c++/7/thread:186
#19 0x0000007fb6466d44 in  () at /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#20 0x0000007fb7d16088 in start_thread (arg=0x7fffffef1f) at pthread_create.c:463
#21 0x0000007fb62434ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Other thread:

> #0  0x0000007fb7d1f5f0 in __lll_lock_wait (futex=futex@entry=0x5555f31b18, private=0) at lowlevellock.c:43
#1  0x0000007fb7d187d4 in __GI___pthread_mutex_lock (mutex=0x5555f31b18) at pthread_mutex_lock.c:78
#2  0x0000007fb7189634 in arm_compute::CPPScheduler::Thread::wait() () at /home/od/Code/arm/armnnBuild/libarmnn.so
#3  0x0000007fb7189840 in arm_compute::CPPScheduler::run_workloads(std::vector<std::function<void (arm_compute::ThreadInfo const&)>, std::allocator<std::function<void (arm_compute::ThreadInfo const&)> > >&) () at /home/od/Code/arm/armnnBuild/libarmnn.so
#4  0x0000007fb718927c in arm_compute::CPPScheduler::schedule(arm_compute::ICPPKernel*, arm_compute::IScheduler::Hints const&) ()
    at /home/od/Code/arm/armnnBuild/libarmnn.so
#5  0x0000007fb7216b60 in arm_compute::(anonymous namespace)::Fallback<float, float>::run() ()
    at /home/od/Code/arm/armnnBuild/libarmnn.so
#6  0x0000007fb7217be4 in arm_compute::NEGEMMAssemblyDispatch::run() () at /home/od/Code/arm/armnnBuild/libarmnn.so
#7  0x0000007fb7211d5c in arm_compute::NEGEMM::run() () at /home/od/Code/arm/armnnBuild/libarmnn.so
#8  0x0000007fb723f034 in arm_compute::NEWinogradConvolutionLayer::run() () at /home/od/Code/arm/armnnBuild/libarmnn.so
#9  0x0000007fb70710c0 in armnn::NeonConvolution2dWorkload::Execute() const () at /home/od/Code/arm/armnnBuild/libarmnn.so
#10 0x0000007fb6fb0d8c in armnn::LoadedNetwork::Execute() () at /home/od/Code/arm/armnnBuild/libarmnn.so
#11 0x0000007fb6fb3480 in armnn::LoadedNetwork::EnqueueWorkload(std::vector<std::pair<int, armnn::ConstTensor>, std::allocator<std::pair<int, armnn::ConstTensor> > > const&, std::vector<std::pair<int, armnn::Tensor>, std::allocator<std::pair<int, armnn::Tensor> > > const&) () at /home/od/Code/arm/armnnBuild/libarmnn.so
#12 0x0000005555563698 in PnetStage::get_proposals(cv::Mat const&, float, unsigned long) (this=this@entry=0x5555f2eba0, img=..., scale=<optimized out>, level=level@entry=0) at /home/od/Code/arm/aa/minipipe/PnetStageCaffe.cpp:298
#13 0x0000005555563b30 in PnetStage::infer(cv::Mat const&) (this=0x5555f2eba0, img=...)
    at /home/od/Code/arm/aa/minipipe/PnetStageCaffe.cpp:43
#14 0x0000005555560eb4 in MiniPipe::operator()() (this=0x55594cd928) at /home/od/Code/arm/aa/minipipe/mainAndroidTest.cpp:84
#15 0x0000005555561850 in std::__invoke_impl<void, MiniPipe>(std::__invoke_other, MiniPipe&&) (__f=...)
    at /usr/include/c++/7/bits/invoke.h:60
#16 0x0000005555561850 in std::__invoke<MiniPipe>(MiniPipe&&) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#17 0x0000005555561850 in std::thread::_Invoker<std::tuple<MiniPipe> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=<optimized out>)
    at /usr/include/c++/7/thread:234
#18 0x0000005555561850 in std::thread::_Invoker<std::tuple<MiniPipe> >::operator()() (this=<optimized out>)
    at /usr/include/c++/7/thread:243
#19 0x0000005555561850 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<MiniPipe> > >::_M_run() (this=<optimized out>)
    at /usr/include/c++/7/thread:186
#20 0x0000007fb6466d44 in  () at /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#21 0x0000007fb7d16088 in start_thread (arg=0x7fffffef1f) at pthread_create.c:463
#22 0x0000007fb62434ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

**Comment by MatthewARM** [comment]
Thanks @gobotix as discussed on the Compute Library issue, the CPU issue is a different bug to the GPU issue reported by @dorforer and is fixed in the next release.

@dorforer I hope you are able to try the debugging steps in my earlier reply?

**Comment by dorftemi** [comment]
@MatthewARM I turned out to be gou problem as you mentioned. I had to do some kernel changes using our Linux team and now everything works. Thank you.

**Comment by MatthewARM** [comment]
Awesome, thanks
