### ISSUE TITLE
How to Reduce Libraries Size

### ISSUE THREAD

**Issue by ilous12** [ARM-software/armnn#239]
Hi @MatthewARM 

I'm having a bit of a problem trying to use "armnn 19.05" on android.
Here's a list of the armnn library file sizes for each build:(we are using tfite model)
├── [9.5M]  libarmnn.so
├── [467K]  libarmnnTfLiteParser.so

Can you tell me about How to Reduce Libraries Size.(option, setting.. etc)

We used belows.

> CXX=aarch64-linux-android-clang++ \
>  CC=aarch64-linux-android-clang \
>  CXX_FLAGS="-fPIE -fPIC" \
>  cmake .. \
>   -DCMAKE_BUILD_TYPE=Release \
>   -DCMAKE_SYSTEM_NAME=Android \
>   -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
>   -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$HOME/armnn-devenv/toolchains/aarch64-android-r16b/ \
>   -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
>   -DARMCOMPUTE_ROOT=$PWD/../third-party/ComputeLibrary \
>   -DARMCOMPUTE_BUILD_DIR=$PWD/../third-party/ComputeLibrary/build \
>   -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
>   -DARMCOMPUTENEON=0 -DARMCOMPUTECL=1 \
>   -DBUILD_TF_PARSER=0 \
>   -DBUILD_TF_LITE_PARSER=1 \
>   -DBUILD_ARMNN_SERIALIZER=0 \
>   -DBUILD_UNIT_TESTS=0 \
>   -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ \
>   -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/ \
>   -DTF_LITE_GENERATED_PATH=$HOME/armnn-devenv/google/tensorflow/tensorflow/contrib/lite/schema \
>   -DFLATBUFFERS_ROOT=$HOME/armnn-devenv/google/flatbuffers/arm64_install \

**Comment by MatthewARM** [comment]
The easiest thing would be to "optimise for space" in your Compute Library and ArmNN builds. 

For ArmNN I would do this by using `-DCMAKE_CXX_FLAGS_RELEASE="-Os"`. For Compute Library I think you add `extra_cxx_flags="-Os"` to the scons line.

This should hopefully knock off enough size to make a difference. After that we'd have to do optimisations on the code. Do you have a target size in mind?

**Comment by MatthewARM** [comment]
Another thing that occurs to me is if this is for a single application, you could statically link everything then strip symbols. That could make a big difference. Even if you need it as a shared library you could probably strip the symbols out of everything except the `.dynsym` section and that would help a lot.

**Comment by Colm-in-Arm** [comment]
Hi @ilous12,

Did @MatthewARM suggestions work for you? If I hear nothing back I'll close this in a week or so.

Colm.
