### ISSUE TITLE
Build error with option " BUILD_TESTS "   'stb_image.h' file not found

### ISSUE THREAD

**Issue by atrah22** [ARM-software/armnn#24]
Hello,

I could successfully build UnitTests and it worked on Galaxy S8.

I want to build the InceptionV3 and other CNN models provided in the "armnn/tests" folder.

I made one change in the cmake/GlobalConfig.cmake file. The change is at the line 4 as follows:
option(BUILD_TESTS "Build test applications" ON) 

So this should build the examples of tests folder. However, The cmake command is same as UnitTest cmake command:
CXX=aarch64-linux-android-clang++ \
 CC=aarch64-linux-android-clang \
 CXX_FLAGS="-fPIE -fPIC" \
 cmake .. \
  -DCMAKE_SYSTEM_NAME=Linux \
  -DCMAKE_EXE_LINKER_FLAGS=-pie \
  -DARMCOMPUTE_ROOT=/home/atul/git_work/ARM/armnn-devenv/ComputeLibrary/ \
  -DARMCOMPUTE_BUILD_DIR=/home/atul/git_work/ARM/armnn-devenv/ComputeLibrary/build \
  -DBOOST_ROOT=/home/atul/git_work/ARM/armnn-devenv/boost/install/ \
  -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 \
  -DTF_GENERATED_SOURCES=/home/atul/git_work/ARM/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1 \
  -DPROTOBUF_ROOT=/home/atul/git_work/ARM/armnn-devenv/google/arm64_pb_install/

I received the error with make command:

make -j16
[  1%] Building CXX object tests/CMakeFiles/inferenceTest.dir/InferenceTest.cpp.o
[  1%] Building CXX object tests/CMakeFiles/inferenceTest.dir/InferenceTestImage.cpp.o
[  2%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/HeapProfiling.cpp.o
[  3%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/Logging.cpp.o
[  3%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/Permute.cpp.o
[  3%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/DotSerializer.cpp.o
[  3%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/LeakChecking.cpp.o
/ARM/armnn-devenv/armnn/tests/InferenceTestImage.cpp:15:10: fatal error:
      'stb_image.h' file not found
#include <stb_image.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [tests/CMakeFiles/inferenceTest.dir/InferenceTestImage.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [tests/CMakeFiles/inferenceTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Linking CXX static library libarmnnUtils.a
[  3%] Built target armnnUtils
make: *** [all] Error 2

**Comment by MatthewARM** [comment]
Hi @atrah22 those tests depend on some third-party IP that we can't distribute, and they aren't yet part of our supported product (hence no documentation for them...) but they do contain some interesting and useful example code.

stb_image is a lightweight open source image handling library which you can get from https://github.com/nothings/stb

After you've got the tests to compile, most of them will require hard-coded model protobufs and image files that we can't distribute. Probably the best thing for you to do would be to treat them as a starting point for your own testing.

The most useful program in that folder is 'ExecuteNetwork', which can take any model, and any input tensor, and simply prints out the output tensor. Hopefully its internal command-line documentation will provide enough information for you to make use of it.

All the best,
Matthew

**Comment by Surmeh** [comment]
Hi @atrah22, I hope you've managed to solve the problem. Please get back in touch if you have any more problems.

Thanks,
Surabhi
