### ISSUE TITLE
"CreateWorkload" tests use invalid bias 

### ISSUE THREAD

**Issue by rhughesgeomerics** [ARM-software/armnn#240]
The function CreatePreCompiledWorkloadTest in src\armnn\test\CreateWorkload.hpp specifies a bias with a 4D shape.

The validation functions in WorkloadData.cpp however, ensure that any bias specified using the public API is 1D.

This means that the tests ran using CreatePreCompiledWorkloadTest have two problems:
1. They are not testing 1D bias properly, which is the case that is always used
2. Backends are required to support 4D tensors in addition to 1D tensors in order to pass tests, which is an unnecessary requirement.

**Comment by arovir01** [comment]
This seems to be indeed the case, well spotted. We'll fix the test.
