### ISSUE TITLE
Arm NN run on GPU 

### ISSUE THREAD

**Issue by pineapple121** [ARM-software/armnn#242]
Hi，everyone！
I have run Arm NN UnitTests successfuly on HiKey960 with mali GPU, but now I need to run my project on other board, which doesn't have mali GPU, so I want to know can the Arm NN and Compute Library's GPU optimization work on other GPU? Such as PowerVR GX6650.

**Comment by MatthewARM** [comment]
Hi @pineapple121 as long as you have NEON instructions you can use our CPU code. If you want to try the GPU code then it should be functional as long as you have an OpenCL 1.2 implementation, but it's hard to predict what the performance will be, and there may be minor issues to work around.

**Comment by pineapple121** [comment]
OK，I will try , Thank you very much.

**Comment by MatthewARM** [comment]
Good luck, please get back in touch if you have any problems!
