### ISSUE TITLE
ARM NN multiple outputs

### ISSUE THREAD

**Issue by idenc** [ARM-software/armnn#243]
I'm stuck on trying to run a .tflite model with multiple outputs. I've based my script on [this](https://github.com/ARM-software/ML-examples/tree/master/armnn-mnist) repo. I grab all the output info through GetNetworkOUtputBindingInfo, but MakeOutputTensors only accepts a single output's info and a single array. If I try to run on just one output I get the error:
`terminate called after throwing an instance of 'armnn::InvalidArgumentException'
  what():  No tensor supplied for output 23296
`
EnqueueWorkload seems to only accept a single output tensor as well. I'm pretty stuck on this and would greatly appreciate some help. Thanks!

**Comment by Burton2000** [comment]
Construct the output tensors manually. For example with a network with 4 outputs:

```
// Initialise vectors to store output from network.
std::vector<float> output0(outputBindingInfo0.second.GetShape().GetNumElements());
std::vector<float> output1(outputBindingInfo1.second.GetShape().GetNumElements());
std::vector<float> output2(outputBindingInfo2.second.GetShape().GetNumElements());
std::vector<float> output3(outputBindingInfo3.second.GetShape().GetNumElements());
    
// Make armnn output tensors.
armnn::OutputTensors outputTensors{
    {outputBindingInfo0.first, armnn::Tensor(outputBindingInfo0.second, output0.data())},
    {outputBindingInfo1.first, armnn::Tensor(outputBindingInfo1.second, output1.data())},
    {outputBindingInfo2.first, armnn::Tensor(outputBindingInfo2.second, output2.data())},
    {outputBindingInfo3.first, armnn::Tensor(outputBindingInfo3.second, output3.data())}
};
```

You can now pass outputTensors to EnqueueWorkload as normal.

**Comment by idenc** [comment]
Thank you!

**Comment by ShailendraSSY** [comment]
Hi..
We are writing one heterogeneous framework where we are using ARMNN internally.
Our framework support single/multiple input and single/multiple output.
Please suggest how to support this multiple input and multiple output scenario at run time.
As input to our framework will change and hence may have sinle  input or multiple input graph.
Similarly output of the network may ne single or multiple.
Currently we are able to support single input and single output.
Please guide us how to create multiple output and multiple out tensor at runtime.


Regards
Shailendra

**Comment by MatthewARM** [comment]
HI @ShailendraSSY please can you open a new Issue for this question? It makes it easier to track which conversations are active.

**Comment by ShailendraSSY** [comment]
Yes sure I will open a new issue for this.
