### ISSUE TITLE
Input/Output workload deployment policy

### ISSUE THREAD

**Issue by sunshinemyson** [ARM-software/armnn#244]
Hi Team,

This is an optimization request.

I am play ARMNN with my very naive backend prototype. Basicly, My backend will support **convolution** and **input/output** layer is supported, suppose we have a network :
**inputLayer ->depthwiseconv -> Convolution -> pooling -> convolution ->pooling > output,**

once i tried to deploy this network with **MyBackend and CpuRef** backend, it should be 
**[MyBackend] inputLayer -> [CpuRef] CopyLayer -> [CpuRef]depthwiseconv -> [MyBackend]CopyLayer -> [MyBackend] Conv -> [cpu] Pooling -> [MyBackend] Conv ->[CpuRef] CopyLayer ->[CpuRef]Pooling ->[MyBackend] CopyLayer -> [MyBackend] OuptutLayer**

There are two copy Layer after inputlayer and before output layer, I think those two layers can be erase out because they just did copy. My very beginning idea is that we can add an affinity attribute to backend, especially for input/output.

**Comment by DerekLambertiOfArm** [comment]
Hi, 

You are quite correct in that the MemCopy workloads on Input and Output can be elided. In fact, for many use cases the copies within the input and output can be elided too. 

We are in the process of introducing a new zero copy mechanism to backends. Some of this is already in master. This can be enabled by implementing the new ITensorHandleFactory interface and overloading the relevant new functions in the IBackendInternal interface as well as the ITensorHandle interface. 

There should be more concrete examples soon as we implement this for the CpuRef, CpuAcc and GpuAcc backends. The aim is to have this ready for the 19.08 release but you can see the progress so far in master.

Once this is done, and your backend is updated to use the new API, you should see far fewer copies and possibly even zero if your backend can support memory import/export.

Hope that helps,
Derek

**Comment by MatthewARM** [comment]
Hi @sunshinemyson hopefully the extra copy layers have disappeared now?

**Comment by Colm-in-Arm** [comment]
No response from @sunshinemyson. We can close this now.
