### ISSUE TITLE
The questions about backend developement...?

### ISSUE THREAD

**Issue by victor0623** [ARM-software/armnn#245]
Hi ARM support,

I am trying to add a new backend to the ARM NN framework.

Here are some questions:
(1) How to decide the priority of backends?
ex: for the same operation, CpuAcc is the first priority, CpuRef is the second.

(2) Which one is the best reference among CpuAcc, CpuRef, GpuAcc?

Thanks!

B.R.
Victor

**Comment by jimfly01** [comment]
>>Here are some questions:
>>(1) How to decide the priority of backends?
>>ex: for the same operation, CpuAcc is the first priority, CpuRef is the second.

In General backends will be ordered by performance, fastest first as it is assumed you want the inference to run as quickly as possible. The normal ordering for the three backends that ship with ArmNN is GpuAcc, CpuAcc, CpuRef 

>>(2) Which one is the best reference among CpuAcc, CpuRef, GpuAcc?

How do you mean 'best reference'? Is it which one is the best example? That would depend on what you need them for. The GpuAcc and CpuAcc delegate calls the Compute Library Framework... if you are writing a backend that calls into an acceleration library then these show one way of doing it. The CpuRef contains the workload code as well as the layers and executes functionality unaccelerated on the CPU... if you are experimenting with new layer types and are unconcerned with performance for the moment then the CpuRef backend might be the one to study.

**Comment by victor0623** [comment]
Hi Jim,

Thanks for the reply.

For (1), can I modify the priority via source codes?

For (2), yes, it means the best example for reference. I will take CpuRef as the example.

Thanks!

B.R.
Victor

**Comment by jimfly01** [comment]
>> For (1), can I modify the priority via source codes?

Yes when you make the call to Optimize your graph i.e. INetwork::Optimize(const INetwork& network,
                              const std::vector<BackendId>& backendPreferences,
                              const IDeviceSpec& deviceSpec,
                              const OptimizerOptions& options = OptimizerOptions(),
                              Optional<std::vector<std::string>&> errMessages = EmptyOptional());

The backendPreferences argument holds the priority list of backends that you want the workloads to be created on. 

Note: we have added a facility for adding your own dynamically loadable backend described in this design note: https://developer.mlplatform.org/w/arm_nn/design_notes/dynamic_backend_loading/

and you can look at the unit test suite for this feature at ./src/backends/backendsCommon/test/DynamicBackendTests.cpp/.hpp for more examples of use

**Comment by victor0623** [comment]
Hi Jim,

Got it.
Thanks for the info.

I will close this issue.

B.R.
Victor
