### ISSUE TITLE
An appropriate way to add printed debug logs?

### ISSUE THREAD

**Issue by victor0623** [ARM-software/armnn#246]
Hi ARM support,

I am tracing the source codes of Arm NN.
I will add the following code section in the beginning of a file when I want to print some debug messages:
#include <iostream>
using namespace std;

Then use:
std::cout << "Test..." << endl;

Is there any more appropriate way for achieving this goal?

Thanks!

B.R.
Victor

**Comment by sunshinemyson** [comment]
Hi Victor,

You can use BOOST_LOG_TRIVIAL().

**Comment by victor0623** [comment]
> Hi Victor,
> 
> You can use BOOST_LOG_TRIVIAL().

Hi,

Thanks for the reply.

To use BOOST_LOG_TRIVIAL(), we still need to add the following line in the file:
#include <boost/log/trivial.hpp>

B.R.
Victor

**Comment by MatthewARM** [comment]
Hope your question is answered OK, please reopen if you still need help.
