### ISSUE TITLE
The simplest way to test LSTM functionality

### ISSUE THREAD

**Issue by victor0623** [ARM-software/armnn#247]
Hi ARM support,

I know that the full UNIT_TEST include the LSTM test.
However, the amount of test cases is so many.

Is there a way to test LSTM functionality simply?

Thanks!

B.R.
Victor

**Comment by MatthewARM** [comment]
Like a simple network for LSTM? You could develop one with TfLite, e.g. https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/examples/lstm/g3doc then load the TfLite file in ArmNN?

**Comment by kejriwalnishant1990** [comment]
Hi @MatthewARM Does ARMNN support LSTM layers? Can i deploy keras trained LSTM model on ARM board using armnn library?

**Comment by matthewsloyanARM** [comment]
Hi @kejriwalnishant1990,

Yes Arm NN supports LSTM in the TFLite Parser and TFLite Delegate. You will need to convert the model to a TFLite format however to be able to use it as we don't support Keras models directly. This can be achieved using the [TFLiteConverter](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter).

I will close this issue as it is quite old but hopefully the above answers your question and you have found a solution. If you have an questions or problems feel free to reopen this ticket or create a new one. Thank you!

Kind regards,

Matthew
