### ISSUE TITLE
Include ArmNN in Android Studio

### ISSUE THREAD

**Issue by mobicham** [ARM-software/armnn#25]
I was able to build ArmNN for arm64-v8a and armeabi-v7a, so I ended up with the following libraries: 
libarmnnUtils.a, libarmnn.so, libarmnnTfParser.so, libc++_shared.so, libprotobuf.so. 
However, it is not clear how use these libraries via JNI in Android Studio. 
It cannot find `armnn` because of linking problems, so I tried to add the include files in the cpp and adapted the headers accordingly but then it cannot find boost. 
Anyone was able to make it work with Android Studio? Any help regarding linking and configuring the gradle file would be much appreciated, thank you.

**Comment by TelmoARM** [comment]
Hi mobicham,

We don't test ArmNN with Android Studio but there's no reason why it shouldn't work if the settings are correct. 

Could you provide more information on the linking problems and the configuration you are using so that I can try to reproduce the problem.

Thanks,
Telmo

**Comment by mobicham** [comment]
Hi @TelmoARM 
Thank you for your answer. I was able to fix the linking problem by following these steps:
- First, I added the libraries + the include files to _CMakeLists.txt_ and used `target_link_libraries` to link the libraries to my jni code. 
- Boost was missing so I had to add the boost include files inside the armnn include files.

At this point, Android Studio was able to recognize `armnn` but then when I tried to run I got a whole bunch of UnsatisfiedLinkError because many libraries were missing (libcutils.so, libc++.so,...), most of them were actually from the system lib64 folder of the android device (Honor 6C in my case). I tried to copy all of them, but still some of the .so files were not available on the device. 

Thank you in advance,

**Comment by TelmoARM** [comment]
Hi mobicham,

I'm not very familiar with Android Studio and my attempts to setup the gradle files to build ArmNN haven't been successful. Could you possibly share your current set-up/gradle config in order to reproduce the issue?

Many thanks,
Telmo

**Comment by mobicham** [comment]
Hi @TelmoARM,

I had some success including armnn in an Android Studio project. It turned out that the missing libraries problem was related to the device (Honor 6C), not the setup. However, I am having another issue that I opened in another thread regarding running code that calls armnn through JNI: https://github.com/ARM-software/armnn/issues/27

To answer you regarding the gradle and CMake config, it was not straightforward, so it might be useful for other people as well, so here's what I did: 
- Copy the built libraries `libarmbb.so, libarmnnTFParser.so, libarmnnUtils.a, libprotobuf.so` to the appropriate lib folder (for me it's src/main/jniLibs/arm64-v8a/)
- Copy the armnn include headers to the appropriate cpp folder (for me it's src/main/arm/armnn and src/main/arm/armnnTFparser)
- Get Boost include files for Android : https://github.com/dec1/Boost-for-Android and copy the include heades to the appropriate cpp folder (for me it's src/main/arm/boost)
- Include the include directories and libraries in CMakeLists.txt as follows:
> ##Add headers
include_directories(${PROJECT_SOURCE_DIR}/src/main/cpp/arm)
##Add libraries
add_library(armnn SHARED IMPORTED)
set_target_properties(armnn PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libarmnn.so)
add_library(armnnUtils STATIC IMPORTED)
set_target_properties(armnnUtils PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libarmnnUtils.a)
add_library(armnnTfParser SHARED IMPORTED)
set_target_properties(armnnTfParser PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libarmnnTfParser.so)
add_library(protobuf SHARED IMPORTED)
set_target_properties(protobuf PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libprotobuf.so)
...
##My main source file is called nnbackend.cpp 
add_library(nnbackend
             SHARED
             src/main/cpp/nnbackend.cpp
             )
##Link the libraries
target_link_libraries(nnbackend ${log-lib}
                       protobuf
                       armnn
                       armnnUtils
                       armnnTfParser)

- Finally, in the gradle file, add the following flags:
> ##CMake build         
externalNativeBuild {
            cmake {
                cppFlags "-std=c++14  -frtti -fexceptions" 
                arguments '-DANDROID_STL=c++_shared' 
            }
        }
   externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
##Specify source folders for the libraries
    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets']
            jni.srcDirs = ['src/main/jniLibs/']
        }
    }

Kind regards,

**Comment by TelmoARM** [comment]
Hi mobicham,

Many thanks for the detailed instructions. 

I can see that you made progress and closed the other ticket as well. Let us know if you encounter any other issues.

Best regards,
Telmo
