### ISSUE TITLE
Pose estimation NN

### ISSUE THREAD

**Issue by dorftemi** [ARM-software/armnn#250]
Hi all, I've been trying to use the NN presented here: 
https://www.tensorflow.org/lite/models/pose_estimation/overview
This page provides a tflite file so I tried to use it with armnn.
I created all outputBindingInfo variables as needed but still when I try to use it on a specific frame I get this error:
```
terminate called after throwing an instance of 'armnn::InvalidArgumentException'
  what():  No tensor supplied for output 21504
```

I of course have seen this post:
https://github.com/ARM-software/armnn/issues/243
But it didn't help me, I get the same error.

Has anyone seen it before, I have tried to look up for it but with no results.
Thanks.

**Comment by dorftemi** [comment]
I only used one input layer, maybe I need to add another one?

**Comment by MatthewARM** [comment]
Hi @dorftemi it looks like this model has four outputs and one input. Are you sure you've bound all four outputs to a tensor when calling EnqueueWorkload?

**Comment by dorftemi** [comment]
Hey @MatthewARM,
yes I have bound all 4 outputs as explained here: https://medium.com/flutter-community/posenet-for-ios-android-and-flutter-using-tensorflow-lite-836788a110c7

But I keep getting all kind of seg faults, like I did somthing wrong with the sizes.

Have you seen anyone doing something like that before?

**Comment by MatthewARM** [comment]
segfaults around the input and output tensors would usually be caused by getting the size wrong. I would check that GetNumBytes() on the TensorInfo for all the input and output tensors it agrees with your buffer sizes.

**Comment by dorftemi** [comment]
Thanks, I have managed to send my output and input arrays to EnqueueWorkload,
but it seems that i get the same results all the time (not good ones).
Has anyone ever tried to interpreter those results, or eve done something like that using armnn?

**Comment by dorftemi** [comment]
@MatthewARM Ok, the problem has returned, apparently I used wrong input size .
Now that I use the right size I once again get the seg fault:
#1  0x0000007fb28c718c in armnn::CopyMemGenericWorkload::Execute() const () from /lib/libarmnn.so

**Comment by james-conroy-arm** [comment]
Hi @dorftemi ,

Are you still getting the segfault?

We would like to help if you are.

Cheers,
James

**Comment by matthewsloyanARM** [comment]
Hi @dorftemi,

I will close this issue due to inactivity. If you are still having issues or have any questions feel free to reopen this ticket or create a new one anytime. Thank you again for reaching out!

Kind regards,

Matthew
