### ISSUE TITLE
About the parser to create LSTM layer

### ISSUE THREAD

**Issue by victor0623** [ARM-software/armnn#252]
Hi ARM support,

I want to test my lstm workload from the trained model.

It seems the parsers of TF/TFLite/ONNX doesn't support the LSTM operation now.
May I know when it gets ready for parsing LSTM op to create the lstm layer?

Thanks!

B.R.
Victor

**Comment by MatthewARM** [comment]
Hi @victor0623 we're hoping to get that done in the next few months, but I can't confirm exactly when. It would be helpful if you could say where you would prefer it (TF, TfLite or ONNX) to guide our prioritisation

**Comment by victor0623** [comment]
Hi Matthew,

We are using Tensorflow for LSTM model training. It will be very helpful to me if Arm take it as the higher priority.

Thanks a lot!

B.R.
Victor

**Comment by nullbyte91** [comment]
Hi Arm Support,

We can see you guys had mentioned that Deep Speech tested on ARM device. 
[Tested networks](https://github.com/ARM-software/armnn/blob/26052fcf2f8c91f3479c9484354e88e8944d004d/src/armnnTfLiteParser/TensorFlowLiteSupport.md#tested-networks).

Which one is correct?

**Comment by MatthewARM** [comment]
Hi @nullbyte91 we test DeepSpeech v1 using the tflite parser. The documentation is correct in that regard.

**Comment by nullbyte91** [comment]
@MatthewARM Thank you for the clarification.

**Comment by nullbyte91** [comment]
@MatthewARM Does it support Deep Speech Quantized Version. I'm getting the following Error,

```bash
Failed to parse operator #1 within subgraph #0 error: outputs.size() = 1 is not valid, not in {4}.  at function ParseDetectionPostProcess [/work/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1938]
Failed to parse operator #2 within subgraph #0 error: outputs.size() = 1 is not valid, not in {4}.  at function ParseDetectionPostProcess [/work/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1938]
Failed to parse operator #3 within subgraph #0 error: New shape defined in reshape parameters [0,26] does not equal output shape [1]:  at function ParseReshape [/work/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1708]
Armnn Error: Buffer #190 has 0 bytes. For tensor: [1] expecting: 4 bytes and 1 elements.  at function CreateConstTensor [/work/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:2612]
```

What does it mean?

Thank You,
Jegathesan S

**Comment by arovir01** [comment]
@nullbyte91 Custom TfLite operators are not generally supported. The TfLite parser attempts to convert any custom operator into a DetectionPostProcessLayer -- which is a custom operator found in the MobileNet SSD model.

**Comment by kejriwalnishant1990** [comment]
Hi @victor0623 , I can see LSTM layer support mentioned in armnn 19.08 release. Is LSTM not supported in armnn?
![armnn_support](https://user-images.githubusercontent.com/1533849/66748285-6fd83b80-eea4-11e9-8249-4425ab7b2b8e.png)

**Comment by MatthewARM** [comment]
@nullbyte91 according to our README file, we're using Mozilla DeepSpeech v0.4.1. Is that the same as your test?

**Comment by victor0623** [comment]
> Hi @victor0623 , I can see LSTM layer support mentioned in armnn 19.08 release. Is LSTM not supported in armnn?
> ![armnn_support](https://user-images.githubusercontent.com/1533849/66748285-6fd83b80-eea4-11e9-8249-4425ab7b2b8e.png)

Hi @kejriwalnishant1990 , yes I know the core of armnn already supports LSTM layer. What I mean is the parsers of TF/TF_Lite/ONNX don't support LSTM.

**Comment by arovir01** [comment]
This should fix the bug that cause _ANY_ custom operator to be parsed as if it were a DetectionPostProcess operator from MobileNet SSD:
https://review.mlplatform.org/#/c/ml/armnn/+/2153/

**Comment by kejriwalnishant1990** [comment]
Hi @victor0623 Do we have any expected timeline for parser support of LSTM layers for tensorflow in armnn ?

**Comment by MatthewARM** [comment]
I'll look into this. I believe we regularly test Mozilla DeepSpeech but I can see there's no ParseLSTM method in the tflite parser code. I'll have to look into how the test is executed.

**Comment by Burton2000** [comment]
> 
> 
> @MatthewARM Does it support Deep Speech Quantized Version. I'm getting the following Error,
> 
> ```shell
> Failed to parse operator #1 within subgraph #0 error: outputs.size() = 1 is not valid, not in {4}.  at function ParseDetectionPostProcess [/work/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1938]
> Failed to parse operator #2 within subgraph #0 error: outputs.size() = 1 is not valid, not in {4}.  at function ParseDetectionPostProcess [/work/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1938]
> Failed to parse operator #3 within subgraph #0 error: New shape defined in reshape parameters [0,26] does not equal output shape [1]:  at function ParseReshape [/work/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1708]
> Armnn Error: Buffer #190 has 0 bytes. For tensor: [1] expecting: 4 bytes and 1 elements.  at function CreateConstTensor [/work/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:2612]
> ```
> 
> What does it mean?
> 
> Or Am I missing something?
> 
> Thank You,
> Jegathesan S

I also got a similar error with the quantized deep speech model, it looks like the model is only quantized using post-training quantization and not full integer quantizaiton. I am guessing the tflite parser can't deal with this kind of graph?

**Comment by james-conroy-arm** [comment]
@victor0623 Regarding the 19.08 release notes, we added [QUANTIZED_16BIT_LSTM ](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a42edb5ab6f1c74f4a756eb1ed0183a16) support to the Android NN Driver for ArmNN.

We do not currently support LSTM layers through our parsers, only through the Android NN Driver API. We do not currently have plans for supporting LSTM through our TensorFlow parser.

However, full TfLite support for LSTM is on (Google's) TfLite 2020 [roadmap](https://www.tensorflow.org/lite/guide/roadmap). We will likely add support for LSTM through our TfLite parser once this happens.

We currently support Mozilla's DeepSpeech model, but this does not contain an LSTM layer. This model contains the mathematical operators which are contained in an LSTM (i.e. Add, Mult, Sigmoid), which we do support through our parsers.

Please let us know if you have any other questions.

Cheers,
James

**Comment by FrancisMurtagh-arm** [comment]
Closing due to age and lack of activity,
