### ISSUE TITLE
Build error when armnnTfParser is configured to static library build

### ISSUE THREAD

**Issue by victor0623** [ARM-software/armnn#254]
Hi ARM support,

For efficiency, I make TfParser build from share library to static library by modifying the contents of CMakeLists.txt:
from:
add_library_ex(armnnTfParser SHARE ${armnn_tf_parser_sources})
to:
add_library_ex(armnnTfParser STATIC ${armnn_tf_parser_sources})

But got the build error:
Adding object library dependency to armnn: armnnRefBackend
Adding object library dependency to armnn: armnnRefBackendWorkloads
CMake Error at CMakeLists.txt:469 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "armnnTfParser".

I did the following modification in CMakeLists.txt and the build can be successfully done:
#if(BUILD_TF_PARSER)
#    install(TARGETS armnnTfParser
#            LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
#            RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
#endif()

if(BUILD_TF_PARSER)
    install(TARGETS armnnTfParser DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
endif()

The v19.05 build doesn't have this build error.

Is it a bug for v19.08?

Thanks!

B.R.
Victor

**Comment by MatthewARM** [comment]
Hi @victor0623 I would say it's not so much a bug, rather that your local patch needs updating for the new release.

Perhaps a better way for the long term would be to add an option to build static versions of the libraries? Would that be something you could contribute to?

**Comment by victor0623** [comment]
Hi Matthew,

OK, I will try to add it once I finish the verification.

Thanks!

B.R.
Victor
