### ISSUE TITLE
Quantization using ARMNN

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/armnn#255]
Hi,
I am trying to create the QASYMM8 quantized  mnist network   from original  float mnist network using ARMNN. 

I have created a csv file which I had to pass to Armnnquantizer. In this csv file, what is the significance of passId and bindingID. Doesn't just the raw image data suffice for quantization?

Thank you,
Praveen

**Comment by MikeJKelly** [comment]
Hi Praveen,

When using Dynamic Calibration the ArmnnQuantizer passes a large data set of representative inputs through the model in FP32. When setting up the CSV file for this the passId identifies the pass number when calibrating the quantization with multiple sets of data and the bindingID identifies the input layer that the data in the raw file is for. 

So if you have a model with two inputs and wish to provide raw input data for two passes your CSV file could look a bit like the following:

```
0, 0, "RefinementData/input_pass0_input0.raw"
0, 1, "RefinementData/input_pass0_input1.raw"
1, 0, "RefinementData/input_pass1_input0.raw"
1, 1, "RefinementData/input_pass1_input1.raw"
```

This way we identify which files are to be used for which inputs on multiple passes. More passes with representative data should mean better a calibrated network. 

Hope that helps, 
Mike

**Comment by uu-praveeng** [comment]
thank you for detailed info
