### ISSUE TITLE
Error while loading the quantized network in armnn

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/armnn#256]
Hi,

I have created a sample network in armnn  which has input->convolution->output.
input dimensions - 1,1,5,5
convolution -bias(1) weights(1,1,3,3), stride(1,1), Pad(1,1,1,1)
output- 1,1,5,5

I have done the serialization, followed by quantization using the sample.csv and then tried to deserialize and run the quantized network.

While Loading the I am seeing the below error.
**An error occurred when preparing the network workloads:  Convolution2dQueueDescriptor: Expected data type Signed32 but got Unsigned8 for bias tensor**

Is the quantizer always expected to quantize the data to unsigned char?
If yes, then how to make the quantizer to give the Signed32 bias which is requirment for ACL, so that I could execute the quantized network.

Is this is a known issue? or did I miss anything.

 Thank you,
Praveen.

**Comment by MatthewARM** [comment]
Hi @uu-praveeng that sounds like it might be a bug. As far as I know the bias tensor should always be Signed32 for quantised networks. I'll get someone to have a look and report back to you.

**Comment by MikeJKelly** [comment]
Hi Praveen, 

can you tell me what version you're using? This looks like an issue that was fixed in the quantizer a couple of months ago.

**Comment by uu-praveeng** [comment]
Hi MikeJKelly,

I tried with armnn v19.05 . I will try with 19.08 and let you know my observations

Thank you,
Praveen

**Comment by uu-praveeng** [comment]
Hi @MikeJKelly 

I have tried with 19.08 and Qauntizer works fine .

Thank you.
