### ISSUE TITLE
UnitTests : "DynamicBackendTests/OpenCloseHandle": check exists(fileNamePath) has failed

### ISSUE THREAD

**Issue by nullbyte91** [ARM-software/armnn#257]
Hi,

I'm building ARMNN for Android device using Android NDK by following "How to use the Android NDK to build ArmNN" guild. 

I'm getting the following Error,
 **"DynamicBackendTests/OpenCloseHandle": check exists(fileNamePath) has failed**

The issue with Instruction given in the BuildGuideAndroidNDK.md. For example to copy testDynamicBackend files,
 
`adb push -p ~/armnn-devenv/armnn/build/src/backends/backendsCommon/test/testDynamicBackend/ /data/local/tmp/src/backends/backendsCommon/test/testDynamicBackend`

This should be,
`adb push -p ~/armnn-devenv/armnn/build/src/backends/backendsCommon/test/testDynamicBackend/* /data/local/tmp/src/backends/backendsCommon/test/testDynamicBackend`

**Comment by MatteoArm** [comment]
Hi @nullbyte91,

"adb push" should handle directories natively by copying all the files in them automatically, so there's no need to add the "/*" at the end (it still can be done though).
We have tested those steps and they are working for us, for reference we use adb 1.0.39

Regards
Matteo

**Comment by nullbyte91** [comment]
@MatteoArm I use 1.0.41 and its not working. 

I don't see adb version mentioned from in any of README file. We can keep this change so we are not depending on adb version.

**Comment by MatteoArm** [comment]
Closing as the change has been merged to master.

**Comment by Sheethal524** [comment]
Hi,

Got the same set of errors while running the test cases

/home/sheethal.ng/armnn-devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(158): error: in "DynamicBackendTests/OpenCloseHandle": check exists(fileNamePath) has failed
/home/sheethal.ng/armnn-devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(171): error: in "DynamicBackendTests/OpenCloseHandle": unexpected exception thrown by sharedObjectHandle = DynamicBackendUtils::OpenHandle(sharedObjectFilePath)
/home/sheethal.ng/armnn-devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(172): error: in "DynamicBackendTests/OpenCloseHandle": check (sharedObjectHandle != nullptr) has failed
/home/sheethal.ng/armnn-devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(158): error: in "DynamicBackendTests/OpenNotSharedObjectFile": check exists(fileNamePath) has failed
/home/sheethal.ng/armnn-devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(158): error: in "DynamicBackendTests/GetValidEntryPoint": check exists(fileNamePath) has failed
/home/sheethal.ng/armnn-devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(223): error: in "DynamicBackendTests/GetValidEntryPoint": unexpected exception thrown by sharedObjectHandle = DynamicBackendUtils::OpenHandle(sharedObjectFilePath)
/home/sheethal.ng/armnn-devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(224): error: in "DynamicBackendTests/GetValidEntryPoint": check (sharedObjectHandle != nullptr) has failed
/home/sheethal.ng/armnn-devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(229): error: in "DynamicBackendTests/GetValidEntryPoint": unexpected exception thrown by testFunctionPointer = DynamicBackendUtils::GetEntryPoint<TestFunctionType>(sharedObjectHandle, "TestFunction1")
/home/sheethal.ng/armnn-devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(230): error: in "DynamicBackendTests/GetValidEntryPoint": check (testFunctionPointer != nullptr) has failed
Segmentation fault

**Comment by nullbyte91** [comment]
@Sheethal524 please use the below change,
[https://github.com/nullbyte91/armnn/commit/ff4a9ed44b5fb765209fa2791177e885724931ce](url)

**Comment by Sheethal524** [comment]
Thanks for the help!!

It is working fine
