### ISSUE TITLE
UnitTests : OpenClTimerBatchNorm - Failure 

### ISSUE THREAD

**Issue by nullbyte91** [ARM-software/armnn#259]
Hi,

I'm building ARMNN for Android device using Android NDK by following "How to use the Android NDK to build ArmNN" guild.

The following error I'm getting when I ran UnitTests,
`OpenClTimerTest.cpp(140): error: in "OpenClTimerBatchNorm/OpenClTimerBatchNorm": check openClTimer.GetMeasurements().front().m_Value > 0 has failed.`

By commenting out the below line from openClTimerTest.cpp, the unitTest return no error detected,
`BOOST_CHECK(openClTimer.GetMeasurements().front().m_Value > 0);`

Could someone point me out What could be the issue?

**Comment by MatthewARM** [comment]
Hi @nullbyte91 this means that the OpenClTimer hasn't recorded any time spent in the function, which is... strange... but harmless unless you need to do OpenCL profiling to improve performance. It should be safe to run without that test.
Is there anything unusual about your OpenCL setup that might cause this to work differently?

**Comment by nullbyte91** [comment]
@MatthewARM  I've followed the same steps given in the Build Doc. So, I really don't think I've a different setup.
