### ISSUE TITLE
Error in linking libarmnn.so

### ISSUE THREAD

**Issue by blestsoul35** [ARM-software/armnn#26]
I am trying to cross-compiling for an ARM from Ubuntu 64bit  and got this error when `make` . Thanks to other posts, I solved some of issues I have had so far, but I am stuck here. :(  Anybody has similar error? 

I used 
cmake -DARMCOMPUTE_ROOT=/home/dajung/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=/home/dajung/ComputeLibrary/build -DBOOST_ROOT=/usr/include/boost -DCAFFE_GENERATED_SOURCES=/home/dajung/caffe/.build_release/src -DBUILD_CAFFE_PARSER=1 -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DPROTOBUF_LIBRARY_DEBUG=/usr/local/lib/libprotobuf.so -DPROTOBUF_LIBRARY_RELEASE=/usr/local/lib/libprotobuf.so .. 

> [ 78%] Linking CXX shared library libarmnn.so
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libboost_log.a(attribute_name.o): Relocations in generic ELF (EM: 62)
/usr/local/lib/libboost_log.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/armnn.dir/build.make:2464: recipe for target 'libarmnn.so' failed
make[2]: *** [libarmnn.so] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/armnn.dir/all' failed
make[1]: *** [CMakeFiles/armnn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I followed [this instuction ](https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe/configuring-the-arm-nn-sdk-build-environment-single-page) and used protoc and boost 1.64, arm-compiled.

**Comment by MatthewARM** [comment]
Hi @blestsoul35 those errors would indicate that it's trying to link to a boost library compiled for the wrong target. Where you have `BOOST_ROOT=/usr/include/boost` that doesn't seem right, as that would indicate your system installed boost libraries.  I would have expected something like `BOOST_ROOT=/path/to/boost_arm64_install`

We've got some better pre-release documentation for cross-compilation, I'll see if I can make it available before the next release.

**Comment by blestsoul35** [comment]
Thank you so much for your sharing. I will try e documentation and doublecheck my installations.

**Comment by Surmeh** [comment]
Hi @blestsoul35,

I hope you've managed to cross-compile successfully. Please get back in touch if you need any further help.

Thanks,
Surabhi
