### ISSUE TITLE
Armnn less accurate than Tflite for deeplab?

### ISSUE THREAD

**Issue by lwu025** [ARM-software/armnn#260]
I compared armnn inference and tflite inference on a deeplab model. It looks like armnn output is always offset by 1 pixel in both x and y direction.

My model is modified from a tensorflow hosted model:https://www.tensorflow.org/lite/models/segmentation/overview
I flatten the atrous conv layers and removed BATCH_TO_SPACE and SPACE_TO_BATCH
Input layer: sub_7
Output layer: ResizeBilinear_2
My armnn inference and tflite inference shared the same resize and visualization function, no preprocessing except resize to 257*257, no postprocessing except resize the mask back to input image size.

My model and images are here: https://drive.google.com/open?id=1lf5Ff0al7cXNxotGfHuT6Rs4bEFI9cgg

Here is my result:
input/armnn/tflite:
![Screenshot from 2019-09-10 10-57-30](https://user-images.githubusercontent.com/43549654/64638022-d952bf00-d3b9-11e9-947c-81987da128df.png)
input/armnn/tflite:
![Screenshot from 2019-09-10 10-59-20](https://user-images.githubusercontent.com/43549654/64638145-14ed8900-d3ba-11e9-9f3e-0b50dc0ac1aa.png)

Thanks!

**Comment by MikeJKelly** [comment]
Hi @lwu025 

sorry for the delay on this but this issue should be resolved by the following Armnn patch: 
https://review.mlplatform.org/c/ml/armnn/+/2547

It will also require this ComputeLibrary patch for CpuAcc: 
https://review.mlplatform.org/c/ml/ComputeLibrary/+/2538

And this ComputeLibrary patch for GpuAcc:
https://review.mlplatform.org/c/ml/ComputeLibrary/+/2569
 
The results will not be exactly the same as with tflite but the differences should be marginal. This code will be in the upcoming 20.02 release later this month.
