### ISSUE TITLE
Android NDK Build - TensorFlow protobuf definitions generation fails with TensorFlow master branch

### ISSUE THREAD

**Issue by nullbyte91** [ARM-software/armnn#267]
Hi ARM Team,

We need a tensorflow/contrib/makefile/tf_proto_files.txt from TensorFlow to generate TensorFlow protobuf definitions. This file not available from TensorFlow master branch. 

We have to use commit ID a0043f9262dc1b0e7dc4bdf3a7f0ef0bebc4891e.

```bash
git checkout a0043f9262dc1b0e7dc4bdf3a7f0ef0bebc4891e 
```
We have to update the BuildGuideAndroidNDK.md file. 

Thank You,
Jegathesan S

**Comment by jasonrandrews** [comment]
I hit the same problem on a native Linux compile on Arm. Thank you for reporting it as it saved me a lot of debugging time.

**Comment by nullbyte91** [comment]
@MatthewARM We need to update this on the doc.

**Comment by TelmoARM** [comment]
@nullbyte91 Thanks for reporting this issue. 

I'll make sure the BuildGuideAndroidNDK.md gets updated.

Thanks,
Telmo

**Comment by jishminor** [comment]
This tutorial could also use the update: https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/cross-compiling-arm-nn-for-the-raspberry-pi-and-tensorflow/building-the-google-protobuf-library

**Comment by TelmoARM** [comment]
@jishminor Thanks for pointing this out. I'll add the changes to both guides.

**Comment by TelmoARM** [comment]
Both guides mentioned in this ticket have been updated. 

We are working on a more long term solution for 20.02 Release onwards.
