### ISSUE TITLE
Adding serialisation-deserialisation support for a custom layer

### ISSUE THREAD

**Issue by AnPay** [ARM-software/armnn#268]
Hello
I am trying to add serialisation-deserialisation support for a layer already supported by armnn
1) added in schema
   Table, descriptor,layer,layer type
2)added Visit layer() in serializer.cpp and hpp
3) added parseLayer in deserializer.cpp
So armnn binary is generated. But when i run it through Execute network, it says Layer with given index not found.
So the layer I added has fb_index =242
In SetupOutputLayer->GetLayerIndexVector
Graph size   target index
243                    0
243                  242
243                    243.  <---- i think it's incorrect.
Can't figure out the reason.
Source index layer comes to be 243, it should come lesser than 243.
Any idea, where am i missing or going wrong.

**Comment by arovir01** [comment]
Did you add the layer to the switch inside Deserializer::GetBaseLayer()?

**Comment by AnPay** [comment]
Yes, added.

**Comment by arovir01** [comment]
If you don't mind me asking, which layer are you trying to add to the serializer? I was under the impression that all supported layers -- with the exception of the ones intended for internal use only, such as DebugLayer, MemCopyLayer, MemImportLayer, etc. -- are already fully serializable :?

**Comment by AnPay** [comment]
It's a layer in caffe models which is present in armnn layers and layer type also, but respective functions ain't there in serializer or deserializer. Even armnnCaffeParser doesn't support it. So now parser support works fine. But once on execution of this model converted to .armnn it gives the error mentioned in my first post.

**Comment by arovir01** [comment]
I checked again and all the publicly accessible layers, i.e. the ones present in INetwork.hpp, are already serializable. The only layers that cannot be serialized are the following:
- ConvertFp16ToFp32
- ConvertFp32ToFp16
- Debug
- FakeQuantization
- MemCopy
- MemImport
- PreCompiled
All these are internal layers that are added by the optimizer -- with the exception of FakeQuantization, which is a training layer that is not fully supported by Arm NN.

Am I missing something?

**Comment by AnPay** [comment]
Hi
Thanks for the reply. I don't see anything for detection output descriptor in serializer.cpp

**Comment by arovir01** [comment]
>  detection output descriptor

There is no such layer in Arm NN :? There is a DetectionPostProcess layer used in the MobilNet SSD network, but that is fully supported by the serializer.

My suspicion is that you are trying to deserialize a layer that is not supported by Arm NN and therefore you end up with a corrupted network, which then fails to execute.

Can you point me to the documentation of the Caffe equivalent of this layer you are trying to deserialize?

**Comment by AnPay** [comment]
Thanks for the reply.
I can see a addDetectionOutputLayer().
And i see DetectionOutputLayer.cpp in armnn/src/armnn/layers

**Comment by arovir01** [comment]
Are you using some custom fork of Arm NN? There is surely no DetectionOutputLayer in our official release. See here the list of layers in the 19.08 release:
https://github.com/ARM-software/armnn/tree/branches/armnn_19_08/src/armnn/layers

In case you are using a fork, you might want to contact whoever implemented the DetectionOutputLayer.

**Comment by AnPay** [comment]
Okay. Thanks.
