### ISSUE TITLE
Fatal signal 11 libc_malloc (Android)

### ISSUE THREAD

**Issue by mobicham** [ARM-software/armnn#27]
I am trying to test the TF-MNIST example on Android via JNI.  Unfortunately, whenever I make a call related to Armnn, I get:

> A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x72e0b43b00 in tid 28503 (ius.visionarmnn)

So for example, this happens when I run `armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();`

Using `logcat` I get the following log: 

> 06-28 15:48:05.430 28882 28882 W google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
06-28 15:48:05.430 28882 28882 W google-breakpad: Chrome build fingerprint:
06-28 15:48:05.430 28882 28882 W google-breakpad: 67.0.3396.87
06-28 15:48:05.430 28882 28882 W google-breakpad: 339608752
06-28 15:48:05.430 28882 28882 W google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
06-28 15:48:05.430 28882 28882 F libc    : Fatal signal 11 (SIGSEGV), code 2, fault addr 0x72e227eb00 in tid 28882 (ius.visionarmnn)
06-28 15:48:05.494 29016 29016 I crash_dump64: obtaining output fd from tombstoned
06-28 15:48:05.495  3375  3375 I /system/bin/tombstoned: received crash request for pid 28882
06-28 15:48:05.496 29016 29016 I crash_dump64: performing dump of process 28882 (target tid = 28882)
06-28 15:48:05.497 29016 29016 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
...
06-28 15:48:05.497 29016 29016 F DEBUG   : ABI: 'arm64'
06-28 15:48:05.497 29016 29016 F DEBUG   : pid: 28882, tid: 28882, name: ius.visionarmnn  >>> ml.mobius.visionarmnn <<<
06-28 15:48:05.497 29016 29016 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x72e227eb00
06-28 15:48:05.497 29016 29016 F DEBUG   :     x0   00000072e1c44b94  x1   00000072e227dc00  x2   00000072e2200000  x3   0000000000000004
06-28 15:48:05.497 29016 29016 F DEBUG   :     x4   000000000000007d  x5   0000007fd0b70870  x6   656e1f63ff737264  x7   7f7f7f7f7f7f7f7f
06-28 15:48:05.497 29016 29016 F DEBUG   :     x8   35b8fa3c82ee61a3  x9   35b8fa3c82ee61a3  x10  000000000000007d  x11  35b8fa3c82ee61a3
06-28 15:48:05.497 29016 29016 F DEBUG   :     x12  35b8fa3c82ee61a3  x13  0000000000000000  x14  000000730314b092  x15  ffffffffffffffff
06-28 15:48:05.497 29016 29016 F DEBUG   :     x16  00000072e1a5c9b8  x17  00000072e19c33d0  x18  000000000000121f  x19  00000073034c0a00
06-28 15:48:05.497 29016 29016 F DEBUG   :     x20  0000007303128a80  x21  00000073034c0a00  x22  0000007fd0b70d9c  x23  00000072e70b7be6
06-28 15:48:05.497 29016 29016 F DEBUG   :     x24  0000000000000000  x25  00000073034c0a98  x26  0000000000000000  x27  0000000000000000
06-28 15:48:05.497 29016 29016 F DEBUG   :     x28  0000000000000000  x29  0000007fd0b70a60  x30  00000072e19c261c
06-28 15:48:05.497 29016 29016 F DEBUG   :     sp   0000007fd0b70a30  pc   00000072e227eb00  pstate 0000000060000000
06-28 15:48:05.502 29016 29016 F DEBUG   : 
06-28 15:48:05.502 29016 29016 F DEBUG   : backtrace:
06-28 15:48:05.502 29016 29016 F DEBUG   :     #00 pc 000000000007eb00  [anon:libc_malloc:00000072e2200000]
06-28 15:48:05.502 29016 29016 F DEBUG   :     #01 pc 0000000000017618  /data/app/armnntest-bSXLFIuFCXxZgS0VskYytg==/lib/arm64/libnnbackend.so (_ZNSt10unique_ptrIN13armnnTfParser9ITfParserEPFvPS1_EED2Ev+76)

I got the same error when I was trying the Compute Library with pre-built libraries (18.05 with neon-cl)

Thank you very much in advance,

**Comment by mobicham** [comment]
Hi @MatthewARM,

Thank you very much for your quick answer.
The crash doesn't happen if I don't make a call related to armnn in my JNI code. 
Regarding the build, I followed https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md. I used NDK 16b and built for arch=arm64-v8a neon=1 opencl=1. 

I copied the following libraries:

>  libarmnn.so, libarmnnTFparser.so, libarmnnUtils.a, libprotobuf.so, libc++_shared.so

My CMakeLists.txt contains this:

> include_directories(${PROJECT_SOURCE_DIR}/src/main/cpp/arm)
add_library(armnn SHARED IMPORTED)
set_target_properties(armnn PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libarmnn.so)
add_library(armnnUtils STATIC IMPORTED)
set_target_properties(armnnUtils PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libarmnnUtils.a)
add_library(armnnTfParser SHARED IMPORTED)
set_target_properties(armnnTfParser PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libarmnnTfParser.so)
add_library(protobuf SHARED IMPORTED)
set_target_properties(protobuf PROPERTIES IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libprotobuf.so)
...
target_link_libraries(nnbackend ${log-lib}
                       armnn
                       armnnUtils
                       armnnTfParser
                       protobuf)

and my Android app build has ` cppFlags "-std=c++14  -frtti -fexceptions" `

Let me know if you need more information, I can also share the built libraries with you.

Kind regards,

**Comment by MatthewARM** [comment]
Do the armnn unit tests work?

**Comment by mobicham** [comment]
Unfortunately, I couldn't run the test because the build crashed at 99% and couldn't build UnitTests. 
However, I am pretty sure it's not an OpenCL issue because I was able to run other OpenCL-based applications on the same device.
Would you be so kind to share some pre-built libraries for v8a/android or v7a/android just to make sure that it's not an issue related to the libraries? Alternatively, I will test my setup on other android devices hopefully tomorrow.

**Comment by mobicham** [comment]
Thank you @MatthewARM for the tip.
Yes, I am using libc++ via `'-DANDROID_STL=c++_shared'`, which should be the same as copying libc++_shared.so from the NDK and putting it together with the other .so files. 

It turns out that the linking order you provided worked, thank you, I am closing this issue. 

Kind regards,
