### ISSUE TITLE
Unable to run ArmNN built with openCL support on a platform without openCL

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#273]
I am not able to use an ArmNN built with openCL, on a system without openCL. (The use case is to use a single package for multiple platforms).

E.g. `CaffeMnist-Armnn` returns:
```
ArmNN v20190800
Armnn Error: Could not initialize the CL runtime. Error description: clGetDeviceIDs. CL error code: -1 
```
Even if `-c CpuRef` or `-c CpuAcc` is specified to force the usage of the cpu.

It would probably be a good idea to fallback to `CpuAcc` when `GpuAcc` is failing?
Or at least honor the `-c` option?

**Comment by MatthewARM** [comment]
Hi @ggardet do you know why this is happening? Any indications from the call stack? At some point an OpenCL routine is going to get called, and therefore something has to link to libOpenCL.so, so if libOpenCL.so isn't present that's a problem??

**Comment by ggardet** [comment]
> Hi @ggardet do you know why this is happening? Any indications from the call stack? At some point an OpenCL routine is going to get called, and therefore something has to link to libOpenCL.so, so if libOpenCL.so isn't present that's a problem??

No, I did not trace it yet.
This is not a crash, just an exit as the lib is installed, but there is no openCL device available.
I think armnn should handle the error to a fallback.

**Comment by MatthewARM** [comment]
Ah I see, so the machine must have libOpenCL.so, but something isn't handling that error correctly.

**Comment by ggardet** [comment]
Yes, libOpenCL is there, but if no openCL device are found, we probably should fallback to a Cpu backend instead of exit.

**Comment by MatthewARM** [comment]
Understood. I'll raise this internally, otherwise feel free to have a hack.

**Comment by MatthewARM** [comment]
@MatteoArm I presume this shouldn't be too hard to fix now that we can handle errors during loading a backend?

**Comment by MatthewARM** [comment]
```matben01@e121305-lin:~/gits/devenv$ build-aarch64/release/armnn/tests/ExecuteNetwork -m models/mobilenet_v1_1.0_224_quant.tflite  -c CpuAcc -f tflite-binary -i input -o data
Info: ArmNN v20191100

terminate called after throwing an instance of 'armnn::ClRuntimeUnavailableException'
  what():  Could not initialize the CL runtime. Error description: clGetPlatformIDs. CL error code: -1001
Aborted (core dumped)
```

**Comment by MatthewARM** [comment]
OK I think I've figured out the right approach - we need to say that "CreateBackendContext" should throw if your backend's runtime component is not available. Then in the constructor of armnn::Runtime we should only add backends into the Runtime's DeviceSpec if the runtime component _is_ available.

This keeps the behavior that the DeviceSpec can know about all backends, so off-line Optimise() can still happen, while making it the Runtime's responsibility to actually probe for necessary Runtime components (like hardware and late-loaded libraries).

**Comment by MatthewARM** [comment]
Review here: https://review.mlplatform.org/c/ml/armnn/+/2680

**Comment by MatthewARM** [comment]
@ggardet this should be fixed in master now. Please reopen if it doesn't work for you.

**Comment by ggardet** [comment]
I tested it successfully, thanks! 
Is there a mean to run unit tests on Cpu only and disable Gpu support, though? 
Because the builder does not necessarily support openCL, but the device where it will be run on, may support it. When builder build to support openCL, but does not support it itself, I get lots of:
```armnn::ClRuntimeUnavailableException: Could not initialize the CL runtime. Error description: clGetDeviceIDs. CL error code: -1```

**Comment by MatthewARM** [comment]
Hi @ggardet there's no global way to disable GPU tests. I've done it before by using test filter expressions. The unit tests use Boost.Test which accepts wildcard tests to disable.

**Comment by FrancisMurtagh-arm** [comment]
@ggardet 

Re: Filtering tests for CL; I used these filters for 19.11 in case it helps:

`./UnitTests  --run_test=!Compute_ArmComputeCl:!MemCopyClNeon:!CreateWorkloadCl:!ClEndToEnd:!ClLayerSupport:!ClOptimizedNetwork:!ClJsonPrinter:!ClRuntime:!Fp16Support:!OpenClTimerBatchNorm:!ClMemCopy`

Francis.
