### ISSUE TITLE
Version armnn libs

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#275]
There are some downstream patches to build versioned armnn libs.
Original patch is from http://arago-project.org/git/?p=meta-arago.git;a=blob;f=meta-arago-extras/recipes-support/armnn/armnn/0004-generate-versioned-library.patch;hb=master
But this one seems to be more complete: https://build.opensuse.org/package/view_file/science:machinelearning/armnn/armnn-generate-versioned-library.patch?expand=1

Could we upstream this?

**Comment by MatthewARM** [comment]
I can't pull stuff from other people without their permission. In the Arm NN project that's what the use of the "Developer Certificate Of Origin" is for. If you are active in those projects please persuade people to engage and upstream.

**Comment by MatthewARM** [comment]
Or are you asking if the Arm NN project would accept those patches? If so, then yes please :-)

**Comment by ggardet** [comment]
Yes, it was to know if you would be ok with those patches.
Since, the answer is yes, I will upstream them. Thanks.

**Comment by MatthewARM** [comment]
Awesome, thanks

**Comment by tom-gall** [comment]
O wow, I was just working on this this afternoon and was going to post my own patch.  

I think the patch as presented is mostly ok but I think exposes something we don't want. That is the date based versioning scheme. I would suggest that armnn should fall into line with standard x.y.z library numeric versioning standards employed across many a project. 

Not convinced? 

Version numbers often imply API/ABI compatibility. Something date based does not. If we want to support list distros (and i think we do), then we need to rely on those version numbers as a commitment as well as a signal when an app will need to be rebuilt. 

Also it wouldn't be a bad idea to start to run like libabigail to watch for changes that could break an app using the shared library. I think this could be something we do as part of the mlplatform CI system in Linaro.

**Comment by MatthewARM** [comment]
Closing this, and splitting off Tom's point to #293.
