### ISSUE TITLE
Add an option to be able to use Boost and ComputeLibrary as shared libraries

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#277]
Currently ArmNN uses static boost and ComputeLibrary libraries. From a distro point of view, it would be better to switch to shared libraries, or at least to make it configurable with CMake.

**Comment by MatthewARM** [comment]
I agree, I think it should be configurable. The TI yocto files have the same problem: 

https://layers.openembedded.org/layerindex/recipe/87616/

I'd appreciate any advice on how to make this work elegantly, without breaking cross-compilation, Android AOSP, etc

**Comment by ggardet** [comment]
I guess something like this should work and keep your current behavior (**untested**):
```
option(USE_SHARED_BOOST "Use shared libraries for Boost" OFF)
if(USE_SHARED_BOOST)
    add_definitions(-DBOOST_ALL_DYN_LINK)
    set(Boost_USE_STATIC_LIBS OFF)
else()
    add_definitions("-DBOOST_ALL_NO_LIB")
    set(Boost_USE_STATIC_LIBS ON)
endif()
```

**Comment by MatthewARM** [comment]
Yeah looks fine. and I guess it implicitly defaults to off (as it won't be defined unless passed to cmake) which is backwards compatible with existing usage.

**Comment by ggardet** [comment]
> Yeah looks fine. and I guess it implicitly defaults to off (as it won't be defined unless passed to cmake) which is backwards compatible with existing usage.

The default is set in `option`, here: `OFF`

**Comment by MatthewARM** [comment]
Oh yeah :-)

**Comment by MatthewARM** [comment]
@ggardet did you submit a review for this? I can do it if you haven't?

**Comment by ggardet** [comment]
> @ggardet did you submit a review for this? I can do it if you haven't?

No, I did not. Fell free to do it.

**Comment by MatthewARM** [comment]
https://review.mlplatform.org/c/ml/armnn/+/2192

**Comment by MatthewARM** [comment]
Done. @ggardet please reopen if you disagree.
