### ISSUE TITLE
armnnTfParser CreateNetwork from pb file as String instead of path

### ISSUE THREAD

**Issue by mobicham** [ARM-software/armnn#28]
The TF parser so far supports 3 ways of loading a model: from text file (prototxt), from binary file (pb), and from a string (basically the content of the prototxt in a string). 

Would it be possible to create a network from the content of the pb file (like `theCreateNetworkFromString` function but for .pb) ? 
The reason why it's important to have this is because using files via paths is not always possible to do in Android. Also, for security reasons, the models are usually encrypted and they are decrypted on runtime in memory. For example, both TensorFlow and the Qualcomm SNPE SDK accept "InputStream" in Java to load a model instead of paths. 
Kind regards,

**Comment by MatthewARM** [comment]
Thanks @mobicham that's good feedback on the Tensorflow parser. I'll add it to the list of improvements that we would like to make.

If you are interested in developing the feature yourself, it looks like google::protobuf::io::CodedInputStream can be created directly from a byte buffer (see https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.coded_stream#CodedInputStream), so adding a new method called TfParser::CraeteNetworkFromBinaryData that is similar to the existing CreateNetworkFromBinaryFile would be possible.

All the best,
Matthew

**Comment by mobicham** [comment]
Thank you @MatthewARM ! 
Just to mention something, it is still possible to use the TF parser from the content of a prototxt file by exporting the model via `tf.train.write_graph` with the flag `as_text=True`. I tested that and it works. 
However, the model file as text (.prototxt) is much larger in size compared to the binary version (.pb), which can create some out of memory problems when reading the file on an Android device.
Kind regards,

**Comment by MatthewARM** [comment]
Hi @mobicham yes we have also noticed that the binary format is a lot more efficient. In practice the text format is only useful for small tests.

All the best,
Matthew
