### ISSUE TITLE
how to build  libinferenceTest.so

### ISSUE THREAD

**Issue by rouyunpan** [ARM-software/armnn#281]
I want build a application to test armnn. 
I get the code from the github of ARM-software/ML-examples/armnn-mobilenet-quant.
https://github.com/ARM-software/ML-examples/tree/master/armnn-mobilenet-quant

but it need the library inferenceTest of armnn
ld option in makefile
LDLIBS=-larmnn -larmnnTfLiteParser -linferenceTest -lboost_system -lboost_filesystem -lboost_program_options

I can't find linferenceTest.so from build folder of armnn. 
How do I build libinferenceTest.so for armmnn?

**Comment by rouyunpan** [comment]
![截图_2019-10-14_14-48-33](https://user-images.githubusercontent.com/5144163/66733450-2f6fc200-ee92-11e9-8a19-3f28198da8f8.png)

**Comment by MatthewARM** [comment]
Hi @rouyunpan should be in the tests/ folder, but it's a static library not a .so:

```
armnn$ ls tests/*.a
tests/libinferenceTest.a
```

**Comment by rouyunpan** [comment]
Because ARM disable the option "BUILD_TESTS" by default. 
I add "-DBUILD_TESTS=1" in cmake option of ARM NN and get this library.

There're some mismatch between ARM NN and ML-examples.
