### ISSUE TITLE
Add a test to be used with live Camera and/or video files

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#283]
It would be great to have a test example with live Camera and/or video files as real (edge) use cases will probably be such a case.

TI provides such an example by adding patches on top of ArmNN in Yocto:  https://layers.openembedded.org/layerindex/recipe/87610/

Source files seems to be under [BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause), so not sure how to add them to ArmNN.
I pinged the author to know if he would be ok to upstream those patches, but I got no feedback so far.

**Comment by matthewsloyanARM** [comment]
Hi @ggardet,

It seems the first link doesn't work anymore, also did you ever receive any reply from the author? We would much appreciate your contribution to add this example if it is still available.

As this is an old issue and based on the updated README.md found [here](https://github.com/ARM-software/armnn/tree/master#how-to-get-involved) under the "How to get involved" section I will close this issue as it is labeled with "Feature Request". Instead, we will be tracking the issue and adding the "Help wanted" label. If you would like to continue with it feel free to reopen this ticket and let us know you are still working on it with a quick comment. We will then track the updates and help you get your additions into our codebase.

Below you will find our contributors guide. If you have any questions feel free to ask here or by creating a new Issue, thank you!

https://www.mlplatform.org/contributing

Kind regards,

Matthew

**Comment by ggardet** [comment]
The patches are still available here: https://build.opensuse.org/package/show/science:machinelearning/armnn
But the original authors do not work for TI anymore.
