### ISSUE TITLE
Want help

### ISSUE THREAD

**Issue by VinayKarnam** [ARM-software/armnn#284]
Hello everyone,
                      
                     
  I am an undergraduate student from India. As part of our academic project in college,
 we have developed armnn caffe2 parser which is compatible with the 18_11 version ( we have not 
tested with the latest version ). We wanted to opensource the code. I have checked the contribution
 guide, as we are new to this opensource kind of stuff, I am finding it difficult to follow. Can anyone 
help us to contribute to the library?

Link to our repo : [https://github.com/kletechuni/armnn_caffe2_parser/tree/vinay]

We have tested our code by running alexnet and mobilenet_v1 models.

**Comment by VinayKarnam** [comment]
@mark-arm

**Comment by MatthewARM** [comment]
Hi @VinayKarnam,

Many thanks for your interest.

The first thing to do is to get it working with the latest master branch of Arm NN.

Next make sure you can log in to gerrit at https://review.mlplatform.org/#/dashboard/self using your Github account. Add your ssh key under "settings -> SSH public keys".

Then submit it to a gerrit review with a command like this, replacing `<github username>` with your Github username:
`git push ssh://<github username>@review.mlplatform.org:29418/ml/armnn` HEAD:refs/for/master

Hope that makes sense, 
Matthew

**Comment by VinayKarnam** [comment]
Thank you @MatthewARM for helping out,
submitted the code for gerrit review

**Comment by MatthewARM** [comment]
Great, thanks very much.

Your review is at https://review.mlplatform.org/c/ml/armnn/+/2303

@MatteoArm has already added some comments.

**Comment by MatthewARM** [comment]
Hi @VinayKarnam are you still interested in working on this? 

All the best,
Matthew

**Comment by VinayKarnam** [comment]
Hi @MatthewARM 
I was quite busy with my course work.
Now I am free, and  excited to work on this. Will be waiting for your next suggestion related to this change.

**Comment by MatthewARM** [comment]
Hi @VinayKarnam welcome back! Hope your course work has gone well.

I'll comment on the review for the next steps.

**Comment by MatthewARM** [comment]
Hi @VinayKarnam the review is looking broadly OK, but we won't be able to progress until you can do the "Signed-Off-By" line in the commit message, showing that you are abiding by the Developer Certificate Of Origin https://developercertificate.org/

**Comment by FrancisMurtagh-arm** [comment]
Hi @VinayKarnam,

I'm closing this ticket but I will leave your review in Gerrit until a decision is made on whether we wish to support Caffe2, we have recently deprecated the CaffeParser and have focused more on TfLite and ONNX.

Thanks,
Francis.
