### ISSUE TITLE
openCL backend enhancement

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#286]
Currently, ArmNN only support `CL_DEVICE_TYPE_GPU`, but according to [1] there are more devices which could be supported, including: `CL_DEVICE_TYPE_ACCELERATOR`, `CL_DEVICE_TYPE_CUSTOM` (?) or maybe even `CL_DEVICE_TYPE_CPU`?

[1] :  https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/clGetDeviceIDs.html#targetText=A%20bitfield%20that%20identifies%20the%20type%20of%20OpenCL%20device.&targetText=The%20host%20processor%20runs%20the,device%20that%20is%20a%20GPU. 

Is there any plan for this?

**Comment by MatthewARM** [comment]
I agree the handling of devices is a bit crude (it always uses the 'default' device) but does it really not work for things other than CL_DEVICE_TYPE_GPU? I've used a CPU device to test things early in Arm NN development and it mostly worked OK back then...

**Comment by MatthewARM** [comment]
@ggardet in practice, do you know of any OpenCL platform that is not CL_DEVICE_TYPE_GPU?

**Comment by matthewsloyanARM** [comment]
Hi @ggardet,

Thank you for reaching out! Based on the updated `README.md` found [here](https://github.com/ARM-software/armnn/tree/master#how-to-get-involved) under the "How to get involved" section we will be closing GitHub issues labeled with "Feature Request". Instead, we will be tracking the issue and adding the "Help wanted" label. All the issues with this label can be found [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). We would much appreciate your help to add these features. If you would like to add this or any feature to Arm NN feel free to reopen this ticket and let us know you are working on it with a quick comment. We will then track the updates and help you get your additions into our codebase.

Below you will find our contributors guide. If you have any questions feel free to ask here or by creating a new Issue, thank you!

https://www.mlplatform.org/contributing

Kind regards,

Matthew
