### ISSUE TITLE
python enablement

### ISSUE THREAD

**Issue by peter197321** [ARM-software/armnn#287]
just curious question: is there python package for arm nn ? make it sense to have one?

**Comment by MatthewARM** [comment]
Hi @peter197321 I think it could make a lot of sense, but we don't have one at the moment. I'll update this ticket if we have any news. We'd certainly accept patches adding a Python package.

**Comment by MatthewARM** [comment]
Hi @peter197321 there is some early development code for this on the experimental/pyarmnn branch at https://git.mlplatform.org/ml/armnn.git/log/?h=experimental/pyarmnn if you would like to get involved in development or testing. Any input would be appreciated.
