### ISSUE TITLE
Can we check if CpuAcc backend supports QuantizedLstmLayer?

### ISSUE THREAD

**Issue by alanhsu5678** [ARM-software/armnn#291]
Hi,

I am using Arm NN sdk v19.08 + ACL v19.08

In the release notes of v19.08 arm nn, it mentioned:
Added Quantized_LSTM layer support to CpuAcc and GpuAcc backend

I write a test program reference to the function SerializeDeserializeQuantizedLstm @src/armnnSerializer/test/SerializerTests.cpp to verify if CpuAcc backend supports QuantizedLstmLayer.

However, the result seems CpuAcc backend doesn't support QuantizedLstmLayer.

Could you please help check if there is any possible issue?

Thanks.
Alan

**Comment by james-conroy-arm** [comment]
Hi Alan,

The release notes are correct in that we support Quanitzed_LSTM on CpuAcc and GpuAcc. The layer is not currently supported on the Reference backend (CpuRef), however.

Can you please supply us with the error message(s) you received, and some more info on how to reproduce.

Thanks,
James

**Comment by arovir01** [comment]
Optimize() takes an optional vector of strings to write error messages to. It would probably be helpful to provide it and see the messages placed into it:

```
std::vector<std::string> errorMessages;
armnn::IOptimizedNetworkPtr optNet = Optimize(*network, {Compute::CpuAcc, Compute::CpuRef}, run->GetDeviceSpec(), armnn::Optional<std::vector<std::string>&>(errorMessages));
```

Then print out the content of `errorMessages`. It should give you an idea why your layer is not supported.

**Comment by james-conroy-arm** [comment]
Hi Alan,

I have looked at your code and I see a few issues with how you have setup the quantization parameters. Please see my diagram below for the data types for each tensor (note that in ArmNN uint8 === QuantisedAsymm8 and int16 === QuantisedSymm16):
![Quantized_Lstm diagram](https://user-images.githubusercontent.com/44364429/67492077-cf390700-f66d-11e9-9f4e-450813b004de.jpg).

There is also specific scale/offsets you need to specify for this layer, which are defined in the Android NN docs (https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a42edb5ab6f1c74f4a756eb1ed0183a16)

The scale/offsets are:
float inputOutputScale = 0.0078125f;
int32_t inputOutputOffset = 128;

float cellStateScale = 0.00048828125f;
int32_t cellStateOffset = 0;

float weightsScale = 0.00408021f;
int32_t weightsOffset = 100;

float biasScale = 3.1876640625e-05f;
int32_t biasOffset = 0;

Please see how this is all put together when creating tensors in the tests for this layer here (also ensuring that the shape of each tensor is correct - this is based on the number of batches, input size and output size): https://github.com/ARM-software/armnn/commit/9c3cae8683e4b24932446b88d3ecbc02f9f9fa08

Let me know how you get on!

Cheers,
J

**Comment by alanhsu5678** [comment]
> Optimize() takes an optional vector of strings to write error messages to. It would probably be helpful to provide it and see the messages written into it by the optimizer:
> 
> ```
> using namespace armnn;
> // ...
> std::vector<std::string> errorMessages;
> IOptimizedNetworkPtr optNet = Optimize(*network, { Compute::CpuAcc, Compute::CpuRef }, run->GetDeviceSpec(), Optional<std::vector<std::string>&>(errorMessages));
> ```
> 
> Then print out the content of `errorMessages`. It should give you an idea why your layer is not supported.

Hi @arovir01 ,

Thanks for the suggestion.
The dumped errMessages are:
errMessages[3]: WARNING: Layer of type QuantizedLstm is not supported on requested backend CpuAcc for data type Unsigned8 (reason: in validate src/runtime/NEON/functions/NELSTMLayerQuantized.cpp:253: input_to_input_weights->num_dimensions() > 2), falling back to the next backend.

Thanks!

Alan

**Comment by alanhsu5678** [comment]
> Hi Alan,
> 
> I have looked at your code and I see a few issues with how you have setup the quantization parameters. Please see my diagram below for the data types for each tensor (note that in ArmNN uint8 === QuantisedAsymm8 and int16 === QuantisedSymm16):
> ![Quantized_Lstm diagram](https://user-images.githubusercontent.com/44364429/67492077-cf390700-f66d-11e9-9f4e-450813b004de.jpg).
> 
> There is also specific scale/offsets you need to specify for this layer, which are defined in the Android NN docs (https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a42edb5ab6f1c74f4a756eb1ed0183a16)
> 
> The scale/offsets are:
> float inputOutputScale = 0.0078125f;
> int32_t inputOutputOffset = 128;
> 
> float cellStateScale = 0.00048828125f;
> int32_t cellStateOffset = 0;
> 
> float weightsScale = 0.00408021f;
> int32_t weightsOffset = 100;
> 
> float biasScale = 3.1876640625e-05f;
> int32_t biasOffset = 0;
> 
> Please see how this is all put together when creating tensors in the tests for this layer here (also ensuring that the shape of each tensor is correct - this is based on the number of batches, input size and output size): [9c3cae8](https://github.com/ARM-software/armnn/commit/9c3cae8683e4b24932446b88d3ecbc02f9f9fa08)
> 
> Let me know how you get on!
> 
> Cheers,
> J

Hi James,

Thanks for the info!
After I applied your suggestion, the validation still got failed.
I think the reason is the dimension defined in function SerializeDeserializeQuantizedLstm @src/armnnSerializer/test/SerializerTests.cpp is 4, which is larger than 2 as the following code section in ACL:

validate() function @src/runtime/NEON/functions/NELSTMLayerQuantized.cpp
    // Dimensionality checks
    ARM_COMPUTE_RETURN_ERROR_ON(input->num_dimensions() > 2);
    ARM_COMPUTE_RETURN_ERROR_ON(input_to_input_weights->num_dimensions() > 2);
    ARM_COMPUTE_RETURN_ERROR_ON(input_gate_bias->num_dimensions() > 1);
    ARM_COMPUTE_RETURN_ERROR_ON(output_state_in->num_dimensions() > 2);

The errorMessages:
    armnn::ConstTensor inputToInputWeights(armnn::TensorInfo(
            4, inputToInputWeightsDimensions.data(),
            armnn::DataType::QuantisedAsymm8, weightsScale, weightsOffset), inputToInputWeightsData);

Is it a bug for the SerializeDeserializeQuantizedLstm test in SerializerTests.cpp?

B.R.
Victor

**Comment by james-conroy-arm** [comment]
Hi Alan,

For the SerializeDeserializeQuantizedLstm test, it looks like the tensors are not setup correctly to pass validation in ArmNN/ACL (the test wasn't created for this purpose, however). For all of the tensors, the number of dimensions is 4:
`armnn::ConstTensor inputToInputWeights(armnn::TensorInfo(
        4, inputToInputWeightsDimensions.data(),
        armnn::DataType::QuantisedAsymm8), inputToInputWeightsData);`

As per the Android documentation, all tensors should be 2-D, except for the Bias tensors, which are 1-D. You will need to change the shape of the bias tensor to {1, 1, 1, 9}.

You could also use the values used in some of the tests I linked you above to test functionality.

- J

**Comment by MatthewARM** [comment]
{1, 1, 1, 9} (ie. 4D tensor, degenerate in leading three dimensions) will work for a bias. 

In very early versions of Arm NN it was required to specify every tensor as 4D (with leading size 1 dimensions in cases like this). 

This has been fixed and now {9} (ie. 1D tensor) will also work, and is preferred.

**Comment by arovir01** [comment]
As James mentioned it, the serialization tests only verify if the layer is serialized and deserialized correctly, i.e. they only check whether the layer the deserializer reconstructs has the exact same properties as the one that was serialized. There is no guarantee that the layers used in those tests are actually valid and executable on any particular backend.

**Comment by MatthewARM** [comment]
Still, unless there's a reason (for test coverage) that this test should use an invalid definition, we could change it. That would avoid the confusion.

@alanhsu5678 feel free to submit a review (on review.mlpatform.org) for this change. I see no reason why this test case can't be changed to use a valid LSTM configuration.

Other than that, I think the original reported issue has been resolved? (ie. CpuAcc backend does support QuantizedLstmLayer, and checking it works in the normal way).

**Comment by james-conroy-arm** [comment]
Thanks for pointing out the invalid test definition @alanhsu5678 , I didn't realise you were referring to it in your initial post. As @MatthewARM suggested, this should be fixed to avoid confusion in the future. If you're interested in submitting a patch, see the contributor's guide for ArmNN: https://github.com/ARM-software/armnn/blob/branches/armnn_19_08/ContributorGuide.md

Cheers,
James

**Comment by alanhsu5678** [comment]
Hi all,

Already uploaded my commit as the follows:
https://review.mlplatform.org/c/ml/armnn/+/2168

B.R.
Alan

**Comment by MatthewARM** [comment]
Many thanks.

**Comment by arovir01** [comment]
Hi Alan,

Thank you for your contribution. Please be aware, however, that it does not compile in its current form.

**Comment by alanhsu5678** [comment]
Hi @arovir01 ,

OK, I'll check on it and upload a new patch set.

B.R.
Alan

**Comment by arovir01** [comment]
It seems the parantheses are in the wrong place, the scale and the offset needs to go inside the TensorInfo constructor.

**Comment by james-conroy-arm** [comment]
Thanks @alanhsu5678 !

**Comment by alanhsu5678** [comment]
Close this issue and thanks for the support!

Alan
