### ISSUE TITLE
backendsCommon/BackendRegistry.hpp is not installed by CMake

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#292]
`backendsCommon/BackendRegistry.hpp` is not installed by CMake, which leads to build errors for Arm ML examples: https://github.com/ARM-software/ML-examples/blob/master/armnn-mobilenet-quant/mobilenetv1_quant_tflite.cpp#L10

```
[  129s] g++ -DARMNN_TF_LITE_PARSER -I/include -I/src/backends -I/src/armnnUtils -I/tests -I/usr/lib64/../include -Wall -O3 -std=c++14 -fPIE mobilenetv1_quant_tflite.cpp -o mobilenetv1_quant_tflite -pie -L -L/tests -L/usr/lib64/../lib64 -larmnn -larmnnTfLiteParser -linferenceTest -lboost_system -lboost_filesystem -lboost_program_options
[  129s] mobilenetv1_quant_tflite.cpp:10:10: fatal error: backendsCommon/BackendRegistry.hpp: No such file or directory
[  129s]    10 | #include "backendsCommon/BackendRegistry.hpp"
[  130s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MatthewARM** [comment]
Yep, there's probably other stuff missing too. The new backends stuff hasn't been properly figured out wrt separate compilation of applications. @DerekLamberti @MatteoArm ?

I think some stuff from backendsCommon needs to move into `include`.

**Comment by MatteoArm** [comment]
Hi @ggardet,

Your build command:
`g++ -DARMNN_TF_LITE_PARSER -I/include -I/src/backends -I/src/armnnUtils -I/tests -I/usr/lib64/../include -Wall -O3 -std=c++14 -fPIE mobilenetv1_quant_tflite.cpp -o mobilenetv1_quant_tflite -pie -L -L/tests -L/usr/lib64/../lib64 -larmnn -larmnnTfLiteParser -linferenceTest -lboost_system -lboost_filesystem -lboost_program_options`
doesn't look right, the include paths look like they are missing the root (like -I/include, or -I/src/backends).
It seems that you are not setting ARMNN_ROOT and/or ARMNN_BUILD etc. as the readme describes.

Tested on my machine with:
`CXX=g++ ARMNN_ROOT=/work/devenv_q/armnn ARMNN_BUILD=/work/devenv_q/build-x86_64/release/armnn BOOST_ROOT=/work/devenv_q/install/x86_64/boost make`
and it builds fine

Regards
Matteo

**Comment by MatthewARM** [comment]
@MatteoArm,

@ggardet is testing arm nn as "installed" on a system, so it won't have access to internal-only headers. We need to change CMakeLists.txt to "install" the right things. Our convention is that public stuff that gets installed lives in armnn/include. ggardet's test shows that backendsCommon/BackendRegistry.hpp is needed by client application code, so it should move to the include directory (and get installed).

**Comment by ggardet** [comment]
@MatteoArm I do not want to use the full sources to build some examples, but just a proper `devel` package.

**Comment by MatthewARM** [comment]
:-)

**Comment by MatteoArm** [comment]
Yep, confirmed. backendsCommon/BackendRegistry.hpp needs to be moved to the include directory (or we have to install bits from other places, like backendsCommon in this case).
I'll see what else is missing
