### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by MatthewARM** [ARM-software/armnn#293]
I would suggest that armnn should fall into line with standard x.y.z library numeric versioning standards employed across many a project. 

Not convinced? 

Version numbers often imply API/ABI compatibility. Something date based does not. If we want to support list distros (and i think we do), then we need to rely on those version numbers as a commitment as well as a signal when an app will need to be rebuilt. 

Also it wouldn't be a bad idea to start to run like libabigail to watch for changes that could break an app using the shared library. I think this could be something we do as part of the mlplatform CI system in Linaro.

_Originally posted by @tom-gall in https://github.com/ARM-software/armnn/issues/275#issuecomment-541234715_

**Comment by Colm-in-Arm** [comment]
This should be implemented in 20.05

**Comment by FrancisMurtagh-arm** [comment]
We now use semantic versioning for our libraries, we also run the abi-compliance-checker on reviews which is similar to libabigail.
https://lvc.github.io/abi-compliance-checker/
