### ISSUE TITLE
request on public .armnn sample model 

### ISSUE THREAD

**Issue by Tee0125** [ARM-software/armnn#294]
I made a patch on Netron to support armnn serialized format and the maintainer requested to add public .armnn model to test.js but I couldn't find public .armnn model link...

So if there's public .armnn model in armnn site or wherever, please let me know the link.

see also:
* https://github.com/lutzroeder/netron/pull/364

**Comment by MatthewARM** [comment]
Thanks @Tee0125, would a really simple example be enough? We could create one.

**Comment by Tee0125** [comment]
code used in dump as in below:

```import torch
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self. layer1 = nn.Sequential(nn.Conv2d(3,20,3),
                                     nn.BatchNorm2d(20),
                                     nn.ReLU(),
                                     nn.MaxPool2d(2))

        self.layer2 = nn.Sequential(nn.Conv2d(20,20,5, padding=2),
                                    nn.BatchNorm2d(20),
                                    nn.Tanh())

    def forward(self, x):
        y = self.layer1(x)
        z = self.layer2(y)

        return y + z;

m = Model()

m.layer1[1].num_batches_tracked = torch.IntTensor(1)
m.layer2[1].num_batches_tracked = torch.IntTensor(1)

print(m)

dummy_input = torch.randn(1, 3, 352, 288)

input_names = [ "input1" ]
output_names = [ "output1" ]

torch.onnx.export(m, dummy_input, "dump.onnx", verbose=True, input_names=input_names, output_names=output_names)```

**Comment by Tee0125** [comment]
armnn's onnx parser make tensor_info with graph->value_info but pytorch does not export weights/bias tensors to graph->value_info when nn.conv member of nn.Sequential, so armnn converter is crashed

And also armnn supports TanH activation but onnx parser have parse method for TanH layer, so I made a patch and converted onnx file dumped with code in above.

[simple_network.armnn.zip](https://github.com/ARM-software/armnn/files/3796679/simple_network.armnn.zip)

**Comment by MatthewARM** [comment]
@Tee0125 it would be great if you could submit a review on mlplatform.org adding this stuff - I think it could go into 'samples/torch'?

Alternatively you could put it on your own github?

**Comment by Tee0125** [comment]
I submitted review on mlplatform.org, see you there 

let me close the issue.
