### ISSUE TITLE
PRelu Support for MTCNN

### ISSUE THREAD

**Issue by td-embeans** [ARM-software/armnn#295]
Dear friends, 

Thanks for doing great work with ArmNN. I am trying to implement the MTCNN model in the ARMNN. But I see the PRelu is not yet supported in ARM. Because of that the Caffe Parser is not able to read it properly. Though in the 19.8 release I see this is mentioned that PRelu is supported. When can we expect to have this as full feature and able to run the MTCNN? 
Have you guys tried to run the MTCNN yet on ARMNN?  What was the result?

**Comment by MikeJKelly** [comment]
Hi  td-embeans,

we have added support for PReLU to both Arm NN and the Android driver in 19.08 however support was not added to the CaffeParser. We do not currently have an estimate for when it will be added. 

If you like you could try to add support to CaffeParser yourself (in CaffeParser.cpp)? You can you can read the contributor guide (linked to from the Readme.md) and if you would like you can join the armnn-dev mailing list to discuss your changes.

**Comment by td-embeans** [comment]
Hello Mike, 
Thanks for your input. 
I have added support the PReLU in the Caffe parser. I have taken reference of ReLU layer parsing code. Now I can load the MTCNN model using the CaffeParser. But I am getting exception while loadNetwork. Still looking into it. Any reference will be really helpful. 

Regards

**Comment by MikeJKelly** [comment]
Hi td-embeans,

what does your exception look like? Can you share the details? 

Checking back I can see that someone attempted to add support for Prelu to caffe in the past, the ticket might contain some useful information:

https://github.com/ARM-software/armnn/issues/232

**Comment by td-embeans** [comment]
Please check the #232  for the log

**Comment by MikeJKelly** [comment]
I've responded in #232

**Comment by Colm-in-Arm** [comment]
Hi @td-embeans,

Would you be willing to contribute your modification to the Caffe parser?

Colm.

**Comment by matthewsloyanARM** [comment]
Hi @td-embeans, 

Unfortunately with the upcoming Arm NN release (21.05) we will be deprecating the Arm NN Caffe Parser, so we won't be able to make this contribution. Based on this I will close this Issue and remove the "Help wanted" label.

We appreciate your efforts and your work on this. If you would like to help again with the development of Arm NN feel free to take a look at the help wanted section [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). You can also find our contributors guide [here](https://www.mlplatform.org/contributing) too which will show you how you can submit a patch to us. Thank you, all the best!

Kind regards, 

Matthew
