### ISSUE TITLE
rmnn Error: Unsupported operation SpaceToBatchND in tensorflow::GraphDef

### ISSUE THREAD

**Issue by quyetvk** [ARM-software/armnn#296]
Hi all,

We tried to run our own tensorflow model (with armnn 19.08) and got the error in parse step:
"Unsupported operation SpaceToBatchND in tensorflow::GraphDef  at function LoadNodeDef"

Can anyone suggest us a solution?
Thank you!

**Comment by james-conroy-arm** [comment]
Hi @quyetvk ,

The error is indicating that our Tensorflow model parser does not have support for SpaceToBatchND. Our TfLite parser does have support for this layer (our TfLite compatibility is a bit more advanced than Tensorflow). Could you please try converting your model to TfLite and trying it then?

TfLite models (through tflite_convert) have the added benefit of performing a standard set of optimisations on the graph, such as removing training-only nodes.

Cheers,
James

**Comment by quyetvk** [comment]
Hi @james-conroy-arm 

Thank you very much for your quick support. We will try your suggestion.
Anyway, do you have near plan to support this layer?

Best regards

**Comment by james-conroy-arm** [comment]
Hi @quyetvk ,

No problem. Unfortunately, we don't have any near-term plans to add TfParser support for this layer.

If you would like to add the support yourself, that'd be great also. This would require modifying armnn/src/armnnTfParser/TfParser.cpp (see this file for other examples). If you are interested (and we'd be happy to help you along the way if needed), please see:
[Contributor's Guide](https://github.com/ARM-software/armnn/blob/master/ContributorGuide.md)
[ArmNN Gerrit Code Review](https://review.mlplatform.org/#/q/project:ml/armnn) (login with GitHub)

Cheers,
James
