### ISSUE TITLE
Logging Support in ARMNN

### ISSUE THREAD

**Issue by td-embeans** [ARM-software/armnn#298]
Dear Friends, 

Is there any plan to add support of Logging for Debugging in the ARMNN codebase ?

**Comment by arovir01** [comment]
There is a setting for the optimizer to insert a DebugLayer after each operation, which dumps the tensor content it receives to cout (and then forwards it to the next layer). It is somewhat rudimentary for now, but it should help you with your debugging.

**Comment by MatthewARM** [comment]
Also, have you turned on logging via `Utils.hpp`?

**Comment by MatthewARM** [comment]
Closing this as I believe the question has been answered. Please get back in touch if you need more information.
