### ISSUE TITLE
Is YOLO Tiny v2 expected to work with Arm NN?

### ISSUE THREAD

**Issue by lordalcol** [ARM-software/armnn#299]
Hi @MatthewARM ,

I am trying to use the pre-trained YOLO v2 (tiny) model, converted to Caffe (https://github.com/tsingjinyun/caffe-yolov2/), with Arm NN v19.08.
I get a segfault when I enqueue the workload.

Is it known to work?

Thanks,
Lorenzo

**Comment by MatthewARM** [comment]
I'm pretty sure that tiny Yolo v2 is known to work. If you're seeing a segfault on EnqueueWorkload it's almost always because your buffers are too small - can you check that you are using buffers big enough, according to TensorInfo::GetNumBytes on the input and output tensors?

**Comment by lordalcol** [comment]
That was the case, thanks. It's running now. I am not sure yet about the output, since I haven't written the parser yet, but at least it's not crashing anymore.
