### ISSUE TITLE
cmake build error 

### ISSUE THREAD

**Issue by Junhyuk** [ARM-software/armnn#3]
cmake build error occured whilng buiding arm nn .
Any of you guys who release on this topic, please share the solution to find out this problem. 

cmake -DARMCOMPUTE_ROOT=<the location of your Compute Library source files directory> -DARMCOMPUTE_BUILD_DIR=<the location of your Compute Library source files directory>/build -- Boost version: 1.64.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   filesystem
--   log
--   program_options
--   date_time
--   log_setup
--   thread
--   regex
--   chrono
--   atomic
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOBUF_LIBRARY
    linked by target "armnnCaffeParser" in directory

**Comment by MatthewARM** [comment]
Hi @Junhyuk you should only get that error if you have set BUILD_CAFFE_PARSER, but you don't have that set in your cmake command. Possibly your cmake cache has got some old variables in it. Try deleting CMakeCache.txt from your build directory and trying again.

**Comment by liviolima80** [comment]
Hi, 
I have the same issue using cmake with the following string

cmake -DARMCOMPUTE_ROOT=/home/vigilate/A2/third-party-lib/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=/home/vigilate/A2/third-party-lib/ComputeLibrary/build -DBOOST_ROOT=/home/vigilate/A2/third-party-lib/build_boost_1_64 -DCAFFE_GENERATED_SOURCES=/home/vigilate/A2/third-party-lib/CaffeOnACL/build/src  -DBUILD_CAFFE_PARSER=1 -DARMCOMPUTENEON=1 ..

I have protobuf already cross-compiled but i don't know how to specify the library path

Thanks

**Comment by MatthewARM** [comment]
Hi @liviolima80 and @Junhyuk, please could you try adding -DPROTOBUF_LIBRARY_DEBUG=<path to libprotobuf.so> and  -DPROTOBUF_LIBRARY_RELEASE=<path to libprotobuf.so> to your cmake command?

**Comment by Junhyuk** [comment]
please checkbelow error similar before. 


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ARMCOMPUTE_CORE_LIBRARY_DEBUG
    linked by target "armnn" in directory /home/junhyuk/samba_server/coding/armnn
ARMCOMPUTE_CORE_LIBRARY_RELEASE
    linked by target "armnn" in directory /home/junhyuk/samba_server/coding/armnn
ARMCOMPUTE_INCLUDE
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
   used as include directory in directory /home/junhyuk/samba_server/coding/armnn
ARMCOMPUTE_LIBRARY_DEBUG
    linked by target "armnn" in directory /home/junhyuk/samba_server/coding/armnn
ARMCOMPUTE_LIBRARY_RELEASE
    linked by target "armnn" in directory /home/junhyuk/samba_server/coding/armnn
HALF_INCLUDE

**Comment by MatthewARM** [comment]
Thanks @liviolima80 this will be included in the cross-compiling documentation which is under development. The existing documentation is all for native compilation on aarch64 linux, where it is assumed that libprotobuf.so is installed on a standard system path.

@Junhyuk I'm sorry to hear that you are still having problems - in this case it looks like you are not setting ARMCOMPUTE_ROOT and ARMCOMPUTE_BUILD_DIR correctly. When running cmake, please replace `<the location of your Compute Library source files directory>` with the path on your computer where you cloned the Compute Library, e.g. `/home/junhyuk/samba_server/coding/ComputeLibrary`.

I'm going to close this issue as I think the original problem (PROTOBUF_LIBRARY set to NOTFOUND) has been resolved - feel free to open new issues for any other problems.
