### ISSUE TITLE
ArmnnConverter Segmentation Fault

### ISSUE THREAD

**Issue by kl456123** [ARM-software/armnn#300]
after I run command `./ArmnnConverter -f onnx.binary -m xx -o xx -p xx -i xx`
I just get segmentation fault (core dumped) without other information

using gdb I get to know that error is happening at  `converter.CreateNetwork<armnnOnnxParser::IOnnexParser>()`

I am so disappointed because I get nothing after a long time of compilation

**Comment by FrancisMurtagh-arm** [comment]
Hi,

That particular line should be:

`converter.CreateNetwork<armnnOnnxParser::IOnnxParser>`

Was that just a typo in your issue description or did gdb say "IOnnexParser"?

Regards,
Francis.

**Comment by kl456123** [comment]
Sorry ,  that is my mistake, I typed it instead of copying from terminal

**Comment by MatthewARM** [comment]
Can you post us the model so we can try?

**Comment by james-conroy-arm** [comment]
Hi @kl456123 ,

I think this issue is resolved now, could you close if it is please?

Cheers,
James
