### ISSUE TITLE
armnn version info

### ISSUE THREAD

**Issue by peter197321** [ARM-software/armnn#301]
I have preinstalled armnn libs on my system, is it possible to get version information om ARM-NN install programmatically? 
Thanks.

**Comment by MikeJKelly** [comment]
Hi peter197321 

there is currently no way of getting version information from Arm NN programatically. Adding semantic versioning information is planned however we don't know when it will be available. 

Yours,
Mike 

See #293

**Comment by MatthewARM** [comment]
I think there's a way of logging the Arm NN version, if that's all you need? Try turning on maximum verbosity using the logging routines in Utils.hpp, and I think you will get a log message that shows the version number.

**Comment by james-conroy-arm** [comment]
Hi @peter197321 ,

We are tracking the addition of Semantic Versioning to ArmNN in #293 .

Were you able to get the version number using Matthew's approach above?

Cheers,
James

**Comment by FrancisMurtagh-arm** [comment]
Hi @peter197321,

A GetVersion API has been added during 21.02 release.

include/armnn/Utils.hpp

`const std::string GetVersion();`

Regards,
Francis.
