### ISSUE TITLE
armnn::ParseException: ReadBase128 exceeded the maximum number of bytes expected for an integer representation

### ISSUE THREAD

**Issue by lordalcol** [ARM-software/armnn#302]
Hi,
I am trying to load a caffemodel of Yolo v2 (Tiny) that I have created using darknet and converted with https://github.com/tsingjinyun/caffe-yolov2 

Unfortunately when I load it in Arm NN, it's throwing me the error: 
```armnn::ParseException: ReadBase128 exceeded the maximum number of bytes expected for an integer representation```

The same model works with Caffe.

**Comment by lordalcol** [comment]
Fixed.

**Comment by JingSun3747** [comment]
I met the same problem, and how to solve it?
