### ISSUE TITLE
Error while running UnitTest

### ISSUE THREAD

**Issue by 4rmature** [ARM-software/armnn#303]
I am following the "How to Cross-Compile ArmNN on x86_64 for arm64" guide and have successfuly built all dependencies and built ArmNN with no error.
 
However, when i run UnitTest i am getting the following error.

Running 1741 test cases...
/home/aditya.c/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(738): error: in "DynamicBackendTests/GetSharedObjects": check sharedObjects.size() == expectedSharedObjects.size() has failed [12 != 9]
/home/aditya.c/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp(747): error: in "DynamicBackendTests/GetSharedObjects": check sharedObjects[8] == expectedSharedObjects[8] has failed [/home/root/aditya.c/armnn/build/src/backends/backendsCommon/test/backendsTestPath2/Arm_CpuAcc_backend.so.1 != /home/root/aditya.c/armnn/build/src/backends/backendsCommon/test/backendsTestPath2/Arm_GpuAcc_backend.so]

May I know how to solve this?

**Comment by MatthewARM** [comment]
@MatteoArm ?

**Comment by 4rmature** [comment]
I re ran armnn build and it worked this time.
I dont know why it occurred but it is working now.

**Comment by 4rmature** [comment]
Can i know how to solve this issue?

**Comment by MatthewARM** [comment]
It's OK, just click 'Close'. I've done it and this issue is closed now.

**Comment by zhaozhixu** [comment]
@4rmature @MatthewARM
 I've also run into this issue. It seems like the test trying to filter out the symbol links to Arm_CpuAcc_backend.so. But if you cross compile the test and `scp -r` the `build` directory to an ARM device, the symbol links become invalid and the test cannot filter them out, thus there are 3 more SharedObjects [12 != 9]:

Arm_CpuAcc_backend.so.1
Arm_CpuAcc_backend.so.1.2
Arm_CpuAcc_backend.so.1.2.3

... and the name comparation goes wrong [check sharedObjects[8] == expectedSharedObjects[8] ].

By the way, using `rsync` instead won't make symbol links invalid.
Consider add some notice in the guide?

**Comment by MatthewARM** [comment]
Thanks @zhaozhixu that makes sense.
