### ISSUE TITLE
ARMNN Quantization

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/armnn#305]
Hi,

I quantized few models with .csv file on ARM Target(HiKey960) using ARMNN.
I have observed that on hikey 960 it takes a considerable amount of time to quantize. 

It would be great if the ARMNN quantization module can be run on CPU targets like Intel . Once the quantization is done we could port it to ARM targets accordingly. Reason for raising this concern is ,quantization would be comparatively much faster on Intel CPUs/GPUs . 

Let us know your comments on this.

Thank you,
Praveen.

**Comment by arovir01** [comment]
ArmnnQuantizer can be built and run on x86.

**Comment by MatthewARM** [comment]
Oops

**Comment by uu-praveeng** [comment]
Thank you @arovir01 . I did not try it on host PC's . Surely will give it a try.

@MatthewARM  , 
Did you want to add anything to this query.  If not , Let me know if I could close this.

**Comment by uu-praveeng** [comment]
I was able to build and run armnnquantizer on Host PC.

Thank you
