### ISSUE TITLE
Can we run onnx model on arm nn android. if yes please tell me how.

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#308]

**Comment by MatthewARM** [comment]
Hi @paragikjain I am aware of https://github.com/JDAI-CV/DNNLibrary that provides Android NNAPI access from ONNX.

If you are using the Arm NN API directly in your application, you can try using the armnnOnnxParser but be warned it is at a fairly early stage of development and may not support the layers in your model. You can check https://github.com/ARM-software/armnn/blob/master/src/armnnOnnxParser/OnnxSupport.md to see if the layers in your model are supported.

**Comment by paragikjain** [comment]
Thanks bro

**Comment by MatthewARM** [comment]
armnnOnnxParser is just for Arm NN, which will run OK on Android. 

For the Android Neural Networks API try https://github.com/JDAI-CV/DNNLibrary.

**Comment by paragikjain** [comment]
@MatthewARM  Thanks!!

**Comment by paragikjain** [comment]
3dlm.cpp:92:24: error: use of undeclared identifier 'runtime'
                        armnn::Status ret = runtime->EnqueueWorkload(networkIdentifier,
error: use of undeclared identifier 'networkIdentifier'
                        armnn::Status ret = runtime->EnqueueWorkload(networkIdentifier

I am getting this two errors while runnig code.i have included all header files  properly.

**Comment by paragikjain** [comment]
aarch64-linux-android-clang++ -fPIE -pie -O3 -std=c++14 -I/home/parag.j/armnn-devenv/armnn/include FD_TF.cpp -o fd_tf -L/home/parag.j/armnn-devenv/armnn/build -L/home/parag.j/armnn-devenv/google/arm64_pb_install/lib -L/home/parag.j/armnn-devenv/ComputeLibrary/build -larmnn -larmnnTfParser -lprotobuf 

getting this error while making can you please help me with that

**Comment by paragikjain** [comment]
<pre>(base) <font color="#8AE234"><b>parag.j@CPU-349U</b></font>:<font color="#729FCF"><b>~/Downloads/armnn-eshwar/3dlm</b></font>$ make all
aarch64-linux-android-clang++ -fPIE -pie -O3 -std=c++14 -I/home/parag.j/armnn-devenv/armnn/include 3dlm.cpp -o fd_tf -L/home/parag.j/armnn-devenv/armnn/build -L/home/parag.j/armnn-devenv/google/arm64_pb_install/lib -L/home/parag.j/armnn-devenv/ComputeLibrary/build -larmnn -larmnnTfParser -lprotobuf 
/tmp/3dlm-afdfc7.o: In function `main&apos;:
3dlm.cpp:(.text+0x1dc): undefined reference to `armnnOnnxParser::IOnnxParser::Create()&apos;
clang60++: <font color="#EF2929"><b>error: </b></font>linker command failed with exit code 1 (use -v to see invocation)
make: *** [3D] Error 1
</pre>

getting this error while making cpp

**Comment by MatthewARM** [comment]
You need to have "-larmnnOnnxParser" (ONNX parser) not "-larmnnTfParser" (Tensorflow Parser)

**Comment by paragikjain** [comment]
<pre>aarch64-linux-android-clang++ -fPIE -pie -O3 -std=c++14 -I/home/parag.j/armnn-devenv/armnn/include 3dlm.cpp -o fd_tf -L/home/parag.j/armnn-devenv/armnn/build -L/home/parag.j/armnn-devenv/google/arm64_pb_install/lib -L/home/parag.j/armnn-devenv/ComputeLibrary/build -larmnn -larmnnOnnxParser -lprotobuf 
/home/parag.j/armnn-devenv/toolchains/aarch64-android-r17b/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -larmnnOnnxParser
clang60++: <font color="#EF2929"><b>error: </b></font>linker command failed with exit code 1 (use -v to see invocation)
make: *** [3D] Error 1
</pre>


Hi after changing it i am getting this error i  don't know  which path it is looking for can you help me with that
