### ISSUE TITLE
Image as an input to execute network

### ISSUE THREAD

**Issue by AnPay** [ARM-software/armnn#309]
Can i pass an image as an input to Execute network?
I see -d option which takes flat array, which i am able to do but i need to generate an input file for each model with different shape.
I see -t which takes a CSV file which I couldn't figure out how to use.
Please help.

**Comment by MatthewARM** [comment]
I don't think we do have the ability to an image. It wouldn't be impossible to add but it's not trivial - you'd need to be able to specify how it gets transformed to a tensor e.g. NHWC or NCHW, and what numerical range to use. That's why we can do it easily for the specific network test applications in `/tests/` but not so easily for ExecuteNetwork where we don't know how the network was trained. Out of interest, what would those parameters be for your images?

I think both `-d` and `-t` need a separate file for each input. The csv file would just be each number in the input tensor, separated by commas.

**Comment by ggardet** [comment]
@MatthewARM I guess one can convert an image to a specific format to be used by `-d` input?
Could you provide some examples for `ExecuteNetwork`, please?

**Comment by MatthewARM** [comment]
@ggardet I personally do it with Python, like this:

```
from PIL import Image
import sys
import os
import cv2
import numpy as np

''' This script create a numpy array separated by spaces aka a "input.snpy" 
    from an input image to be used on the ArmNN Execute Network app''' 

argvs=sys.argv
if (len(argvs) != 2):
 print 'Usage: # python %s imagepath' % argvs[0]
 quit()

img = argvs[1]

# get the file extension to rename the result with the .snpy exntension
file_name = os.path.splitext(img)[0]
print 'Loading %s to generate Execute Network input .snpy file' % file_name

im = cv2.imread(img)
snpy = ' '.join(map(str,im.flatten().tolist()))

print ''

# Writes new the new file as a .snpy
with open("%s.snpy" % file_name,'wb') as f:
    f.write(snpy)

# Checks if the .snpy file has been converted and saved
snpy_path=os.path.isfile(file_name+".snpy")
if snpy_path == True:
    print '%s.snpy has been saved to disk - Success !' % file_name
elif snpy_path == False:
    print "Something has gone wrong with the %s.snpy conversion and it failed to save" % file_name
```

**Comment by MatthewARM** [comment]
Depending on how the network was trained this is more or less likely to work. Most of the training frameworks use numpy in this way, so it's got a good chance of working.

This won't work for quantised models, which will need the input data quantised according to the parameters trained into the model.

**Comment by matthewsloyanARM** [comment]
Hi @ggardet,

Thank you for reaching out! Based on the updated `README.md` found [here](https://github.com/ARM-software/armnn/tree/master#how-to-get-involved) under the "How to get involved" section we will be closing GitHub issues labeled with "Feature Request". Instead, we will be tracking the issue and adding the "Help wanted" label. All the issues with this label can be found [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). We would much appreciate your help to add these features. If you would like to add this or any feature to Arm NN feel free to reopen this ticket and let us know you are working on it with a quick comment. We will then track the updates and help you get your additions into our codebase.

Below you will find our contributors guide. If you have any questions feel free to ask here or by creating a new Issue, thank you!

https://www.mlplatform.org/contributing

Kind regards,

Matthew
