### ISSUE TITLE
Runtime error while running onxx model on arm nn android

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#310]
Hi i am getting runtime error while running onnx model on armnn android  error is: 

<pre>(base) <font color="#8AE234"><b>parag.j@CPU-349U</b></font>:<font color="#729FCF"><b>~/Downloads/armnn-eshwar/3dlm</b></font>$ adb shell &apos;LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/3DLM&apos;
CANNOT LINK EXECUTABLE &quot;/data/local/tmp/3DLM&quot;: cannot locate symbol &quot;_ZN15armnnOnnxParser11IOnnxParser6CreateEv&quot; referenced by &quot;/data/local/tmp/3DLM&quot;...
</pre>

Please help with that

**Comment by arovir01** [comment]
Did you build armnnOnnxParser? It seems the dynamic linker is not able to find it.

**Comment by paragikjain** [comment]
yes i have built it

**Comment by Colm-in-Arm** [comment]
Hi @paragikjain,

Is this a problem you still need help with?

One little thing I noticed in your original error is that you are overwriting the LD_LIBRARY_PATH variable rather than adding to it.

Colm.

**Comment by paragikjain** [comment]
HI Thanks for response . Now i am not getting this issue.
