### ISSUE TITLE
How to run inference?

### ISSUE THREAD

**Issue by 4rmature** [ARM-software/armnn#316]
I am new to this, i just want to know how to write the application to run inference for 1 image using ssd_mobilenet_v1_quantized given in the following link:
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz

I have built ArmNN with support for Tensorflow and TensorflowLite.

**Comment by gangooteli** [comment]
Go to test folder, there is a code written for ssd mobilenet. Check the name of model which this code requires.

Then run the executable of SSD Mobilenet for TF parser in build/tests folder along with model path location and image as an arguments.

**Comment by 4rmature** [comment]
Oh okay thank you so much
