### ISSUE TITLE
Unit test failing in depthwise convolution

### ISSUE THREAD

**Issue by teamaltumview** [ARM-software/armnn#317]
When I ran the ARM NN unit test I got the following error.

Running 2290 test cases...
<source>:3005:54: warning: expression result unused
    DOT_PRODUCT_REDUCTION_WEIGHTS(acc0.s1, (uchar8)((w0.s9ABC), (w0.sDEF), w1.s0), w1.s1);
                                                     ^~~~~~~~
<source>:2424:17: note: expanded from here
        ARM_DOT(w0.s0123, (uchar4)1, sum);         \
                ^~
<source>:1793:47: note: expanded from here
#define ARM_DOT(x, y, val) val = arm_dot_acc((x), (y), val);
                                              ^

<source>:3005:66: warning: expression result unused
    DOT_PRODUCT_REDUCTION_WEIGHTS(acc0.s1, (uchar8)((w0.s9ABC), (w0.sDEF), w1.s0), w1.s1);
                                                                 ^~~~~~~
<source>:2424:17: note: expanded from here
        ARM_DOT(w0.s0123, (uchar4)1, sum);         \
                ^~
<source>:1793:47: note: expanded from here
#define ARM_DOT(x, y, val) val = arm_dot_acc((x), (y), val);
                                              ^

<source>:3005:5: error: member reference base type 'uchar' (aka 'unsigned char') is not a structure or union
    DOT_PRODUCT_REDUCTION_WEIGHTS(acc0.s1, (uchar8)((w0.s9ABC), (w0.sDEF), w1.s0), w1.s1);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:2424:19: note: expanded from here
        ARM_DOT(w0.s0123, (uchar4)1, sum);         \
                ~~^~~~~~
<source>:1793:47: note: expanded from here
#define ARM_DOT(x, y, val) val = arm_dot_acc((x), (y), val);
                                              ^

<source>:3005:54: warning: expression result unused
    DOT_PRODUCT_REDUCTION_WEIGHTS(acc0.s1, (uchar8)((w0.s9ABC), (w0.sDEF), w1.s0), w1.s1);
                                                     ^~~~~~~~
<source>:2425:17: note: expanded from here
        ARM_DOT(w0.s4567, (uchar4)1, sum);         \
                ^~
<source>:1793:47: note: expanded from here
#define ARM_DOT(x, y, val) val = arm_dot_acc((x), (y), val);
                                              ^

<source>:3005:66: warning: expression result unused
    DOT_PRODUCT_REDUCTION_WEIGHTS(acc0.s1, (uchar8)((w0.s9ABC), (w0.sDEF), w1.s0), w1.s1);
                                                                 ^~~~~~~
<source>:2425:17: note: expanded from here
        ARM_DOT(w0.s4567, (uchar4)1, sum);         \
                ^~
<source>:1793:47: note: expanded from here
#define ARM_DOT(x, y, val) val = arm_dot_acc((x), (y), val);
                                              ^

<source>:3005:5: error: member reference base type 'uchar' (aka 'unsigned char') is not a structure or union
    DOT_PRODUCT_REDUCTION_WEIGHTS(acc0.s1, (uchar8)((w0.s9ABC), (w0.sDEF), w1.s0), w1.s1);

I dug around a little bit and found that this error was thrown when opencl tries to compile depthwise_convolution_quantized.cl in ARM compute library.
My ARM compute library is on the master branch at commit 975dfe175e3d7c62c27598b1c0e8e77ed90df463
Is this an expected issue?

Just out of curiosity, what is the syntax for the arguement "(uchar8)((w0.s9ABC), (w0.sDEF)" in the following line
DOT_PRODUCT_REDUCTION_WEIGHTS(acc0.s1, (uchar8)((w0.s9ABC), (w0.sDEF), w1.s0), w1.s1);

**Comment by FrancisMurtagh-arm** [comment]
Hi teamaltumview,

The Compute library commit we are using is 94e0cf960ea6116eb57fa88d9b951f859b52c602.

If you run armnn/scripts/get_compute_library.sh it will pull the correct version.

Could you see if the issue persists with that version?

Thanks,
Francis.

**Comment by james-conroy-arm** [comment]
Hi @teamaltumview ,

Using @FrancisMurtagh-arm advice above, I think your issue is now resolved.

Please let us know if we can close this issue.

Cheers,
James

**Comment by james-conroy-arm** [comment]
Hi @teamaltumview ,

Since we have not heard back from you in a while and the issue appears to be resolved now, we are going to close this issue.

Please let us know if this is being closed in error, or feel free to open a new issue if another one should arise.

Cheers,
James

**Comment by teamaltumview** [comment]
Hi:
Thanks for contacting me. Please close this ticket.
Thanks
________________________________
