### ISSUE TITLE
How to use Batch processing

### ISSUE THREAD

**Issue by gangooteli** [ARM-software/armnn#318]
Below snippet in the ML-examples/armnn-mobilenet-quant/mobilenetv1_quant_tflite.cpp code is used to load and preprocess the input.

    // Load and preprocess input image
    const std::vector<TContainer> inputDataContainers =
    { PrepareImageTensor<uint8_t>(programOptions.imagePath,
            inputTensorWidth, inputTensorHeight,
            normParams,
            inputTensorBatchSize,
            inputTensorDataLayout) };

programOptions.imagePath takes a path of single image.

There is an option of batch processing using argument "inputTensorBatchSize" in the "PrepareImageTensor".

I am able to run it successfully for single image.

How to utilise this above code for batch processing with multiple images. Please help.

Thanks in advance.

**Comment by MatthewARM** [comment]
You need to use Tensorflow or Tensorflow Lite to set the batch size expected by the model. I afraid I don't know how to do that. The input tensor to armnn is then made from all the input tensors of all the input images concatenated together. 

PrepareImageTensor is a helper function that's used in some tests, it's not really part of the armnn api. I don't think it can handle batch processing properly.
