### ISSUE TITLE
Unable to quantize networks having AdditionLayer

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/armnn#321]
Hi,

I was able to create and run resnet50 FP32  using ARMNN APIs. 
But when I tried to quantize the same I was seeing issues where the additionlayer was unable to get the parent layer(ReLU) connection .  This parent layer is also input to one more layer which could be the case.

To isolate the serialization and network issues. I have created 4 layered network in the ArmNNQuantizerMain.cpp and passed it for quantization as shown below

    auto network = createNetwork();
    armnn::INetworkQuantizerPtr quantizer = armnn::INetworkQuantizer::Create(network.get(), quantizerOptions);

The network I have used is as shown below 
```
INetworkPtr createNetwork()
{
    //armnn::NetworkId networkIdentifier;
    INetworkPtr myNetwork = INetwork::Create();

    std::vector<float> constantData;
    constantData.resize(3*224*224);


    IConnectableLayer *InputLayer =  myNetwork->AddInputLayer(0,"InputLayer");
    armnn::ActivationDescriptor ReLUDesc;
    ReLUDesc.m_Function = ActivationFunction::ReLu;

    IConnectableLayer *ReLULayer1 = myNetwork->AddActivationLayer(ReLUDesc, "ReLU1");
    IConnectableLayer *ReLULayer2 = myNetwork->AddActivationLayer(ReLUDesc, "ReLU2");
    IConnectableLayer *ReLULayer3 = myNetwork->AddActivationLayer(ReLUDesc, "ReLU3");
    IConnectableLayer *addLayer1 = myNetwork->AddAdditionLayer("addLayer1");
    IConnectableLayer *OutputLayer = myNetwork->AddOutputLayer(0,"OutPutLayer");
    
    InputLayer->GetOutputSlot(0).Connect(ReLULayer1->GetInputSlot(0));
    ReLULayer1->GetOutputSlot(0).Connect(ReLULayer2->GetInputSlot(0));
    ReLULayer2->GetOutputSlot(0).Connect(ReLULayer3->GetInputSlot(0));
    ReLULayer2->GetOutputSlot(0).Connect(addLayer1->GetInputSlot(0));
    ReLULayer3->GetOutputSlot(0).Connect(addLayer1->GetInputSlot(1));
    addLayer1->GetOutputSlot(0).Connect(OutputLayer->GetInputSlot(0));

    InputLayer->GetOutputSlot(0).SetTensorInfo(TensorInfo(TensorShape({1, 3, 224, 224}), DataType::Float32));
    ReLULayer1->GetOutputSlot(0).SetTensorInfo(TensorInfo(TensorShape({1, 3, 224, 224}), DataType::Float32));
    ReLULayer2->GetOutputSlot(0).SetTensorInfo(TensorInfo(TensorShape({1, 3, 224, 224}), DataType::Float32));
    ReLULayer3->GetOutputSlot(0).SetTensorInfo(TensorInfo(TensorShape({1, 3, 224, 224}), DataType::Float32));
    addLayer1->GetOutputSlot(0).SetTensorInfo(TensorInfo(TensorShape({1, 3, 224, 224}), DataType::Float32));
    
    return myNetwork;
}
```
In the above network add layer receives input from ReLU2, ReLU3. 
Could you let me know how to resolve the issue. Do I need to insert a pass through layer after ReLULayer2?

Also I have attached the ArmNNQuantizerMain.cpp file for your reference.
[Quantizer.zip](https://github.com/ARM-software/armnn/files/4019119/Quantizer.zip)
Thank you,
Praveen.

**Comment by uu-praveeng** [comment]
Hi Team,

I have debugged further into this issue. It appears to be an issue while removing the DebugLayers and establishing reconnection of original network in function **DynamicQuantizationVisitor::RemoveDebugLayers()** .

After clearing all the debug layers, ReLU2 which ought to have 2 output connections has only 1 connection to ReLU3 and is no longer connected to succeeding Addition Layer. This is causing the assert at addition layer  while creating new quantized network using original network. Snippet where the code crashes as shown.

```
    const OutputSlot* outputSlot = inputSlot->GetConnectedOutputSlot();
    BOOST_ASSERT(outputSlot);
```

Let me know if there would be a fix for this in near future.

Thank you,
Praveen.

**Comment by MatthewARM** [comment]
Hi @uu-praveeng sorry you're hitting a bug - I'll see if I can get someone to look into it.

**Comment by uu-praveeng** [comment]
Ok @MikeJKelly . Let me know if you need any inputs from me. 

Thank you,
Praveen

**Comment by MikeJKelly** [comment]
Hi Praveen,

This issue should be resolved by:

https://review.mlplatform.org/c/ml/armnn/+/2607

Can you take a look and confirm, please? 

Thanks,
Mike

**Comment by uu-praveeng** [comment]
Hi @MikeJKelly ,

Issue is  resolved with this patch for this query and for related query https://github.com/ARM-software/armnn/issues/328 .
In which release this patch will be included?

Thank you,
Praveen.

**Comment by MikeJKelly** [comment]
That's great news, the fix is currently on the Linaro master and it will be in the next official release 20.02. That will come in late February.

**Comment by MatthewARM** [comment]
Closing per Mike's comment.
