### ISSUE TITLE
Arm nn standalone code is working but while i will  same code with android apk not working

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#322]
Arm nn standalone code is working but while i will integrate same code with android apk not working one function is crashing.

I have built armnn with same instruction given on site which is using ndk 17b and clang++
and my android is using ndk 17c and g++

function which is crashing named  = CreateNetworkFromBinaryFile() which is in TfParser.cpp, ITfParser.hpp

**Comment by paragikjain** [comment]
@MatthewARM  Please help

**Comment by MatthewARM** [comment]
Does it say anything in logcat when it crashes?

**Comment by paragikjain** [comment]
armnn run time exception are not printing inside logcat

**Comment by MatthewARM** [comment]
If it's raising an exception up to your code, you'll have to catch it and handle it - it's not really up to Arm NN whether a runtime exception is fatal / recoverable / harmless, that's your application to decide

**Comment by arovir01** [comment]
If the exception is raised in `CreateNetworkFromBinaryFile()`, it is either a `FileNotFoundException` or a `ParseException`. The latter means that the `TfParser` is unable to parse your model, the former means that the model file cannot be found. If the same model has previously worked with the TfParser, than I would check if the path is correct and accessible.

**Comment by paragikjain** [comment]
@arovir01 yes i have checked path manually as well as by fopen so path is correct and same model file is working in standalone code. But with android integration it is not working. And by defualt i am not getting armnn exception log in android logcat so can you please suggest me how to do that
