### ISSUE TITLE
is it posiible to build armnn android with aarch64-linux-android-g++? 

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#323]
. As of now i am building with aarch64-linux-android-clang++ . is it posiible to build armnn android with aarch64-linux-android-g++ .

**Comment by MatthewARM** [comment]
I think I remember that the g++ version in Android is too old. Can you check what version it is and I'll let you know?

**Comment by paragikjain** [comment]
aarch64-linux-android-g++ **(GCC) 4.9.x 20150123**   this version

**Comment by MatthewARM** [comment]
Ah yes, that compiler doesn't have full support for C++14 which is needed to compile Arm NN. g++ 4.9 lacks full constexpr support according to this table: https://gcc.gnu.org/projects/cxx-status.html#cxx14 and I know that's used in a couple of places in Arm NN.
