### ISSUE TITLE
Armnn android error detection 

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#324]
I am running standalone code of armnn and any runtime error is there then it will show error for example "model file not found". But when i am link this code to android application it will not show any runtime error. 

So do you have idea how to enable that runtime error in android logs?
or is there any way to detect armnn runtime error with android application?

**Comment by MatthewARM** [comment]
Hi @paragikjain it should show up in 'logcat' unless something has gone wrong...

**Comment by paragikjain** [comment]
Hi @MatthewARM  Thanks
