### ISSUE TITLE
Getting Error while trying to run armnn code with android studio

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#325]
Hi i am adding armnn code in android studio and i have attached all required so files
1.libarmnn.so
2.libarmnnTfparser.so
3.libprotobuf.so
4.libc++_shared.so

here is my code:

`#include<jni.h>
#include <string>
#include "android/log.h"
#include <iostream>
#include <string>
#include <fstream>
#include <vector>
#include <typeinfo>
#include <memory>
#include <array>
#include <algorithm>
#include "armnn/ArmNN.hpp"
#include "armnn/Exceptions.hpp"
#include "armnn/Tensor.hpp"
#include "armnn/INetwork.hpp"
#include "armnnTfParser/ITfParser.hpp"

#undef   LOG_TAG
#define  LOG_TAG    "ARM:"

#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__)
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
using namespace std;

extern "C" JNIEXPORT jstring JNICALL
Java_com_example_paragj_androidarm_MainActivity_hello(JNIEnv *env, jobject /*this*/ )
{
        LOGD("run successfully");
     std::string` hello="Welcome to android---0000";

     LOGD("Hi i am here");
	// Import the Tf model. Note: use CreateNetworkFromTextFile for text files.
	armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();
	LOGD("parser CREATED, size %lu\n", sizeof(parser));

    **LOGD("Hi i am here1");**

        return env->NewStringUTF(hello.c_str());
}

// Helper function to make input tensors`

I am able to reach  till  LOGD("Hi i am here1"); line but armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create(); this line is reason of crash when i will comment it my code will work.

here i am adding my android logcat
`01-07 14:22:41.855  8244  8244 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xf570323a9c00 in tid 8244 (ragj.androidarm), pid 8244 (ragj.androidarm)
01-07 14:22:41.983  8265  8265 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-07 14:22:41.984  3024  3024 I /system/bin/tombstoned: received crash request for pid 8244
01-07 14:22:41.985  8265  8265 I crash_dump64: performing dump of process 8244 (target tid = 8244)
01-07 14:22:42.014  8265  8265 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-07 14:22:42.014  8265  8265 F DEBUG   : Build fingerprint: 'Android/mek_8q/mek_8q:9/2.3.0-ga-rc2/mayur.mb01031251:userdebug/dev-keys'
01-07 14:22:42.014  8265  8265 F DEBUG   : Revision: '0'
01-07 14:22:42.014  8265  8265 F DEBUG   : ABI: 'arm64'
01-07 14:22:42.014  8265  8265 F DEBUG   : pid: 8244, tid: 8244, name: ragj.androidarm  >>> com.example.paragj.androidarm <<<
01-07 14:22:42.014  8265  8265 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xf570323a9c00
01-07 14:22:42.014  8265  8265 F DEBUG   :     x0  0000f57008fc3964  x1  0000ffffebba31e8  x2  0000000000000000  x3  0000f570320d1f04
01-07 14:22:42.014  8265  8265 F DEBUG   :     x4  0000ffffebba31d0  x5  0000000012c84f91  x6  20656d6f636c6557  x7  6f72646e61206f74
01-07 14:22:42.014  8265  8265 F DEBUG   :     x8  0000f570323a9c00  x9  ea990a7ab60cba3f  x10 0000000000430000  x11 0000f57036dac074
01-07 14:22:42.014  8265  8265 F DEBUG   :     x12 696f72646e61206f  x13 303030302d2d2d64  x14 ffffffffffffffff  x15 0a1b130000000000
01-07 14:22:42.014  8265  8265 F DEBUG   :     x16 0000000000000007  x17 0000f57035921b70  x18 0000ffffebba261a  x19 0000000000000075
01-07 14:22:42.014  8265  8265 F DEBUG   :     x20 0000f570370595e0  x21 0000f57032214c00  x22 0000ffffebba35c0  x23 0000f5702df0be83
01-07 14:22:42.014  8265  8265 F DEBUG   :     x24 0000000000000004  x25 0000f570370595e0  x26 0000f57032214ca0  x27 0000000000000001
01-07 14:22:42.015  8265  8265 F DEBUG   :     x28 0000ffffebba32f0  x29 0000ffffebba32c0
01-07 14:22:42.015  8265  8265 F DEBUG   :     sp  0000ffffebba3290  lr  0000f57008790ebc  pc  0000f570323a9c00
01-07 14:22:42.625  8265  8265 F DEBUG   : 
01-07 14:22:42.625  8265  8265 F DEBUG   : backtrace:
01-07 14:22:42.625  8265  8265 F DEBUG   :     #00 pc 00000000001a9c00  [anon:libc_malloc:0000f57032200000]
01-07 14:22:42.626  8265  8265 F DEBUG   :     #01 pc 000000000000feb8  /data/app/com.example.paragj.androidarm-BI8TQJJq1h21_ZD7IRn-ZQ==/lib/arm64/libndktest.so (Java_com_example_paragj_androidarm_MainActivity_hello+196)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #02 pc 0000000000565be0  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #03 pc 000000000055cb88  /system/lib64/libart.so (art_quick_invoke_stub+584)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #04 pc 00000000000cf740  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #05 pc 0000000000282460  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #06 pc 000000000027c41c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+948)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #07 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #08 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #09 pc 000000000000b91e  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.example.paragj.androidarm-BI8TQJJq1h21_ZD7IRn-ZQ==/split_lib_slice_1_apk.apk (deleted) (com.example.paragj.androidarm.MainActivity.onCreate+74)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #10 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #11 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #12 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #13 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #14 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #15 pc 0000000000389542  /system/framework/boot-framework.vdex (android.app.Activity.performCreate+24)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #16 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #17 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #18 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #19 pc 000000000052f518  /system/lib64/libart.so (MterpInvokeVirtualQuick+584)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #20 pc 0000000000552f14  /system/lib64/libart.so (ExecuteMterpImpl+29972)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #21 pc 00000000004bbd28  /system/framework/boot-framework.vdex (android.app.Activity.performCreate+2)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #22 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.626  8265  8265 F DEBUG   :     #23 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #24 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #25 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #26 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #27 pc 00000000003a894c  /system/framework/boot-framework.vdex (android.app.Instrumentation.callActivityOnCreate+6)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #28 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #29 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #30 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #31 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #32 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #33 pc 0000000000380b92  /system/framework/boot-framework.vdex (android.app.ActivityThread.performLaunchActivity+736)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #34 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #35 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #36 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #37 pc 000000000052d808  /system/lib64/libart.so (MterpInvokeDirect+296)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #38 pc 000000000054f294  /system/lib64/libart.so (ExecuteMterpImpl+14484)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #39 pc 000000000038082a  /system/framework/boot-framework.vdex (android.app.ActivityThread.handleLaunchActivity+72)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #40 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #41 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #42 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #43 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #44 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #45 pc 00000000003c6a60  /system/framework/boot-framework.vdex (android.app.servertransaction.LaunchActivityItem.execute+114)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #46 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.627  8265  8265 F DEBUG   :     #47 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #48 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #49 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #50 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #51 pc 00000000003c76e4  /system/framework/boot-framework.vdex (android.app.servertransaction.TransactionExecutor.executeCallbacks+198)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #52 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #53 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #54 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #55 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #56 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #57 pc 00000000003c75f6  /system/framework/boot-framework.vdex (android.app.servertransaction.TransactionExecutor.execute+68)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #58 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #59 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #60 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #61 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #62 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #63 pc 0000000000380002  /system/framework/boot-framework.vdex (android.app.ActivityThread$H.handleMessage+78)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #64 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #65 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #66 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #67 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #68 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.628  8265  8265 F DEBUG   :     #69 pc 0000000000ae5bfa  /system/framework/boot-framework.vdex (android.os.Handler.dispatchMessage+42)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #70 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #71 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #72 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #73 pc 000000000052c4c8  /system/lib64/libart.so (MterpInvokeVirtual+584)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #74 pc 000000000054f194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #75 pc 0000000000aecce8  /system/framework/boot-framework.vdex (android.os.Looper.loop+404)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #76 pc 0000000000255f18  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2088410233+496)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #77 pc 000000000025ba98  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #78 pc 000000000027c400  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
01-07 14:22:42.629  8265  8265 F DEBUG   :     #79 pc 000000000052d9cc  /system/lib64/libart.so (MterpInvokeStatic+204)`

**Comment by MatthewARM** [comment]
There's no mention of armnn in the crash log... I don't know what could be going wrong here

**Comment by paragikjain** [comment]
hi This isuue has been resolved thanks for help.
Actually armnnutils.a i forgot to attach with my android apkbut now it is working
