### ISSUE TITLE
TfInceptionV3-Armnn returns warnings

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#327]
`TfInceptionV3-Armnn` returns the following warning 94 times:
```
WARNING: Layer of type Rsqrt is not supported on requested backend CpuAcc for data type Float32 (reason: IsRsqrtSupported is not implemented [/home/abuild/rpmbuild/BUILD/armnn-19.08/src/backends/backendsCommon/LayerSupportBase.cpp:400]), falling back to the next backend.
```

Is it expected?

IIUC, this means this is not part of `CpuAcc` and thus, the slow `CpuRef` backend implementation will be used?

**Comment by arovir01** [comment]
> this means this is not part of CpuAcc and thus, the slow CpuRef backend implementation will be used

Yes, it means precisely that.

**Comment by MatthewARM** [comment]
@ggardet the rsqrt nodes get removed from the graph if you use Tensorflow to "optimise for inference". Specifically you need to apply the fold_constants and fold_batch_norms optimizations:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#fold_batch_norms

**Comment by james-conroy-arm** [comment]
Hi @ggardet ,

Did you try Matthew's suggestion above for applying the fold_constants and fold_batch_norms optimizations?

Cheers,
James

**Comment by ggardet** [comment]
No, I did not. 
My question was more:  would it be useful to add `Rsqrt` support to `CpuAcc` backend.

**Comment by james-conroy-arm** [comment]
Hi @ggardet ,

We added NEON (CpuAcc) workload support for Rsqrt in 19.11. Have you checked if this warning occurs since that release of ArmNN?

Cheers,
James

**Comment by ggardet** [comment]
Indeed, with latest release, I cannot reproduce.
