### ISSUE TITLE
File to add OpenCL lib

### ISSUE THREAD

**Issue by phamyphen** [ARM-software/armnn#33]
Could anyone know how to solve below issues?

/usr/local/lib/libOpenCL.so: error adding symbols: File in wrong format
clang60++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by MatthewARM** [comment]
Hi @phamyphen some people have reported that issue before, we don't have a good fix for it yet but there is a workaround, I'll dig it out...

**Comment by MatthewARM** [comment]
@phamyphen please try removing line 271 of cmake/GlobalConfig.cmake, which should say:
`    find_library(OPENCL_LIBRARIES OpenCL)`

Then delete your build directory and re-run cmake.

This will stop it from ever finding the host system OpenCL library.

**Comment by phamyphen** [comment]
Thanks MatthewARM. 
The problem is solved based on your solution.
