### ISSUE TITLE
Missing items on installation

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#330]
While building and installing Arm NN, I have the following items which are not installed from cmake build system:
* `ArmnnConverter`
* `ArmnnQuantizer`
* `libarmnnQuantizer.so`*

I think this should be installed.

**Comment by ggardet** [comment]
And `libarmnnQuantizer.so` is not versioned.

**Comment by MatthewARM** [comment]
Hmm, do you actually need those things for something? Or know of someone who does? I'm inclined to say that those things are so immature as to only be useful to developers of Arm NN.

**Comment by ggardet** [comment]
> Hmm, do you actually need those things for something? Or know of someone who does? I'm inclined to say that those things are so immature as to only be useful to developers of Arm NN.

I wanted to make it available in distro package as ArmNN tools. It is not useful on real life use cases?

**Comment by MohiniMohiniMohini** [comment]
Hi @ggardet @MatthewARM ,

Any update on this? How do i create the ArmnnConverter and ArmnnQuantizer?

**Comment by ggardet** [comment]
> How do i create the ArmnnConverter and ArmnnQuantizer?

They are built automatically when building ArmNN.

**Comment by MohiniMohiniMohini** [comment]
Hi @ggardet,

Yes, those are built with ArmNN I could not locate those earlier inside the docker. Thanks for the reply anyway.

**Comment by FrancisMurtagh-arm** [comment]
Hi @ggardet,

The ArmnnQuantizer and libarmnnQuantizer.so have since been deprecated and removed; however I've added a patch to install ArmnnConverter here:

https://review.mlplatform.org/c/ml/armnn/+/5639

Regards,
Francis.

**Comment by FrancisMurtagh-arm** [comment]
Going to close as the patch has been merged, please reopen if you have any issues.

Thanks,
Francis.
