### ISSUE TITLE
segmentaion fault

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#332]
I am getting **segmentation fault** during run time
 Program is crashing **runtime->LoadNetwork(networkIdentifier, std::move(optNet));**  on this line

**Comment by MatthewARM** [comment]
Probably optNet is a NULL pointer, due to failure of Optimise(). You need to check that Optimise() succeeded before calling LoadNetwork.

**Comment by paragikjain** [comment]
<pre>armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::**CpuAcc**}, runtime-&gt;GetDeviceSpec());
</pre>

<pre>armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::**CpuRef**}, runtime-&gt;GetDeviceSpec());
</pre>

In OptNet in Optimize function if i will pass **CpuRef** in place of **CpuAcc**  then it will work fine I will not get any segmentation error. But it will not optimize my network one inference is taking too much time

so Could you please tell me what is the difference between  **CpuRef**  and **CpuAcc**  flags and why i am getting segmentation error with cpuAcc and what I have to do for Optimize my network 


**I am using armnn android**

Thanks in advance.

**Comment by MatthewARM** [comment]
CpuAcc uses the Compute Library Neon operators.
CpuRef uses simple non-optimised operators built in to ArmNN - they are often quite slow, and are for testing and reference only.

I suggest you turn on verbose logging (see armnn/Utils.hpp) and check what error message is being reported - probably you are doing something that the Compute Library does not support.

It can often be best to enable CpuAcc *and* CpuRef, That way you will get accelerated optimised implementations via Compute Library, with fallback to the reference operator when necesary. You do this by passing both backends to 'Optimize', separated by commas: ` {armnn::Compute::CpuAcc, armnn::Compute::CpuRef}`

**Comment by paragikjain** [comment]
okay thanks @MatthewARM  during the time of building armnn and compute library I kept  neon=0 opencl=0  that is the reason of getting error while i will using CpuAcc . so for support of CpuAcc both of flag need to  be 1 or just neon is enough.
