### ISSUE TITLE
how to add backend folder inside android studio armnn android

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#334]
Hi i am pushing src/backed/test folder inside android in the case of binary execution.
But during building of apk for acceleration we need backed support so normally  all .so files like (libarmnn.so, libtenserflow.so .........)I am copying my lib folder of apk but this backed support folder needs to be copy fully or just so files inside that folder i can copy to my project.

without cpu acceleration i am able to run my android app using (libarmnn.so, libarmnnTfParser.so, libc++_shared.so,libprotobuf.so,armnnutils.a) files but the with same libaray i am not able to turn on cpu acceleration on run time iot will crash.

**Comment by MatthewARM** [comment]
Hi @paragikjain you should be able to just copy the .so files.
I'm not fully famililar with how permissions of .so files work when loaded from within an .apk. Do you know any documentation I can refer to, to help figure out what might be going wrong?

**Comment by paragikjain** [comment]
Hy thanks for help I forgot to push libarmnnutils.a so I was getting runtime error now I added it so it is working thanks. I am closing the issue.

**Comment by mathpopo** [comment]
@paragikjain  which libc++_shared.so you select?i complie ,meet a question:
[100%] Linking CXX executable UnitTests
/home/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc++_shared.so, needed by /home/chenxin/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so, not found (try using -rpath or -rpath-link)
[100%] Built target UnitTests
/usr/local/bin/cmake -E cmake_progress_start /home/chenxin/armnn-devenv/armnn/build/CMakeFiles 0
