### ISSUE TITLE
Invalid Backend ID GpuAcc

### ISSUE THREAD

**Issue by gangooteli** [ARM-software/armnn#336]
I am getting following error while using armnn and TfLiteParser.

> ArmNN v20191100
> 
> Armnn Error: Some backend IDs are invalid: GpuAcc
> 

Is GpuAcc as a backend is not supported. Please tell me how we can resolve this.
Thanks for help in advance.

**Comment by MikeJKelly** [comment]
Hi,

for GpuAcc to be supported you need to have an Arm Mali GPU on your device. How did you build ArmNN? Did you follow a guide?

You may have a line something similar to this in your code:

`armnn::IOptimizedNetworkPtr optimizedNet = Optimize(*network, {Compute::GpuAcc}, run->GetDeviceSpec());
`

If you do not have a Mali Gpu you will need to change the GpuAcc to CpuAcc if you're running on a device with an Arm CPU. If you're not running it on an Arm device then you should change it to CpuRef to run it on the reference backend.

**Comment by james-conroy-arm** [comment]
Hi @gangooteli ,

Did @MikeJKelly 's response above resolve your issue?

Cheers,
James

**Comment by james-conroy-arm** [comment]
Hi @gangooteli ,

Since we have not heard back from you in a while and the issue appears to be resolved now, we are going to close this issue.

Please let us know if this is being closed in error, or feel free to open a new issue if another one should arise.

Cheers,
James
