### ISSUE TITLE
DetectionPostProcess not supported for TfLite MobilenetSsd CpuAcc 

### ISSUE THREAD

**Issue by gangooteli** [ARM-software/armnn#337]
I am getting following error while using backend as CpuAcc. 

> ArmNN v20191100
> 
> WARNING: Layer of type DetectionPostProcess is not supported on requested backend CpuAcc for input data type QAsymm8 and output data type Float32 (reason: IsDetectionPostProcessSupported is not implemented [/home/nvidia/armnn-tflite/armnn/src/backends/backendsCommon/LayerSupportBase.cpp:171]), falling back to the next backend.
> ERROR: Layer of type DetectionPostProcess is not supported on any preferred backend [CpuAcc ]
> 

When I am running same model with backend as 

> CpuRef

, I am able to run it but it is taking 30 sec to perform detection in a image.

In release doc of 19.11 https://github.com/ARM-software/armnn/releases/tag/v19.11, DetectionPostProcess has already mentioned for TfliteParser.

Please help me regarding this issue. 
Thanks in advance.
[mobilenetssd_coco.zip](https://github.com/ARM-software/armnn/files/4075619/mobilenetssd_coco.zip)

**Comment by MatthewARM** [comment]
Hi @gangooteli you should enable CpuAcc *and* CpuRef, with CpuAcc first. Then all of the neural network layers will run on Neon and only the post process will run on reference. In my testing the postprocess layer takes about 5ms on CpuRef, so having only that layer on the reference backend shouldn't be too bad.

**Comment by MatthewARM** [comment]
@gangooteli Hope that helped, please reopen if it still doesn't work.
