### ISSUE TITLE
How to run armnn quantized model?

### ISSUE THREAD

**Issue by hossein1387** [ARM-software/armnn#338]
I have built and installed armnn, and it's TFlite and TF parser. I have also built Armnn quantizer and I successfully quantized a simple TFlite model with it. The output of the quantizer is a armnn file. Now I wonder how can I run my model? I am not able to find any function that could parse the armnn model (for instance, for tflite model, I used armnnTfLiteParser class to create a parser and load the model). Is there any sample code for this?

**Comment by MikeJKelly** [comment]
Hi 

you can load the .armnn file using IDeserializer.CreateNetworkFromBinary(...) this behaves the same way as the method in the ITfLiteParser. 

You can see some sample code for this in the Serialization tests (look at ActivationSerializationTests.cpp for a good example). 

Best regards,
Mike

**Comment by MatthewARM** [comment]
@hossein1387 hope you're all sorted, feel free to reopen the ticket if you still need help.

**Comment by korabelnikov** [comment]
Hi, thank you for a help.
I've changed to IDeserializer and got trouble with BindingPointInfo method cause it now need 'layerId' as parameter. Where I should find layer id?

method's signature is
```
    /// Retrieve binding info (layer id and tensor info) for the network input identified by
    /// the given layer name and layers id
    virtual BindingPointInfo GetNetworkInputBindingInfo(unsigned int layerId,
                                                        const std::string& name) const = 0;
```
