### ISSUE TITLE
Running two models on the GpuAcc

### ISSUE THREAD

**Issue by barak12344** [ARM-software/armnn#340]
Hi, I'm trying to run 2 networks on the same thread, but whenever I add the second network I get this error: Error in clEnqueueMapBuffer

I guess it is something that connected to the gpu, but I can't figure out what.

**Comment by nikraj01** [comment]
Hi @barak12344 , Could you please explain it a bit more like what version of ArmNN are you using , what are the models that you are trying to run etc.

Thanks

**Comment by barak12344** [comment]
Hi. I have solved it.
The problem was that I had used a different IRuntimePtr for each, instead of one that handles both of them.
Once I have changed it to one it worked.

**Comment by MatthewARM** [comment]
Thanks, good to know.
