### ISSUE TITLE
LTO build makes UnitTests to fail on: Assertion `counterValuePtr' failed.

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#341]
With ArmNN 19.11, with LTO enabled, the build makes `UnitTests` to fail:
```
[  960s] + LD_LIBRARY_PATH=/home/abuild/rpmbuild/BUILD/armnn-19.11/build/
[  960s] + ./build/UnitTests
[ 1014s] UnitTests: /home/abuild/rpmbuild/BUILD/armnn-19.11/src/profiling/ProfilingService.cpp:232: virtual uint32_t armnn::profiling::ProfilingService::IncrementCounterValue(uint16_t): Assertion `counterValuePtr' failed.
[ 1014s] Running 2776 test cases...
[ 1014s] unknown location(0): fatal error: in "FileOnlyProfilingDecoratorTests/DumpOutgoingValidFileEndToEnd": signal: SIGABRT (application abort requested)
[ 1014s] /home/abuild/rpmbuild/BUILD/armnn-19.11/src/profiling/test/FileOnlyProfilingDecoratorTests.cpp(81): last checkpoint
[ 1019s] 
[ 1019s] *** 1 failure is detected in the test module "UnitTests"
```

**Comment by nikraj01** [comment]
Hi @ggardet , Could you please try to run the unittests by turning off that particular test and let us know how it goes?
Thanks

**Comment by ggardet** [comment]
@nikraj01 How could I do that easily?

**Comment by MatthewARM** [comment]
@ggardet I'm not at my desk right now, but I think it's:

UnitTests -t \!FileOnlyProfilingDecoratorTests/DumpOutgoingValidFileEndToEnd

That would run all tests except that one case. Should help see if anything else is going wrong that could help narrow down the problem.

**Comment by ggardet** [comment]
The UnitTests are successful if I disable this test with `-t !FileOnlyProfilingDecoratorTests/DumpOutgoingValidFileEndToEnd`

**Comment by james-conroy-arm** [comment]
Hi @ggardet ,

This test (failing intermittently) was disabled and will not fail in the 20.05 release of ArmNN.

We have a fix for this test in review now: https://review.mlplatform.org/c/ml/armnn/+/3455

We will update you again when the fix is merged into master.

Cheers,
James

**Comment by ggardet** [comment]
Thanks for the update @james-conroy-arm

**Comment by james-conroy-arm** [comment]
Hi @ggardet ,

The fix has now been merged. I am going to close this issue but feel free to comment here if you see this issue occurring again.

Cheers,
James
