### ISSUE TITLE
ARMNN Performance VS OnnxRuntime

### ISSUE THREAD

**Issue by hossein1387** [ARM-software/armnn#342]
I am trying to use ARMNN with a quantized network. I am specifically using the tensorflow lite parser in ARMNN. My target device is NVIDIA Jetson 2 (TX2) board that has 6 ARMv8 rev 3 core with the following extensions: **fp asimd evtstrm aes pmull sha1 sha2 crc32**
For my model I am using the quantized version of VWW model downloaded from this link: https://github.com/mit-han-lab/VWW

I ran this model with ARMMNN and onnxruntime-cpu  to compare performance. Currently onnxruntime reaches 16fps while my code with armnn achieves less than 1 fps! I am not sure what I am missing here. Here is the code that I am working with:

```
int main(int argc, char** argv)
{

	// Import the TensorFlow model. Note: use CreateNetworkFromBinaryFile for .pb files.
	armnnTfLiteParser::ITfLiteParserPtr parser = armnnTfLiteParser::ITfLiteParser::Create();
	armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("/home/askari/repo/armnn-vww/model/model_quantized.tflite");
	// Find the binding points for the input and output nodes
	armnnTfLiteParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo(0, "input");
	armnnTfLiteParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo(0, "Softmax");

	// Optimize the network for a specific runtime compute device, e.g. CpuAcc, GpuAcc
	armnn::IRuntime::CreationOptions options;
	armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);
	armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuRef}, runtime->GetDeviceSpec());

	// Load the optimized network onto the runtime device
	armnn::NetworkId networkIdentifier;
	runtime->LoadNetwork(networkIdentifier, std::move(optNet));


	// Run a single inference on the test image
	std::array<float, 1> output;

    VideoCapture cap;
    // open the default camera, use something different from 0 otherwise;
    // Check VideoCapture documentation.
    if(!cap.open(1))
        return 0;

	auto start = std::chrono::high_resolution_clock::now();
	auto finish = std::chrono::high_resolution_clock::now();
	double fps = 0;
    for(;;)
    {
    	start = std::chrono::high_resolution_clock::now();
        Mat frame;
        cap >> frame;
        if( frame.empty() ) break; // end of video stream
      	armnn::Status ret = runtime->EnqueueWorkload(networkIdentifier,
      	                                           MakeInputTensors(inputBindingInfo, frame.data),
      	                                           MakeOutputTensors(outputBindingInfo, &output[0]));
      	imshow("vww model", frame);
        if( waitKey(10) == 27 ) break; // stop capturing by pressing ESC
        finish = std::chrono::high_resolution_clock::now();
        fps = (1.0 / duration_cast<microseconds>(finish - start).count()) * 1000000;
        fprintf(stderr, "return val is: %f      fps=%2.2f\n", output[1], fps);
    }
    // the camera will be closed automatically upon exit
    // cap.close();
    return 0;
}
```

I am not sure the way I am using runtime works for stream data. Am I missing anything?

**Comment by MikeJKelly** [comment]
Hi,

you're using the reference (CpuRef) implementation rather than the Cpu accelerator (CpuAcc). 

If you change: 
`armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuRef}, runtime->GetDeviceSpec());`

to:
`armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuAcc}, runtime->GetDeviceSpec());`

You should see much better performance. 

I hope that helps,
Mike

**Comment by hossein1387** [comment]
Thanks, but just changing CpuRef to CpuAcc gave me a segfault! any idea?

**Comment by arovir01** [comment]
Have you compiled Arm NN with CpuAcc support?

**Comment by MikeJKelly** [comment]
Hi,

You need to compile Arm NN with CpuAcc support you can see a guide here that might be helpful in building it:

https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx

**Comment by hossein1387** [comment]
I compiled tArmNN with neon support and I am getting 16fps! quite a difference! thanks a lot!
