### ISSUE TITLE
Feature request: Support for Embed layer

### ISSUE THREAD

**Issue by matthill** [ARM-software/armnn#346]
This layer is missing and prevents us from running one of our models: https://caffe.berkeleyvision.org/tutorial/layers/embed.html

**Comment by FrancisMurtagh-arm** [comment]
Hi Matthill,

I've labelled it as a feature request however; we are open to contributions if this is something that would interest you?

If you have a look here:
https://mlplatform.org/contributing/

Our gerrit server: https://review.mlplatform.org/#/dashboard/self

The first thing to do is to get it working with the latest master branch of Arm NN.

Next make sure you can log in to gerrit at https://review.mlplatform.org/#/dashboard/self using your Github account. Add your ssh key under "settings -> SSH public keys".

Then submit it to a gerrit review with a command like this, replacing <github username> with your Github username:
git push ssh://<github username>@review.mlplatform.org:29418/ml/armnn HEAD:refs/for/master

Thanks,
Francis.

**Comment by james-conroy-arm** [comment]
Hi @matthill ,

Did you manage to work around this issue in some way?

Cheers,
James

**Comment by matthewsloyanARM** [comment]
Hi @matthill,

It seems like you are running a Caffe model based on the link you have supplied. Unfortunately with the upcoming Arm NN release (21.05) we will be deprecating the Arm NN Caffe Parser, so we won't be add support for this operator. Based on this I will close this Issue and remove the "Help wanted" label. However, if this is incorrect feel free to reopen the ticket at anytime.

If you would like to help with the development of Arm NN feel free to take a look at the help wanted section [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). You can also find our contributors guide [here](https://www.mlplatform.org/contributing) which will show you how you can submit a patch to us. Thank you, all the best!

Kind regards, 

Matthew
