### ISSUE TITLE
NaN output when choose CpuAcc

### ISSUE THREAD

**Issue by sangdv** [ARM-software/armnn#348]
I run a Caffe model for age prediction.
CpuACC: armnn::Optimize(*network, {armnn::Compute::CpuAcc}, runtime->GetDeviceSpec());
However, when I choose mode, the output is NaN
Meanwhile the output for two other modes CpuRef and GpuAcc is fine.

**Comment by MikeJKelly** [comment]
Hi Sangdv,

can you share the model with us? What device are you running the model on?

**Comment by sangdv** [comment]
Hi, I am running on the Orange Pi 4

**Comment by MikeJKelly** [comment]
Can you give us the model or provide some more information on the structure of the model? Is it a quantized or fp16/32 model? Do you get any log or error information?

**Comment by sangdv** [comment]
Hi, I just tried a Age and Gender Classification downloaded from the Caffe model zoo: https://github.com/BVLC/caffe/wiki/Model-Zoo#models-for-age-and-gender-classification
or https://gist.github.com/GilLevi/c9e99062283c719c03de

**Comment by MikeJKelly** [comment]
I'm closing this as Caffe support has been removed.
