### ISSUE TITLE
Make Input tensor for single channel Image

### ISSUE THREAD

**Issue by akanxit** [ARM-software/armnn#349]
I am trying to run inference using a custom tflite model. So I followed the instructions mentioned at 
**https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/deploying-a-quantized-tensorflow-lite-mobilenet-v1-model-using-the-arm-nn-sdk/single-page**

My code looks roughly like:
// Set input Tensor
    	const unsigned int inputTensorWidth = 158;
    	const unsigned int inputTensorHeight = 158;
    	const unsigned int inputTensorBatchSize = 1;
        const armnn::DataLayout inputTensorDataLayout = armnn::DataLayout::NHWC;

//Create Container for input image
    
    	const std::vector<TContainer> inputDataContainers =
    	{ PrepareImageTensor<uint8_t>(img_path.c_str(),
      	inputTensorWidth, inputTensorHeight,
      	normParams,
      	inputTensorBatchSize,
      	inputTensorDataLayout) } ;

//Create tflite Parser
using IParser = armnnTfLiteParser::ITfLiteParser;
    	auto armnnparser(IParser::Create());
    	armnn::INetworkPtr network = armnnparser->CreateNetworkFromBinaryFile(model_path.c_str());

//get binding point Info
    	using BindingPointInfo = armnnTfLiteParser::BindingPointInfo;
    	const std::vector<BindingPointInfo> inputBindings = {armnnparser->GetNetworkInputBindingInfo(0, inputName)};
    	const std::vector<BindingPointInfo> outputBindings = {armnnparser->GetNetworkOutputBindingInfo(0, outputName)};

    	// Output tensor size is equal to the number of model output labels
       const std::vector<std::string> modelOutputLabels =
        {"0", "1"};
    	const unsigned int outputNumElements = modelOutputLabels.size();
    	std::vector<TContainer> outputDataContainers = { std::vector<uint8_t>(outputNumElements)};
   
    	// Optimize the network for a specific runtime compute
    	// device, e.g. CpuAcc, GpuAcc
    	armnn::IRuntime::CreationOptions options;
    	armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);
    	armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network,
    	{armnn::Compute::CpuAcc, armnn::Compute::CpuRef},
                                                         runtime->GetDeviceSpec());

    	// Load the optimized network onto the runtime device
    	armnn::NetworkId networkIdentifier;
    	runtime->LoadNetwork(networkIdentifier, std::move(optNet));

       // Run Inference
    	armnn::Status ret = runtime->EnqueueWorkload(networkIdentifier,
                    armnnUtils::MakeInputTensors(inputBindings, inputDataContainers),                                                 
		    armnnUtils::MakeOutputTensors(outputBindings, outputDataContainers));

It throws an error: 
terminate called after throwing an instance of 'armnn::Exception'
  what():  The input tensor has incorrect size (expected 24964 got 74892)
Aborted
It looks like the input tensor being created is being created for a 3 channel image although the input image is grayscale with size 158*158. How can I create a tensor for a single-channel image? 
@MatthewARM would really appreciate any help.

**Comment by MikeJKelly** [comment]
Hi akanxit,

From looking at the code that generates that exception the input tensor is the correct size (1x158x158x1 = 24964 bytes) but it seems that the image being loaded is a 3 channel image (1x158x158x3 = 74892 bytes). 

You will need to convert your image to a single channel image.
