### ISSUE TITLE
got "Segmentation fault" in CreateNetworkFromBinaryFile(model_path)

### ISSUE THREAD

**Issue by o0olele** [ARM-software/armnn#350]
ARMNN ver: 20.02
tflite_model: [here](https://github.com/o0olele/armnn_yolo/releases/download/0.0.0/yolov3-tiny.tflite)

when trying [InferenceModel.cpp](https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/tests/InferenceModel.hpp), 
```
static armnn::INetworkPtr Create(const Params& params,
                                     std::vector<armnn::BindingPointInfo>& inputBindings,
                                     std::vector<armnn::BindingPointInfo>& outputBindings)
    {
        const std::string& modelPath = params.m_ModelPath;

        // Create a network from a file on disk
        IParser::TfLiteParserOptions options;
        options.m_StandInLayerForUnsupported = params.m_ParseUnsupported;
        auto parser(IParser::Create(options));

        armnn::INetworkPtr network{nullptr, [](armnn::INetwork *){}};
        {
            ARMNN_SCOPED_HEAP_PROFILING("Parsing");
	    std::cout << "creating" << std::endl;
            network = parser->CreateNetworkFromBinaryFile(modelPath.c_str());
	    std::cout<< "created!" << std::endl;
        }
```

got
```
creating
Segmentation fault
```

need help!
Thanks!

**Comment by arovir01** [comment]
Does `params.m_ModelPath` point to the correct .tflite model file?

**Comment by o0olele** [comment]
@arovir01 yes, the path is correct

**Comment by o0olele** [comment]
@arovir01 and for a wrong path, it will show "can not find the file"

**Comment by james-conroy-arm** [comment]
Hi @o0olele ,

Are you still getting the segmentation fault?

Cheers,
James

**Comment by matthewsloyanARM** [comment]
Hi @o0olele,

I will close this issue due to inactivity. If you are still having this issue or have any questions feel free to reopen this ticket or create a new one anytime. Thanks again for reaching out!

Kind regards,

Matthew
