### ISSUE TITLE
GLIBC error: Cross-compiling ARMNN on x86_64 (Ubuntu18.04) for ARM Cortex A9(Debian 9)

### ISSUE THREAD

**Issue by Nukul13** [ARM-software/armnn#353]
I cross-compiled ARMNN for my ARM Cortex-A9 (Debian 9) device on my host system which is x86_64 (Ubuntu 18.04).

I have successfully compiled ARMNN and all it's dependencies without any errors, but when I try to run the sample mnist on Cortex-A9, it gives the following error:
```
duu@34d456-45433g:~/ML-examples/armnn-mnist$ make test
arm-linux-gnueabihf-g++ -O3 -std=c++14 -I/home/duu/armnn/armnn/include mnist_caffe.cpp -o mnist_caffe -L/home/duu/build -larmnn -larmnnCaffeParser
/home/admin/build/libarmnn.so: undefined reference to `exp2f@GLIBC_2.27'
/home/admin/build/libarmnn.so: undefined reference to `logf@GLIBC_2.27'
/home/admin/build/libarmnn.so: undefined reference to `log2f@GLIBC_2.27'
/home/admin/build/libarmnn.so: undefined reference to `powf@GLIBC_2.27'
/home/admin/build/libarmnn.so: undefined reference to `expf@GLIBC_2.27'
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'mnist_caffe' failed
make: *** [mnist_caffe] Error 1
```
I figured later that the device should have the same compiler and same GLIBC package, both with same versions as the host on which the library was compiled.

I compiled ARMNN using gcc-6.4.0 and glibc-2.27 on the host and I have gcc-6.3.0 and glibc-2.24 on Cortex-A9 device.

I managed to match the GCC versions and solve the compiler error but I am not able to find matching versions of GLIBC on Ubuntu 18.04 and debian 9.

Is there any way to resolve this issue?

**Comment by FrancisMurtagh-arm** [comment]
Hi Nukul,

Are you following our cross compile guide?
https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideCrossCompilation.md

Is it possible for you to upgrade your Cortex-A9 device to Debian 10? Debian 10 ships with glibc-2.28 which should fix your problem.

Regards,
Francis.

**Comment by Nukul13** [comment]
> Hi Nukul,
> 
> Are you following our cross compile guide?
> https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideCrossCompilation.md
> 
> Is it possible for you to upgrade your Cortex-A9 device to Debian 10? Debian 10 ships with glibc-2.28 which should fix your problem.
> 
> Regards,
> Francis.

Hi Francis,

Yes, I followed your cross compile guide with slight modification. The steps that are given, are for aarch64 and I have compiled for armv7a. 

Yes, upgrading the device to Debian 10 might solve the issue but it is not possible for me due to other dependencies. Isn't there any other solution for this?

**Comment by FrancisMurtagh-arm** [comment]
Hi Nukul,

This guide is actually for armv7a:
https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/cross-compiling-arm-nn-for-the-raspberry-pi-and-tensorflow/single-page

This could possibly be done in a debian 9 Virtual Machine which may get you the same glibc versions.

Otherwise you might have to manually upgrade your version of glibc or statically link it.

Regards,
Francis.

**Comment by MatthewARM** [comment]
Francis, I think your suggestion would work, however it might also be possible to copy libc-2.24.so from the target to the build host, and change the libc.so.6 symlink to point to that instead. Happy to go further into this Nukul if you think it's worth a try.

This conversation has made me realise that the cross-compilation guide depends on the same versions of debian / ubuntu being installed on both the build host and the target. We should update the documentation to mention that explicitly.

**Comment by Nukul13** [comment]
Hi @MatthewARM 

I tried your suggestion and copied the libc-2.24 from my target to build the library on my host. It works properly. I had to copy some other library dependencies also along with libc to make it work.

Hi @FrancisMurtagh-arm 

I went ahead and followed the link you provided, it also worked properly for me.
