### ISSUE TITLE
cmake warning

### ISSUE THREAD

**Issue by zanazakaryaie** [ARM-software/armnn#354]
Following [this guide](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite/build-arm-nn), I did:

`cmake .. -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build -DBOOST_ROOT=$BASEDIR/boost -DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf -DPROTOBUF_ROOT=$BASEDIR/protobuf-host -DBUILD_TF_LITE_PARSER=1 -DTF_LITE_GENERATED_PATH=$BASEDIR/tensorflow/tensorflow/lite/schema -DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers -DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers/libflatbuffers.a -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 -DSAMPLE_DYNAMIC_BACKEND=1 -DDYNAMIC_BACKEND_PATHS=~/armnn-tflite/armnn/src/dynamic/sample`

BUT, it produces this warning:

> CMake Warning:
>   Manually-specified variables were not used by the project:
>    PROTOBUF_ROOT
>    TF_GENERATED_SOURCES

Why does this happen?

**Comment by FrancisMurtagh-arm** [comment]
Hi zanazakaryaie,

This is a warning as you are setting paths for PROTOBUF_ROOT and TF_GENERATED_SOURCES which are not used if you only build the TfLiteParser (-DBUILD_TF_LITE_PARSER).

Regards,
Francis.

**Comment by zanazakaryaie** [comment]
Hi @FrancisMurtagh-arm 

So it's not a critical warning. I asked because when I run ./Unittest, an error occurs. I thought it might be due to those cmake warnings.
Thanks
