### ISSUE TITLE
How to build armnn/tests

### ISSUE THREAD

**Issue by zanazakaryaie** [ARM-software/armnn#360]
Hello
I'm on Raspberry Pi 3 B+ with Raspbian. I have built armnn successfully and now want to run MobilenetSSD with tflite using armnn. There is an example in armnn/tests folder for this application. There is also a CMakelist.txt. So, I did `mkdir build`, and then inside the build folder, run `cmake ..`
It gave me an error: `Unknown cmake command add_library_ex.` I changed it to `add_library` and the error resolved. But now, it gives me another error:

> ~/armnn-tflite/armnn/tests/InferenceTest.hpp:7:27: fatal error: armnn/ArmNN.hpp: No such file or directory
>  #include <armnn/ArmNN.hpp>

What should I do? Please help

**Comment by nikraj01** [comment]
Hi @zanazakaryaie ,

May I know what version of ArmNN are you building? We don't have ArmNN.hpp inside armnn.

Thanks,
Nikhil.

**Comment by MikeJKelly** [comment]
Hi @zanazakaryaie 

you will need to call make from armnn/build/cmake.. with -DBUILD_TESTS=1 in addition to the other flags specified in the guide:

https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite/build-arm-nn

**Comment by zanazakaryaie** [comment]
Hi @nikraj01 

I'm using the latest armnn release (20.02)

**Comment by zanazakaryaie** [comment]
Hi @MikeJKelly 

I didn't know that. Thanks for informing me. I'll test it right now

**Comment by zanazakaryaie** [comment]
@MikeJKelly 

I added -DBUILD_TESTS=1 to cmake an those binaries were generated after `make`. Thanks
