### ISSUE TITLE
None of the preferred backends [CpuRef ] are supported. Current  platform provides [CpuAcc ]

### ISSUE THREAD

**Issue by korabelnikov** [ARM-software/armnn#361]
armnn have been builded with opencl and neon, 
armnnref param is 'on' as well.
![image](https://user-images.githubusercontent.com/3808833/76421464-bf1f8b00-63b4-11ea-9ea6-566dfcceba39.png)

platform is armv7l, that supports neon

**Comment by FrancisMurtagh-arm** [comment]
Hi Korabelnikov,

Are you following one of our build guides?

How are you executing our code to get the mentioned error? 
Is it during the UnitTests or something else?

Regards,
Francis.

**Comment by korabelnikov** [comment]
Hi @FrancisMurtagh-arm 

It's SimpleSample from samples.

I've found out that it tries only 'ref' backend for some reason. I've changed source and make simple sample work

**Comment by Mo-Abdelgawad** [comment]
Hello, 
@korabelnikov I have encountered a problem somehow like that. Could you please let me know how you solved it? what change did you make to which source file?
Thanks.

**Comment by FrancisMurtagh-arm** [comment]
Hi @Mo-Abdelgawad,

Looking at the code it looks like the backend has been hardcoded to CpuRef:
armnn/samples/SimpleSample.cpp

Line 57:
armnn::IOptimizedNetworkPtr optNet = Optimize(*myNetwork, {Compute::CpuRef}, run->GetDeviceSpec());

You could change that to whichever backend you prefer.

Regards,
Francis.

**Comment by Mo-Abdelgawad** [comment]
Thank you @FrancisMurtagh-arm!

**Comment by AliSheheryar** [comment]
I am also facing this issue. I am using Pyarmnn to run fire detection model in a docker Ubuntu20.04 container.
