### ISSUE TITLE
ArmNN 19.08 and 19.11 are not CTS compliant. 

### ISSUE THREAD

**Issue by jimfly01** [ARM-software/armnn#365]
Both releases of ArmNN fail several tests in the Android 10 R2 CTS test suite when running against GpuAcc backend (Mali GPU) and CpuAcc (NEON)

**Comment by jimfly01** [comment]
New ArmNN patch release 19.08.01 and 19.11.01 run cleanly against the Android 10 R2 CTS test suite when running against GpuAcc backend (Mali GPU) and CpuAcc (NEON)

**Comment by JingSun3747** [comment]
I don't know how to run Android CTS upon ARMNN. Could you share the test method?

**Comment by MatthewARM** [comment]
Hi @JingSun3747 the main CTS instructions are here: https://source.android.com/compatibility/cts
 
The Arm NN HAL Driver for the Android Neural Networks API is here: https://github.com/ARM-software/android-nn-driver/

There is an integration guide in that repository for how to build Android to use the Arm NN driver for Neural Networks HAL acceleration.

All these instructions assume that you are phone developer - there is no supported way to 'add' Arm NN under the Neural Networks HAL to an existing phone. 

If you are an application developer simply use the Arm NN API directly in your application (or via the Tensorflow Lite delegate currently under development). In which case the Android CTS tests are not relevant.

Hope that helps,
Matthew

**Comment by JingSun3747** [comment]
Hi @MatthewARM 
Thank you for the reply. It helped me a lot!

Many thanks,
JingSun
