### ISSUE TITLE
build issue: fatal error: arm_neon.h: No such file or directory

### ISSUE THREAD

**Issue by MohiniMohiniMohini** [ARM-software/armnn#367]
armnn-devenv/ComputeLibrary/arm_compute/core/NEON/kernels/NEFFTRadixStageKernel.h:30:22: fatal error: arm_neon.h: No such file or directory
compilation terminated.

Command:
cd /home/admin1/ && git clone https://github.com/ARM-software/armnn.git && \
    cd armnn && mkdir build && cd build && \
    CXX=aarch64-linux-gnu-g++ && \
    CC=aarch64-linux-gnu-gcc && \
    cmake .. \
    -DARMCOMPUTE_ROOT=/home/admin1/armnn-devenv/ComputeLibrary \
    -DARMCOMPUTE_BUILD_DIR=/home/admin1/armnn-devenv/ComputeLibrary/build/ \
    -DBOOST_ROOT=/home/admin1/armnn-devenv/boost_arm64_install/ \
    -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 \
    -DCAFFE_GENERATED_SOURCES=/home/admin1/armnn-devenv/caffe/build/include \
    -DBUILD_CAFFE_PARSER=1 \
    -DPROTOBUF_ROOT=/home/admin1/armnn-devenv/google/x86_64_pb_install/ \
    -DPROTOBUF_LIBRARY_DEBUG=/home/admin1/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.15.0.1 \
    -DPROTOBUF_LIBRARY_RELEASE=/home/admin1/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.15.0.1 && \
    make -j32

**Comment by MikeJKelly** [comment]
Hi @MohiniMohiniMohini 

are you compiling on an arm based system? What system are you planning on using armnn on? 

If you're compiling on an x86 based system you can try the cross-compiling guide at https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideCrossCompilation.md 

Best regards,
Mike

**Comment by nullbyte91** [comment]
Hello @MikeJKelly,

We are trying to create a docker image for x86 target by following the steps given in the above link.

**Comment by MohiniMohiniMohini** [comment]
@MikeJKelly here is the dockerfile i'm using. 
[dockertxt.txt](https://github.com/ARM-software/armnn/files/4376623/dockertxt.txt)

**Comment by MikeJKelly** [comment]
Hi @MohiniMohiniMohini 

the arm_neon.h header should have been installed as part of the crossbuild-essential-arm64 package, can you confirm if it's there, it should be somewhere in /usr/lib/gcc-cross (your path may vary). 

If it is in there can you write a simple hello-world application that includes arm_neon.h to confirm that your environment is set up properly? 

Best regards,
Mike

**Comment by MohiniMohiniMohini** [comment]
Hi @MikeJKelly,
The file is present under
/usr/lib/gcc-cross/aarch64-linux-gnu/5/include/arm_neon.h

However it is not detected by NEFFTRadixStageKernel.h
I tried including the file in cmakelist as include_dirs() I get following error:

/usr/lib/gcc-cross/aarch64-linux-gnu/5/include/arm_neon.h:38:9: error: ‘__Int8x8_t’ does not name a type typedef __Int8x8_t int8x8_t;

The same error for rest of the data types. 
(tried re-installing and updating the cross-compiler) 
Let me know if there is anything I can try.

**Comment by nullbyte91** [comment]
@MikeJKelly The root cause for this issue is When we execute the below script to build armnn,
```bash
#!/bin/bash
CXX=aarch64-linux-gnu-g++ \
CC=aarch64-linux-gnu-gcc \
cmake .. \
-DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary \
-DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build/ \
-DBOOST_ROOT=$HOME/armnn-devenv/boost_arm64_install/ \
-DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 \
-DCAFFE_GENERATED_SOURCES=$HOME/armnn-devenv/caffe/build/src \
-DBUILD_CAFFE_PARSER=1 \
-DPROTOBUF_ROOT=$HOME/armnn-devenv/google/x86_64_pb_install/ \
-DPROTOBUF_LIBRARY_DEBUG=$HOME/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.15.0.1 \
-DPROTOBUF_LIBRARY_RELEASE=$HOME/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.15.0.1
```
The tool chains are not getting updated and the source code is compiling with default C, C++ tool chain. 
**Solution:**
```bash
#!/bin/bash
export CXX=aarch64-linux-gnu-g++ \
export CC=aarch64-linux-gnu-gcc \ 
....
```

**Comment by MikeJKelly** [comment]
Ah that makes sense, thanks for letting us know!
