### ISSUE TITLE
Linking CXX executable UnitTests

### ISSUE THREAD

**Issue by hashtagrk** [ARM-software/armnn#368]
`libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::io::EpsCopyOutputStream::WriteRawFallback(void const*, int, unsigned char*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::ComputeUnknownFieldsSize(google::protobuf::internal::InternalMetadataWithArena const&, unsigned long, google::protobuf::internal::CachedSize*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::GenericSwap(google::protobuf::MessageLite*, google::protobuf::MessageLite*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedField<float>::Add(float const&)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliasedOutline(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::PackedUInt64Parser(void*, char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::UnknownFieldParse(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::AddDescriptors(google::protobuf::internal::DescriptorTable const*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::VerifyUTF8(google::protobuf::StringPiece, char const*)'
libarmnnTfParser.so.20.02: undefined reference to `scc_info_Any_google_2fprotobuf_2fany_2eproto'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::Any::_InternalParse(char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::VarintParseSlow64(char const*, unsigned int)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get(int) const'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Add()'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::ReadTagFallback(char const*, unsigned int)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::ReadSizeFallback(char const*, unsigned int)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::EpsCopyInputStream::ReadStringFallback(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::WireFormat::InternalSerializeUnknownFieldsToArray(google::protobuf::UnknownFieldSet const&, unsigned char*, google::protobuf::io::EpsCopyOutputStream*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::DoubleValue::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const'
libarmnnTfParser.so.20.02: undefined reference to `descriptor_table_google_2fprotobuf_2fany_2eproto'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::PackedEnumParser(void*, char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::PackedDoubleParser(void*, char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedField<int>::Add(int const&)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::DoubleValue::_InternalParse(char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedField<long>::Add(long const&)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField(google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField(google::protobuf::Arena*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::PackedInt64Parser(void*, char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::PackedInt32Parser(void*, char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::Arena::AllocateAlignedNoHook(unsigned long)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::UnknownFieldParse(unsigned int, google::protobuf::internal::InternalMetadataWithArena*, char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedField<bool>::Add(bool const&)'
libarmnnTfParser.so.20.02: undefined reference to `scc_info_DoubleValue_google_2fprotobuf_2fwrappers_2eproto'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::VarintParseSlow32(char const*, unsigned int)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Clear()'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::MergeFrom(google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::PackedBoolParser(void*, char const*, google::protobuf::internal::ParseContext*)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::internal::NameOfEnum[abi:cxx11](google::protobuf::EnumDescriptor const*, int)'
libarmnnTfParser.so.20.02: undefined reference to `google::protobuf::Any::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const'

**Comment by MikeJKelly** [comment]
Hi @hashtagrk 

it looks like you have missing or out of date protobuf compilation libraries. You can use the command 'protoc --version' to check which version of protobuf is available (version 3.5.1 is required).

Are you following a guide? You can find a guide that tells you how to obtain and build the correct version at https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides

Best regards,
Mike

**Comment by hashtagrk** [comment]
@MikeJKelly , my version is 3.11.4. Are you sure 3.11.4 is not supported?

**Comment by hashtagrk** [comment]
The issue got solved using.....
-DPROTOBUF_LIBRARY_DEBUG='path/to/protobuf.so'
-DPROTOBUF_LIBRARY_RELEASE='path/to/protobuf.so' in cmake .

**Comment by MikeJKelly** [comment]
Thanks for letting us know! We've had problems with some earlier and later versions of protobuf and the version we've tested with is 3.5.2 so that's what we recommend.
