### ISSUE TITLE
Merge PyArmNN code into ArmNN

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#369]
I think it would be better to merge PyArmNN code from https://github.com/ARM-software/ML-examples/commits/master/pyarmnn-fire-detection/pyarmnn-19.11.0.tar.gz into ArmNN, instead of having a separate fork with non matching versions.

**Comment by MikeJKelly** [comment]
That sounds like a good idea.

**Comment by Burton2000** [comment]
PyArmNN has now been merged into master.

**Comment by james-conroy-arm** [comment]
Thanks Richard.

@ggardet , is it ok if I close this issue?

Cheers,
James

**Comment by ggardet** [comment]
It looks ok, thanks!
