### ISSUE TITLE
About Unit Test from default made binary(Without code change)

### ISSUE THREAD

**Issue by phamyphen** [ARM-software/armnn#37]
Hello,

What is the UnitTest binary entry point while running it? Where can we find the list of all test cases for the default UnitTest binary.  And how the interface works between tensor flow and ARMNN? Can anyone provide a example to show the mechanism behind it?

Thanks a lot.

**Comment by MatteoArm** [comment]
Hi @phamyphen,

In the unit tests there is no explicit entry point, that is a `main` function. the macro BOOST_TEST_MODULE is used instead (https://www.boost.org/doc/libs/1_64_0/libs/test/doc/html/boost_test/utf_reference/link_references/link_boost_test_module_macro.html), which does what BOOST_TEST_MAIN does, plus defines the name of the master test suite.

For a list of all unit tests, you can run the unit test binary with the --list_content option, for example:
`<your build path>/armnn/UnitTests --list_content`

**Comment by Surmeh** [comment]
Hi @phamyphen,

I hope your question has been answered. Please get in touch if you have any more queries.

Thanks,
Surabhi
