### ISSUE TITLE
Create an arm64 API 26 libc++ toolchain.

### ISSUE THREAD

**Issue by pradeepkrnik** [ARM-software/armnn#371]
I am getting some error in this process the error window is attached down:
![image](https://user-images.githubusercontent.com/62541809/78659266-ea7c9380-78e8-11ea-8e09-0e577355c64b.png)

I am using UBUNTU 16.04 , which is my laptop.
-thanks in advance.
Pradeep

**Comment by MikeJKelly** [comment]
Hi @pradeepkrnik 

this is a harmless warning that can be ignored. 

Newer Android NDK bundles have a prebuilt prebuilt toolchain that you can use you don't need to do toolchain generation anymore. You can skip that step.

**Comment by nikraj01** [comment]
Hi @pradeepkrnik ,

If you are not facing issues with building android, wondering if this can also be closed?

Thanks,
Nikhil.

**Comment by pradeepkrnik** [comment]
closed with the protobuf 3.5.0 and using  -Wno-error=deprecated-declarations? You can pass this to -DCMAKE_CXX_FLAGS
