### ISSUE TITLE
arm nn build failure.

### ISSUE THREAD

**Issue by pradeepkrnik** [ARM-software/armnn#373]
HI 
 I am trying to build the arm nn using the link provided below:
https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideAndroidNDK.md
I could succeed upto 
Build ArmNN steps
the cmake configure also got succeded.
the make -j16 throws the error
please see the below the attached cmake output and make -j16 output.
--cmake 

pradeep.k@PradeepK-LaptopU:~/.../build$ CXX=aarch64-linux-android-clang++ \
>  CC=aarch64-linux-android-clang \
>  CXX_FLAGS="-fPIE -fPIC" \
>  cmake .. \
>   -DCMAKE_SYSTEM_NAME=Android \
>   -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
>   -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$HOME/armnn-devenv/toolchains/aarch64-android-r17b/ \
>   -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
>   -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
>   -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
>   -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
>   -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 \
>   -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1 \
>   -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/
-- Android: Targeting API '26' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- The C compiler identification is Clang 6.0.2
-- The CXX compiler identification is Clang 6.0.2
-- Check for working C compiler: /home/pradeep.k/armnn-devenv/toolchains/aarch64-android-r17b//bin/clang
-- Check for working C compiler: /home/pradeep.k/armnn-devenv/toolchains/aarch64-android-r17b//bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/pradeep.k/armnn-devenv/toolchains/aarch64-android-r17b//bin/clang++
-- Check for working CXX compiler: /home/pradeep.k/armnn-devenv/toolchains/aarch64-android-r17b//bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   filesystem
--   program_options
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for valgrind/memcheck.h
-- Looking for valgrind/memcheck.h - not found
-- Caffe parser support is disabled
-- Tensorflow Lite parser support is disabled
-- Armnn Serializer support is disabled
-- ArmNN Quantizer support is disabled
-- Including backend common library into the build: /home/pradeep.k/armnn-devenv/armnn/src/backends/aclCommon/common.cmake
-- Including backend common library into the build: /home/pradeep.k/armnn-devenv/armnn/src/backends/backendsCommon/common.cmake
-- Including backend into the build: /home/pradeep.k/armnn-devenv/armnn/src/backends/cl/backend.cmake
-- Including backend into the build: /home/pradeep.k/armnn-devenv/armnn/src/backends/neon/backend.cmake
-- Including backend into the build: /home/pradeep.k/armnn-devenv/armnn/src/backends/reference/backend.cmake
-- Adding object library dependency to armnn: armnnAclCommon
-- Adding object library dependency to armnn: armnnBackendsCommon
-- Adding object library dependency to armnn: armnnClBackend
-- Adding object library dependency to armnn: armnnClBackendWorkloads
-- Adding object library dependency to armnn: armnnNeonBackend
-- Adding object library dependency to armnn: armnnNeonBackendWorkloads
-- Adding object library dependency to armnn: armnnRefBackend
-- Adding object library dependency to armnn: armnnRefBackendWorkloads
-- Adding object library dependency to UnitTests: armnnAclCommonUnitTests
-- Adding object library dependency to UnitTests: armnnBackendsCommonUnitTests
-- Adding object library dependency to UnitTests: armnnClBackendUnitTests
-- Adding object library dependency to UnitTests: armnnNeonBackendUnitTests
-- Adding object library dependency to UnitTests: armnnRefBackendUnitTests
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pradeep.k/armnn-devenv/armnn/build
pradeep.k@PradeepK-LaptopU:~/.../build$ make -j16
----------------------------------------------------------------------------------------

make -j16 fails.

**Comment by pradeepkrnik** [comment]
the make -j16 throws the following error:
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1074:13: error: 'host_temp_memory_size' is deprecated
      [-Werror,-Wdeprecated-declarations]
  if (this->host_temp_memory_size() != 0) {

**Comment by MikeJKelly** [comment]
That's a build issue when building protobuf, what protobuf version are you trying to build? The error is being raised by the -W=deprecated-declarations flag, you will need to build with -Wno-error=deprecated-declarations to get around this issue.

You seem to be encountering a lot of build problems, are you following a guide? You can find guides at https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides these guides give the versions we've tested with.

**Comment by pradeepkrnik** [comment]
Hi, 
 I am following the link 
https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideAndroidNDK.md

Could you please tell me 
-Wno-error=deprecated-declarations 
for which library i need to use this ?

**Comment by pradeepkrnik** [comment]
i am still not able to build on android 
any inputs here, facing the problem with protobuf. I followed the link 
https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideAndroidNDK.md

**Comment by nikraj01** [comment]
Hi @pradeepkrnik ,

Can you please let me know what error you are getting? Also I would be interested in knowing what ndk, protobuf and clang versions you are using?

Thanks,
Nikhil.

**Comment by nikraj01** [comment]
From the log it looks like you are trying to compile using clang

**Comment by nikraj01** [comment]
We were able to build successfully with protobuf 3.5.2 and ndk17 with gcc.

**Comment by pradeepkrnik** [comment]
I am following exact procedure mentioned in the link  all the versions, are adhered to below link
https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideAndroidNDK.md

To be specific:
Protobuf v3.5.2
Tensor flow using the branch: 590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b
ndk: wget https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip


After using exact paramertes for cmake which are mentioned in the below link,
--------------
https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideAndroidNDK.md
------------ 
and while make command, the error is :
---------------------------------------------------------------------------------------------------------------------------------
[ 51%] Built target gatordMockService
Scanning dependencies of target armnnTfParser
[ 51%] Building CXX object CMakeFiles/armnnTfParser.dir/src/armnnTfParser/TfParser.cpp.o
In file included from /home/pradeep.k/armnn-devenv/armnn/src/armnnTfParser/TfParser.cpp:20:
In file included from /home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/graph.pb.h:10:
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:140:2: error: PROTOBUF_FINAL was previously defined
#error PROTOBUF_FINAL was previously defined
^
In file included from /home/pradeep.k/armnn-devenv/armnn/src/armnnTfParser/TfParser.cpp:20:
In file included from /home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/graph.pb.h:26:
In file included from /home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/generated_message_table_driven.h:34:
In file included from /home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/map.h:48:
In file included from /home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/map_type_handler.h:35:
In file included from /home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/w
---------------------------------------------------------------------------------------------------------------------------------

**Comment by pradeepkrnik** [comment]
not building with me ..

**Comment by nikraj01** [comment]
ok, that's weird. I haven't come across that issue with my build.

**Comment by pradeepkrnik** [comment]
is there any guidence on how to build protobuf with 
-Wno-error=deprecated-declarations
this is coming from the previous suggestion by MikeJKelly commented 10 days ago •

**Comment by pradeepkrnik** [comment]
I am facing these errors:
-----------------------------------
[ 68%] Building CXX object src/backends/backendsCommon/test/CMakeFiles/ValidTestDynamicBackend.dir/TestDynamicBackend.cpp.o
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1074:13: error: 'host_temp_memory_size' is deprecated
      [-Werror,-Wdeprecated-declarations]
  if (this->host_temp_memory_size() != 0) {
            ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.h:698:3: note: 'host_temp_memory_size' has been explicitly
      marked deprecated here
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int64 host_temp_memory_size() const;
  ^
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:154:44: note: expanded from macro
      'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1080:13: error: 'device_temp_memory_size' is deprecated
      [-Werror,-Wdeprecated-declarations]
  if (this->device_temp_memory_size() != 0) {
            ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.h:707:3: note: 'device_temp_memory_size' has been explicitly
      marked deprecated here
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int64 device_temp_memory_size() const;
  ^
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:154:44: note: expanded from macro
      'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1104:13: error: 'device_persistent_memory_size' is
      deprecated [-Werror,-Wdeprecated-declarations]
  if (this->device_persistent_memory_size() != 0) {
            ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.h:743:3: note: 'device_persistent_memory_size' has been
      explicitly marked deprecated here
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int64 device_persistent_memory_size() const;
  ^
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:154:44: note: expanded from macro
      'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1206:13: error: 'host_temp_memory_size' is deprecated
      [-Werror,-Wdeprecated-declarations]
  if (this->host_temp_memory_size() != 0) {
            ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.h:698:3: note: 'host_temp_memory_size' has been explicitly
      marked deprecated here
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int64 host_temp_memory_size() const;
  ^
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:154:44: note: expanded from macro
      'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1213:13: error: 'device_temp_memory_size' is deprecated
      [-Werror,-Wdeprecated-declarations]
  if (this->device_temp_memory_size() != 0) {
            ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.h:707:3: note: 'device_temp_memory_size' has been explicitly
      marked deprecated here
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int64 device_temp_memory_size() const;
  ^
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:154:44: note: expanded from macro
      'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1241:13: error: 'device_persistent_memory_size' is
      deprecated [-Werror,-Wdeprecated-declarations]
  if (this->device_persistent_memory_size() != 0) {
            ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.h:743:3: note: 'device_persistent_memory_size' has been
      explicitly marked deprecated here
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int64 device_persistent_memory_size() const;
  ^
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:154:44: note: expanded from macro
      'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1302:12: error: 'host_temp_memory_size' is deprecated
      [-Werror,-Wdeprecated-declarations]
  if (from.host_temp_memory_size() != 0) {
           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.h:698:3: note: 'host_temp_memory_size' has been explicitly
      marked deprecated here
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int64 host_temp_memory_size() const;
  ^
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:154:44: note: expanded from macro
      'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1305:12: error: 'device_temp_memory_size' is deprecated
      [-Werror,-Wdeprecated-declarations]
  if (from.device_temp_memory_size() != 0) {
           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.h:707:3: note: 'device_temp_memory_size' has been explicitly
      marked deprecated here
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int64 device_temp_memory_size() const;
  ^
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:154:44: note: expanded from macro
      'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc:1317:12: error: 'device_persistent_memory_size' is
      deprecated [-Werror,-Wdeprecated-declarations]
  if (from.device_persistent_memory_size() != 0) {
           ^
/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.h:743:3: note: 'device_persistent_memory_size' has been
      explicitly marked deprecated here
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::int64 device_persistent_memory_size() const;
  ^
/home/pradeep.k/armnn-devenv/google/arm64_pb_install/include/google/protobuf/port_def.inc:154:44: note: expanded from macro
      'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
9 errors generated.
make[2]: *** [CMakeFiles/armnnTfParser.dir/home/pradeep.k/armnn-devenv/google/tf_pb/tensorflow/core/framework/cost_graph.pb.cc.o] Error 1
make[1]: *** [CMakeFiles/armnnTfParser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 68%] Linking CXX shared module backendsTestPath5/Arm_TestInvalid8_backend.so
[ 68%] Built target Arm_TestInvalid8_backend
[ 68%] Linking CXX shared module testDynamicBackend/libInvalidTestDynamicBackend1.so
[ 69%] Linking CXX shared module testDynamicBackend/libValidTestDynamicBackend.so
[ 69%] Built target InvalidTestDynamicBackend1
[ 69%] Built target ValidTestDynamicBackend
make: *** [all] Error 2
---------------------------------------
though I have built protobuf with the following methods.


 mkdir ~/armnn-devenv/google
 cd ~/armnn-devenv/google
 git clone https://github.com/google/protobuf.git
 cd protobuf
 git checkout -b v3.5.2 v3.5.2

 ./autogen.sh
 mkdir x86_build
 cd x86_build
 ../configure --prefix=$HOME/armnn-devenv/google/x86_pb_install
CXX_FLAGS="-Wno-error=deprecated-declarations" \
 make install -j16
cd ..

 mkdir arm64_build
 cd arm64_build
 CC=aarch64-linux-android-clang \
   CXX=aarch64-linux-android-clang++ \
   CFLAGS="-fPIE -fPIC" LDFLAGS="-pie -llog" \
    ../configure --host=aarch64-linux-android \
    --prefix=$HOME/armnn-devenv/google/arm64_pb_install \
    --with-protoc=$HOME/armnn-devenv/google/x86_pb_install/bin/protoc \
CXX_FLAGS="-Wno-error=deprecated-declarations" \
 make install -j16
 cd ..

and tensor flow using:
 cd ~/armnn-devenv/google/
 git clone https://github.com/tensorflow/tensorflow.git
     cd tensorflow/
     git checkout 590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b

 cd ~/armnn-devenv/google/tensorflow
 ~/armnn-devenv/armnn/scripts/generate_tensorflow_protobuf.sh \
  $HOME/armnn-devenv/google/tf_pb $HOME/armnn-devenv/google/x86_pb_install



-- any hint....

**Comment by nikraj01** [comment]
do you have protobuf root pointing to $HOME/google/arm64_pb_install/ while building ArmNN?

**Comment by pradeepkrnik** [comment]
-DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/
this is what configured during cmake

**Comment by nikraj01** [comment]
ok, can you build ArmNN using -Wno-error=deprecated-declarations? You can pass this to -DCMAKE_CXX_FLAGS

**Comment by pradeepkrnik** [comment]
ok. will try this.

**Comment by pradeepkrnik** [comment]
thanks for the information,
its building with protobuf 3.5.0 and give suggestion.
