### ISSUE TITLE
 Unsupported operation Neg in tensorflow::GraphDef  at function LoadNodeDef

### ISSUE THREAD

**Issue by pradeepkrnik** [ARM-software/armnn#374]
HI 
 I am using the ARMNN On Linux ubuntu 16.04, 

Was trying to use the tensor flow model, which is not showing the branch at 
* (HEAD detached at 590d6ee)
- I faced the error as:
  Unsupported operation Neg in tensorflow::GraphDef  at function LoadNodeDef at  /armnn-tflite/armnn/src/armnnTfParser/TfParser.cpp:3431]
- any suggestion here ..
thanks in advance.
-regards
Pradeep

**Comment by MikeJKelly** [comment]
Hi @pradeepkrnik 

The Tensorflow Parser does not support the Neg operation. If you wish to add support for that operation then we are open to contributions?

If you have a look here:
https://mlplatform.org/contributing/

Our gerrit server: https://review.mlplatform.org/#/dashboard/self

The first thing to do is to get it working with the latest master branch of Arm NN.

Next make sure you can log in to gerrit at https://review.mlplatform.org/#/dashboard/self using your Github account. Add your ssh key under "settings -> SSH public keys".

Then submit it to a gerrit review with a command like this, replacing with your Github username:
git push ssh://@review.mlplatform.org:29418/ml/armnn HEAD:refs/for/master

Best regards,
Mike.

**Comment by matthewsloyanARM** [comment]
Hi @pradeepkrnik,

With the upcoming Arm NN release (21.05) we will be deprecating the Arm NN TensorFlow Parser, so we won't be able to add Neg support unfortunately. Based on this I will close this Issue and remove the "Help wanted" label. However, we have recently added support for Neg in the TFLiteParser which will be available in the 21.05 release at the end of the month. It is also currently supported in the TFLite Delegate so this would be another solution. Here is a guide if you would like to implement this in your application: https://arm-software.github.io/armnn/latest/md_delegate__build_guide_native.xhtml. Also to use these you could covert your TF model to TFLite using the [TFLiteConverter](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter).

If you have any questions or problems please don't hesitate to reopen this issue or create a new one. Thank you!

Kind regards, 

Matthew
