### ISSUE TITLE
Caffe getting started link is not working

### ISSUE THREAD

**Issue by santo4ul** [ARM-software/armnn#377]
Hi, The below given link in README.md file isn't working. Is the side down or the link is wrong?

[https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe](https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe)

Thanks,
San

**Comment by nikraj01** [comment]
Hi @santo4ul ,

That particular page seems to be down for the moment. I will get an update on this soon.

Thanks,
Nikhil.

**Comment by nikraj01** [comment]
Hi @santo4ul ,

We have updated link to the guides in the readme file now. Can you please try to access it and let me know?

Thanks,
Nikhil.

**Comment by santo4ul** [comment]
Thanks @nikraj01
