### ISSUE TITLE
armn_neon.h file missing

### ISSUE THREAD

**Issue by pradeepkrnik** [ARM-software/armnn#378]
HI I am trying to build armnn on Ubuntu 16.04.
with the below cmake
cmake .. \
-DBUILD_TESTS=1 \
-DFLATC=$BASEDIR/flatbuffers \
-DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary \
-DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build \
-DBOOST_ROOT=$BASEDIR/boost \
-DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf \
-DPROTOBUF_ROOT=$BASEDIR/protobuf-host \
-DSAMPLE_DYNAMIC_BACKEND=1 \
-DDYNAMIC_BACKEND_PATHS=$BASEDIR/armnn/src/dynamic/sample \
-DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf \
-DBUILD_TF_PARSER=1 \
-DBUILD_TF_LITE_PARSER=1 \
-DTF_LITE_GENERATED_PATH=$BASEDIR/tensorflow/tensorflow/lite/schema \
-DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers \
-DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers/libflatbuffers.a \
-DBUILD_ONNX_PARSER=1 \
-DONNX_GENERATED_SOURCES=$BASEDIR/onnx \

I am able to build armnn successfully.

but If add   -DARMCOMPUTENEON=1  , as show below ..
cmake .. \
-DBUILD_TESTS=1 \
-DFLATC=$BASEDIR/flatbuffers \
-DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary \
-DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build \
-DBOOST_ROOT=$BASEDIR/boost \
-DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf \
-DPROTOBUF_ROOT=$BASEDIR/protobuf-host \
-DSAMPLE_DYNAMIC_BACKEND=1 \
-DDYNAMIC_BACKEND_PATHS=$BASEDIR/armnn/src/dynamic/sample \
-DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf \
-DBUILD_TF_PARSER=1 \
-DBUILD_TF_LITE_PARSER=1 \
-DTF_LITE_GENERATED_PATH=$BASEDIR/tensorflow/tensorflow/lite/schema \
-DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers \
-DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers/libflatbuffers.a \
-DBUILD_ONNX_PARSER=1 \
-DONNX_GENERATED_SOURCES=$BASEDIR/onnx \
-DARMCOMP-DARMCOMPUTENEON=1UTENEON=1

I get below error while using "make" command  - arm_neon.h file missing. - any help here ..
/home/pradeep.k/armnn-tflite/ComputeLibrary/arm_compute/core/NEON/kernels/NEFFTRadixStageKernel.h:30:22: fatal **error: arm_neon.h: No such file or directory**
compilation terminated.
src/backends/neon/CMakeFiles/armnnNeonBackend.dir/build.make:88: recipe for target 'src/backends/neon/CMakeFiles/armnnNeonBackend.dir/NeonLayerSupport.cpp.o' failed
make[2]: *** [src/backends/neon/CMakeFiles/armnnNeonBackend.dir/NeonLayerSupport.cpp.o] Error 1
CMakeFiles/Makefile2:1960: recipe for target 'src/backends/neon/CMakeFiles/armnnNeonBackend.dir/all' failed
make[1]: *** [src/backends/neon/CMakeFiles/armnnNeonBackend.dir/all] Error 2
Makefile:129: recipe for target 'all' failed

-thanks
Pradeep

**Comment by MikeJKelly** [comment]
Hi @pradeepkrnik 

the arm_neon.h header should have been installed as part of the crossbuild-essential-arm64 package, can you confirm if it's there, it should be somewhere in /usr/lib/gcc-cross (your path may vary). 

You will also have to set your CXX and CC variables for the make command.   
Our guides recommend something like:

cd armnn && mkdir build && cd build &&
CXX=aarch64-linux-gnu-g++ &&
CC=aarch64-linux-gnu-gcc &&
cmake ..
-DBUILD_TESTS=1
-DFLATC=$BASEDIR/flatbuffers
-DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary
-DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build
-DBOOST_ROOT=$BASEDIR/boost
-DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf
-DPROTOBUF_ROOT=$BASEDIR/protobuf-host
-DSAMPLE_DYNAMIC_BACKEND=1
-DDYNAMIC_BACKEND_PATHS=$BASEDIR/armnn/src/dynamic/sample
-DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf
-DBUILD_TF_PARSER=1
-DBUILD_TF_LITE_PARSER=1
-DTF_LITE_GENERATED_PATH=$BASEDIR/tensorflow/tensorflow/lite/schema
-DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers
-DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers/libflatbuffers.a
-DBUILD_ONNX_PARSER=1
-DONNX_GENERATED_SOURCES=$BASEDIR/onnx
-DARMCOMPUTENEON=1

See #367 for more information

Best regards,
Mike

**Comment by pradeepkrnik** [comment]
HI Mike,
i have checked below
pradeep.k@PradeepK-LaptopU:/usr$ sudo find . -name "arm_neon.h"
[sudo] password for pradeep.k: 
./lib/gcc-cross/aarch64-linux-gnu/5/include/arm_neon.h
./lib/llvm-3.8/lib/clang/3.8.0/include/arm_neon.h
./lib/llvm-6.0/lib/clang/6.0.1/include/arm_neon.h
pradeep.k@PradeepK-LaptopU:/usr$ 


but even after setting the flags like:
CXX=aarch64-linux-gnu-g++ &&
CC=aarch64-linux-gnu-gcc &&
cmake ..
....
...

the error is still persists.

-any help.
-thanks
Pradeep

**Comment by pradeepkrnik** [comment]
> /usr/lib/gcc-cross
pradeep.k@PradeepK-LaptopU:.../lib$ find . -name "arm_neon.h"
./gcc-cross/aarch64-linux-gnu/5/include/arm_neon.h
./llvm-3.8/lib/clang/3.8.0/include/arm_neon.h
./llvm-6.0/lib/clang/6.0.1/include/arm_neon.h

But still the error is present -- any help.

**Comment by Colm-in-Arm** [comment]
Hi @pradeepkrnik,

I've looked at the compile chain and I can't find anything specific to the ArmNN build added to pick up arm_neon.h. It is relying on the default compiler include path to find it. Is there something in your environment that is overriding the default include paths for the compiler? Have you set C_INCLUDE_PATH or CPLUS_INCLUDE_PATH?

Colm.

**Comment by james-conroy-arm** [comment]
Hi @pradeepkrnik ,

Do you have any new information regarding this issue or Colm's questions?

Cheers,
James

**Comment by TeresaARM** [comment]
Closing this issue as we have not heard from you since May. Please come back to us if you have any further questions.
