### ISSUE TITLE
Output armnn-mobilenet-quant misaligned.

### ISSUE THREAD

**Issue by Qengineering** [ARM-software/armnn#379]
It looks that the output of the MobileNetV1_Quant ML-example is misaligned. The first (and only) prediction of the ARMnn example gives always the second option of the official TensorFlow Lite C++ example. For instance, grace_hopper.bmp gives "Windsor tie" as output, which should be "Military uniform" (0.834) and next "Windsor tie" (0.021).

**Comment by MatthewARM** [comment]
Hi @Qengineering do you mean the code in https://github.com/ARM-software/ML-examples/tree/master/armnn-mobilenet-quant ?

**Comment by Qengineering** [comment]
Indeed, however, it is not entirely clear. With the grace-hopper.bmp you get the "Windsor tie" as an incorrect result. On this site, you see this error also at the end, if you look carefully: https://medium.com/@RouYunPan/arm-nn-on-rpi4-806ef8a10e61
On the other hand, when I run the "school bus" image, it gives the correct output.

**Comment by james-conroy-arm** [comment]
Hi @Qengineering ,

We have reproduced this and are investigating it now.

Thanks,
James

**Comment by james-conroy-arm** [comment]
Hi @Qengineering ,

Please refer to this website for Tensorflow's hosted TfLite models: https://www.tensorflow.org/lite/guide/hosted_models

There are four different versions of the MobileNetV1 quantized model with varying degrees of depth multiplier (channels): 0.25, 0.5, 0.75 and 1.0.
1. Mobilenet_V1_0.25_224_quant
2. Mobilenet_V1_0.50_224_quant
3. Mobilenet_V1_0.75_224_quant
4. Mobilenet_V1_1.0_224_quant

We have tested all of the above with the ArmNN example. Both (1) and (4) give the correct result, "military uniform".
Models (2) and (3) both give the result "bow tie, bow-tie, bowtie", which is incorrect.

Therefore, your issue can be explained by the accuracy of the model you are using. It's possible that the model you are using which produces the result "Windsor tie" is out of date (could you let us know where you sourced it please?)

Please let us know if the above information resolves your issue.

Cheers,
James

**Comment by Qengineering** [comment]
Dear James,

Many thanks for all the effort you have taking. 
I have the same results as you after downloading the latest Mobilenet_V1_xx_244_quant form the tensorflow.org site.
I'm closing the issue because it's resolved.

Cheers,
Rients
