### ISSUE TITLE
Neon Workload creation fails for Fully Connected layer with Quantized ONet

### ISSUE THREAD

**Issue by pateldarsh** [ARM-software/armnn#380]
Hi,

I am not able to run quantized ONet ARMNN. ONet is part of MTCNN for face landmarks detection. I am able to run Non-Quantized version of same model. Both are in TFLite format. I am getting below error.

Please let me know if you need any more information on this.

_root@h3ulcb:~//tests# ./ExecuteNetwork -f tflite-binary -i onet/input -o onet/conv6-1/conv6-1 onet/conv6-2/conv6-2 onet/conv6-3/conv6-3 -c CpuAcc -s 1,48,48,3  -m ./Onet_without_Neg_Quantized.tflite_ 

_Info: ArmNN v20200200

Warning: No input files provided, input tensors will be filled with 0s.
Warning: WARNING: Layer of type Constant is not supported on requested backend CpuAcc for input data type Float32 and output data type QAsymmS8 (reason: ), falling back to the next backend.
Warning: WARNING: Layer of type Constant is not supported on requested backend CpuAcc for input data type Float32 and output data type QAsymmS8 (reason: ), falling back to the next backend.
Warning: WARNING: Layer of type Constant is not supported on requested backend CpuAcc for input data type Float32 and output data type QAsymmS8 (reason: ), falling back to the next backend.
Warning: WARNING: Layer of type Constant is not supported on requested backend CpuAcc for input data type Float32 and output data type QAsymmS8 (reason: ), falling back to the next backend.
Warning: WARNING: Layer of type Constant is not supported on requested backend CpuAcc for input data type Float32 and output data type QAsymmS8 (reason: ), falling back to the next backend.
**Error: An error occurred when preparing the network workloads:  No workload created for layer (name: 'FullyConnected:0:24' type: '20') (compute 'CpuAcc')
Fatal: Armnn Error: IRuntime::LoadNetwork failed**_

Thanks,
Darshan

**Comment by MikeJKelly** [comment]
Hi @pateldarsh 

it looks like Constant doesn't support QAsymmS8 at the moment, I'll take a look. 

Mike

**Comment by pateldarsh** [comment]
Hi Mike,

Thank you for your feedback. I added few logs in code. It seems INT8 datatype is not supported yet for FC layers. It supports only FLOAT32 and UINT8.

_std::unique_ptr<armnn::IWorkload> NeonWorkloadFactory::CreateFullyConnected(
    const FullyConnectedQueueDescriptor& descriptor, const WorkloadInfo& info) const
{
    return MakeWorkloadHelper<NeonFullyConnectedWorkload, NeonFullyConnectedWorkload>(
        descriptor, info, m_MemoryManager->GetIntraLayerManager());
}_


_void FullyConnectedQueueDescriptor::Validate(const WorkloadInfo& workloadInfo) const_
    _// Check the supported data types
    std::vector<DataType> supportedTypes =
    {
        DataType::Float32,
        DataType::Float16,
        DataType::QAsymmU8,
        DataType::QSymmS16
    };_


But it seems ComputeLib has added QSymmS8 and QAsymmS8. Could you please guide me steps for adding this support in ARMNN ?

Please let me know if issue is somewhere else.


Thanks,
Darshan

**Comment by MikeJKelly** [comment]
Hi Darshan,

I've created a review to add QAsymmS8 to the Neon backend, it's at: 

https://review.mlplatform.org/c/ml/armnn/+/3099 

That should hopefully be merged soon, if you want you can cherry pick that patch to see if it solves your problem? 

Looking at the master branch I can see that QAsymmS8 was added to the FullyConnectedQueueDescriptor in March, are you on the 20.02 release? If you switch the master branch that should be OK now:

https://github.com/ARM-software/armnn/blob/master/src/backends/backendsCommon/WorkloadData.cpp

Best regards,
Mike

**Comment by pateldarsh** [comment]
Hi Mike,

I modifed _FullyConnectedQueueDescriptor::Validate_ to accept QAsymmS8. Also added mapping of this to InitializeArmComputeTensorData. Now I am able to run ONet. I am yet to match output of model with PC version.

Please let me know if this temporary fix is not valid.

Thanks,
Darshan

**Comment by pateldarsh** [comment]
Hi Mike,

I am using v20.02. Thank you for your support. This solves my issue.

Thanks,
Darshan
