### ISSUE TITLE
How can i choose code style fomat for C/C++ file?

### ISSUE THREAD

**Issue by LjBLincoln** [ARM-software/armnn#381]
How can i choose code style fomat for C/C++ file?
when add a c/C++ file ,what code style can i choose :Google？LLVM ？ which make the code sytle same as the armnn.

**Comment by keidav01** [comment]
Hi @LjBLincoln, we use our own standard that is loosely based on the Googles codestyle. Using theirs will achieve a similar layout!

**Comment by LjBLincoln** [comment]
Hi @keidav01 , thanks for you advices, i will use goolge codestyle.
