### ISSUE TITLE
MUL & FullyConnected layer takes more processing time for QAsymmS8 than Float32 Datatype

### ISSUE THREAD

**Issue by pateldarsh** [ARM-software/armnn#382]
Hi,

I quantized ONet ( Part of [MTCNN](https://github.com/timesler/facenet-pytorch) ). ONet is for facial landmarks detections. But quantized model takes more time compare to FP32 model.

When I analyze layer timing details, FullyConnected layer and Matrix Multiplacation takes more than double time for S8 compare to FP32. I guess, Both internally uses _NEPixelWiseMultiplication_. Convolution layer time is reduced. Models attached in zip file. File is renamed to text for attachment purpose.

**Command To reproduce** :

_./ExecuteNetwork -i onet/input -o onet/conv6-2/conv6-2,onet/conv6-3/conv6-3,onet/conv6-1/conv6-1 -s 1,48,48,3 -f tflite-binary -c CpuAcc -m onet_INT8.tflite -e_

Is this behavior expected ? Or I have configured something wrong ?

Please let me know more details are required.

[models.txt](https://github.com/ARM-software/armnn/files/4547079/models.txt)

**Comment by MikeJKelly** [comment]
Hi @pateldarsh 

it could be expected depending on the kind of hardware that your model is running on. If the processor does not have the 8-bit integer dot-product instruction then using quantized 8-bit wouldn't give you a performance increase, only reduced memory bandwidth. What kind of device are you running on?

**Comment by pateldarsh** [comment]
Hi @MikeJKelly ,

Thank you for your reply. I am using **NXP iMX 8X** device. It has **4 Cortex A35 cores**.

As I have mentioned, I could see improvment in Convolution layer. I have profiled public MobileNet and SSD COCO. I observed quantized model takes half the time FP32 model on hardware. Depthwise Conv2D time is also reduced.

Please let me know if you want me to run any specific test on my hardware to give more info regarding the issue.

Thanks,
Darshan

**Comment by morgolock** [comment]
Hi @pateldarsh 

Please take a look at my reply here: https://github.com/ARM-software/ComputeLibrary/issues/816

ConvolutionLayer does not use PixelWiseMultiplication.

Comparing individual layers for different types is not quite the same as comparing the full network.

FCLayer and Convolution layer are expected to be slightly slower for quantized types than for fp32 in the absence of the dot product instruction.

Hope this helps.

**Comment by james-conroy-arm** [comment]
Hi @pateldarsh ,

Do you have any other questions regarding this issue?

Cheers,
James

**Comment by pateldarsh** [comment]
No. @james-conroy-arm . We got a reply of MLCE ticket that there's a bug with INT8 datatype handling which leads to increase in processing time. Closing it here. Thank you for help.
