### ISSUE TITLE
input & weight must have identical data types.

### ISSUE THREAD

**Issue by najiji** [ARM-software/armnn#383]
I am trying to run a tflite model. Upon loading that model into armnn, I get 

```
An error occurred when preparing the network workloads:  Convolution2dQueueDescriptor: input & weight must have identical data types.

terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
```

When running with CpuAcc backend and

```
Warning: WARNING: Layer of type Convolution2d is not supported on requested backend CpuRef for input data type Float32 and output data type Float32 (reason: Reference Convolution2d: input and weights types mismatched.), falling back to the next backend.
Warning: ERROR: Layer of type Convolution2d is not supported on any preferred backend [CpuRef ]
```

When running with CpuRef backend. The program then crashes on a segfault upon `LoadNetwork`. Is there a specific form I have to put the tflite network in to make it work?

**Comment by Colm-in-Arm** [comment]
Hi Thomas,

Can you describe the failing layer please? What are the data types of the input and weights on the Convolution2d layer in the model before conversion?

Could you please tell me a bit more about the "segfault upon LoadNetwork". This shouldn't happen. Which version of ArmNN you're using and on what platform please.

Colm.

**Comment by najiji** [comment]
Hi Colm, 

I figured out where the problem was: When exporting a tf model to tflite, I was giving the converter the option `tf.lite.Optimize.DEFAULT`. Upon inspection of the resulting network, I found that this option ends up quantizing weights in some Conv2D layers to int8, based on some heuristics I presume. Not giving this options leaves the network alone and all is in float32 as expected. 

I am using tensorflow `2.2.0-rc0` and ArmNN `v20200200`, on an i.MX8M Cortex A53. 
The segfault in `LoadNetwork` was caused by the call to `armnn::Optimize` returning a `nullptr`, as already mentioned in other threads. 

The fp32 model now works with CpuAcc and CpuRef, with CpuAcc about 130 times faster.
 
The same model exported to quantized with the tflite converter option set to `tf.lite.OpsSet.TFLITE_BUILTINS_INT8` does work with CpuRef, but segfaults with CpuAcc on the `LoadNetwork` call. This time, the call to `armnn::Optimize` does not return a `nullptr`. I still expect the problem to be in `armnn::Optimize`, as when I set debug to true there, nothing gets printed. Also setting the global log level to debug doesn't output more.

The tflite exporter keeps the input / output as fp32, and adds the `Quantize` and `Dequantize` layers, is that something that is not supported yet?

**Comment by pateldarsh** [comment]
Hi @najiji ,

I have faced similar issue with quantized networks. In my case, Fully connected layer was creating issue.

Are you getting something like below error ?

```
_Error: An error occurred when preparing the network workloads:  No workload created for layer (name: 'FullyConnected:0:24' type: '20') (compute 'CpuAcc')
Fatal: Armnn Error: IRuntime::LoadNetwork failed_
```

If possible, Please share your model or some information related to types of layers used.

Thanks,
Darshan

**Comment by najiji** [comment]
@pateldarsh No, I do not get that error, in my case, there is no error at all. I produced a minimal model with just a single 1x1 conv layer and no activation that produces the error. In the attachment both the FP32 version which works in my case, and the int8 version that crashes. 


[minimal_models.zip](https://github.com/ARM-software/armnn/files/4608631/minimal_models.zip)

**Comment by kannanrn** [comment]
> Hi Colm,
> 
> I figured out where the problem was: Some of my Conv2D layers had 8-bit quantized weights, but FP32 inputs. My fault!
> The segfault in `LoadNetwork` was caused by the call to `armnn::Optimize` returning a `nullptr`, as already mentioned in other threads.
> 
> The fp32 model now works with CpuAcc and CpuRef, with CpuAcc about 130 times faster.

Hi Najiji,  

Even I am facing exactly the same issue with same error message and failure at armnn::Optimize call.

Could you please elaborate the steps you followed to resolve this issue.  Thanks for your support.

Kannan
