### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zx854217561** [ARM-software/armnn#384]
I am trying to build armnn on ubuntu18.04

Scanning dependencies of target armnnAclCommon
[ 15%] Building CXX object src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/ArmComputeTensorUtils.cpp.o
In file included from /home/zmou/armnn/src/backends/aclCommon/ArmComputeTensorUtils.cpp:6:0:
/home/zmou/armnn/src/backends/aclCommon/ArmComputeUtils.hpp: In function ‘arm_compute::ActivationLayerInfo::ActivationFunction armnn::ConvertActivationFunctionToAclActivationFunction(armnn::ActivationFunction)’:
/home/zmou/armnn/src/backends/aclCommon/ArmComputeUtils.hpp:68:79: error: ‘HARD_SWISH’ is not a member of ‘AclActivationFunction {aka arm_compute::ActivationLayerInfo::ActivationFunction}’
 se ActivationFunction::HardSwish:     return AclActivationFunction::HARD_SWISH;
                                                                     ^~~~~~~~~~
/home/zmou/armnn/src/backends/aclCommon/ArmComputeTensorUtils.cpp: In function ‘arm_compute::DataType armnn::armcomputetensorutils::GetArmComputeDataType(armnn::DataType, bool)’:
/home/zmou/armnn/src/backends/aclCommon/ArmComputeTensorUtils.cpp:21:43: error: ‘BFLOAT16’ is not a member of ‘arm_compute::DataType’
             return arm_compute::DataType::BFLOAT16;
                                           ^~~~~~~~
src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/build.make:62: recipe for target 'src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/ArmComputeTensorUtils.cpp.o' failed
make[2]: *** [src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/ArmComputeTensorUtils.cpp.o] Error 1
CMakeFiles/Makefile2:850: recipe for target 'src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/all' failed
make[1]: *** [src/backends/aclCommon/CMakeFiles/armnnAclCommon.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MatthewARM** [comment]
Hi @zx854217561 it looks like you're building with the master branch of Arm NN, but an older version of Compute Library.  

If you need the master branch of Arm NN then you will also need a recent unreleased version of Compute Library. (From the development gerrit repo at review.mplatform.org)

Alternatively, you could use the latest released version of Arm NN (20.02) which will work fine with the corresponding Compute Library release (20.02)

Hope that helps,
Matthew

**Comment by zx854217561** [comment]
hi@MatthewARM
I follow with the https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideCrossCompilation.md
may be i git the wrong version?
which version should i use?

**Comment by zx854217561** [comment]
> Hi @zx854217561 it looks like you're building with the master branch of Arm NN, but an older version of Compute Library.
> 
> If you need the master branch of Arm NN then you will also need a recent unreleased version of Compute Library. (From the development gerrit repo at review.mplatform.org)
> 
> Alternatively, you could use the latest released version of Arm NN (20.02) which will work fine with the corresponding Compute Library release (20.02)
> 
> Hope that helps,
> Matthew

hi@MatthewARM
I follow with the https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideCrossCompilation.md
may be i git the wrong version?
which version should i use?

**Comment by MatthewARM** [comment]
Strange, those instructions should get the 20.02 release, I'll check over them.

In any case, you can fix it by checking out the 20.02 release branch:

```
cd armnn
git checkout branches/armnn_20_02
git pull
```

**Comment by zx854217561** [comment]
> Strange, those instructions should get the 20.02 release, I'll check over them.
> 
> In any case, you can fix it by checking out the 20.02 release branch:
> 
> ```
> cd armnn
> git checkout branches/armnn_20_02
> git pull
> ```

thank u so much

**Comment by Colm-in-Arm** [comment]
Both BuildGuideAndroidNDK.md  and BuildGuideCrossCompilation.md have been updated for the 20.05 release.

https://review.mlplatform.org/c/ml/armnn/+/3224

Colm.
