### ISSUE TITLE
Example ONNX running with Arm NN on server

### ISSUE THREAD

**Issue by GalMoore** [ARM-software/armnn#385]
Hey -  I was hoping you could point me in the right direction:

1. When I [build an environment](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx/single-page) for ONNX, I see ONNX protobuf source files are created. Could you explain where is the architecture definition and where are the weights?
2. Looking at the[ simple example](https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/samples/SimpleSample.cpp) – I haven’t yet found online a working example with ONNX model for deployment – could you share a cpp file that runs the ONNX model and weights with some input?

Thank you!

**Comment by MatthewARM** [comment]
Hi @GalMoore 

1. The generated files in the build step are part of the Arm NN ONNX *parser*, ie. they contain code for decoding ONNX files. Your network architecture definition and weights should be in either a .pb or .onnx file generated by some other tool. E.g. the ONNX exporter from PyTorch.
2. Unfortunately the only example for reading ONNX files in the Arm NN tree is in the test system, which uses quite a few other dependencies: https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/tests/OnnxMnist-Armnn/OnnxMnist-Armnn.cpp

Eventually that code calls through to methods on IONNXParser to create an Arm NN onnx parser and load the model.

**Comment by GalMoore** [comment]
Thanks @MatthewARM. 

I'm trying to run the OnnxMnist-Armnn executable after compiling ArmNN following  [these steps](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx/single-page) and enabling the following rows [here](https://github.com/ARM-software/armnn/blob/branches/armnn_20_05/cmake/GlobalConfig.cmake)

> option(BUILD_ONNX_PARSER "Build Onnx parser" ON)
option(BUILD_UNIT_TESTS "Build unit tests" ON)
option(BUILD_TESTS "Build test applications" ON)

 I used [this data](https://github.com/ARM-software/ML-examples/tree/master/armnn-mnist/data) and [this onnx model ](https://onnxzoo.blob.core.windows.net/models/opset_8/mnist/mnist.tar.gz) and I am getting this error: 

>  [gal@taishan87 tests]$ ./OnnxMnist-Armnn --data-dir=mnist --model-dir=mnist
Info: ArmNN v20200200
> 
> Fatal: Armnn Error: Some backend IDs are invalid: CpuAcc

I am on an ARM A server with EulerOS. What is the CpuAcc error and how to I fix it?
Thanks!

**Comment by MatthewARM** [comment]
Hi @GalMoore that error indicates that the NEON backend ("CPU Accelerated" or CpuAcc) hasn't been linked in to your Arm NN.

You need to add `-DARMCOMPUTENEON=1` to your cmake command, as per the section on "If you are supporting NEON..." at https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx/single-page#build-arm-nn

If you have already done that and it's still not working, could you post the output of your cmake command?

Thanks,
Matthew

**Comment by GalMoore** [comment]
Thank you @MatthewARM. I am going through [this]( https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx/single-page#build-arm-nn) again, but fail to compile ComputeLibrary with `neon=1` ending with this error:

![image](https://user-images.githubusercontent.com/14869708/83638718-3fb7e700-a5b2-11ea-87da-4fe33dac31ba.png)

1. Is it possible to run ComputeLibrary and Armnn at all without NEON?
2. If not, how do I debug the error above during installation? 
3. Alternatively, is it possible to compile ArmNN with neon (as suggested) and ComputeLibrary without neon (this has worked previously?

Thanks!

**Comment by MatthewARM** [comment]
Hi @GalMoore,

The backends that are in the Arm NN codebase are:
CpuAcc - acceleration provided by Compute Library NEON routines
GpuAcc - acceleration provided by Compute Library OpenC routines
CpuRef - no acceleration (reference C++ routines)

So if you want CpuAcc you have to compile Compute Library NEON support.
If you just want to run on CPU to try out things on the Arm NN frontend you can use CpuRef but the inference performance will be poor.

Out of interest, what CPU / Architecture are you compiling for?

Hope that helps,
Matthew

**Comment by GalMoore** [comment]
Thanks @MatthewARM. I'm running a 64-bit server microprocessor called [Kunpeng 920](https://en.wikichip.org/wiki/hisilicon/kunpeng/920-6426) which is ARMv8.2. I am building on target (not cross-compile) so using `build=native` flag together with` neon=1` in scons.

**Comment by MatthewARM** [comment]
Have you set `arch=arm64-v8.2-a` when building ComputeLibrary? It's strange to see this error though as I thought that fadd was a core NEON instruction.

@morgolock any suggestions about the Compute Library compile error?

**Comment by morgolock** [comment]
Hi @GalMoore 

Could you please share the full output of the compiler to have a better view of the error?

Could you please also share the output of `g++ -v`?

Does the library build for arch=armv8-a?

**Comment by GalMoore** [comment]
Thanks @MatthewARM and @morgolock.

I've now managed to compile ComputeLibrary with  `arch=arm64-v8.2-a` (was previously using `arch=arm64-v8a`). Then left Boost, Google protobuf and Onnx protobuf as they were from previous builds, deleted Armnn build dir and tried building; this time with  

> cmake .. -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build -DBOOST_ROOT=$BASEDIR/boost -DPROTOBUF_ROOT=$BASEDIR/protobuf-host -DBUILD_ONNX_PARSER=1 -DONNX_GENERATED_SOURCES=$BASEDIR/onnx -DARMCOMPUTENEON=1

fails at 

> [ 27%] Building CXX object src/backends/neon/workloads/CMakeFiles/armnnNeonBackendWorkloads.dir/NeonSoftmaxBaseWorkload.cpp.o
/home/gal/armnn-onnx/armnn/src/backends/neon/workloads/NeonSoftmaxBaseWorkload.cpp: In function ‘arm_compute::Status armnn::NeonSoftmaxWorkloadValidate(const armnn::TensorInfo&, const armnn::TensorInfo&, const armnn::SoftmaxDescriptor&)’:
/home/gal/armnn-onnx/armnn/src/backends/neon/workloads/NeonSoftmaxBaseWorkload.cpp:24:107: error: conversion to ‘int32_t {aka int}’ from ‘unsigned int’ may change the sign of the result [-Werror=sign-conversion]
  arm_compute::NESoftmaxLayer::validate(&aclInputInfo, &aclOutputInfo, descriptor.m_Beta, aclAxis);
                                                                                                 ^
cc1plus: all warnings being treated as errors
make[2]: *** [src/backends/neon/workloads/CMakeFiles/armnnNeonBackendWorkloads.dir/build.make:544: src/backends/neon/workloads/CMakeFiles/armnnNeonBackendWorkloads.dir/NeonSoftmaxBaseWorkload.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1653: src/backends/neon/workloads/CMakeFiles/armnnNeonBackendWorkloads.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Should I go through installation of boost etc again or is something else causing this? 

Output of `g++ -v`

> $ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-linux-gnu/7.3.0/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release -with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,fortran,lto --enable-plugin --enable-initfini-array --disable-libgcj --without-isl --without-cloog --enable-gnu-indirect-function --build=aarch64-linux-gnu --with-stage1-ldflags=' -Wl,-z,relro,-z,now' --with-boot-ldflags=' -Wl,-z,relro,-z,now' --with-multilib-list=lp64
Thread model: posix
gcc version 7.3.0 (GCC) 

Thanks!

**Comment by MatthewARM** [comment]
NeonSoftmaxWorkload.cpp has been changed a bit over the last few months. If you are on older code I'd suggest updating to the v20.05 release code (both Compute Library and Arm NN) and trying again.

Specifically, I think the warning you are seeing was fixed in efc5da41

**Comment by GalMoore** [comment]
Thanks @MatthewARM with the help of [this tutorial](https://en.opensuse.org/Arm_NN) and the explanations above got it to work now. Thanks again.

**Comment by MatthewARM** [comment]
Thanks @GalMoore and that is a pretty awesome tutorial. We should probably link to it from the Readme.  

Closing this issue, don't hesitate to open a new one if you have any more problems.
