### ISSUE TITLE
cross compile arm nn tensorflow lite for ZCU104

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#386]
What libraries do I need to install for cross compiling arm nn for ZCU104 platform and Tensorflow Lite? The OS is petalinux. Can I just follow the procedure https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/cross-compiling-arm-nn-for-the-raspberry-pi-and-tensorflow/single-page?

**Comment by MikeJKelly** [comment]
Yes, that should be enough, that guide lists the libraries that are required to cross build armnn.

**Comment by ivs-pychen** [comment]
Thanks for your reply. I'll try it.

**Comment by MikeJKelly** [comment]
Hi @ivs-pychen 

thinking about it a bit more I think you may have better luck with the armnn crossbuild guide at https://github.com/ARM-software/armnn/blob/master/BuildGuideCrossCompilation.md

**Comment by nikraj01** [comment]
Hi @ivs-pychen ,
Do you still face this issue?
Thanks

**Comment by ivs-pychen** [comment]
I didn't use cross compile. I directly build Arm NN on my device.
