### ISSUE TITLE
cross compiling error when build the Arm NN for tensorflow lite

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#387]
I follow the steps in https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/cross-compiling-arm-nn-for-the-raspberry-pi-and-tensorflow/single-page to cross compile the Arm NN. 
But I got the following error
[ 49%] Linking CXX shared library libarmnn.so
/home/ivslab/armnn-zcu104/ComputeLibrary/build/libarm_compute_core-static.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
CMakeFiles/armnn.dir/build.make:3577: recipe for target 'libarmnn.so.20.02' failed
make[2]: *** [libarmnn.so.20.02] Error 1
CMakeFiles/Makefile2:118: recipe for target 'CMakeFiles/armnn.dir/all' failed
make[1]: *** [CMakeFiles/armnn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

And the following is my cmake 
cmake .. -DCMAKE_LINKER=/usr/bin/arm-linux-gnueabihf-ld -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ -DCMAKE_C_COMPILER_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-mfpu=neon -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build -DBOOST_ROOT=$BASEDIR/boost -DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf -DBUILD_TF_LITE_PARSER=1 -DPROTOBUF_ROOT=$BASEDIR/protobuf-arm -DARMCOMPUTENEON=1 -DARMNNREF=1 -DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers -DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers/libflatbuffers.a -DTF_LITE_GENERATED_PATH=$BASEDIR/tensorflow/tensorflow/lite/schema

Is the command for cmake incorrect for tensorflow lite?

**Comment by MikeJKelly** [comment]
Hi @ivs-pychen 

thinking about it a bit more I think you may have better luck with the armnn crossbuild guide at https://github.com/ARM-software/armnn/blob/master/BuildGuideCrossCompilation.md 

The raspberry pi guide mentions building compute library for an earlier architecture (armv7a) but your device has a more recent one so you should be using something more like (arm64-v8a)

**Comment by nikraj01** [comment]
Hi @ivs-pychen ,
Were you able to cross compile successfully?
Thanks

**Comment by ivs-pychen** [comment]
I didn't use cross compile. I directly build Arm NN on my device.
