### ISSUE TITLE
Arm NN TfLite parser accepts illegal TfLite files

### ISSUE THREAD

**Issue by MatthewARM** [ARM-software/armnn#388]
In https://www.tensorflow.org/lite/performance/quantization_spec it's documented for several operators that "restriction: Input and outputs must all have same scale/zero_point". We're not checking  that in the Arm NN TfLite parser, so we'll pass through the net into Arm NN, and then most likely the backends will reject the operator. Should we be stricter on input?

**Comment by james-conroy-arm** [comment]
Hi @MatthewARM ,

There is now a patch in review for this: https://review.mlplatform.org/c/ml/armnn/+/3456.

I will let you know once it's merged.

Cheers,
J.

**Comment by james-conroy-arm** [comment]
Hi @MatthewARM ,

The patch has now merged, thanks for reporting this issue.

We will close this issue soon, if you don't have any other questions regarding it.

Cheers,
James

**Comment by MatthewARM** [comment]
Thanks
