### ISSUE TITLE
Is there any way to run armnn format model with pyarmnn?

### ISSUE THREAD

**Issue by wangg** [ARM-software/armnn#389]
I think I need an IDeserializer to parse armnn format model, but it seems like that IDeserializer is not exposed in the Python interface while all other parsers are? I want to test the quantization of armnn, which I think only works with armnn format models, and pyarmnn is preferred since I can test things really fast with it. Please let me know if I missed something.

**Comment by Colm-in-Arm** [comment]
Hi Guanqun,

Strangely enough the answer is no. We have interfaces for Caffe, TF, Onnx and TfLite but not for our de-serializer. I'll talk to some people and see if it is something we're planning on adding. 

In the meantime if you'd like to contribute a SWIG wrapper for it we can help you.

Colm.

**Comment by wangg** [comment]
Hi Colm,

If nobody is planning on this, I would like to have a try. One thing I am concerned about is that IDeseiralizer does not have a CreateNetworkFromBinaryFile method like other parsers. I am just wondering if it is necessary to implement one before making a SWIG wrapper?

Wang

**Comment by Colm-in-Arm** [comment]
Hi Wang,

There's no immediate plan to implement this but it has been recognized as a something we'd like to add. We would welcome your contribution. 

In the case of IDeserializer no special handling is required around reading the binary file. It's done directly before the network is de-serialized. Have a look at InferenceModel.hpp under tests. The ARMNN_SERIALIZER template starting around line 170 reads the file and passes it directly to CreateNetworkFromBinary.

`std::ifstream file(params.m_ModelPath, std::ios::binary);
 network = parser->CreateNetworkFromBinary(file);`

I'm not familiar with SWIG but I presume you can read a binary file in python and pass it directly into CreateNetworkFromBinary.

Colm.

**Comment by wangg** [comment]
@macenpav Thanks for the advice. I have been playing around with my own armnn_deserializer.i for a little while. One problem I noticed is that the current cmake configuration does not build a shared lib for deserializer. For now I just modifed CMakeLists to build one which will be used by SWIG later. I am just wondering if this is the only way to do it?

**Comment by MatthewARM** [comment]
Changing CMakeLists.txt to build a shared lib for the Deserializer sounds correct to me. There's no reason not to make it a shared library similar to the other parser front-ends.

**Comment by wangg** [comment]
I just submitted a change on Gerrit (https://review.mlplatform.org/c/ml/armnn/+/3841), but it looks like armnn32-ci-build failed because the master branch of ArmNN depends on a different version of ComputeLibrary than the building script is using. Should I do something to the change I submitted, or should I just wait for further review by others?

My apologies if I am asking in a wrong place.

**Comment by Colm-in-Arm** [comment]
That's very strange. It looks like the Linaro CI is building a combination of ArmNN master + patch and CL 20.05. ScaleKernelInfo has been added since that release, hence the build error. I'm not familiar with the Linaro CI setup. I'll fire off a question.

We'll hold off on your patch anyway as the ArmNN 20.08 release is due any day now. There might be some rework required to keep up to date with PyArmnn.

Colm

**Comment by Colm-in-Arm** [comment]
I got some feedback from the Linaro CI people. They've temporarily disabled the armnn32-ci-build until this problem is solved.

Can you re-trigger by maybe updating the commit message and pushing again. We'll see what happens.

Colm.

**Comment by K1504296** [comment]
Hey Colm and wangg,

I'm responsible for the ArmNN Linaro CI. Sorry for the issues with the 32 bit armnn ,I'm currently looking into it. In the meantime a patch has just gone live which will disable reporting from the 32 bit armnn build to review.mlplatfrom.org

Theo

**Comment by wangg** [comment]
My patch has been merged into the mainline.
