### ISSUE TITLE
Performance on Cortex-A53 (Galaxy S7)

### ISSUE THREAD

**Issue by mobicham** [ARM-software/armnn#39]
Hi,
I am running some benchmarks to see how Arm NN performs on the CPU and GPU and I am noticing something a bit strange. 
I am using the Galaxy S7 (Cortex-A53 / Mali-T880) for the benchmark, as well as a OnePlus 3 (Snapdragon 820, I know it's not an Arm chip but I was just curious to see what happens since I know the performance of the same model using TFMobile, TFLite and Qualcomm SNPE (GPU mode) on that device).
Everything is running on Android as follows: image reading/resizing is done on Android, the float array version of the image is passed to a JNI/C++ interface that returns predictions, then the predictions are parsed in Java. So basically every prediction call is like this:
```cpp
//Parse image data from Java
 armnn_status = runtime.get()->EnqueueWorkload(networkIdentifier,
                                                       MakeInputTensors(inputBindingInfo, input_cpp),
                                                       MakeOutputTensors(outputBindingInfo_prediction, 
                                                       &output_prediction_cpp[0]));
//Return predicitons to Java
```
#### ArmNN CpuAcc mode (Galaxy S7)
The first predictions are quite fast, then suddenly it becomes much slower. Here's the detailed log in the form <prediction time> (<image count>) on the app start:
> 99 ms (1/35)
69 ms (2/35)
70 ms (3/35)
74 ms (4/35)
73 ms (5/35)
69 ms (6/35)
69 ms (7/35)
70 ms (8/35)
68 ms (9/35)
73 ms (10/35)
78 ms (11/35)
90 ms (12/35)
94 ms (13/35)
83 ms (14/35)
78 ms (15/35)
83 ms (16/35)
72 ms (17/35)
77 ms (18/35)
89 ms (19/35)
232 ms (20/35)
256 ms (21/35)
252 ms (22/35)
346 ms (23/35)
247 ms (24/35)
242 ms (25/35)
310 ms (26/35)
271 ms (27/35)
295 ms (28/35)
260 ms (29/35)
338 ms (30/35)
295 ms (31/35)
296 ms (32/35)
271 ms (33/35)
269 ms (34/35)
297 ms (35/35)

In fact, it becomes ridiculously slow after longer runs: 

> 429 ms (249/256)
405 ms (250/256)
412 ms (251/256)
2605 ms (252/256)
3960 ms (253/256)
4117 ms (254/256)
4155 ms (255/256)
3925 ms (256/256)

#### ArmNN GpuAcc mode (Galaxy S7)
Processing is pretty stable on the GPU as you can see but becomes slightly slower after the first runs (for the sake of comparison, the same architecture runs at a stable ~30ms/img on the OnePlus3 using the SNPE SDK): 
> 123 ms (1/35)
57 ms (2/35)
57 ms (3/35)
56 ms (4/35)
54 ms (5/35)
55 ms (6/35)
54 ms (7/35)
54 ms (8/35)
53 ms (9/35)
54 ms (10/35)
54 ms (11/35)
55 ms (12/35)
58 ms (13/35)
62 ms (14/35)
65 ms (15/35)
62 ms (16/35)
80 ms (17/35)
66 ms (18/35)
62 ms (19/35)
57 ms (20/35)
81 ms (21/35)
59 ms (22/35)
87 ms (23/35)
62 ms (24/35)
57 ms (25/35)
64 ms (26/35)
62 ms (27/35)
75 ms (28/35)
57 ms (29/35)
62 ms (30/35)
75 ms (31/35)
74 ms (32/35)
59 ms (33/35)
64 ms (34/35)
58 ms (35/35)

#### TFMobile (OnePlus 3)
Processing is stable on the CPU using TFMobile on the OnePlus 3: 
> 167 ms (1/35)
93 ms (2/35)
96 ms (3/35)
107 ms (4/35)
93 ms (5/35)
93 ms (6/35)
93 ms (7/35)
94 ms (8/35)
93 ms (9/35)
90 ms (10/35)
94 ms (11/35)
97 ms (12/35)
91 ms (13/35)
90 ms (14/35)
89 ms (15/35)
93 ms (16/35)
91 ms (17/35)
91 ms (18/35)
93 ms (19/35)
96 ms (20/35)
100 ms (21/35)
88 ms (22/35)
92 ms (23/35)
93 ms (24/35)
92 ms (25/35)
92 ms (26/35)
94 ms (27/35)
85 ms (28/35)
89 ms (29/35)
93 ms (30/35)
91 ms (31/35)
87 ms (32/35)
92 ms (33/35)
89 ms (34/35)
87 ms (35/35)

#### ArmNN CpuAcc mode (OnePlus 3)
Stable processing at around ~100ms/img and pretty good performance compared to TFMobile even-though the chip is not ARM:  
> 181 ms (1/35)
101 ms (2/35)
117 ms (3/35)
147 ms (4/35)
112 ms (5/35)
105 ms (6/35)
103 ms (7/35)
101 ms (8/35)
107 ms (9/35)
102 ms (10/35)
103 ms (11/35)
104 ms (12/35)
114 ms (13/35)
135 ms (14/35)
136 ms (15/35)
107 ms (16/35)
103 ms (17/35)
102 ms (18/35)
115 ms (19/35)
101 ms (20/35)
102 ms (21/35)
103 ms (22/35)
102 ms (23/35)
103 ms (24/35)
100 ms (25/35)
106 ms (26/35)
100 ms (27/35)
103 ms (28/35)
102 ms (29/35)
104 ms (30/35)
99 ms (31/35)
105 ms (32/35)
100 ms (33/35)
100 ms (34/35)
103 ms (35/35)

So the question is why ArmNN becomes slower on the Cortex-A53 after several runs? Anyone experienced something similar on other Arm chips? 

Thanks a lot in advance, 
Kind regards,

**Comment by Surmeh** [comment]
Hi @mobicham 

As the ArmNN SDK is performing good on one device and not on another, it could be a system/hardware related factor impacting the performance, e.g: thermal throttling, dynamic frequency scaling, ddrfreq etc.

Have you set the CPU frequency to a specific value or its dynamically allocating it? I would suggest checking the temperature and the frequency of the device while its performing inference. It might be the device is reaching its peak temperature and giving strange results.

I hope this helps,
Surabhi

**Comment by Surmeh** [comment]
Hi @mobicham,

Were you able to dig deeper into the inference runs?  Please get back in touch if you require any further help.

Best regards,
Surabhi

**Comment by mobicham** [comment]
Hi @Surmeh,

Sorry for my late response. I tried Tensorflow mobile on the same device and got the same behaviour, so I guess it's a throttling issue with the Galaxy S7. Weird, I tested many different devices to run deep nets on device and this is the first time I see something like that. 

Thank you very much again for your assistance, I will close the issue. 
Kind regards,
Hicham
