### ISSUE TITLE
How to restrict number of cores used by CNN Inference ?

### ISSUE THREAD

**Issue by darshjp** [ARM-software/armnn#390]
Hi,

I am using ARMNN v20.02 on iMX8x platfrom. It has 4 A35 core. By default, When I run any network using `runtime->EnqueueWorkload `API with `CpuAcc`, It uses all 4 cores. Is there a way to customize this ? I want to restrict it to 2 cores only as customer applications runs on other two cores.

I guess, `arm_compute::IScheduler` has API `set_num_threads`  but I am not sure if it's available at ARMNN RunTime API level.

Thanks,
Darshan

**Comment by MikeJKelly** [comment]
Hi 

as you say setup_backend_context is not available through the ArmNN runtime API level but you should be able to control the number of threads by doing something like:

```
#include <arm_compute/runtime/Scheduler.h>
arm_compute::Scheduler::get().set_num_threads(2);
```
