### ISSUE TITLE
Convolution2d: input and weights types mismatched while running yolov3tiny.tflite

### ISSUE THREAD

**Issue by krBarma** [ARM-software/armnn#394]
Hi,

I am using ARMNN v20.02 on the S32V234 vision processor, getting below error while running quantized yolov3tiny.tflie on ubuntu as well. Mobilenet example is running properly.
./tests/TfLiteYoloV3Big-Armnn /Downloads/armnn-temp/yoloweights/ /Downloads/armnn-temp/yoloweights/
Info: ArmNN v21.0.0

Info: Initialization time: 0.07 ms

Info: Loading backbone...
Debug: Model loaded ok: /home/cll/Downloads/armnn-temp/yoloweights/yolov3_1080_1920_backbone_int8.tflite
Warning: WARNING: Layer of type Convolution2d is not supported on requested backend CpuRef for input data type Float32 and output data type Float32 (reason: Reference Convolution2d: input and weights types mismatched.
), falling back to the next backend.
Warning: ERROR: Layer of type Convolution2d is not supported on any preferred backend [CpuAcc CpuRef ]
Fatal: Could not optimize the model:/home/cll/Downloads/armnn-temp/yoloweights/yolov3_1080_1920_backbone_int8.tflite
Info: Shutdown time: 0.00 ms

**Comment by james-conroy-arm** [comment]
Hi @krBarma ,

Many of the test applications in armnn/tests, including TfLiteYoloV3Big-Armnn, require the use of models that have been internally optimized by Arm and are not available publicly.

We are currently working on ways to provide a better solution to this situation.

Cheers,
James

**Comment by james-conroy-arm** [comment]
Hi @krBarma ,

Since we have not heard back from you in a while and the issue appears to be resolved now, we are going to close this issue.

Please let us know if this is being closed in error, or feel free to open a new issue if another one should arise.

Cheers,
James
