### ISSUE TITLE
Need yolov3tiny test example with .tflite files

### ISSUE THREAD

**Issue by krBarma** [ARM-software/armnn#395]
Hi,

Can you please provide test example for yolov3tiny with int8 and float .tflite files.

Thanks.

**Comment by james-conroy-arm** [comment]
Hi @krBarma ,

Many of the test applications in armnn/tests require the use of models that have been internally optimized by Arm and are not available publicly.

We are currently working on ways to provide a better solution to this situation.

Cheers,
James

**Comment by james-conroy-arm** [comment]
Hi @krBarma ,

Since we have not heard back from you in a while and the issue appears to be resolved now, we are going to close this issue.

Please let us know if this is being closed in error, or feel free to open a new issue if another one should arise.

Cheers,
James
