### ISSUE TITLE
GEMM operator

### ISSUE THREAD

**Issue by xinchenhawaii** [ARM-software/armnn#399]
Linear gemm operator issues. ARMNN doesn't support linear gemm operator. However, it is a widely used function. Could you support it ?

**Comment by MatthewARM** [comment]
Hi @xinchenhawaii it could be possible. There hasn't been much demand for it so far as there's no GEMM operator in TfLite or NNAPI which are the front-ends where we have best coverage. Could you explain how you're using it, and how you are using the Arm NN API? Which parsers would you need it in or are you using the Arm NN graph API directly?

**Comment by xinchenhawaii** [comment]
Hi Matthew,

Nice to hear back from you. I just began to use the ONNX parser. However,
this parser supported fewer operators than tflite and TF.

When we use nn.linear in pytorch, which is widely used layer in
classification, it will be converted to GEMM in ONNX. Without it, most of
models trained by pytorch can't be used in armnn. I have rewrite nn.linear
as  weight*transpose(input)+bias. But onnx parser don't support transpose
as well. As a result, I tired to add transpose layer in onnxparser by
myself. But it failed. If you can help to do so, I'd like to contribute
this part to the project. Also, I will contribute more in the future
because we are utilizing ARMNN to build our compiler.

my code is following:

void OnnxParser::ParserTranspose(const onnx::NodeProto& node)
{
    //CHECK_VALID_SIZE(static_cast<size_t>(node.input_size()), 1);
    std::cout<<static_cast<size_t>(node.input_size())<<std::endl;
    std::cout<<"Transpose Parser"<<std::endl;
    TransposeDescriptor desc = TransposeDescriptor();
    std::cout<<"Create Desc"<<std::endl;

    std::cout<<node.name().c_str()<<std::endl;
    IConnectableLayer* layer = m_Network->AddTransposeLayer(desc, node.name
().c_str());
    if (layer != nullptr)
        std::cout<<"Create layers"<<std::endl;

    //auto outputInfo = ComputeOutputInfo({node.output(0)}, layer,
{inputShape});
    layer->GetOutputSlot(0).SetTensorInfo(outputInfo[0]);

    RegisterInputSlots(layer, {node.input(0)});
    RegisterOutputSlots(layer, {node.output(0)});
    std::cout<<"Complete Transpose Layer"<<std::endl;
}

I will to follow (Deserializer.cpp line 2902-2923)

void Deserializer::ParseTranspose(GraphPtr graph, unsigned int layerIndex)
{
CHECK_LAYERS(graph, 0, layerIndex);

auto dimsMapping = graph->layers()->Get(layerIndex)->layer_as_TransposeLayer
()->descriptor()->dimMappings();

auto inputs = GetInputs(graph, layerIndex);
CHECK_VALID_SIZE(inputs.size(), 1);

auto outputs = GetOutputs(graph, layerIndex);
CHECK_VALID_SIZE(outputs.size(), 1);
auto outputInfo = ToTensorInfo(outputs[0]);

auto layerName = GetLayerName(graph, layerIndex);
const armnn::TransposeDescriptor descriptor(armnn::PermutationVector
(dimsMapping->data(), dimsMapping->Length()));

IConnectableLayer* layer = m_Network->AddTransposeLayer(descriptor,
layerName.c_str());
layer->GetOutputSlot(0).SetTensorInfo(outputInfo);

RegisterInputSlots(graph, layerIndex, layer);
RegisterOutputSlots(graph, layerIndex, layer);
}

Obviously, I don't know how to get dimsMapping from onnx::NodeProto. Could
you let me know how to do in onnxparser like auto dimsMapping = graph->
layers()->Get(layerIndex)->layer_as_TransposeLayer()->descriptor()->
dimMappings();?


Sincerely,

Xin

**Comment by MatthewARM** [comment]
Hi @xinchenhawaii thanks for this information, it's great to hear that that you can contribute and I hope we can help.

I think the attribute you need is called `perm' in the ONNX transpose layer: https://github.com/onnx/onnx/blob/master/docs/Operators.md#Transpose

So you'll need something like this in OnnxParser::ParseTranspose (I've not tried any of this):

```
std::vector<uint32_t> perm = ReadOptionalNodeUint32ListAttribute(node, "perm")
if (perm.empty())
  <default to reversing the dimensions>
else
  <convert perm to dimMappings>
```

Hope that helps,
Matthew

**Comment by xinchenhawaii** [comment]
Hi Matthew,

Thank you for your answer. I finish my ParserTranspose code as following:

void OnnxParser::ParserTranspose(const onnx::NodeProto& node)
{
   
    std::vector<uint32_t> perm = ReadOptionalNodeUint32ListAttribute(node, "perm");
    if (perm.empty())
    {
        std::cout<<"New disc"<<std::endl;
    }
    else
    {
        
        TensorShape inputShape = m_TensorsInfo[node.input(0)].m_info->GetShape();
        
        const TransposeDescriptor desc(PermutationVector(perm.data(), perm.size()));
        IConnectableLayer* layer = m_Network->AddTransposeLayer(desc, node.name().c_str());
        auto outputInfo = ComputeOutputInfo({node.output(0)}, layer, {inputShape});
        layer->GetOutputSlot(0).SetTensorInfo(outputInfo[0]);

        RegisterInputSlots(layer, {node.input(0)});
        RegisterOutputSlots(layer, {node.output(0)});
        std::cout<<"Complete Transpose Layer"<<std::endl;
    }
}

perm is right [1,0]. However, when I load the graph, there is the other error,terminate called after throwing an instance of 'armnn::ParseException'
  what():  One of the input tensors ('465' or '467') should be constant in node ''  
at function AddFullyConnected  in GetInputAndParam(matmulNode, &inputName, &weightName, CHECK_LOCATION()) in void OnnxParser::AddFullyConnected(const onnx::NodeProto& matmulNode, const onnx::NodeProto* addNode)

Any suggestion?

**Comment by ChenBoSyun** [comment]
> Hi @xinchenhawaii it could be possible. There hasn't been much demand for it so far as there's no GEMM operator in TfLite or NNAPI which are the front-ends where we have best coverage. Could you explain how you're using it, and how you are using the Arm NN API? Which parsers would you need it in or are you using the Arm NN graph API directly?

Hope to hear the news about supporting GEMM. 
I have the same problem when using Onnx parser to parse pytorch classification model.
I think it is a widely used function.
Many thanks

**Comment by jokerspy** [comment]
Hi, I met the same problem that GEMM is not supported when using ONNX parser and I see you mentioned the workaround using transpose operator. Do you have any update either about GEMM or transpose operator? Thanks

**Comment by xinchenhawaii** [comment]
Not yet now.

**Comment by matthewsloyanARM** [comment]
Hi @xinchenhawaii,

Thank you for reaching out! Support for GEMM and Transpose in Arm NN ONNX Parser is currently on our backlog however there is no ETA at the moment when this will be implemented. We would much appreciate your contributions to add these operators though.

In reply to the error below you are seeing at a first glance it looks like model you are using has non constant Weights or Biases for the FullyConnected layer. This isn't supported in the ONNX Parser. 

```
what(): One of the input tensors ('465' or '467') should be constant in node ''
at function AddFullyConnected in GetInputAndParam(matmulNode, &inputName, &weightName, CHECK_LOCATION()) in void OnnxParser::AddFullyConnected(const onnx::NodeProto& matmulNode, const onnx::NodeProto* addNode)
```

As this is an old issue and based on the updated `README.md` found [here](https://github.com/ARM-software/armnn/tree/master#how-to-get-involved) under the "How to get involved" section I will close this issue as it is labeled with "Feature Request". Instead, we will be tracking the issue and adding the "Help wanted" label. All the issues with this label can be found [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). If you would like to continue to add the Transpose operator mentioned above free to reopen this ticket and let us know you are still working on it with a quick comment. We will then track the updates and help you get your additions into our codebase.

Below you will find our contributors guide which will show you how you can submit a patch to us. If you have any questions feel free to ask here or by creating a new Issue, thank you!

https://www.mlplatform.org/contributing

Kind regards,

Matthew
