### ISSUE TITLE
Build ArmNN error

### ISSUE THREAD

**Issue by mathpopo** [ARM-software/armnn#400]
@MatthewARM i also meet this issue
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ CXX=aarch64-linux-android-clang++ CC=aarch64-linux-android-clang CXX_FLAGS="-fPIE -fPIC" cmake .. -DCMAKE_ANDROID_NDK=$NDK -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=27 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_EXE_LINKER_FLAGS="-pie -llog -lz" -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1 -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/
-- Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain ''
-- The C compiler identification is Clang 8.0.7
-- The CXX compiler identification is Clang 8.0.7
-- Check for working C compiler: /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- broken
CMake Error at /usr/local/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
The C compiler

_"/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"_

_**is not able to compile a simple test program.**_

It fails with the following output:

Change Dir: /home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_e23db/fast && /usr/bin/make -f CMakeFiles/cmTC_e23db.dir/build.make CMakeFiles/cmTC_e23db.dir/build
make[1]: Entering directory '/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e23db.dir/testCCompiler.c.o
/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains//prebuilt/linux-x86_64 --sysroot=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/sysroot  -isystem /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/sysroot/usr/include -isystem /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/sysroot/usr/include/aarch64-linux-android  -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=27 -fexceptions  -g -fPIE   -o CMakeFiles/cmTC_e23db.dir/testCCompiler.c.o   -c /home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_e23db
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e23db.dir/link.txt --verbose=1
/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains//prebuilt/linux-x86_64 --sysroot=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/platforms/android-27/arch-arm64 -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=27 -fexceptions  -g  -Wl,--gc-sections  CMakeFiles/cmTC_e23db.dir/testCCompiler.c.o  -o cmTC_e23db 
/usr/bin/ld: unrecognised emulation mode: aarch64linux
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/cmTC_e23db.dir/build.make:86: recipe for target 'cmTC_e23db' failed
make[1]: *** [cmTC_e23db] Error 1
make[1]: Leaving directory '/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_e23db/fast' failed
make: *** [cmTC_e23db/fast] Error 2

CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeOutput.log".
See also "/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeError.log".
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ aarch64-linux-android-clang++
clang++: error: no input files
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ aarch64-linux-android-clang
clang: error: no input files

**Comment by mathpopo** [comment]
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ aarch64-linux-android-clang
clang: error: no input files
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ aarch64-linux-android-clang++
clang++: error: no input files

**Comment by mathpopo** [comment]
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ which aarch64-linux-android-clang
/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-clang
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ which aarch64-linux-android-clang++
/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-clang++

**Comment by mathpopo** [comment]
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn$ git log .
commit 42ce2484624c7e81e08811f48b2ce6b930b2d949 (HEAD -> branches/armnn_20_02, origin/branches/armnn_20_02)
Author: nikraj01 <44364373+nikraj01@users.noreply.github.com>
Date:   Thu Apr 16 16:44:16 2020 +0100

    Update README.md

commit 983f360ecd131451ea8d2c8cbb2685e5bf847725
Author: nikraj01 <44364373+nikraj01@users.noreply.github.com>
Date:   Thu Apr 16 16:42:18 2020 +0100

    Update README.md

**Comment by MatthewARM** [comment]
Looks like cmake is bombing out very early, it can't even detect how to run the compiler properly.

@mathpopo which OS and which versionof cmake are you using?

@nikraj01 which version of cmake do we use for testing the Android NDK build instructions?

**Comment by nikraj01** [comment]
We use cmake 3.16

**Comment by MatthewARM** [comment]
Ah, looks like @mathpopo uses 3.15 which is close and should be fine.

**Comment by MatthewARM** [comment]
I think that the issue is that CC and CXX are set to `aarch64-linux-android-clang
clang` and `aarch64-linux-android-clang++`. i think an API level should be in there somewhere.

**Comment by MatthewARM** [comment]
@mathpopo I think you need to change your CC and CXX settings to:

`CXX=aarch64-linux-android21-clang++ CC=aarch64-linux-android21-clang`

This corresponds to the `<Android_API>` bit in the instructions at https://github.com/ARM-software/armnn/blob/branches/armnn_20_05/BuildGuideAndroidNDK.md

**Comment by mathpopo** [comment]
@MatthewARM  firstly thank you for your support, my env:OS:UBUNTU18.04 CMAKE:3.15.0-rc4
ndk:
/llvm/prebuilt/linux-x86_64/bin$ ll /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-clang
lrwxrwxrwx 1 root root 29 6月   9 09:17 /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-clang -> aarch64-linux-android21-clang*
@nikraj01 hi,could you tell me your env?


(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ CXX=aarch64-linux-android21-clang++ \
> CC=aarch64-linux-android21-clang \
> CXX_FLAGS="-fPIE -fPIC" \
> cmake .. \
>     -DCMAKE_ANDROID_NDK=$NDK \
>     -DCMAKE_SYSTEM_NAME=Android \
>     -DCMAKE_SYSTEM_VERSION=21 \
>     -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
>     -DCMAKE_EXE_LINKER_FLAGS="-pie -llog -lz" \
>     -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
>     -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
>     -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
>     -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 \
>     -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1 \
>     -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/
-- Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain ''
-- The C compiler identification is Clang 8.0.7
-- The CXX compiler identification is Clang 8.0.7
-- Check for working C compiler: /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- broken
CMake Error at /usr/local/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_24775/fast && /usr/bin/make -f CMakeFiles/cmTC_24775.dir/build.make CMakeFiles/cmTC_24775.dir/build
    make[1]: Entering directory '/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_24775.dir/testCCompiler.c.o
    /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains//prebuilt/linux-x86_64 --sysroot=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/sysroot  -isystem /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/sysroot/usr/include -isystem /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/sysroot/usr/include/aarch64-linux-android  -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=27 -fexceptions  -g -fPIE   -o CMakeFiles/cmTC_24775.dir/testCCompiler.c.o   -c /home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_24775
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_24775.dir/link.txt --verbose=1
    /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains//prebuilt/linux-x86_64 --sysroot=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/platforms/android-27/arch-arm64 -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=27 -fexceptions  -g  -Wl,--gc-sections  CMakeFiles/cmTC_24775.dir/testCCompiler.c.o  -o cmTC_24775 
    /usr/bin/ld: unrecognised emulation mode: aarch64linux
    Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_24775.dir/build.make:86: recipe for target 'cmTC_24775' failed
    make[1]: *** [cmTC_24775] Error 1
    make[1]: Leaving directory '/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_24775/fast' failed
    make: *** [cmTC_24775/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeOutput.log".
See also "/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeError.log".

**Comment by mathpopo** [comment]
(base) chenxin@Nitro-AN515:~/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin$ ./clang
clang: error: no input files
(base) chenxin@Nitro-AN515:~/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin$ ll ./clang
-rwxr-xr-x 1 chenxin chenxin 57468480 10月 17  2019 ./clang*

**Comment by mathpopo** [comment]
@MatthewARM 
because :
(base) chenxin@Nitro-AN515:~/armnn-devenv/ComputeLibrary$ scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC"  benchmark_tests=0 validation_tests=0 os=android -j16
scons: Reading SConscript files ...
ERROR: Compiler ' aarch64-linux-android-clang++' not found


so i ln -s aarch64-linux-android21-clang++ aarch64-linux-android-clang++

**Comment by mathpopo** [comment]
@MatthewARM 

do as https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideAndroidNDK.md


CXX=aarch64-linux-android-clang++ \
>  CC=aarch64-linux-android-clang \
>  CXX_FLAGS="-fPIE -fPIC" \
>  cmake .. \
>   -DCMAKE_SYSTEM_NAME=Android \
>   -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
>   -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$HOME/armnn-devenv/toolchains/aarch64-android-r17b/ \
>   -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
>   -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
>   -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
>   -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
>   -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 \
>   -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1 \
>   -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/



[100%] Linking CXX executable UnitTests
[100%] Built target UnitTests

**Comment by mathpopo** [comment]
but 
-DSAMPLE_DYNAMIC_BACKEND=1 \
-DDYNAMIC_BACKEND_PATHS=$SAMPLE_DYNAMIC_BACKEND_PATH

cannot search libArm_SampleDynamic_backend.so

**Comment by mathpopo** [comment]
if git checkout branches/armnn_20_02  also compile errror

**Comment by mathpopo** [comment]
if git checkout branches/armnn_20_02  also compile errror

**Comment by nikraj01** [comment]
Hi @mathpopo ,

If you have built with -DSAMPLE_DYNAMIC_BACKEND=1, you must have set a working dir for the dynamic sample backend to get build (for example /armnn/src/dynamic/sample/build/). This is where you will find the  libArm_SampleDynamic_backend.so. I hope this helps. Please let me know if you have any issues.
Thanks
