### ISSUE TITLE
ModelProto class problem

### ISSUE THREAD

**Issue by xinchenhawaii** [ARM-software/armnn#401]
I am working on writing ONNXParser new layer Transpose following Deserializer.cpp 

void Deserializer::ParseTranspose(GraphPtr graph, unsigned int layerIndex)
{
    CHECK_LAYERS(graph, 0, layerIndex);

    auto dimsMapping = graph->layers()->Get(layerIndex)->layer_as_TransposeLayer()->descriptor()->dimMappings();

    auto inputs = GetInputs(graph, layerIndex);
    CHECK_VALID_SIZE(inputs.size(), 1);

    auto outputs = GetOutputs(graph, layerIndex);
    CHECK_VALID_SIZE(outputs.size(), 1);
    auto outputInfo = ToTensorInfo(outputs[0]);

    auto layerName = GetLayerName(graph, layerIndex);
    const armnn::TransposeDescriptor descriptor(armnn::PermutationVector(dimsMapping->data(), dimsMapping->Length()));

    IConnectableLayer* layer = m_Network->AddTransposeLayer(descriptor, layerName.c_str());
    layer->GetOutputSlot(0).SetTensorInfo(outputInfo);

    RegisterInputSlots(graph, layerIndex, layer);
    RegisterOutputSlots(graph, layerIndex, layer);
}

in modelProto, how do I can do the same thing as raph->layers()->Get(layerIndex)->layer_as_TransposeLayer()->descriptor()->dimMappings();. Then I can create my armnn::TransposeDescriptor for AddTransposeLayer. 

BTW, any document to explain modelProto?

Thank you very much!

**Comment by MatthewARM** [comment]
Hi @xinchenhawaii I've answered the specific question about dimMappings in a reply to Issue #399. 

In general:

Deserializer.cpp is for parsing .armm files using the protobuf schema defined at armnn/src/armnnSerializer/ArmnnSchema.fbs. You can use that as an example of how to create Arm NN layers, but you will need to have different code for reading and parsing the ONNX files.

modelProto is a pointer to a `onnx::ModelProto` object. The definition of that is in the ONNX protobuf schema here: https://github.com/onnx/onnx/blob/925b3657924c0c16cd20b54595f41e76159b03ab/onnx/onnx.proto#L320 and gets converted into a C++ object by the protobuf library. You can see the documentation for that here: https://developers.google.com/protocol-buffers/docs/cpptutorial

Hope that helps,
Matthew

**Comment by FrancisMurtagh-arm** [comment]
Closing due to age and inactivity.
