### ISSUE TITLE
ArmNN on Mac OS - Unit Tests Fail with Boost

### ISSUE THREAD

**Issue by l-oneil** [ARM-software/armnn#402]
Hello, 

I had an issue regarding the compilation of ArmNN on Mac OS environment and I wanted to document this somewhere to help anyone experiencing the issue in future. 

I ran into an issue when compiling ArmNN on Mac OS where the unit tests were failing with issues such as: 
`libgatordMockService.a(CommandLineProcessor.cpp.o): In function boost::program_options::basic_command_line_parser<char>::extra_parser(boost::function1<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&>):`

I managed to isolate this issue to the compilation of the Boost libraries. The issue for me was that the boost `b2` tool appears to have a bug were it defaults to using the native `ranlib` even when specifying the correct tool in the user_config.jam. 

You can validate that this issue is occurring by inspecting the boost build log, I was seeing warnings like so:
`warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: warning for library: bin.v2/libs/atomic/build/clang-darwin-android/release/link-static/threading-multi/libboost_atomic.a the table of contents is empty (no object file members in the library define global symbols)`

The issue with a manual fix has been captured in this (not so easily findable) [issue](https://github.com/boostorg/build/issues/160). 

I have implemented an automated fix for this in [this shell script](https://gist.github.com/l-oneil/686f23b2fa1e003912382538eb646850). 

Hope this helps any Mac Users who struggled like me :)

**Comment by Colm-in-Arm** [comment]
Hi @l-oneil 

Thanks for your contribution. I'll see if we can add this to the FAQ document.

Colm.

**Comment by FrancisMurtagh-arm** [comment]
Closing as the FAQs have since been updated.

Thanks again.
Francis.
