### ISSUE TITLE
Anyone tested TfLiteYoloV3Big-Armnn code ?

### ISSUE THREAD

**Issue by vnn0804** [ARM-software/armnn#403]
Hello,
If anyone test above example please give me .tflite file and help me how to run above demo code

**Comment by james-conroy-arm** [comment]
Hi @vnn0804 ,

Many of the test applications in armnn/tests, including TfLiteYoloV3Big-Armnn, require the use of models that have been internally optimized by Arm and are not available publicly.

We are currently working on ways to provide a better solution to this situation.

Cheers,
James

**Comment by james-conroy-arm** [comment]
Hi @vnn0804 ,

Since we have not heard back from you in a while and the issue appears to be resolved now, we are going to close this issue.

Please let us know if this is being closed in error, or feel free to open a new issue if another one should arise.

Cheers,
James
