### ISSUE TITLE
Tensorflow C3D model

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#406]
I want to implement a Tensorflow C3D model through Arm NN. And I convert the Tensorflow C3D model to Tensorflow Lite format. But the model will contain Tensorflow and Tensorflow lite operation. Does the Arm NN can implement a model contain both the Tensorflow and Tensorflow lite operation?
And does Arm NN can support Tensorflow C3D operation?

**Comment by MikeJKelly** [comment]
Hi @ivs-pychen 

ArmNN does not support the Convolution 3D or max pool 3D operators. They are not currently on our roadmap. 

Best regards,
Mike

**Comment by james-conroy-arm** [comment]
Hi @ivs-pychen ,

If you don't have any other questions relating to this issue, could you close it please?

Cheers,
James
