### ISSUE TITLE
SampleDynamic_backend.so not exist

### ISSUE THREAD

**Issue by mathpopo** [ARM-software/armnn#408]
do as https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideAndroidNDK.md
add -DSAMPLE_DYNAMIC_BACKEND=1 \
-DDYNAMIC_BACKEND_PATHS=$SAMPLE_DYNAMIC_BACKEND_PATH

(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ CXX=aarch64-linux-android-clang++ \
>  CC=aarch64-linux-android-clang \
>  CXX_FLAGS="-fPIE -fPIC" \
>  cmake .. \
>   -DCMAKE_SYSTEM_NAME=Android \
>   -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
>   -DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$HOME/armnn-devenv/toolchains/aarch64-android-r17b/ \
>   -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
>   -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
>   -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
>   -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
>   -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 \
>   -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1 \
>   -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install -DSAMPLE_DYNAMIC_BACKEND=1 -DDYNAMIC_BACKEND_PATHS=~/armnn-devenv/armnn/build
-- Android: Targeting API '26' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- The C compiler identification is Clang 6.0.2
-- The CXX compiler identification is Clang 6.0.2
-- Check for working C compiler: /home/chenxin/armnn-devenv/toolchains/aarch64-android-r17b//bin/clang
-- Check for working C compiler: /home/chenxin/armnn-devenv/toolchains/aarch64-android-r17b//bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/chenxin/armnn-devenv/toolchains/aarch64-android-r17b//bin/clang++
-- Check for working CXX compiler: /home/chenxin/armnn-devenv/toolchains/aarch64-android-r17b//bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   filesystem
--   program_options
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for valgrind/memcheck.h
-- Looking for valgrind/memcheck.h - not found
-- Caffe parser support is disabled
-- Tensorflow Lite parser support is disabled
-- Armnn Serializer support is disabled
-- ArmNN Quantizer support is disabled
-- PyArmNN wheel package is disabled
-- PyArmNN source package is disabled
-- Including backend common library into the build: /home/chenxin/armnn-devenv/armnn/src/backends/aclCommon/common.cmake
-- Including backend common library into the build: /home/chenxin/armnn-devenv/armnn/src/backends/backendsCommon/common.cmake
-- Including backend into the build: /home/chenxin/armnn-devenv/armnn/src/backends/cl/backend.cmake
-- Including backend into the build: /home/chenxin/armnn-devenv/armnn/src/backends/neon/backend.cmake
-- Including backend into the build: /home/chenxin/armnn-devenv/armnn/src/backends/reference/backend.cmake
-- Adding object library dependency to armnn: armnnAclCommon
-- Adding object library dependency to armnn: armnnBackendsCommon
-- Adding object library dependency to armnn: armnnClBackend
-- Adding object library dependency to armnn: armnnClBackendWorkloads
-- Adding object library dependency to armnn: armnnNeonBackend
-- Adding object library dependency to armnn: armnnNeonBackendWorkloads
-- Adding object library dependency to armnn: armnnRefBackend
-- Adding object library dependency to armnn: armnnRefBackendWorkloads
-- Adding object library dependency to UnitTests: armnnAclCommonUnitTests
-- Adding object library dependency to UnitTests: armnnBackendsCommonUnitTests
-- Adding object library dependency to UnitTests: armnnClBackendUnitTests
-- Adding object library dependency to UnitTests: armnnNeonBackendUnitTests
-- Adding object library dependency to UnitTests: armnnRefBackendUnitTests
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chenxin/armnn-devenv/armnn/build

[100%] Linking CXX shared module Arm_CpuRef_backend.so
[100%] Built target Arm_CpuRef_backend

but (base) chenxin@Nitro-AN515:~/armnn-devenv/armnn$ find ./ -name "*SampleDynamic_backend.so*"  ---which no!

**Comment by nikraj01** [comment]
Hi @mathpopo ,
What you should be looking for is libArm_SampleDynamic_backend.so. 
Thanks
