### ISSUE TITLE
ARM-NN for Caffe SDK : build error in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by KimonoYan** [ARM-software/armnn#41]
Hi, =v=
I tried to build armnn environment in **Ubuntu 18.04 LTS**. In the meantime, I set up in accordance with the official Step-by-Step manual. No errors occurred, and every step was tested as far as possible until the last step(cd armnn/; cmake & make).

Here is my configurations and build environment version
Version
cmake：   3.10.1
scons：			2.4.1
boost：			1.64.0		1.67.0(tested)
protobuf：		3.5.1		        3.6.0(tested)
armnn：			18.05.02		18.05(tested)
CROSS_CPMPILE：	gcc-linaro-arm-linux-gnueabihf-4.9-2014.07_linux
caffe：			        1.0.0                 (sudo apt install caffe-cpu)
ComputeLibrary

Hardware
	ARMv7-A(CPU-Only)

Configure the Arm NN SDK build using CMake
![image](http://chuantu.biz/t6/341/1531448969x-1404817629.png)

Executing cmake ... seems OK
![image](http://chuantu.biz/t6/341/1531449074x-1404755468.png)

But a fatal error occured when **make -j32**
![image](http://chuantu.biz/t6/341/1531449968x-1404755468.png)

make stop
![image](http://chuantu.biz/t6/341/1531450221x-1404755468.png)

Can you tell me where the problem is? Thank you QvQ

**Comment by MatteoArm** [comment]
Hi @KimonoYan,

The cmake step looks fine to me, although I see you are using a newer version of cmake than I do (we use cmake 3.7.2).
Maybe more recent versions of cmake are pickier these days and report the syntax of `GetDataTypeName` in TypesUtils.hpp as invalid (by missing a proper return statement at the end).
Can you try changing `GetDataTypeName` as follows by adding a return statement at the end of it and see if it builds?

```
constexpr const char* GetDataTypeName(DataType dataType)
{
    switch (dataType)
    {
        case DataType::Float32:   return "Float32";
        case DataType::QuantisedAsymm8: return "Unsigned8";
        case DataType::Signed32:  return "Signed32";
        default:                  return "Unknown";
    }
    return "Unknown"; // <-- The change.
}
```

If the change above fixes your issue we may need to consider integrating it in future releases.
Let me know if that helped.

Regards

**Comment by KimonoYan** [comment]
First of all, let me express my thanks for your reply.

I have made the above modifications according to your suggestion, but the problem has not improved.
Besides, some of the other engineering documents I refer to on the web are using cmake 3.9.1 ,no errors were encountered in the build stage.

**Here's all the print information：**
In file included from /home/kimono/armNN_SDK/armnn-18.05/include/armnn/IRuntime.hpp:12:0,
                 from /home/kimono/armNN_SDK/armnn-18.05/src/armnn/backends/ClWorkloadFactory.hpp:9,
                 from /home/kimono/armNN_SDK/armnn-18.05/src/armnn/backends/ClWorkloadFactory.cpp:5:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In function ‘constexpr const char* armnn::GetStatusAsCString(armnn::Status)’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:26:1: error: body of constexpr function ‘constexpr const char* armnn::GetStatusAsCString(armnn::Status)’ not a return-statement
 }
 ^
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In function ‘constexpr const char* armnn::GetComputeDeviceAsCString(armnn::Compute)’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:38:1: error: body of constexpr function ‘constexpr const char* armnn::GetComputeDeviceAsCString(armnn::Compute)’ not a return-statement
 }
 ^
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In function ‘constexpr const char* armnn::GetActivationFunctionAsCString(armnn::ActivationFunction)’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:57:1: error: body of constexpr function ‘constexpr const char* armnn::GetActivationFunctionAsCString(armnn::ActivationFunction)’ not a return-statement
 }
 ^
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In function ‘constexpr const char* armnn::GetPoolingAlgorithmAsCString(armnn::PoolingAlgorithm)’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:69:1: error: body of constexpr function ‘constexpr const char* armnn::GetPoolingAlgorithmAsCString(armnn::PoolingAlgorithm)’ not a return-statement
 }
 ^
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In function ‘constexpr const char* armnn::GetOutputShapeRoundingAsCString(armnn::OutputShapeRounding)’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:81:1: error: body of constexpr function ‘constexpr const char* armnn::GetOutputShapeRoundingAsCString(armnn::OutputShapeRounding)’ not a return-statement
 }
 ^
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In function ‘constexpr const char* armnn::GetPaddingMethodAsCString(armnn::PaddingMethod)’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:93:1: error: body of constexpr function ‘constexpr const char* armnn::GetPaddingMethodAsCString(armnn::PaddingMethod)’ not a return-statement
 }
 ^
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In function ‘constexpr unsigned int armnn::GetDataTypeSize(armnn::DataType)’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:105:1: error: body of constexpr function ‘constexpr unsigned int armnn::GetDataTypeSize(armnn::DataType)’ not a return-statement
 }
 ^
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In instantiation of ‘constexpr bool armnn::StrEqual(const char*, const char (&)[N]) [with int N = 7]’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:120:31:   required from here
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:116:1: error: body of constexpr function ‘constexpr bool armnn::StrEqual(const char*, const char (&)[N]) [with int N = 7]’ not a return-statement
 }
 ^
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In function ‘constexpr armnn::Compute armnn::ParseComputeDevice(const char*)’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:136:1: error: body of constexpr function ‘constexpr armnn::Compute armnn::ParseComputeDevice(const char*)’ not a return-statement
 }
 ^
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp: In function ‘constexpr const char* armnn::GetDataTypeName(armnn::DataType)’:
/home/kimono/armNN_SDK/armnn-18.05/include/armnn/TypesUtils.hpp:148:1: error: body of constexpr function ‘constexpr const char* armnn::GetDataTypeName(armnn::DataType)’ not a return-statement
 }
 ^
CMakeFiles/armnn.dir/build.make:62: recipe for target 'CMakeFiles/armnn.dir/src/armnn/backends/ClWorkloadFactory.cpp.o' failed
make[2]: *** [CMakeFiles/armnn.dir/src/armnn/backends/ClWorkloadFactory.cpp.o] Error 1
CMakeFiles/Makefile2:174: recipe for target 'CMakeFiles/armnn.dir/all' failed
make[1]: *** [CMakeFiles/armnn.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MatteoArm** [comment]
Ignore my previous suggestion, your problem seems to be that your compiler doesn't support C++14 properly.
Specifically, `constexpr` is available since gcc 5, have a look at the standard here: https://gcc.gnu.org/projects/cxx-status.html#cxx14 (at "Relaxing requirements on constexpr functions").
I would suggest that you update the compiler and retry.

**Comment by Surmeh** [comment]
Hi @KimonoYan,

I hope your issue is resolved now. Please open a new one if you are still having problems.

Thanks,
Surabhi
