### ISSUE TITLE
resnext_TF_quantized_for_armnn_team.pb is not available

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#416]
While trying to run `TfResNext-Armnn` I get an error because `resnext_TF_quantized_for_armnn_team.pb` is not available.
Where could I find this file? Could you make it part of the sources, if not publicly available, please?

**Comment by james-conroy-arm** [comment]
Hi @ggardet ,

Many of the test applications in armnn/tests, including TfResNext-Armnn, require the use of models that have been internally optimized by Arm and are not available publicly.

We are currently working on ways to provide a better solution to this situation.

Cheers,
James

**Comment by james-conroy-arm** [comment]
Hi @ggardet ,

Since we have not heard back from you in a while and the issue appears to be resolved now, we are going to close this issue.

Please let us know if this is being closed in error, or feel free to open a new issue if another one should arise.

Cheers,
James

**Comment by ggardet** [comment]
Nothing is resolved since  `resnext_TF_quantized_for_armnn_team.pb` is not available publicly.
