### ISSUE TITLE
Porting armnn to android

### ISSUE THREAD

**Issue by pcub** [ARM-software/armnn#42]
Hello,
I am following the https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md
to compile armnn on android. However, it does not work in last part ('Build ArmNN:")

Then I created bash files (based on https://github.com/sh1r0/caffe-android-lib)
and here is my cmake command line options in build_armnn.sh:

```
CXX_FLAGS="-fPIE -fPIC"
export CC=${PROJECT_DIR}/toolchain/aarch64-linux-android-ndk-r16b/bin/aarch64-linux-android-clang
export CXX=${PROJECT_DIR}/toolchain/aarch64-linux-android-ndk-r16b/bin/aarch64-linux-android-clang++

cmake \
-DCMAKE_TOOLCHAIN_FILE="/opt/android-ndk-r16b/build/cmake/android.toolchain.cmake" \
-DCMAKE_SYSTEM_NAME=Android \
-DBOOST_ROOT="${PROJECT_DIR}/boost/boost_1_64_0/install" \
-DBoost_LIBRARY_DIR="${PROJECT_DIR}/boost/boost_1_64_0/install/lib" \
-DBoost_INCLUDE_DIR="${PROJECT_DIR}/boost/boost_1_64_0/install/include" \
-DCMAKE_EXE_LINKER_FLAGS=-pie \
-DANDROID_ABI="${ANDROID_ABI}" \
-DANDROID_NDK="${NDK_ROOT}" \
-DANDROID_NATIVE_API_LEVEL="${API_LEVEL}" \
-DARMCOMPUTE_ROOT="{ACLDIR}" \
-DARMCOMPUTE_INCLUDE="${ACLDIR}" \
-DARMCOMPUTE_CORE_LIBRARY_RELEASE="${ACL_LIBS_DIR}/libarm_compute_core-static.a" \
-DARMCOMPUTE_LIBRARY_RELEASE="${ACL_LIBS_DIR}/libarm_compute-static.a" \
-DARMCOMPUTE_CORE_LIBRARY_DEBUG="${ACL_LIBS_DIR}/libarm_compute_core-static.a" \
-DARMCOMPUTE_LIBRARY_DEBUG="${ACL_LIBS_DIR}/libarm_compute-static.a" \
-DARMCOMPUTENEON=1 \
-DARMCOMPUTECL=1 \
-DBUILD_CAFFE_PARSER=0 \
-DBUILD_TF_PARSER=1 \
-DTF_GENERATED_SOURCES="${PROJECT_DIR}/google/tf_pb/" \
-DPROTOBUF_ROOT="${PROJECT_DIR}/google/arm64_pb_install/" \
-DOPENCL_INCLUDE="${ACLDIR}/include" \
-DOPENCL_LIBRARIES="${ACL_LIBS_DIR}/libOpenCL.so" \
-DHALF_INCLUDE="${ACLDIR}/include" \
-DBUILD_UNIT_TESTS=0 \
-DPROJECT_DIR="${PROJECT_DIR}" ..

make -j11
```
But compiler gives bunch of errors depending on cmake options (e.g., with and without *android.toolchain.cmake), for example:

```
armnn_android/armnn/src/armnn/SerializeLayerParameters.cpp:57:17: error: no member named
      'to_string' in namespace 'std'
    fn("A",std::to_string(desc.m_A));

```

Have you guys compiled like me?

Also, when I add -DBUILD_UNIT_TESTS=1, there are lot of undefined reference related linking errors on some cpp and libarmnn.so files.

How to compile armnn properly?

**Comment by MatteoArm** [comment]
Hi @pcub, when you say that step "Build ArmNN" doesn't work, are you referring to this linking issue #35 ? Or is it a different problem?

**Comment by MatteoArm** [comment]
To add to my previous comment, ArmNN builds fine for me with the following (there's most likely an error in the documentation):

```
CXX=aarch64-linux-android-clang++ \
 CC=aarch64-linux-android-clang \
 CXX_FLAGS="-fPIE -fPIC" \
 cmake .. \
  -DCMAKE_SYSTEM_NAME=Linux \
  -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
  -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
  -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
  -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
  -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 \
  -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1 \
  -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/
```

With the following env variables set:
`NDK=$HOME/armnn-devenv/toolchains/android-ndk-r16b`
`PATH=$HOME/armnn-devenv/toolchains/aarch64-android-r16b/bin:$PATH`

My base project dir is $HOME/armnn-devenv and both aarch64-linux-android-clang and aarch64-linux-android-clang++ are found on PATH (as they are in $HOME/armnn-devenv/toolchains/aarch64-android-r16b)

Also, there's no need to specify -DBUILD_UNIT_TESTS=1, as they are built by default anyway.

**Comment by Surmeh** [comment]
Hi @pcub,

I hope you were able to resolve your problem following Matteo's instructions. Please get back in touch if you have more problems.

Thanks,
Surabhi
