### ISSUE TITLE
 /system/bin/sh: ./UnitTests: No such file or directory

### ISSUE THREAD

**Issue by mathpopo** [ARM-software/armnn#421]
https://github.com/ARM-software/armnn/issues/411

i do the same with 411 from Adreno (TM) 506 to Mali-G71,but show error,is same operations
 need to modify?
 adb shell dumpsys | grep GLES
GLES: ARM, Mali-G71, OpenGL ES 3.2 v1.r14p0-00cet0.9500166da1423e9591394b068a52b758

**Comment by mathpopo** [comment]
/vendor/lib64 $ find ./ -name "*opencl*"
./libSR_opencl.so

**Comment by MatthewARM** [comment]
Hi @mathpopo is there any more information other than "No such file or directory"?

**Comment by MatthewARM** [comment]
Another thing is, it might be worth asking on the Arm Compute Library github project as they might know more about getting the GPU code running on different phones.

**Comment by mathpopo** [comment]
@MatthewARM 
HWMOA-M:/data/local/tmp/build $ strings libarm_compute.so | grep arm_compute_version
arm_compute_version=v20.05 Build options: {'embed_kernels': '1', 'opencl': '1', 'neon': '1', 'internal_only': '0', 'extra_cxx_flags': '-fPIC', 'arch': 'arm64-v8a'} Git hash=6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe
