### ISSUE TITLE
armnn file size is more

### ISSUE THREAD

**Issue by avanilkumar** [ARM-software/armnn#422]
A simple TF file with only 2 layers :
1. input of shape (1) 
 2. output layer.
The size of such .pb file is 90 bytes .
On converting to armnn file....the size of armnn file is 372 bytes

I observe that pb file size is much lesser than armnn file if it has more simple layers( with out tensors)...

**Comment by MatthewARM** [comment]
Hi @avanilkumar,

Do you expect this to cause a problem in practice?

It's not exactly a like-for-like comparison as the Tensorflow .pb file uses protobuf serialisation, whereas .armnn uses flatbuffers. There is some description of the difference here: https://codeburst.io/json-vs-protocol-buffers-vs-flatbuffers-a4247f8bda6f

The biggest advantage of using .armnn for a real-world deployment is that the compiled deserializer is about 500kb, whereas the parser for Tensorflow format is about 6MB.
