### ISSUE TITLE
ArmNN prebuild version

### ISSUE THREAD

**Issue by jnulzl** [ARM-software/armnn#424]
Could you release a prebuild version ??

**Comment by MatthewARM** [comment]
Hi @jnulzl we're planning to do this by providing Debian and Ubuntu packages. The first version going through the Debian testing system can be seen here: https://piuparts.debian.org/sid/source/a/armnn.html

**Comment by jnulzl** [comment]
> Hi @jnulzl we're planning to do this by providing Debian and Ubuntu packages. The first version going through the Debian testing system can be seen here: https://piuparts.debian.org/sid/source/a/armnn.html

Nice！Thanks！
