### ISSUE TITLE
ArmnnConverter  error

### ISSUE THREAD

**Issue by mathpopo** [ARM-software/armnn#428]
(base) chenxin@Nitro-AN515:~/Downloads/armnn-onnx/armnn/build$ ls
ArmnnConverter                  libarmnnSerializer.so.21
ArmnnQuantizer                  libarmnnSerializer.so.21.0
CMakeCache.txt                  libarmnn.so
CMakeFiles                      libarmnn.so.21
cmake_install.cmake             libarmnn.so.21.0
GatordMock                      libarmnnUtils.a
libarmnnBasePipeServer.so       libgatordMockService.a
libarmnnBasePipeServer.so.21    libtimelineDecoder.so
libarmnnBasePipeServer.so.21.0  libtimelineDecoder.so.21
libarmnnOnnxParser.so           libtimelineDecoder.so.21.0
libarmnnOnnxParser.so.21        Makefile
libarmnnOnnxParser.so.21.0      profiling
libarmnnQuantizer.so            samples
libarmnnQuantizer.so.21         src
libarmnnQuantizer.so.21.0       UnitTests
libarmnnSerializer.so

download   https://github.com/onnx/models/blob/master/vision/classification/mobilenet/model/mobilenetv2-7.onnx

(base) chenxin@Nitro-AN515:~/Downloads/armnn-onnx/armnn/build$ ./ArmnnConverter -f onnx-binary -m /home/chenxin/Downloads/ArmNN -i mobilenetv2-7.onnx -o /home/chenxin/Downloads/ArmNN -p mobilenetv2-7.armnn
Fatal: Failed to load model from file: The given model does not have any outputs  at function SetupOutputLayers [/home/chenxin/Downloads/armnn-onnx/armnn/src/armnnOnnxParser/OnnxParser.cpp:1683]

**Comment by mathpopo** [comment]
sorry ,it is a git LFS HEAD

**Comment by mathpopo** [comment]
(git-lfs) chenxin@Nitro-AN515:~/Downloads/models$ git lfs pull --include="*mobilenet*7*" --exclude=""

**Comment by mathpopo** [comment]
(base) chenxin@Nitro-AN515:~/Downloads/models/vision/classification/mobilenet/model$ ll
total 28344
drwxr-xr-x 3 chenxin chenxin     4096 7月  21 10:35 ./
drwxr-xr-x 3 chenxin chenxin     4096 6月  29 23:12 ../
drwxr-xr-x 5 chenxin chenxin     4096 6月  30  2018 mobilenetv2-1.0/
-rw-r--r-- 1 chenxin chenxin 14246826 7月  21 10:33 mobilenetv2-7.onnx
-rw-r--r-- 1 chenxin chenxin 14758284 7月  21 10:33 mobilenetv2-7.tar.gz


(base) chenxin@Nitro-AN515:~/Downloads/armnn-onnx/armnn/build$ ./ArmnnConverter -f onnx-binary -m /home/chenxin/Downloads/models/vision/classification/mobilenet/model/mobilenetv2-1.0 -i mobilenetv2-1.0.onnx -o mobilenetv2-1.0.armnn -p /home/chenxin/Downloads/models/vision/classification/mobilenet/model/mobilenetv2-1.0
Fatal: Failed to load model from file: The given model does not have any outputs  at function SetupOutputLayers [/home/chenxin/Downloads/armnn-onnx/armnn/src/armnnOnnxParser/OnnxParser.cpp:1683]

**Comment by mathpopo** [comment]
![Screenshot from 2020-07-21 10-39-04](https://user-images.githubusercontent.com/21274466/88006543-759f3380-cb3e-11ea-87fb-337f207a171f.png)

**Comment by mathpopo** [comment]
@MatthewARM  Is it the model have no output layer?

**Comment by mathpopo** [comment]
@MatthewARM  IT has output layer
![Screenshot from 2020-07-21 10-41-59](https://user-images.githubusercontent.com/21274466/88006711-e2b2c900-cb3e-11ea-8356-99620c8397c5.png)

**Comment by mathpopo** [comment]
(base) chenxin@Nitro-AN515:~/Downloads/armnn-onnx/armnn/build$ ./ArmnnConverter -f onnx-binary -m /home/chenxin/Downloads/models/vision/classification/mobilenet/model/mobilenetv2-1.0 -i mobilenetv2-1.0.onnx -s 1 3 224 224 -o mobilenetv2-1.0.armnn -p /home/chenxin/Downloads/models/vision/classification/mobilenet/model/mobilenetv2-1.0
Fatal: Failed to load model from file: The given model does not have any outputs  at function SetupOutputLayers [/home/chenxin/Downloads/armnn-onnx/armnn/src/armnnOnnxParser/OnnxParser.cpp:1683]

![Screenshot from 2020-07-21 10-44-25](https://user-images.githubusercontent.com/21274466/88006836-2c9baf00-cb3f-11ea-95ae-47c704fb201d.png)

**Comment by mathpopo** [comment]
void OnnxParser::SetupOutputLayers()
{
    if(m_Graph->output_size() == 0)
    {
        throw ParseException(boost::str(boost::format("The given model does not have any outputs %1%")
                                                      % CHECK_LOCATION().AsString()));
    }

**Comment by MikeJKelly** [comment]
Hi @mathpopo 

It looks like your inputs to the ArmnnConverter are incorrect. It's a very confusing error message though and is not at all helpful.
The -m parameter should be the path to the onnx file. 
The -i parameter should contain the names of the input layer.
The -o parameter should contain the names of the output layer.

So the command line for this model should look something like this: 

./ArmnnConverter -f onnx-binary -m /path/to/input/mobilenetv2-1.0.onnx -i data -o mobilenetv20_output_flatten0_reshape0 -p /path/to/output/mobilenetv2-1.0.armnn

Best regards,
Mike

**Comment by mathpopo** [comment]
@m

> Hi @mathpopo
> 
> It looks like your inputs to the ArmnnConverter are incorrect. It's a very confusing error message though and is not at all helpful.
> The -m parameter should be the path to the onnx file.
> The -i parameter should contain the names of the input layer.
> The -o parameter should contain the names of the output layer.
> 
> So the command line for this model should look something like this:
> 
> ./ArmnnConverter -f onnx-binary -m /path/to/input/mobilenetv2-1.0.onnx -i data -o mobilenetv20_output_flatten0_reshape0 -p /path/to/output/mobilenetv2-1.0.armnn
> 
> Best regards,
> Mike

very thank you ,it works
