### ISSUE TITLE
where to find the cross compile guide? 

### ISSUE THREAD

**Issue by fcyella** [ARM-software/armnn#43]
I didn't find it on this page, https://developer.arm.com/products/processors/machine-learning/arm-nn
or this one, https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides
Thanks very much

**Comment by MatteoArm** [comment]
Hi @fcyella, are you referring to https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md?
You should be able to adapt those instructions for other targets as you require.

**Comment by Surmeh** [comment]
Hi @fcyella,

I hope you've found the guide Matteo was referring to. Please open a new one if you have any problems.

Thanks,
Surabhi
