### ISSUE TITLE
Does Arm NN support tflite model converted from tensorflow1 or tensorflow2?

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#430]

**Comment by janeil01** [comment]
Hi @ivs-pychen,

ArmNN officially supports tensorflow1. Many models converted with tensorflow2 work as well. But the new tflite converter is causing issues in some special cases. We are working on a solution for that. 
Until we added a proper fix you can simply try running your model with our ExecuteNetwork app. You can find it in armnn/tests/ExecuteNetwork. 

If you need any further help don't hesitate to reach out for us again.

Jan

**Comment by ivs-pychen** [comment]
Does the Mobilenet-ssd and tiny yolov2 work well?

**Comment by janeil01** [comment]
Mobilnet-ssd should run fine. We have a test executing Mobilenet-ssd regularly.
We don't have a test for yolov2 tiny in place. But just from looking at the models operators it shouldn't cause problems.
However, if you want to be sure the best way is to try it out.

**Comment by dudqls1994** [comment]
Hello how to run yolov3 & mobilenet-SSD use  'armnn/tests/ExecuteNetwork'  


I found only mobilenet example in this repository :  ARMNN_ETHOSN_BACKEND_CONFIG_FILE=my_config.txt $BASEDIR/armnn/build/tests/ExecuteNetwork -f tflite-binary -i input -y qasymm8 -o MobilenetV1/Predictions/Reshape_1 -z qasymm8 -m /home/linaro/eval_platform_release_20_08/notebook/models/mobilenet_v1_1.0_224_quant.tflite -c EthosNAcc --parse-unsupported

**Comment by janeil01** [comment]
Hey @dudqls1994 

if you run ExecuteNetwork with the --help flag you will get a short explanation to all the parameters that you can use. The required parameters are:
```
-c or --compute
-f or --model-format
-m or --model-path
-i or --input-name
-o or --output-name
```
I personally like to use [netron](https://netron.app/) to determine the input and output names. It's a web app to view network models. It's also very handy to determine the input shapes if you require them as well. 

If you've got any more questions let me know. 
Jan
