### ISSUE TITLE
TFLite operations supported by Arm NN

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#431]
I want to know what TFLite operations are supported by Arm NN. Where can I find this information?

**Comment by janeil01** [comment]
Hey @ivs-pychen 

you can find a list of supported TfLite operators [here](https://github.com/ARM-software/armnn/tree/branches/armnn_20_05/src/armnnTfLiteParser) in the TensorflowLiteSupport.md file.

Jan
