### ISSUE TITLE
CreateNetworkFromBinaryFile :Need to have api which takes FILE* as input and return raw ptr instead of std::unique_ptr

### ISSUE THREAD

**Issue by ShailendraSSY** [ARM-software/armnn#434]
Details :
ARMNN Version :19.05
ACL Version : 19.05
OS :TIZEN
Parser : TLITE Parser
We are developing a system where we are using ARMNN api's for Neural Network inferencing.
ON analyzing the api's we have found that  following api of TfLiteParser
virtual armnn::INetworkPtr CreateNetworkFromBinaryFile(const char* graphFile) override;
takes only const char*.
In mycase we only have FILE* available where this api will be called.
Also the above API return's INetworkPtr which is std::unique_ptr but since we want to store the network pointer and use it only at the later point of time,hence we need a raw pointer.
**So we have following queries:**
1.)Is it possible to have api with signature as follows 
virtual armnn::INetwork* CreateNetworkFromBinaryFile(const char* graphFile) override;
2.)If not ,please suggest how can we use the current api as per requirement mentioned above.

**Comment by MikeJKelly** [comment]
Hi @ShailendraSSY 

There are two CreateNetworkFromBinaryFile functions one that takes the name of the file and another which takes a vector of uint8_t. That one looks more like what you need. You can read the contents of your file into a vector and pass it to the function:

`virtual armnn::INetworkPtr CreateNetworkFromBinary(const std::vector<uint8_t> & binaryContent) override;
`
If you want the raw pointer you can call release on the unique_ptr which will release ownership of the return the raw pointer. 

```
armnn::INetworkPtr uniquePtr = parser.CreateNetworkFromBinary(contents);
armnn::INetwork* ptr = uniquePtr.release();
```

Best regards,
Mike
