### ISSUE TITLE
ArmnnConverter Usage error.

### ISSUE THREAD

**Issue by liyanan-kinght** [ARM-software/armnn#435]
Hello
I am tring  converted tf model to armnn format model.
My compiler environment is ubuntu16.04.
My ARM device is Raspberry Pi 4 Model B.

./ArmnnConverter -f tflite-binary -m converted_model-cnn.tflite  -i input_x -s 1 150 40 1 -o labels_softmax -p test.armnn

Error: Failed to parse operator #0 within subgraph #0 error: Target 'shape' input is not a 1D tensor:  at function ParseReshape [/home/liyanan/armnn-pi/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:1984]
Fatal: Failed to load model from file: Buffer #23 has 0 bytes. For tensor: [1,150,40,1] expecting: 24000 bytes and 6000 elements.  at function CreateConstTensor [/home/liyanan/armnn-pi/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:3099]

Cross-compiling Arm NN for the Raspberry Pi and TensorFlow

mkdir armnn-pi && cd armnn-pi
export BASEDIR=`pwd`
Download the Compute Library, Boost, Protobuf, TensorFlow, ONNX, FlatBuffer, and Arm NN git repositories and source bundles. To download the repositories and bundles, enter the following commands:

git clone https://github.com/Arm-software/ComputeLibrary.git 
git clone https://github.com/Arm-software/armnn
wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2
tar xf boost_1_64_0.tar.bz2
git clone -b v3.5.0 https://github.com/google/protobuf.git
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow/
git checkout 590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b
git clone https://github.com/onnx/onnx.git 
cd onnx       
git fetch https://github.com/onnx/onnx.git f612532843bd8e24efeab2815e45b436479cc9ab && git checkout FETCH_HEAD
wget -O flatbuffers-1.10.0.tar.gz https://github.com/google/flatbuffers/archive/v1.10.0.tar.gz    
tar xf flatbuffers-1.10.0.tar.gz

cd $BASEDIR/ComputeLibrary
scons extra_cxx_flags="-fPIC -std=c++11" benchmark_tests=0 validation_tests=0  Werror=0 debug=0 asserts=0 neon=1 opencl=1 os=linux arch=armv7a examples=1 embed_kernels=1

cd $BASEDIR/boost_1_64_0/tools/build
./bootstrap.sh
Go to the $BASEDIR/boost_1_64_0/ directory and open the project-config.jam file in a text editor. In the GCC Configuration section, modif the following line:
using gcc : arm : arm-linux-gnueabihf-g++ ;
b2 --build-dir=$BASEDIR/boost_1_64_0/build toolset=gcc-arm link=static cxxflags=-fPIC --with-filesystem --with-test --with-log --with-program_options install --prefix=$BASEDIR/boost

cd $BASEDIR/protobuf
git submodule update --init --recursive
./autogen.sh
./configure --prefix=$BASEDIR/protobuf-host
make
make install
make clean

./configure --prefix=$BASEDIR/protobuf-arm --host=arm-linux CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ --with-protoc=$BASEDIR/protobuf-host/bin/protoc
make
make install

cd $BASEDIR/tensorflow
../armnn/scripts/generate_tensorflow_protobuf.sh ../tensorflow-protobuf ../protobuf-host

cd $BASEDIR/onnx

export LD_LIBRARY_PATH=$BASEDIR/protobuf-host/lib:$LD_LIBRARY_PATH        
$BASEDIR/protobuf-host/bin/protoc onnx/onnx.proto --proto_path=. --proto_path=$BASEDIR/protobuf-host/include --cpp_out=$BASEDIR/onnx 

cd flatbuffers-1.10.0         
rm -f CMakeCache.txt
rm -rf build
mkdir build
cd build
cmake .. \         
-DFLATBUFFERS_BUILD_FLATC=1 \               
-DCMAKE_INSTALL_PREFIX:PATH=$BASEDIR/flatbuffers
make all install

cd $BASEDIR/flatbuffers-1.10.0     
modify CMakeList add  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall  -Wno-missing-braces -Wconversion -Wsign-conversion -pthread") 
mkdir build-arm32
cd build-arm32
cmake .. -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc \         
-DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ \         
-DFLATBUFFERS_BUILD_FLATC=1 \         
-DCMAKE_INSTALL_PREFIX:PATH=$BASEDIR/flatbuffers-arm32 \        
-DFLATBUFFERS_BUILD_TESTS=0
make all install

cd $BASEDIR
mkdir tflite
cd tflite
cp $BASEDIR/tensorflow/tensorflow/lite/schema/schema.fbs .       
$BASEDIR/flatbuffers-1.10.0/build/flatc -c --gen-object-api --reflect-types --reflect-names schema.fbs

cd $BASEDIR/armnn

modify CMakeList add  
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall  -Wno-missing-braces -Wconversion -Wsign-conversion -pthread") 
SET(CMAKE_SYSTEM_NAME Linux)
    
mkdir build
cd build

build Armnn command:
cmake .. -DCMAKE_LINKER=arm-linux-gnueabihf-ld -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_C_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-mfpu=neon -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build -DBOOST_ROOT=$BASEDIR/boost -DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf -DBUILD_TF_PARSER=1 -DBUILD_ONNX_PARSER=1 -DONNX_GENERATED_SOURCES=$BASEDIR/onnx -DBUILD_TF_LITE_PARSER=1 -DTF_LITE_GENERATED_PATH=$BASEDIR/tflite -DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers-arm32 -DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers-arm32/lib/libflatbuffers.a -DFLATC_DIR=$BASEDIR/flatbuffers-1.10.0/build -DPROTOBUF_ROOT=$BASEDIR/protobuf-arm -DPROTOBUF_LIBRARY_DEBUG=$BASEDIR/protobuf-arm/lib/libprotobuf.so -DPROTOBUF_LIBRARY_RELEASE=$BASEDIR/protobuf-arm/lib/libprotobuf.so -DPROTOBUF_INCLUDE_DIRS=$BASEDIR/protobuf-arm/include -DBUILD_TESTS=1 -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 -DBUILD_ARMNN_SERIALIZER=1 -DBUILD_ARMNN_QUANTIZER=1 -DFLATC=$BASEDIR/flatbuffers-1.10.0/build/flatc 
make -j8

**Comment by janeil01** [comment]
Hey @liyanan-kinght 

would you mind trying it again with our armnn master branch? We added a [patch](https://review.mlplatform.org/c/ml/armnn/+/3563) just 2 weeks ago that should solve your problem.

Let me know if it worked 
Jan

**Comment by liyanan-kinght** [comment]
OK!  I will tring it again.

**Comment by liyanan-kinght** [comment]
> Hey @liyanan-kinght
> 
> would you mind trying it again with our armnn master branch? We added a [patch](https://review.mlplatform.org/c/ml/armnn/+/3563) just 2 weeks ago that should solve your problem.
> 
> Let me know if it worked
> Jan

Hello

I use armnn master branch. build armnn error.

build armnn command;

cmake .. -DCMAKE_LINKER=arm-linux-gnueabihf-ld -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_C_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-mfpu=neon -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build -DBOOST_ROOT=$BASEDIR/boost -DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf -DBUILD_TF_PARSER=1  -DBUILD_TF_LITE_PARSER=1 -DTF_LITE_GENERATED_PATH=$BASEDIR/tensorflow/tensorflow/lite/schema -DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers-arm32 -DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers-arm32/lib/libflatbuffers.a -DFLATC_DIR=$BASEDIR/flatbuffers/build -DPROTOBUF_ROOT=$BASEDIR/protobuf-arm -DPROTOBUF_LIBRARY_DEBUG=$BASEDIR/protobuf-arm/lib/libprotobuf.so -DPROTOBUF_LIBRARY_RELEASE=$BASEDIR/protobuf-arm/lib/libprotobuf.so -DPROTOBUF_INCLUDE_DIRS=$BASEDIR/protobuf-arm/include -DBUILD_TESTS=1 -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 -DBUILD_ARMNN_SERIALIZER=1 -DBUILD_ARMNN_QUANTIZER=1 -DFLATC=$BASEDIR/flatbuffers/build/flatc 

In file included from /home/liyanan/armnn-pi-last/armnn/src/backends/neon/NeonInterceptorScheduler.cpp:6:
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/NeonInterceptorScheduler.hpp:38:41: error: ‘InputTensorMap’ in namespace ‘arm_compute’ does not name a type
                      const arm_compute::InputTensorMap &inputs,
                                         ^~~~~~~~~~~~~~
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/NeonInterceptorScheduler.hpp:39:41: error: ‘OutputTensorMap’ in namespace ‘arm_compute’ does not name a type
                      const arm_compute::OutputTensorMap &outputs ) override;
                                         ^~~~~~~~~~~~~~~
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/NeonInterceptorScheduler.hpp:36:10: error: ‘void armnn::NeonInterceptorScheduler::schedule_op(arm_compute::ICPPKernel*, const arm_compute::IScheduler::Hints&, const int&, const int&)’ marked ‘override’, but does not override
     void schedule_op(arm_compute::ICPPKernel *kernel,
          ^~~~~~~~~~~
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/NeonInterceptorScheduler.cpp:57:63: error: ‘InputTensorMap’ in namespace ‘arm_compute’ does not name a type
                                            const arm_compute::InputTensorMap &inputs,
                                                               ^~~~~~~~~~~~~~
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/NeonInterceptorScheduler.cpp:58:63: error: ‘OutputTensorMap’ in namespace ‘arm_compute’ does not name a type
                                            const arm_compute::OutputTensorMap &outputs )
                                                               ^~~~~~~~~~~~~~~
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/NeonInterceptorScheduler.cpp: In member function ‘void armnn::NeonInterceptorScheduler::schedule_op(arm_compute::ICPPKernel*, const arm_compute::IScheduler::Hints&, const int&, const int&)’:
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/NeonInterceptorScheduler.cpp:62:21: error: ‘class arm_compute::IScheduler’ has no member named ‘schedule_op’; did you mean ‘schedule’?
     m_RealScheduler.schedule_op(kernel, hints, inputs, outputs);
                     ^~~~~~~~~~~
                     schedule
/home/liyanan/armnn-pi-last/armnn/src/backends/cl/workloads/ClResizeWorkload.cpp: In function ‘arm_compute::Status armnn::ClResizeWorkloadValidate(const armnn::TensorInfo&, const armnn::TensorInfo&, const armnn::ResizeDescriptor&)’:
/home/liyanan/armnn-pi-last/armnn/src/backends/cl/workloads/ClResizeWorkload.cpp:41:56: error: ‘ScaleKernelInfo’ is not a member of ‘arm_compute’
                                           arm_compute::ScaleKernelInfo(aclInterpolationPolicy,
                                                        ^~~~~~~~~~~~~~~
/home/liyanan/armnn-pi-last/armnn/src/backends/cl/workloads/ClResizeWorkload.cpp: In constructor ‘armnn::ClResizeWorkload::ClResizeWorkload(const armnn::ResizeQueueDescriptor&, const armnn::WorkloadInfo&)’:
/home/liyanan/armnn-pi-last/armnn/src/backends/cl/workloads/ClResizeWorkload.cpp:70:42: error: ‘ScaleKernelInfo’ is not a member of ‘arm_compute’
                             arm_compute::ScaleKernelInfo(aclInterpolationPolicy,
                                          ^~~~~~~~~~~~~~~
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/workloads/NeonResizeWorkload.cpp: In function ‘arm_compute::Status armnn::NeonResizeWorkloadValidate(const armnn::TensorInfo&, const armnn::TensorInfo&, const armnn::ResizeDescriptor&)’:
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/workloads/NeonResizeWorkload.cpp:41:56: error: ‘ScaleKernelInfo’ is not a member of ‘arm_compute’
                                           arm_compute::ScaleKernelInfo(aclInterpolationPolicy,
                                                        ^~~~~~~~~~~~~~~
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/workloads/NeonResizeWorkload.cpp:41:56: note: suggested alternative: ‘NEScaleKernel’
                                           arm_compute::ScaleKernelInfo(aclInterpolationPolicy,
                                                        ^~~~~~~~~~~~~~~
                                                        NEScaleKernel
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/workloads/NeonResizeWorkload.cpp: In constructor ‘armnn::NeonResizeWorkload::NeonResizeWorkload(const armnn::ResizeQueueDescriptor&, const armnn::WorkloadInfo&)’:
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/workloads/NeonResizeWorkload.cpp:72:42: error: ‘ScaleKernelInfo’ is not a member of ‘arm_compute’
                             arm_compute::ScaleKernelInfo(aclInterpolationPolicy,
                                          ^~~~~~~~~~~~~~~
/home/liyanan/armnn-pi-last/armnn/src/backends/neon/workloads/NeonResizeWorkload.cpp:72:42: note: suggested alternative: ‘NEScaleKernel’
                             arm_compute::ScaleKernelInfo(aclInterpolationPolicy,
                                          ^~~~~~~~~~~~~~~
                                          NEScaleKernel

In file included from /home/liyanan/my_git_new/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/8.3.0/vector:69,
                 from /home/liyanan/armnn-pi-last/armnn/src/armnn/Instrument.hpp:9,
                 from /home/liyanan/armnn-pi-last/armnn/src/backends/cl/OpenClTimer.hpp:8,
                 from /home/liyanan/armnn-pi-last/armnn/src/backends/cl/OpenClTimer.cpp:6:
/home/liyanan/my_git_new/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/8.3.0/bits/vector.tcc: In member function ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, double&, armnn::Measurement::Unit}; _Tp = armnn::Measurement; _Alloc = std::allocator<armnn::Measurement>]’:
/home/liyanan/my_git_new/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/8.3.0/bits/vector.tcc:413:7: note: parameter passing for argument of type ‘std::vector<armnn::Measurement>::iterator’ {aka ‘__gnu_cxx::__normal_iterator<armnn::Measurement*, std::vector<armnn::Measurement> >’} changed in GCC 7.1
       vector<_Tp, _Alloc>::
       ^~~~~~~~~~~~~~~~~~~
/home/liyanan/my_git_new/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/8.3.0/bits/vector.tcc: In member function ‘virtual std::vector<armnn::Measurement> armnn::OpenClTimer::GetMeasurements() const’:
/home/liyanan/my_git_new/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/8.3.0/bits/vector.tcc:109:4: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<armnn::Measurement*, std::vector<armnn::Measurement> >’ changed in GCC 7.1
    _M_realloc_insert(end(), std::forward<_Args>(__args)...);
    ^~~~~~~~~~~~~~~~~

**Comment by janeil01** [comment]
Sorry, I should have thought about this. Looks like your acl version doesn't match with armnn. When we release armnn we ensure that the same acl (arm compute library) version works with our version. So armnn_20.05 works with acl_20.05. But when you work with our master branch you'll have to check out a specific commit in acl that works with your current armnn master version. Here is how you can identify the right commit for acl:

In your armnn directory there is a folder called scripts. In scripts there is a script (who would have guessed that) that is called get_compute_library.sh. If you open that up with an editor of your choice, I used nano,
```
cd <rootdir>/armnn/scripts
nano get_compute_library.sh
```
you'll see on top of the file something like this:
```
# For pinning to a revision use this:
DEFAULT_CLFRAMEWORKREVISION="ad7515d231acb075a9585e52f257373b1a1b5d1f"
```
Copy the sha, in this case ad7515d231acb075a9585e52f257373b1a1b5d1f, then change to your acl directory and checkout the copied sha:
```
cd <rootdir>/arm_compute <-- I'm just guessing where your compute library is located, you won't be able to copy this command
git checkout ad7515d231acb075a9585e52f257373b1a1b5d1f
```
Now you can recompile arm compute library and armnn and it should work :+1:

**Comment by liyanan-kinght** [comment]
Hello  @janeil01

Thanks! I solved the problem. Thank you for your help. Many thanks!

**Comment by liyanan-kinght** [comment]
> Sorry, I should have thought about this. Looks like your acl version doesn't match with armnn. When we release armnn we ensure that the same acl (arm compute library) version works with our version. So armnn_20.05 works with acl_20.05. But when you work with our master branch you'll have to check out a specific commit in acl that works with your current armnn master version. Here is how you can identify the right commit for acl:
> 
> In your armnn directory there is a folder called scripts. In scripts there is a script (who would have guessed that) that is called get_compute_library.sh. If you open that up with an editor of your choice, I used nano,
> 
> ```
> cd <rootdir>/armnn/scripts
> nano get_compute_library.sh
> ```
> 
> you'll see on top of the file something like this:
> 
> ```
> # For pinning to a revision use this:
> DEFAULT_CLFRAMEWORKREVISION="ad7515d231acb075a9585e52f257373b1a1b5d1f"
> ```
> 
> Copy the sha, in this case ad7515d231acb075a9585e52f257373b1a1b5d1f, then change to your acl directory and checkout the copied sha:
> 
> ```
> cd <rootdir>/arm_compute <-- I'm just guessing where your compute library is located, you won't be able to copy this command
> git checkout ad7515d231acb075a9585e52f257373b1a1b5d1f
> ```
> 
> Now you can recompile arm compute library and armnn and it should work 👍
