### ISSUE TITLE
Cross-compiling Arm NN for the Raspberry Pi and TensorFlowLite . Failed to load model.

### ISSUE THREAD

**Issue by liyanan-kinght** [ARM-software/armnn#436]
Hello

My compiler environment is ubuntu16.04.
My ARM device is Raspberry Pi 4 Model B.

 libarmnnTfLiteParser.so ,Failed to load model.

my test code:

`#include`  `<iostream>`
#include  `<string>`
#include   `<cassert>`
#include   `<fstream>`
#include   `<vector>`
#include   `<array>`
#include   `<memory>`
#include   `<algorithm>`

#ifdef __cplusplus
extern "C"
{
#endif

#include <pthread.h>
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include <stdlib.h>
#include <math.h>
#ifdef __cplusplus
}
#endif

#include "armnn/ArmNN.hpp"
#include "armnn/Descriptors.hpp"
#include "armnn/Exceptions.hpp"
#include "armnn/Tensor.hpp"
#include "armnn/INetwork.hpp"
#include <armnn/IRuntime.hpp>
#include <armnn/Utils.hpp>
#include "armnnTfLiteParser/ITfLiteParser.hpp"

using namespace armnn;

int main(int argc,char *argv[])
{
													   
	armnnTfLiteParser::ITfLiteParserPtr parser = armnnTfLiteParser::ITfLiteParser::Create(); 
	//armnn::INetworkPtr pose_reg_network{nullptr, [](armnn::INetwork *){}};

	armnn::InputTensors pose_reg_in_tensors;
	armnn::OutputTensors pose_reg_ou_tensors;
	armnn::IRuntimePtr runtime{nullptr, [](armnn::IRuntime *){}};
	armnn::NetworkId networkIdentifier;
	armnn::IOptimizedNetworkPtr optNet{nullptr, [](armnn::IOptimizedNetwork *){}};;
	armnn::IRuntime::CreationOptions runtimeOptions;

	// loading tflite model
    std::string pose_reg_modelPath = "./converted_model_10cnn_float_v1.13.tflite";
	printf("load model begin\n");

	if(nullptr == parser)
	{
		printf("parser is null\n");
	}
	else
	{
		printf("parser not null\n");
	}
	
	
    armnn::INetworkPtr pose_reg_network = parser->CreateNetworkFromBinaryFile(pose_reg_modelPath.c_str());

	printf("load model end\n");
	

    return 0;
}

error info:
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Buffer #23 has 0 bytes. For tensor: [1,150,40,1] expecting: 24000 bytes and 6000 elements.  at function CreateConstTensor [/home/liyanan/armnn-pi/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:3099]
Aborted

Cross-compiling Arm NN for the Raspberry Pi and TensorFlowLite

mkdir armnn-pi && cd armnn-pi
export BASEDIR=pwd
Download the Compute Library, Boost, Protobuf, TensorFlow, ONNX, FlatBuffer, and Arm NN git repositories and source bundles. To download the repositories and bundles, enter the following commands:

git clone https://github.com/Arm-software/ComputeLibrary.git
git clone https://github.com/Arm-software/armnn
wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2
tar xf boost_1_64_0.tar.bz2
git clone -b v3.5.0 https://github.com/google/protobuf.git
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow/
git checkout 590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b
git clone https://github.com/onnx/onnx.git
cd onnx
git fetch https://github.com/onnx/onnx.git f612532843bd8e24efeab2815e45b436479cc9ab && git checkout FETCH_HEAD
wget -O flatbuffers-1.10.0.tar.gz https://github.com/google/flatbuffers/archive/v1.10.0.tar.gz
tar xf flatbuffers-1.10.0.tar.gz

cd $BASEDIR/ComputeLibrary
scons extra_cxx_flags="-fPIC -std=c++11" benchmark_tests=0 validation_tests=0 Werror=0 debug=0 asserts=0 neon=1 opencl=1 os=linux arch=armv7a examples=1 embed_kernels=1

cd $BASEDIR/boost_1_64_0/tools/build
./bootstrap.sh
Go to the $BASEDIR/boost_1_64_0/ directory and open the project-config.jam file in a text editor. In the GCC Configuration section, modif the following line:
using gcc : arm : arm-linux-gnueabihf-g++ ;
b2 --build-dir=$BASEDIR/boost_1_64_0/build toolset=gcc-arm link=static cxxflags=-fPIC --with-filesystem --with-test --with-log --with-program_options install --prefix=$BASEDIR/boost

cd $BASEDIR/protobuf
git submodule update --init --recursive
./autogen.sh
./configure --prefix=$BASEDIR/protobuf-host
make
make install
make clean

./configure --prefix=$BASEDIR/protobuf-arm --host=arm-linux CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ --with-protoc=$BASEDIR/protobuf-host/bin/protoc
make
make install

cd $BASEDIR/tensorflow
../armnn/scripts/generate_tensorflow_protobuf.sh ../tensorflow-protobuf ../protobuf-host

cd $BASEDIR/onnx

export LD_LIBRARY_PATH=$BASEDIR/protobuf-host/lib:$LD_LIBRARY_PATH
$BASEDIR/protobuf-host/bin/protoc onnx/onnx.proto --proto_path=. --proto_path=$BASEDIR/protobuf-host/include --cpp_out=$BASEDIR/onnx

cd flatbuffers-1.10.0
rm -f CMakeCache.txt
rm -rf build
mkdir build
cd build
cmake .. \
-G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=Release \
-DFLATBUFFERS_BUILD_FLATC=1 \
-DCMAKE_INSTALL_PREFIX:PATH=$BASEDIR/flatbuffers
make all install

cd $BASEDIR/flatbuffers-1.10.0
modify CMakeList add set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Wno-missing-braces -Wconversion -Wsign-conversion -pthread")
mkdir build-arm32
cd build-arm32
cmake ..   -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release\
-DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc \
-DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ \
-DFLATBUFFERS_BUILD_FLATC=1 \
-DCMAKE_INSTALL_PREFIX:PATH=$BASEDIR/flatbuffers-arm32 \
-DFLATBUFFERS_BUILD_TESTS=0
make all install

cd $BASEDIR
mkdir tflite
cd tflite
cp $BASEDIR/tensorflow/tensorflow/lite/schema/schema.fbs .
$BASEDIR/flatbuffers-1.10.0/build/flatc -c --gen-object-api --reflect-types --reflect-names schema.fbs

cd $BASEDIR/armnn

modify CMakeList add
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Wno-missing-braces -Wconversion -Wsign-conversion -pthread")
SET(CMAKE_SYSTEM_NAME Linux)

mkdir build
cd build

build Armnn command:
cmake .. -DCMAKE_LINKER=arm-linux-gnueabihf-ld -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_C_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-mfpu=neon -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build -DBOOST_ROOT=$BASEDIR/boost -DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf -DBUILD_TF_PARSER=1 -DBUILD_ONNX_PARSER=1 -DONNX_GENERATED_SOURCES=$BASEDIR/onnx -DBUILD_TF_LITE_PARSER=1 -DTF_LITE_GENERATED_PATH=$BASEDIR/tflite -DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers-arm32 -DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers-arm32/lib/libflatbuffers.a -DFLATC_DIR=$BASEDIR/flatbuffers-1.10.0/build -DPROTOBUF_ROOT=$BASEDIR/protobuf-arm -DPROTOBUF_LIBRARY_DEBUG=$BASEDIR/protobuf-arm/lib/libprotobuf.so -DPROTOBUF_LIBRARY_RELEASE=$BASEDIR/protobuf-arm/lib/libprotobuf.so -DPROTOBUF_INCLUDE_DIRS=$BASEDIR/protobuf-arm/include -DBUILD_TESTS=1 -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1 -DBUILD_ARMNN_SERIALIZER=1 -DBUILD_ARMNN_QUANTIZER=1 -DFLATC=$BASEDIR/flatbuffers-1.10.0/build/flatc
make -j8

**Comment by janeil01** [comment]
Hi @liyanan-kinght 

I tried to reproduce your error but it worked fine for me. What license is your model under? Is it possible for you to share or give me a link to it?

Jan

**Comment by liyanan-kinght** [comment]
> Hi @liyanan-kinght
> 
> I tried to reproduce your error but it worked fine for me. What license is your model under? Is it possible for you to share or give me a link to it?
> 
> Jan

Hello @janeil01

Thank you very much. I have solved the problem. Thank you for your help.  You helped me solve the problem in another ISSUE.
