### ISSUE TITLE
got segmentation fault in CreateNetworkFromBinaryFile(programOptions.modelPath.c_str()

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#438]
I got segmentation fault when running the following code.

using IParser = armnnTfLiteParser::ITfLiteParser;
auto armnnparser(IParser::Create());
armnn::INetworkPtr network = armnnparser->CreateNetworkFromBinaryFile(programOptions.modelPath.c_str());

**Comment by ivs-pychen** [comment]
I use TFLite model converted from TF2. Is this the possible cause for the segmentation fault?

**Comment by janeil01** [comment]
Hi @ivs-pychen 

Tf2 is not fully tested yet. But we don't expect any problems with it. 

What kind of model are you running? And could you post the full error message?
Also have you tried your code with a tf.1.15 model or with a different tf2 model? 

Jan

**Comment by ivs-pychen** [comment]
I run the Mobilenetv2 ssd. And I just got the Segmentation fault, no other error messages.
I tried other model from [tensorflow lite hosted models](https://www.tensorflow.org/lite/guide/hosted_models) and [tensorflow lite object detection](https://www.tensorflow.org/lite/models/object_detection/overview). And both of them can import the model.

Does the tf1.15 can be fully supported by Arm NN?

**Comment by janeil01** [comment]
Alright, I think I know what is going on. You have build acl in release. To make the code more efficient a lot of IsSupported tests are skipped in the release build. If you rebuild acl in debug mode you'll get more informative error messages. 

In mobilenet there is a hard_swish operator that is not supported by armnn_20.05. There is a similar ticket [here](https://github.com/ARM-software/armnn/issues/425). Not sure if MobilenetV2 ssd is any different. Best is to try it. All that you need should be mentioned in the other ticket. 

If you need any additional help let me know.
Jan

**Comment by ivs-pychen** [comment]
Do you mean I need to rebuild the acl?

**Comment by janeil01** [comment]
If you rebuild acl in debug it will give you more informative error messages. Also to build the armnn master branch you'll have to checkout the correct acl revision. After that you will have to rebuild acl.

To get the acl version that matches the armnn master branch, checkout the master branch in armnn and take a look at the following script:
```
nano armnn/scripts/get_compute_library.sh  # I use nano but you can use any text editor you like
```
You will find an entry in that file with the current revision of acl. Something like this::
```
# For pinning to a revision use this:
DEFAULT_CLFRAMEWORKREVISION="d6d1b3682a2cdd54bae5498635b108a4b19a045a" #COMPMID-37$
```
`cd` to your acl directory and `git checkout <DEFAULT_CLFRAMEWORKREVISION>` that revision. After, rebuild acl in debug mode. Finally, build armnn. It should all work now (And if not you'll get a more informative error message that you can bother me with :D ).

Let me know how it goes and good luck :+1:
