### ISSUE TITLE
build steps required for building ARMNN with ARM compiler. 

### ISSUE THREAD

**Issue by pradeepkrnik** [ARM-software/armnn#439]
Hi,
 Please provide the building steps to build the ARMNN with ARM compiler.
-thanks
Pradeep

**Comment by janeil01** [comment]
Hi @pradeepkrnik 

could you give me some insights on what you're trying to do? Do you just want to compile armnn for an arm architecture?

We've got a guide about [crosscompiling armnn](https://github.com/ARM-software/armnn/blob/branches/armnn_20_05/BuildGuideCrossCompilation.md). Have you already tried following that while passing your preferred compiler to the build commands? 

There are also more guides available on [developer.arm.com](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides) that might have some information of value to you.

Jan

**Comment by pradeepkrnik** [comment]
HI Jan,
 Thanks for coming back.
  Yes the goal is to mesaure the performance of ARMNN on ARM COMPILER vs GCC. 

 Yes I had looked into  crosscompiling armnn, is it something like every build listed in the cross compiling armnn we need to build with ARM COMPILER ? 
 boost lib,
 protobuf lib, 
 I could find the gcc compiler but for 
compute lib its with scons - i dont know how to mention the arm compiler here...

Any help would be appreciated.
Thanks
Pradeep

**Comment by janeil01** [comment]
`CC= CXX= scons` should work
