### ISSUE TITLE
stl gnustl and libc++

### ISSUE THREAD

**Issue by santo4ul** [ARM-software/armnn#44]
Hi,

I'm trying to compile ARM NN using Android toolchain (aarch64-linux-android-)

ACL recomends using "--stl gnustl" [here](https://arm-software.github.io/ComputeLibrary/latest/index.xhtml#S3_3_android)

ARM NN recommends using "--stl=libc++" [here](https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md)

Currently I have two standalone toolchains. One to build ACL (with gnustl), the other to build ARM NN using libc++.

Is this the right way to do? Would there be any conflicts with the final library/exec?  

Thanks,
San

**Comment by MatteoArm** [comment]
Hi @santo4ul, that would probably result in errors when linking ACL in ArmNN.
I'd recommend keeping the same stl for all component builds, or the same NDK toolchain entirely.

**Comment by MatteoArm** [comment]
I just noticed that you indeed have linker errors related to the stl version (#35).

**Comment by santo4ul** [comment]
Thanks MatteoArm.

The problem is, ACL recommends using gnustl with the following warning/attention. How do we go about it. We may endup with runtime errors, I'm not sure.

_Attention
Due to some NDK issues make sure you use clang++ & gnustl_

Thanks,
San

**Comment by MatteoArm** [comment]
I just spoke with the Compute Library team and they confirmed that they already have plans to switch to libc++ over gnustl, updating also to NDK r17.

Building everything with r16b and libc++ is ok for the time being.

**Comment by santo4ul** [comment]
Thank you @MatteoArm for the confirmation.
