### ISSUE TITLE
Which version of tensorflow1 or tensorflow2 can completely supported by Arm NN?

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#440]

**Comment by janeil01** [comment]
Hey @ivs-pychen 

Armnn20.05 supports tensorflow 1.15. In the context of your previous question I'm guessing you're asking about the TfLite parser. The TfLite parser in the current master branch should (not fully tested yet) also support tensorflow 2.1 models.

Jan

**Comment by ivs-pychen** [comment]
How do I know the Armnn version I installed?

**Comment by janeil01** [comment]
Go to the directory where you have downloaded armnn and do a git log
```
cd <root>/armnn
git log -1
```
Our default branch is armnn_20_05 right now. If you haven't changed anything your output should look something like this:
```
commit ea104f29baf384eb098215fd55fd0bdd680711c2 (HEAD -> branches/armnn_20_05, tag: v20.05, origin/branches/armnn_20_05)
Author: Colm Donelan <Colm.Donelan@arm.com>
Date:   Fri May 29 11:15:40 2020 +0100

    IVGCVSW-4801: Updating Doxygen project version for 20.05 release.
    
    Signed-off-by: Colm Donelan <Colm.Donelan@arm.com>
    Change-Id: I408a10610a5a91de4608b2597918445fcb5ee21c
```
You can build different versions of armnn by checking out different branches. You'll have to make sure though to have the correct version of compute library as well. 
When we release armnn we ensure that the same acl (arm compute library) version works with our version. So armnn_20.05 works with acl_20.05. But when you work with our master branch you'll have to check out a specific commit in acl that works with your current armnn master version. Here is how you can identify the right commit for acl:

In your armnn directory there is a folder called scripts. In there you can find a script that is called `get_compute_library.sh`. If you open that up with an editor of your choice, I used nano,
```
cd <rootdir>/armnn/scripts
nano get_compute_library.sh
```
you'll see on top of the file something like this:
```
# For pinning to a revision use this:
DEFAULT_CLFRAMEWORKREVISION="ad7515d231acb075a9585e52f257373b1a1b5d1f"
```
Copy the sha, in this case `ad7515d231acb075a9585e52f257373b1a1b5d1f`, then change to your acl directory and checkout the copied sha:
```
cd <rootdir>/arm_compute <-- I'm just guessing where your compute library is located, you won't be able to copy this command
git checkout ad7515d231acb075a9585e52f257373b1a1b5d1f
```
Now just follow the steps to build armnn. You can find multiple guides for different configurations (TfLite, Caffe, etc) linked in our [github repository](https://github.com/ARM-software/armnn).
