### ISSUE TITLE
Error loading TENSORFLOW model file

### ISSUE THREAD

**Issue by liyanan-kinght** [ARM-software/armnn#442]
Hello

1.compile enviroment : Ubuntu 16.04
2.arm device : raspberry pi 4B
3.cross compile tools: gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf

My code:

`
#include <iostream>
#include <string>
#include <cassert>
#include <fstream>
#include <vector>
#include <array>
#include <memory>
#include <algorithm>

#ifdef __cplusplus
extern "C"
{
#endif

#include <pthread.h>
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include <stdlib.h>
#include <math.h>
#ifdef __cplusplus
}
#endif

#include "armnn/ArmNN.hpp"
#include "armnn/Descriptors.hpp"
#include "armnn/Exceptions.hpp"
#include "armnn/Tensor.hpp"
#include "armnn/INetwork.hpp"
#include <armnn/IRuntime.hpp>
#include <armnn/Utils.hpp>

#include "armnnTfParser/ITfParser.hpp"

using namespace armnn;

int main(int argc,char *argv[])
{
    armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();
    printf("load model begin\n");
    armnn::INetworkPtr network = parser->CreateNetworkFromTextFile("frozen_graph_10cnn_v1.13.pb",
                                                                   { {"input_x", {1, 150, 40, 1}} },
                                                                   { "labels_softmax" });
    printf("load model end\n");																   
	armnnTfParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo("input_x");
    armnnTfParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("labels_softmax");
	
	armnn::IRuntime::CreationOptions options;
    armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);
    armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuAcc}, runtime->GetDeviceSpec());
    
    // Load the optimized network onto the runtime device
    armnn::NetworkId networkIdentifier;
    runtime->LoadNetwork(networkIdentifier, std::move(optNet));

    return 0;
}

`

test Error Info:
[libprotobuf ERROR google/protobuf/text_format.cc:288] Error parsing text-format tensorflow.GraphDef: 2:1: Expected identifier, got: 9
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Failed to parse graph file  at function CreateNetworkFromTextFile [/home/liyanan/tmp_git_armnn_private_project/armnn_tensorflow_TEST/armnn/src/armnnTfParser/TfParser.cpp:3590]
Aborted (core dumped)

./ArmnnConverter -f tensorflow-binary -m frozen_graph_10cnn_v1.13.pb  -i input_x -s 1 150 40 1 -o labels_softmax -p test.armnn

Segmentation fault (core dumped)

Cross-compiling Arm NN for the Raspberry Pi and TensorFlow

mkdir armnn-pi && cd armnn-pi
export BASEDIR=pwd
Download the Compute Library, Boost, Protobuf, TensorFlow, ONNX, FlatBuffer, and Arm NN git repositories and source bundles. To download the repositories and bundles, enter the following commands:

git clone https://github.com/Arm-software/ComputeLibrary.git
git clone https://github.com/Arm-software/armnn
wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2
tar xf boost_1_64_0.tar.bz2
git clone -b v3.5.0 https://github.com/google/protobuf.git
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow/
git checkout 590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b
git clone https://github.com/onnx/onnx.git
cd onnx
git fetch https://github.com/onnx/onnx.git f612532843bd8e24efeab2815e45b436479cc9ab && git checkout FETCH_HEAD
wget -O flatbuffers-1.10.0.tar.gz https://github.com/google/flatbuffers/archive/v1.10.0.tar.gz
tar xf flatbuffers-1.10.0.tar.gz

cd $BASEDIR/ComputeLibrary
scons extra_cxx_flags="-fPIC -std=c++14" benchmark_tests=0 validation_tests=0 Werror=0 debug=0 asserts=0 neon=1 opencl=0 os=linux arch=armv7a examples=1 

cd $BASEDIR/boost_1_64_0/tools/build
./bootstrap.sh
Go to the $BASEDIR/boost_1_64_0/ directory and open the project-config.jam file in a text editor. In the GCC Configuration section, modif the following line:
using gcc : arm : arm-linux-gnueabihf-g++ ;
b2 --build-dir=$BASEDIR/boost_1_64_0/build toolset=gcc-arm link=static cxxflags=-fPIC --with-filesystem --with-test --with-log --with-program_options install --prefix=$BASEDIR/boost

cd $BASEDIR/protobuf
git submodule update --init --recursive
./autogen.sh
./configure --prefix=$BASEDIR/protobuf-host
make
make install
make clean

./configure --prefix=$BASEDIR/protobuf-arm --host=arm-linux CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ --with-protoc=$BASEDIR/protobuf-host/bin/protoc
make
make install

cd $BASEDIR/tensorflow
../armnn/scripts/generate_tensorflow_protobuf.sh ../tensorflow-protobuf ../protobuf-host

cd $BASEDIR/onnx

export LD_LIBRARY_PATH=$BASEDIR/protobuf-host/lib:$LD_LIBRARY_PATH
$BASEDIR/protobuf-host/bin/protoc onnx/onnx.proto --proto_path=. --proto_path=$BASEDIR/protobuf-host/include --cpp_out=$BASEDIR/onnx

cd flatbuffers-1.10.0
rm -f CMakeCache.txt
rm -rf build
mkdir build
cd build
cmake ..
-G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
-DFLATBUFFERS_BUILD_FLATC=1
-DCMAKE_INSTALL_PREFIX:PATH=$BASEDIR/flatbuffers
make all install

cd $BASEDIR/flatbuffers-1.10.0
modify CMakeList add set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -Wall -Wno-missing-braces -Wconversion -Wsign-conversion -pthread")
mkdir build-arm32
cd build-arm32
cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
-DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc
-DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++
-DFLATBUFFERS_BUILD_FLATC=1
-DCMAKE_INSTALL_PREFIX:PATH=$BASEDIR/flatbuffers-arm32
-DFLATBUFFERS_BUILD_TESTS=0
make all install

cd $BASEDIR/armnn

modify CMakeList add
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -Wall -Wno-missing-braces -Wconversion -Wsign-conversion -pthread")
SET(CMAKE_SYSTEM_NAME Linux)

mkdir build
cd build

build Armnn command:
cmake .. -DCMAKE_LINKER=arm-linux-gnueabihf-ld -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_C_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-mfpu=neon -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTE_BUILD_DIR=$BASEDIR/ComputeLibrary/build -DBOOST_ROOT=$BASEDIR/boost -DTF_GENERATED_SOURCES=$BASEDIR/tensorflow-protobuf -DBUILD_TF_PARSER=1 -DBUILD_ONNX_PARSER=1 -DONNX_GENERATED_SOURCES=$BASEDIR/onnx -DBUILD_TF_LITE_PARSER=1 -DTF_LITE_GENERATED_PATH=$BASEDIR/tensorflow/tensorflow/lite/schema  -DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers-arm32 -DFLATBUFFERS_LIBRARY=$BASEDIR/flatbuffers-arm32/lib/libflatbuffers.a -DFLATC_DIR=$BASEDIR/flatbuffers-1.10.0/build -DPROTOBUF_ROOT=$BASEDIR/protobuf-arm -DPROTOBUF_LIBRARY_DEBUG=$BASEDIR/protobuf-arm/lib/libprotobuf.so -DPROTOBUF_LIBRARY_RELEASE=$BASEDIR/protobuf-arm/lib/libprotobuf.so -DPROTOBUF_INCLUDE_DIRS=$BASEDIR/protobuf-arm/include -DBUILD_TESTS=1 -DARMCOMPUTENEON=1 -DARMNNREF=1 -DBUILD_ARMNN_SERIALIZER=1 -DBUILD_ARMNN_QUANTIZER=1 -DFLATC=$BASEDIR/flatbuffers-1.10.0/build/flatc
make -j8

**Comment by janeil01** [comment]
Hi @liyanan-kinght 

From your file ending (.pb) I guess that you don't have your model saved as text file (json). If your model is saved as protobuf binary do the following: 
Instead of 
```
armnn::INetworkPtr network = parser->CreateNetworkFromTextFile("frozen_graph_10cnn_v1.13.pb")
```
use 
```
armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("frozen_graph_10cnn_v1.13.pb")
```

Hope that helps
Jan

**Comment by liyanan-kinght** [comment]
> Hi @liyanan-kinght
> 
> From your file ending (.pb) I guess that you don't have your model saved as text file (json). If your model is saved as protobuf binary do the following:
> Instead of
> 
> ```
> armnn::INetworkPtr network = parser->CreateNetworkFromTextFile("frozen_graph_10cnn_v1.13.pb")
> ```
> 
> use
> 
> ```
> armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("frozen_graph_10cnn_v1.13.pb")
> ```
> 
> Hope that helps
> Jan

Hello @janeil01 

I changed the code.
Run program error.

error info:
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unexpected number of inputs for node ExpandDims. Expected 1, found 2  at function GetInputParsedTfOperationsChecked [/home/liyanan/tmp_git_armnn_private_project/armnn_tensorflow_TEST/armnn/src/armnnTfParser/TfParser.cpp:610]
Aborted (core dumped)


int main(int argc,char *argv[])
{
    armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();
    printf("load model begin\n");
    armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("frozen_graph_10cnn_v1.13.pb",
                                                                   { {"input_x",{1,150,4,1}} } ,
                                                                   { "labels_softmax" });
    printf("load model end\n");																   
	armnnTfParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo("input_x");
    armnnTfParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("labels_softmax");
	
	armnn::IRuntime::CreationOptions options;
    armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);
    armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuAcc}, runtime->GetDeviceSpec());
    
    // Load the optimized network onto the runtime device
    armnn::NetworkId networkIdentifier;
    runtime->LoadNetwork(networkIdentifier, std::move(optNet));

    return 0;
}

**Comment by liyanan-kinght** [comment]
> Hi @liyanan-kinght
> 
> From your file ending (.pb) I guess that you don't have your model saved as text file (json). If your model is saved as protobuf binary do the following:
> Instead of
> 
> ```
> armnn::INetworkPtr network = parser->CreateNetworkFromTextFile("frozen_graph_10cnn_v1.13.pb")
> ```
> 
> use
> 
> ```
> armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("frozen_graph_10cnn_v1.13.pb")
> ```
> 
> Hope that helps
> Jan

Hello @janeil01 

I build the ARMNN item version information

armnn :  
branch : master     
version number : f2225ca02f10db41db6a5dc91db57be0ad5dc190

computelibary:
branch : master
version number : 3b64e3e78c166773fea680afb4829d886e90552d

protobuf:
branch: v3.5.0

flatbuffers:
branch : master
version number : c30a87de6fc741d7dfcf1f721a69d89ca27a0866

boost:
version : 1.64.0

tensorflow:
version number : 590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b

**Comment by janeil01** [comment]
What license is your model under? Can you upload it? Or is there a link to a network with a similar structure like yours?

Would like to find out if there are actually two inputs to the ExpandDims operation.

**Comment by liyanan-kinght** [comment]
[frozen_graph_10cnn_v1.13.zip](https://github.com/ARM-software/armnn/files/5027713/frozen_graph_10cnn_v1.13.zip)

Hello@janeil01

**Comment by liyanan-kinght** [comment]
> What license is your model under? Can you upload it? Or is there a link to a network with a similar structure like yours?
> 
> Would like to find out if there are actually two inputs to the ExpandDims operation.

Hello @janeil01 
The model file is in the previous reply.

Thanks!

**Comment by janeil01** [comment]
Thanks @liyanan-kinght, 
Which version of tensorfow did you use to create the model?

**Comment by liyanan-kinght** [comment]
Hello @janeil01 
armnn :
branch : master
version number : f2225ca

computelibary:
branch : master
version number : 3b64e3e78c166773fea680afb4829d886e90552d

protobuf:
branch: v3.5.0

flatbuffers:
branch : master
version number : c30a87de6fc741d7dfcf1f721a69d89ca27a0866

boost:
version : 1.64.0

tensorflow:  version number : 590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b

**Comment by janeil01** [comment]
Sorry, I missed that you've posted the tf version already.

Looks like this is a bug. We expect a single input and dim/axis as the operators attribute but your network passes dim/axis as a second input. I created an internal ticket to solve this issue.

I can only point you to our TfLiteParser as a quick alternative.

**Comment by liyanan-kinght** [comment]
Hello @janeil01 

Ok, I see. Thank you very much for your help.
I would use TensorFlowlite as an alternative.

Thanks!

**Comment by liyanan-kinght** [comment]
Hello@ @janeil01 

I used to remove the DROPOUT layer's PB files. Still get an error.

Error Info:
[libprotobuf ERROR google/protobuf/text_format.cc:288] Error parsing text-format tensorflow.GraphDef: 2:1: Expected identifier, got: 9
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Failed to parse graph file  at function CreateNetworkFromTextFile [/home/liyanan/armnn-pi-last/armnn/src/armnnTfParser/TfParser.cpp:3590]
Aborted

`#include <iostream>
#include <string>
#include <cassert>
#include <fstream>
#include <vector>
#include <array>
#include <memory>
#include <algorithm>

#ifdef __cplusplus
extern "C"
{
#endif

#include <pthread.h>
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include <stdlib.h>
#include <math.h>
#ifdef __cplusplus
}
#endif

#include "armnn/ArmNN.hpp"
#include "armnn/Descriptors.hpp"
#include "armnn/Exceptions.hpp"
#include "armnn/Tensor.hpp"
#include "armnn/INetwork.hpp"
#include <armnn/IRuntime.hpp>
#include <armnn/Utils.hpp>

#include "armnnTfParser/ITfParser.hpp"
//#include "armnnTfLiteParser/ITfLiteParser.hpp"

using namespace armnn;

int main(int argc,char *argv[])
{
    armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();
    armnn::INetworkPtr network = parser->CreateNetworkFromTextFile("frozen_graph_10cnn_v1point20_nodropout.pb",
                                                                   { {"input_x", {1, 150, 40, 1}} },
                                                                   { "labels_softmax" });
																   
	armnnTfParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo("input_x");
    armnnTfParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("labels_softmax");
	
	armnn::IRuntime::CreationOptions options;
    armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);
    armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuRef}, runtime->GetDeviceSpec());
    
    // Load the optimized network onto the runtime device
    armnn::NetworkId networkIdentifier;
    runtime->LoadNetwork(networkIdentifier, std::move(optNet));

    
	/*															   
	armnnTfLiteParser::ITfLiteParserPtr parser = armnnTfLiteParser::ITfLiteParser::Create(); 
	//armnn::INetworkPtr pose_reg_network{nullptr, [](armnn::INetwork *){}};

	armnn::InputTensors pose_reg_in_tensors;
	armnn::OutputTensors pose_reg_ou_tensors;
	armnn::IRuntimePtr runtime{nullptr, [](armnn::IRuntime *){}};
	armnn::NetworkId networkIdentifier;
	armnn::IOptimizedNetworkPtr optNet{nullptr, [](armnn::IOptimizedNetwork *){}};;
	armnn::IRuntime::CreationOptions runtimeOptions;

	// loading tflite model
    std::string pose_reg_modelPath = "./converted_model-cnn.tflite";
	printf("load model begin\n");

	if(nullptr == parser)
	{
		printf("parser is null\n");
	}
	else
	{
		printf("parser not null\n");
	}
	
	
    armnn::INetworkPtr pose_reg_network = parser->CreateNetworkFromBinaryFile(pose_reg_modelPath.c_str());

	printf("load model end\n");
	*/


    return 0;
}
`

compile command:
arm-linux-gnueabihf-g++ -g -std=c++14 test_armnn.cpp -I /home/pi/trigger_awake_unittest_armnn/armnn-dist/armnn/include/ -I /home/pi/trigger_awake_unittest_armnn/armnn-dist/boost/include/ -L ./ -l protobuf -l armnn -larmnnTfParser -lpthread -o test

[frozen_graph_10cnn_v1point20_nodropout.zip](https://github.com/ARM-software/armnn/files/5038933/frozen_graph_10cnn_v1point20_nodropout.zip)

**Comment by janeil01** [comment]
I see two things that might be wrong.

If you're using the TfLiteParser you'll have to convert your network to TfLite first. The .pb suffing of your model file indicates that you are using a tensorflow model.

Also you seem to use `CreateNetworkFromTextFile` instead of `CreateNetworkFromBinaryFile`.

**Comment by liyanan-kinght** [comment]
Hello@janeil01 

I changed the code.  I use CreateNetworkFromTextFile instead of CreateNetworkFromBinaryFile.

I used to remove the DROPOUT layer's PB files. Still get an [error.](https://github.com/ARM-software/armnn/issues/442#issuecomment-669274624)

my tf model file:
[frozen_graph_10cnn_v1point20_nodropout.zip](https://github.com/ARM-software/armnn/files/5040274/frozen_graph_10cnn_v1point20_nodropout.zip)

Error Info:
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unexpected number of inputs for node ExpandDims. Expected 1, found 2  at function GetInputParsedTfOperationsChecked [/home/liyanan/armnn-pi-last/armnn/src/armnnTfParser/TfParser.cpp:610]
Aborted

compile command:
arm-linux-gnueabihf-g++ -g -std=c++14 test_armnn.cpp -I /home/pi/trigger_awake_unittest_armnn/armnn-dist/armnn/include/ -I /home/pi/trigger_awake_unittest_armnn/armnn-dist/boost/include/ -L ./ -l protobuf -l armnn -larmnnTfParser -lpthread -o test

Code:

`#include <iostream>
#include <string>
#include <cassert>
#include <fstream>
#include <vector>
#include <array>
#include <memory>
#include <algorithm>

#ifdef __cplusplus
extern "C"
{
#endif

#include <pthread.h>
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include <stdlib.h>
#include <math.h>
#ifdef __cplusplus
}
#endif

#include "armnn/ArmNN.hpp"
#include "armnn/Descriptors.hpp"
#include "armnn/Exceptions.hpp"
#include "armnn/Tensor.hpp"
#include "armnn/INetwork.hpp"
#include <armnn/IRuntime.hpp>
#include <armnn/Utils.hpp>

#include "armnnTfParser/ITfParser.hpp"

using namespace armnn;

int main(int argc,char *argv[])
{
    armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();
    armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("frozen_graph_10cnn_v1point20_nodropout.pb",
                                                                   { {"input_x", {1, 150, 40, 1}} },
                                                                   { "labels_softmax" });
																   
	armnnTfParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo("input_x");
    armnnTfParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo("labels_softmax");
	
	armnn::IRuntime::CreationOptions options;
    armnn::IRuntimePtr runtime = armnn::IRuntime::Create(options);
    armnn::IOptimizedNetworkPtr optNet = armnn::Optimize(*network, {armnn::Compute::CpuRef}, runtime->GetDeviceSpec());
    
    // Load the optimized network onto the runtime device
    armnn::NetworkId networkIdentifier;
    runtime->LoadNetwork(networkIdentifier, std::move(optNet));

    return 0;
}
`

**Comment by janeil01** [comment]
Right now you are still using the TfParser. The problem with that is that ArmNNs ExpandDims operation doesn't support 2 inputs. That's the bug we encountered earlier. Your model without dropout still has an ExpandDims operation with 2 inputs in it. That's why the error persists.
![image](https://user-images.githubusercontent.com/49715517/89636574-c0d87680-d8a0-11ea-9b7e-8c8a30eb0a45.png)

We are working on a solution for that. In the meantime you could try using our TfLiteParser. 

Let me know if you need any help with that :)

**Comment by liyanan-kinght** [comment]
Hello@janeil01 
Sorry,I mistakenly thought the model file had been changed to match the current TfParser.This model file was given to me by a colleague. 
I will try to test with a  model file that matches the current TfParser. Thank you very much for you help.

**Comment by janeil01** [comment]
Hey @liyanan-kinght 

do you have any further questions? Can this issue be closed?

**Comment by liyanan-kinght** [comment]
hello @janeil01 

Thank you very much!  I'll try it.

**Comment by liyanan-kinght** [comment]
hello @janeil01 

I tried and still got an error.  

ARMNN Version:
```
commit a25886e0966a6b9433cd23595688fadb88a161b2
Author: Sadik Armagan <sadik.armagan@arm.com>
Date:   Tue Sep 15 17:17:08 2020 +0100

    IVGCVSW-5317 'Add enable_fast_math Option to ExecuteNetwork'
    
    Signed-off-by: Sadik Armagan <sadik.armagan@arm.com>
    Change-Id: I4eb3e27837aea926593d49f9ccea07bab8388d5b

```

Error Info:
```
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Missing input shape for Placeholder 'keep_prob'  at function ParsePlaceholder [/home/liyanan/tmp_git_armnn_private_project/armnn-pi/my_git_armnn/armnn_tensorflow/armnn/src/armnnTfParser/TfParser.cpp:2779]
Aborted
```
