### ISSUE TITLE
Model deployment with Arm NN

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#443]
If I want to deploy my model on Arm CPU, Arm NPU, and our deep learning accelerator. How can I assign specific layer to specific processor. For example, I want to assign layer1 to Arm CPU, layer2 to Arm NPU, and layer3 to our deep learning accelerator.

**Comment by MikeJKelly** [comment]
Hi @ivs-pychen 

you can set the preferred backend through the BackendSelectionHint(BackendId id) function. 

```
BackendId cpuAcc("CpuAcc");
BackendId npuAcc("NpuAcc");
BackendId yourAcc("YourBackendId");

layer1->BackendSelectionHint(cpuAcc);
layer2->BackendSelectionHint(npuAcc);
layer3->BackendSelectionHint(yourAcc);
```

That should work. 

Best regards,
Mike

**Comment by MatthewARM** [comment]
Or set your preference order of backends, and let the optimiser choose.
