### ISSUE TITLE
intermideate output in armnn

### ISSUE THREAD

**Issue by avanilkumar** [ARM-software/armnn#444]
I have an armnn file. It has layers say a1,a2.......an.......a100.
Based on situation i don't want to run till a100  but to any layer in between say an.
Need suggestion on how to achieve it. Also I dont want to maintain multiple armnn files with layers a1...an    & one with layers a1 to a100.

**Comment by MikeJKelly** [comment]
Hi, 

there is currently no way to do this and it's not on our roadmap. Once you begin running a graph it will always attempt to run to completion and at the moment you will not be able to know the internal state. 

If you wanted to check the output of a layer of the graph to determine if you want to continue executing it then the only way to currently do this is to break the graph into subgraphs.

Best regards,
Mike.
