### ISSUE TITLE
ONNX Parser support for SqueezeNet ?

### ISSUE THREAD

**Issue by sahibdhanjal** [ARM-software/armnn#445]
Hi,

I'm trying to make armnn's ONNX Parser work with an open source version of [squeezenet](https://github.com/onnx/models/tree/master/vision/classification/squeezenet), however, the parser is failing to load the model throwing the following error:
```
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unsupported operation Concat for node 'squeezenet0_concat0'  at function LoadGraph [/home/sahib/ARMNN/armnn/src/armnnOnnxParser/OnnxParser.cpp:680]
Aborted (core dumped)
```
From the documentation on supported layers, I'm able to see that the **concat** layer is not supported for the time-being, so I was wondering if anyone has been able to make the same work, or pointers to how the support can be added. 

Thanks!

**Comment by MikeJKelly** [comment]
Hi @sahibdhanjal 

Onnx parser support for Concat is on the roadmap for an upcoming release but there is no ETA at the moment.
 
If you wish to add support for a layer to the Onnx parser then the Concat operator is described at https://github.com/onnx/onnx/blob/master/docs/Operators.md#Concat and a good example of the way that an Onnx operator is added would be: https://review.mlplatform.org/c/ml/armnn/+/2978 

If you get it working then we are open to contributions. You can find more information here:
https://mlplatform.org/contributing/

Our gerrit server: https://review.mlplatform.org/#/dashboard/self

The first thing to do is to get it working with the latest master branch of Arm NN.

Next make sure you can log in to gerrit at https://review.mlplatform.org/#/dashboard/self using your Github account. Add your ssh key under "settings -> SSH public keys".

Then submit it to a gerrit review with a command like this, replacing with your Github username:
git push ssh://@review.mlplatform.org:29418/ml/armnn HEAD:refs/for/master

Best regards,
Mike

**Comment by sahibdhanjal** [comment]
I see. Thanks for the quick response! If I'm able to make it work on my side I'll create a PR for the same. Closing this ticket for now
