### ISSUE TITLE
Arm NN Inference type

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#447]
What is the inference type of the TFLite model deployed through the Arm NN?  Is it the same as the TFLite model converted from the TF? For example, the TFLite model converted from TF is float-point32, and the TFLite model deployed through the Arm NN is also float-point32.

**Comment by janeil01** [comment]
Hey @ivs-pychen 

yes, that's right :+1:  An fp32 model in TfLite is deployed as fp32 model in ArmNN
