### ISSUE TITLE
Segmentation Fault OnnxParser::ParseActivation

### ISSUE THREAD

**Issue by sahibdhanjal** [ARM-software/armnn#448]
Hello,

I was trying to use the ONNX parser for a personal project, and was running into the issue where it leads to a segmentation fault. I was able to make an open source  [mobilenet onnx model](https://github.com/onnx/models/blob/master/vision/classification/mobilenet/model/mobilenetv2-7.onnx) work perfectly. However, when I remove the classification head from the original architecture, and add 2 separate classification heads (all the layers I use are supported based on the documentation and already exist in the mobilenet backbone), I start facing a segmentation fault. 

As can be seen from the graph below, the backbone is same upto the BN layer and just branches out to 2 heads instead of 1 in my case.

![image001](https://user-images.githubusercontent.com/8936122/91225170-fe7a3380-e6d7-11ea-9236-3da1b344d446.png)

_(right model is mine, left model is the open source one from the ONNX repository)_

The error I'm facing is:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b97360 in armnnOnnxParser::OnnxParser::ParseActivation(onnx::NodeProto const&, armnn::ActivationFunction) ()
   from /home/sahib/ARMNN/armnn/build/libarmnnOnnxParser.so.21
```

I'm also attaching the script, model and makefile for reproducibility. You would need to update the following in the makefile to the path your build/include exists:
```
ARMNN_LIB = ${HOME}/ARMNN/armnn/build
ARMNN_INC = ${HOME}/ARMNN/armnn/include
```
It would be great if you could provide some pointers as to how to make this work and/or why this is not working :smile: 

**Test Files:**
[test.zip](https://github.com/ARM-software/armnn/files/5126180/test.zip)

Cheers,
Sahib Dhanjal

**Comment by MikeJKelly** [comment]
Hi @sahibdhanjal 

I'll take a look and try to see what the problem is. 

Best regards,
Mike

**Comment by MikeJKelly** [comment]
Hi @sahibdhanjal 

The segfault I see occurs when we parse Clip. According to the docs for Clip https://github.com/onnx/onnx/blob/master/docs/Operators.md#Clip Clip can have two optional inputs for Min and Max. However, in your file your Min and Max are Attributes rather than Inputs. 

The parser shouldn't segfault at this stage as the inputs are optional so I'll put together a patch to fix that but I think your model should work if you change your Min and Max to be inputs rather than attributes. 

Best regards,
Mike

**Comment by sahibdhanjal** [comment]
Hi @MikeJKelly ,

Thanks for the quick turn around! I'll try setting the Min/Max to inputs and see if it works. Will let you know how it goes

Best Regards,
Sahib

**Comment by sahibdhanjal** [comment]
Hi @MikeJKelly ,

I tried moving the same from attributes to inputs but it didn't work out. The conversion is handled directly by PyTorch's `torch.onnx.export` hence I'm not able to meddle around with the individual layer. I also noticed that even in the open source mobilenet, the min/max are treated as attributes itself in the clip layers it has, so I can't figure out why there's an issue with this one (I'm using netron to see this). Anyway, could you please respond to this thread once you merge the patch? Would really be helpful!

Best Regards,
Sahib

**Comment by MikeJKelly** [comment]
Thanks for the update, Sahib!
