### ISSUE TITLE
During Armnn Cross Compilation Getting Error

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#451]
Hi Team
I am getting below error while cross compliling armnn for yocto. 
/opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/include/c++/7.3.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>

This file is present in my compiler can you please help me how to resolve this.

Thanks for help in advance
Parag Jain

**Comment by FinnWilliamsArm** [comment]
Hi paragikjain

This could be a result of mixing up compiler and system includes. 
In gcc you can check the include path for your compiler with:
gcc -xc -E -v -
gcc -xc++ -E -v -

Then check if stdlib.h is in the include path that is listed by that command.
