### ISSUE TITLE
How much computing resource is used by Arm NN?

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#452]
How do I know how many cpus or gpus are used by Arm NN?

**Comment by FinnWilliamsArm** [comment]
Hi @ivs-pychen 

There are two previous issues that might have the answer your looking for: #92 #75

Internally I don't believe we have any tools to measure how many CPUs/GPUs Arm NN is using.
But you can use linux commands to inspect this, e.g. "top -H -p <pid of armnn process>"
