### ISSUE TITLE
How to Build Armnn Converter

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#457]
Hi 
I want to build armnn converter so i can convert tenserflow model to armnn.
So is there any flag which need to be enable during building armnn . What is way to build armnn converter. Can you please tell me in brief.

@MatteoArm 
@MatthewARM 

Thanks in Advance

**Comment by FinnWilliamsArm** [comment]
Hi @paragikjain 

The flag you are looking for is -DBUILD_ARMNN_SERIALIZER, but you will also need to build and link flatbuffers.
If you haven't done that before there is some info on how to [here](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite/build-the-google-flatbuffers-library).

Hope that works for you

Finn

**Comment by paragikjain** [comment]
@FinnWilliamsArm  thanks for the information i will try to build.

**Comment by paragikjain** [comment]
Hi @FinnWilliamsArm  I have built armnn  using DBUILD_ARMNN_SERIALIZER FLAG but after build i did not got any executable called armnnconverter to convert my model to .armnn

**Comment by FinnWilliamsArm** [comment]
Hi @paragikjain 

Apologies looks like you will also need to use DARMNNREF and for tensorflow, if you don't have it already, DBUILD_TF_PARSER.

Hope that works for you,

Finn

**Comment by paragikjain** [comment]
Hi @FinnWilliamsArm 

Thank you very much for help i am able to build now.

Apart from this I have one more doubt can I convert tflite model using armnn converter.

**Comment by FinnWilliamsArm** [comment]
Hey @paragikjain 

Glad to hear it worked, you can convert tflite models, you need to add DBUILD_TF_LITE_PARSER though. 
Pass in -f tflite-binary for that. 
You can also see the list of argument options by calling ArmnnConverter with the -h argument.

Regards,

Finn

**Comment by paragikjain** [comment]
Thanks @FinnWilliamsArm , It worked.
