### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#458]
I use the TF2 TFLite Converter(Python API) to convert MobilenetV1_SSD, the TFLite model is added Quantize and Dequantize nodes. But I got segmentation fault and no other error messages.
I think the error is resulted from the following code:
    using IParser = armnnTfLiteParser::ITfLiteParser;
    auto armnnparser(IParser::Create());
    armnn::INetworkPtr network = armnnparser->CreateNetworkFromBinaryFile(programOptions.modelPath.c_str());

Are the Quantize and Dequantize nodes the main cause of this error?

The following zip file is the tflite model
[MobilenetV1_SSD.zip](https://github.com/ARM-software/armnn/files/5259771/MobilenetV1_SSD.zip)

**Comment by MikeJKelly** [comment]
Hi @ivs-pychen 

I was able to load your model with no issues using the following code:

```
using IParser = armnnTfLiteParser::ITfLiteParser;
auto armnnparser(IParser::Create());
armnn::INetworkPtr network = armnnparser->CreateNetworkFromBinaryFile("/home/myhome/path/quantized_model.tflite");
``` 

Perhaps the issue is with a null programOptions or programOptions.modelPath? You could try giving it a hard-coded path to the model to see if that solves the issue? 

Best regards,
Mike

**Comment by ivs-pychen** [comment]
I try to give it a hard-coded path to the model but that doesn't solve the segmentation fault. 
I try other models with the same code but those models do not cause this error.

**Comment by FrancisMurtagh-arm** [comment]
Hi @ivs-pychen,

Are you still having issues? 

Francis.
