### ISSUE TITLE
FakeQuant Node

### ISSUE THREAD

**Issue by ivs-pychen** [ARM-software/armnn#459]
I use TF quantization-aware training, and the fakequant nodes will be added to the model.
Therefore, the converted TFLite model contains FakeQuant node. Does the Arm NN support the FakeQuant operation?
Because the error show the following messages
![image](https://user-images.githubusercontent.com/65347253/93856757-156a7080-fcec-11ea-960f-66fa1dd99f0d.png)

**Comment by MikeJKelly** [comment]
Hi @ivs-pychen 

ArmNN supports Fake Quantization but the TfLiteParser does not support it. 

If you want to try to add support for Fake Quantization to the TfLiteParser we do welcome contributions, for more information on contributing to Arm NN please see the Contributing page on the MLPlatform.org website, or see the [Contributor Guide](https://github.com/ARM-software/armnn/blob/branches/armnn_20_08/ContributorGuide.md). 

Best regards,
Mike

**Comment by ivs-pychen** [comment]
OK, Thank you.
