### ISSUE TITLE
Why does nn not support tflite?

### ISSUE THREAD

**Issue by Wizikim** [ARM-software/armnn#46]
cpu run float inference is too slow. Why nn not support tflite?

**Comment by MatteoArm** [comment]
Hi @Wizikim, tflite support will be availble in the next upcoming release.

**Comment by Wizikim** [comment]
Dear @MatteoArm,

       1. Will opencl support for tflite quantization model in the next release version too? 
       2. I am also very eager to know when will the next version coming

Thanks!

**Comment by MatteoArm** [comment]
Hi @Wizikim, we don't have a definite date for the next release yet, also keep in mind that tflite support will be in alpha state (limited support will be provided).

**Comment by Surmeh** [comment]
Hi @Wizikim,

I hope your question has been answered. Please get in touch if you have any more queries.

Thanks,
Surabhi
