### ISSUE TITLE
Transformers

### ISSUE THREAD

**Issue by Mo-Abdelgawad** [ARM-software/armnn#461]
Hi,
Are transformers supported by ARMNN? In other words, does ARMNN support all the operators (maybe in Tensorflow lite) required to run a transformer?
Thanks,
Mohamed.

**Comment by MikeJKelly** [comment]
Hi @Mo-Abdelgawad 

We support many of the operators required by transformers however Arm NN TensorFlow Lite parser does not currently support Layer Normalization. 

You can find a full list of the operators supported through the Arm NN TensorFlow Lite parser at:

https://github.com/ARM-software/armnn/blob/branches/armnn_20_08/src/armnnTfLiteParser/TensorFlowLiteSupport.md

Best regards,
Mike
