### ISSUE TITLE
ARM  NN inference engine performance?

### ISSUE THREAD

**Issue by pure-water** [ARM-software/armnn#462]
Hi 
  Is there a general comparsion between armnn as the inference engine agaisnt some other vendor's inference engine somewhere? 

Regards
Y

**Comment by MikeJKelly** [comment]
Hi @pure-water 

there isn't a general comparison available that I know of. It would be very difficult to get useful like-for-like comparisons as those other vendor's inference engines would be running on different hardware. 

Best regards,
Mike

**Comment by pure-water** [comment]
Hi @MikeJKelly 

Thanks for answering. What about compare to native TensorflowLite?   I  know it would be very mis-leading to conclude something .  At least, can you please elaborate somewhere where the issue is discussed so we can get a grain of salt at least. 

Regards
Yao

**Comment by psyhtest** [comment]
Hi @pure-wate, to compare ArmNN vs TFLite on ResNet + MobileNet-v1/v2 across several platforms please check out the MLPerf Inference v0.5 results: http://cknowledge.org/dashboard/mlperf.inference

**Comment by pure-water** [comment]
Hi @psyhtest , 

 Thanks for the hint. Help much appreciated!

Regards

**Comment by psyhtest** [comment]
You are welcome @pure-water!
