### ISSUE TITLE
Profiling layers of model

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#464]
Hi Arm Team

I have heard that we can profile time taken by each layer in .armnn models using some command but I am not aware what command is that how to build that command and how to use that command. I have searched on internet but no clues.

Could you please help me if their is any such command present.

Thanks you very much.
Parag Jain

**Comment by paragikjain** [comment]
is it ExecuteNetwork command . if yes then what all flags we need to enable to build this command.

@MatthewARM 
@FinnWilliamsArm

**Comment by paragikjain** [comment]
HI 
I got the way 
using ExecuteNetwork we can do layer wise profiling 
But for .armnn model in -f argument what I need to pass  like in tenserflow We have to pass tenserflow-binary 

Thanks

**Comment by MikeJKelly** [comment]
Hi @paragikjain 

If you build the Arm NN serializer/deserializer or any of the parsers then ExecuteNetwork will be automatically built and can be found in the <build>/armnn/tests/ folder). 

If you run ExecuteNetwork with the -e switch then it will output profiling information in a JSON structure that shows the amount of time each layer takes to run. 

Best regards
Mike

**Comment by paragikjain** [comment]
Thanks Mike for help

**Comment by paragikjain** [comment]
Hi @MikeJKelly 

Is there any way by which we can  profile layerwise using c code in armnn.

Can you please help me with this.

Thanks,
Parag Jain

**Comment by FrancisMurtagh-arm** [comment]
Hi @paragikjain 

You can use the IProfiler C++ API for profiling just like the ExecuteNetwork Application uses.

```
// Create a profiler and register it for the current thread.
std::unique_ptr<IProfiler> profiler = std::make_unique<IProfiler>();
ProfilerManager::GetInstance().RegisterProfiler(profiler.get());

// Enable profiling.
profiler->EnableProfiling(true);

// Run Inference
{...}

// Print output
profiler->Print(std::cout);
```
Example can be found here:
armnn/tests/InferenceTest.cpp

Thanks,
Francis.

**Comment by siddhuE000666** [comment]
is there any command or anything to get additional details for profiling other than time taken for every layer such as hardware utilization , memory consumption ( in Execute Network command we only get the profiling information for time taken for each layer) 
Tried using Streamline Application but we dont get layer wise insights in that
