### ISSUE TITLE
NonMaxSuppression maybe not correct

### ISSUE THREAD

**Issue by antkillerfarm** [ARM-software/armnn#465]
In armnn/src/backends/reference/workloads/DetectionPostProcess.cpp: NonMaxSuppression(): Line 80:

```
    for (unsigned int i = 0; i < numAboveThreshold; ++i)
    {
        if (outputIndices.size() >= numOutput)
        {
            break;
        }
        if (!visited[sortedIndices[i]])
        {
            outputIndices.push_back(indicesAboveThreshold[sortedIndices[i]]);
        }
        for (unsigned int j = i + 1; j < numAboveThreshold; ++j)
        {
            unsigned int iIndex = indicesAboveThreshold[sortedIndices[i]] * 4;
            unsigned int jIndex = indicesAboveThreshold[sortedIndices[j]] * 4;
            if (IntersectionOverUnion(&boxCorners[iIndex], &boxCorners[jIndex]) > nmsIouThreshold)
            {
                visited[sortedIndices[j]] = true;
            }
        }
    }
```

should be changed to:

```
    for (unsigned int i = 0; i < numAboveThreshold; ++i)
    {
        if (outputIndices.size() >= numOutput)
        {
            break;
        }
        if (!visited[sortedIndices[i]])
        {
            outputIndices.push_back(indicesAboveThreshold[sortedIndices[i]]);
            for (unsigned int j = i + 1; j < numAboveThreshold; ++j)
            {
                unsigned int iIndex = indicesAboveThreshold[sortedIndices[i]] * 4;
                unsigned int jIndex = indicesAboveThreshold[sortedIndices[j]] * 4;
                auto iou = IntersectionOverUnion(&boxCorners[iIndex], &boxCorners[jIndex]);
                if ( iou > nmsIouThreshold)
                {
                    visited[sortedIndices[j]] = true;
                }
            }
        }
    }
```

I think if visited flag set true, it should not be visited any more.

For example, if we put 10 ordered boxes into  NonMaxSuppression:

Step 1: Suppose Box 2/3/6/8 are suppressed by Box 1. Box 4/5/7/9/10 survived.

Step2:

Correct way:  We use Box 4 to suppress the survive boxes.

But current way: Box 4 may be suppressed by Box 2, even Box 2 is already suppressed by Box 1...

**Comment by antkillerfarm** [comment]
PS: TOPK is slow way for NMS. You can reference:

https://android.googlesource.com/platform/frameworks/ml/+/refs/heads/master/nn/common/operations/GenerateProposals.cpp: hardNmsMultiClass()

**Comment by TeresaARM** [comment]
Hi @antkillerfarm, 
thanks for the patch, I will have a look into this and test your proposal. 

In case you are interested, for this specific change or for the future, here is our Contributor Guide: https://github.com/ARM-software/armnn/blob/master/ContributorGuide.md. In particular we need the Signed-Off-By line, and ideally instead of a pull request we'd use a Gerrit review.

Thank you very much!

**Comment by MikeJKelly** [comment]
These changes have been merged. Thanks for the contribution, Antkillerfarm!
