### ISSUE TITLE
undefined reference to fmt with Yocto build system

### ISSUE THREAD

**Issue by vinceab** [ARM-software/armnn#466]
I am currently trying to build armnn master branch and I am having trouble with undefined reference to fmt.
Since commit ba3ef18cb6117c49fcdbf177dce5991d6d679cbc that change fmt to be header-only interface library the build is failing.
It seems like FMT_HEADER_ONLY compilation flag is not enabled even if there is a reference of this activation in the armnn/third-party/fmt/CMakeLists.txt.

I need some clue to understand the problem so that I will be in position to propose a patch.

Here is the output log of Yocto:
| [...]/libexec/arm-ostl-linux-gnueabi/gcc/arm-ostl-linux-gnueabi/9.3.0/ld: src/backends/backendsCommon/test/CMakeFiles/armnnBackendsCommonUnitTests.dir/DynamicBackendTests.cpp.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v7::format<char [24], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(char const (&) [24], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
| [...]/armnn/third-party/fmt/core.h:1982: undefined reference to `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>, fmt::v7::format_args)'
| [...]/libexec/arm-ostl-linux-gnueabi/gcc/arm-ostl-linux-gnueabi/9.3.0/ld: libarmnnUtils.a(ParserHelper.cpp.o): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v7::format<char [90], unsigned int, unsigned int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(char const (&) [90], unsigned int&&, unsigned int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
| [...]/armnn/third-party/fmt/core.h:1982: undefined reference to `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>, fmt::v7::format_args)'
| [...]/libexec/arm-ostl-linux-gnueabi/gcc/arm-ostl-linux-gnueabi/9.3.0/ld: libarmnnUtils.a(TensorUtils.cpp.o): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v7::format<char [51], int&, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(char const (&) [51], int&, unsigned int&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
| [...]/armnn/third-party/fmt/core.h:1982: undefined reference to `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>, fmt::v7::format_args)'
| collect2: error: ld returned 1 exit status
| ninja: build stopped: subcommand failed.

Thanks
Vincent

**Comment by janeil01** [comment]
Hey @vinceab 

fmt is a third-party library that we use for string formatting. You can find the repository on [github](https://github.com/fmtlib/fmt). The library can be made a header-only library by adding this FMT_HEADER_ONLY flag that you encountered yourself. This triggers a macro that removes all dependencies to the source files of fmt.

I never worked with yocto myself. Do you might have a build command that I could look at? Depending on how you build armnn it is possible that there might be a link missing to add fmt to one of the targets.

Keep me updated!
Jan

**Comment by vinceab** [comment]
Hi @janeil01 ,

On this github you can find the recipe to build armnn:
https://github.com/STMicroelectronics/meta-st-stm32mpu-ai/blob/master/recipes-frameworks/armnn/armnn_20.05.bb

The version on the github is the 20.05 but except the fact that I point to the master branch, the configuration remains the same and this is maybe where I have an issue.
You can especially check the EXTRA_OECMAKE configuration which is the configuration pass to cmake.
In term of dependency, I did not add fmt because I understand that the FMT_HEADER_ONLY allow to have fmt function defined inline.

I surely miss something.
Thanks for your help.
Vincent

**Comment by janeil01** [comment]
Hi @vinceab,

looks like you are right and fmt doesn't get installed properly. I'll create an internal ticket and let you know when this is resolved.

Thanks, that you reported this.
Jan

**Comment by janeil01** [comment]
Hey @vinceab 

could you add this [patch](https://review.mlplatform.org/c/ml/armnn/+/4294) on top of your armnn master branch and try installing it?

Regards Jan

**Comment by vinceab** [comment]
Hi @janeil01 

I have tested the patch and it does not solve the issue.
But based on your patch, I manage to create a new one to build armnn.
Please find the patch attached.
I apply it on top of the patch you provide. I let you check it on your side and merge if needed into your original patch.

Vincent
[0001-fix-fmt-linking-issue-with-Yocto-build-environment.zip](https://github.com/ARM-software/armnn/files/5486707/0001-fix-fmt-linking-issue-with-Yocto-build-environment.zip)

**Comment by janeil01** [comment]
You kept the third-party/fmt/cmakelist.txt file? Your patch removes the fmt sources from the armnn_sources list but doesn't define them somewhere else.

**Comment by vinceab** [comment]
Hi @janeil01,

I apply the provided patch on top of yours so fmt/cmakelist.txt does not include fmt source.
Yes you are right about the fmt source but it seems to work like that.
I actually try to find the minimum line of code I have to add but I cannot really understand why it is working.

Vincent

**Comment by janeil01** [comment]
Hey @vinceab 

I changed my [patch](https://review.mlplatform.org/c/ml/armnn/+/4294) and made fmt a static library. That way you don't have to specify the header only flag. My theory is that you only have to link it to armnn because all targets use the same functions of fmt and therefore should be able to use the symbolic links added to armnn.

Could you try that out?
Jan

**Comment by vinceab** [comment]
Hello @janeil01 

Thanks for the patch. Build is successful with it.

Vincent

**Comment by janeil01** [comment]
:) thanks for all the testing you've done :+1:
