### ISSUE TITLE
About saving optimized network to a local file

### ISSUE THREAD

**Issue by wangg** [ARM-software/armnn#467]
I am using mali GPU for inference, but the optimization takes a little bit of time every time I load the network. Since I am always 
 running the same model in the same environment, I suppose it makes more sense to save the optimized network to reduce initialization time?

It was mentioned in #59 that saving optimized network will be added to the roadmap. Is it still on the roadmap? Or there is already a way to save an optimized network?

**Comment by TeresaARM** [comment]
Hello,
we decided to do not save the optimized network as such, but it is in our roadmap to cache the kernels used by the optimized network which will speed up load times in GPU.
