### ISSUE TITLE
Where to download the model for TfLiteYoloV3Big-Armnn?

### ISSUE THREAD

**Issue by antkillerfarm** [ARM-software/armnn#469]
Test case TfLiteYoloV3Big-Armnn have 2 tflite model: yoloV3big_backbone.tflite & yoloV3big_detector.tflite.
Where to download these model?

**Comment by TeresaARM** [comment]
There is a list of tflite tested networks: [TensorFlowLiteSupport.md](https://github.com/ARM-software/armnn/blob/branches/armnn_20_08/src/armnnTfLiteParser/TensorFlowLiteSupport.md)
but those specific models are not available, I am sorry.
