### ISSUE TITLE
CMSIS-NN interface didn't found.

### ISSUE THREAD

**Issue by RockySong** [ARM-software/armnn#47]
In https://developer.arm.com/products/processors/machine-learning/arm-nn, there is a statement "It includes support for the Arm Machine Learning processor and, via CMSIS-NN, support for Cortex-M CPUs.". 
But I didn't find keyword 'cmsis' in armnn code, don't know how armnn interface with cmsis-nn.

**Comment by smitakolekar123** [comment]
@RockySong ,
Can you please explain how you are using CMSIS NN with tensorflow lite
