### ISSUE TITLE
ARMNN - Training Support

### ISSUE THREAD

**Issue by pure-water** [ARM-software/armnn#473]
Hi, is there an ARM NN training support? 

Regards
Yao

**Comment by MikeJKelly** [comment]
Hi @pure-water 

There is a selection of online guides available at https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides which might be helpful? If you have any specific questions that aren't covered there then please raise an issue here on GitHub ticket and we might be able to help.  

Best regards,
Mike

**Comment by pure-water** [comment]
Hi @Mike

  Apology. I should have said it with more clarification. I mean "training support" (agains inference as now) on ARM NN level ?


Regards
Yao

**Comment by TeresaARM** [comment]
Hi @pure-water,
we support purely inference in armnn.
Regards

**Comment by pure-water** [comment]
Hi Teresa，

   Is there any plan for "training support" in the roadmap?

Regards

**Comment by TeresaARM** [comment]
Hi,
no, there is not.
Kindest Regards
