### ISSUE TITLE
Build error with ArmNN and ArmCL v20.11

### ISSUE THREAD

**Issue by armflorentlebeau** [ARM-software/armnn#476]
Hi,

I'm building ArmNN natively on Arm64 with the following script:
```
$ git clone https://github.com/jasonrandrews/ml-armnn.git
$ cd ml-armnn
$ ./build-armnn.sh
```

The script checks out the latest version of ArmNN and ArmCL. With versions 20.11, building ArmNN fails with the following error message:
```
[ 54%] Building CXX object CMakeFiles/armnnTfParser.dir/src/armnnTfParser/TfParser.cpp.o
/home/ubuntu/armnn-devenv/armnn/src/armnnTfParser/TfParser.cpp: In member function ‘virtual armnn::INetworkPtr armnnTfParser::TfParser::CreateNetworkFromBinaryFile(const char*, const std::map<std::__cxx11::basic_string<char>, armnn::TensorShape>&, const std::vector<std::__cxx11::basic_string<char> >&)’:
/home/ubuntu/armnn-devenv/armnn/src/armnnTfParser/TfParser.cpp:3567:43: error: no matching function for call to ‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)’
     codedStream.SetTotalBytesLimit(INT_MAX);
                                           ^
In file included from /home/ubuntu/armnn-devenv/pkg/tensorflow-protobuf/tensorflow/core/framework/graph.pb.h:22:0,
                 from /home/ubuntu/armnn-devenv/armnn/src/armnnTfParser/TfParser.cpp:24:
/home/ubuntu/armnn-devenv/pkg/install/include/google/protobuf/io/coded_stream.h:402:8: note: candidate: void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int, int)
   void SetTotalBytesLimit(int total_bytes_limit, int warning_threshold);
        ^~~~~~~~~~~~~~~~~~
/home/ubuntu/armnn-devenv/pkg/install/include/google/protobuf/io/coded_stream.h:402:8: note:   candidate expects 2 arguments, 1 provided
```

I need to checkout versions 20.08 for both ArmNN and ArmCL to be able to build. Could this be a regression?

Florent

**Comment by FrancisMurtagh-arm** [comment]
Hi Florent,

The script (https://github.com/jasonrandrews/ml-armnn/blob/master/build-armnn.sh) needs to be updated as we have changed Protobuf version to 3.12.0, as seen in our release notes under "Versions we support":
https://github.com/ARM-software/armnn/releases/tag/v20.11


`
git clone --branch v3.12.0  https://github.com/google/protobuf.git
`

Thanks,
Francis.

**Comment by armflorentlebeau** [comment]
Hi Francis,

It works, thanks!

Florent

**Comment by skottmckay** [comment]
Would be good to update https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx/single-page to mention either the new protobuf version and/or point readers to the release notes so they can check if the instructions are out of date.
