### ISSUE TITLE
armnn make Error while building for  x86_64 

### ISSUE THREAD

**Issue by Sandeeppasala** [ARM-software/armnn#477]
I am facing below issue when i try to make. Please help.

ARMNN : branches/armnn_20_11 

https://github.com/ARM-software/armnn.git

>armnn/build$ make
[  1%] Built target pipeCommon
[  3%] Built target armnnUtils
[  3%] Built target armnnAclCommon
[  4%] Built target armnnBackendsCommon
[  4%] Built target armnnNeonBackend
[  5%] Built target armnnRefBackend
[ 14%] Built target armnnRefBackendWorkloads
[ 15%] Built target armnnClBackend
[ 21%] Built target armnnClBackendWorkloads
[ 21%] Built target fmt
[ 35%] Built target armnn
[ 36%] Built target timelineDecoderJson
[ 37%] Built target gatordMockService
[ 38%] Building CXX object CMakeFiles/armnnTfParser.dir/src/armnnTfParser/TfParser.cpp.o
armnn/src/armnnTfParser/TfParser.cpp: In member function ‘virtual armnn::INetworkPtr armnnTfParser::TfParser::CreateNetworkFromBinaryFile(const char*, const std::map<std::__cxx11::basic_string<char>, armnn::TensorShape>&, const std::vector<std::__cxx11::basic_string<char> >&)’:
armnn/src/armnnTfParser/TfParser.cpp:3567:43: error: no matching function for call to ‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)’
     codedStream.SetTotalBytesLimit(INT_MAX);
                                           ^
In file included from tensorflow-protobuf/tensorflow/core/framework/graph.pb.h:22:0,
                 from armnn/src/armnnTfParser/TfParser.cpp:24:
google/x86_64_pb_install/include/google/protobuf/io/coded_stream.h:402:8: note: candidate: void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int, int)
   void SetTotalBytesLimit(int total_bytes_limit, int warning_threshold);
        ^
google/x86_64_pb_install/include/google/protobuf/io/coded_stream.h:402:8: note:   candidate expects 2 arguments, 1 provided
CMakeFiles/armnnTfParser.dir/build.make:62: recipe for target 'CMakeFiles/armnnTfParser.dir/src/armnnTfParser/TfParser.cpp.o' failed
make[2]: *** [CMakeFiles/armnnTfParser.dir/src/armnnTfParser/TfParser.cpp.o] Error 1
CMakeFiles/Makefile2:316: recipe for target 'CMakeFiles/armnnTfParser.dir/all' failed
make[1]: *** [CMakeFiles/armnnTfParser.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MikeJKelly** [comment]
Hi @Sandeeppasala 

We updated our protobuf version to v3.12.0 can you try to build with that version instead?  

If you run `git clone --branch v3.12.0 https://github.com/google/protobuf.git` instead of `git clone --branch v3.5.2 https://github.com/google/protobuf.git`then follow the guide as before it should work.

Best regards,
Mike

**Comment by Sandeeppasala** [comment]
Thanks issue is resolved.

Facing below issue now while doing armnn make 

armnn-devenv/armnn/build$ make
[  1%] Built target gatordMockService
[  2%] Built target pipeCommon
[  3%] Built target armnnRefBackend
[  3%] Built target fmt
[  5%] Built target armnnUtils
[  6%] Built target armnnClBackend
[  6%] Built target armnnNeonBackend
[  7%] Built target armnnAclCommon
[  7%] Built target TestSharedObject
[  7%] Built target timelineDecoder
[  7%] Built target armnnBasePipeServer
[  9%] Built target armnnBackendsCommon
[  9%] Built target armnnAclCommonUnitTests
[  9%] Built target link_dummy_dynamic_backend
[ 18%] Built target armnnRefBackendWorkloads
[ 24%] Built target armnnClBackendWorkloads
[ 25%] Built target armnnRefBackendUnitTests
[ 26%] Built target armnnClBackendUnitTests
[ 40%] Built target armnn
[ 41%] Built target timelineDecoderJson
[ 41%] Built target armnnTfLiteParser
[ 42%] Built target armnnSerializer
[ 58%] Built target armnnTfParser
[ 59%] Built target InvalidTestDynamicBackend5
[ 59%] Built target InvalidTestDynamicBackend2
[ 59%] Built target InvalidTestDynamicBackend6
[ 59%] Built target GatordMock
[ 59%] Built target InvalidTestDynamicBackend4
[ 60%] Built target Arm_TestInvalid10_backend
[ 60%] Built target InvalidTestDynamicBackend3
[ 60%] Built target Arm_TestInvalid8_backend
[ 60%] Built target ArmnnConverter
[ 60%] Built target InvalidTestDynamicBackend7
[ 61%] Built target InvalidTestDynamicBackend1
[ 61%] Built target ValidTestDynamicBackend
[ 62%] Built target Arm_TestValid3_backend
[ 62%] Built target Arm_TestValid2_backend
[ 62%] Built target Arm_TestInvalid11_backend
[ 62%] Built target Arm_TestInvalid9_backend
[ 62%] Built target Arm_TestValid5_backend
[ 62%] Built target Arm_TestValid4_backend
[ 71%] Built target Arm_CpuRef_backend
[ 78%] Built target armnnBackendsCommonUnitTests
[ 78%] Linking CXX executable UnitTests
/usr/bin/ld: /home/sandeep/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/sandeep/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/sandeep/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/sandeep/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/sandeep/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/home/sandeep/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/UnitTests.dir/build.make:5390: recipe for target 'UnitTests' failed
make[2]: *** [UnitTests] Error 1
CMakeFiles/Makefile2:127: recipe for target 'CMakeFiles/UnitTests.dir/all' failed
make[1]: *** [CMakeFiles/UnitTests.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sandeeppasala** [comment]
make sure CC and CXX point to gcc and g++ rather that aarch-gcc and aarch-g++.
