### ISSUE TITLE
ARMNN build errors

### ISSUE THREAD

**Issue by tlsnarayana** [ARM-software/armnn#478]
Hi

I have followed https://github.com/ARM-software/armnn/blob/master/BuildGuideCrossCompilation.md to build ARMNN for x86_64 system. Getting below errors while building ARMNN. Please advise me whats going wrong.

/usr/bin/ld: /home/pasdktest/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/pasdktest/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/pasdktest/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/pasdktest/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/pasdktest/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/pasdktest/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/pasdktest/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a(framework.o): Relocations in generic ELF (EM: 183)
/home/pasdktest/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/UnitTests.dir/build.make:5390: recipe for target 'UnitTests' failed
make[2]: *** [UnitTests] Error 1
CMakeFiles/Makefile2:127: recipe for target 'CMakeFiles/UnitTests.dir/all' failed
make[1]: *** [CMakeFiles/UnitTests.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

regards,
Narayana

**Comment by tlsnarayana** [comment]
BTW, I am trying to build on Ubuntu 16.04 linux.

**Comment by davmon01** [comment]
Hey @tlsnarayana ,

It looks like either your boost library or ArmNN is not compiled in the correct format based on this error:

`/home/pasdktest/armnn-devenv/boost_arm64_install/lib/libboost_unit_test_framework.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status`

Check that you are using the same compiler to build ArmNN that you used to compile boost. 
For example when targetting Aarch64 both boost and ArmNN should use: aarch64-linux-gnu-g++

Do you mind posting the CMake commands used for both? That would help to shed more light on the issue.

Regards,
Dave

**Comment by tlsnarayana** [comment]
Thanks, Its working now after changing same compiler for boost and ArmNN.
