### ISSUE TITLE
Unsupported operation Transpose in tensorflow::GraphDef  at function LoadNodeDef

### ISSUE THREAD

**Issue by Sheethal00** [ARM-software/armnn#479]
Hi,

I have a tensorflow model which was converted from pytorch-onnx and then from onnx-.pb.
And i am loading the same using armnnTfParser but i am getting "Unsupported operation Transpose in tensorflow::GraphDef  at function LoadNodeDef" error.

Could anyone tell me what is the issue

I am attaching both the code and .pb file for reference
<img width="960" alt="tf" src="https://user-images.githubusercontent.com/65819572/101594243-5afb2780-3a17-11eb-8473-10dda508279d.png">
![model pb](https://user-images.githubusercontent.com/65819572/101594277-6bab9d80-3a17-11eb-871c-9116f820877b.png)

**Comment by davmon01** [comment]
Hey @Sheethal00,

Looking through the model image you linked it seems to contain some operators we do not currently support. Specifically SparseToDense, and Padv2 when using the TfParser. We support Padv2 when using some other parsers such as TfLite but there is no current plan to support SparseToDense unfortunately. 
Hope this clarifies things a bit.

Regards,
Dave
