### ISSUE TITLE
interfacing with CMSIS-NN not found

### ISSUE THREAD

**Issue by RockySong** [ARM-software/armnn#48]
In https://developer.arm.com/products/processors/machine-learning/arm-nn, there is a statement "It includes support for the Arm Machine Learning processor and, via CMSIS-NN, support for Cortex-M CPUs.". 
But I didn't find keyword 'cmsis' in armnn code, don't know how armnn interface with cmsis-nn.

**Comment by Surmeh** [comment]
Hi @RockySong,

Cortex-M support is not available in Arm NN at the moment. For running neural networks on Cortex-M you can use CMSIS-NN directly: https://github.com/ARM-software/CMSIS_5.

If you could comment about the sort of device you are intending to use, the amount of RAM available, and the how big the neural network is I can make sure that information is made available to the development team. If not, I completely understand.

Best regards,
Surabhi

**Comment by RockySong** [comment]
Hi Surmeh, 

Understood, hope M version of ARM-NN is on the way.

Do appreciate if ARM-NN has python version, I'm not familar with C++14 and don't want to be bounded under Linux environment.

Device is i.MX RT1062 (600MHz M7), 1MB on-chip SRAM with configurable up to 512kB TCM (ITCM+DTCM<=512kB), no on-chip flash, through external QSPI or Hyper flash.

Model size ranges from 30kB to ~200kB; However, if I use SDRAM or HyperRAM, model size can be larger as several MBs, more larger model may be not practical limited by M7 horse power.

**Comment by Surmeh** [comment]
Thanks for the information @RockySong.
We do not have any plans for a python implementation of ArmNN, but we'll surely keep you posted when we do have it.

Best Regards,
Surabhi

**Comment by guineau** [comment]
Hi Surmeh,

Any update on ARM-NN for CMSIS-NN support? Looking to run on an M7 bare-metal.

john
