### ISSUE TITLE
*.cmake files installed in wrong directory

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#481]
`*.cmake` files are installed in `set(INSTALL_CONFIGDIR ${CMAKE_INSTALL_LIBDIR})` which usually expands to `/usr/lib64` whereas it should be installed to something like `/usr/lib64/cmake/Armnn`

**Comment by ek9852** [comment]
@MikeJKelly  https://review.mlplatform.org/c/ml/armnn/+/4790

**Comment by ek9852** [comment]
@MikeJKelly Would u merge this https://review.mlplatform.org/c/ml/armnn/+/4790
Thanks.

**Comment by MikeJKelly** [comment]
Merged, thank you @ek9852 

Please let us know if this works for you @ggardet

**Comment by ggardet** [comment]
This patch install files to the expected location `$LIBDIR/cmake/armnn`. Thanks!
