### ISSUE TITLE
TFLite parser failing to parse ssd sample model

### ISSUE THREAD

**Issue by jeremyong** [ARM-software/armnn#483]
When loading the same tflite model used in the object detection sample, the model appears to parse incorrectly. The subgraph is there and the nodes appear correct. The various operator options appear correct as well, corresponding to options for conv2d and other operators you would expect.

However, the operator_codes that the subgraph nodes should map to are mysteriously all "0" which corresponds to the "ADD" operator, and thus the network construction fails. The exact exception is an input size mismatch (the ADD operator takes two inputs, so an exception is thrown).

The schema file I'm using is the one provided in the tensorflow repository, but I've also tested generating the schema myself from the version three schema file (which matches the version of the tflite model).

I've verified that the model I've downloaded looks correct in a tflite viewer (Netron). Do you have any idea why the parser might be doing this?

**Comment by MikeJKelly** [comment]
Hi @jeremyong 

Our object detection sample https://github.com/ARM-software/armnn/blob/branches/armnn_20_11/samples/ObjectDetection/Readme.md uses a model downloaded from https://storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.zip is that the one you're using? If not can you provide a link to the model you're using? 

That model should be made up mostly of DepthwiseConvolution and Convolution operations with some Reshape and Logistic operations. There should be no Add operations in it. 

Best regards,
Mike

**Comment by jeremyong** [comment]
Hey Mike, yes that’s the model I’m using and I do expext conv and depth
conv layers as well. That seems to be present in the subgraph but the
operator identifiers themselves don’t seem to be parsing correctly. I get
that this is a weird issue so I’ll try to dig more later today. Thanks!

**Comment by ek9852** [comment]
@jeremyong @MikeJKelly 
Try this patch and it should fix the problem:
https://review.mlplatform.org/c/ml/armnn/+/4779/1/src/armnnTfLiteParser/TfLiteParser.cpp
I assume you are using tensorflow 2.4+ version with a v3a schema.

**Comment by MikeJKelly** [comment]
Thank you @ek9852 I'm just trying that patch now.

**Comment by MikeJKelly** [comment]
Closing as we now have support for versions of TFlite later than 2.3.1 where the new operator builtin_codes were introduced. ArmNN should parse this model correctly now. 

Best regards,
Mike
