### ISSUE TITLE
build break if system contains a different version of fmtlib

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#484]
~/workspaces/armnn/third-party/fmt/src/format.cc:47:61: error: explicit instantiation of 'vformat_to' does not refer to a function template, variable template, member function, member class, or static
      data member
template FMT_API FMT_BUFFER_CONTEXT(char)::iterator detail::vformat_to(
                                                            ^
/usr/local/include/fmt/format.h:3761:14: note: candidate template ignored: could not match 'void' against 'fmt::v7::detail::buffer_appender<char>'
void detail::vformat_to(
             ^
1 error generated.

Notice  that if the system had another  version of fmt, they will mismatch and build breaks.
It seems that armnn will pull its own version of fmtlib into third-arty folder. But a lot of place it just include   the system format.h one  instead  of the one in thirdparty folder. 

Test on t latest trunk : 7782dae050a5d6b37215ceea25bf7894d1f2c227

**Comment by FrancisMurtagh-arm** [comment]
Hi Keith,

What were you're build steps? I added fmt to my /usr/include/ directory but was not able to reproduce the mismatch.

Thanks,
Francis.

**Comment by ek9852** [comment]
@FrancisMurtagh-arm what version of fmt is installed in your system. u need a diffrent version of it , so the api will mismatch.
or you can inspect the full path of include file. It should not include the system fmt.h header by adding -M in  gcc .

**Comment by FrancisMurtagh-arm** [comment]
Hi Keith,

I took fmt-master going of Changelog.rst it's 7.1.3 - 2020-11-24

I'll try that, thanks.

Francis.

**Comment by FrancisMurtagh-arm** [comment]
Hi Keith,

I see that it looks in includes
```
#Commented out #includes above fmt first
~/dev/devenv/armnn$ gcc -M src/backends/cl/ClContextDeserializer.cpp | grep fmt
 /usr/include/stdc-predef.h /usr/include/fmt/format.h \
 /usr/include/c++/7/backward/auto_ptr.h /usr/include/fmt/core.h \
```

However if I set the directory for includes it finds the third-party ones first:
```
gcc -M src/backends/cl/ClContextDeserializer.cpp -I/home/$USER/dev/devenv/armnn/third-party/ | grep fmt
 /home/USER/dev/devenv/armnn/third-party/fmt/format.h \
 /home/USER/dev/devenv/armnn/third-party/fmt/core.h \

```

Do you know what options you used to build? And did you have the third-party folder there?
This is how we link fmt:
```
# Link fmt third-party library
add_subdirectory(third-party/fmt)
target_link_libraries(armnn fmt)
```
And then fmt finds its headers using:
```
message("fmt include dir: " ${CMAKE_CURRENT_SOURCE_DIR})     # Added to debug
target_include_directories(fmt PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})

# Outputs: fmt include dir /home/USER/dev/devenv/armnn/third-party/fmt
```

Francis.

**Comment by ek9852** [comment]
@FrancisMurtagh-arm See this:
`cd /Users/kmok/workspaces/armnn/build/third-party/fmt && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DARMNNREF_ENABLED -DARMNN_CAFFE_PARSER -DARMNN_SERIALIZER -DARMNN_SERIALIZER_SCHEMA_PATH=\"/Users/kmok/workspaces/armnn/src/armnnSerializer/ArmnnSchema.fbs\" -DARMNN_TF_LITE_PARSER -DBOOST_ALL_NO_LIB -DDYNAMIC_BACKEND_BUILD_DIR=\"/Users/kmok/workspaces/armnn/build\" -DPROTOBUF_USE_DLLS -I/Users/kmok/workspaces/armnn/include -I/Users/kmok/workspaces/armnn/profiling -I/Users/kmok/workspaces/armnn/third-party/fmt -isystem /usr/local/include -isystem /Users/kmok/workspaces/armnn/third-party -std=c++14 -Wall -Wextra -Werror -Wold-style-cast -Wno-missing-braces -Wconversion -Wsign-conversion -g -g -O0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -fPIC -o CMakeFiles/fmt.dir/src/format.cc.o -c /Users/kmok/workspaces/armnn/third-party/fmt/src/format.cc
/Users/kmok/workspaces/armnn/third-party/fmt/src/format.cc:47:61: error: explicit instantiation of 'vformat_to' does not refer to a function template, variable template, member function, member class, or
      static data member
template FMT_API FMT_BUFFER_CONTEXT(char)::iterator detail::vformat_to(`

adding -M to above command shows it includeds:
  /usr/local/include/fmt/format.h /usr/local/include/fmt/core.h \

**Comment by ek9852** [comment]
Attached pls find the cmakecache.txt
[CMakeCache.txt](https://github.com/ARM-software/armnn/files/6038078/CMakeCache.txt)

**Comment by ek9852** [comment]
@FrancisMurtagh-arm :
The problem seems related to all those include system:
 
`cmake/GlobalConfig.cmake:    include_directories(SYSTEM "${Boost_INCLUDE_DIRS}")
cmake/GlobalConfig.cmake:  include_directories(SYSTEM "${CXXOPTS_INCLUDE}")
cmake/GlobalConfig.cmake:  include_directories(SYSTEM "${GHC_INCLUDE}")
cmake/GlobalConfig.cmake:    include_directories(SYSTEM "${PROTOBUF_INCLUDE_DIRS}")
cmake/GlobalConfig.cmake:    include_directories(SYSTEM "${CAFFE_GENERATED_SOURCES}")
cmake/GlobalConfig.cmake:    include_directories(SYSTEM "${TF_GENERATED_SOURCES}")
cmake/GlobalConfig.cmake:    include_directories(SYSTEM "${ONNX_GENERATED_SOURCES}")
cmake/GlobalConfig.cmake:    include_directories(SYSTEM "${ARMCOMPUTE_INCLUDE}")
cmake/GlobalConfig.cmake:    include_directories(SYSTEM ${OPENCL_INCLUDE})
cmake/GlobalConfig.cmake:    include_directories(SYSTEM ${HALF_INCLUDE})
`

 This makes all those dependency as system include directories.

**Comment by ek9852** [comment]
A more serious problem is that we had Werror in GlobalConfig.cmake.
If flatbuffer or boost or half.hpp does not included as system (which gcc will ignore the warning warning errors on those "system" files), then   we will get a lot of building error, after all SYSTEM are removed from include_directory
