### ISSUE TITLE
Support argmax and deconv in caffe parser

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#489]
armnn support argmax and deconv , but caffe parser ignore /unsupported those.

Resolved by https://review.mlplatform.org/c/ml/armnn/+/4739

**Comment by ek9852** [comment]
FYI: I have a patch to resolve this in https://review.mlplatform.org/c/ml/armnn/+/4739

**Comment by ek9852** [comment]
@MikeJKelly Anyone can merge the PR https://review.mlplatform.org/c/ml/armnn/+/4739

**Comment by MikeJKelly** [comment]
Hi @ek9852 

That review is failing our tests as one of the lines has a length greater than 120. I've left a comment on the review. 

Best regards,
Mike

**Comment by ek9852** [comment]
@MikeJKelly  Pushed a fix, pls check. Thx.

**Comment by MikeJKelly** [comment]
The code has been merged, thanks for your contribution @ek9852 !
