### ISSUE TITLE
Model converted from tf lite to armnn serialization format cannot be loaded.

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#491]
Tried on master branch on a tflite model:
./ArmnnConverter  -f tflite-binary -m model.tflite  -i xx   -o xx   -p /tmp/model.armnn
No error or any output from above command.

Then when try to load the converted armnn model:
./tests/ExecuteNetwork  -m /tmp/o/aa  -f  armnn-binary -c CpuRef -i input -o output 
Warning: No input files provided, input tensors will be filled with 0s.
Info: ArmNN v23.0.0

Info: Initialization time: 0.11 ms

Fatal: Armnn Error: Unsupported data type 0 = NONE.  at function ToConstTensor [/Users/kmok/workspaces/armnn/src/armnnDeserializer/Deserializer.cpp:627]
Info: Shutdown time: 0.01 ms

========
The same tflite model can be run directly if NO T converted to armnn serialized format:
./tests/ExecuteNetwork  -m  model.tflite   -f  tflite-binary  -c CpuRef -i input_1 -o Identity   
Above runs okay.

**Comment by MikeJKelly** [comment]
Hi @ek9852 

From the look of it the serializer doesn't have up to date support for some newer data types. Is your model is using signed 64 bit ints?

Best regards,
Mike

**Comment by ek9852** [comment]
No, nothing fancy. It is just a tflite quant model.

**Comment by TeresaARM** [comment]
could you try:
 ./tests/ExecuteNetwork -m /tmp/model.armnn -f armnn-binary -c CpuRef -i input_1 -o Identity

if it does not work, can you add _-s <InputShape>_ in the format _"1 720 1080 3"_?

_-i_ and _-o_ are for the names of the layers, which in your case I am not sure if they are _-i input -o output_ or  _-i input_1 -o Identity_

Note: when you open the serialized model in [netron](https://lutzroeder.github.io/netron/), for example, you can check that the names and the shape is matching with what you have given in your command.

Thank you!! :)

**Comment by ek9852** [comment]
Same problem, it is not related to input shape. It failed immediately in
deserialization.

Info: Initialization time: 0.10 ms


Fatal: Armnn Error: Unsupported data type 0 = NONE.  at function
ToConstTensor
[/Users/kmok/workspaces/armnn/src/armnnDeserializer/Deserializer.cpp:704]

Info: Shutdown time: 0.01 ms

And tried netron and got:
TypeError Cannot read property 'data' of undefined in 'model.armnn'.

**Comment by FrancisMurtagh-arm** [comment]
Hi @ek9852 

Could you provide a .zip of the .tflite model and the converted .armnn model?

Thanks,
Francis.

**Comment by ek9852** [comment]
@FrancisMurtagh-arm I sent the model to teresa.charlinreyes email address.

**Comment by TeresaARM** [comment]
Hi @ek9852

Could you apply [this patch](https://review.mlplatform.org/c/ml/armnn/+/5266), generate again the .armnn file and then try ExecuteNetwork?

Regards

**Comment by ek9852** [comment]
https://review.mlplatform.org/c/ml/armnn/+/5266
Work for me. Thanks

**Comment by TeresaARM** [comment]
Great, thank you
