### ISSUE TITLE
Does armnn_20_11  support tensorflow lite model "ssd_mobilenet_v3_small.tflite"?

### ISSUE THREAD

**Issue by frankksi** [ARM-software/armnn#493]
I found a file "ssd_mobilenet_v3_small_coco_2019_08_14.armnn" in directory ~/armnn-branches-armnn_20_11\samples\serialized. How to use this file?

Does armnn_20_11 support ssd_mobilenet_v3_small.tflite?

**Comment by morgolock** [comment]
Hi @frankksi 

The file `ssd_mobilenet_v3_small_coco_2019_08_14.armnn` is an armnn model. You could visualize it with netron:

![image](https://user-images.githubusercontent.com/5577511/106776024-97c05500-663b-11eb-871c-abb413cba00a.png)


You can execute the model with the ExecuteNetwork tool as shown below:
`root@acl_hikey_dev:~/tmp/pabtel01# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./ExecuteNetwork -m ssd_mobilenet_v3_small_coco_2019_08_14.armnn -c CpuAcc -f armnn-binary  -i "normalized_input_image_tensor" -o "raw_outputs/box_encodings"`

**Comment by frankksi** [comment]
Hi @morgolock 
I have made ssd_mobilenet_v3_small.tflite run with ArmNN successfully. Thanks:)

**Comment by TeresaARM** [comment]
no problem, happy to hear it worked.
