### ISSUE TITLE
Tflite model  cannot be loaded

### ISSUE THREAD

**Issue by frankksi** [ARM-software/armnn#494]
I downloaded a tflite model "coco_ssd_mobilenet_v1_1.0_quant_2018_06_29" from https://storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.zip.

Then I executed the test command "ExecuteNetwork", there was an error.
Does anyone know why?

pi@NanoPi-M4v2:~/armnn_test/armnn-dist/armnn/lib/tests$ ./ExecuteNetwork -m ./detect.tflite -f  tflite-binary -c CpuRef -i dog.jpg  -o output.jpg 
Warning: No input files provided, input tensors will be filled with 0s.
Info: ArmNN v23.0.0

Info: Initialization time: 11.28 ms

Error: Failed to parse operator #0 within subgraph #0 error: inputs.size() = 3 is not valid, not in {}. 2
Fatal: Armnn Error: Failed to parse operator #0 within subgraph #0 error: inputs.size() = 3 is not valid, not in {}. 2

Info: Shutdown time: 0.63 ms

**Comment by ek9852** [comment]
@frankksi pls  read the help and options in ExecuteNetwork.
The -i and -o are used to specify the input and output tensor name. Not a file

**Comment by ek9852** [comment]
It runs without any problem (tried on master branch)

```
./tests/ExecuteNetwork  -m  /tmp/detect.tflite    -f  tflite-binary  -c CpuRef -i normalized_input_image_tensor  -o TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3
Warning: No input files provided, input tensors will be filled with 0s.
Info: ArmNN v23.0.0

Info: Initialization time: 0.12 ms

Info: Network parsing time: 282.94 ms

Info: Optimization time: 5.31 ms

Warning: The input data was generated, note that the output will not be useful
TFLite_Detection_PostProcess: 0.067040 0.029848 0.971710 0.948930 0.612747 0.026421 0.981155 0.985098 0.394721 0.140771 0.990165 0.983825 0.070287 -0.000700 0.968362 0.585407 0.042023 -0.001062 0.992750 0.258911 0.031419 0.595671 0.962352 1.025769 -0.015088 -0.016336 0.240808 0.996440 0.397384 0.012219 0.988623 0.612877 0.099920 0.366800 0.929753 0.991159 -0.009857 0.075012 0.585588 0.891833 
TFLite_Detection_PostProcess:1: 71.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 15.000000 
TFLite_Detection_PostProcess:2: 0.144531 0.105469 0.105469 0.101562 0.089844 0.082031 0.082031 0.078125 0.070312 0.070312 
TFLite_Detection_PostProcess:3: 10.000000 
Info: 
Inference time: 14846.49 ms

Debug: Runtime::UnloadNetwork(): Unloaded network with ID: 0
Info: Shutdown time: 1.64 ms
```

**Comment by FrancisMurtagh-arm** [comment]
Closing as @ek9852 was able to run with same arguments, however if you are still having issue with this please reopen @frankksi.
