### ISSUE TITLE
Missing operation support in tensorflow lite

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#495]
Support for DEPTH_TO_SPACE, BIDIRECTIONAL_SEQUENCE_LSTM, GATHER is missing in armnn tflite parser.

Need those layers support to run apple-to-apple (same model) benchmark  against running  on Android with nnapi via tensorflow lite directly.

**Comment by ek9852** [comment]
DEPTH_TO_SPACE and GATHER should already be implemented in arm computelibrary.
not sure about BIDIRECTIONAL_SEQUENCE_LSTM

**Comment by MikeJKelly** [comment]
Hi Keith,

no we do not currently support BIDIRECTIONAL_SEQUENCE_LSTM and we do not have any plans to add support for it at the moment. 

Have you considered using the Arm NN TensorFlow Lite Delegate? Added in the 20.11 release the Arm NN TensorFlow Lite Delegate should enable all TensorFlow Lite models to be loaded and executed. As you know, if a model has a layer that is not supported by the Arm NN TensorFlow Lite Parser then the model cannot be loaded. With the Arm NN TensorFlow Lite Delegate the supported layers are accelerated by Arm NN while any remaining unsupported layers are executed on TensorFlow Lite's own CPU kernels. 

You can find more information on the Arm NN TensorFlow Lite delegate at https://github.com/ARM-software/armnn/tree/branches/armnn_20_11/delegate including a guide on building the delegate. This delegate should give a better experience than the parser. If you decide to use the delegate then please let us know what you think and if you experience any issues building or using it, it's still very new so we'd like to catch any issues as soon as possible. 

Best regards,
Mike

**Comment by ek9852** [comment]
Hi Mike,

Fallback to CPU is a very bad idea.
And will make the model run super slow. Since memory copy , latency will be
added to copy the result to and forth between gpu and cpu in the intermed
layers.

I am doing a benchmark using models in https://ai-benchmark.com/tests.html.
Those models run completely (not partially)  in gpu/dsp with
qualcomm/mediatek/kirin SoC via nnapi .
I am going to test armnn performance with SoC using Mali GPU and compare
the results using vendor provided nnapi on the same GPU and also compare
the result with tensorflow lite builtin CL delegate also (which
implemented  CNN using opencl like what arm computelibrary did).
As I did not see any benchmark against that on the web. I only see
armnn/computelibrary benchmark compare to c reference code which is not
optimized)

If models cannot be run completely in armnn and fallback to CPU.
Those models will run very poorly using armnn..
I would rather have those models not running on armnn.
Otherwise I have to put those poor figures side by side with results from
vendor-provided nnapi on GPU and   result with tensorflow lite builtin CL
delegate.

Regards,
Keith

**Comment by ek9852** [comment]
@MikeJKelly The  armnn delegate is actually a duplicated works  of android-nn-driver (https://github.com/ARM-software/android-nn-driver)

And the android-nn-driver seems to be more completed. 
Actually  tensorflow lite nnapi support pure linux also. (nnapi  is not specific to android)
Modify the android-nn-driver  to build in pure linux and avoid having two delegates can save efforts in development and give more time to focus on adding missing layers/features.
Currently the ARM  android-nn-driver only build on Android.

FYI
The tensorflow lite prebuilt pure Linux executable already support nnapi and will try to dlopen libneturalnetwork.so) 
https://www.tensorflow.org/lite/performance/measurement
There is no need to modify the application to use nnapi  delegate.

**Comment by MikeJKelly** [comment]
Hi @ek9852 

I don't think that would be all that simple. The android-nn-driver is a driver that plugs into the Android NNAPI Runtime (libneuralnetwork.so). In order to build and run the driver you need Android specific artefacts for everything from the interfaces and enumerations that describe the model and its operations to the Android logging, threading, memory frameworks and more. 

The NNAPI Runtime itself acts as a bridge between the application (TF Lite in this case) and the driver. The NNAPI Runtime itself does not include any of our code it simply has CPU implementations of the operations. The Runtime behaves a lot like the TF Lite Delegate trying to find an driver capable of accelerating parts of the model so it adds another layer of abstraction between the TF application and the code performing the operation. 

Also the Android NNAPI and NNAPI delegate documentation both say they require Android 8.1 or later but if you can get the NNAPI delegate to run on pure Linux (with or without Arm NN or the android-nn-driver) then we'd be very interested in how you did it. It would really help us to test and debug around here.

https://source.android.com/devices/architecture/modular-system/nnapi
https://www.tensorflow.org/lite/performance/nnapi

Best regards
Mike

**Comment by ek9852** [comment]
Hi Mike,

The nnapi support native linux, I am already using prebuilt tensorflow
benchmark tools to do testing on a SoC using nnapi delegate which the SoC
had a nnapi driver and provided a libneuralnetwork.so for that. The
prebuilt benchmark tools in the native linux arm 64 bits one in
https://www.tensorflow.org/lite/performance/measurement

There are some works needs to be done on the arm implemented
android-nn-driver, such as wrap the LOGE/V/D (android logging system) when
building in pure linux instead of Android, add a CMakefile for that,
copy/rewrite some code from libneuralnetwork_common in AOSP and implement
those ANeuralNetworksModel_<operation>.
But imo, it is better to maintain one delegate instead of having two
delegates and focus the effort in implementing the missing features, since
any missing features in the delegate will fallback to CPU and provide a
very poor performance figure when I am doing side-by-side performance
comparison.
Again I  am testing the models in https://ai-benchmark.com/tests.html and
all those models can run fully in qualcoom/mediatek/hisilicon SoC with
their nnapi implementations. But armnn does not support a number of layers
and fallback to CPU making armnn performance very poor to compare with.

FYI you might refer to this open source project on how nnapi is supported
and implemented on both android and pure-linux :
https://source.codeaurora.org/external/imx/nn-imx/tree/nn_runtime/nnapi_delegate?h=imx-1.0.4
https://source.codeaurora.org/external/imx/nn-imx/tree/nn_runtime?h=imx-1.0.4

**Comment by ek9852** [comment]
@MikeJKelly Let's move the discuss to https://github.com/ARM-software/android-nn-driver/issues/15  for using android-nn-driver for pure linux. So sure there is some works to do for getting android-dnn-driver to work on pure linux. But tensorflow lite is already ready for that.

**Comment by ek9852** [comment]
DEPTH_TO_SPACE and GATHER are resolved by 2686849118217ba692439407adb53ec3849d48ac
Let's create a new one for BIDIRECTIONAL_SEQUENCE_LSTM for tracking.
