### ISSUE TITLE
Is it possible to build ARM NN on PC?

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#496]
Hi,

According to the configuration guild [https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow/single-page](url) , ARM NN is installed on a ARM-based platform or board. 

I want to ask:
1. Is it possible to build ARM NN on a PC with x86 system?
2. If ARM NN can be built on PC, is it possible to cross-compile or convert NN models to ARM-based platform?

Thank you

**Comment by ek9852** [comment]
@Rahn80643 
> Is it possible to build ARM NN on a PC with x86 system?
Yes, I am able to build armnn on my intel based macbook. But you can only run use the cpu reference backend which  is not tuned for speed. Most models will takes several seconds to run.

You can always cross-compile to arm platform. The armnn model format is multi-platform compatible, The armnn  serialized model  does not depend on particular platform.

**Comment by SadikARM** [comment]
Hi @Rahn80643,

There is a Cross-Compilation guide available at https://github.com/ARM-software/armnn/blob/branches/armnn_20_11/BuildGuideCrossCompilation.md which have the instructions on cross-compiling ArmNN under an x86_64 system to target an Arm64 system.

Best Regards,
Sadik

**Comment by Rahn80643** [comment]
Hi SadikARM and ek9852,

I successfully built ARM NN on my x86_64 system, and using CPU to execute the model.

Thank you.

**Comment by rayeh5** [comment]
Hi Rahn80643,

   I want to try the armnn on x86_64 system, would you please provide me the build script if it's possible?
   Thanks for your time.

Ruey-an Yeh (rayeh5@gmail.com)

**Comment by james-conroy-arm** [comment]
Hi @rayeh5 ,

The build guide for cross compilation of ArmNN can be found here: https://github.com/ARM-software/armnn/blob/branches/armnn_21_11/BuildGuideCrossCompilation.md

Alternatively, you can use this Dockerfile which will build ArmNN 21.11 for an aarch64 target on a x86_64 system: https://github.com/ARM-software/armnn/blob/master/docker/x86_64/Dockerfile

Let me know if you require any assistance.

Cheers,
James

**Comment by rayeh5** [comment]
Hi James,

   Thanks for your feedback.
   Actually, my goal is to build and run armnn (no needs for some components) on the same x86 Ubuntu machine.
   I will try the link by just build x86 part, but if you have the solution, please let me konw.
  
   Thanks for your time.

Best regards,

Ruey-an Yeh (rayeh5@gmail.com)

**Comment by Rahn80643** [comment]
Hi rayeh5,
Sorry for replying late.
I used the steps in the following attachments to build armnn on my x86 machine

Best Regrads,
Rahn
[arm_nn-tf_x86_64.tar.gz](https://github.com/ARM-software/armnn/files/7939664/arm_nn-tf_x86_64.tar.gz)
