### ISSUE TITLE
armnn based nnapi implementation vs armnn specific  delegate

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#498]
Since we already have  https://github.com/ARM-software/android-nn-driver,
and tensorflow lite and  nnapi support pure embedded Linux  (not Android based).

Why we still need a separated delegate in this project ? (TfLiteArmnnDelegateCreate)

**Comment by MatthewARM** [comment]
I'll answer this under https://github.com/ARM-software/android-nn-driver/issues/15 as the questions are closely related.
