### ISSUE TITLE
TfLiteInceptionV3Quantized-Armnn fails with ArmNN 20.11 and TFLite 2.4.0

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#499]
While trying Armnn 20.11, built with Tensorflow Lite 2.4.0 with the test `TfLiteInceptionV3Quantized-Armnn --data-dir=armnn/data --model-dir=armnn/models` I get the following error:
```
Error: Failed to parse operator #0 within subgraph #0 error: inputs.size() = 3 is not valid, not in {}.2
```

**Comment by ek9852** [comment]
Pls try using TF 2.3.1 or apply this patch: https://review.mlplatform.org/c/ml/armnn/+/4779

**Comment by ggardet** [comment]
Thanks, I will try it and it will likely fix the problem.

**Comment by ggardet** [comment]
I confirm this fixes the problem, thanks!

**Comment by ggardet** [comment]
fyi, https://review.mlplatform.org/c/ml/armnn/+/4779 has not been merged and now is in conflict.

**Comment by FrancisMurtagh-arm** [comment]
Hi @ggardet,

We still support TF 2.3.1 so we would need a backwards compatible fix, unless there is some big need to bump.

Thanks,
Francis.

**Comment by ggardet** [comment]
> Hi @ggardet,
> 
> We still support TF 2.3.1 so we would need a backwards compatible fix, unless there is some big need to bump.
> 
> Thanks,
> Francis.

I guess a pre-processor macro could be used for backward compatibility?

**Comment by FrancisMurtagh-arm** [comment]
> > Hi @ggardet,
> > We still support TF 2.3.1 so we would need a backwards compatible fix, unless there is some big need to bump.
> > Thanks,
> > Francis.
> 
> I guess a pre-processor macro could be used for backward compatibility?

Possibly we'd also need to ensure the correct version of schema_generated.h is used when building.
