### ISSUE TITLE
does Arm NN support Android 5.1?

### ISSUE THREAD

**Issue by jackwish** [ARM-software/armnn#50]
We have a legacy board of Android 5.1. I have seen that the `BuildGuideAndroidNDK.md` talks about using API level 26. So, is Android 8.0 (or higher) is required?

**Comment by jackwish** [comment]
inactive community...

**Comment by Surmeh** [comment]
Hi @jackwish,

If you are building standalone ArmNN on android it doesn't require Android 8.0. This is only required when you using AndroidNN. I hope this answers your query.

Thanks,
Surabhi

**Comment by jackwish** [comment]
Thank you @Surmeh
