### ISSUE TITLE
Need support for BIDIRECTIONAL_SEQUENCE_LSTM in tensorflow  lite parser

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#500]
as title

**Comment by MikeJKelly** [comment]
Hi @ek9852 

BIDIRECTIONAL_SEQUENCE_LSTM is not currently supported in ComputeLibrary on Neon or GPU. ComputeLibrary is a separate project from Arm NN with a different team. 

If you want GPU support for this layer then I think the first step would be to open an issue in their GitHub requesting the layer. The ComputeLibrary team GitHub is at: https://github.com/ARM-software/ComputeLibrary

If they do add plans to support these layers to their roadmap then we can see about adding it to the Arm NN roadmap too. I'll add a tracking issue there.

Best regards,
Mike

**Comment by ek9852** [comment]
Is it possible to use two LSTM layers to simulate that ?
from tensorflow doc:
```
##### BiDirectional LSTM

Bidirectional LSTM can be implemented with two Keras LSTM layers, one for
forward and one for backward, see examples
[here](https://github.com/tensorflow/tensorflow/blob/35a3ab91b42503776f428bda574b74b9a99cd110/tensorflow/python/keras/layers/wrappers.py#L382).
```

**Comment by MikeJKelly** [comment]
Yes, after looking into it a bit more last night I was just coming on to say that we might be able to do just that! 

I'll have to confirm that our LSTM implementation will work but it would be great to be able to do this as a composite layer made from pre-existing layers.

**Comment by matthewsloyanARM** [comment]
Hi @ek9852,

Thank you for reaching out! Based on the updated `README.md` found [here](https://github.com/ARM-software/armnn/tree/master#how-to-get-involved) under the "How to get involved" section we will be closing GitHub issues labeled with "Feature Request". Instead, we will be tracking the issue and adding the "Help wanted" label. All the issues with this label can be found [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). We would much appreciate your help to add these features. If you would like to add this or any feature to Arm NN feel free to reopen the ticket and let us know you are working on it with a quick comment. We will then track the updates and help you get your additions into our codebase.

Below you will find our contributors guide. If you have any questions feel free to ask here or by creating a new Issue, thank you!

https://www.mlplatform.org/contributing

Kind regards,

Matthew
