### ISSUE TITLE
Mobilenetv3-SSD tflite model has very low accuracy when running with ARMNN 20.11

### ISSUE THREAD

**Issue by frankksi** [ARM-software/armnn#503]
I made a mobilenetv3-SSD Tflite model by myself. It can run it smoothly with good accuracy under Tensorflow runtime. But when I use ARM NN 20.11 to run the same model, I can't get any valid result. 
The model is attached below. Can anyone help me?

[ssdlite_mobilenet_v3_1.0_float32.zip](https://github.com/ARM-software/armnn/files/5878539/ssdlite_mobilenet_v3_1.0_float32.zip)

**Comment by MikeJKelly** [comment]
Hi @frankksi 

that model looks like it run fine with Arm NN 20.1,1 how are you trying to run the model? 

Best regards,
Mike

**Comment by frankksi** [comment]
I use the demo "~/armnn-branches-armnn_20_11/samples/ObjectDetection"  to run my model. 
My Tensorflow version is 1.15.0.  Under the environment of this version, my model runs smoothly with good output. 
I compile the  Arm NN 20.11 dynamic library using the same Tensorflow source code（version 1.15.0)，but I can't get any valid result.

Which Tensorflow version do you use when you compile your Arm NN 20.11 dynamic library? Maybe Tensorflow 1.15.0 is not compatible with Arm NN 20.11?

**Comment by MikeJKelly** [comment]
It might be the problem, we use TensorFlow 2.3.1 now. 

You can get the version we've tested with using the following commands:

> git clone https://github.com/tensorflow/tensorflow.git 
> cd tensorflow/ 
> git checkout fcc4b966f1265f466e82617020af93670141b009

Then build it as before. Are you following a guide when using Arm NN? There are some guides that you might find useful linked from: 
https://github.com/ARM-software/armnn/blob/branches/armnn_20_11/README.md

**Comment by frankksi** [comment]
I built the Arm NN library according to the guide from https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite.The guide is the newest one. The pdf version of this guide is attached below. It didn't say which Tensorflow version I can use, so I used the one (Tensorflow 1.15.0) I have at hand.
    I'll try the guide you offered as soon as possible. I'll report the result later.
   Thanks a lot.


[Arm - Configuring the Arm NN SDK build environment for TensorFlow Lite.zip](https://github.com/ARM-software/armnn/files/5886975/Arm.-.Configuring.the.Arm.NN.SDK.build.environment.for.TensorFlow.Lite.zip)

**Comment by frankksi** [comment]
I built the Arm NN library according to the guide from 
https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite.
The guide is the newest one. The pdf version of this guide is attached below. It didn't say which Tensorflow
version I can use, so I used the one (Tensorflow 1.15.0) I had at hand.
I'll try the guide you offer as soon as possible. I'll report the result later.
Thanks a lot.


[Arm - Configuring the Arm NN SDK build environment for TensorFlow Lite.zip](https://github.com/ARM-software/armnn/files/5887014/Arm.-.Configuring.the.Arm.NN.SDK.build.environment.for.TensorFlow.Lite.zip)

**Comment by frankksi** [comment]
Hi, I have resolved the problem, but it has nothing with Tensorflow versions. The problem is caused by the resizing process.
The dimension of my original video is 640X240. I should resize it to 320X320 so it fits the demand of the Mobilenetv3 inference. I use the function 
ResizeFrame(const cv::Mat& frame, cv::Mat& dest, const od::Size& aspectRatio)
from ~/armnn-branches-armnn_20_11/samples/ObjectDetection/src/ImageUtils.cpp to do this work.

The content of this function is shown below:
void ResizeFrame(const cv::Mat& frame, cv::Mat& dest, const od::Size& aspectRatio)
{
    if(&dest != &frame)
    {
        double longEdgeInput = std::max(frame.rows, frame.cols);
        double longEdgeOutput = std::max(aspectRatio.m_Width, aspectRatio.m_Height);
        const double resizeFactor = longEdgeOutput/longEdgeInput;
        cv::resize(frame, dest, cv::Size(0, 0), resizeFactor, resizeFactor, DefaultResizeFlag);
    }
    else
    {
        const std::string warningMessage{"Resize was not performed because resized frame references the source frame."};
        ARMNN_LOG(warning) << warningMessage;
    }
}

According to the algorithm of this function, my video frame(640X240) will be resized to frame(320X120). 
It doesn't fit the demand of the Mobilenetv3 inference.
When I corrected the parameters of the resize function, the problem was cracked.

**Comment by FrancisMurtagh-arm** [comment]
Hi frankksi,

I'm glad you managed to crack it.

Do you need any other help or can I close this issue?

Thanks,
Francis.

**Comment by wanghaohapp** [comment]
> I made a mobilenetv3-SSD Tflite model by myself. It can run it smoothly with good accuracy under Tensorflow runtime. But when I use ARM NN 20.11 to run the same model, I can't get any valid result.
> The model is attached below. Can anyone help me?
> 
> [ssdlite_mobilenet_v3_1.0_float32.zip](https://github.com/ARM-software/armnn/files/5878539/ssdlite_mobilenet_v3_1.0_float32.zip)

Hi frankksi,

How do you turn tensorflow model into tflite? I use the model published on tensorflow official website for conversion and find that float32 and int8 can run, but float16 always has errors.  
 terminate called after throwing an instance of 'armnn::ParseException'
  what():  Failed to parse operator #2 within subgraph #0 error: Buffer #0 has 0 bytes. For tensor: [32,3,3,3] expecting: 3456 bytes and 864 elements.  at function CreateConstTensor [/home/app/drive/arm32/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:3212]
Aborted

Can you help me?

**Comment by FrancisMurtagh-arm** [comment]
Hi @wanghaohapp,

Would you be able to open a new issue to track your problem please?

Could you also provide a link to the model you tried converting?

Thanks,
Francis.
