### ISSUE TITLE
ArmNN tests with 20.11 are very slow compared to 20.05

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#504]
My tests (in qemu/kvm on aarch64) with 20.05 used to be fast, but with 20.11 they are much slower (10x-60x slower). It may also be some build options, build dependencies or test environment. But likely worth to report.

* Tensorflow-lite:
  * TfLiteMobilenetV2Quantized-Armnn: 
    * Total time for 3 tests: 0.166 seconds vs 10.528 seconds
    * Average time per test case: 55.246 ms vs 3509.416 ms

* Tensorflow:
  * TfInceptionV3-Armnn:  
    * Total time for 3 tests: 1.899 seconds vs 128.682 seconds
    * Average time per test case: 632.835 ms vs 42893.912 ms
  * TfMnist-Armnn: 
    * Total time for 5 tests: 0 seconds vs 0 seconds
    * Average time per test case: 0.056 ms vs 0.093 ms

* Caffe
  * CaffeMnist-Armnn: 
    * Total time for 5 tests: 0.006 seconds vs 0.057 seconds
    * Average time per test case: 1.124 ms vs 11.379 ms

**Comment by MikeJKelly** [comment]
Thanks @ggardet those are big differences alright, I assume this is on CpuAcc rather than CpuRef yes? I'm not aware of large performance differences between 20.05 and 20.11 I'll see if we're tracking anything here.

**Comment by MatthewARM** [comment]
Could be in one case CpuAcc was in use, and in the other case CpuRef was in use? That would produce a big difference like this.

**Comment by ggardet** [comment]
> Could be in one case CpuAcc was in use, and in the other case CpuRef was in use? That would produce a big difference like this.

I do not specify any backend explicitly. So, I would expect to use `CpuAcc` by default. Did that change to use `CpuRef` by default?

**Comment by MatthewARM** [comment]
Hmm, I'm not sure we specify what the default order of preference for backends is....

**Comment by MatthewARM** [comment]
But I would more likely suspect that the CpuAcc backend failed to load, which would result in some non-fatal warnings somewhere.

**Comment by ggardet** [comment]
Ok, so if I force `CpuAcc` usage with `-c CpuAcc`, it runs pretty fast. So, the default backend used changed in between.

**Comment by MikeJKelly** [comment]
That's great, I'm glad that you were able to solve this. 

I'm going to close this ticket if you have any further issues please let us know.

**Comment by ggardet** [comment]
> That's great, I'm glad that you were able to solve this.
> 
> I'm going to close this ticket if you have any further issues please let us know.

I would not close the issue since the default backend used has **now** pretty bad performances. It should default to `CpuAcc` by default, IMO.
