### ISSUE TITLE
ARMnn much slower than ARMcl?

### ISSUE THREAD

**Issue by cakeng** [ARM-software/armnn#505]
Hello, I've noticed that armnn's convolution has much slower speed compared to armcl's benchmark tests. 

I've followed [this guide](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite) to build both armcl and armnn.
We are using [Odroid N2+](https://www.hardkernel.com/ko/shop/odroid-n2-with-4gbyte-ram-2/) from Hardkernel, with Ubuntu 18.04 and gcc 7.5.0.
I've used "test/benchmark_graph_vgg16" in the armcl's build directory to benchmark armcl, which returned these results.
```
Version = arm_compute_version=v20.11 Build options: {'neon': '1', 'validation_tests': '1', 'build': 'native', 'benchmark_tests': '1', 'extra_cxx_flags': '-fPIC', 'arch': 'arm64-v8a'} Git hash=49b8f9080cf2a24da986b6f156c7418ee3d28478
CommandLine = ./benchmark_graph_vgg16 --iterations=10 --example_args=--threads=6 
CL_DEVICE_VERSION = OpenCL 2.0 git.c8adbf9.122c9daed32dbba4b3056f41a2f23c58
Iterations = 10
Running [0] 'Examples/benchmark_graph_vgg16'
Threads : 6
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file : 
Fast math enabled? : false

  Wall clock/Wall clock time:    AVG=398875.7778 us, STDDEV=0.89 %, MIN=393505.0000 us, MAX=405243.0000 us, MEDIAN=398969.0000 us
Executed 1 test(s) (1 passed, 0 expected failures, 0 failed, 0 crashed, 0 disabled) in 8 second(s)
```

I've changed armnn's SimpleSample.cpp a bit to test the VGG16's layer2 convolution using armnn, which resulted in about 190ms per iteration. 
```
#include <armnn/INetwork.hpp>
#include <armnn/IRuntime.hpp>
#include <armnn/Utils.hpp>
#include <armnn/Descriptors.hpp>
#include <arm_compute/runtime/Scheduler.h>

#define TESTBLOCKS 64
#define TESTCHANNEL 64
#define TESTHEIGHT 224
#define TESTWIDTH 224
#define TESTFILHEIGHT 3
#define TESTFILWIDTH 3

void armnnTest(float* output)
{
    using namespace armnn;
    auto t1 = std::chrono::high_resolution_clock::now();
    auto t2 = std::chrono::high_resolution_clock::now();
    auto duration1 = std::chrono::duration_cast<std::chrono::microseconds>( t2 - t1 ).count();
    arm_compute::Scheduler::get().set_num_threads(6);
    // Turn on logging to standard output
    // This is useful in this sample so that users can learn more about what is going on
    armnn::ConfigureLogging(true, false, LogSeverity::Warning);

    // Construct ArmNN network
    armnn::NetworkId networkIdentifier;
    INetworkPtr myNetwork = INetwork::Create();

    armnn::Convolution2dDescriptor Conv2dDesc;
    Conv2dDesc.m_PadTop = 1;
    Conv2dDesc.m_PadBottom = 1;
    Conv2dDesc.m_PadRight = 1;
    Conv2dDesc.m_PadLeft = 1;
    Conv2dDesc.m_StrideX = 1;
    Conv2dDesc.m_StrideY = 1;
    Conv2dDesc.m_BiasEnabled = true;

    TensorInfo weightsInfo(TensorShape({TESTBLOCKS, TESTCHANNEL, TESTFILHEIGHT, TESTFILWIDTH}), DataType::Float32);
    armnn::ConstTensor weights(weightsInfo, &(testFilter[0][0][0][0]));

    TensorInfo biasInfo(TensorShape({TESTBLOCKS}), DataType::Float32);
    armnn::ConstTensor bias(biasInfo, &(testBias[0][0][0][0]));

    IConnectableLayer *convLayer = myNetwork->AddConvolution2dLayer(Conv2dDesc, weights, bias, "Armnn Conv2d");

    IConnectableLayer *InputLayer = myNetwork->AddInputLayer(0);
    IConnectableLayer *OutputLayer = myNetwork->AddOutputLayer(0);

    InputLayer->GetOutputSlot(0).Connect(convLayer->GetInputSlot(0));
    convLayer->GetOutputSlot(0).Connect(OutputLayer->GetInputSlot(0));

    // Create ArmNN runtime
    IRuntime::CreationOptions options; // default options
    IRuntimePtr run = IRuntime::Create(options);

    //Set the tensors in the network.
    TensorInfo inputTensorInfo(TensorShape({1, TESTCHANNEL, TESTHEIGHT, TESTWIDTH}), DataType::Float32);
    InputLayer->GetOutputSlot(0).SetTensorInfo(inputTensorInfo);

    TensorInfo outputTensorInfo(TensorShape({1, TESTBLOCKS, TESTHEIGHT, TESTWIDTH}), DataType::Float32);
    convLayer->GetOutputSlot(0).SetTensorInfo(outputTensorInfo);

    // Optimise ArmNN network
    armnn::IOptimizedNetworkPtr optNet = Optimize(*myNetwork, {Compute::CpuAcc}, run->GetDeviceSpec());
    if (!optNet)
    {
        // This shouldn't happen for this simple sample, with reference backend.
        // But in general usage Optimize could fail if the hardware at runtime cannot
        // support the model that has been provided.
        std::cerr << "Error: Failed to optimise the input network." << std::endl;
    }

    // Load graph into runtime
    run->LoadNetwork(networkIdentifier, std::move(optNet));

    armnn::InputTensors inputTensors{{0, armnn::ConstTensor(run->GetInputTensorInfo(networkIdentifier, 0), &(testFeatureMap[0][0][0][0]))}};
    
    armnn::OutputTensors outputTensors{{0, armnn::Tensor(run->GetOutputTensorInfo(networkIdentifier, 0), output)}};

    // Execute network
    for (size_t i = 0; i < 100; i++)
    {
        t1 = std::chrono::high_resolution_clock::now();
        run->EnqueueWorkload(networkIdentifier, inputTensors, outputTensors);
        t2 = std::chrono::high_resolution_clock::now();
        duration1 = std::chrono::duration_cast<std::chrono::microseconds>( t2 - t1 ).count();
        printf("Armnn Time: %4.2f ms,\n",(double)duration1/1000);
    }
}
```
testFeatureMap, testFilter, testBias is a randomly generated float array with dimensions corresponding to the VGG16's second layer.
output is an empty float array with size of 64 * 224 * 224 in this case. 

Is there something that I've missed? I thought armnn was using armcl under the hood, what makes such a drastic difference?
(400ms for the whole VGG16 on armcl vs 190ms for a single layer on armnn)

Thank you.
Park.

**Comment by MatthewARM** [comment]
I think it's because the ComputeLibrary test is using NHWC, whereas the Arm NN code is using NCHW. 
The CpuAcc backend does use Compute Library NEON functions under the hood, but the NCHW routines in Compute Library are quite a bit slower than the NHWC routines.

Hope that helps,
Matthew

**Comment by MatthewARM** [comment]
The quickest way to check this might be to change the Compute Library test to NCHW mode - I believe there's a command line option to do that but I can't remember exactly what it is off the top of my head.

**Comment by cakeng** [comment]
Thank you for your suggestion. Changing the benchmark to NCHW mode did result in a slower run. 
```
 Version = arm_compute_version=v20.11 Build options: {'neon': '1', 'validation_tests': '1', 'build': 'native', 'benchmark_tests': '1', 'extra_cxx_flags': '-fPIC', 'arch': 'arm64-v8a'} Git hash=49b8f9080cf2a24da986b6f156c7418ee3d28478
CommandLine = ./benchmark_graph_vgg16 --iterations=10 --example_args=--threads=6,--layout=NCHW 
CL_DEVICE_VERSION = OpenCL 2.0 git.c8adbf9.122c9daed32dbba4b3056f41a2f23c58
Iterations = 10
Running [0] 'Examples/benchmark_graph_vgg16'
Threads : 6
Target : NEON
Data type : F32
Data layout : NCHW
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file : 
Fast math enabled? : false

  Wall clock/Wall clock time:    AVG=661343.5556 us, STDDEV=1.34 %, MIN=646932.0000 us, MAX=678084.0000 us, MEDIAN=661500.0000 us
Executed 1 test(s) (1 passed, 0 expected failures, 0 failed, 0 crashed, 0 disabled) in 10 second(s)
```
But it is still 660ms for the whole net, which is probably running way faster than the armnn's single layer test of 190ms.
I'll try implementing a single layer benchmark based on the Compute Library code, and a full implementation of VGG16 for armnn, in NHWC mode.
By the way, Is there anything that I have done wrong for the armnn test code?

**Comment by MatthewARM** [comment]
The Arm NN test code looks good. To change it to use NHWC, you can set the DataLayout parameter in the convolution descriptor, and adjust the shapes of the input, output and weights tensors accordingly.

**Comment by MatthewARM** [comment]
Arm NN can output the 'instruments' from the underlying Compute Library kernels... If you turn them on in both examples you should be able to see the precise timing measured in Compute Library for the individual kernel. That's the way to absolutely make sure that the comparison is like-for-like. 
The usual reason for a big timing difference is a different Compute Library kernel being selected due to differences of layout, type, options, etc. The detailed event profiling information will show exactly which kernel is being selected in each case, and we can make sure it's the most optimal one.

**Comment by cakeng** [comment]
Armnn's VGG16 layer 2 test in NHWC mode returned 70ms; this is much more reasonable than NCHW mode's 190ms.
I've also modified the Compute library VGG16 benchmark to run layer 2 only, and it resulted in 63ms for NHWC mode, and 72ms for NCHW mode.
I'm not entirely sure what makes the 120ms difference in armnn's NCHW mode, but the NHWC mode results look normal.

Thank you for your support, @MatthewARM.
Park.
