### ISSUE TITLE
RuntimeError: Current TfLite parser only supports 1 subgraph.

### ISSUE THREAD

**Issue by n-moussa** [ARM-software/armnn#507]
Hello team!

I'm getting an issue when I try to parse a tflite model using armnn tflite parser.
I'm trying with PyArmNN.
TF lite model version is 2.3.1
ArmNN is 20.11

The model has multiple outputs.

Does multiples subgraphs in TF Lite can be supported  ??

Edit: I'm having the same issue using ./ArmConverter tool or building a small c++ code to use armnnTfLiteParser

Thanks for your feedback!

**Comment by SadikARM** [comment]
Hi @n-moussa,

Currently TfLite parser only supports 1 subgraph. But we introduced Arm NN TfLite Delegate: https://github.com/ARM-software/armnn/tree/branches/armnn_20_11/delegate on 20.11 release.
Here is the build guide for the delegate: https://github.com/ARM-software/armnn/blob/branches/armnn_20_11/delegate/BuildGuideNative.md.
Currently we are improving the delegate, adding more operator supports, more documentation and integrating into TfLite using Python which will be available on upcoming release.

Best Regards,
Sadik

**Comment by n-moussa** [comment]
Thanks @SadikARM

Yes that's also my plan, I will soon dig into this :)

Regards,
Moussa

**Comment by n-moussa** [comment]
Hi @SadikARM,

When trying to use ArmNN delegate I got into this issue:

**Comment by SadikARM** [comment]
Hi @n-moussa,

Are there any dynamic type tensors in the model you are trying to run on TfLite ArmNN delegate? Dynamic type tensors are not supported in Arm NN yet, we have added an item to our backlog but there is no ETA at the moment.

Currently we are working on documentation with examples, tutorials but in the meantime we have some documentation: https://github.com/ARM-software/armnn/blob/master/delegate/IntegrateDelegateIntoPython.md and small test examples in here: https://github.com/ARM-software/armnn/tree/master/delegate/python/test which will be available on the upcoming release.

Best regards,
Sadik

**Comment by n-moussa** [comment]
Hi @SadikARM,

I fixed all model tensors dimension to static before converting the model into TF Lite format.
But, I'm having some fancy operator from TF Lite which is 'tf.while' (the subgraphs are coming from this operator).

I'm not sure if this would be supported by ArmNN backend.
So my plan is to run the main subgraph with armnn and let tf lite interpreter to manage the subgraphs occurred with operator tf.while.

Could you let me know if that would be possible ?

Thanks

**Comment by FrancisMurtagh-arm** [comment]
Hi @n-moussa,

Your plan should work fine as, with the Delegate, only subgraphs of layers supported by ArmNN will be ran by ArmNN and then the subgraphs with the tf.while operator will indeed be ran through TF Lite reference backend.

Thanks,
Francis.
