### ISSUE TITLE
DIRECTORY_PATH not defined in BuildGuideCrossCompilation.md

### ISSUE THREAD

**Issue by ashutoshnaik** [ARM-software/armnn#508]
Hi,

In the BuildGuideCrossCompilation.md, the envornment variable DIRECTORY_PATH is not defined. This is causing build failues.

I am trying to crosscompile the repository on x86_64 for the ARM target, hence any support will be greatly appreciated.

Regards
Ashutosh Naik.

**Comment by nikraj01** [comment]
Hi @ashutoshnaik ,

DIRECTORY_PATH is the path where you have installed your dependencies or tools. It will be different for different users, hence it is not defined. But we will make a note of it and update the guide in the upcoming release. I hope that helps. Please let me know if you have more questions.

Thanks

**Comment by ashutoshnaik** [comment]
Hi @nikraj01 

Sorry, its still extremely unclear. 

Could you please clarify what exactly should be the path as per the ReadMe Guide ? Could you please be specific as to the exact dependencies/tools that we are talking about here.

Also, in the "Build Onnx" section:

`export LD_LIBRARY_PATH=$<DIRECTORY_PATH>/protobuf-host/lib:$LD_LIBRARY_PATH`

The `protobuf-host ` directory is not built or referenced anywhere else in the build process.

If you could provide working instructions for the ARMNN build, that would be great'

Thanks.

**Comment by ashutoshnaik** [comment]
Hi,

It would be great if the Documentation is updated with clear instructions like https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx/single-page

The above steps worked for me on the native compilation but cross-compilation failed.

Thanks!

**Comment by FrancisMurtagh-arm** [comment]
Hi @ashutoshnaik,

This has been updated in our trunk:
https://review.mlplatform.org/c/ml/armnn/+/5043

Thanks,
Francis.
