### ISSUE TITLE
MobileSSD net

### ISSUE THREAD

**Issue by shirbarzel** [ARM-software/armnn#51]
Hey,
Where can I find an implementation of SSDmobile net with armnn?

Thanks

**Comment by Surmeh** [comment]
Hi @shirbarzel,

We currently do not have the layer support required for SSDMobileNet, but are looking to implement it and might have it in the future release. Could you please let us know which framework are you interested in, Caffe, Tensorflow or TfLite?

Thanks,
Surabhi

**Comment by shirbarzel** [comment]
Hi, I`m interested in Caffe framework.
I found out that the performance of your tiny-yolo implementation in human detection is not so good,
What implementation you are most recommend in terms of efficiency and accuracy in human detection?

Thanks,
Shir

**Comment by Georg-W** [comment]
Hi I would also be very interested in using ssd mobilenet, but coming from the Tflite/Tensorflow side. 
Are there any rough estimates that you could give about your timeline?
This would be really helpful.

Thanks,
Georg

**Comment by shirbarzel** [comment]
HI, I tried to run the SSD mobileNet network but I got the following error:
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Couldn't find requested output layer 'fc12' in graph
Maybe it will be more simple and quick to add the layers that are missing?
I need this implementation ASAP

**Comment by Surmeh** [comment]
Hi @Georg-W,

Thank you very much for your interest.

I can't comment on the estimates, but I will certainly pass on your interest. The Caffe path is currently our highest priority, but we will certainly look into implementing the other paths too.

**Comment by shirbarzel** [comment]
Hi @Surmeh 
Could you please answer my previous question?
Thanks,
Shir

**Comment by Surmeh** [comment]
Hi @shirbarzel,

We've currently only implemented Tiny-Yolo Caffe network in ArmNN for human detection. There are definitely networks like Faster-RCNN, SSD and their variants which are efficient in performance and accuracy, which we might look into implementing in the future.

The error you're getting suggests to me that the output layer name is incorrect. Could you please look into the prototxt file and mention the last layer's "top" name. You will still get an error for not supported layer(s) as we've not implemented SSDMobileNet in ArmNN.

I hope all your questions have been answered. I'm going to close this issue as the original question has been answered.

**Comment by shirbarzel** [comment]
Hi @Surmeh 
You're right, I changed the name of the layer that the code expects to get and it worked
Now I get an error as you said about the not supported layer(s)
**Permute layer is the layer which is not supported.**
Maybe you can implement the few layers which are not supported.
Attached the caffemodel and the prototxt that I`m trying to test.


[MobileNet.zip](https://github.com/ARM-software/armnn/files/2352244/MobileNet.zip)

**Comment by steniu01** [comment]
Hi Shirbarzel,

I benchmarked both tiny yolo and mobilenet-ssd ( Rockchip has their in house ARMNN mobilenet-ssd implementation), the result I get show the speed of mobilenet-ssd performs significant better.  The performance of tiny yolo can't meet my company's product target while mobilenet-ssd can.  

I also hope ARMNN can officially support mobilenet-ssd soon.

**Comment by foromer4** [comment]
Hi @Surmeh, I'm looking for the mobilenet-SSD implantation you mentioned but can't find it. anyway you could share a link? many thanks
