### ISSUE TITLE
Int8 optimization support

### ISSUE THREAD

**Issue by allnes** [ARM-software/armnn#511]
Hi, there was a discussion in this issue [https://github.com/ARM-software/armnn/issues/143](https://github.com/ARM-software/armnn/issues/143) that int8 models are losing performance to fp32 models, but it was said that int8 core optimization will be implemented. Are there already optimized cores or are there plans to add them?

**Comment by FrancisMurtagh-arm** [comment]
Hi @allnes,

The "optimized assembly kernels for quantized kernels for armv7" mentioned in the ticket, are not implemented and not currently in our plans but I have highlighted it as a feature request.

Thanks,
Francis.

**Comment by allnes** [comment]
@FrancisMurtagh-arm thank you!

**Comment by allnes** [comment]
@FrancisMurtagh-arm sorry, but how are things going with arm-v8?

**Comment by MatthewARM** [comment]
@allnes in Arm NN the CPU performance is provided by the Arm Compute Library, so you can get a detailed answer to your question by asking on their Github (https://github.com/ARM-software/ComputeLibrary).  But from my knowledge, most of the work for int8 quantisation was done in their 20.02 release (ie. February 2020) and since then they have done further optimisations in each release.

**Comment by allnes** [comment]
@MatthewARM thank you!

**Comment by AIWintermuteAI** [comment]
It's mentioned in https://github.com/ARM-software/ComputeLibrary/issues/877#issuecomment-800141065 that optimized INT8 kernels should be available for aarch64 armv8a.
I have installed ARM NN and pyArmNN(22.0.0) on arm64 version of Raspberry Pi OS Raspberry Pi 4 4 Gb. According to this page
https://developer.arm.com/ip-products/processors/cortex-a/cortex-a72
Raspberry Pi 4 CPU should support Armv8-A architecture instructions. However when comparing inference time of INT8 and FLOAT32 .tflite models, the INT8 model is two times slower.

I have prepared scripts and models for you to reproduce the issue:
[test_armnn_int8.zip](https://github.com/ARM-software/armnn/files/6590450/test_armnn_int8.zip)

The following is the output of 3 different commands run on arm64 version of Raspberry Pi OS Raspberry Pi 4 4 Gb with pyArmNN(22.0.0) installed:

FLOAT32 tflite model inference, model obtained by converting as in https://www.tensorflow.org/lite/performance/post_training_quantization#dynamic_range_quantization
```
pi@raspberrypi:~/pyarmnn/examples/object_detection $ python3 run_video_file.py --video_file_path ../samples/test.mp4 --model_file_path YOLO_best_mAP.tflite --model_name yolo_v2 --label_path labelmap_face.txt 
Your ArmNN library instance does not support Caffe models parser functionality.  Skipped ICaffeParser import.
Your ArmNN library instance does not support Onnx models parser functionality.  Skipped IOnnxParser import.
Your ArmNN library instance does not support TF models parser functionality.  Skipped ITfParser import.
face_detection.mp4
766
Preferred backends: ['CpuAcc', 'CpuRef']
IDeviceSpec { supportedBackends: [CpuAcc, CpuRef]}
Optimization warnings: ()
Processing frames:   0%|                                                                                                                    | 0/766 [00:00<?, ?it/s]/home/pi/pyarmnn/examples/object_detection/yolov2.py:73: RuntimeWarning: overflow encountered in exp
  return 1. / (1. + np.exp(-x))
Processing frames: 100%|##########################################################################################################| 766/766 [00:43<00:00, 17.71it/s]
Finished processing frames
Average time(ms):  20.0
FPS:  50.0
```
Integer with float fallback (using default float input/output), model obtained by converting as in  https://www.tensorflow.org/lite/performance/post_training_quantization#integer_with_float_fallback_using_default_float_inputoutput

```
pi@raspberrypi:~/pyarmnn/examples/object_detection $ python3 run_video_file.py --video_file_path ../samples/test.mp4 --model_file_path YOLO_best_mAP_dynamic.tflite --model_name yolo_v2 --label_path labelmap_face.txt 
Your ArmNN library instance does not support Caffe models parser functionality.  Skipped ICaffeParser import.
Your ArmNN library instance does not support Onnx models parser functionality.  Skipped IOnnxParser import.
Your ArmNN library instance does not support TF models parser functionality.  Skipped ITfParser import.
face_detection(2).mp4
766
Preferred backends: ['CpuAcc', 'CpuRef']
IDeviceSpec { supportedBackends: [CpuAcc, CpuRef]}
Optimization warnings: ()
Traceback (most recent call last):
  File "/home/pi/pyarmnn/examples/object_detection/run_video_file.py", line 97, in <module>
    main(args)
  File "/home/pi/pyarmnn/examples/object_detection/run_video_file.py", line 54, in main
    executor = ArmnnNetworkExecutor(args.model_file_path, args.preferred_backends)
  File "/home/pi/pyarmnn/examples/object_detection/../common/network_executor.py", line 96, in __init__
    self.network_id, self.runtime, self.input_binding_info, self.output_binding_info = create_network(model_file,
  File "/home/pi/pyarmnn/examples/object_detection/../common/network_executor.py", line 52, in create_network
    net_id, _ = runtime.LoadNetwork(opt_network)
  File "/usr/lib/python3/dist-packages/pyarmnn/_generated/pyarmnn.py", line 4014, in LoadNetwork
    return _pyarmnn.IRuntime_LoadNetwork(self, network, networkProperties)
RuntimeError: An error occurred when preparing the network workloads:  Convolution2dQueueDescriptor: input & weight must have identical data types.
```

and finally fully quantized INT8 tflite model, obtained as in https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only

```
pi@raspberrypi:~/pyarmnn/examples/object_detection $ python3 run_video_file.py --video_file_path ../samples/test.mp4 --model_file_path YOLO_best_mAP_fullint.tflite --model_name yolo_v2 --label_path labelmap_face.txt 
Your ArmNN library instance does not support Caffe models parser functionality.  Skipped ICaffeParser import.
Your ArmNN library instance does not support Onnx models parser functionality.  Skipped IOnnxParser import.
Your ArmNN library instance does not support TF models parser functionality.  Skipped ITfParser import.
face_detection(3).mp4
766
Preferred backends: ['CpuAcc', 'CpuRef']
IDeviceSpec { supportedBackends: [CpuAcc, CpuRef]}
Optimization warnings: ()
Processing frames:   0%|                                                                                                                    | 0/766 [00:00<?, ?it/s]/home/pi/pyarmnn/examples/object_detection/yolov2.py:73: RuntimeWarning: overflow encountered in exp
  return 1. / (1. + np.exp(-x))
Processing frames: 100%|##########################################################################################################| 766/766 [00:54<00:00, 13.99it/s]
Finished processing frames
Average time(ms):  40.0
FPS:  25.0
```

As you can see INT8 average inference time is 40 ms, while FLOAT32 is 20 ms.
