### ISSUE TITLE
Cannot make inference on a tflite quantized model

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#512]
I trained and quantized a TF2 model and then converted to tflite. I tried to perform inference with PyArmnn but I got the following warnings and errors:

_**Traceback (most recent call last):
  File "main.py", line 121, in <module>
    input_binding_info, output_tensors, runtime = initialize_interpreter(model_path)
  File "main.py", line 84, in initialize_interpreter
    opt_network, messages = ann.Optimize(network, preferredBackends, runtime.GetDeviceSpec(), ann.OptimizerOptions())
  File "/usr/lib/python3.7/site-packages/pyarmnn/_generated/pyarmnn.py", line 3380, in Optimize
    return _pyarmnn.Optimize(*args)
RuntimeError: WARNING: Layer of type Quantize is not supported on requested backend VsiNpu for input data type Float32 and output data type QAsymmS8 (reason: Npu quantize: output type not supported.
), falling back to the next backend.WARNING: Layer of type Convolution2d is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu convolution2d: Uint8UnbiasedConvolution not supported.
Npu convolution2d: input is not a supported type.
Npu convolution2d: output is not a supported type.
Npu convolution2d: weights is not a supported type.
Npu convolution2d: input and weights types mismatched.
), falling back to the next backend.WARNING: Layer of type Activation is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu activation: input type not supported.
Npu activation: output type not supported.
), falling back to the next backend.WARNING: Layer of type DepthwiseConvolution2d is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu DepthwiseConvolution2d: input is not a supported type.
Npu DepthwiseConvolution2d: output is not a supported type.
Npu DepthwiseConvolution2d: weights is not a supported type.
Npu DepthwiseConvolution2d: input and weights types mismatched.
), falling back to the next backend.WARNING: Layer of type Activation is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu activation: input type not supported.
Npu activation: output type not supported.
), falling back to the next backend.WARNING: Layer of type Convolution2d is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu convolution2d: Uint8UnbiasedConvolution not supported.
Npu convolution2d: input is not a supported type.
Npu convolution2d: output is not a supported type.
Npu convolution2d: weights is not a supported type.
Npu convolution2d: input and weights types mismatched.
), falling back to the next backend.WARNING: Layer of type Convolution2d is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu convolution2d: Uint8UnbiasedConvolution not supported.
Npu convolution2d: input is not a supported type.
Npu convolution2d: output is not a supported type.
Npu convolution2d: weights is not a supported type.
Npu convolution2d: input and weights types mismatched.
), falling back to the next backend.WARNING: Layer of type Activation is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu activation: input type not supported.
Npu activation: output type not supported.
), falling back to the next backend.WARNING: Layer of type Pad is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu pad: input dimension not support.
), falling back to the next backend.WARNING: Layer of type DepthwiseConvolution2d is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu DepthwiseConvolution2d: input is not a supported type.
Npu DepthwiseConvolution2d: output is not a supported type.
Npu DepthwiseConvolution2d: weights is not a supported type.
Npu DepthwiseConvolution2d: input and weights types mismatched.
), falling back to the next backend.WARNING: Layer of type Activation is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu activation: input type not supported.
Npu activation: output type not supported.
), falling back to the next backend.WARNING: Layer of type Convolution2d is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu convolution2d: Uint8UnbiasedConvolution not supported.
Npu convolution2d: input is not a supported type.
Npu convolution2d: output is not a supported type.
Npu convolution2d: weights is not a supported type.
Npu convolution2d: input and weights types mismatched.
), falling back to the next backend.WARNING: Layer of type Convolution2d is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu convolution2d: Uint8UnbiasedConvolution not supported.
[...]
Npu convolution2d: input is not a supported type.
Npu convolution2d: output is not a supported type.
Npu convolution2d: weights is not a supported type.
Npu convolution2d: input and weights types mismatched.
), falling back to the next backend.WARNING: Layer of type Activation is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu activation: input type not supported.
Npu activation: output type not supported.
), falling back to the next backend.WARNING: Layer of type Mean is not supported on requested backend VsiNpu for input data type QAsymmS8 and output data type QAsymmS8 (reason: Npu Mean: input type not supported.
), falling back to the next backend.WARNING: Layer of type Mean is not supported on requested backend CpuAcc for input data type QAsymmS8 and output data type QAsymmS8 (reason: in validate_config src/runtime/NEON/functions/NEReduceMean.cpp:48: ITensor data type QASYMM8_SIGNED not supported by this kernel), falling back to the next backend.WARNING: Layer of type Mean is not supported on requested backend CpuRef for input data type QAsymmS8 and output data type QAsymmS8 (reason: in validate_config src/runtime/NEON/functions/NEReduceMean.cpp:48: ITensor data type QASYMM8_SIGNED not supported by this kernelReference Mean: input type not supported.
), falling back to the next backend.ERROR: Layer of type Mean is not supported on any preferred backend [VsiNpu CpuAcc CpuRef ]**_

How can I fix these problems?

**Comment by MatthewARM** [comment]
Hi @FSet89 what version of ArmNN and Compute Library are you using? 

It seems your TfLite model is using int8 quantisation (which in Arm NN is called "QASYMM8_SIGNED"), but your version of Arm NN and Compute Library doesn't have support for "Mean" using QASYMM8_SIGNED.

I can't comment on the VsiNpu backend as that is a separate project maintained outside of Arm NN.

**Comment by MatthewARM** [comment]
I just checked the release notes for Compute Library: https://arm-software.github.io/ComputeLibrary/v20.11/#S2_2_changelog

QASYMM8_SIGNED support for NEReduceMean was added in the 20.05 release. Are you using a version at least as recent as 20.05?

**Comment by FSet89** [comment]
Hi, thank you for your quick reply. I think I have an older version. Is there a workaround for tflite models or is it better to update it?

**Comment by MikeJKelly** [comment]
Hi @FSet89 

I would suggest you update ArmNN and ComputeLibrary to the most recent version, there have been numerous bug fixes and improvements made to both including the QASYMM8_SIGNED support you need.

Best regards,
Mike

**Comment by MatthewARM** [comment]
I'm quite biased, so I'd say it's best to update, as there's lots of feature and performance improvements in every release :-)

However, there _is_ a possible workaround, which is to quantise using the 'old' quantisation method in Tensorflow which produces uint8 (rather than int8) quantisation. I know this is still available via an option somehow but I don't know how to use it, or how limited it is in recent Tensorflow.
