### ISSUE TITLE
Segmentation fault when loading uint8 tflite model

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#513]
I converted a TF model to tflite using this code:

```
converter = tf.lite.TFLiteConverter.from_keras_model(trained_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.uint8]
quantized_tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(quantized_tflite_model)
```
Then I tried to make inference using pyArmnn:

```
parser = ann.ITfLiteParser()  
network = parser.CreateNetworkFromBinaryFile("converted_model.tflite")
graph_id = 0
input_names = parser.GetSubgraphInputTensorNames(graph_id)
input_binding_info = parser.GetNetworkInputBindingInfo(graph_id, input_names[0])
input_tensor_id = input_binding_info[0]
input_tensor_info = input_binding_info[1]
```
However, I get a segmentation fault when the model is loaded. This does not happen if I remove the line `converter.target_spec.supported_types = [tf.uint8]`, but my current Compute Library version does not support signed integers so I need it. Is this a bug?

**Comment by FrancisMurtagh-arm** [comment]
Hi @FSet89,

Would you be able to share the model, so I could try it out?

My assumption is without the line "converter.target_spec.supported_types = [tf.uint8]" the model doesn't get quantized as the default is float32?
![image](https://user-images.githubusercontent.com/44639508/109143125-96c0a600-7757-11eb-9954-633970ca0385.png)
https://www.tensorflow.org/api_docs/python/tf/lite/TargetSpec

There could be some issue when using uint8 with one of the operators.

Thanks,
Francis.

**Comment by MikeJKelly** [comment]
Hi @FSet89 

Can you clarify the versions of ArmNN and ComputeLibrary that you are using please and provide more details on the seg fault? 

Best regards,
Mike

**Comment by FrancisMurtagh-arm** [comment]
Closed due to lack of activity.
