### ISSUE TITLE
ArmNN still builds static libs even with -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#514]
ArmNN still builds static libs even with `-DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF`

This is a problem for Linux distributions which usually only package dynamic libs, not static ones.

This lead to `/usr/lib64/cmake/armnn/ArmnnTargets.cmake` containing some `STATIC` refs and make some 3rd party builds to fail since the package dropped the static libs.

The problematic static libs are:
```
/usr/lib64/libarmnnUtils.a 
/usr/lib64/libfmt.a
/usr/lib64/libpipeCommon.a
```

**Comment by FrancisMurtagh-arm** [comment]
Hi @ggardet,

For our Debian packaging we use .install files to selectively package just the shared libraries we want, is that something these distribution can do? 

Or is it at the build stage the packaging tooling refuses to create the static libraries and so they end up not being linked to libarmnn.so etc?

Thanks,
Francis.

**Comment by ggardet** [comment]
@FrancisMurtagh-arm 
Yes, static libs are dropped from the RPM package to only install shared libs, but the problem is `ArmnnTargets.cmake` still states we need to link to those static libs which are not available for the user.

**Comment by MatthewARM** [comment]
Hmm, those three libraries are implementation details and ideally shouldn't be exported _at all_. But I guess they need to be, to satisfy linking of static Arm NN where that's needed.

So really what we need here is something like GNU Libtool's "Convenience Library" feature (https://www.gnu.org/software/automake/manual/html_node/Libtool-Convenience-Libraries.html).

I wonder if CMake has such a feature?
