### ISSUE TITLE
Cannot specifiy gpuacc in TfLiteBenchmark-Armnn

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#516]
Patch in https://review.mlplatform.org/c/ml/armnn/+/51 
@jimfly01 
Please review and merge . 
Thanks.

**Comment by FrancisMurtagh-arm** [comment]
Hi Keith,

I'll look into this now.
https://review.mlplatform.org/c/ml/armnn/+/5198

Francis.

**Comment by FrancisMurtagh-arm** [comment]
Hi Keith,

I left some small comments on the review. Overall fix makes sense though.

Thanks,
Francis.
