### ISSUE TITLE
dockerfile is out dated and does not build

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#518]
cd docker/x86_64
docker build  --rm --tag armnn:v1 . 

Build will failed with 
src/core/NEON/kernels/arm_conv/pooling/kernels/a64_s8q_nhwc_avg_generic_depthfirst/generic.cpp: In function ‘void arm_conv::pooling::a64_s8q_nhwc_avg_generic_depthfirst_impl(uint64_t, uint64_t, uint64_t, const int8_t* const*, int8_t*, const arm_conv::pooling::Requantize32&)’:
src/core/NEON/kernels/arm_conv/pooling/kernels/a64_s8q_nhwc_avg_generic_depthfirst/generic.cpp:90:45: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if (static_cast<int64_t>(rescale_value) == (1ll << 31))
     
Then after adding Werror=0 in scons in Dockerfile when building ComputeLibrary.
Got following errors for FLATBUFFERS_INCLUDE_PATH:
CMake Warning at src/backends/cl/CMakeLists.txt:11 (message):
  flatc not found.  Specify the full path of the flatc executable with
  -DFLATC=<flatc path>

-- Adding object library dependency to armnn: armnnBackendsCommon
-- Adding object library dependency to armnn: armnnAclCommon
-- Adding object library dependency to armnn: armnnRefBackend
-- Adding object library dependency to armnn: armnnRefBackendWorkloads
-- Adding object library dependency to armnn: armnnNeonBackend
-- Adding object library dependency to armnn: armnnNeonBackendWorkloads
-- Adding object library dependency to armnn: armnnClBackend
-- Adding object library dependency to armnn: armnnClBackendWorkloads
-- Adding object library dependency to UnitTests: armnnBackendsCommonUnitTests
-- Adding object library dependency to UnitTests: armnnAclCommonUnitTests
-- Adding object library dependency to UnitTests: armnnRefBackendUnitTests
-- Adding object library dependency to UnitTests: armnnNeonBackendUnitTests
-- Adding object library dependency to UnitTests: armnnClBackendUnitTests
-- CMAKE_CURRENT_LIST_DIR /root/armnn
-- CMAKE_CURRENT_BINARY_DIR /root/armnn/build
-- Configuring incomplete, errors occurred!
See also "/root/armnn/build/CMakeFiles/CMakeOutput.log".
See also "/root/armnn/build/CMakeFiles/CMakeError.log".
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FLATBUFFERS_INCLUDE_PATH
   used as include directory in directory /root/armnn/src/backends/cl
   used as include directory in directory /root/armnn/src/backends/cl
   used as include directory in directory /root/armnn/src/backends/cl
   used as include directory in directory /root/armnn/src/backends/cl
   used as include directory in directory /root/armnn/src/backends/cl
   used as include directory in directory /root/armnn/src/backends/cl
   used as include directory in directory /root/armnn/src/backends/cl

**Comment by ek9852** [comment]
Fix in https://review.mlplatform.org/c/ml/armnn/+/5285
We might still need to add onnx support.
And I would prefer to the deprecate the procedures in BuildGuideCrossCompilation.md.
Just ask user to refer to the DockeFile in docker/x86_64/DockerFile.
The procedures are self-explained in the DockerFile. Then we just maintain the DockerFile.
And have  the dockerfile auto build in the gerrit server to make sure build does not breaks with new PR.

And we don't want user to copied and paste procedures in MD readme and  waste few hours in waiting and copy paste the procedures. A dockerfile is enough for documentation and a quick build prototype.

**Comment by ek9852** [comment]
Updated patchset 3
Add onnx parser to dockerfile also.
And I need to disable all warning in armnn in the dockerfile due to this:https://github.com/ARM-software/armnn/issues/519

**Comment by FrancisMurtagh-arm** [comment]
Hi Keith,

I'm looking into the review for this now, thanks for the contribution.

Francis.
