### ISSUE TITLE
Build error when Werror on when BUILD_TESTS enable

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#519]
abs is int type not float type !!!

/root/armnn-devenv/armnn/tests/TfLiteYoloV3Big-Armnn/TfLiteYoloV3Big-Armnn.cpp: In function ‘void CheckAccuracy(std::vector<float>*, std::vector<float>*, std::vector<float>*, std::vector<float>*, const std::vector<yolov3::Detection>&, const std::vector<std::__cxx11::basic_string<char> >&)’:
/root/armnn-devenv/armnn/tests/TfLiteYoloV3Big-Armnn/TfLiteYoloV3Big-Armnn.cpp:265:62: error: conversion to ‘int’ from ‘__gnu_cxx::__alloc_traits<std::allocator<float> >::value_type {aka float}’ may alter its value [-Werror=float-conversion]
                 compare = abs(expected[j] - outputs[i]->at(j));
                if (compare > 0.001f)
                {
                    count++;
                }                                                              ^
/root/armnn-devenv/armnn/tests/TfLiteYoloV3Big-Armnn/TfLiteYoloV3Big-Armnn.cpp:265:25: error: conversion to ‘float’ from ‘int’ may alter its value [-Werror=conversion]
                 compare = abs(expected[j] - outputs[i]->at(j));
                         ^
                 if (compare > 0.001f)
                {
                    count++;
                }

**Comment by ek9852** [comment]
Fix in https://review.mlplatform.org/c/ml/armnn/+/5291

**Comment by FrancisMurtagh-arm** [comment]
Hi @ek9852,

I've commented on the fix, could you use std::abs just to align with our codebase.

Thanks for contribution,
Francis.

**Comment by FrancisMurtagh-arm** [comment]
I've merged that review now.

Thanks again,
Francis.
