### ISSUE TITLE
armnn is not supported layer Deconvolution

### ISSUE THREAD

**Issue by Wayne-pw** [ARM-software/armnn#52]
hello
    I run a network(caffe network) with deconvolution layer，there are some errors:

WARNING: linker: /data/armnn_caffe_test: unsupported flags DT_FLAGS_1=0x8000000
WARNING: linker: /system/lib64/libarmnnCaffeParser.so: unused DT entry: type 0xf
 arg 0x2dbdd
terminating with uncaught exception of type armnn::ParseException: Unsupported l
ayer type 'Deconvolution'
Aborted

armnn is not supported deconvolution?

**Comment by Surmeh** [comment]
Hi @Wayne-pw,

We currently do not have the support for Deconvolution layer. If you could comment about the model you're using I can make sure that information is made available to the development team.

You can also check the below documentation which mentions the layers supported by ArmNN.
https://github.com/ARM-software/armnn/blob/master/src/armnnCaffeParser/CaffeSupport.md
https://github.com/ARM-software/armnn/blob/master/src/armnnTfParser/TensorFlowSupport.md

Thanks,
Surabhi

**Comment by Surmeh** [comment]
Hi @Wayne-pw,

It would be great if you could provide us with the model information. If not, I completely understand.

Thanks,
Surabhi
