### ISSUE TITLE
Reduce layer does not support axis

### ISSUE THREAD

**Issue by ek9852** [ARM-software/armnn#521]
trunk
model: 
[memnet_float.tflite.zip](https://github.com/ARM-software/armnn/files/6174277/memnet_float.tflite.zip)

NEON
Warning: WARNING: Layer of type Reduce is not supported on requested backend CpuAcc for input data type Float32 and output data type Float32 (reason: NeonReduceWorkload: Reduction is supported only on 1 axis.), falling back to the next backend.
Warning: ERROR: Layer of type Reduce is not supported on any preferred backend [CpuAcc ]

CL:
Warning: WARNING: Layer of type Reduce is not supported on requested backend GpuAcc for input data type Float32 and output data type Float32 (reason: ClReduceWorkload: Reduction is supported only on 1 axis.), falling back to the next backend.
Warning: ERROR: Layer of type Reduce is not supported on any preferred backend [GpuAcc ]
Fatal: Armnn Error: Failed to assign a backend to each layer
Info: Shutdown time: 13.37 ms

**Comment by TeresaARM** [comment]
This request originates with this other one: https://github.com/ARM-software/armnn/issues/501

**Comment by ek9852** [comment]
@MikeJKelly  We possibly need to do a reshape before doing reduction if backend does not support more than 1 axis.

**Comment by matthewsloyanARM** [comment]
Hi @ek9852, 

I am currently looking into adding this support. Thank you!

Kind regard,

Matthew

**Comment by MikeJKelly** [comment]
Matthew's patch to add support for this has been merged so this should work now, can you confirm @ek9852 : 
https://review.mlplatform.org/c/ml/armnn/+/5550

**Comment by matthewsloyanARM** [comment]
Thanks @MikeJKelly for adding this, there was also a follow up patch to fix a bug which can be found here: https://review.mlplatform.org/c/ml/armnn/+/5714. Would you be able to try both of these @ek9852?

Thank you!

Kind regards,

Matthew

**Comment by matthewsloyanARM** [comment]
Hi @ek9852,

I am closing this ticket as it has been implemented. However, do let us know if it works for you and if there is anything else we can do feel free to let us know. Thanks again!

Kind regards,

Matthew
