### ISSUE TITLE
Argmax erros when loading TFLite model

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#523]
HI,

In ARM NN 21.02, argmax layer is supported, and we've tried with our tfLite model in CpuRef mode.

However, when using ARM NN to interpret our model, there is a error "Invalid dimension index: 4 (number of dimensions is 4) at function CheckDimensionIndex [Tensor.cpp:279]" in the corresponding argmax layer. 

We've also printed some messages from function "ArgMinMaxLayer::InferOutputShapes" in armnn/layers/ArgMinMaxLayer.cpp, the error happens because **unsignedAxis==255** which is not compatible with the dimension of variable "**inputShape==4**".

```
        std::vector<unsigned int> tensorDimensions(inputNumDimensions - 1, 0);
        for (unsigned int i = 0; i < unsignedAxis; ++i)
        {
            tensorDimensions[i] = inputShape[i];
        }
```
The following is the tensor size of the argmax layer in our model: 1x 256x 512x 19. We want to ask:

1. Is there any solution to this problem?
2. Is there specific requirement of dimension of argmax layer?
3. How does layer "ArgMinMaxLayer" work? Does it work the same as ArgMax layer in TensorFlow?

**Comment by FrancisMurtagh-arm** [comment]
Hi @Rahn80643,

Would you be able to provide the tflite model?

Do you know what the Axis is? Or is it the default -1?

ArgMinMaxLayer works the same as ArgMax as long as descriptor's m_Function = ArgMinMaxFunction::Max


Thanks,
Francis.

**Comment by Rahn80643** [comment]
Hi @FrancisMurtagh-arm ,
Thank you for your reply. 
1. The following steps show how we create the TFLite model, and the axis of the model is set as -1:
    (1) convert TensorFlow ckpt file to pb file
    (2) convert pb file to TFLite file

2. The parser we use is `armnnTfLiteParser::ITfLiteParser;`

3. The attachments are the the pb and tflite file of our model

Thanks,
Rahn80643.
[model.tar.gz](https://github.com/ARM-software/armnn/files/6225870/model.tar.gz)

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643, 

Thank you for supplying the information and the model files. It is much appreciated.

I am looking into this for you now. Thanks!

Kind regards,

Matthew

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643, 

This issue has been resolved with [28f177c](https://github.com/ARM-software/armnn/commit/28f177c45cb8e23b86c9f3ff435921183340fc33) which is currently on the master branch here on GitHub. Would you be able to checkout this branch and pull the latest changes to see if it fixes it for you? 

Thank you, have a nice weekend!

Kind regards,

Matthew

**Comment by Rahn80643** [comment]
@MatthewARM,
I have used the patch to rebuild my ARM NN; however, there is an error during compilation:

`Linking CXX executable GatorMock
libarmnn.so.25.0: undefined reference to armnnarmnn::experimental::WorkingMemHandle::WorkingMemHandle(int, std::vector<armnn::experimental::WorkingMemDescriptor, std::allocator<armnn::experimental::WorkingMemDescriptor> >, std::unordered_map<armnn::profiling::ProfilingGuid, armnn::experimental::WorkingMemDescriptor, std::hash<armnn::profiling::ProfilingGuid>, std::equal_to<armnn::profiling::ProfilingGuid>, std::allocator<std::pair<armnn::profiling::ProfilingGuid const, armnn::experimental::WorkingMemDescriptor> > >)'
 `

The following are the steps I used to rebuild the project:
1. Clone the arm nn repository
2. Update to the patch inside directory `armnn` with command: `git checkout 28f177c45cb8e23b86c9f3ff435921183340fc33`
3. Follow the [compilation tutorial](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/cross-compiling-arm-nn-for-the-raspberry-pi-and-tensorflow/building-arm-nn) to compile the arm nn, `-DARMCOMPUTENEON=1 and -DARMCOMPUTECL=1` are also added for hardware acceleration support.

Is the error caused by settings of my cmake parameters or other possible bug?

Best regards,
Rahn. 

![20210413_make_error_ARMNN_argmax_patch](https://user-images.githubusercontent.com/8951991/114640073-f07a3100-9d01-11eb-9a63-c049b0d52ae1.png)

**Comment by MatthewARM** [comment]
I've not seen that particular error before, I'll try building that hash from scratch to see if I have the same problem. Most likely this would be a possible bug in the build system, rather than a problem with your cmake parameters.

**Comment by matthewsloyanARM** [comment]
Thanks @MatthewARM for testing this out natively. I will try to cross-compile later today to see if I can reproduce this.

Kind regards,

Matthew

**Comment by Rahn80643** [comment]
Hi @MatthewARM,
I solved the error by rebuilding my environment, I think the error was caused by the settings in my cmake options.
Now the model with argmax layer is successfully loaded and executed

Thank you so much for your help!
Rahn

**Comment by matthewsloyanARM** [comment]
I am just after cross compiling and I wasn't seeing any issues either, but that's great I am glad to hear that! Thank you for reaching out and if you have any further questions feel free to create an issue anytime.

Thanks again, all the best!

Kind regards,

Matthew
