### ISSUE TITLE
 Operators breakdown

### ISSUE THREAD

**Issue by prabhakarlad** [ARM-software/armnn#525]
Hi All,

Is it possible to get a breakdown of which operators is executing on which H/W (CPU/GPU) ?

Cheers,
Prabhakar

**Comment by morgolock** [comment]
Hi @prabhakarlad 

Normally it's up to you to specify which backend you wish the workloads to be executed, for example with the tool ExecuteNetwork https://github.com/ARM-software/armnn/tree/branches/armnn_21_02/tests/ExecuteNetwork you use the -c option to choose either CpuAcc or GpuAcc.

The option -e is very useful too, it will generate a json file with all the kernel names executed and the time it took them to run.

All workloads will run using a single backend.

Hope this helps.

**Comment by prabhakarlad** [comment]
Hi @morgolock

Thanks for the pointer, ill give that a try.

unrelated query is there a tool to convert jpg to snpy files ?

Cheers,
Prabhakar

**Comment by matthewsloyanARM** [comment]
Hi @prabhakarlad, 

There is a nice snippet of code here: https://github.com/ARM-software/armnn/issues/309 that will allow you to convert an image to a .snpy format. However, regarding printing the tensor size it isn't something that I have done myself but it should be possible. Would you have any suggestions for this @MikeJKelly?

Kind regards,

Matthew

**Comment by prabhakarlad** [comment]
Hi @matthewsloyanARM,

Thank for the pointer, script works like a charm.

Cheers,
Prabhakar

**Comment by matthewsloyanARM** [comment]
Hi @prabhakarlad, 

No problem, I am glad to hear it! I will close this Issue now if that is okay? If you have any questions feel free to reopen the ticket anytime or create a new one.

Thanks again for reaching out!

Kind regards,

Matthew
