### ISSUE TITLE
Integrate TFLite Delegate into TfLite in C++

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#527]
Hi,
The document [Integrate delegate using Python](https://arm-software.github.io/armnn/latest/md_delegate__integrate_delegate_into_python.xhtml) shows how to use TFLite delegate with ARM NN using Python. 

Is it possible to integrate TFLite delegate using **C++**? If so, is there any tutorial or sample to do this?

Thank you

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643,

Yes it certainly is. At the bottom of the Arm NN Delegate build guide is a small snippet that shows how it can be achieved. This can be found here: https://arm-software.github.io/armnn/latest/md_delegate__build_guide_native.xhtml

In the codebase there is a number of examples of it being used which may be helpful too. E.g. In the ExecuteNetwork TfLiteDelegateMainImpl function there is an example which can be found in `armnn/tests/ExecuteNetwork/ExecuteNetwork.cpp`. Also, there are multiple nice examples within the `TestHelper.hpp` files for each operator. These can be found in the `armnn/delegate/src/test` directory. 

I hope this helps, but if you have any further questions feel free to reach out. Thank you!

Kind regards,

Matthew

**Comment by Rahn80643** [comment]
Hi @MatthewARM,
Thank you for providing the information of sample. Since the hardware we use contain both GPU and NPU, we want to ask:

1. Is it possible to assign a certain operation to be executed in GPU or NPU by using TFLite delegate?
2. How to copy and transfer data between GPU and NPU?
3. The tutorial of [TFLite delegate model](https://www.tensorflow.org/lite/performance/gpu) mainly focus on mobile devices, but our system will be an embedded system. Is there other tutorial of TFLite delegate for creating TFLite delegate model for embedded systems?
4. Do ARM NN/ TFLite delegate support both TensorFlow 1 and TensorFlow 2 model ?

Thank you,
Rahn

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643, 

You're very welcome, I will reply to your questions in the same manner as above.

1. Yes, you can call this function below with your with your backend's ID, this will provide a hint for the optimizer as to which backend to prefer for this layer. This is declared in the armnn/include/INetwork.hpp interface.
```
void BackendSelectionHint(Optional<BackendId> backend) final
{
      m_BackendHint = backend;
}
```
2. This should be handled by the TFLite Delegate and ArmNN.
3. The tutorial I provided above is the only ArmNN tutorial at the moment. However, embedded systems are supported by TensorFlow Lite as seen [here](https://www.tensorflow.org/lite/guide/inference), to use the ArmNN TFLite Delegate you simply have to plug the ArmNN delegate into the TFLite Interpreter. The ArmNN TFLite Delegate can use any TFLite Lite model (.tflite). These models can be converted using [TensorFlow Lite Converter.](https://www.tensorflow.org/lite/convert/index) I hope this answers your question.
4. The Arm TFLite Delegate uses TensorFlow version 2.3.1 so any model supported by this version should work with the delegate. It will need TFLite models. If you have TF models you can convert them with the TensorFlow Lite Converter as mentioned above.

Thank you!

Kind regards,

Matthew

**Comment by Rahn80643** [comment]
Hi @MatthewARM, 
Thank so much for providing the information, we have successfully loading a MobileNetv1 classifier model with TFLite delegate parser based on `armnn/tests/ExecuteNetwork/ExecuteNetwork.cpp`

The following are questions we want to figure out:
1. From the [tutorial](https://arm-software.github.io/armnn/latest/md_delegate__integrate_delegate_into_python.xhtml), does libarmnnDelegate.so in PyARMNN provide the API of ArmNN delegate for Python to call?
2. Based on the list of supported operations of [ArmNN TFLite parser](https://github.com/ARM-software/armnn/releases/tag/v21.02) and [TFLite delegate, gpu advanced](https://www.tensorflow.org/lite/performance/gpu_advanced). If a model contains ARGMAX operation which doesn't appear in supported list of TFLite delegate, will the model be interpreted successfully with ArmNN TFLite delegate parser?
3. Is it possible to mixedly use ARMNN TF lite parser and TFLite delegate to parser a single model at the same time, and assign specific operation to a certain parser? For example, loading a MobileNetv1 classifier, and assign ArmNN TFLite to execute the first convolution operation, and TFLite delegate to execute the rest of convolution operations.
4. When a model is parsed through TFLite delegate parser, it is possible to split the model into two parts, the first part is executed on NPU, and the second part is executed on GPU?
5. If a model whose operations are partially supported in NPU can be fully interpreted by TFLite delegate parser, will these unsupported operations be executed in GPU without the implentation of backend?
6. In our understanding, the requred reserved memory for NPU is 256MB. Is the memory stored for temporary processed data? How to make sure the processed data tranfered between GPU and NPU?
7. The role of [TFLite custom delegate](https://www.tensorflow.org/lite/performance/implementing_delegate)  looks similar to `ArmNN backend`, both of these features allows users to implement a custom operation. What's the difference between these features?
8. Is it possible to provide a list of supported operations of TFLite parser for NPU?

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643, 

You're very welcome and that's great news! Of course, I will do my best to answer them below and I will update 7 & 8 once I have more information.

1. Yes the libarmnnDelegate.so provides the API for the ArmNN TFLiteDelegate.
2. ARG_MAX is supported by the ArmnNN TFLiteParser and ArmNN TFLiteDelegate but I am currently working on a fix for the TFLiteParser implementation when the axis is negative. ARG_MIN support will also be added in this patch for the TFLiteParser. However, with the ArmNN TFLiteDelegate if there is an operator that isn't supported it will fallback to the TFLite default implementation, whereas with the ArmNN TFLiteParser it simply won't run.
3. I think there maybe some confusion here between the [ArmNN TFLiteParser](https://arm-software.github.io/armnn/latest/parsers.xhtml#S6_tf_lite_parser) and the [ArmNN TFLiteDelegate](https://arm-software.github.io/armnn/latest/delegate.xhtml). Both provide the same accelerated operator support and performance. The difference resides the benefits, how it is created and how it is used. The ArmNN TFLiteDelegate plugs into TFLite's own interpreter as seen in the ArmNN TFLiteDelegate build guide. The TFLiteParser is created using the ArmNN TFLiteParser API as seen in this [guide](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/deploying-a-quantized-tensorflow-lite-mobilenet-v1-model-using-the-arm-nn-sdk/write-your-application). So both wouldn't be used together if that makes sense. Also, you have the fallback benefit mentioned in point 2 with the ArmNN TFLite Delegate so it can be used to execute any TFLite model. A full list of accelerated operators can be found [here](https://arm-software.github.io/armnn/latest/delegate.xhtml#delegatefullysupported). 
4. Yes you should be able to split it on a layer by layer basis, you can specify which backend a layer will run on using the `BackendSelectionHint` method mentioned in my previous comment.
5. If unsupported in the preferred backend it will fallback to the next available backend.
6. I am not too sure about this question, however, the data transfer should be handled by the ArmNN TFLiteDelegate and ArmNN for you.

Thank you!

Kind regards,

Matthew

**Comment by Rahn80643** [comment]
Hi @matthewsloyanARM 

Thank you for your reply, the information is very helpful.
I will try to use the function `BackendSelectionHint` into our code.

Thank you!
Best regards,
Rahn
