### ISSUE TITLE
a53 fp16-turbo-mode

### ISSUE THREAD

**Issue by prabhakarlad** [ARM-software/armnn#535]
Hi,

While doing some comparisons between a55 and a53 (dual cores both running on same clock speeds), when fp16-turbo-mode is used on A55 I see a reduced times for inference times, but when I run the same model on A53 I see inference time is more when  fp16-turbo-mode is enabled.

Machine A with has dual a53 has NEON™/VFPv4 supported
Machine B with has  dual a55 (r2p0) has NEON™ FPU engine supported

Note for both the machines inference is run on CPU backend.

Any thoughts is this expected on a53 ?

Cheers,
Prabhakar

**Comment by morgolock** [comment]
Hi @prabhakarlad

The A55 supports FP16 whereas A53 doesn't, you wont see any gains using turbo mode on CPUs without support for FP16

Hope this helps

**Comment by prabhakarlad** [comment]
Thanks @morgolock
