### ISSUE TITLE
Apply BackendSelectionHint with tfLite parser

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#536]
Hi, 

I'm trying to apply Hint from the info of [this post](https://github.com/ARM-software/armnn/issues/527#issuecomment-823044051) and **armnn/src/backends/cl/ClFallbackTests.cpp** to my program with TfLite parser and TfLite Delegate parser respectively.

I found that the procedure in **ClFallbackTests.cpp** is: the network is constructed manually with IConnectableLayer*, specific backend to the layer is assigned with `BackendSelectionHint()`, and the network is optimized.
However, I load the network with `ITfLiteParser -> CreateNetworkFromBinaryFile` and get the optimizedNet with `armnn::Optimize()` in my program. Since I couldn't find public method in INetwork to get a layer, I couldn't call `BackendSelectionHint()` to the layer that I want it to be executed in a certain backend.

My questions are:
1. Is it possible to call `BackendSelectionHint()` after `ITfLiteParser -> CreateNetworkFromBinaryFile` and before `armnn::Optimize()`? 
2. Is `BackendSelectionHint()` only set with the network is created by `IConnectableLayer*` manually?
3. There is no public method to get a layer in `TfLite Delegate parser` either, how can I get a layer after `tfLiteInterpreter->ModifyGraphWithDelegate` and assign desired backend to a layer with `BackendSelectionHint()`?

Best regards,
Rahn

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643, 

Thanks for reaching out about this!

To answer your questions, yes it is only possible to use BackendSelectionHint() when creating the network manually. I have added it to our backlog to add a more generic implementation but there is currently no ETA on when this will be added. 

However, I can refer you to another possible way around it. There is an `IStrategy` public interface which includes a `ExecuteStrategy` method. When creating the network using `armnn::INetworkPtr network = armnnparser->CreateNetworkFromBinaryFile()` you can call `network->ExecuteStrategy(strategy);` and pass in your own strategy that you can create. Within this strategy you could have a switch statement for the layers you want to designate to a specific backend, then set the backend hint for that layer `layer->BackendSelectionHint(cpuAcc);`.

I would be careful slicing your network up too much as swapping between backends can be expensive and in some instances can cause performance decreases. Do let us know if you have any issues with this or have any further questions. Thank you!

Kind regards,

Matthew

**Comment by Rahn80643** [comment]
Hi, thanks for your information,
We've tried to apply `BackendSelectionHint()` in `ExecuteStrategy()` in both `Convolution2dLayer.cpp` and `ArgMinMaxLayer.cpp`.
The procedures are as follows:
1. Function `ExecuteStrategy()` is added inside `ArgMinMaxLayer.cpp`.
2. A variable `layer` is created through `armnn::Layer* layer = const_cast<armnn::Convolution2dLayer*> this` in `Convolution2dLayer.cpp` and `armnn::Layer* layer = const_cast<armnn::ArgMinMaxLayer*> this` in `ArgMinMaxLayer.cpp`.
3. Assign the backend in function `ExecuteStrategy()` inside both `Convolution2dLayer.cpp and `ArgMinMaxLayer.cpp`.
   However,`GetBackendId()` in `ExecuteStrategy()` shows `Unknown` after we apply `BackendSelectionHint()`, so we couldn't examine whether the desired backend is assigned or not.


We want to ask that:
1. Is the steps above correct to assign `BackendSelectionHint()` for both `Convolution2dLayer` and `ArgMinMaxLayer`?
2. In `armnn/src/backends/cl/ClFallbackTests.cpp`, `BackendSelectionHint()` for a layer is set before function `Optimize()` for the network. If `BackendSelectionHint()` is set with `GpuAcc` and `Optimize()` is set with `CpuAcc`, will the backend `GpuAcc` execute the specific layer correctly? We observed that `BackendSelectionHint()` for a layer is set as `GpuAcc`. After `Optimize()` which is set as `CpuAcc`, the result of `GetBackendId()` of a layer shows `CpuAcc`, we though the backend setting of Optimize() has higher priority than `BackendSelectionHint()`, is this correct?

Best regards,
Rahn

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643,

Thank you for trying this out. To answer your first question it seems you are creating a new armnn layer within the ExecuteStrategy method of the Convolution2dLayer.cpp, this won't be the layer in your network so setting the backend hint there I don't think will assign it correctly. What I would suggest to do is implement something like the example in `armnn/src/armnnSerializer/test/ActivationSerializationTests.cpp`. So you will be creating a class which will be your strategy that inherits from IStrategy. It should include a ExecuteStrategy method which will then have your switch/if statements. In these statements you can add `layer->BackendSelectionHint(backend);` for the layers you want to set the backend hint for. When you create the network with `armnn::INetworkPtr network = armnnparser->CreateNetworkFromBinaryFile(networkFile)` you can call `network->ExecuteStrategy(strategy);` after. This will go through your network and set the backend hint for the layers you specify. Hopefully that makes sense.

To answer your second question the BackendSelectionHint() will take priority when assigning the backends to the layers which can be seen in Network.cpp line 933, so I'd imagine they weren't getting set correctly and it was using the preferred CpuAcc backend passed in. Implementing the above suggestion should fix this. Thank you!

Kind regards,

Matthew

**Comment by Rahn80643** [comment]
Hi,
Thank you for provide the correct way to apply BackendSelectionHint in ExecuteStrage, we successfully assigned some layers to be executed in certain backend. 

In addition, since we will use NPU in the near future, does BackendSelectionHint support using NPU backend with the option `EthosNBackendId()` ?

Besk regards,

Rahn

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643, 

No problem and yes it should support it. 

Thanks again for reaching out, if you have any questions feel free to ask anytime.

Kind regards,

Matthew

**Comment by Rahn80643** [comment]
Hi, 
We're trying to apply executeStrategy with BackendSelectionHint to TfLiteDelegateParser as well, but we notice that TfLiteDelegateParser loads models and optimizes networks with `tfLiteInterpreter` which is not `armnn::INetwork`. So we couldn't set BackendSelectionHint to TfLiteDelegateParser through `executeStragegy()`.

Does this means `BackendSelectionHint` cannot be set when:
1. The parser is TfLiteDelegateParser.
2. Instead of building the network manually through ARM NN API, the model is loaded by `tflite::FlatBufferModel::BuildFromFile` and the network is optimized by `tfLiteInterpreter->ModifyGraphWithDelegate()`

Besk regards,

Rahn

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643, 

Yes the TFLite Delegate doesn't expose the INetwork like the TFLite Parser does, so it is not possible currently using the API. However there is a possible workaround. In the `armnn/delegate/src/armnn_delegate.cpp` around line 340 (before optimize and after the graph has been created) you can access the INetwork pointer from here and call ExecuteStrategy like you have done when using the TFLite Parser. Something like the following `delegateData.m_Network->ExecuteStrategy(yourStrategy);`. I haven't tested this but it should work.

Also thank you for letting us know about it and hopefully you can use this as a workaround until we get a solution in place. All the best!

Kind regards, 

Matthew

**Comment by Rahn80643** [comment]
Hi, @MatthewARM,

Thank you for providing the information, I'll try to test the approach.

Best regards,

Rahn
