### ISSUE TITLE
caffe compilation selection

### ISSUE THREAD

**Issue by photoszzt** [ARM-software/armnn#54]
I'm following https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe/setting-up-the-build-dependencies to build armnn. In the tutorial, it doesn't say anything about what specific config I need to make on caffe. 

I want to use both CPU and GPU. But caffe only has a CPU only option. Their default GPU is CUDA. Should I just build a CPU only caffe and it would automatically contains the GPU side invocation? Or should I compile the OpenCL caffe?

**Comment by MatthewARM** [comment]
Hi @photoszzt you can just build the CPU caffe.

For ArmNN, GPU and CPU targets are selected by the ArmNN build system when you follow this step in the documentation: https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe/building-the-environment

**Comment by photoszzt** [comment]
Thanks!
