### ISSUE TITLE
ARM NN hint with scheduling

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#540]
Hi,

We had separate the model into two parts and executed on different backends through "hint": the first part is executed with GpuAcc, and the second part is executed with CpuAcc. 

Since both parts in the model are separated, is it possible to schedule both parts? For example, the first part which is executed on Gpu infers t frame; meanwhile, the second part which is executed on Cpu infers the (t-1) frame.

Best regards,
Rahn

**Comment by MikeJKelly** [comment]
Hi @Rahn80643 

ArmNN cannot currently schedule model execution like that.

Best regards,
Mike

**Comment by keidav01** [comment]
Hi @Rahn80643 

Thank you for reaching out! Based on the updated README.md found [here](https://github.com/ARM-software/armnn/tree/master#how-to-get-involved) under the "How to get involved" section we will be closing GitHub issues labeled with "Feature Request". Instead, we will be tracking the issue and adding the "Help wanted" label. All the issues with this label can be found [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). We would much appreciate your help to add these features. If you would like investigate a fix for this issue feel free to reopen the ticket and let us know you are working on it with a quick comment. We will then track the updates and help you get your additions into our codebase.

Below you will find our contributors guide. If you have any questions feel free to ask here or by creating a new Issue. Thank you!

https://www.mlplatform.org/contributing

Kind regards,
Keith
