### ISSUE TITLE
TFLite with armnn delegate slower on little cortex ?

### ISSUE THREAD

**Issue by n-moussa** [ARM-software/armnn#541]
Hello,

I'm running a tflite model using armnn delegate (based on conv + lstm layers).
It's running on a small cortex A9 (v7l neon vfpv3 32-bits) and the processing time is 3 times slower than tflite model standalone execution (~3ms vs ~1ms).

Is it something that could happen on small cortex ?

Neon option is enabled and backend is CpuAcc.

Thanks for your feedback

**Comment by MikeJKelly** [comment]
Hi @n-moussa 

I would expect it to be faster (or much the same). If parts of the model are unsupported by armnn for one reason or another then execution will fall back to the default tflite implementation. In that case it could be slower as shifting between tflite and the armnn delegate incurs a memory copying cost.

Can you provide some more information please? 

1. How are you determining the processing time, is this the amount of time taken to create the network and run or just the time taken to run the network? 
2. How many times are you running the ? The first inference is always slower.  
3. How large is your model and is it publicly available? What datatype is it (i.e. is it float 32 or int8 for example?) 
4. What version of the tflite delegate are you using?  

Best regards,
Mike

**Comment by n-moussa** [comment]
Hi @MikeJKelly 

Here some more details:

1) I'm measuring the processing time before and after the inference (setting the inputs -> call invoke() function -> setting outputs). It's running inside a thread and this part of the code is the same for tflite standalone and tflite with armnn delegate.

2) It's running several times (hundreds/thousands)

3) Unfortunately the model is not publicly available, it's a small one ( between 200 KBytes - 300 KBytes). It has basic layers such as conv2d, lstm, full connected, reshape, batchnorm). Is the unidirectional lstm supported by armnn delegate ? The datatype is float32.

4) I'm using TFlite 2.4.1 and armnn 21.02.


Thanks!

**Comment by keidav01** [comment]
Hey @n-moussa 

We do not support TfLite 2.4.1, but 2.3.1. It would be worth building TfLite on that branch.

Could I also ask what device you are using for the cortex A9? We may be able to run it and provide some feedback.

Cheers,
Keith

**Comment by n-moussa** [comment]
Hi @keidav01 

I'm using a zynq 7020 platform for the cortex A9.
I'm attaching a tflite model (which is close to the one that I tested).
[model.zip](https://github.com/ARM-software/armnn/files/6471321/model.zip)


I will try with TFLite 2.3.1

Thanks for your feedback!

**Comment by n-moussa** [comment]
Hi @keidav01 

I have tried with TFLite 2.3.1, and I'm having the same performance issue.

**Comment by MatthewARM** [comment]
Probably worth asking about thins on the Compute Library github issues. The performance for Arm NN on Cortex-A CPUs comes from Compute Library (https://github.com/ARM-software/ComputeLibrary). I believe the optimisations for Arm v7 are not as good as the optimisations for Arm v8.

**Comment by n-moussa** [comment]
Is there a way to track and profile the NN model execution when using ArmNN delegate ?

**Comment by n-moussa** [comment]
Is there a way to track and profile the NN model execution when using ArmNN delegate ?

Thanks

**Comment by keidav01** [comment]
Hey @n-moussa,

You can use the benchmark_model tool provided by tensorflow which can be downloaded for your particular platform at the bottom of this link: https://www.tensorflow.org/lite/performance/implementing_delegate.

You can utilize the ArmNN TfLite Delegate through this tool with the flags --external_delegate_path and --external_delegate_options

**Comment by keidav01** [comment]
Hi @n-moussa, 

Have you any further questions? I will close this issue in 2 days otherwise with the assumption that your questions have been satisfied. 

Thank you very much, 
Keith

**Comment by n-moussa** [comment]
Hi @keidav01 

The problem is still occurring and I would like to share my latest update please.

As you advised, I gave a try with the benchmark tool and this time I used a raspberry pi 4 (64-bits CPU A72). When testing the TFLite model with and without armnn delegate, I got a performance drop by almost 10x (using float-32 precision for the model).

~70 µs without armnn delegate
~623 µs with armnn delegate

So the problem is not coming from the HW right?

```
/benchmark_model --graph=ts_75.tflite
STARTING!
Log parameter values verbosely: [0]
Graph: [ts_75.tflite]
Loaded model ts_75.tflite
Going to apply 0 delegates one after another.
The input model file size (MB): 0.184108
Initialized session in 1.304ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=7028 first=2071 curr=69 min=68 max=2071 avg=70.3736 std=24

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=14192 first=93 curr=70 min=68 max=249 avg=69.691 std=5

Inference timings in us: Init: 1304, First inference: 2071, Warmup (avg): 70.3736, Inference (avg): 69.691
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=1.90234 overall=1.90234
```

```
./benchmark_model --graph=ts_75.tflite --external_delegate_path="../armnn-21.02/build/delegate/libarmnnDelegate.so" --external_delegate_options="backends:CpuAcc;logging-severity:info"
STARTING!
Log parameter values verbosely: [0]
Graph: [ts_75.tflite]
External delegate path: [../armnn-21.02/build/delegate/libarmnnDelegate.so]
External delegate options: [backends:CpuAcc;logging-severity:info]
Loaded model ts_75.tflite
Info: ArmNN v24.0.0

Info: Initialization time: 0.26 ms

INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
EXTERNAL delegate created.
Going to apply 1 delegates one after another.
Explicitly applied EXTERNAL delegate, and the model graph will be partially executed by the delegate w/ 3 delegate kernels.
The input model file size (MB): 0.184108
Initialized session in 30.886ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=784 first=1203 curr=564 min=536 max=5798 avg=636.411 std=277

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=1601 first=716 curr=564 min=508 max=10487 avg=623.432 std=347

Inference timings in us: Init: 30886, First inference: 1203, Warmup (avg): 636.411, Inference (avg): 623.432
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=10.6992 overall=10.6992
Info: Shutdown time: 0.33 ms
```

Thank you,
Moussa

**Comment by MatthewARM** [comment]
So I'm guessing the problem here is "Explicitly applied EXTERNAL delegate, and the model graph will be partially executed by the delegate w/ 3 delegate kernels."

I wonder if the overhead of calling out to the delegate for a partial execution is vastly overshadowing any other contribution to execution time.

**Comment by n-moussa** [comment]
When I check the model, I don't find any ops that wouldn't be supported by the delegate..(based on the doc here https://arm-software.github.io/armnn/latest/delegate.xhtml)
It has basic CNN, BN, LSTM, FC.

I need to check why it's going for a partial execution.
There should be some parameter or config that may be not supported by the delegate.

And this is also being higher:
Peak memory footprint (MB): init=10.6992 overall=10.6992

**Comment by MatthewARM** [comment]
BatchNormalization isn't on that list?

**Comment by MatthewARM** [comment]
I would expect the peak memory footprint with the delegate to be higher  - at the very least, it has to load the delegate code into memory.

**Comment by n-moussa** [comment]
In fact, the BN isn't on this list.
But the 'TFLite ops' used to support the BN are simple 'ADD' and 'MUL'.
So, this should not cause the switch between backends.



> I would expect the peak memory footprint with the delegate to be higher - at the very least, it has to load the delegate code into memory.

I see, it makes sense for the memory usage then.

**Comment by kassianl26** [comment]
I have the same issue.
`./linux_aarch64_benchmark_model --graph=model_32bits_float.tflite
STARTING!
Log parameter values verbosely: [0]
Graph: [model_32bits_float.tflite]
Loaded model model_32bits_float.tflite
Going to apply 0 delegates one after another.
The input model file size (MB): 0.019552
Initialized session in 0.969ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=2988 first=296 curr=166 min=145 max=469 avg=166.384 std=7

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=5961 first=175 curr=165 min=143 max=2615 avg=166.798 std=39

Inference timings in us: Init: 969, First inference: 296, Warmup (avg): 166.384, Inference (avg): 166.798
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=1.32812 overall=1.32812
`

`./linux_aarch64_benchmark_model --graph=model_32bits_float.tflite --external_delegate_path="ArmNN-linux-aarch64/libarmnnDelegate.so" --external_delegate_options="backends:CpuAcc;logging-severity:info"
STARTING!
Log parameter values verbosely: [0]
Graph: [model_32bits_float.tflite]
External delegate path: [ArmNN-linux-aarch64/libarmnnDelegate.so]
External delegate options: [backends:CpuAcc;logging-severity:info]
Loaded model model_32bits_float.tflite
Info: ArmNN v25.0.0

Info: Initialization time: 0.86 ms

INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
EXTERNAL delegate created.
Going to apply 1 delegates one after another.
Explicitly applied EXTERNAL delegate, and the model graph will be partially executed by the delegate w/ 1 delegate kernels.
The input model file size (MB): 0.019552
Initialized session in 43.078ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=2533 first=421 curr=212 min=180 max=421 avg=196.386 std=8

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=5072 first=218 curr=196 min=171 max=640 avg=196.159 std=8

Inference timings in us: Init: 43078, First inference: 421, Warmup (avg): 196.386, Inference (avg): 196.159
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=30.7734 overall=30.7734
Info: Shutdown time: 0.17 ms
`

The model is : 
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_2 (LSTM)                (None, 20)                3920      
_________________________________________________________________
flatten_2 (Flatten)          (None, 20)                0         
_________________________________________________________________
output (Dense)               (None, 10)                210       
=================================================================
Total params: 4,130
Trainable params: 4,130
Non-trainable params: 0

**Comment by kassianl26** [comment]
I have the same issue. The model is :
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_2 (LSTM)                (None, 20)                3920      
_________________________________________________________________
flatten_2 (Flatten)          (None, 20)                0         
_________________________________________________________________
output (Dense)               (None, 10)                210       
=================================================================
Total params: 4,130
Trainable params: 4,130
Non-trainable params: 0


 **./linux_aarch64_benchmark_model --graph=model_32bits_float.tflite --external_delegate_path="ArmNN-linux-aarch64/libarmnnDelegate.so" --external_delegate_options="backends:CpuAcc;logging-severity:info"**
STARTING!
Log parameter values verbosely: [0]
Graph: [model_32bits_float.tflite]
External delegate path: [ArmNN-linux-aarch64/libarmnnDelegate.so]
External delegate options: [backends:CpuAcc;logging-severity:info]
Loaded model model_32bits_float.tflite
Info: ArmNN v25.0.0

Info: Initialization time: 0.86 ms

INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
EXTERNAL delegate created.
Going to apply 1 delegates one after another.
Explicitly applied EXTERNAL delegate, and the model graph will be partially executed by the delegate w/ 1 delegate kernels.
The input model file size (MB): 0.019552
Initialized session in 43.078ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=2533 first=421 curr=212 min=180 max=421 avg=196.386 std=8

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=5072 first=218 curr=196 min=171 max=640 avg=196.159 std=8

Inference timings in us: Init: 43078, First inference: 421, Warmup (avg): 196.386, Inference (avg): **196.159**
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=30.7734 overall=30.7734
Info: Shutdown time: 0.17 ms

**./linux_aarch64_benchmark_model --graph=model_32bits_float.tflite**
STARTING!
Log parameter values verbosely: [0]
Graph: [model_32bits_float.tflite]
Loaded model model_32bits_float.tflite
Going to apply 0 delegates one after another.
The input model file size (MB): 0.019552
Initialized session in 0.969ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=2988 first=296 curr=166 min=145 max=469 avg=166.384 std=7

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=5961 first=175 curr=165 min=143 max=2615 avg=166.798 std=39

Inference timings in us: Init: 969, First inference: 296, Warmup (avg): 166.384, Inference (avg): **166.798**
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=1.32812 overall=1.32812

**Comment by MatthewARM** [comment]
Maybe `--enable_op_profiling=true` would be helpful? https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#profiling-model-operators

I don't know for sure, but maybe that will tell you which operators are not running on the delegate

**Comment by kassianl26** [comment]
> Maybe `--enable_op_profiling=true` would be helpful? https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#profiling-model-operators
> 
> I don't know for sure, but maybe that will tell you which operators are not running on the delegate

The  UNIDIRECTIONAL_SEQUENCE_LSTM layer doesn't run with ArmNN delegate.

Node   0 Operator Builtin Code  44 UNIDIRECTIONAL_SEQUENCE_LSTM (not delegated)
  24 Input Tensors:[0,5,4,3,2,13,12,11,10,-1,-1,-1,9,8,7,6,-1,-1,14,17,-1,-1,-1,-1] -> 18976B (0.02MB)
  1 Output Tensors:[18] -> 2240B (0.00MB)
  1 Temporary Tensors:[22] -> 320B (0.00MB)
Node   1 Operator Builtin Code  22 RESHAPE (delegated by node 4)
  2 Input Tensors:[18,15] -> 0B (0.00MB)
  1 Output Tensors:[19] -> 0B (0.00MB)
Node   2 Operator Builtin Code   9 FULLY_CONNECTED (delegated by node 4)
  3 Input Tensors:[19,1,16] -> 0B (0.00MB)
  1 Output Tensors:[20] -> 0B (0.00MB)
Node   3 Operator Builtin Code  25 SOFTMAX (delegated by node 4)
  1 Input Tensors:[20] -> 0B (0.00MB)
  1 Output Tensors:[21] -> 0B (0.00MB)
Node   4 Operator Custom Name TfLiteArmNnDelegate
  4 Input Tensors:[1,15,16,18] -> 24688B (0.02MB)
  1 Output Tensors:[21] -> 40B (0.00MB)

Execution plan as the list of 2 nodes invoked in-order: [0,4]
Among these nodes in the execution plan:
  Node 4 is a TfLiteArmNnDelegate node (0xaaab068132b0), which has delegated 3 nodes: [1-3]
--------------Subgraph-0 dump has completed--------------

**Comment by MatthewARM** [comment]
Thanks, so two questions here @MikeJKelly and @keidav01 
1. We should add UNIDIRECTIONAL_SEQUENCE_LSTM to the roadmap
2. Is it plausible that one operator not being delegated could cause a big performance drop? Can we improve this?

**Comment by kassianl26** [comment]
What is the difference between UNIDIRECTIONAL_SEQUENCE_LSTM and LSTM (release 21.02) ?
Thank you !

**Comment by MatthewARM** [comment]
I'm not really sure of all the mathematical differences in the operations, but it's to do with how Keras models get converted to Tensorflow Lite format.

An LSTM at the Keras level can convert to LSTM, BIDIRECTIONAL_SEQUENCE_LSTM, or UNIDIRECTIONAL_SEQUENCE_LSTM at the Tensorflow Lite level, depending on how the sequence worked in Keras.

There's some documentation here: https://www.tensorflow.org/lite/convert/rnn. There's an example here: https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb showing an LSTM within a Sequence context getting converted to a UNIDIRECTIONAL_SEQUENCE_LSTM.

I **think** that you get a UNIDIRECTIONAL_SEQUENCE_LSTM (rather than an LSTM) if the **time_major** attribute is set in Keras.

**Comment by n-moussa** [comment]
Thanks a lot for providing insights on this issue!

I tried with turning on / off the time_major attribute at keras level (by default it's off).
The TFLite model is still using UNIDIRECTIONAL_SEQUENCE_LSTM.
I think it's aligned with what suggested on their doc
https://www.tensorflow.org/lite/convert/rnn
> Users may choose time-major or no time-major. Keras LSTM adds a time-major attribute in the function def attributes. For Unidirectional sequence LSTM, we can simply map to unidirecional_sequence_lstm's time major attribute.

If you look at their supported ops, we can find the time_major attribute in their implementation.
https://www.tensorflow.org/mlir/tfl_ops#tflunidirectional_sequence_lstm_tflunidirectionalsequencelstmop
> time_major | BoolAttr | bool attribute attribute

The UNIDIRECTIONAL_SEQUENCE_LSTM is providing the same results (in terms of accuracy) against its keras implementation `tf.keras.LSTM(units, return_sequences=True)`. It maintains the cell states between predictions (stateful between sequences but stateless between batch of sequences).
https://keras.io/guides/working_with_rnns/

**Comment by keidav01** [comment]
Hi @MatthewARM,

1. I've added this to our CE roadmap
2. It's very plausible that one operator not being delegated could be causing this massive drop in performance. It may be that a single partition is being created for unidirectional_sequence_lstm for vanilla tf lite and the two others for the ArmNN Delegate. The overhead in having these partitions communicate with eachother could be quite costly. Notwithstanding that it's quite a large operation involved, in LSTM. I'll investigate improving this

**Comment by kassianl26** [comment]
> Thanks a lot for providing insights on this issue!
> 
> I tried with turning on / off the time_major attribute at keras level (by default it's off).
> The TFLite model is still using UNIDIRECTIONAL_SEQUENCE_LSTM.
> I think it's aligned with what suggested on their doc
> https://www.tensorflow.org/lite/convert/rnn
> 
> > Users may choose time-major or no time-major. Keras LSTM adds a time-major attribute in the function def attributes. For Unidirectional sequence LSTM, we can simply map to unidirecional_sequence_lstm's time major attribute.
> 
> If you look at their supported ops, we can find the time_major attribute in their implementation.
> https://www.tensorflow.org/mlir/tfl_ops#tflunidirectional_sequence_lstm_tflunidirectionalsequencelstmop
> 
> > time_major | BoolAttr | bool attribute attribute
> 
> The UNIDIRECTIONAL_SEQUENCE_LSTM is providing the same results (in terms of accuracy) against its keras implementation `tf.keras.LSTM(units, return_sequences=True)`. It maintains the cell states between predictions (stateful between sequences but stateless between batch of sequences).
> https://keras.io/guides/working_with_rnns/

Could you share your code ? 

How to get LSTMOp in a tflite model ?

**Comment by n-moussa** [comment]
Hi @kassianl26 
Sorry, I was not able to get a tflite model with LSTMOp.
It always uses a UNIDIRECTIONAL_SEQUENCE_LSTM op.

Hmm, I'm not getting a performance drop when using XNNPACK delegate and it also falls back to TFLite to support LSTM.

**Comment by keidav01** [comment]
Hi @n-moussa,

Apologies for the delay. Can you test the performance on a 64 bit architcture please? Our Compute Library is not greatly optimised for v7 32bit

Let me know how you get on. 

Cheers,
Keith

**Comment by kassianl** [comment]
> 
> 
> Hi @MatthewARM,
> 
>     1. I've added this to our CE roadmap
> 
>     2. It's very plausible that one operator not being delegated could be causing this massive drop in performance. It may be that a single partition is being created for unidirectional_sequence_lstm for vanilla tf lite and the two others for the ArmNN Delegate. The overhead in having these partitions communicate with eachother could be quite costly. Notwithstanding that it's quite a large operation involved, in LSTM. I'll investigate improving this

Hi @keidav01 

Is the layer UNIDIRECTIONNAL_SEQUENCE_LSTM from tf lite going to be implemented in the next update ?

Thank you

**Comment by n-moussa** [comment]
Hi @Colm-in-Arm,

How we can test the reference implementation ?
Should we use the armnn Parser for TFLite and try to run it on x86-64 ? or arm CPU ?

Thanks a lot for the update,
Moussa

**Comment by Colm-in-Arm** [comment]
HI @n-moussa,

Right now the TfLite delegate support is in review (https://review.mlplatform.org/c/ml/armnn/+/6099) and there's no TfLite parser support. If you **really** wanted to test it then you would need to go directly to the Arm NN interface calling "AddUnidirectionalSequenceLstmLayer". I would suggest you wait until the TfLite delegate support is merged.

Colm.

**Comment by MikeJKelly** [comment]
Closing this as the TFLite delegate support has been merged for ArmNN reference backend (CpuRef) on the TFLite Delegate. When support is added to ArmNN's accelerated CPU backend (CpuAcc) we'll update this ticket. 

Best regards,
Mike
