### ISSUE TITLE
Wrong include path in src/backends/cl/ClImportTensorHandle.hpp#L22

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#545]
In `src/backends/cl/ClImportTensorHandle.hpp#L22`
```
#include <include/CL/cl_ext.h>
```
Should be:
```
#include <CL/cl_ext.h>
```

**Comment by FrancisMurtagh-arm** [comment]
Hi @ggardet,

We've pushed the fix, thanks.

https://review.mlplatform.org/c/ml/armnn/+/5690

Francis.

**Comment by FrancisMurtagh-arm** [comment]
Closing as fix has been merged.

Thanks.
