### ISSUE TITLE
RuntimeError: None of the preferred backends [CpuAcc CpuRef ] are supported. -Pyarmnn Docker

### ISSUE THREAD

**Issue by AliSheheryar** [ARM-software/armnn#546]
I am using PyArmnn on ubuntu 20.04 docker container and when i run , get following response.
arch-v7l
os: docker ubuntu20.04 

![Screenshot from 2021-05-31 19-09-42](https://user-images.githubusercontent.com/56480949/120206072-2b014400-c244-11eb-90df-fba2e6ca31ff.png)

**Comment by MikeJKelly** [comment]
Hi @AliSheheryar 

that indicates that the CpuRef and CpuAcc backends either haven't been built or aren't available, can you tell me how you obtained or built your version of ArmNN and PyArmnn? Did you follow our guides? What kind of device is just running on?

Best regards, 
Mike

**Comment by AliSheheryar** [comment]
Thanks Mike, I was able to solve this error. I am using PyArmnn 25.0 and Armnn 25.0. Libraries were installed using Apt repository for Ubuntu 20.04. Hardware is armn v7l with Neon support.
Please visit the link for proper info:
https://community.arm.com/developer/tools-software/oss-platforms/f/machine-learning-forum/49464/runtimeerror-none-of-the-preferred-backends-cpuacc-cpuref-are-supported-pyarmnn-docker/172504#172504

**Comment by Colm-in-Arm** [comment]
Hi @AliSheheryar,

Glad that you resolved your issue.

Colm.
