### ISSUE TITLE
Error while loading INT8 TFLite model

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#550]
Hi, I'm trying to use a converted INT8 TFLite model in ARMNN, but I got the following error:
```
Error: An error occurred when preparing the network workloads:  Convolution2dQueueDescriptor: Expected 0.0002141608711 quantization scale for bias tensor (the product of the input and weight scales), but got 0.001101637143 at function operator() [/home/odroid/ARMNN_2102/armnn_2102_argmax_patch/src/backends/backendsCommon/WorkloadData.cpp:223]
```
![executeNetork_error](https://user-images.githubusercontent.com/8951991/120627173-fc7aa780-c495-11eb-82a9-f20aedce43e7.png)

The followings are the information of how the model is converted and used:
1. ARM NN version: 21.02
2. The TFLite model is converted by [Post-training quantization, integer only](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only), there was a representative dataset used during the conversion.
3. The converted TFLite model was tested with ExecuteNetwork with the following command:
```
./ExecuteNetwork -c CpuAcc tflite-binary -f tflite-binary -m ./convertedTFLite/int8_model.lite -i input_tensor -o final_output --input-tensor-shape 1,360,360,3 --input-type int --output-type int --tflite-executor parser --iterations 1 
```
4. Visualization of the model in Netron:
![model#1](https://user-images.githubusercontent.com/8951991/120628215-ffc26300-c496-11eb-9314-031870d81efc.png)
![model#2](https://user-images.githubusercontent.com/8951991/120628224-00f39000-c497-11eb-9cf4-4cc2c84baede.png)

1. Is the error occurs because the model is converted with [Post-training quantization, integer only](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only)?
2. Is it possible to apply an INT8 TFLite model in ARM NN?

Best regards,
Rahn.

**Comment by Rahn80643** [comment]
Hi,
I've updated Arm nn to 21.08, but the inferred results from int8 model are still wrong, is the issue caused by `use biases with different quantization scales` in int8 tflite models?

![圖片2](https://user-images.githubusercontent.com/8951991/131790185-853bd581-d5a5-49ee-8eb7-f424c7fc9f4d.png)

**Comment by Shelton-N** [comment]
@Rahn80643 has known which leading to the differnet result? thanks a lot.
