### ISSUE TITLE
ARM NN  Compute Library  - Vulkan & Raspberry pi 4 GPU

### ISSUE THREAD

**Issue by ASR-Engineering-Consulting** [ARM-software/armnn#551]
ARM NN - Backends Raspberry GPU  and Vulkan
I am doing research on System on Chip "SoC" efficient Hardware utilization, I want to perform some performance analysis on Raspberry Pi 4. 

Open source Vulkan initiative since the best option for the GPU optimization  tool.  so I cannot find any support on the those  open source topics, Vulkan and Raspberry GPU supported by ARM NN.

Is there any ARM NN project to support the integration of Vulkan to enable raspberry Pi GPU for machine learning -  inference? 

Efficient targeting hardware, in the research community should focus in apnostic Hardware solution and having Raspberry Pi aducative and low cost solution to validate innovative approach.  

In my case, I got the proposed concept on implementing Convolution layers into Heterogeneous SoC but I can not validate performance. I could used other GPU hardware to implement my solution but it would be more beneficial for the researchers implemented into Raspberry Pi 4.

On the raspberry pi 4, there are two problems the moment. One the Raspberry Pi4 Vulkan driver still immature and not having big support from  open source Community. Second the Raspberry Pi 4 GPU VideoCore 6 support for machine learning.

Reading many ARM NN literary and tutorials.  Broadcom VideoCore VI and Raspberry Pi 4 B (Broadcom BCM2711). 

I would like to contribute the open source community with CNN optimization solution but those 2 Raspberry constraints, Vulkan and GPU still a blocking point for many optimation ideas.

ARM NN community have any  solution or suggestion on how we could remove those two constraints?

**Comment by MikeJKelly** [comment]
Hi @ASR-Engineering-Consulting 

> Is there any ARM NN project to support the integration of Vulkan to enable raspberry Pi GPU for machine learning - inference?

I do not know of any project for either of those. The only GPU backend that I know of is ArmNN's Compute Library GPU backend which uses OpenCL and requires an Arm GPU. 

In order to add support for VideoCore and Vulkan you would have to create a Backend similar in functionality to our ArmNN ComputeLibrary GPU backend. 

You can read more about adding a backend here:

https://github.com/ARM-software/armnn/tree/branches/armnn_21_05/src/backends

Best regards,
Mike

**Comment by StuartIanNaylor** [comment]
The Broadcom VideoCore VI is Raspberries Achiles heel.
As an alternative have a look at RockPi 4 as does have a Mali also with a M.2 that can use a Coral AI
The Radxa Zero is a 'Pi3' in a Zero format with a Mali-G31 that is a really interesting low cost micro SBC that is currently being trialled.

**Comment by MikeJKelly** [comment]
Thanks for the recommendations @StuartIanNaylor

**Comment by ASR-Engineering-Consulting** [comment]
Thank for the advice, but My aim is Vulkan & Raspberry pi 4 GPU. @StuartIanNaylor
I have many alternatives but goal is Vulkan and Raspberry
looking at Shade languages

**Comment by ASR-Engineering-Consulting** [comment]
ARM NN Compute Library is a open source? or just limited API to ARM!!

**Comment by StuartIanNaylor** [comment]
Its sort of in the name!?
