### ISSUE TITLE
[Delegate] VisitUnpackOperator: not supported by armnn: Tensors have different shapes

### ISSUE THREAD

**Issue by Linsha350** [ARM-software/armnn#554]
Hi.
I'm working with Odroid N2 (ARM CPU & Mali GPU)
I want to use ArmNN for tensorflow lite object detection network.
First, I installed armnn delegate by following the guide.
(build ArmNN first, build tensorflow lite, then build TfLite Delegate)
However, the DelegateUnitTests shows ERROR, and a lot of skips
The ArmNN UnitTest works well!
There is no any information about the error... so I write this question.

odroid@odroid:~/armnn-devenv/armnn/delegate/build$ ./DelegateUnitTests --test-suite=*CpuAcc*
[doctest] doctest version is "2.4.0"
[doctest] run with "--help" for options
INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
WARNING: VisitUnpackOperator: not supported by armnn: in validate_arguments src/core/NEON/kernels/NEStridedSliceKernel.cpp:67: Tensors have different shapes
ERROR: VisitUnpackOperator: not supported by any specified backend
WARNING: VisitUnpackOperator: not supported by armnn: in validate_arguments 
src/core/NEON/kernels/NEStridedSliceKernel.cpp:67: Tensors have different shapes
ERROR: VisitUnpackOperator: not supported by any specified backend

===============================================================================
[doctest] test cases:    187 |    187 passed |      0 failed |    394 skipped
[doctest] assertions:  15086 |  15086 passed |      0 failed |
[doctest] Status: SUCCESS!

odroid@odroid:~/armnn-devenv/armnn/delegate/build$ ./DelegateUnitTests --test-suite=*CpuAcc*,*GpuAcc*
[doctest] doctest version is "2.4.0"
[doctest] run with "--help" for options
INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
WARNING: operator(): not supported by armnn: in validate_arguments src/core/CL/kernels/CLDepthConvertLayerKernel.cpp:55: ITensor data type QASYMM8 not supported by this kernel
ERROR: operator(): not supported by any specified backend
WARNING: VisitUnpackOperator: not supported by armnn: in validate_arguments src/core/NEON/kernels/NEStridedSliceKernel.cpp:67: Tensors have different shapes
ERROR: VisitUnpackOperator: not supported by any specified backend
WARNING: VisitUnpackOperator: not supported by armnn: in validate_arguments src/core/NEON/kernels/NEStridedSliceKernel.cpp:67: Tensors have different shapes
ERROR: VisitUnpackOperator: not supported by any specified backend
WARNING: VisitUnpackOperator: not supported by armnn: in validate_arguments src/core/CL/kernels/CLStridedSliceKernel.cpp:65: Tensors have different shapes
ERROR: VisitUnpackOperator: not supported by any specified backend
WARNING: VisitUnpackOperator: not supported by armnn: in validate_arguments src/core/CL/kernels/CLStridedSliceKernel.cpp:65: Tensors have different shapes
ERROR: VisitUnpackOperator: not supported by any specified backend

===============================================================================
[doctest] test cases:    372 |    372 passed |      0 failed |    209 skipped
[doctest] assertions:  30102 |  30102 passed |      0 failed |
[doctest] Status: SUCCESS!

Thank you!

- Linsha-

**Comment by MikeJKelly** [comment]
Hi @Linsha350 

what version of ArmNN are you using? 

This should be fixed on the master branch by this review https://review.mlplatform.org/c/ml/armnn/+/5660 but the fix was too late for the 21.05 release

Best regards,
Mike

**Comment by Linsha350** [comment]
I use branches/v21.05 !

Thank you!
I will try it

**Comment by MikeJKelly** [comment]
I hope this has worked out for you. I'm going to close this, please comment if you're still having issues.
