### ISSUE TITLE
Issue installing tensorflow when using armnn docker image. 

### ISSUE THREAD

**Issue by connorb573** [ARM-software/armnn#556]
Hi, I'm trying to install tensorflow 1.15 using pip while using the armnn docker image https://hub.docker.com/r/armswdev/armnn 

Whenever I attempt to install using either pip3 install or python3 -m pip install tensorflow==1.15 I get the following output: 

`ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.15`

I've done some lengthy troubleshooting and tried all the given fixes I can find (python version etc - i'm using 3.6.9) and none of them seem to work so I wondered if this was an issue anyone else had come across before when using the armnn docker image?

**Comment by MikeJKelly** [comment]
Hi @connorb573 

I have seen similar issues on older versions of ubuntu, what version of ubuntu are you using?

That docker image from https://hub.docker.com/r/armswdev/armnn links back to the Tool-Solutions github, https://github.com/ARM-software/Tool-Solutions/tree/master/ml-tool-examples/build-armnn they may have seen issue reported there?

Best regards,
Mike

**Comment by connorb573** [comment]
Hi @MikeJKelly, I'm using ubuntu 18.04.5. 

I'll take a look at issues on the Tool-Solutions GitHub as well. 

Thanks

**Comment by milpuz01** [comment]
Hi @connorb573,

Tensorflow for AArch64 at the moment is not available on PyPi so If you want to install it using pip you would need to do it using a python wheel that you can find here from Linaro for versions 1.15 and 2.4.1: https://snapshots.linaro.org/ldcg/python/tensorflow-manylinux/4/tensorflow_cpu/ and here for version 2.5.0: https://snapshots.linaro.org/ldcg/python/tensorflow-manylinux/11/tensorflow-cpu/. For Python 3.6 you should pick up *-cp36-* wheel.

If you are interested in working with TensorFlow I would suggest to use container with Tensorflow already built that you can find here: https://hub.docker.com/r/armswdev/tensorflow-arm-neoverse-n1. If you want to use ArmNN with TensorFlow then you would need TensorFlow Lite. On this page https://gitlab.com/arm-hpc/packages/-/wikis/packages/tensorflow-lite are instructions how to build TesnorFlow Lite with ArmNN and run models either using ArmNN as a standalone library or run them using TensorFlow Lite with ArmNN as delegate. We will be publishing container with TensorFlow Lite and ArmNN to https://hub.docker.com/r/armswdev/ soon.

Best,
Milos.

**Comment by connorb573** [comment]
Hi @milpuz01, 

Thanks so much for your comment, I wasn't aware of TensorFlow for Aarch64 not being on PyPi, the fix you provided works great. Thanks for providing all that info also, it's very useful! 

Best,
Connor.
