### ISSUE TITLE
Noise appear in uint8 model and wrong result in int model

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#557]
Noise appear in uint8 model and wrong result in int model

Hi,
I've been testing our segmentation models that are converted in uint8 precision and int8 precision on different computation unit on Odroid. I found that the detected results of the float model on all computation units are the same, the detected results of the uint8 model contain some noise while executing at GpuAcc mode, and the detected result of int8 models are completely wrong at all computation units.
More detailed information of the models is as follow:

1. The version of ArmNN is 21.05 in order to execute int8.
2. The uint8 model is converted based on the steps in [Quantification (pb->tflite), Method 1](https://www.programmersought.com/article/66626957619/)
3. The int8 model is converted based on the steps in [post_training_quantization, int only](https://www.tensorflow.org/lite/performance/post_training_quantization)

4. Comparisons of different models on different computation unit:

![圖片2](https://user-images.githubusercontent.com/8951991/122852198-ccab1b00-d342-11eb-8c8f-c34df45bf612.png)

1. Could the nose be removed while applying the uint8 model on GPU?
2. Is there any possible solution to the wrong results of int8 model on all computation unit?

Best regards,
Rahn

**Comment by Burton2000** [comment]
Just to check, do the results of all the models look correct when not using ArmNN e.g. when running them in the TensorFlow Lite interpreter?

For the int8 model are you correctly quantizing your input if you used integer only quantization?

**Comment by Rahn80643** [comment]
hi, 
1. The int8 and float tflite model was tested in TensorFlow Lite interpreter, and the results from these models are similar.

![Screenshot from 2021-06-30 13-43-07](https://user-images.githubusercontent.com/8951991/123907879-277aed00-d9a9-11eb-8372-999a3534f19e.png)


2. I had modified the input image and quantized the pixel values for int8 model, the pixel values fall between -128~ 127.
3. I followed (post training quantization)[https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only] to quantizing the int8 model.

**Comment by morgolock** [comment]
Hi @Rahn80643 

Could you please share the models with us?

**Comment by Rahn80643** [comment]
Hi, @morgolock 


The attachment is the converted int8 model.
The input name is input_tensor.
The output name is final_output.
The size of input tensor is: 360x 360x 3 (Wx Hx C)
The size of output tensor is: 180x 180 (Wx H)

[model_int8.lite.tar.gz](https://github.com/ARM-software/armnn/files/6745607/model_int8.lite.tar.gz)

Best Regards,
Rahn

**Comment by morgolock** [comment]
Hi @Rahn80643 

Could you please share the original non converted model?

**Comment by Rahn80643** [comment]
Hi, @morgolock

The attachment is the original pb model.
The input name is input_tensor.
The output name is final_output.
The size of input tensor is: 360x 360x 3 (Wx Hx C)
The size of output tensor is: 180x 180 (Wx H)

[model.pb.tar.gz](https://github.com/ARM-software/armnn/files/6747967/model.pb.tar.gz)


Best Regards,
Rahn

**Comment by MikeJKelly** [comment]
Hi @Rahn80643 

what images did you use for your representative_dataset when performing your post training quantization? Do you have a link to the image set? How did you run the models through armnn?

Best regards,
Mike

**Comment by Rahn80643** [comment]
Hi,
The link below are the images I used for post-training quantization.
[google drive link](https://drive.google.com/drive/folders/1xxXtEmu_tgu6YaNd-y9aRt88gLKJY5he?usp=sharing)
The image preprocessing function, please note that the images should be resized to 360x 360.
![20210707_imgProc](https://user-images.githubusercontent.com/8951991/124697109-d626ac80-df18-11eb-830b-ad2621c73074.png)


I modified the sample code in [ML-examples/armnn-mobilenet-quant](https://github.com/ARM-software/ML-examples/tree/master/armnn-mobilenet-quant) to exeucte my model, and the modifications are as follows.
1. (mobilenetv1_quant_tflite.cpp) Add an extra container `TContainer_int8` for the int8 model.
![20210707_1_container](https://user-images.githubusercontent.com/8951991/124697176-ef2f5d80-df18-11eb-8b22-5adf1c3ffacd.png)

2. (mobilenetv1_quant_tflite.cpp) Modify normParams.scale, normParams.mean, and normParams.stddev for the int8 model.
![20210707_2_normParams](https://user-images.githubusercontent.com/8951991/124697187-f5bdd500-df18-11eb-8a83-8b95a4ca60b8.png)

3. (mobilenetv1_quant_tflite.cpp) Preprocess images by calling `PrepareImageTensor_int` which is modified in utils.cpp.
![20210707_3_callPreproc](https://user-images.githubusercontent.com/8951991/124697199-fb1b1f80-df18-11eb-8aa9-8143b104f61a.png)


4. (utils.cpp) Cast the pixel values to uint_8 and return the preprocessed image.
![20210707_4_utils_cast](https://user-images.githubusercontent.com/8951991/124697213-00786a00-df19-11eb-878e-c3af29b18d90.png)


5. (mobilenetv1_quant_tflite.cpp) Execute inference and get the output result
![20210707_5_for_output](https://user-images.githubusercontent.com/8951991/124697243-0b32ff00-df19-11eb-99f7-9c95834f98ef.png)

Best Regards,
Rahn

**Comment by morgolock** [comment]
Hi @Rahn80643 

Could you please also share the uint8 model with us?

**Comment by Rahn80643** [comment]
Hi,
The following attachment is the converted tflite uint8 model.
[model_uint8.lite.tar.gz](https://github.com/ARM-software/armnn/files/6776811/model_uint8.lite.tar.gz)

Best Regards,
Rahn

**Comment by MikeJKelly** [comment]
Hi @Rahn80643 

there were some int8 fixes  ran one of your images through "model_int8.lite" using the version of ArmNN and ComputeLibrary on master and got good results on CpuRef but very poor results on both CpuAcc and GpuAcc. 

When we looked into the model a bit more we saw that "model_int8.lite" uses per-axis quantization for the weights in its convolution and depthwise convolution layers but ComputeLibrary doesn't have per-axis supports it applies quantization along the Channel dimension. 

I'll add a test to the CL and Neon backends to check for situations where the axis is not equal to the channel. 

Best regards,
Mike

**Comment by Rahn80643** [comment]
Hi, 
I was informed to use armnn 21.05 with [this patch](https://github.com/ARM-software/armnn/commit/d7ed6d4e53a877a25fcea754d76c8831451f18f1) to test issue of wrong results in qasymms8 (int8) models. However, I got errors during compiling this patch with Compute Library 21.05:
armnn/src/backends/cl/workloads/ClAbsWorkload.hpp:11:10: fatal error: arm_compute/runtime/CL/functions/CLElementwiseUnaryLayer.h: No such file or directory #include <arm_compute/runtime/CL/functions/CLElementwiseUnaryLayer.h>

![2181230](https://user-images.githubusercontent.com/8951991/127736883-81ad04b3-e55a-4304-b810-e225561925c6.jpg)

I also tried to compile this arm nn patch with compute library 5907 patch, but the error message above still appear. Does this issue occur because of the settings in makefiles? 

Best regards,
Rahn

**Comment by Rahn80643** [comment]
Hi,
I've updated Arm nn to 21.08, but the inferred results from int8 model are still wrong, is the issue caused by use biases with different quantization scales in int8 tflite models?

![圖片2](https://user-images.githubusercontent.com/8951991/131790441-69a256a3-55c8-40d4-9d98-709d0d2570c9.png)

**Comment by Rahn80643** [comment]
Hi,
I have asked the related question on https://github.com/ARM-software/ethos-n-driver-stack/issues,
thanks you so much for providing the information above

Rahn
