### ISSUE TITLE
Issue with YOLO with CaffeYolo-Armnn example

### ISSUE THREAD

**Issue by getsumit123** [ARM-software/armnn#56]
Hi
I tried to test CaffeYolo-Armnn example by converting yolo tiny darknet model to caffemodel

But everytime it returns "Prediction for test case 0 (14) is incorrect (should be 11)"
Issue may be with the yolo model which i am using.
Could anyone please provide Yolo model which works with armnn or redirect me to the place where i can get caffe port which works with armnn.

I am using command "CaffeYolo-Armnn -i 10 -d /path/to/image/ -m /path/to/alexnet/model_file/ -c GpuAcc"

Regards
Sumit

**Comment by Surmeh** [comment]
Hi @getsumit123,

ArmNN uses CaffeModel from https://github.com/hojel/caffe-yolo-model. Also, make sure to modify the code if you're using a different image as the image and the class is hard-coded in the test which can be found at tests/YoloDatabase.cpp.

**Comment by TelmoARM** [comment]
Hi @getsumit123,

I'm assuming the model Surabhi suggested fixed your problem and I'm marking this ticket as resolved. Feel free to re-open the ticket if you are still having problems.

Telmo

**Comment by TelmoARM** [comment]
Hi @gustavsl, 

A few notes:
- Without seeing your changes or more information it's hard to diagnose the problem. 
- The ArmNN test you are using is specific to a particular image and expects the bounding box to be at a specific location. 
- The armnn/tests directory contains tests used during ArmNN development. Many of them depend on third-party IP, model protobufs and image files not distributed with ArmNN. The dependencies of some of the tests are available freely on the Internet, for those who wish to experiment.
- The 'ExecuteNetwork' program, in armnn/tests/ExecuteNetwork, has no additional dependencies beyond those required by ArmNN and the model parsers. It takes any model and any input tensor, and simply prints out the output tensor. Run with no arguments to see command-line help.

We recommend ArmNN users to use the ExecuteNetwork app in the armnn/tests folder.I have verified this working with the Yolo_tiny.caffemodel. If you need help with this you can open a new ticket.

I hope this helps,
Telmo
