### ISSUE TITLE
Square operation

### ISSUE THREAD

**Issue by Sheethal00** [ARM-software/armnn#561]
Hi,

I am getting the below error when i try to load inception resnetv1 model

Fatal: Armnn Error: Unsupported operation Square in tensorflow::GraphDef  at function LoadNodeDef [/home/darshan.p/armnn/poky_linux/armnn/src/]

Is Square operation supported if not is their any alternative

Regards
Sheethal

**Comment by morgolock** [comment]
Hi @Sheethal00 

Could you please share the model with us?

**Comment by MikeJKelly** [comment]
Hi @Sheethal00 

what version of ArmNN are you using? Tensorflow support was removed in 21.05 but ArmNN should support resnet in tflite. 

Best regards
Mike

**Comment by MikeJKelly** [comment]
Closed due to inactivity, if you still require help please open another ticket.
