### ISSUE TITLE
Performance Issue in NEDepthwiseConvolutionLayerNativeKernel

### ISSUE THREAD

**Issue by szihs** [ARM-software/armnn#563]
ARMNN & ACL - v21.02 (Neon backend)
Platform - Tizen armv7l

I used ARMNN to run the tflite network however performance was not good.
So I profiled the same & found that the NEDepthwiseConvolutionLayerNativeKernel layer is taking about 90% of the time. 

Could you please help me how can I improve it / Debug this performance issue.

`{
  "ArmNN": {
    "inference_measurements_#1": {
      "type": "Event",
      "Wall clock time_#1": {
        "type": "Measurement",
        "raw": [
          105473.470000
        ],
        "unit": "us"
      },
      "Wall clock time (Start)_#1": {
        "type": "Measurement",
        "raw": [
          210329.407000
        ],
        "unit": "us"
      },
      "Wall clock time (Stop)_#1": {
        "type": "Measurement",
        "raw": [
          315802.877000
        ],
        "unit": "us"
      },
      "PrepareInputs_#2": {
        "type": "Event",
        "Wall clock time_#2": {
          "type": "Measurement",
          "raw": [
            45.125000
          ],
          "unit": "us"
        },
        "Wall clock time (Start)_#2": {
          "type": "Measurement",
          "raw": [
            210347.067000
          ],
          "unit": "us"
        },
        "Wall clock time (Stop)_#2": {
          "type": "Measurement",
          "raw": [
            210392.192000
          ],
          "unit": "us"
        }
      },
      "PrepareOutputs_#3": {
        "type": "Event",
        "Wall clock time_#3": {
          "type": "Measurement",
          "raw": [
            9.441000
          ],
          "unit": "us"
        },
        "Wall clock time (Start)_#3": {
          "type": "Measurement",
          "raw": [
            210394.470000
          ],
          "unit": "us"
        },
        "Wall clock time (Stop)_#3": {
          "type": "Measurement",
          "raw": [
            210403.911000
          ],
          "unit": "us"
        }
      },
      "Execute_#4": {
        "type": "Event",
        "Wall clock time_#4": {
          "type": "Measurement",
          "raw": [
            105387.004000
          ],
          "unit": "us"
        },
        "Wall clock time (Start)_#4": {
          "type": "Measurement",
          "raw": [
            210410.787000
          ],
          "unit": "us"
        },
        "Wall clock time (Stop)_#4": {
          "type": "Measurement",
          "raw": [
            315797.791000
          ],
          "unit": "us"
        },
        "Working Memory Allocation_#5": {
          "type": "Event",
          "Wall clock time_#5": {
            "type": "Measurement",
            "raw": [
              5379.192000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#5": {
            "type": "Measurement",
            "raw": [
              210424.540000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#5": {
            "type": "Measurement",
            "raw": [
              215803.732000
            ],
            "unit": "us"
          }
        },
        "CopyMemGeneric_Execute_#6": {
          "type": "Event",
          "Wall clock time_#6": {
            "type": "Measurement",
            "raw": [
              116.048000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#6": {
            "type": "Measurement",
            "raw": [
              215816.264000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#6": {
            "type": "Measurement",
            "raw": [
              215932.312000
            ],
            "unit": "us"
          },
          "Synchronize buffers_#7": {
            "type": "Event",
            "Wall clock time_#7": {
              "type": "Measurement",
              "raw": [
                11.475000
              ],
              "unit": "us"
            },
            "Wall clock time (Start)_#7": {
              "type": "Measurement",
              "raw": [
                215864.929000
              ],
              "unit": "us"
            },
            "Wall clock time (Stop)_#7": {
              "type": "Measurement",
              "raw": [
                215876.404000
              ],
              "unit": "us"
            }
          }
        },
        "NeonConstantWorkload_Execute_#8": {
          "type": "Event",
          "Wall clock time_#8": {
            "type": "Measurement",
            "raw": [
              13.876000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#8": {
            "type": "Measurement",
            "raw": [
              218902.771000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#8": {
            "type": "Measurement",
            "raw": [
              218916.647000
            ],
            "unit": "us"
          }
        },
        "NeonDepthwiseConvolutionWorkload_Execute_#9": {
          "type": "Event",
          "NeonKernelTimer/0: NEDepthwiseConvolutionLayerNativeKernel_#9": {
            "type": "Measurement",
            "raw": [
              93771.769000
            ],
            "unit": "us"
          },
          "NeonKernelTimer/1: CpuActivationKernel_#9": {
            "type": "Measurement",
            "raw": [
              230.021000
            ],
            "unit": "us"
          },
          "Wall clock time_#9": {
            "type": "Measurement",
            "raw": [
              94143.392000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#9": {
            "type": "Measurement",
            "raw": [
              218940.613000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#9": {
            "type": "Measurement",
            "raw": [
              313084.005000
            ],
            "unit": "us"
          }
        },
        "NeonReshapeWorkload_Execute_#10": {
          "type": "Event",
          "NeonKernelTimer/0: CpuReshapeKernel_#10": {
            "type": "Measurement",
            "raw": [
              21.403000
            ],
            "unit": "us"
          },
          "Wall clock time_#10": {
            "type": "Measurement",
            "raw": [
              27.222000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#10": {
            "type": "Measurement",
            "raw": [
              313101.542000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#10": {
            "type": "Measurement",
            "raw": [
              313128.764000
            ],
            "unit": "us"
          }
        },
        "NeonPooling2dWorkload_Execute_#11": {
          "type": "Event",
          "NeonKernelTimer/0: CpuPoolingKernel_#11": {
            "type": "Measurement",
            "raw": [
              481.608000
            ],
            "unit": "us"
          },
          "Wall clock time_#11": {
            "type": "Measurement",
            "raw": [
              490.764000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#11": {
            "type": "Measurement",
            "raw": [
              313136.617000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#11": {
            "type": "Measurement",
            "raw": [
              313627.381000
            ],
            "unit": "us"
          }
        },
        "NeonConvolution2dWorkload_Execute_#12": {
          "type": "Event",
          "NeonKernelTimer/0: NEWinogradLayerTransformInputKernel_#12": {
            "type": "Measurement",
            "raw": [
              644.694000
            ],
            "unit": "us"
          },
          "NeonKernelTimer/1: NEGEMMAssemblyWrapperKernel/sgemm_8x6_#12": {
            "type": "Measurement",
            "raw": [
              392.741000
            ],
            "unit": "us"
          },
          "NeonKernelTimer/2: NEWinogradLayerTransformOutputKernel_#12": {
            "type": "Measurement",
            "raw": [
              337.524000
            ],
            "unit": "us"
          },
          "Wall clock time_#12": {
            "type": "Measurement",
            "raw": [
              1483.521000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#12": {
            "type": "Measurement",
            "raw": [
              313636.332000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#12": {
            "type": "Measurement",
            "raw": [
              315119.853000
            ],
            "unit": "us"
          }
        },
        "NeonPooling2dWorkload_Execute_#13": {
          "type": "Event",
          "NeonKernelTimer/0: CpuPoolingKernel_#13": {
            "type": "Measurement",
            "raw": [
              89.315000
            ],
            "unit": "us"
          },
          "Wall clock time_#13": {
            "type": "Measurement",
            "raw": [
              98.836000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#13": {
            "type": "Measurement",
            "raw": [
              315129.497000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#13": {
            "type": "Measurement",
            "raw": [
              315228.333000
            ],
            "unit": "us"
          }
        },
        "NeonConvolution2dWorkload_Execute_#14": {
          "type": "Event",
          "NeonKernelTimer/0: NEWinogradLayerTransformInputKernel_#14": {
            "type": "Measurement",
            "raw": [
              72.917000
            ],
            "unit": "us"
          },
          "NeonKernelTimer/1: NEGEMMAssemblyWrapperKernel/sgemm_8x6_#14": {
            "type": "Measurement",
            "raw": [
              94.808000
            ],
            "unit": "us"
          },
          "NeonKernelTimer/2: NEWinogradLayerTransformOutputKernel_#14": {
            "type": "Measurement",
            "raw": [
              44.312000
            ],
            "unit": "us"
          },
          "Wall clock time_#14": {
            "type": "Measurement",
            "raw": [
              233.724000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#14": {
            "type": "Measurement",
            "raw": [
              315231.710000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#14": {
            "type": "Measurement",
            "raw": [
              315465.434000
            ],
            "unit": "us"
          }
        },
        "NeonPooling2dWorkload_Execute_#15": {
          "type": "Event",
          "NeonKernelTimer/0: CpuPoolingKernel_#15": {
            "type": "Measurement",
            "raw": [
              33.691000
            ],
            "unit": "us"
          },
          "Wall clock time_#15": {
            "type": "Measurement",
            "raw": [
              38.167000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#15": {
            "type": "Measurement",
            "raw": [
              315469.015000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#15": {
            "type": "Measurement",
            "raw": [
              315507.182000
            ],
            "unit": "us"
          }
        },
        "NeonSubtractionWorkload_Execute_#16": {
          "type": "Event",
          "NeonKernelTimer/0: CpuSubKernel_#16": {
            "type": "Measurement",
            "raw": [
              26.123000
            ],
            "unit": "us"
          },
          "Wall clock time_#16": {
            "type": "Measurement",
            "raw": [
              32.593000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#16": {
            "type": "Measurement",
            "raw": [
              315510.356000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#16": {
            "type": "Measurement",
            "raw": [
              315542.949000
            ],
            "unit": "us"
          }
        },
        "NeonReshapeWorkload_Execute_#17": {
          "type": "Event",
          "NeonKernelTimer/0: CpuReshapeKernel_#17": {
            "type": "Measurement",
            "raw": [
              7.203000
            ],
            "unit": "us"
          },
          "Wall clock time_#17": {
            "type": "Measurement",
            "raw": [
              12.003000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#17": {
            "type": "Measurement",
            "raw": [
              315546.245000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#17": {
            "type": "Measurement",
            "raw": [
              315558.248000
            ],
            "unit": "us"
          }
        },
        "NeonL2NormalizationFloatWorkload_Execute_#18": {
          "type": "Event",
          "NeonKernelTimer/0: NEReductionOperationKernel_#18": {
            "type": "Measurement",
            "raw": [
              33.285000
            ],
            "unit": "us"
          },
          "NeonKernelTimer/1: NEL2NormalizeLayerKernel_#18": {
            "type": "Measurement",
            "raw": [
              25.431000
            ],
            "unit": "us"
          },
          "Wall clock time_#18": {
            "type": "Measurement",
            "raw": [
              82.032000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#18": {
            "type": "Measurement",
            "raw": [
              315561.096000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#18": {
            "type": "Measurement",
            "raw": [
              315643.128000
            ],
            "unit": "us"
          }
        },
        "NeonFullyConnectedWorkload_Execute_#19": {
          "type": "Event",
          "NeonKernelTimer/0: CpuReshapeKernel_#19": {
            "type": "Measurement",
            "raw": [
              4.964000
            ],
            "unit": "us"
          },
          "NeonKernelTimer/1: NEGEMMAssemblyWrapperKernel/sgemm_8x6_#19": {
            "type": "Measurement",
            "raw": [
              5.371000
            ],
            "unit": "us"
          },
          "Wall clock time_#19": {
            "type": "Measurement",
            "raw": [
              30.802000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#19": {
            "type": "Measurement",
            "raw": [
              315646.831000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#19": {
            "type": "Measurement",
            "raw": [
              315677.633000
            ],
            "unit": "us"
          }
        },
        "NeonSoftmaxWorkload_Execute_#20": {
          "type": "Event",
          "NeonKernelTimer/0: CpuLogits1DMaxKernel_#20": {
            "type": "Measurement",
            "raw": [
              11.515000
            ],
            "unit": "us"
          },
          "NeonKernelTimer/1: CpuLogits1DLogSoftmaxKernel_#20": {
            "type": "Measurement",
            "raw": [
              40.080000
            ],
            "unit": "us"
          },
          "Wall clock time_#20": {
            "type": "Measurement",
            "raw": [
              88.990000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#20": {
            "type": "Measurement",
            "raw": [
              315680.725000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#20": {
            "type": "Measurement",
            "raw": [
              315769.715000
            ],
            "unit": "us"
          }
        },
        "CopyMemGeneric_Execute_#21": {
          "type": "Event",
          "Wall clock time_#21": {
            "type": "Measurement",
            "raw": [
              22.339000
            ],
            "unit": "us"
          },
          "Wall clock time (Start)_#21": {
            "type": "Measurement",
            "raw": [
              315774.150000
            ],
            "unit": "us"
          },
          "Wall clock time (Stop)_#21": {
            "type": "Measurement",
            "raw": [
              315796.489000
            ],
            "unit": "us"
          },
          "Synchronize buffers_#22": {
            "type": "Event",
            "Wall clock time_#22": {
              "type": "Measurement",
              "raw": [
                2.116000
              ],
              "unit": "us"
            },
            "Wall clock time (Start)_#22": {
              "type": "Measurement",
              "raw": [
                315785.584000
              ],
              "unit": "us"
            },
            "Wall clock time (Stop)_#22": {
              "type": "Measurement",
              "raw": [
                315787.700000
              ],
              "unit": "us"
            }
          }
        }
      }
    }
  }
}`

![Vej5lD0q0d](https://user-images.githubusercontent.com/675653/127272412-587d3c95-9de3-420a-91c4-7a2690c478d0.png)

Thank you.
-Harsh

**Comment by morgolock** [comment]
Hi @szihs 

In order to have a better view of what's going on you could:

Use ExecuteNetwork -e to output profiling information as shown below:
```LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./tests/ExecuteNetwork  -m BiSeNetv2_float.lite  -c GpuAcc --iterations=1 -f tflite-binary  -i input_tensor -o final_output -e  > BiSeNetv2_float.lite.proof```

Make the necessary changes to the command above for your network: -c CpuAcc and you will need to change the model name and input and output

Then you can use the following python script to produce an simple breakdown of how much time each layer takes:
```
root@odroid:~/pablo# python3 vison/vison.py -j BiSeNetv2_float.lite.proof | tail -n 30
Inference time:  735315.667 us
Total kernel time  640304.6419999998 us
Total time per kernel				Percentage of total time		Kernel name
	 21.6780              us 		% 0.00003386 			  gemm_mm_reshaped_only_rhs_t 
	 24.2550              us 		% 0.00003788 			  reduction_operation_y 
	 54.9540              us 		% 0.00008582 			  reduction_operation_z 
	 517.4760             us 		% 0.00080817 			  concatenate_width_x2 
	 610.2180             us 		% 0.00095301 			  fill_image_borders_constant 
	 805.2270             us 		% 0.00125757 			  pixelwise_mul_float 
	 893.3590             us 		% 0.00139521 			  activation_layer 
	 938.7490             us 		% 0.00146610 			  depthwise_convolution_3x3_nhwc 
	 1090.4610            us 		% 0.00170303 			  gemm_reshape_lhs_matrix_nt 
	 1248.5670            us 		% 0.00194996 			  gemm_mm_reshaped_lhs_nt_rhs_t 
	 1276.6560            us 		% 0.00199383 			  pooling_layer_MxN_nhwc 
	 1481.6300            us 		% 0.00231395 			  elementwise_operation_ADD 
	 2271.3090            us 		% 0.00354723 			  depthwise_convolution_3x3_stridex2_stridey2_f32 
	 2966.6480            us 		% 0.00463318 			  reshape_layer 
	 4089.4700            us 		% 0.00638676 			  depthwise_convolution_3x3_stridex1_stridey1_f32 
	 4176.9500            us 		% 0.00652338 			  depthwise_convolution_3x3_nhwc_stride1 
	 11842.5860           us 		% 0.01849524 			  softmax_layer_norm 
	 15025.9490           us 		% 0.02346688 			  im2col3x3_nhwc 
	 16433.1250           us 		% 0.02566454 			  softmax_layer_max_shift_exp_sum_serial 
	 17526.0700           us 		% 0.02737146 			  winograd_output_transform_4x4_3x3_nhwc 
	 26331.9740           us 		% 0.04112413 			  arg_min_max_x 
	 29888.0950           us 		% 0.04667793 			  permute 
	 44669.7030           us 		% 0.06976320 			  winograd_input_transform_4x4_3x3_stepz1_nhwc 
	 78658.5800           us 		% 0.12284556 			  scale_bilinear_nhwc 
	 377460.9530          us 		% 0.58950213 			  gemm_mm_floating_point_f32_bifrost 
```

You can download the python script from https://github.com/morgolock/vison

Hope this helps.

**Comment by szihs** [comment]
Here is the output 

```
Working Memory Allocation_#5
CopyMemGeneric_Execute_#6
NeonConstantWorkload_Execute_#8
NeonDepthwiseConvolutionWorkload_Execute_#9
            94979.289 us                          NEDepthwiseConvolutionLayerNativeKernel
              530.925 us                          CpuActivationKernel
NeonReshapeWorkload_Execute_#10
               19.043 us                          CpuReshapeKernel
NeonPooling2dWorkload_Execute_#11
              791.829 us                          CpuPoolingKernel
NeonConvolution2dWorkload_Execute_#12
              576.538 us                          NEWinogradLayerTransformInputKernel
               394.45 us                          NEGEMMAssemblyWrapperKernel/sgemm_8x6
              299.235 us                          NEWinogradLayerTransformOutputKernel
NeonPooling2dWorkload_Execute_#13
               145.63 us                          CpuPoolingKernel
NeonConvolution2dWorkload_Execute_#14
               74.463 us                          NEWinogradLayerTransformInputKernel
               50.822 us                          NEGEMMAssemblyWrapperKernel/sgemm_8x6
               44.759 us                          NEWinogradLayerTransformOutputKernel
NeonPooling2dWorkload_Execute_#15
               55.502 us                          CpuPoolingKernel
NeonSubtractionWorkload_Execute_#16
               27.914 us                          CpuSubKernel
NeonReshapeWorkload_Execute_#17
                7.325 us                          CpuReshapeKernel
NeonL2NormalizationFloatWorkload_Execute_#18
               96.395 us                          NEReductionOperationKernel
               29.052 us                          NEL2NormalizeLayerKernel
NeonFullyConnectedWorkload_Execute_#19
                5.086 us                          CpuReshapeKernel
                8.301 us                          NEGEMMAssemblyWrapperKernel/sgemm_8x6
NeonSoftmaxWorkload_Execute_#20
               13.997 us                          CpuLogits1DMaxKernel
                36.54 us                          CpuLogits1DLogSoftmaxKernel
CopyMemGeneric_Execute_#21



Inference time:  111501.464 us
Total kernel time  98187.09500000002 us

Total time per kernel                           Percentage of total time                Kernel name
         13.9970              us                % 0.00014255                      CpuLogits1DMaxKernel
         27.9140              us                % 0.00028429                      CpuSubKernel
         29.0520              us                % 0.00029588                      NEL2NormalizeLayerKernel
         31.4540              us                % 0.00032035                      CpuReshapeKernel
         36.5400              us                % 0.00037215                      CpuLogits1DLogSoftmaxKernel
         96.3950              us                % 0.00098175                      NEReductionOperationKernel
         343.9940             us                % 0.00350345                      NEWinogradLayerTransformOutputKernel
         453.5730             us                % 0.00461948                      NEGEMMAssemblyWrapperKernel/sgemm_8x6
         530.9250             us                % 0.00540728                      CpuActivationKernel
         651.0010             us                % 0.00663021                      NEWinogradLayerTransformInputKernel
         992.9610             us                % 0.01011295                      CpuPoolingKernel
         94979.2890           us                % 0.96732966                      NEDepthwiseConvolutionLayerNativeKernel
```

which shows NEDepthwiseConvolutionLayerNativeKernel takes most of the time.
Is it normal ?

**Comment by szihs** [comment]
- Could you please comment if it's an performance issue with ACL?

**Comment by MikeJKelly** [comment]
It certainly seems that the NEDepthwiseConvolutionLayerNativeKernel is taking most of the time but you're using a build with 32bit armv7a kernels which are not as optimised as our aarch64 kernels. What kind of device are you running it on?

**Comment by szihs** [comment]
I am running on a Tizen TV.

**Comment by MikeJKelly** [comment]
Hi @szihs 

ACL performance on Arm v7 is not as optimized as our Arm v8 kernels and we have no plans to optimize them further (armv7 is over 10 years old at this stage and we need to concentrate on newer technologies). If your Tizen TV has an Arm v8 processor and you build for Arm v8 then you will probably get a performance boost over TFLite on its own otherwise you may get better performance using TFLite without Arm NN.

Best regards,
Mike
