### ISSUE TITLE
Compilation failure with CL, Question on which Arm ComputeLibrary to use

### ISSUE THREAD

**Issue by bhahn2004** [ARM-software/armnn#564]
I have been trying to build ArmNN with CL
However I have been getting this error:

```
In file included from /home/pi/experiment-inference-performance-pi/armnn-pi/armnn/src/backends/cl/ClLayerSupport.cpp:22:
/home/pi/experiment-inference-performance-pi/armnn-pi/armnn/src/backends/cl/workloads/ClAbsWorkload.hpp:11:10: fatal error: arm_compute/runtime/CL/functions/CLElementwiseUnaryLayer.h: No such file or directory
 #include <arm_compute/runtime/CL/functions/CLElementwiseUnaryLayer.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/backends/cl/CMakeFiles/armnnClBackend.dir/build.make:158: src/backends/cl/CMakeFiles/armnnClBackend.dir/ClLayerSupport.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1494: src/backends/cl/CMakeFiles/armnnClBackend.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I seems that naming `CLElementwiseUnaryLayer.h` vs `CLElementWiseUnaryLayer.h` is the issue.
I found this commit 77c92e4 that this name is changed for some reason.
However, at least from what I see in the ComputeLibrary repo (v21.05 and current master branch) that the name remains to be `CLElementWiseUnaryLayer.h`.

https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/functions/CLElementWiseUnaryLayer.h

https://github.com/ARM-software/ComputeLibrary/blob/v21.05/arm_compute/runtime/CL/functions/CLElementWiseUnaryLayer.h

I guess it makes sense if I look at https://review.mlplatform.org/c/ml/ComputeLibrary/+/5769, but does this mean that I am supposed to use the development version of the ComputeLibrary in https://git.mlplatform.org/ml/ComputeLibrary.git all the time to compile latest versions of ArmNN master branch?

**Comment by MikeJKelly** [comment]
Hi @bhahn2004 

how are you getting your ArmNN and CL? The released versions of ArmNN and CL match, so ArmNN 21.05 and CL 21.05 were tested together and should work together. 

If you're getting ArmNN from the master the best way to get a compatible version of ComputeLibrary is to call armnn/scripts/get_compute_library.sh which will download the latest working version of ComputeLibrary.

Best regards,
Mike

**Comment by bhahn2004** [comment]
@MikeJKelly 

CL I used 21.05. However, I had to use ArmNN's 0176fd8 commit.
This is because I have been running into some problem while using ITfLiteParser or IOnnxParser while parsing my model.

So I guess the best way would be to use `get_compute_library.sh`.
Thanks for the note!
