### ISSUE TITLE
Unsupported Operators with ITfLiteParser and IOnnxParser while using PyArmNN

### ISSUE THREAD

**Issue by bhahn2004** [ARM-software/armnn#565]
ONNX version of the last few layers from my model
![image](https://user-images.githubusercontent.com/73912804/127645283-22f35d92-2627-43f4-a27d-b44b22edbc7d.png)

TFLite (converted from ONNX) of last few layers from my model
![image](https://user-images.githubusercontent.com/73912804/127645314-0c5f388e-77e5-4e6c-8994-a4ab72715f5c.png)

I have been running into issues regarding `Operator not supported`

With OnnxParser, it could not parse the node `Shape_168` like in #542
On the other hand, with TFLite, I got error with `EQUAL` operator.

Q1.
Are there any plans in the foreseeable future to support wider range of operations?
Maybe supporting some higher version of opset versions for ONNX?

Q2. 
Also, are there any reference to which operators are supported and not? 

### Environment

ACL: v21.05
ArmNN: 0176fd8
Platform Raspberry Pi 4

### History

1. tried using OnnxRuntime on Raspberry Pi 4 --> Successfully runs all models
2. for more accelerated performance tried using OnnxRuntime with ACL and ArmNN as EP --> Failed due to similar error to this issue
3. fall back to PyArmNN v21.05 with IOnnxParser --> Failed due to similar error to this issue
4. use PyArmNN commit 0176fd8 with TFLite as per suggestion in #542 --> Failed due to similar error to this issue
5. out of options?

**Comment by bhahn2004** [comment]
I have been running into similar issue for different models/operators too for which I share the error messages:
I hope this may be of reference to the developers in some way

```
Traceback (most recent call last):
  File “tflite_test.py”, line 6, in <module>
    network = parser.CreateNetworkFromBinaryFile(‘./model-0.tflite’)
  File “/home/pi/.local/lib/python3.7/site-packages/pyarmnn/_generated/pyarmnn_tfliteparser.py”, line 711, in CreateNetworkFromBinaryFile
    return _pyarmnn_tfliteparser.ITfLiteParser_CreateNetworkFromBinaryFile(self, graphFile)
RuntimeError: Failed to parse operator #0 within subgraph #0 error: Operator not supported. subgraph:0 operator:0 opcode_index:0 opcode:32 / CUSTOM  at function ParseUnsupportedOperator [/home/pi/armnn-pi/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:861]
```

```
Your ArmNN library instance does not have an armnn models parser funcionality.  Skipped IDeserializer import.
Traceback (most recent call last):
  File “onnx_test.py”, line 6, in <module>
    network = parser.CreateNetworkFromBinaryFile(‘./model-0.onnx’)
  File “/home/pi/.local/lib/python3.7/site-packages/pyarmnn/_generated/pyarmnn_onnxparser.py”, line 672, in CreateNetworkFromBinaryFile
    return _pyarmnn_onnxparser.IOnnxParser_CreateNetworkFromBinaryFile(self, graphFile)
RuntimeError: ‘BOOL’ is not a currently supported datatype for tensor 328. Supported dataTypes are FLOAT, INT32 and INT64.   at function ToTensorInfo [/home/pi/armnn-pi/armnn/src/armnnOnnxParser/OnnxParser.cpp:273]
```

```
Your ArmNN library instance does not have an armnn models parser funcionality.  Skipped IDeserializer import.
Traceback (most recent call last):
  File “tflite_test.py”, line 7, in <module>
    network = parser.CreateNetworkFromBinaryFile(‘./base-model.tflite’)
  File “/home/pi/.local/lib/python3.7/site-packages/pyarmnn/_generated/pyarmnn_tfliteparser.py”, line 711, in CreateNetworkFromBinaryFile
    return _pyarmnn_tfliteparser.ITfLiteParser_CreateNetworkFromBinaryFile(self, graphFile)
RuntimeError: Failed to parse operator #226 within subgraph #0 error: Operator not supported. subgraph:0 operator:226 opcode_index:12 opcode:71 / EQUAL  at function ParseUnsupportedOperator [/home/pi/armnn-pi/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:861]
```

```
Your ArmNN library instance does not have an armnn models parser funcionality.  Skipped IDeserializer import.
Traceback (most recent call last):
  File “onnx_test.py”, line 7, in <module>
    network = parser.CreateNetworkFromBinaryFile(‘./base-model.onnx’)
  File “/home/pi/.local/lib/python3.7/site-packages/pyarmnn/_generated/pyarmnn_onnxparser.py”, line 672, in CreateNetworkFromBinaryFile
    return _pyarmnn_onnxparser.IOnnxParser_CreateNetworkFromBinaryFile(self, graphFile)
RuntimeError: Unsupported operation Shape for node ‘Shape_168’  at function LoadGraph [/home/pi/armnn-pi/armnn/src/armnnOnnxParser/OnnxParser.cpp:734]
```

**Comment by MikeJKelly** [comment]
Hi @bhahn2004 

I've added tickets for adding these operators to our backlog however there is no ETA at the moment when they will be implemented. As we're going to track these internally I'm going to close this issue but we'll update it if and when support for these operators have been added.  

If you would like to help implement these operators then here is a link to our contributors guide which will show you how you can submit a patch to us. If you have any questions then please feel free to create a new Issue, thank you!

https://www.mlplatform.org/contributing

Kind regards,

**Comment by MikeJKelly** [comment]
Hi @bhahn2004 

When looking at the tickets for these I can see that we have added support for Shape, GEMM and Unqueeze to the 21.11 release. If those were the only missing operators then the ONNX model should parse correctly.   

Best regards,
Mike.
