### ISSUE TITLE
Yolo_V3 throws runtime error when executed on RPI4 with PyARMNN

### ISSUE THREAD

**Issue by shenba-krish** [ARM-software/armnn#568]
Hello. I am trying to follow the examples of object detection provided in the ARM Reference documentation [https://developer.arm.com/documentation/102557/0100/Introduction-to-PyArmNN].

Unfortunately, when I try to run Yolo_V3 it gives a runtime error. 
_RuntimeError: Buffer doesn't conform to the expected Tensorflow Lite flatbuffers format. size:133  at function LoadModelFromBinary [/build/armnn-tICQCd/armnn-21.05/src/armnnTfLiteParser/TfLiteParser.cpp:3352]_

Does yolo_v3 is supported by tflite parser? When I read the parser documentation looks like it only supports quantized yolo_v3 and ssd_mobilenet. But how did yolo_v3 was tested successfully in this reference documentation. Am I missing something here. Would like to hear your thoughts!!

**Comment by Colm-in-Arm** [comment]
Hi @shenba-krish,

> "Does yolo_v3 is supported by tflite parser?"

This depends on which yolo v3 you are using but I would expect so. Taking a look at the Tiny YOLO v3 that's available in our [Model Zoo](https://github.com/ARM-software/ML-zoo/tree/master/models/object_detection/yolo_v3_tiny/tflite_fp32) it is supported.

The error you've mentioned indicates that the tflite binary does not match the expected FlatBuffers format, not that there's an underlying problem with the model. Can you try with the file in the Model Zoo please and see if you get the same error.

Colm.

**Comment by shenba-krish** [comment]
Hey @Colm-in-Arm 

I have used the same model from the Model Zoo. I tried using the ARMNN_VERSIONS = 22,24,25. 
Still, the same error persists!! 

Looking forward to hearing from you to fix this issue. Thanks in advance.

**Comment by Colm-in-Arm** [comment]
Hi @shenba-krish,

What version of Arm NN are you compiling with? The document you're referencing is for PyArmNN. I can't see how you'd end up calling the TfLite parser if you're using it. Can you share an outline of the code you're trying?

Colm.

**Comment by shenba-krish** [comment]
Hello @Colm-in-Arm 

I am just following the guide that I have referenced. [I](https://developer.arm.com/documentation/102557/0100/Running-the-example)

I am using ARMNN Version = 22 as per the guide. I also tried using versions 24 and 25. 

Still, I get the error concerning the FlatBuffers format.

The below lines are from the reference documentation:-

> ''The CreateNetworkFromBinaryFile() function creates the parser and loads the network file. The parser then constructs the underlying Arm NN graph from the network file.
> 
> The following code selects the TFLite parser and converts the model file into an Arm NN network graph:
> 
> parser = ann.ITfLiteParser() 
> network = parser.CreateNetworkFromBinaryFile(model_file_path.as_posix()) ''

**Comment by Colm-in-Arm** [comment]
Hi @shenba-krish,

I'm going to try and run through this guide myself. It's possible something significant has changed since it was written that's causing the problem. In the meantime can you tell me which distribution and version you're using on the Pi4? Ubuntu, Debian?

Colm.

**Comment by shenba-krish** [comment]
Hello @Colm-in-Arm,

Thanks for the reply. Please give it a try and let me know. I use Ubuntu 64-bit server version 20.04 LTS.

/Shenba

**Comment by shenba-krish** [comment]
Hi @Colm-in-Arm 

Thanks for the suggestion.

Now I got it solved. Looks like when you clone the ML-Zoo repository it did not download any models but instead showed only its GIT header. To download the  specific model you need 

> git lfs pull --include="[path to model].tflite" --exclude=""

Probably you can add this to the reference documentation. Thanks for the assistance.

/Shenba

**Comment by Colm-in-Arm** [comment]
Hi Shenba,

I'm pleased you got it working.

Enabling git lfs is included in step 5 on a [previous page](https://developer.arm.com/documentation/102557/0100/Device-specific-installation) of the guide but the reason for it isn't made clear. I'll suggest an update.

Colm.

**Comment by MikeJKelly** [comment]
Closing this as the issue has been resolved. If you need any further help please open another issue.

Best regards,
Mike
