### ISSUE TITLE
tensorflow-protobuf deprecated  erro  for Cross-Compile Arm NN on x86_64 for arm64

### ISSUE THREAD

**Issue by Niuxiaotong** [ARM-software/armnn#569]
1. env:
armnn21_02
tensorflow-2.3.1
protobuf-3.12
2. compile ArmNN appear erro, the following:
....tensorflow-protobuf/tensorflow/core/framework/cost_graph.pb.cc: In member function ‘virtual google::protobuf::uint8* tensorflow::CostGraphDef_Node::_InternalSerialize(google::protobuf::uint8*, google::protobuf::io::EpsCopyOutputStream*) const’:
/home/xiaotong.niu/ArmNN_2102/armnn_21_02/third-party/prebuild/tensorflow-protobuf/tensorflow/core/framework/**cost_graph.pb.cc**:1406:35: error: ‘google::protobuf::int64 

tensorflow::CostGraphDef_Node::host_temp_memory_size() const’ is **deprecated** [-Werror=deprecated-declarations]
   if (this->host_temp_memory_size() != 0) {

in cost_graph.pb.cc: serverl functon  is deprecated result in compile erro,
how to slove the problem ,please give me a direct,thanks.

**Comment by Colm-in-Arm** [comment]
Hi @Niuxiaotong,

I attempted to recreate this problems by following the [cross compile guide for 21.02](https://github.com/ARM-software/armnn/blob/branches/armnn_21_02/BuildGuideCrossCompilation.md). I did encounter some deprecated warning messages but the build completed successfully.

Can you verify that you are compiling using the labeled tensorflow 2.3.1. Here's the SHA I see in Tensorflow:

> coldon01@e121545-lin:~/armnn-devenv/tensorflow$ git rev-parse HEAD
> fcc4b966f1265f466e82617020af93670141b009

Colm.

**Comment by Niuxiaotong** [comment]
Hi,Colm, thanks for your replay,  as follow:
.../tensorflow$ git rev-parse HEAD
fcc4b966f1265f466e82617020af93670141b009
and about protobuf :
.../protobuf$ git rev-parse HEAD
0dd036d675508a4ecf69e61626fd0c88235a661d

and compile options as follow:
    cmake $ROOT_DIR \
        -DCMAKE_SYSTEM_NAME=Linux \
        -DCMAKE_SYSTEM_PROCESSOR=arm \
        -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
        -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=$OUT_DIR/build_linux_arm64/install \
        -DBOOST_ROOT=$PREBUILD/boost/linux_arm64 \
        -DARMCOMPUTENEON=ON \
        -DARMCOMPUTE_ROOT=$COMPUTELIBRARY_DIR \
        -DARMCOMPUTE_BUILD_DIR=$PREBUILD/computelibrary/linux_arm64 \
        -DBUILD_ARMNN_SERIALIZER=ON \
        -DBUILD_ARMNN_QUANTIZER=ON \
        -DBUILD_CAFFE_PARSER=ON \
        -DCAFFE_GENERATED_SOURCES=$PREBUILD/caffe-protobuf \
        -DBUILD_ONNX_PARSER=ON \
        -DONNX_GENERATED_SOURCES=$PREBUILD/onnx-protobuf \
        -DBUILD_TF_PARSER=ON \
        -DTF_GENERATED_SOURCES=$PREBUILD/tensorflow-protobuf \
        -DBUILD_TF_LITE_PARSER=ON \
        -DTF_LITE_GENERATED_PATH=$PREBUILD/tflite-flatbuffers \
        -DPROTOBUF_ROOT=$PREBUILD/protobuf/linux_arm64 \
        -DFLATBUFFERS_ROOT=$PREBUILD/flatbuffers/linux_arm64 \
        -DFLATC_DIR=$FLATC_HOST_DIR/bin \
        -DDYNAMIC_BACKEND_PATHS="/data/local/" \
        -DBUILD_TESTS=ON \
        -DGOOGLETEST_ROOT=$PREBUILD/googletest/linux_arm64 \
        -DCMAKE_CXX_FLAGS = "-Wno-error=deprecated-declarations"

    make -j32
    make install

others:
add DCMAKE_CXX_FLAGS  options:
        -DCMAKE_CXX_FLAGS = "-Wno-error=deprecated-declarations" refer to https://github.com/ARM-software/armnn/issues/373

**Comment by Niuxiaotong** [comment]
Colm，I try again ,After adding -DCMAKE_CXX_FLAGS="-Wno-error=deprecated-declarations" , building armNN success ,apart from some warnings.
In additon, how to slove with those warnings ,give me some advice please ,Colm.
xiaotong

**Comment by Colm-in-Arm** [comment]
Hi xiaotong,

If the warning that concern you relate to deprecated interfaces such as: "HloInstructionProto::all_reduce_id()" or "CostGraphDef_Node::host_temp_memory_size()" then you can safely ignore them. If the warning are from Arm NN code then please do send me the details and I'll investigate.

Colm.

**Comment by Niuxiaotong** [comment]
thanks Colm,everything is ok,xiaotong.
