### ISSUE TITLE
ExecuteNetwork Segfault for TFLite Delegate

### ISSUE THREAD

**Issue by jishminor** [ARM-software/armnn#572]
I am experiencing a segfault if I don't pass the tensor input shape for `ExecuteNetwork` using the tflite armnn delegate option to run the network.

Versions tested: v21.05 v21.08

Platform: Docker image with base `ubuntu:20.04` running on Marvell Thunderx2 host

Example command using inceptionv3 tflite model:
```
root@893098a75dbe:/benchmarking# ./ExecuteNetwork -c CpuAcc -f tflite-binary -m /models/inceptionv3/1/model.tflite -i input -o InceptionV3/Predictions/Reshape_1 -T delegate
Warning: No input files provided, input tensors will be filled with 0s.
Info: ArmNN v26.0.0

Can't load libOpenCL.so: libOpenCL.so: cannot open shared object file: No such file or directory
Can't load libGLES_mali.so: libGLES_mali.so: cannot open shared object file: No such file or directory
Can't load libmali.so: libmali.so: cannot open shared object file: No such file or directory
Couldn't find any OpenCL library.
Info: Initialization time: 1.58 ms

Info: ArmNN v26.0.0

Info: Initialization time: 0.13 ms

INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
Segmentation fault (core dumped)
```

If I pass the input shape as following the program executes properly:
```
./ExecuteNetwork -c CpuAcc -f tflite-binary -m /models/inceptionv3/1/model.tflite -i input -o InceptionV3/Predictions/Reshape_1 -T delegate -s 1,299,299,3
```

**Comment by MikeJKelly** [comment]
Hi Josh, 
thanks for the bug report, the -s should be an optional way to override the input shape and so shouldn't be required. I'll see about getting a review together that fixes this. 

Best regards,
Mike

**Comment by MikeJKelly** [comment]
Hi Josh,

I think that this review should fix the issue: https://review.mlplatform.org/c/ml/armnn/+/6192 Now when the -s option is missing we will get the tensor shapes from the TFLite Delegate. 

Can you confirm if this works?

Best regards,
Mike

**Comment by jishminor** [comment]
This fixes the issue. Thanks.
