### ISSUE TITLE
slice layer does not match the size tensor value  = -1

### ISSUE THREAD

**Issue by tuanhe** [ARM-software/armnn#577]
in some tflite models , the slice layer has 3 input tensor : input , begin , size .
if the size value = -1 , the armnn will treat it as unsigned value , that will cause output shape error .

![image](https://user-images.githubusercontent.com/4641886/132473681-6ada6038-208a-4c51-a8c5-6dd20297b37c.png)

**Comment by MikeJKelly** [comment]
Hi @tuanhe 

This patch should fix the issue: https://review.mlplatform.org/c/ml/armnn/+/6250
can you try it and confirm if it works?

Best regards,
Mike

**Comment by tuanhe** [comment]
@MikeJKelly 
It works , thanks very much

**Comment by MikeJKelly** [comment]
@tuanhe 

That's great, the fix has been merged so I'll close this, let us know if you still have any problems and thanks for the bug report!
