### ISSUE TITLE
Moving files after cross compiling

### ISSUE THREAD

**Issue by CodeMonkey3435** [ARM-software/armnn#579]
Hi there everyone,
I was just wondering how to actually proceed after finishing this guide: https://github.com/ARM-software/armnn/blob/branches/armnn_21_08/BuildGuideCrossCompilation.md. I would have used the bash script here: https://github.com/ARM-software/Tool-Solutions/tree/master/ml-tool-examples/build-armnn. But it threw errors along the way. 
So, what files do I need to move to my target device and what dependencies do I have to set? I actually want to use the python api in the end. 
Thanks everyone

**Comment by Colm-in-Arm** [comment]
Hi @CodeMonkey3435,

There's a section called "Run Unit Tests" towards the end of the document that describes how to execute the unit tests on the target device. This is probably a good first step to ensure what you have built works on your aarch64 device.

If I take this specific case the executable that will be run is called "UnitTests". It has a series a shared library dependencies. The actual paths and version number will be dependent on the version of Arm NN you are using:

Arm NN and its associated libraries:

libarmnn.so 
libarmnnSerializer.so
libtimelineDecoder.so
libarmnnBasePipeServer.so
libtimelineDecoderJson.so
libarmnnTfLiteParser.so
libarmnnOnnxParser.so

Third party library that we use: libprotobuf.so and then various system libraries.

Could you post on the error messages you encountered when running "build-armnn.sh" please.

Colm.

**Comment by CodeMonkey3435** [comment]
After building with the script I get this error: 

> building 'pyarmnn._generated._pyarmnn_version' extension
> x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/codemonkez/armnn-devenv/armnn/include/ -I/usr/include/python3.8 -c src/pyarmnn/_generated/armnn_version_wrap.cpp -o build/temp.linux-x86_64-3.8/src/pyarmnn/_generated/armnn_version_wrap.o -std=c++14
> x86_64-linux-gnu-gcc: error: src/pyarmnn/_generated/armnn_version_wrap.cpp: No such file or directory
> x86_64-linux-gnu-gcc: fatal error: no input files
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> ~/armnn-devenv

Really no idea how to fix this.

**Comment by CodeMonkey3435** [comment]
Also if I run the unit Test I get the following error:
`sudo LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./UnitTests`

> ./UnitTests: error while loading shared libraries: ./libtimelineDecoder.so.26: file too short

**Comment by CodeMonkey3435** [comment]
Hello, yes build-armnn.sh is very confortable. I gave it another shot by installing ubuntu18.04 in virtualBox and trying it out right now. Last time I used a more recent version of ubuntu. I do not understand this link architecture. I copied all the files from your last post and that still lead to the same error (building armnn manually)

**Comment by CodeMonkey3435** [comment]
One more info: When running the build-armnn.sh I use this command:
`./build-armnn.sh -a arm64-v8a -o 1 -x 1`
And another bug that I found is that setuptools is not installed automatically via the build-armnn.sh file. I simply installed this beforehand with this command:
`sudo apt install python3-setuptools`
