### ISSUE TITLE
armnn Parser for Caffe deconvolution.

### ISSUE THREAD

**Issue by ssj4gogeta** [ARM-software/armnn#58]
I am trying to write a parser for caffe deconvolution to execute through armnn. I have a few questions.
1. What difference will be there in comparision to caffe convolution parser with respect to weights?
2. Should I reshape the weights in any specific manner before passing to Deconvolution configure?
3. What will be the values of inner_border_top & inner_border_right? and
4. Are there any other things that I need to take care of? for getting the same answer as in caffe deconvolution layer.
Thanks in advance!

**Comment by Surmeh** [comment]
Hi @ssj4gogeta,

Thanks for showing interest in ArmNN and sorry for the late response.

We haven't analyzed the Caffe deconvolution layer, so I'm afraid I won't be able to answer some of the questions. You could look into Compute library's implementation, as mentioned below:

2. Weights should be the same as in the Convolution layer: [W, H, IFM, OFM] and not [W, H, OFM, IFM]
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEDeconvolutionLayer.h#L84
3. inner_border_right & inner_border_top have the same value. 
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEDeconvolutionLayer.h#L57

I hope this is helpful.

**Comment by TelmoARM** [comment]
Hi @ssj4gogeta,

Since we haven't analyzed the Caffe deconvolution layer. I'm marking this ticket as future work and closing. Let us know if you agree or find any other issues.

Telmo
