### ISSUE TITLE
Segmentation fault (core dumped) while getting the node attributes from the TF Graphdef

### ISSUE THREAD

**Issue by Darshvino** [ARM-software/armnn#582]
Hi armnn team,

Thanks for your amazing work.

I was trying to use the TF Parser code (https://github.com/ARM-software/armnn/blob/branches/armnn_20_08/src/armnnTfParser/TfParser.cpp) for deserializing the Frozen graph.

```
    FILE* fd = fopen("model.pb", "rb");
    if (fd == nullptr)
    {
        std::cout<<"*******there is no graph file found**********"<<std::endl;

    }
    GraphDef graphDef;

     std::cout<<"right after ReadBinaryProto"<<std::endl;
    google::protobuf::io::FileInputStream  inStream(fileno(fd));
    google::protobuf::io::CodedInputStream codedStream(&inStream);
    codedStream.SetTotalBytesLimit(INT_MAX, INT_MAX);
    bool success = graphDef.ParseFromCodedStream(&codedStream); 
    fclose(fd);

```
The above code works correctly, but while I am trying to get the node attributes from the Graphdef, I am getting **Segmentation fault (core dumped)**.

```
    for (int i = 0; i < graphDef.node_size(); ++i)
    {

            const NodeDef& node = graphDef.node(i);
            DataType type = tensorflow::DT_FLOAT;
    	    //auto node = graphDef.node(i);
    	    auto attr = node.attr().at("T");
            type = attr.type();
}

```

I am not sure whether it is a Model issue or a Deserialisation code issue. It would be of great help if anyone can help me to understand and resolve the issue.

Thanks and Regards

**Comment by Colm-in-Arm** [comment]
HI @Darshvino,

Support for TensorFlow was removed in 21.05 but I see you back in 20.08.

"graphDef" has at least been partially populated in your code as graphDef.node_size() > 0. Is the segmentation fault happening when you access "node" or "attr"?

Colm.

**Comment by Darshvino** [comment]
Hi @Colm-in-Arm,

Thanks for your reply. The segmentation fault is happening while I access "attr".

Not Sure about the exact issue. I had also tried with TF 21.05.

Looking forward to your reply.

Thanks,
Darshan C G

**Comment by Colm-in-Arm** [comment]
Hi Darshan C G,

If I look at the Tf documentation: this code "auto attr = node.attr().at("T");" should result in either attr being set or an std::out_of_range exception. However, I wonder if the de-serialization is getting in the way a bit. Have you tried examining or iterating the node.attr() map to see if there are any attributes there at all?

Colm.

**Comment by Darshvino** [comment]
Hi @Colm-in-Arm,

I am able to print the Graphdef content and all seems to be right. I am able to get the correct graph.

```
    for (int i = 0; i < graph_Def.node_size(); i++)
    {
            graph_Def.node(i).PrintDebugString();

    }

```

But not sure how do I get the attributes and the weights from the graphDef?

**Comment by james-conroy-arm** [comment]
Hi @Darshvino ,

This [StackOverflow question](https://stackoverflow.com/questions/46127471/how-to-get-weights-from-pb-model-in-tensorflow) may help you with getting the weights from the GraphDef, you may need to refer to TensorFlow's documentation also. If you still have issues you should get more helpful information by [opening an issue with TensorFlow](https://github.com/tensorflow/tensorflow/issues/new/choose).

Since this issue appears to be an environment issue and affects the TF Parser which is now removed from Arm NN in release 21.05, I think this ticket can be closed. Please feel free to re-open if this is not the case.

Thanks,
James

**Comment by james-conroy-arm** [comment]
From Arm NN 21.05 release onwards, we recommend using our TF Lite parser instead of the removed TF Parser. Please refer to TensorFlow's documentation for help with converting TF models to TF Lite format: https://www.tensorflow.org/lite/convert
