### ISSUE TITLE
pyarmnn: reshape input size TFlite and ONNX

### ISSUE THREAD

**Issue by helion-du-mas-des-bourboux-thales** [ARM-software/armnn#584]
Is there a way in pyArmNN TFLite or ONNX parser to change the input and output tensors.
For example in TensorFlow, one would run the folowing with a dynamicly defined model
```
model.resize_tensor_input(input_details[0]['index'], x.shape)
model.resize_tensor_input(output_details[0]['index'], y.shape)

input_details = model.get_input_details()
output_details = model.get_output_details()

model.allocate_tensors()
```

**Comment by Colm-in-Arm** [comment]
Hi @helion-du-mas-des-bourboux-thales,

Sorry but Arm NN does not currently support dynamic size for input or output tensors.

Colm.
