### ISSUE TITLE
 armnn_v21_08 memory usage

### ISSUE THREAD

**Issue by dongmunha** [ARM-software/armnn#586]
When I run "sample/ObjectionDetection" using the YOLOv3 model, the memory usage increases about 2.5 times more than the previous version (armnn_21_05). I want to know what is the cause.

**Comment by Colm-in-Arm** [comment]
Hi @dongmunha,

Can you give me some more details please:

* Architecture.
* Backends in use.
* Source of the YOLOv3 model.

Colm.

**Comment by dongmunha** [comment]
Thanks for the reply. The answer to your request is as follows.
1. Architecture : ARM Cortex-A9 dual core
2. Backbone in use: Tiny YOLOv3
3. Source code of the YOLOv3 model :  I downloaded the model and weight files from the darknet official site and used them after converting them into tensorflow lite format. The resource I used can be downloaded from the link below.
   1) model file : https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-tiny.cfg
   2) weight : https://pjreddie.com/media/files/yolov3-tiny.weights

**Comment by Colm-in-Arm** [comment]
Hi @dongmunha,

My first concern here is you are using a v7 core. Arm NN and ACL are not optimized to run on v7. There was a discussion about this on [community.arm.com](https://community.arm.com/developer/tools-software/oss-platforms/f/machine-learning-forum/49732/subsequent-iterated-inference-cycles-work-slower-than-the-very-first-one)

Each release of Arm NN and ACL strives to improve performance on aarch64 hardware and it's possible that improvments in the 21.08 release could negatively effect execution on v7. As Ben Clark put it in that conversation:

"Arm v7 is >10 years old now (Arm v9 is out!), so the Arm NN team need to focus their resources on more recent technologies. Yes, it's a shame that they're not getting to it, but they can't do everything."

Perhaps you could try using the TfLite runtime and comparing performance and memory footprint with your model. I'd be interested in know how it works out.

Colm.

**Comment by MikeJKelly** [comment]
Closing as I think this issue has been resolved. If you have any further questions then please open another issue. 

Best regards,
Mike
