### ISSUE TITLE
delegate test failed

### ISSUE THREAD

**Issue by sunforever1990** [ARM-software/armnn#589]
I followed BuildGuideNative.md in delegate/ and successfully build armnn and delegate. When I come to this:

To ensure that the build was successful you can run the unit tests for the delegate that can be found in 
the build directory for the delegate. [Doctest](https://github.com/onqtam/doctest) was used to create those tests. Using test filters you can
filter out tests that your build is not configured for. In this case, because Arm NN was only built for Cpu 
acceleration (CpuAcc), we filter for all test suites that have `CpuAcc` in their name.
```bash
cd $BASEDIR/armnn/delegate/build
./DelegateUnitTests --test-suite=*CpuAcc* 
```
If you have built for Gpu acceleration as well you might want to change your test-suite filter:
```bash
./DelegateUnitTests --test-suite=*CpuAcc*,*GpuAcc*
```
I build this project on an aarch64 machine. The cpu test is ok but GpuAcc did't work. 

![2102125884](https://user-images.githubusercontent.com/45776934/138400288-d0235ea9-5772-4cb4-b54d-9b28b413a1b0.jpg)

When I test with tflite another error came up.

temi@temi:~/ArmNNDelegate/benchmarking$ LD_LIBRARY_PATH=../armnn/build ./benchmark_model --graph=mobilenet_v2_1.0_224_quantized_1_default_1.tflite --external_delegate_path="../armnn/build/delegate/libarmnnDelegate.so" --external_delegate_options="backends:CpuAcc;logging-severity:info"
STARTING!
Log parameter values verbosely: [0]
Graph: [mobilenet_v2_1.0_224_quantized_1_default_1.tflite]
External delegate path: [../armnn/build/delegate/libarmnnDelegate.so]
External delegate options: [backends:CpuAcc;logging-severity:info]
Loaded model mobilenet_v2_1.0_224_quantized_1_default_1.tflite
EXTERNAL delegate created

When I type clinfo it prints"Number of platforms       0 "
Is this means my driver for Mali GPU is missing?

How to solve this? Any suggestions? Thanks!

**Comment by gfa99** [comment]
@sunforever1990: you can try like follow:
1. place the libmails.so into /usr/lib
```
git clone -b 29mirror https://github.com/rockchip-linux/libmali
sudo cp -R libmail/include/CL/ /usr/include/
sudo cp libmail/lib/aarch64-linux-gnu/libmali-midgard-t86x-r14p0.so /usr/lib/
sudo ln -s /usr/lib/libmali-midgard-t86x-r14p0.so /usr/lib/libOpenCL.so
```
2. config udev rules:
```
sudo cat > /etc/udev/rules.d/50-mail400.rules << EOF
KERNEL=="mali", MODE="0666", GROUP="video"
EOF
sudo cat > /etc/udev/rules.d/50-mail.rules << EOF
KERNEL=="mali0", MODE="0666", GROUP="video"
EOF
```
3. reboot your system

**Comment by sunforever1990** [comment]
> KERNEL=="mali", MODE="0666", GROUP="video"
> EOF
> sudo cat > /etc/udev/rules.d/50-mail.rules << EOF
> KERNEL=="mali0", MODE="0666", GROUP="video"
> EOF

This actually solved my problem. There was no rules file under /etc/udev/rules.d/ in my system. Thank you a lot!
