### ISSUE TITLE
Saving optimized model to disk

### ISSUE THREAD

**Issue by AGhiuta** [ARM-software/armnn#59]
Hi!

Is there any way to save an optimized network (its parameters, not just the graph definition) to disk?
Also, is there any way to run inference on a vanilla (unoptimized) network?

Thanks

**Comment by Surmeh** [comment]
Hi @AGhiuta,

No, we currently don't have the provision to save an optimized network but we are looking to add it to our roadmap.
As the Optimiser makes the decision of the hardware to run the inference on, there is no way to run the inference on an unoptimized network.

I hope this helps.

**Comment by Surmeh** [comment]
Hi @AGhiuta, since the initial question was answered, I'm marking this ticket resolved. Let us know if you have any other issues.
