### ISSUE TITLE
Building the TfLite Delegate generates fatal error: common/include/ProfilingGuid.hpp: No Such file or directory.

### ISSUE THREAD

**Issue by topquant** [ARM-software/armnn#591]
OS Ubuntu 20.04 (aarch64)

ubuntu@ubuntu:~/ArmNNDelegate/armnn/delegate/build$ cmake -DCMAKE_BUILD_TYPE=release -DTENSORFLOW_ROOT=$BASEDIR/tensorflow -DTFLITE_LIB_ROOT=$BASEDIR/tensorflow/bazel-bin -DFLATBUFFERS_ROOT=$BASEDIR/flatbuffers-1.12.0/install -DArmnn_DIR=$BASEDIR/armnn/build -DARMNN_SOURCE_DIR=$BASEDIR/armnn ..
-- Found Armnn: /home/ubuntu/ArmNNDelegate/armnn/build/ArmnnConfig.cmake
-- Armnn Import: /home/ubuntu/ArmNNDelegate/armnn/build/ArmnnTargets.cmake
-- CMAKE_CURRENT_LIST_DIR /home/ubuntu/ArmNNDelegate/armnn/delegate
-- CMAKE_CURRENT_BINARY_DIR /home/ubuntu/ArmNNDelegate/armnn/delegate/build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/ArmNNDelegate/armnn/delegate/build
ubuntu@ubuntu:~/ArmNNDelegate/armnn/delegate/build$ make -j4
Scanning dependencies of target armnnDelegate
[  4%] Building CXX object CMakeFiles/armnnDelegate.dir/src/armnn_delegate.cpp.o
[  4%] Building CXX object CMakeFiles/armnnDelegate.dir/src/armnn_external_delegate.cpp.o
[  7%] Building CXX object CMakeFiles/armnnDelegate.dir/src/DelegateOptions.cpp.o
[  9%] Linking CXX shared library libarmnnDelegate.so
[  9%] Built target armnnDelegate
Scanning dependencies of target DelegateUnitTests
[ 12%] Building CXX object CMakeFiles/DelegateUnitTests.dir/src/test/ActivationTest.cpp.o
[ 14%] Building CXX object CMakeFiles/DelegateUnitTests.dir/src/test/ArmnnDelegateTest.cpp.o
[ 17%] Building CXX object CMakeFiles/DelegateUnitTests.dir/src/test/BatchSpaceTest.cpp.o
[ 19%] Building CXX object CMakeFiles/DelegateUnitTests.dir/src/test/ArgMinMaxTest.cpp.o
[ 21%] Building CXX object CMakeFiles/DelegateUnitTests.dir/src/test/CastTest.cpp.o
[ 24%] Building CXX object CMakeFiles/DelegateUnitTests.dir/src/test/ComparisonTest.cpp.o
[ 26%] Building CXX object CMakeFiles/DelegateUnitTests.dir/src/test/ControlTest.cpp.o
[ 29%] Building CXX object CMakeFiles/DelegateUnitTests.dir/src/test/Convolution2dTest.cpp.o
[ 31%] Building CXX object CMakeFiles/DelegateUnitTests.dir/src/test/DelegateOptionsTest.cpp.o
/home/ubuntu/ArmNNDelegate/armnn/delegate/src/test/DelegateOptionsTest.cpp:7:10: fatal error: common/include/ProfilingGuid.hpp: No such file or directory
    7 | #include <common/include/ProfilingGuid.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/DelegateUnitTests.dir/build.make:167: CMakeFiles/DelegateUnitTests.dir/src/test/DelegateOptionsTest.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/DelegateUnitTests.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
ubuntu@ubuntu:~/ArmNNDelegate/armnn/delegate/build$ 
 

But file is found:
ubuntu@ubuntu:~/ArmNNDelegate/armnn/delegate/build$ locate ProfilingGuid.hpp
/home/ubuntu/ArmNNDelegate/armnn/profiling/common/include/ProfilingGuid.hpp
ubuntu@ubuntu:~/ArmNNDelegate/armnn/delegate/build$ 

So the question is how to modify the CMakeLists.txt file to locate the missing Profiling includes.  Any help would be greatly appreciated.

**Comment by janeil01** [comment]
Hey @topquant 

what armnn branch are you working on?

**Comment by topquant** [comment]
armnn 26.0.0  is only the standalone build that fails.  The integrated
build works fine.  It appears there are things missing from the standalone
build cmake file.  A revised cmake would solve the problem.

**Comment by janeil01** [comment]
Hey @topquant 

was seeing that problem as well. Thanks for pointing it out!

There is a fix [here](https://review.mlplatform.org/c/ml/armnn/+/6609) if you want to check it out it's available in the master branch.

Thanks again!
Jan
