### ISSUE TITLE
Error compile for ArmNN

### ISSUE THREAD

**Issue by Niuxiaotong** [ARM-software/armnn#592]
aim at: **build armNN Delegate**
ref from:https://github.com/ARM-software/armnn/blob/branches%2Farmnn_21_02/delegate/BuildGuideNative.md
env:
**1) ubuntu18.04
2) tensorflow-2.3.1 -build success
3) flatbuffers-1.12.0-build success
4) compute library_21.02 -build success**
delegate/ComputeLibrary$ **scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC" benchmark_tests=0 validation_tests=0 -j8 internal_only=0**

scons: Reading SConscript files ...
Mkdir("build")
scons: done reading SConscript files.
...
larm_compute_graph
scons: done building targets.

**5) armnn_21.02
/delegate/armnn/build$ cmake .. -DARMCOMPUTE_ROOT=$BASEDIR/ComputeLibrary -DARMCOMPUTENEON=1 -DBUILD_UNIT_TESTS=0**

 The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
....
- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for valgrind/memcheck.h
-- Looking for valgrind/memcheck.h - not found
-- Caffe parser support is disabled
-- Tensorflow parser support is disabled
-- Tensorflow Lite parser support is disabled
-- Armnn Serializer support is disabled
-- ArmNN Quantizer support is disabled
-- PyArmNN wheel package is disabled
-- PyArmNN source package is disabled
-- Including backend common library into the build: 
/home/****/delegate/armnn/src/backends/aclCommon/common.cmake
-- Including backend common library into the build: /home/****/delegate/armnn/src/backends/backendsCommon/common.cmake
-- Including backend into the build: /home/****/delegate/armnn/src/backends/cl/backend.cmake
-- CL backend is disabled
-- Including backend into the build: /home/****/delegate/armnn/src/backends/neon/backend.cmake
-- Including backend into the build: /home/***/delegate/armnn/src/backends/reference/backend.cmake
-- Adding object library dependency to armnn: armnnAclCommon
-- Adding object library dependency to armnn: armnnBackendsCommon
-- Adding object library dependency to armnn: armnnClBackend
-- Adding object library dependency to armnn: armnnNeonBackend
-- Adding object library dependency to armnn: armnnNeonBackendWorkloads
-- Adding object library dependency to armnn: armnnRefBackend
-- Adding object library dependency to armnn: armnnRefBackendWorkloads
-- CMAKE_CURRENT_LIST_DIR /home/***/delegate/armnn
-- CMAKE_CURRENT_BINARY_DIR /home/***/delegate/armnn/build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/***/delegate/armnn/build 
*****@7321fff4a0d4:~/delegate/armnn/build$ make**
Scanning dependencies of target pipeCommon
[  1%] Building CXX object profiling/common/src/CMakeFiles/pipeCommon.dir/CommandHandlerFunctor.cpp.
....
 75%] Building CXX object CMakeFiles/armnn.dir/src/profiling/TimelineUtilityMethods.cpp.o
[ 75%] Building CXX object CMakeFiles/armnn.dir/src/profiling/backends/BackendProfiling.cpp.o
[ 75%] Linking CXX shared library libarmnn.so
/usr/bin/ld: /home/****/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/***/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/***/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/***/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/***/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/home/xiaotong.niu/delegate/ComputeLibrary/build/libarm_compute_core-static.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/armnn.dir/build.make:2394: recipe for target 'libarmnn.so.24.0' failed
make[2]: *** [libarmnn.so.24.0] Error 1
CMakeFiles/Makefile2:464: recipe for target 'CMakeFiles/armnn.dir/all' failed
make[1]: *** [CMakeFiles/armnn.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

build armNN when make , appear erro about"ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)" ,please give me some advice to slove problem, thanks.
---xiaotong

**Comment by janeil01** [comment]
Hey @Niuxiaotong 

did you have trouble building the arm compute library? You seem to have a build directory which should not be the case if you use the commands from the guide. Maybe you have cross compiled the ComputeLibrary before compiling it natively and you didn't do a clean build..

Hard to say. I suggest you try building again but before you do so clean your build:
`cd /home//delegate/ComputeLibrary/ `
`scons -c # clean root directory`
`rm -r build # remove build directory if there is one`
`scons Werror=1 -j8 debug=0 neon=1 opencl=0 os=linux arch=arm64-v8a build=native`

Hope that helps. Keep me posted!
Jan

**Comment by Niuxiaotong** [comment]
it is OK. see document，it use aarch64 machine natively .i am in x86 machine .before i donot add cross compile common to build cl，when add CXX=Aarch64…… CC=aarch64… It is OK，Last ，i guess Most of our not has aarch64 machine so that meet some question according to guide.

**Comment by janeil01** [comment]
Sorry, you were saying you are following the BuildGuideNative and I assumed you are building natively yourself.

Yeah, I'm afraid there currently isn't a cross-compile guide for the delegate available. But there is a general cross-compile guide for ArmNN at armnn/BuildGuideCrossCompilation.md which can be used as a reference.

**Comment by Niuxiaotong** [comment]
> Sorry, you were saying you are following the BuildGuideNative and I assumed you are building natively yourself.
> 
> Yeah, I'm afraid there currently isn't a cross-compile guide for the delegate available. But there is a general cross-compile guide for ArmNN at armnn/BuildGuideCrossCompilation.md which can be used as a reference.

It is OK, I also refer to BuildGuideCrossCompilation.md .
at all ,it is just different compile between aarch64 and x86. 
by the way, accroding to guides, build tflite , is there different between aarch and x86 envinment??

**Comment by janeil01** [comment]
Yes there is. The CrossCompile guide doesn't actually build tflite. It only extracts the schema file that we armnn is using to translate tflite models. 

To build the armnn delegate we need to link to the cpp tflite library. You don't have to build it yourself, as the guide shows it, you can also use a prebuilt tflite binary of it too.

**Comment by Niuxiaotong** [comment]
ok，I will open another issue , close this ,thanks .
