### ISSUE TITLE
Unable to optimize a network with PyArmNN

### ISSUE THREAD

**Issue by FrancescoTosetti** [ARM-software/armnn#596]
Hi, I am trying to optimize a network for keypoint detection on the ARM CPU of my Raspberry Pi4. 
I can parse without any problem from TFLite but then when creating the optimized network with this code:

```python
options = ann.CreationOptions()
runtime = ann.IRuntime(options)
preferredBackends = [ann.BackendId('CpuAcc'),  ann.BackendId('CpuRef')]
opt_network, messages = ann.Optimize(network,  preferredBackends,  runtime.GetDeviceSpec(), ann.OptimizerOptions())

```

I get this error:

``` 
 File "inference.py", line 38, in <module>
    opt_network, messages = ann.Optimize(network, preferredBackends, runtime.GetDeviceSpec(), ann.OptimizerOptions())
  File "/usr/lib/python3/dist-packages/pyarmnn/_generated/pyarmnn.py", line 3575, in Optimize
    return _pyarmnn.Optimize(*args)
RuntimeError: Unspecified dimension while using ShapeInferenceMethod::ValidateOnly
```

I also tried modifying the parsing options in this way 
```python    
parserOptions = ann.TfLiteParserOptions()
parserOptions.m_InferAndValidate = True
parser = ann.ITfLiteParser(parserOptions)
```

and I get now this error, again during network optimization:
`RuntimeError: Dimension index: 0 not specified. Tensor shape not inferred yet. at function CheckDimensionSpecified`

Any suggestion? Is my model incompatible with ArmNN?

Thank you

**Comment by james-conroy-arm** [comment]
Hi @FrancescoTosetti ,

Would it be possible for you to provide the model you are using to us please?
Which version of ArmNN are you using? Are you following this guide? https://github.com/ARM-software/armnn/tree/branches/armnn_21_08/python/pyarmnn

Thanks,
James

**Comment by FrancescoTosetti** [comment]
Hi,
Sure, you can find attached the .tflite model. Yes I am following this guide here: https://github.com/ARM-software/armnn/tree/branches/armnn_21_08/python/pyarmnn .

I also tried fire example in the ML-examples repository and everything went well, so I don't think I missed the Arm NN or PyarmNN installation.

Thanks,
Francesco
[keypoint.tflite.zip](https://github.com/ARM-software/armnn/files/7520279/keypoint.tflite.zip)

**Comment by FrancescoTosetti** [comment]
Hi, I just found a workaround to this problem. I simply retrained and converted the model using TF 2.1 and now it seems to work properly.

**Comment by james-conroy-arm** [comment]
Oh, interesting! What did you train and convert with previously? Would you mind sending the new model so we can compare please?

Thanks,
James

**Comment by FrancescoTosetti** [comment]
I trained the first model with the latest stable TensorFlow version (2.7). 
[Here](https://github.com/ARM-software/armnn/files/7526743/keypoint_model_tf21.zip) you can find the working model (tensorflow==2.1.0)

Thank you anyway for your support 
Francesco

**Comment by james-conroy-arm** [comment]
Hi @FrancescoTosetti ,

Many thanks for the valuable information, this should be helpful when we start to support later versions of TensorFlow. The latest version of TF that we support for ArmNN 21.08 is TF 2.3.1. You can see this near the bottom of our [21.08 Release Notes](https://github.com/ARM-software/armnn/releases/tag/v21.08).

We will start to support TF 2.5.1 in our coming 21.11 Release, arriving at the end of this month (November).

Many thanks,
James

![image](https://user-images.githubusercontent.com/44364429/141454320-a655d8a1-4321-4a8f-8930-4e83e6f7b0a1.png)

**Comment by fr4wanglei** [comment]
Hi, I am trying to optimize a network on the ARM CPU and got the same problem. 
ArmNN version: 22.05
TF version: 2.5.1

I trained the model with yolov5 and export to fp16.tflite
