### ISSUE TITLE
Error while importing pyarmnn

### ISSUE THREAD

**Issue by Tyogi** [ARM-software/armnn#599]
I am getting Your ArmNN library instance does not support Onnx models parser functionality.  Skipped IOnnxParser import.
26.0.0
Instead of # Returns '{ARMNN_MAJOR_VERSION}.0.0' e.g. 27.0.0
while executing python3 -c "import pyarmnn as ann;print(ann.GetVersion())". please look into it.
![Screenshot from 2021-12-07 19-31-53](https://user-images.githubusercontent.com/77155162/145044299-1d9e3d02-3f60-4d6b-98e3-122c39754e51.png)

**Comment by MikeJKelly** [comment]
Hi @Tyogi 

```Your ArmNN library instance does not support Onnx models parser functionality. Skipped IOnnxParser import.```

Is just a warning that ArmNN was built without Onnx parser support, the ArmNN version is printed on the next line: ```26.0.0```

Best regards,
Mike

**Comment by Tyogi** [comment]
can I continue or should I do anything else.
While I am executing sudo apt-get install -y armnn-latest-cpu
I am getting error saying:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package armnn-latest-cpu

**Comment by MikeJKelly** [comment]
It should be OK to continue with it. 

If apt-get can't find the armnn-latest-cpu package then you might need to use these commands before you try to run ```sudo apt-get install -y armnn-latest-cpu``` :

```
sudo add-apt-repository ppa:armnn/ppa
sudo apt update
```

Then it should work!

**Comment by Tyogi** [comment]
Yes, I executed those commands but still not working.

**Comment by MikeJKelly** [comment]
Try ```sudo apt-get install -y armnn-latest-all ``` and see what it installs, on my x86 dev machine I see the following:

```
The following additional packages will be installed:
  libarmnn-cpuref-backend26 libarmnn26 libarmnntfliteparser24 libflatbuffers1
```
```armnn-latest-cpu``` will only work on a machine that as an Arm CPU.

**Comment by Tyogi** [comment]
I am using intel what should I do now should I skip these commands are their any other commands

**Comment by MikeJKelly** [comment]
If you're running on Intel then the commands that you have already run (```sudo apt-get install -y python3-pyarmnn armnn-latest-all```) should be enough to get armnn to work. You will be able to use the reference backend on intel but it may be quite slow.  

Are you following a guide? If you are and the guide says to specify the backend to use by using ```--preferred_backends CpuAcc CpuRef``` , for example, then you will have to use ```--preferred_backends CpuRef``` instead but then the example should still work.

**Comment by Tyogi** [comment]
Getting error while executing this cmake $BASEDIR/tensorflow 
CMake Error: The source directory "/home/yogi/ArmNNDelegate/tensorflow" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
please look into it.

**Comment by MikeJKelly** [comment]
Hi @Tyogi 

are you following a different guide? You shouldn't need to build tensorflow if you've already installed armnn-latest-all (that will have libarmnntfliteparser24). What tensorflow version are you using? If you want to build tensorflow with CMake then you will need to download tensorflow version 2.4 or later.

Best regards,
Mike

**Comment by Tyogi** [comment]
I am new to this, I am not really understanding what to do. Is their any other way to install armnn like a video or something.Please help me

**Comment by MikeJKelly** [comment]
Hi @Tyogi 

You have successfully installed ArmNN, you can see that because this command:

```python3 -c "import pyarmnn as ann;print(ann.GetVersion())"```

Returns ```26.0.0```. So ArmNN has been correctly installed.

What are you trying to do with ArmNN?

**Comment by Tyogi** [comment]
I have to analyse the cpu and GPU performances of a mobile phone and optimize the memory bottleneck.

**Comment by MikeJKelly** [comment]
Hi @Tyogi 

you can download the libraries for Android devices here:

https://github.com/ARM-software/armnn/releases/tag/v21.11

The library to download depends on the version of Android installed and the type of CPU on the mobile phone you're using. 

If you want to build the libraries you will need to follow the Android build guide:
https://github.com/ARM-software/armnn/blob/branches/armnn_21_11/BuildGuideAndroidNDK.md

Best regards,
Mike
