### ISSUE TITLE
Linking CXX executable UnitTests error

### ISSUE THREAD

**Issue by szihs** [ARM-software/armnn#6]
Hello support-ARM,

While using static boost libs I face linking error in UnitTests executable.

Linking CXX executable UnitTests
```
libarmnn.so: undefined reference to `boost::detail::add_thread_exit_function(boost::detail::thread_exit_function_base*)'
libarmnn.so: undefined reference to `boost::detail::get_tss_data(void const*)'
libarmnn.so: undefined reference to `boost::detail::set_tss_data(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*, bool)'

```

Changing in file cmake/GlobalConfig.cmake
```
-find_package(Boost 1.59 REQUIRED COMPONENTS unit_test_framework system filesystem log program_options)
+find_package(Boost 1.59 REQUIRED COMPONENTS unit_test_framework system filesystem log **thread** program_options)

```
makes it link properly.

Regards,
Harsh

**Comment by MatthewARM** [comment]
Thanks @szihs, you are right that boost thread is needed as it is a dependency of some of the other boost libraries. However, indirect dependencies are supposed to be added automatically by armnn/cmake/modules/FindBoost.cmake. Please could you let me know which version of Cmake and boost you are using? I'm using cmake 3.5.1 and boost 1.64.

Thanks,
Matthew

**Comment by MatthewARM** [comment]
Thanks, then probably what has happened here is that boost 1.65 has an additional dependency on boost.thread that was not previously needed, and our version of FindBoost.cmake does not know about it.

I'll flag the issue internally and we'll fix it properly in a future release. I'm closing this issue as you have a workaround.

All the best,
Matthew
