### ISSUE TITLE
Limit on Pad, Stride & Kernel values Convolution type layers is 0 & 11.

### ISSUE THREAD

**Issue by ssj4gogeta** [ARM-software/armnn#60]
Hello,
Why are pad, stride & kernel width values restricted to lie between 0 & 11  armnnCaffe parser?
Also, why is there a restriction that they should be equal? [for example, padH=padW]
Thanks!

**Comment by Surmeh** [comment]
Hi @ssj4gogeta,

We went ahead with what Compute Library had implemented at that time. I'll discuss this internally with Compute Library team and see if any modifications are needed.

**Comment by Surmeh** [comment]
Hi @ssj4gogeta, since the initial question has been answered, I'm marking this ticket resolved. Let us know if you have any other issues.
