### ISSUE TITLE
armnn v22.02 cmake failing with error Could NOT find TfLiteSrc (missing: TfLite_INCLUDE_DIR   TfLite_Schema_INCLUDE_PATH)

### ISSUE THREAD

**Issue by supratimc239** [ARM-software/armnn#607]
Hi,
I am new to armnn development.
I have cloned https://github.com/ARM-software/armnn.git and using armnn_21_11 branch.

I am using following cmake command:
cmake .. \
    -DCMAKE_ANDROID_NDK=$NDK \
    -DCMAKE_SYSTEM_NAME=Android \
    -DCMAKE_SYSTEM_VERSION=29 \
    -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
    -DCMAKE_EXE_LINKER_FLAGS="-pie -llog -lz" \
    -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
    -DCMAKE_FIND_ROOT_PATH=$HOME/armnn-devenv/boost/install \
    -DFLATBUFFERS_INCLUDE_PATH=$HOME/armnn-devenv/armnn/flatbuffers/include \
    -DFLATBUFFERS_LIBRARY=$HOME/armnn-devenv/armnn/flatbuffers/libflatbuffers.a \
    -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
    -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
    -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=0 \
    -DBUILD_TF_PARSER=0 \
    -DBUILD_ARMNN_SERIALIZER=1 \
    -DBUILD_ARMNN_QUANTIZER=1 \
    -DFLATC=$HOME/armnn-devenv/armnn/flatbuffers/flatc \
    -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install \
    -DBUILD_TF_LITE_PARSER=1 \
    -DTF_LITE_GENERATED_PATH=$HOME/armnn-devenv/armnn/flatbuffers/tflite \
    -DSAMPLE_DYNAMIC_BACKEND=1 \
    -DDYNAMIC_BACKEND_PATHS=/data/local/tmp/dynamic/sample/

Following is output of the command:
>     -DCMAKE_ANDROID_NDK=$NDK \
>     -DCMAKE_SYSTEM_NAME=Android \
>     -DCMAKE_SYSTEM_VERSION=29 \
>     -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
>     -DCMAKE_EXE_LINKER_FLAGS="-pie -llog -lz" \
>     -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
>     -DCMAKE_FIND_ROOT_PATH=$HOME/armnn-devenv/boost/install \
>     -DFLATBUFFERS_INCLUDE_PATH=$HOME/armnn-devenv/armnn/flatbuffers/include \
>     -DFLATBUFFERS_LIBRARY=$HOME/armnn-devenv/armnn/flatbuffers/libflatbuffers.a \
>     -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
>     -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/ \
>     -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=0 \
>     -DBUILD_TF_PARSER=0 \
>     -DBUILD_ARMNN_SERIALIZER=1 \
>     -DBUILD_ARMNN_QUANTIZER=1 \
>     -DFLATC=$HOME/armnn-devenv/armnn/flatbuffers/flatc \
>     -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install \
>     -DBUILD_TF_LITE_PARSER=1 \
>     -DTF_LITE_GENERATED_PATH=$HOME/armnn-devenv/armnn/flatbuffers/tflite \
>     -DSAMPLE_DYNAMIC_BACKEND=1 \
>     -DDYNAMIC_BACKEND_PATHS=/data/local/tmp/dynamic/sample/
-- Android: Targeting API '29' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected unified Clang toolchain
-- The C compiler identification is Clang 8.0.7
-- The CXX compiler identification is Clang 8.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/supratim/armnn-devenv/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/supratim/armnn-devenv/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Flatbuffers headers are located at: /home/supratim/armnn-devenv/armnn/flatbuffers/include
-- Flatbuffers library located at: /home/supratim/armnn-devenv/armnn/flatbuffers/libflatbuffers.a
-- Tf Lite generated header found at: /home/supratim/armnn-devenv/armnn/flatbuffers/tflite
-- Flatbuffers headers are located at: /home/supratim/armnn-devenv/armnn/flatbuffers/include
-- Flatbuffers library located at: /home/supratim/armnn-devenv/armnn/flatbuffers/libflatbuffers.a
-- Looking for valgrind/memcheck.h
-- Looking for valgrind/memcheck.h - not found
-- PyArmNN wheel package is disabled
-- PyArmNN source package is disabled
-- Set TENSORFLOW_ROOT: /home/supratim/armnn-devenv/armnn/../tensorflow
**CMake Error at /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find TfLiteSrc (missing: TfLite_INCLUDE_DIR
  TfLite_Schema_INCLUDE_PATH)**
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  delegate/cmake/Modules/FindTfLiteSrc.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:42 (_find_package)
  src/armnnTfLiteParser/CMakeLists.txt:26 (find_package)

-- Configuring incomplete, errors occurred!

**Could you please tell what I am missing here? Please note I want to use my TF-lite model on ARM CPU and hence I did not create any TF-lite delegate (as per ARM documentation needed for GPU and DSP).**
I created flatbuffer library using command "cmake -DFLATBUFFERS_BUILD_FLATC=1-DFLATBUFFERS_BUILD_TESTS=ON -DFLATBUFFERS_BUILD_FLATLIB=ON -DFLATBUFFERS_BUILD_FLATHASH=OFF"

and generated schema using following commands inside flatbuffers (following instructions in https://developer.arm.com/documentation/102644/2108/Generate-the-build-dependencies-for-TensorFlow-Lite):
$ mkdir tflite
$ cd tflite
$ cp /$HOME/armnn-devenv/google/tensorflow/tensorflow/lite/schema/schema.fbs .
$ $HOME/armnn-devenv/armnn/flatbuffers/flatc -c --gen-object-api --reflect-types --reflect-names schema.fbs

**Comment by Rahn80643** [comment]
Hi, I changed `-DTF_LITE_GENERATED_PATH=` to `-DTfLite_Schema_INCLUDE_PATH=` and `-DTfLite_INCLUDE_DIR=`, and the armnn could be built.

**Comment by james-conroy-arm** [comment]
Hi @supratimc239 ,

Could you please let us know which guide/tutorial you are following?

Cheers,
James

**Comment by supratimc239** [comment]
Hi James,

I am following the link https://github.com/ARM-software/armnn/blob/branches/armnn_21_11/BuildGuideAndroidNDK.md. Please let me know if this is the correct link.

Cheers,
Supratim

**Comment by supratimc239** [comment]
Hi Sadik,

As you can see below, I was setting TF_LITE_GENERATED_PATH=$HOME/armnn-devenv/armnn/flatbuffers/tflite and $BASEDIR/tensorflow/tensorflow/lite/schema.

**Could you please have a look at my cmake command below and see if this is the only change I need to do?**
-DCMAKE_ANDROID_NDK=$NDK
-DCMAKE_SYSTEM_NAME=Android
-DCMAKE_SYSTEM_VERSION=29
-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a
-DCMAKE_EXE_LINKER_FLAGS="-pie -llog -lz"
-DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/
-DCMAKE_FIND_ROOT_PATH=$HOME/armnn-devenv/boost/install
-DFLATBUFFERS_INCLUDE_PATH=$HOME/armnn-devenv/armnn/flatbuffers/include
-DFLATBUFFERS_LIBRARY=$HOME/armnn-devenv/armnn/flatbuffers/libflatbuffers.a
-DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build
-DBOOST_ROOT=$HOME/armnn-devenv/boost/install/
-DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=0
-DBUILD_TF_PARSER=0
-DBUILD_ARMNN_SERIALIZER=1
-DBUILD_ARMNN_QUANTIZER=1
-DFLATC=$HOME/armnn-devenv/armnn/flatbuffers/flatc
-DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install
-DBUILD_TF_LITE_PARSER=1
-DTF_LITE_GENERATED_PATH=$HOME/armnn-devenv/armnn/flatbuffers/tflite
-DSAMPLE_DYNAMIC_BACKEND=1
-DDYNAMIC_BACKEND_PATHS=/data/local/tmp/dynamic/sample/

**Also, could you please let me know what versions of tensorflow, flatbuffer, protobuf and boost library are compatible with armnn and compute library v21.11?**

Thanks

**Comment by SadikARM** [comment]
Hi @supratimc239,

Could you confirm that `$HOME/armnn-devenv/armnn/flatbuffers/tflite` is TensorflowLite install directory? I can not see where `$BASEDIR/tensorflow/tensorflow/lite/schema` is set from the commands mentioned above?

BOOST is removed as a dependency from Arm NN on v21.08. You do not need to install BOOST if you are using v21.08 or later versions and you do not need to set `-DBOOST_ROOT=$HOME/armnn-devenv/boost/install/`
Arm NN Quantizer tool is also removed from Arm NN on v21.05. You do not set `-DBUILD_ARMNN_QUANTIZER=1` if you are using v21.05 or later versions.

Please see the [v21.11 Release page](https://github.com/ARM-software/armnn/releases/tag/v21.11) Build Dependencies table for the versions of the dependencies used to build Arm NN.

Best Regards,
Sadik

**Comment by supratimc239** [comment]
Hi @SadikARM ,

Sorry for the late response. I recently moved both my ACL and armnn code to v12.02 and based on https://developer.arm.com/documentation/102644/2202/Build-Arm-NN?lang=en attempted following cmake command from armnn/build:

CXX=aarch64-linux-android-clang++ \
CC=aarch64-linux-android-clang \
CXX_FLAGS="-fPIE -fPIC" \
cmake .. \
-DCMAKE_ANDROID_NDK=$NDK \
-DCMAKE_SYSTEM_NAME=Android \
-DCMAKE_SYSTEM_VERSION=29 \
-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
-DCMAKE_EXE_LINKER_FLAGS="-pie -llog -lz" \
-DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/ \
-DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build \
-DBUILD_TF_LITE_PARSER=1 \
-DTF_LITE_GENERATED_PATH=$HOME/armnn-devenv/google/tensorflow/tensorflow/lite/schema \
-DFLATBUFFERS_ROOT=$HOME/armnn-devenv/flatbuffers-arm64 \
-DFLATC_DIR=$HOME/armnn-devenv/flatbuffers-1.12.0/build/ \
-DARMCOMPUTENEON=1 -DARMCOMPUTECL=0 -DARMNNREF=1 \
-DBUILD_TESTS=1

But I am still getting following error:
-- Tf Lite generated header found at: /home/supratim/armnn-devenv/google/tensorflow/tensorflow/lite/schema
-- Looking for valgrind/memcheck.h
-- Looking for valgrind/memcheck.h - not found
-- Armnn Serializer support is disabled
-- PyArmNN wheel package is disabled
-- PyArmNN source package is disabled
-- Set TENSORFLOW_ROOT: /home/supratim/armnn-devenv/armnn/../tensorflow
__CMake Error at /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find TfLiteSrc (missing: TfLite_INCLUDE_DIR
  TfLite_Schema_INCLUDE_PATH)
Call Stack (most recent call first):_
  _/usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  delegate/cmake/Modules/FindTfLiteSrc.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:42 (_find_package)
  src/armnnTfLiteParser/CMakeLists.txt:26 (find_package)

-- Configuring incomplete, errors occurred!

Could you please tell me what I am missing?

Thanks in advance.

**Comment by supratimc239** [comment]
Once I added "-DTENSORFLOW_ROOT=$HOME/armnn-devenv/google/tensorflow \" in the cmake command for armnn, cmake error I was seeing was removed and instead I can see following prints:
"-- TENSORFLOW_ROOT: /home/supratim/armnn-devenv/google/tensorflow
-- Found TfLiteSrc: /home/supratim/armnn-devenv/google/tensorflow"

After that when I use make command I can successfully build.
