### ISSUE TITLE
When run the UnitTests, it seems to be stuck?

### ISSUE THREAD

**Issue by clhne** [ARM-software/armnn#61]
My platform and env:
Ubuntu18.04, python2.7, scons2.4.1
I compile both ArmNN and Compute Library "How to use the Android NDK to build ArmNN" on arm64-v8a, but when run the UnitTests: 
![unittests_error](https://user-images.githubusercontent.com/11884005/45068013-22fa3100-b0f8-11e8-8f9c-5676ec91b8ec.png)
Here,stack trace:

> execve("./UnitTests", ["./UnitTests"], [/* 20 vars */]) = 0
set_tid_address(0x7fb36caaa8)           = 2404
mmap(NULL, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb3611000
mprotect(0x7fb3611000, 4096, PROT_NONE) = 0
sigaltstack({ss_sp=0x7fb3612000, ss_flags=0, ss_size=16384}, NULL) = 0
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3612000, 16384, "thread signal stack") = 0
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3611000, 4096, "thread signal stack guard page") = 0
mprotect(0x7fb36c2000, 12288, PROT_READ) = 0
mprotect(0x7fb36c9000, 4096, PROT_READ) = 0
mprotect(0x7fb36c9000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c9000, 4096, PROT_READ) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb36c1000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb36c1000, 4096, "atexit handlers") = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
openat(AT_FDCWD, "/dev/urandom", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
ioctl(3, RNDGETENTCNT, 0x7fcabaf194)    = 0
read(3, "+\233<V3\211\201\321\277F\37\323U\217\234\324\7\306\326#9\22V\2537\t\277\210\344\261|k"..., 40) = 40
close(3)                                = 0
mmap(NULL, 16, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb3610000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3610000, 16, "arc4random _rs structure") = 0
mmap(NULL, 1088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb360f000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb360f000, 1088, "arc4random _rsx structure") = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb360e000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb360e000, 4096, "linker_alloc_small_objects") = 0
mmap(NULL, 24, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb360d000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb360d000, 24, "linker_alloc_vector") = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb360c000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb360c000, 4096, "linker_alloc_small_objects") = 0
mmap(NULL, 24, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb360b000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb360b000, 24, "linker_alloc_vector") = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb360a000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb360a000, 4096, "linker_alloc_small_objects") = 0
mmap(NULL, 24, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3609000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3609000, 24, "linker_alloc_vector") = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3608000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3608000, 4096, "linker_alloc") = 0
newfstatat(AT_FDCWD, "/dev/__properties__", {st_mode=S_IFDIR|0755, st_size=1400, ...}, 0) = 0
openat(AT_FDCWD, "/property_contexts", O_RDONLY|O_CLOEXEC) = 3
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3607000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3607000, 4096, "linker_alloc_lob") = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=9583, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3605000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3605000, 8192, "linker_alloc_lob") = 0
read(3, "#line 1 \"system/sepolicy/propert"..., 4096) = 4096
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3604000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3604000, 4096, "linker_alloc_small_objects") = 0
mmap(NULL, 24, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3603000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3603000, 24, "linker_alloc_vector") = 0
read(3, ":config_prop:s0\nro.config.      "..., 4096) = 4096
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3602000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3602000, 4096, "linker_alloc_small_objects") = 0
mmap(NULL, 48, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3601000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3601000, 48, "linker_alloc_vector") = 0
munmap(0x7fb360b000, 24)                = 0
read(3, "file     u:object_r:coresight_pr"..., 4096) = 1391
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb360b000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb360b000, 4096, "linker_alloc_small_objects") = 0
mmap(NULL, 48, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3600000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3600000, 48, "linker_alloc_vector") = 0
munmap(0x7fb360d000, 24)                = 0
read(3, "", 4096)                       = 0
munmap(0x7fb3604000, 4096)              = 0
close(3)                                = 0
munmap(0x7fb3605000, 8192)              = 0
openat(AT_FDCWD, "/dev/__properties__/properties_serial", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=131072, ...}) = 0
mmap(NULL, 131072, PROT_READ, MAP_SHARED, 3, 0) = 0x7fb35e0000
close(3)                                = 0
rt_sigaction(SIGABRT, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, NULL, 8) = 0
rt_sigaction(SIGBUS, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, NULL, 8) = 0
rt_sigaction(SIGFPE, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, NULL, 8) = 0
rt_sigaction(SIGILL, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, NULL, 8) = 0
rt_sigaction(SIGSEGV, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, NULL, 8) = 0
rt_sigaction(SIGSTKFLT, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, NULL, 8) = 0
rt_sigaction(SIGTRAP, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, NULL, 8) = 0
newfstatat(AT_FDCWD, "/proc/self/exe", {st_mode=S_IFREG|0777, st_size=7637192, ...}, 0) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fb36c1000, 4096, PROT_READ) = 0
futex(0x7fb36c6aa0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
readlinkat(AT_FDCWD, "/proc/self/exe", "/data/local/tmp/UnitTests", 4096) = 25
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb360d000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb360d000, 4096, "linker_alloc") = 0
newfstatat(AT_FDCWD, "/system", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
newfstatat(AT_FDCWD, "/system/lib64", {st_mode=S_IFDIR|0755, st_size=8192, ...}, AT_SYMLINK_NOFOLLOW) = 0
newfstatat(AT_FDCWD, "/vendor", {st_mode=S_IFLNK|0777, st_size=14, ...}, AT_SYMLINK_NOFOLLOW) = 0
readlinkat(AT_FDCWD, "/vendor", "/system/vendor", 4095) = 14
newfstatat(AT_FDCWD, "/system", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
newfstatat(AT_FDCWD, "/system/vendor", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
newfstatat(AT_FDCWD, "/system/vendor/lib64", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 3
fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
connect(3, {sa_family=AF_LOCAL, sun_path="/dev/socket/logdw"}, 110) = 0
openat(AT_FDCWD, "/dev/__properties__/u:object_r:default_prop:s0", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFREG|0444, st_size=131072, ...}) = 0
mmap(NULL, 131072, PROT_READ, MAP_SHARED, 4, 0) = 0x7fb35c0000
close(4)                                = 0
openat(AT_FDCWD, "/dev/__properties__/u:object_r:logd_prop:s0", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFREG|0444, st_size=131072, ...}) = 0
mmap(NULL, 131072, PROT_READ, MAP_SHARED, 4, 0) = 0x7fb35a0000
close(4)                                = 0
clock_gettime(CLOCK_REALTIME, {316573014, 369397515}) = 0
writev(3, [{"\0", 1}, {"d\t", 2}, {"V\205\336\22\v\217\4\26", 8}, {"\5", 1}, {"linker\0", 7}, {"/data/local/tmp/UnitTests: unuse"..., 65}], 6) = 84
close(3)                                = 0
write(2, "WARNING: linker: ", 17WARNING: linker: )       = 17
write(2, "/data/local/tmp/UnitTests", 25/data/local/tmp/UnitTests) = 25
write(2, ": unused DT entry: type ", 24: unused DT entry: type ) = 24
write(2, "0xf", 30xf)                      = 3
write(2, " arg ", 5 arg )                    = 5
write(2, "0x1d251", 70x1d251)                  = 7
write(2, "\n", 1
)                       = 1
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 3
fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
connect(3, {sa_family=AF_LOCAL, sun_path="/dev/socket/logdw"}, 110) = 0
clock_gettime(CLOCK_REALTIME, {316573014, 375285862}) = 0
writev(3, [{"\0", 1}, {"d\t", 2}, {"V\205\336\22fh^\26", 8}, {"\5", 1}, {"linker\0", 7}, {"/data/local/tmp/UnitTests: unsup"..., 66}], 6) = 85
close(3)                                = 0
write(2, "WARNING: linker: ", 17WARNING: linker: )       = 17
write(2, "/data/local/tmp/UnitTests", 25/data/local/tmp/UnitTests) = 25
write(2, ": unsupported flags DT_FLAGS_1=", 31: unsupported flags DT_FLAGS_1=) = 31
write(2, "0x8000000", 90x8000000)                = 9
write(2, "\n", 1
)                       = 1
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3606000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3606000, 4096, "linker_alloc") = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3605000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3605000, 4096, "linker_alloc") = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb3604000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb3604000, 4096, "linker_alloc_small_objects") = 0
openat(AT_FDCWD, "/system/lib64/liblog.so", O_RDONLY|O_CLOEXEC) = 3
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb359e000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb359e000, 8192, "linker_alloc_lob") = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb359c000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb359c000, 8192, "linker_alloc_lob") = 0
readlinkat(AT_FDCWD, "/proc/self/fd/3", "/system/lib64/liblog.so", 4096) = 23
munmap(0x7fb359c000, 8192)              = 0
munmap(0x7fb359e000, 8192)              = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=68392, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb359f000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb359f000, 4096, "linker_alloc_small_objects") = 0
mmap(NULL, 24, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0) = 0x7fb359e000
prctl(0x53564d41 /* PR_??? */, 0, 0x7fb359e000, 24, "linker_alloc_vector") = 0
pread64(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 64, 0) = 64
mmap(NULL, 576, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb359d000
mmap(NULL, 3984, PROT_READ, MAP_PRIVATE, 3, 0x10000) = 0x7fb359c000
mmap(NULL, 5728, PROT_READ, MAP_PRIVATE, 3, 0xf000) = 0x7fb359a000
mmap(NULL, 4045, PROT_READ, MAP_PRIVATE, 3, 0x1000) = 0x7fb3599000
openat(AT_FDCWD, "/system/lib64/libarmnnTfParser.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/system/vendor/lib64/libarmnnTfParser.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
close(3)                                = 0
munmap(0x7fb3599000, 4045)              = 0
munmap(0x7fb359a000, 5728)              = 0
munmap(0x7fb359c000, 3984)              = 0
munmap(0x7fb359d000, 576)               = 0
munmap(0x7fb359f000, 4096)              = 0
munmap(0x7fb3604000, 4096)              = 0
writev(2, [{"CANNOT LINK EXECUTABLE \"./UnitTe"..., 77}, {"\n", 1}], 2CANNOT LINK EXECUTABLE "./UnitTests": library "libarmnnTfParser.so" not found
) = 78
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 3
fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
connect(3, {sa_family=AF_LOCAL, sun_path="/dev/socket/logdw"}, 110) = 0
clock_gettime(CLOCK_REALTIME, {316573014, 395453323}) = 0
writev(3, [{"\4", 1}, {"d\t", 2}, {"V\205\336\22\213#\222\27", 8}, {"\7", 1}, {"libc\0", 5}, {"CANNOT LINK EXECUTABLE \"./UnitTe"..., 78}], 6) = 95
close(3)                                = 0
rt_sigprocmask(SIG_SETMASK, ~[ABRT], [], 8) = 0
tgkill(2404, 2404, SIGABRT)             = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=2404, si_uid=0} ---
rt_sigaction(SIGABRT, {SIG_DFL, [], SA_RESTART}, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, 8) = 0
rt_sigaction(SIGABRT, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, NULL, 8) = 0
prctl(PR_GET_NAME, "UnitTests")         = 0
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 3
fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
connect(3, {sa_family=AF_LOCAL, sun_path="/dev/socket/logdw"}, 110) = 0
clock_gettime(CLOCK_REALTIME, {316573014, 400076246}) = 0
writev(3, [{"\4", 1}, {"d\t", 2}, {"V\205\336\22\326\255\330\27", 8}, {"\7", 1}, {"libc\0", 5}, {"Fatal signal 6 (SIGABRT), code -"..., 58}], 6) = 75
close(3)                                = 0
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
connect(3, {sa_family=AF_LOCAL, sun_path=@"android:debuggerd"}, 20) = 0
write(3, "\0\0\0\0d\t\0\0\0\0\0\0\0\0\0\0\372\377\377\377", 20) = 20
read(3, 0x7fb3614d18, 1)                = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
read(3, "", 1)                          = 0
close(3)                                = 0
rt_sigaction(SIGABRT, {SIG_DFL, [], SA_RESTART}, {0x7fb361ee10, [], SA_RESTART|SA_SIGINFO|SA_ONSTACK}, 8) = 0
rt_tgsigqueueinfo(2404, 2404, SIGABRT, {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=2404, si_uid=0}) = 0
rt_sigreturn({mask=~[ABRT KILL STOP]})  = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=2404, si_uid=0} ---
+++ killed by SIGABRT +++
Aborted 

And, addr2line result:
armnn-devenv/ComputeLibrary/include/CL/cl2.hpp:7530
armnn-devenv/ComputeLibrary/src/runtime/CL/CLMemoryRegion.cpp:73
armnn-devenv/ComputeLibrary/src/core/CL/OpenCL.cpp:542
armnn-devenv/ComputeLibrary/src/runtime/CPP/CPPScheduler.cpp:182

Thanks in advance!
Best,
clhne

**Comment by Surmeh** [comment]
Hi @clhne,

From the trace, it looks like it's not able to find libarmnnTfParser.so - "CANNOT LINK EXECUTABLE "./UnitTests": library "libarmnnTfParser.so" not found". Could you please check whether the executables are present.

Thanks,
Surabhi

**Comment by Surmeh** [comment]
Hi @clhne, Did you manage to resolve your issue? Please get back in touch if you need any help.

**Comment by MatthewARM** [comment]
@clhne In order to debug your hanging tests, I would try:
* Build ArmNN without NEON, CL, TensorflowParser or CaffeParser (ie. use CMake to turn off all optional modules with -DARMCOMPUTENEON=1 -DARMCOMPUTECL=0 -DBUILD_TF_PARSER=0 -DBUILD_CAFFE_PARSER=0)
* Run the tests and see if you get the same problem. If you do, then run them under gdb and use gdb to print a stack trace when the hang happens
* If the tests work when all the optional modules are turned off, try turning them on one at a time, rerunning the tests each time in the following order until the tests start hanging again:
** NEON
** CL
** CaffeParser
** TensorflowParser

At that point we should have a minimal build of ArmNN that just has the modules needed to cause the problem, and a detailed stack backtrace to help figure out what it going on.

Alll the best,
Matthew

**Comment by Surmeh** [comment]
Hi @clhne, did you get a chance to try the steps Matthew mentioned. Please let us know if you need further assistance.

**Comment by Surmeh** [comment]
Hi @clhne, did you get a chance to try the steps Matthew mentioned. Please let us know if you need further assistance.

**Comment by clhne** [comment]
I'll try on the new machine, and then give feedback.

**Comment by MatthewARM** [comment]
Closing this ticket due to inactivity, @clhne if you are still having trouble please get back in touch.

All the best,
Matthew
