### ISSUE TITLE
Applying hint to executeNetwork not works

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#613]
Hi,

I'm trying to apply the "hint" mechanism for a tflite model to `executeNetwork` based on [this issue](https://github.com/ARM-software/armnn/issues/536), and I added the following code snippets to `InferenceModel.hpp` which is the attachment:

0. The version of Armnn and Compute Library are 21.08
1. [line 11] add header `#include <armnn/IStrategy.hpp>` 
2. [line 138] implement a class `class VerifyActivationName ` and assigned the backend IDs to target layer types 
3. [line 362] create a VerifyActivationName object and utilize it with `network->ExecuteStrategy(visitor);`

However, executeNetwork fails to execute inference of the model, and the error occurs at `network->ExecuteStrategy(visitor);`. Is there a step omiited in the steps above?
![Screenshot](https://user-images.githubusercontent.com/8951991/153166477-97711728-35f7-4bc9-b6fd-e9b913d790c6.png)

Best Regards, 
Rahn
[InferenceModel.hpp.txt](https://github.com/ARM-software/armnn/files/8031323/InferenceModel.hpp.txt)

**Comment by SadikARM** [comment]
Hi @Rahn80643,

Could you try  `network->ExecuteStrategy(visitor);` call on Line 373 after TfLite Parser parsed the model? After the TfLite Parser, Arm NN graph would be already built so `ExecuteStrategy()` call could visit all the layers in the network.

Best Regards,
Sadik

**Comment by Rahn80643** [comment]
Hi SadikARM,

I changed `network->ExecuteStrategy(visitor);` after TfLiter parser parsed the model and `hint` could be executed sucessfully.

Thank you!

Best Regards,
Rahn
