### ISSUE TITLE
Profiling models in armnn

### ISSUE THREAD

**Issue by saswat0** [ARM-software/armnn#615]
I'd like to run onnx/tflite models using pyarmnn (using the CPU, GPU, both) and profile (layer-wise and hardware level) the inference. What's the recommended approach to do that? The steps to use streamline aren't very clear in the official guides

**Comment by james-conroy-arm** [comment]
Hi @saswat0 ,

There is this guide for Streamline which includes some info on using it with Arm NN: https://developer.arm.com/documentation/101814/0709/Target-Setup/Using-Streamline-with-Arm-NN

I am not sure if this guide is still up-to-date, but it may help.

Cheers,
James

**Comment by saswat0** [comment]
@james-conroy-arm ,
The steps to install and configure gatord/streamline aren't very lucid in this official doc. Could you please direct me to some maintained repos instead?

Thanks in advance

**Comment by FinnWilliamsArm** [comment]
Hi @saswat0 you could try using the internal profiling which does not require streamline.
There is a good explanation here: https://github.com/ARM-software/armnn/issues/468#issuecomment-717472886
on how to use it.

Regards,
Finn

**Comment by saswat0** [comment]
Got you. Thanks Finn 👍
