### ISSUE TITLE
Supported models in onnx_parser

### ISSUE THREAD

**Issue by saswat0** [ARM-software/armnn#616]
I was trying to run inference on models released by [onnx](https://github.com/onnx/models/tree/main/vision/classification) but most of them run into errors. I've attached some of the errors here

```
RuntimeError: Unsupported operation LRN for node ''  at function LoadGraph [armnn-dist/armnn/src/armnnOnnxParser/OnnxParser.cpp:886]

RuntimeError: Tensor numDimensions must be greater than 0 at function CheckValidNumDimensions [armnn-dist/armnn/src/armnn/Tensor.cpp:287]

RuntimeError: Error parsing Convolution node: . The 'group'=4 parameter should be 1 or be equal to the channel of the input shape=24 (in NCHW format).  at function ParseConv [armnn-dist/armnn/src/armnnOnnxParser/OnnxParser.cpp:1751]

RuntimeError: Unsupported operation LRN for node ''  at function LoadGraph [armnn-dist/armnn/src/armnnOnnxParser/OnnxParser.cpp:886]
```

Is there any comprehensive list of supported onnx models for compiling with pyarmnn's onnxparser?

**Comment by MikeJKelly** [comment]
Hi @saswat0 

We do not have a comprehensive list of supported ONNX models. Our ONNX support is very limited as we're focusing on TF Lite support. You can see the ONNX operators we support and some details of the models we've used for testing at: 

https://arm-software.github.io/armnn/latest/parsers.xhtml#S5_onnx_parser

Best regards,
Mike

**Comment by saswat0** [comment]
@MikeJKelly 
Understood. In that case, for the tflite models, are all the models listed in this above page the officially tested ones?
I'm looking to test and benchmark image classifications models on aarch64 boards

**Comment by MikeJKelly** [comment]
@saswat0 

Yes, those are the models we currently test with.

**Comment by saswat0** [comment]
Got you
