### ISSUE TITLE
Unspecified dimension while using ShapeInferenceMethod::ValidateOnly when loading TFLite models

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#619]
Hi,

I'm trying to apply a BiSeNetV2 model implemented by TensorFlow2 API to Arm NN, but I met the following error message:
`Fatal: Armnn Error: Unspecified dimension while using ShapeInferenceMethod::ValidateOnly`

![armnn_error](https://user-images.githubusercontent.com/8951991/157829658-e72787cc-fb7f-44d2-8a09-af8379c69052.png)

The tflite model is converted based on the [tutorial](https://www.tensorflow.org/lite/convert). The followings are the settings of the environment:
- ArmNN 21.08
- Compute Library 21.08
- TensorFlow 2.4.0
- tensorflow-model-optimization	0.7.1

How to know which layer causes the error above, and is the error above related to dimension of layers?

The attachment contains the tflite model I tested on Arm NN.
[TF2_tflite_test.tar.gz](https://github.com/ARM-software/armnn/files/8230279/TF2_tflite_test.tar.gz)

Best Regards,
Rahn

**Comment by TeresaARM** [comment]
Hi @Rahn80643 

When a dimension is unspecified or unknown (usually it is the batch size), we need to infer the size across the whole model. 
We have to "modes": ValidateOnly(the one by default) and InferOutputShape.

could you try adding to you command when calling Arm NN `--infer-output-shape`  ?

Thank you
Kind regards

**Comment by Rahn80643** [comment]
Hi @TeresaARM 

Thank you for providing the issue thread, I can execute the command successfully with `--infer-output-shape` and the inference code could be executed successfully when setting `m_InferAndValidate = true;` as well.
Thank you!

Best Regards,
Rahn

**Comment by TeresaARM** [comment]
Hi @Rahn80643 

glad to here your model is working now!
