### ISSUE TITLE
error compilation for tensorflow

### ISSUE THREAD

**Issue by dimitryn** [ARM-software/armnn#62]
Compilation : on Ubunutu 16.0 
Target : android arm64-va

I follow stages from : https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow/single-page

after calling make inside armnn/build directory :

[ 55%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/NeonWorkloads/NeonSoftmaxFloat32Workload.cpp.o
[ 56%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/NeonWorkloads/NeonSoftmaxUint8Workload.cpp.o
[ 56%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/NeonWorkloads/NeonSplitterFloat32Workload.cpp.o
[ 57%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/NeonWorkloads/NeonSplitterUint8Workload.cpp.o
[ 57%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/NeonWorkloadUtils.cpp.o
[ 58%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/ArmComputeTensorUtils.cpp.o
[ 58%] Linking CXX shared library libarmnn.so
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a(TensorInfo.o): Relocations in generic ELF (EM: 183)
/home/dnozik/Code/arm/ComputeLibrary/build/libarm_compute_core-static.a: error adding symbols: File in wrong format
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/armnn.dir/build.make:1906: recipe for target 'libarmnn.so' failed
make[2]: *** [libarmnn.so] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/armnn.dir/all' failed
make[1]: *** [CMakeFiles/armnn.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Thanks for help..

**Comment by dimitryn** [comment]
@Surmeh Hi  I build all parts (computer library , protobuf, boost ) from your documentation for  arm-v8a . how do I change last cmake command for arm nn to generate build for arm-v8a , thanks

**Comment by dimitryn** [comment]
Hi  @Surmeh  , I follow instruction from cross build guide , it failed for me on CompiteLibrary compilation.

aarch64-linux-gnu-g++ -o build/src/core/NEON/kernels/NEFillBorderKernel.o -c -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=gnu++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -Wno-implicit-fallthrough -march=armv8-a -Werror -O3 -ftree-vectorize -fPIC -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_AARCH64_V8A -DNO_DOT_IN_TOOLCHAIN -Iinclude -I. -Ibuild/build/src/core -Ibuild/src/core -Ibuild/arm_compute/core/NEON/kernels/winograd -Iarm_compute/core/NEON/kernels/winograd -Ibuild/arm_compute/core/NEON/kernels/assembly -Iarm_compute/core/NEON/kernels/assembly src/core/NEON/kernels/NEFillBorderKernel.cpp
src/core/NEON/kernels/NEDirectConvolutionLayerKernel.cpp: In instantiation of ‘{anonymous}::convolver_nhwc<T1>::convolve(const arm_compute::Window&, int, unsigned int, const arm_compute::ITensor*, const arm_compute::ITensor*, arm_compute::ITensor*, const arm_compute::PadStrideInfo&)::<lambda(const arm_compute::Coordinates&)>::<lambda(const arm_compute::Coordinates&)> [with T1 = float]’:
src/core/NEON/kernels/NEDirectConvolutionLayerKernel.cpp:593:61:   required from ‘struct {anonymous}::convolver_nhwc<T1>::convolve(const arm_compute::Window&, int, unsigned int, const arm_compute::ITensor*, const arm_compute::ITensor*, arm_compute::ITensor*, const arm_compute::PadStrideInfo&)::<lambda(const arm_compute::Coordinates&)> [with T1 = float]::<lambda(const class arm_compute::Coordinates&)>’
src/core/NEON/kernels/NEDirectConvolutionLayerKernel.cpp:566:32:   required from ‘{anonymous}::convolver_nhwc<T1>::convolve(const arm_compute::Window&, int, unsigned int, const arm_compute::ITensor*, const arm_compute::ITensor*, arm_compute::ITensor*, const arm_compute::PadStrideInfo&)::<lambda(const arm_compute::Coordinates&)> [with T1 = float]’
src/core/NEON/kernels/NEDirectConvolutionLayerKernel.cpp:593:61:   required from ‘struct {anonymous}::convolver_nhwc<T1>::convolve(const arm_compute::Window&, int, unsigned int, const arm_compute::ITensor*, const arm_compute::ITensor*, arm_compute::ITensor*, const arm_compute::PadStrideInfo&) [with T1 = float]::<lambda(const class arm_compute::Coordinates&)>’
src/core/NEON/kernels/NEDirectConvolutionLayerKernel.cpp:564:28:   required from ‘static void {anonymous}::convolver_nhwc<T1>::convolve(const arm_compute::Window&, int, unsigned int, const arm_compute::ITensor*, const arm_compute::ITensor*, arm_compute::ITensor*, const arm_compute::PadStrideInfo&) [with T1 = float]’
src/core/NEON/kernels/NEDirectConvolutionLayerKernel.cpp:1284:40:   required from here
src/core/NEON/kernels/NEDirectConvolutionLayerKernel.cpp:606:50: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                             out_val += out_values[0];

**Comment by Surmeh** [comment]
Hi @dimitryn,

I saw you closed this issue. Were you able to compile Compute Library and move forward?

**Comment by dimitryn** [comment]
Hi @Surmeh  I fully success to build arm nn for tensorflow with cross compile guide, thanks for help.
 now I trying to build arm nn for tensorflow with BuildGuideAndroidNDK.md . I am currently failing on last stage 

In file included from /home/Code/arm/armnn/src/armnnUtils/../armnn/Half.hpp:9:0,
                 from /home/Code/arm/armnn/src/armnnUtils/FloatingPointConverter.cpp:7:
/home/Code/arm/armnn/third-party/half/half.hpp: In static member function 'static half_float::detail::expr half_float::detail::functions::remainder(float, float)':
/home/Code/arm/armnn/third-party/half/half.hpp:1263:17: error: 'remainder' is not a member of 'std'
     return expr(std::remainder(x, y));

I use NDK 17.

**Comment by Surmeh** [comment]
Hi @dimitryn, that's good to know. Could you please open another ticket for the issue as the original issues has been resolved.

**Comment by Niuxiaotong** [comment]
meet similar with erro ,when build armNN,as follow :
... 
[75%] Linking CXX shared library libarmnn.so
/usr/bin/ld: /home/***/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/xiaotong.niu/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/xiaotong.niu/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/xiaotong.niu/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: /home/xiaotong.niu/delegate/ComputeLibrary/build/libarm_compute_core-static.a(Error.o): Relocations in generic ELF (EM: 183)
/home/xiaotong.niu/delegate/ComputeLibrary/build/libarm_compute_core-static.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/armnn.dir/build.make:2394: recipe for target 'libarmnn.so.24.0' failed
make[2]: *** [libarmnn.so.24.0] Error 1
CMakeFiles/Makefile2:464: recipe for target 'CMakeFiles/armnn.dir/all' failed
make[1]: *** [CMakeFiles/armnn.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

@dimitryn .how to slove similar problem before, thanks.
