### ISSUE TITLE
bash: ./UnitTests: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by aravind329** [ARM-software/armnn#621]
we had tried on different ubuntu platforms but we had encountered same error can someone please help me with this

**Comment by morgolock** [comment]
Hi @aravind329 

Could you please share the output of the command:
`file ./UnitTests`

**Comment by aravind329** [comment]
![Screenshot (1270)](https://user-images.githubusercontent.com/73662879/158334869-72075ae3-91ba-4ec4-a3b0-936cf73dca12.png)

**Comment by aravind329** [comment]
![Screenshot (1270)_LI](https://user-images.githubusercontent.com/73662879/158335201-29895671-8924-4d6a-a32d-ba5c80a2a16a.jpg)

**Comment by MikeJKelly** [comment]
Hi @aravind329 

Exec format error probably means that the binary was compiled for an architecture other than the one being run on. Have you compiled for arm64 and try to run on x86, for example?

If you run `file ./UnitTests` like Pablo suggested it will tell you what the architecture the unit tests were compiled for, for example, if it's compiled for an arm64 machine it will look like this:

`./UnitTests: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, with debug_info, not stripped
`
That will not run on an x86 machine.

**Comment by MikeJKelly** [comment]
Hi @aravind329 

we have a cross-compilation guide at https://github.com/ARM-software/armnn/blob/branches/armnn_22_02/BuildGuideCrossCompilation.md which explains how to build aarch64 binaries using x86. 

In order to run that code you will need a device with an Arm CPU to run that, what kind of hardware do you have with Arm CPUs?

**Comment by aravind329** [comment]
Hi @MikeJKelly 
We are using amd64 cpu for this crossbuild and also we followed the document which we found in your repo
and can you please help us where to find an arm cpu we are searching them but we can't able to find them.
it will be very helpful for our research.

**Comment by aravind329** [comment]
Hi @MikeJKelly 
Thank You For Your support we had successfully build our arm unittests and we run them on arm6 cpu.
we had added some small operations and can you please help us with squeeze operation we are confused over this operation can you share an support document so which we can go forward in our research
Thank You

**Comment by TeresaARM** [comment]
Hi @aravind329 

Squeeze is a known operation, present in most known frameworks:

- https://www.tensorflow.org/api_docs/python/tf/squeeze
- https://pytorch.org/docs/stable/generated/torch.squeeze.html

It is a specific case of reshape, so we parse it to the reshape layer in Arm NN.

Regards

**Comment by aravind329** [comment]
Thanks, I'll check it out.

**Comment by TeresaARM** [comment]
Thank you for your questions! I will close the ticket as the issue is solved now.
Please do not hesitate to contact us again!
Kindest Regards

**Comment by aravind329** [comment]
Thanks a lot.  For giving so much time and support.
