### ISSUE TITLE
ARMNN v21.05: Checking intermediate output at various hidden layer

### ISSUE THREAD

**Issue by supratimc239** [ARM-software/armnn#628]
Hi,

While executing my model, I am seeing some differences between prediction from Python and armnn. In order to debug this, I was planning to compare intermediate ouput at various hidden layers (I mean after various ops).

Could you please tell me how I can dump intermediate output at various ops level (for example my model consists of multiple conv2D and I want to dump output for each of the conv2D module)?

Kind regards
Supratim

**Comment by morgolock** [comment]
HI @supratimc239 

You can dump intermediate layers with the `-p` option
`root@acl_hikey_1:~/tmp/pabtel01/armnn# LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH  ./ExecuteNetwork -f tflite-binary -m mobilenet_v2_1.0_224_quant.tflite -i input -o output -c CpuAcc -p`

Hope this helps

**Comment by supratimc239** [comment]
Hi @morgolock ,

I upgraded my ACL and ARM-NN to v22.02, but the ARM-NN build is failing. Could you please have a look at my latest comment in https://github.com/ARM-software/armnn/issues/607 and see why the ARM-NN build is failing.

Once I can execute my model on v22.02 will start checking your instruction on dumping intermediate layers.

Thanks

**Comment by MikeJKelly** [comment]
Hi 
I think this issue has been resolved and the linked ticket #607 has been closed so I'm going to close it now, if you need any more help with this issue then please open a new issue, thanks! 

Best regards,
Mike
