### ISSUE TITLE
Do you have any plan to support latest boost library?

### ISSUE THREAD

**Issue by daeinki** [ARM-software/armnn#63]
Hi,

Seems current ARMNN library supports only boost v1.64.0 so fixed boost version makes it hard to deploy ARMNN to Linux platform because some platforms may use different version of boost library.

It would be glad to support at least all versions since v1.64.0.
As for this, do you have any plan?

**Comment by daeinki** [comment]
Hi @MatthewARM thanks for quick response.

When I tried to build armnn with boost v1.65 I see below warning messages,
[   11s] CMake Warning at cmake/modules/FindBoost.cmake:765 (message):
[   11s]   Imported targets not available for Boost version 106501
[   11s] Call Stack (most recent call first):
[   11s]   cmake/modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
[   11s]   cmake/modules/FindBoost.cmake:1471 (_Boost_MISSING_DEPENDENCIES)
[   11s]   cmake/GlobalConfig.cmake:106 (find_package)
[   11s]   CMakeLists.txt:11 (include)
[   11s] 
[   11s] 
[   11s] CMake Warning at cmake/modules/FindBoost.cmake:765 (message):
[   11s]   Imported targets not available for Boost version 106501
[   11s] Call Stack (most recent call first):
[   11s]   cmake/modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
[   11s]   cmake/modules/FindBoost.cmake:1471 (_Boost_MISSING_DEPENDENCIES)
[   11s]   cmake/GlobalConfig.cmake:106 (find_package)
[   11s]   CMakeLists.txt:11 (include)
[   11s] 
[   11s] 
[   11s] CMake Warning at cmake/modules/FindBoost.cmake:765 (message):
[   11s]   Imported targets not available for Boost version 106501
[   11s] Call Stack (most recent call first):
[   11s]   cmake/modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
[   11s]   cmake/modules/FindBoost.cmake:1471 (_Boost_MISSING_DEPENDENCIES)
[   11s]   cmake/GlobalConfig.cmake:106 (find_package)
[   11s]   CMakeLists.txt:11 (include)
[   11s] 
[   11s] 
[   11s] CMake Warning at cmake/modules/FindBoost.cmake:765 (message):
[   11s]   Imported targets not available for Boost version 106501
[   11s] Call Stack (most recent call first):
[   11s]   cmake/modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
[   11s]   cmake/modules/FindBoost.cmake:1471 (_Boost_MISSING_DEPENDENCIES)
[   11s]   cmake/GlobalConfig.cmake:106 (find_package)
[   11s]   CMakeLists.txt:11 (include)
[   11s] 
[   11s] 
[   11s] CMake Warning at cmake/modules/FindBoost.cmake:765 (message):
[   11s]   Imported targets not available for Boost version 106501
[   11s] Call Stack (most recent call first):
[   11s]   cmake/modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
[   11s]   cmake/modules/FindBoost.cmake:1471 (_Boost_MISSING_DEPENDENCIES)
[   11s]   cmake/GlobalConfig.cmake:106 (find_package)
[   11s]   CMakeLists.txt:11 (include)
[   11s] 
[   11s] 
[   11s] -- Boost version: 1.65.1
[   11s] -- Found the following Boost libraries:
[   11s] --   unit_test_framework
[   11s] --   system
[   11s] --   filesystem
[   11s] --   log
[   11s] --   program_options

And then linking error,
[  656s] [ 99%] Building CXX object CMakeFiles/UnitTests.dir/src/armnnCaffeParser/test/TestSplit.cpp.o
[  661s] [100%] Linking CXX executable UnitTests
[  662s] /usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/../../../../armv7l-tizen-linux-gnueabi/bin/ld: libarmnnUtils.a(Logging.cpp.o): undefined reference to symbol '_ZN5boost6detail12get_tss_dataEPKv'
[  662s] //lib/libboost_thread.so.1.65.1: error adding symbols: DSO missing from command line
[  662s] collect2: error: ld returned 1 exit status

With boost 1.64, it was no problem. Could you guide me?

Thanks,
Inki Dae

**Comment by daeinki** [comment]
Hi @MatthewARM,

I resoved the linking error by modifying required boost version like below,
diff --git a/cmake/modules/FindBoost.cmake b/cmake/modules/FindBoost.cmake
index cf08f9b..29a5705 100644
--- a/cmake/modules/FindBoost.cmake
+++ b/cmake/modules/FindBoost.cmake
@@ -745,7 +745,7 @@ function(_Boost_COMPONENT_DEPENDENCIES component _ret)
     set(_Boost_THREAD_DEPENDENCIES chrono system date_time atomic)
     set(_Boost_WAVE_DEPENDENCIES filesystem system serialization thread chrono date_time atomic)
     set(_Boost_WSERIALIZATION_DEPENDENCIES serialization)
-  elseif(NOT Boost_VERSION VERSION_LESS 106300 AND Boost_VERSION VERSION_LESS 106500)
+  elseif(NOT Boost_VERSION VERSION_LESS 106300 AND Boost_VERSION VERSION_LESS 106600)

Thanks,
Inki Dae

**Comment by MatthewARM** [comment]
Thanks @daeinki, looks like we should update our version of FindBoost.cmake. I'll note this down to follow up internally.
