### ISSUE TITLE
ssd_mobilenet_v3 stuck in IRuntime::EnqueueWorkload

### ISSUE THREAD

**Issue by steven9046** [ARM-software/armnn#632]
I'm using this [ssd_mobilenet_v3_small_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_small_coco_2020_01_14.tar.gz). It runs well on my computer. But will stuck in IRuntime::EnqueueWorkload when I run it on RK3399 with ubuntu 16.04 installed. I'm using armnnv21.08 because the newer version can't be built on ubuntu16.04. No error code. Just can't return.  Any suggestion?

**Comment by steven9046** [comment]
The model can be found here:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md

**Comment by steven9046** [comment]
This model runs well at first. Then suddenly stuck in IRuntime::EnqueueWorkload after mybe 5min or 30min randomly.

**Comment by james-conroy-arm** [comment]
Hi @steven9046 ,

Whilst we don't officially support Ubuntu 16.04 anymore, Arm NN should still work on this platform. Could you please build with the latest version of Arm NN (22.02) and see if the behaviour is any different?

Cheers,
James
