### ISSUE TITLE
Pooling2dLayer: TensorShape set on OutputSlot[0] does not match the inferred shape

### ISSUE THREAD

**Issue by Shelton-N** [ARM-software/armnn#641]
**1.env:**
armnn21.02
tensorflow:2.3.1
model:mobilenet_v1_1.0_224_frozen.pb
model:NHWC, batch,224,224,3

**2.When  inference tensorflw model on armnn,LayerValidationException Happend**

load network pass
terminate called after throwing an instance of 'armnn::LayerValidationException'
  **what():  Pooling2dLayer: TensorShape set on OutputSlot[0] does not match the inferred shape. : [4,2147483648,1,1024] != [4,2147483649,1,1024]**
Aborted (core dumped)

**Comment by MikeJKelly** [comment]
Hi @Shelton-N 

There seems to be something wrong with your model: [4,**2147483648**,1,1024] != [4,**2147483649**,1,1024] 

That second dimension is far too large for a TF Mobilenet model but the assertion is correct as 2147483648 is not equal to 2147483649.

The output of that Pooling2D would require 8192 **GB** of memory. 

Support for TensorFlow was dropped in 21.02 I'd recommend converting the model to TFLite and using a more up to date version of ArmNN.

Best regards,
Mike

**Comment by Shelton-N** [comment]
> Hi @Shelton-N
> 
> There seems to be something wrong with your model: [4,**2147483648**,1,1024] != [4,**2147483649**,1,1024]
> 
> That second dimension is far too large for a TF Mobilenet model but the assertion is correct as 2147483648 is not equal to 2147483649.
> 
> The output of that Pooling2D would require 8192 **GB** of memory.
> 
> Support for TensorFlow was dropped in 21.02 I'd recommend converting the model to TFLite and using a more up to date version of ArmNN.
> 
> Best regards, Mike

@MikeJKelly
OK，I use armnn22.02 to deploy TFLite model ，everything is right。
