### ISSUE TITLE
Squeezenet Test code not working.

### ISSUE THREAD

**Issue by getsumit123** [ARM-software/armnn#65]
While testing Squeezenet 1.0 in examples, we are getting the error that 4D shape is not supported by softmax layer. only 2D layer is supported. Any plan to support 4D tensor shape or any work-around for this to test squeezenet model.

**Comment by MatthewARM** [comment]
Hi @getsumit123 we'll see what we can do. Which parser are you using?

**Comment by MatthewARM** [comment]
And is your priority for GPU or NEON?

**Comment by getsumit123** [comment]
i am using Caffe with gpu.

**Comment by MatthewARM** [comment]
Thanks, we'll see whether we can add this to our next release.

**Comment by MatthewARM** [comment]
We've improved support for 4D softmax towards the next release. We haven't yet re-tested Squeezenet to see if that was the only problem.
