### ISSUE TITLE
ArmNN TFLite Delegate produces different output with CpuRef on x86_64 linux desktop

### ISSUE THREAD

**Issue by MrSherish** [ARM-software/armnn#656]
Hey,

As per my usecase:
- I'm running ArmNN 22.05 built from scratch
- TFLite 2.7 (C API, not C++ - but delegates leveraging C++ can be used)
- x86_64 linux desktop (CpuRef) for the sake of initial implementation before moving to ARM-based platform

I have a running reference code with models in TFLite C library. For the past few days I was tinkering with ArmNN to offload most (if not all) operations to ArmNN Delegate. Finally after much work and reading source code (as documentation isn't helpful), I managed to run inference with one of the models running with delegate (without some operators, but some minor ones - there is a fallback to TFLite afaik in these cases). I had to use `AllowExpandedDims` option aswell for it to work.

**The problem is:** the produced output from the network is completely different and gibberish than the one in pure TFLite, rendering model unusable under ArmNN - at most I would expect some accuracy differences.
If you do not know what the solution might be, what can I do to track down the rootcause? Some debugging tips? I also wonder if running under ARM would work.

I cannot share a model and I do not have a minimal example right now.
Unsupported ops are (if it is helpful anyhow, but I guess it doesn't matter in that case):
```
ERROR: Operator STRIDED_SLICE [45] is not supported by armnn_delegate.
ERROR: Operator SIN [66] is not supported by armnn_delegate.
ERROR: Operator LOG [73] is not supported by armnn_delegate.
ERROR: Operator SQUARED_DIFFERENCE [99] is not supported by armnn_delegate.
ERROR: Operator COS [108] is not supported by armnn_delegate.
```

Code snippet which I use to add ArmNN delegate:
```
std::cout << "Initializing ArmNN\n";

std::vector<armnn::BackendId> backends;
backends.push_back("CpuRef");  // ARM magic not available on x86_64 desktop

// https://github.com/ARM-software/armnn/issues/653#issuecomment-1156832113
armnn::BackendOptions allow_expanded_dims("AllowExpandedDims",
                                          {{"AllowExpandedDims", true}});

std::vector<armnn::BackendOptions> backend_options{allow_expanded_dims};
armnn::OptimizerOptions optimizer_options;
optimizer_options.m_ModelOptions.push_back(allow_expanded_dims);
armnnDelegate::DelegateOptions armnn_options(backends, optimizer_options);

auto armnn_delegate = armnnDelegate::TfLiteArmnnDelegateCreate(armnn_options));
TfLiteInterpreterOptionsAddDelegate(options, armnn_delegate);
```

**Comment by MikeJKelly** [comment]
Hi @MrSherish 

These errors seemed to be related to the TFLite version I see them in 2.7 but not in version 2.5 which is the version we test with. I'll see if I can find out the defect but if you can switch to 2.5 it might solve your issues? 

Best regards,
Mike

**Comment by MrSherish** [comment]
I'll check at the beginning of next week if:
- the issue persists with 2.7 and CpuAcc on ARM
- switching to 2.5 indeed solves it for my model

I would like to stay on 2.7 anyway, because of availability of signature API since that version.
https://www.tensorflow.org/lite/guide/signatures

I think that in the end the issue should be fixed regardless. Tensorflow itself is already at version 2.9.

**Comment by MrSherish** [comment]
Interesting: using still TFLite 2.7, CpuAcc on armv7 Android gets confused about StridedSlice:

```
ERROR: Operator SIN [66] is not supported by armnn_delegate.
ERROR: Operator LOG [73] is not supported by armnn_delegate.
ERROR: Operator SQUARED_DIFFERENCE [99] is not supported by armnn_delegate.
ERROR: Operator COS [108] is not supported by armnn_delegate.
INFO: Replacing 121 node(s) with delegate (TfLiteArmNnDelegate) node, yielding 19 partitions.
terminating with uncaught exception of type armnn::Exception: TfLiteArmnnDelegate: Exception (TfLiteArmnnDelegate: Network could not be loaded:An error occurred when preparing the network workloads:  StridedSliceQueueDescriptor:  Tensor type is not supported.) caught from LoadNetwork.
/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type armnn::Exception: TfLiteArmnnDelegate: Exception (TfLiteArmnnDelegate: Network could not be loaded:An error occurred when preparing the network workloads:  StridedSliceQueueDescriptor:  Tensor type is not supported.) caught from LoadNetwork." failed
```

Above didn't happen on desktop with CpuRef:
```
ERROR: Operator STRIDED_SLICE [45] is not supported by armnn_delegate.
```

**Comment by MrSherish** [comment]
> Interesting: using still TFLite 2.7, armv7 Android, CpuAcc gets confused about StridedSlice:

I moved it to https://github.com/ARM-software/armnn/issues/663
