### ISSUE TITLE
Failed to compile with BuildGuideAndroidNDK.md on Ubuntu 16.0 NDK 17

### ISSUE THREAD

**Issue by dimitryn** [ARM-software/armnn#66]
Hi ,
I followed BuildGuideAndroidNDK.md to build arm nn with Tensorflow enabled .
Build failed in last stage , building arm nn.
Error1:
/home/dnozik/Code/arm/armnn/include/armnn/TypesUtils.hpp: In function 'constexpr const char* armnn::GetStatusAsCString(armnn::Status)':
/home/dnozik/Code/arm/armnn/include/armnn/TypesUtils.hpp:26:1: error: body of constexpr function 'constexpr const char* armnn::GetStatusAsCString(armnn::Status)' not a return-statement
 }
 ^
/home/dnozik/Code/arm/armnn/include/armnn/TypesUtils.hpp: In function 'constexpr const char* armnn::GetComputeDeviceAsCString(armnn::Compute)':
/home/dnozik/Code/arm/armnn/include/armnn/TypesUtils.hpp:37:1: error: body of constexpr function 'constexpr const char* armnn::GetComputeDeviceAsCString(armnn::Compute)' not a return-statement
 }
 ^

If I remove constexpr from TypeUtils.hpp it pass, but I get another error.
Error 2.

[  2%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/LeakChecking.cpp.o
[  2%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/CsvReader.cpp.o
[  3%] Building CXX object CMakeFiles/armnnUtils.dir/src/armnnUtils/FloatingPointConverter.cpp.o
In file included from /home/dnozik/Code/arm/armnn/src/armnnUtils/../armnn/Half.hpp:9:0,
                 from /home/dnozik/Code/arm/armnn/src/armnnUtils/FloatingPointConverter.cpp:7:
/home/dnozik/Code/arm/armnn/third-party/half/half.hpp: In static member function 'static half_float::detail::expr half_float::detail::functions::remainder(float, float)':
/home/dnozik/Code/arm/armnn/third-party/half/half.hpp:1263:17: error: 'remainder' is not a member of 'std'
     return expr(std::remainder(x, y));

OS : ubuntu 16
NDK - 17,
cmake command:
CXX=aarch64-linux-android-clang++ \
 CC=aarch64-linux-android-clang \
 CXX_FLAGS="-fPIE -fPIC" \
cmake .. \
-DCMAKE_ANDROID_NDK=/home/Code/android-ndk-r17b \
-DCMAKE_SYSTEM_NAME=Android \
-DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
-DARMCOMPUTE_ROOT=$/home/Code/arm/ComputeLibrary \
-DARMCOMPUTE_BUILD_DIR=/home/Code/arm/ComputeLibrary/build/ \
-DARMCOMPUTE_INCLUDE=/home/Code/arm/ComputeLibrary/ \
-DBOOST_ROOT=/home/Code/arm/boost-android/ \
-DARMCOMPUTENEON=1 -DARMCOMPUTECL=0 \
-DTF_GENERATED_SOURCES=/home/Code/arm/protobuf_install/arm64/ \
-DBUILD_TF_PARSER=1 \
-DPROTOBUF_ROOT=/home/Code/arm/protobuf_install/arm64/ \
-DPROTOBUF_LIBRARY_DEBUG=/home/Code/arm/protobuf_install/arm64/lib/libprotobuf.so.15.0.1 \
-DPROTOBUF_LIBRARY_RELEASE=/home/Code/arm/protobuf_install/arm64/libprotobuf.so.15.0.1 \
-DHALF_INCLUDE=/home/Code/arm/armnn/third-party/

Thanks for help.

**Comment by TelmoARM** [comment]
Hi @dimitryn,

Thanks for getting in touch. I'll look into it and report back soon.

Telmo

**Comment by TelmoARM** [comment]
Hi @dimitryn,

I was able to run through the guide successfully using:
OS : ubuntu 16.04
NDK - r16b

I will also try with the r17c version but we currently only test it with the AndroidNDK r16b. 
I'll let you know the result soon.

Telmo

**Comment by TelmoARM** [comment]
Hi @dimitryn ,

I was also able to build ArmNN successfully with NDK-r17c.

You are setting the CMAKE_ANDROID_NDK variable but it is not being used in the project. I got the following warning when I used your Cmake instructions:
```
- CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_ANDROID_NDK
```

I would suggest:
- Delete your ArmNN build folder completely.
- Update your NDK to a known working version, NDK-r17c or NDK-r16b and rebuild the toolchain for the chosen NDK.
- Rebuild the remaining components mentioned in the guide.

Let us know if that works for you.

Thanks,
Telmo

**Comment by dimitryn** [comment]
I did exactly what you sad @TelmoARM  with NDK 16b 
last stage:
CXX=aarch64-linux-android-clang++ \
 CC=aarch64-linux-android-clang \
 CXX_FLAGS="-fPIE -fPIC" \
 cmake .. \
  -DCMAKE_SYSTEM_NAME=Android \
  -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
  -DARMCOMPUTE_ROOT=/home/Code/arm/ComputeLibrary/ \
  -DARMCOMPUTE_BUILD_DIR=/home/Code/arm/ComputeLibrary/build \
  -DBOOST_ROOT=/home/dnozik/Code/arm/boost-android/ \
  -DARMCOMPUTENEON=1 \
  -DTF_GENERATED_SOURCES=/home/Code/arm/protobuf_install/x86/tf_pb/ -DBUILD_TF_PARSER=1 \
  -DPROTOBUF_ROOT=/home/Code/arm/protobuf_install/arm64/


result
CXX=aarch64-linux-android-clang++ \
>  CC=aarch64-linux-android-clang \
>  CXX_FLAGS="-fPIE -fPIC" \
>  cmake .. \
>   -DCMAKE_SYSTEM_NAME=Android \
>   -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" \
>   -DARMCOMPUTE_ROOT=/home//Code/arm/ComputeLibrary/ \
>   -DARMCOMPUTE_BUILD_DIR=/home//Code/arm/ComputeLibrary/build \
>   -DBOOST_ROOT=/home//Code/arm/boost-android/ \
>   -DARMCOMPUTENEON=1 \
>   -DTF_GENERATED_SOURCES=/home//Code/arm/protobuf_install/x86/tf_pb/ -DBUILD_TF_PARSER=1 \
>   -DPROTOBUF_ROOT=/home//Code/arm/protobuf_install/arm64/
-- The C compiler identification is Clang 5.0.300080
-- The CXX compiler identification is Clang 5.0.300080
-- Check for working C compiler: /home//Code/arm/toolchains/aarch64-android-r16b/bin/clang
-- Check for working C compiler: /home//Code/arm/toolchains/aarch64-android-r16b/bin/clang -- broken
CMake Error at /usr/local/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/home//Code/arm/toolchains/aarch64-android-r16b/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home//Code/arm/armnn/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/home//Code/arm/toolchains/aarch64-android-r16b/bin/make" "cmTC_45e54/fast"
    /home//Code/arm/toolchains/aarch64-android-r16b/bin/make -f CMakeFiles/cmTC_45e54.dir/build.make CMakeFiles/cmTC_45e54.dir/build
    make[1]: Entering directory `/home//Code/arm/armnn/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_45e54.dir/testCCompiler.c.o
    /home//Code/arm/toolchains/aarch64-android-r16b/bin/clang --target=armv5te-none-linux-androideabi --gcc-toolchain=/home//Code/arm/toolchains/aarch64-android-r16b --sysroot=/home//Code/arm/toolchains/aarch64-android-r16b/sysroot   -march=armv5te -mthumb -msoft-float -mtune=xscale -funwind-tables -no-canonical-prefixes  -g -fPIE   -o CMakeFiles/cmTC_45e54.dir/testCCompiler.c.o   -c /home//Code/arm/armnn/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_45e54
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_45e54.dir/link.txt --verbose=1
    /home//Code/arm/toolchains/aarch64-android-r16b/bin/clang --target=armv5te-none-linux-androideabi --gcc-toolchain=/home//Code/arm/toolchains/aarch64-android-r16b --sysroot=/home//Code/arm/toolchains/aarch64-android-r16b/sysroot -march=armv5te -mthumb -msoft-float -mtune=xscale -funwind-tables -no-canonical-prefixes  -g  -fPIE -pie -Wl,--gc-sections -Wl,-z,nocopyreloc  CMakeFiles/cmTC_45e54.dir/testCCompiler.c.o  -o cmTC_45e54 
    /usr/bin/ld: unrecognised emulation mode: armelf_linux_eabi
    Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
    clang50: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_45e54] Error 1
    make[1]: Leaving directory `/home//Code/arm/armnn/build/CMakeFiles/CMakeTmp'
    make: *** [cmTC_45e54/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/home//Code/arm/armnn/build/CMakeFiles/CMakeOutput.log".
See also "/home//Code/arm/armnn/build/CMakeFiles/CMakeError.log".

**Comment by MatthewARM** [comment]
Strange - it is trying to build for armv5te instead of aarch64. 

Is aarch64-linux-android-clang on your PATH?
What happens if you run aarch64-linux-android-clang with no arguments?
What version of CMake do you have?

**Comment by dimitryn** [comment]
dnozik@dnozik-VirtualBox:~/Code/arm/armnn/build$  aarch64-linux-android-clang 
clang50: error: no input files


dnozik@dnozik-VirtualBox:~/Code/arm/armnn/build$ cmake -version
cmake version 3.12.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by MatthewARM** [comment]
Thanks for closing this dimitryn, hope you are able to build OK now.
All the best,
Matthew

**Comment by dimitryn** [comment]
Hi @MatteoArm I success build last state with cmake-gui , don't  know why it work , but it worked , thanks for help.

**Comment by mathpopo** [comment]
@MatthewARM  i also meet this issue
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ CXX=aarch64-linux-android-clang++ CC=aarch64-linux-android-clang CXX_FLAGS="-fPIE -fPIC" cmake ..     -DCMAKE_ANDROID_NDK=$NDK     -DCMAKE_SYSTEM_NAME=Android     -DCMAKE_SYSTEM_VERSION=27     -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a     -DCMAKE_EXE_LINKER_FLAGS="-pie -llog -lz"     -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/     -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build     -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/     -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1 -DARMNNREF=1     -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1     -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/
-- Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain ''
-- The C compiler identification is Clang 8.0.7
-- The CXX compiler identification is Clang 8.0.7
-- Check for working C compiler: /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- broken
CMake Error at /usr/local/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_e23db/fast && /usr/bin/make -f CMakeFiles/cmTC_e23db.dir/build.make CMakeFiles/cmTC_e23db.dir/build
    make[1]: Entering directory '/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_e23db.dir/testCCompiler.c.o
    /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains//prebuilt/linux-x86_64 --sysroot=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/sysroot  -isystem /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/sysroot/usr/include -isystem /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/sysroot/usr/include/aarch64-linux-android  -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=27 -fexceptions  -g -fPIE   -o CMakeFiles/cmTC_e23db.dir/testCCompiler.c.o   -c /home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_e23db
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e23db.dir/link.txt --verbose=1
    /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains//prebuilt/linux-x86_64 --sysroot=/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/platforms/android-27/arch-arm64 -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=27 -fexceptions  -g  -Wl,--gc-sections  CMakeFiles/cmTC_e23db.dir/testCCompiler.c.o  -o cmTC_e23db 
    /usr/bin/ld: unrecognised emulation mode: aarch64linux
    Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_e23db.dir/build.make:86: recipe for target 'cmTC_e23db' failed
    make[1]: *** [cmTC_e23db] Error 1
    make[1]: Leaving directory '/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_e23db/fast' failed
    make: *** [cmTC_e23db/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeOutput.log".
See also "/home/chenxin/armnn-devenv/armnn/build/CMakeFiles/CMakeError.log".
(base) chenxin@Nitro-AN515:~/armnn-devenv/armnn/build$ aarch64-linux-android-clang++
clang++: error: no input files


@dimitryn how do you solve this issue?
