### ISSUE TITLE
Bias support in TransposeConv2d for TFLite Delegate

### ISSUE THREAD

**Issue by MrSherish** [ARM-software/armnn#660]
Hey,

I would like to request support for bias in TransposeConv2d (https://github.com/ARM-software/armnn/blob/branches/armnn_22_05/delegate/src/Convolution.hpp#L563). Currently it is suported for Conv3d or DepthwiseConv2d. I guess the implementation could be the same as in Depthwise variant, but I am not experienced enough with ArmNN or implementing neural network operators to evaluate that.

**Comment by catcor01** [comment]
Hello @MrSherish,

I've added a ticket for adding the operator to our backlog however there is no ETA at the moment when they will be implemented. As we're going to track these internally, I'm going to close this issue but we'll update it if and when support for these operators have been added.

If you would like to help implement these operators then here is a link to our contributors guide which will show you how you can submit a patch to us. If you have any questions then please feel free to create a new Issue, thank you!

https://www.mlplatform.org/contributing

Kind Regards, Cathal.
