### ISSUE TITLE
Problem with multiple input Model using armnn

### ISSUE THREAD

**Issue by Shelton-N** [ARM-software/armnn#665]
I want to deply tflite model with multiple input on ARMNN22.02,
ARMNN whether support multiple input Model  ,how to construct multiple input programne?

**Comment by catcor01** [comment]
Hello @Shelton-N,

ArmNN will support a multiple input tflite model. We recommend using our TFLite Delegate which will parse your tflite model to run using ArmNN. To build the delegate see [here](https://github.com/ARM-software/armnn/blob/branches/armnn_22_02/delegate/BuildGuideNative.md). To run your tflite model with the delegate using Python see [here](https://github.com/ARM-software/armnn/blob/branches/armnn_22_02/delegate/DelegateQuickStartGuide.md). If you have any other requirement or problems, please let me know and am happy to help out.

Kind Regards, Cathal.

**Comment by Shelton-N** [comment]
Hello @catcor01 ,Sucessfully, can use ARMNN to deploy tflite model which multiple input and multiple output .
thanks.
