### ISSUE TITLE
armnnTfParser does not support tf.Variable, so what could be alternative?

### ISSUE THREAD

**Issue by leeanzel** [ARM-software/armnn#67]
Hi, I'm trying to run tensorflow model on cortex-a53 board so trying to use armnn.
But I found tf.Variable method doesn't supported in armnnTfParser.
(from https://github.com/ARM-software/armnn/blob/master/src/armnnTfParser/TensorFlowSupport.md)
I'm not in professional at tensorflow but almost examples that I found are using tf.Variable method.
So my question is these.

* What could be an alternative for tf.Variable in armnn?  And is there any plans for support tf.Variable?
* Or do I have to use another way for armnn works?
   For example, 1. make a graph for training 2. and save parameters after training done. 3.And have to 
   make another graph for armnn?

**Comment by leeanzel** [comment]
This is my self answer.
I missunderstood purpose of ARM_NN and tensorflow model export behavior.
ARM_NN is only for inference.
(https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/improving-your-machine-learning-workflow-using-the-arm-nn-sdk/single-page)
So all models from tensorflow which want to run with ARMNN have to exported as 'freezed_graph'; loading checkpoint and change all Variables to Const.
With this focus, ARM_NN don't need to support Variable, right?
I think now I'm understand  about ARM_NN concept.  But if there is any miss-understand or tips for me please comment me.
Thank you.

**Comment by MatthewARM** [comment]
Hi @leeanzel that is right, ArmNN is only for inference (at least at the moment) so for Tensorflow models you need to freeze it, and probably run some "optimise for mobile inference" steps.

We're gradually increasing our support for Tensorflow models but these steps will likely be required for the foreseeable future.

Good luck with your project and please post back here with any news of success or further problems!

**Comment by TelmoARM** [comment]
Hi @leeanzel,

As per Matthew comment, support for this feature will be added in the future. I'm marking this issue as resolved. Let us know if you have any other issues.

Telmo
