### ISSUE TITLE
Error message while executing inference with NPU

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#674]
Hi,

We adopted two methods to compile our ArmNN inference code, the first method is compiling via Makefile and the other one is via CMakeLists. We logged the execution time from these compiling approaches and compared the results based on the same inference code, test image, and test model, and the logs are shown in the attachment.
[logs.zip](https://github.com/ARM-software/armnn/files/9207442/logs.zip)

However, the execution results contain the following error message:

```
Error: An error occurred attempting to execute a workload: An error has occurred waiting for the inference of a pre-compiled object: Timed out while waiting for the inference to complete
```

Why does the execution of NPU produce the error above? Since it takes time to reset the status of NPU, how to resolve the issue?

Best Regards

**Comment by Shelton-N** [comment]
@Rahn80643 
you mean erro happend due to different builds, can show the Makefile which generated from CMake.

**Comment by MikeJKelly** [comment]
Hi @Rahn80643 

I haven't seen that error message before, from looking at the EthosN code it occurs when the NPU returns a WaitErrorCode::Timeout but I do not know the situations why that might occur. I think you would be better off asking that question on the NPU GitHub:

https://github.com/ARM-software/ethos-n-driver-stack

The engineers there would be better able to answer this one. 

Best regards,
Mike

**Comment by Rahn80643** [comment]
@Shelton-N,

the attachment is the Makefile generated from CMake

Best Regards,
Rahn
[Makefile_from_CMakeLists.txt](https://github.com/ARM-software/armnn/files/9249603/Makefile_from_CMakeLists.txt)

**Comment by FrancisMurtagh-arm** [comment]
Closing as this issue would be best asked on NPU Github: https://github.com/ARM-software/ethos-n-driver-stack

Regards,
Francis.
