### ISSUE TITLE
ERROR: Operator SQUARED_DIFFERENCE is not supported by armnn_delegate.

### ISSUE THREAD

**Issue by luchangli03** [ARM-software/armnn#677]
ERROR: Operator SQUARED_DIFFERENCE is not supported by armnn_delegate.

**Comment by ArmRyan** [comment]
Hi @luchangli03 

Can you provide any more details on the issue?
Such as:
ArmNN Version,
ACL version,
TfLite version,
System OS,
what device is being used,
Model information ( can you link the model? )
How are you running the delegate?

Regards,
Ryan

**Comment by keidav01** [comment]
Hi @luchangli03 can you provide more details? 

I will close this on October 10th if I do not hear from you. 

Thank you,
Keith
