### ISSUE TITLE
GATHER: not supported by armnn: in validate_arguments src/core/CL/kernels/CLGatherKernel.cpp:41: indices->num_dimensions() > 1

### ISSUE THREAD

**Issue by luchangli03** [ARM-software/armnn#679]
GATHER: not supported by armnn: in validate_arguments src/core/CL/kernels/CLGatherKernel.cpp:41: indices->num_dimensions() > 1

**Comment by ArmRyan** [comment]
Hi @luchangli03 

Can you provide any more details on the issue?
Such as:
ArmNN Version,
ACL version,
TfLite version,
System OS,
what device is being used,
Model information ( can you link the model? )
How are you running the delegate?

Regards,
Ryan

**Comment by luchangli03** [comment]
> 
ArmNN Version：armnn-22.05.01
TfLite version: 2.15
System OS: android
Model information：I can not directly provide the model, but many transformer based NLP models contain gather op.

**Comment by ArmRyan** [comment]
How many dimensions are trying to get passed in to the indices?

**Comment by keidav01** [comment]
Hey @luchangli03 

Again, I will close this on October 10th if I do not hear from you.

Thank you, 
Keith
