### ISSUE TITLE
ONNX Parser: Not support softmax

### ISSUE THREAD

**Issue by Shelton-N** [ARM-software/armnn#680]
**Sys Info:**
armnn22.02
ubuntu18.04
platform:Arm cortex-A76 + A55

deploy ONNX model with armnn22.02,but ONNX Parser cannot support softmax.
How to deal with the problems?

**Comment by ArmRyan** [comment]
Hi @Shelton-N 

This is an unsupported operator with the ONNX Parser. I have created an internal ticket to add support but I can not give any estimated time on when the ticket will be completed. 

We are an open source project so if you would like to, you are welcome to get involved! Here is a link to our contibutor guide: https://www.mlplatform.org/contributing

There is also some information available on our README: https://github.com/ARM-software/armnn/blob/master/README.md 

Regards,
Ryan

**Comment by FrancisMurtagh-arm** [comment]
Closing issue as we are tracking internally and have marked as Help-Wanted for external contributors to re-open if desired.
