### ISSUE TITLE
Tutorial link - Testing SSD model using TFLite delegate 

### ISSUE THREAD

**Issue by kamalasubha** [ARM-software/armnn#682]
Hi, 
Any tutorial available for testing [ssd model object detection](https://github.com/ARM-software/ML-zoo/tree/master/models/object_detection/ssd_mobilenet_v1/tflite_fp32) (tflite model) using tflite Delegate?

**Comment by ArmRyan** [comment]
Hi @kamalasubha ,

We have this [quick start guide](https://github.com/ARM-software/armnn/blob/branches/armnn_22_05/delegate/DelegateQuickStartGuide.md) or a slightly [more in depth guide](https://developer.arm.com/documentation/102561/2111/Overview-of-running-the-application/Run-the-application). They are both using the python tflite api. Neither of them are specifically for the ssd mobilenet model but can be adapted!

Regards,
Ryan
