### ISSUE TITLE
UnitTest Failed：TensorflowLiteParser

### ISSUE THREAD

**Issue by Shelton-N** [ARM-software/armnn#684]
sysinfo:
platform:anrdoid13
Arm cortex-A76+A55
armnn:22.02

**TensorflowLiteParser DepthwiseConvolution2D. test failed and MaxPool2D Segmentation violation signal.**

`Orid:/data/local/tmp/ut # ./UnitTests --test-suite=TensorflowLiteParser_`
> [doctest] doctest version is "2.4.6"
> [doctest] run with "--help" for options
> ===============================================================================
> /home/armnnsrc/armnnTfLiteParser/test/DepthwiseConvolution2D.cpp:130:
> TEST SUITE: TensorflowLiteParser_DepthwiseConvolution2D
> TEST CASE:  ParseDepthwiseConv2DSame
> 
> /home/armnnsrc/armnnTfLiteParser/test/ParserFlatbuffersFixture.hpp:385: ERROR: CHECK( result.m_Result ) is NOT correct!
>   values: CHECK( false )
>   logged: 4 different values at: [0,0,1,0] (17 != 18), [0,1,0,0] (28 != 29), [0,1,2,0] (55 != 56), ... (and 1 other differences)
> 
> ===============================================================================
> /home/armnnsrc/armnnTfLiteParser/test/DepthwiseConvolution2D.cpp:182:
> TEST SUITE: TensorflowLiteParser_DepthwiseConvolution2D
> TEST CASE:  ParseDepthwiseConv2DSameBias
> 
> /home/armnnsrc/armnnTfLiteParser/test/ParserFlatbuffersFixture.hpp:385: ERROR: CHECK( result.m_Result ) is NOT correct!
>   values: CHECK( false )
>   logged: 4 different values at: [0,0,1,0] (22 != 23), [0,1,0,0] (33 != 34), [0,1,2,0] (60 != 61), ... (and 1 other differences)
> 
> ===============================================================================
> /home/armnnsrc/armnnTfLiteParser/test/DepthwiseConvolution2D.cpp:555:
> TEST SUITE: TensorflowLiteParser_DepthwiseConvolution2D
> TEST CASE:  ParseDepthwiseConv2DFilterWeightsPerChannelQuant4
> 
> /home/armnnsrc/armnnTfLiteParser/test/ParserFlatbuffersFixture.hpp:385: ERROR: CHECK( result.m_Result ) is NOT correct!
>   values: CHECK( false )
>   logged: 9 different values at: [0,0,0,7] (8 != 7), [0,0,1,7] (8 != 7), [0,0,2,7] (8 != 7), ... (and 6 other differences)
> 
> ===============================================================================
> /home/armnnsrc/armnnTfLiteParser/test/DepthwiseConvolution2D.cpp:821:
> TEST SUITE: TensorflowLiteParser_DepthwiseConvolution2D
> TEST CASE:  ParseDepthwiseConv2DFilterWeightsPerChannelQuant4_2
> 
> /home/armnnsrc/armnnTfLiteParser/test/ParserFlatbuffersFixture.hpp:385: ERROR: CHECK( result.m_Result ) is NOT correct!
>   values: CHECK( false )
>   logged: 27 different values at: [0,0,0,3] (7 != 6), [0,0,0,7] (21 != 20), [0,0,0,11] (26 != 25), ... (and 24 other differences)
> 
> ===============================================================================
> /home/armnnsrc/armnnTfLiteParser/test/DepthwiseConvolution2D.cpp:887:
> TEST SUITE: TensorflowLiteParser_DepthwiseConvolution2D
> TEST CASE:  ParseDepthwiseConv2DFilterWeightsPerChannelQuant4_5
> 
> /home/armnnsrc/armnnTfLiteParser/test/ParserFlatbuffersFixture.hpp:385: ERROR: CHECK( result.m_Result ) is NOT correct!
>   values: CHECK( false )
>   logged: 118 different values at: [0,0,0,2] (3 != 4), [0,0,0,4] (9 != 10), [0,0,0,5] (11 != 12), ... (and 115 other differences)
> 
> ===============================================================================
> /home/armnnsrc/armnnTfLiteParser/test/MaxPool2D.cpp:108:
> TEST SUITE: TensorflowLiteParser_MaxPool2D
> TEST CASE:  MaxPoolLiteUint2DOutput
> 
> /home/armnnsrc/armnnTfLiteParser/test/MaxPool2D.cpp:108: FATAL ERROR: test case CRASHED: SIGSEGV - Segmentation violation signal
> 
> ===============================================================================
> [doctest] test cases: 149 | 143 passed | 6 failed | 4806 skipped
> [doctest] assertions: 975 | 970 passed | 5 failed |
> [doctest] Status: FAILURE!
> Segmentation fault (core dumped)

**Comment by ArmRyan** [comment]
Hello @Shelton-N ,

We don't officially support Android 13 yet. The first release that will likely support Android 13 will probably be 22.11.

Can I ask what NDK you are building with?

Thanks,
Ryan

**Comment by Shelton-N** [comment]
@ArmRyan ,
I compiled armnn22.02 with ndk-r20, Just test in Android13.
