### ISSUE TITLE
Performance ArmNN vs ComputeLibrary

### ISSUE THREAD

**Issue by ddenaro** [ARM-software/armnn#69]
Hello,
I have a caffe model for a simple classification task.
I measured the inference time using ComputeLibrary and ArmNN. 
In details:
    Using the ComputeLibrary Graph API the inference time is about **93ms** with NEON and 2-Threads.
    Using ArmNN and the caffe loader the inference time is about **118ms** with armnn::Compute::CpuAcc.
Is It possible that ArmNN optimized network is slower than a simple Graph of ComputeLibrary ?

**Comment by MatthewARM** [comment]
Hi @ddenaro without knowing the exact neural network, it's hard to answer exactly what might be happening here.

In general we expect ArmNN to have almost exactly the same performance as Compute Library when the graphs are identical. In practice, the Caffe parser might not be creating exactly the same graph as your directly-written ComputeLibrary Graph API test.

You can dump the ArmNN graph using "IOptimizedNetwork::SerializeToDot()" after optimizing. This will show you details of precisely how the Caffe parser has interpreted the Caffe file, and should be comparable to your Compute Library code.

**Comment by MatthewARM** [comment]
Also, you can use the ArmNN event-based profiler, see include/armnn/IProfiler.hpp and IRuntime::GetProfiler(), to see exactly where time is being spent.

**Comment by ddenaro** [comment]
Thank you.
