### ISSUE TITLE
Interrupt building without docker and build again will cause error

### ISSUE THREAD

**Issue by huzq85** [ARM-software/armnn#697]
I tried to build ARM-NN in my WSL (Ubuntu) environment without docker. However, when I interrupted the installation script and then executed it again, an error occurred.

**Reproduce Steps:**
1. First I execute the installation script by typing the command: sudo ./install-packages.sh.
2. I interrupted the installation procedure because I wanted to switch the building procedure to the local docker.
3. However, I decided to switch back to the WSL (Ubuntu) again to continue the building.
4. After I executed the script install-packages.sh, the error occurred.
5. The error message said that "E: unable to locate cmake."

**Root Cause**
The root cause is that in my 1st step, the existing CMake had been uninstalled, and then in step 4 the installation script tried to find the existing CMake. The error occurred because it had already been uninstalled.
In this case, I think the install-packages.sh should be updated to continue the installation if the existing CMake had been removed. Otherwise, users maybe confused.

**Comment by james-conroy-arm** [comment]
Hi @huzq85 ,

Many thanks for raising this issue. You have definitely caught an edge case in this script - we are working on a fix now and will update you when it's ready.

Did you end up getting passed this stage with your own modifications already and were you able to build Arm NN successfully?

Thanks,
James

**Comment by james-conroy-arm** [comment]
Great to hear @huzq85 

I haven't been able to reproduce your issue yet. I uninstalled CMake from my system and ran the install-packages.sh script and it proceeded to install CMake 3.19 with no issues.

This if statement in install-packages.sh checks if the correct version of CMake is present:
```
if [[ "$(cmake --version 2> /dev/null | grep "$CMAKE_VERSION" )" == *"$CMAKE_VERSION"* ]]; then
  echo -e "\n***** CMake $CMAKE_VERSION already installed, skipping CMake install *****"
else
  download_cmake
  install_cmake
fi
```
It should return false if CMake is present and not the correct version AND should also return false if CMake is not installed at all (i.e. `cmake --version` returns an error which is captured by /dev/null).

Is there something else I'm missing? Do you know how far the script executed the first time you ran it?

Thanks,
James

**Comment by huzq85** [comment]
hi, @james-conroy-arm ,
Thank you so much for your update! Yes, I think this piece of the script makes sense in install-packages.sh. From this point, you remind me of something when I was trying to build ARM-NN through scripts. I built ARM-NN in several environments, such as in docker and in my local Ubuntu OS. It's very likely that I forgot to run this install-packages.sh except the first time I build ARM-NN. If this is the case, I think this issue can be closed now. And I will keep an eye on whether this issue will appear on my side in the future.

Thank you for your help!

**Comment by james-conroy-arm** [comment]
No bother :)

Do you have any feedback on your experience using the build-tool? e.g. did you prefer using Docker or running scripts directly on your machine etc.

Which target device are you testing on?

Cheers,
James

**Comment by huzq85** [comment]
I think building using Docker is much more convenient than building from scripts, but of course the prerequisite is that users need to install Docker first :) Anyway, I think building from scripts is convenient enough at this stage, especially for users who do not have and do not want to install Docker.

**Comment by james-conroy-arm** [comment]
Thanks for that!

I guess having the choice is what matters :)
