### ISSUE TITLE
Plans to add support for 1D operators?

### ISSUE THREAD

**Issue by avirn** [ARM-software/armnn#705]
I was wondering if there were any plans to add support for CONV_1D and MAX_POOLING_1D? Trying to accelerate a model which uses both operators but I believe it is being slowed down because those operators are not supported causing a shift between the tflite and armnn delegates.

**Comment by Colm-in-Arm** [comment]
Hi,

We currently have no active plans to add 1D operators in the next few months. Would you be interested in contributing the operators yourself? One potential approach is to reshape to 2D and use the existing operator.

Details on how to contribute are here:
https://github.com/ARM-software/armnn/blob/branches/armnn_22_08/CONTRIBUTING.md

Is there a publicly available model containing these operators that I could add to the feature request?

Colm.

**Comment by FrancisMurtagh-arm** [comment]
Hi@avirn,

I've added a ticket our backlog however there is no ETA at the moment when it will be implemented. As we're going to track these internally, I'm going to close this issue but we'll update it if and when support has been added.

Thanks,
Francis.
