### ISSUE TITLE
Provide a `CreateNetworkFromBinary` method for the ONNX parser

### ISSUE THREAD

**Issue by Inlinebool** [ARM-software/armnn#709]
Currently (22.08.01) there is only a `CreateNetworkFromBinaryFile` method for the ONNX parser. For my project, however, I need to read a binary buffer from some external device, and I'm hoping that I could directly create a network from the buffer, instead of first saving it to disk. 

I see that there is a `CreateNetworkFromBinary` method for the TFLite parser. I'm wondering if a similar method will be added to the ONNX parser. Thanks.

**Comment by MikeJKelly** [comment]
Hi @Inlinebool 

thank you for bringing that omission to our intention, I've created a review that adds that function: 

https://review.mlplatform.org/c/ml/armnn/+/8695

It is too late for the 22.11 release but should be there for 23.02 and should merge cleanly into our existing releases. Can you check if it works for your needs and let me know?

Best regards,
Mike

**Comment by FrancisMurtagh-arm** [comment]
Hi @Inlinebool,

The above patch has been merged so I'll close the ticket, please reopen if necessary.

Thanks,
Francis.
