### ISSUE TITLE
Error during Android NDK build

### ISSUE THREAD

**Issue by praisonjoshua** [ARM-software/armnn#71]
![screenshot 8](https://user-images.githubusercontent.com/33496837/46427762-d38f3b00-c75f-11e8-84aa-aa75113ef3c9.png)

**Comment by praisonjoshua** [comment]
C compiler error
gcc version is 
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Comment by MatthewARM** [comment]
Hi @praisonjoshua recently another user had a very similar problem to this:
https://github.com/ARM-software/armnn/issues/66 and after some work the problem stopped happening but we're not sure why.

Would you be able to read that thread to see if there is anything helpful? We're not yet sure why some users are experiencing this problem.

**Comment by TelmoARM** [comment]
Hi @praisonjoshua, 

Might be worth having a look at [68 ](https://github.com/ARM-software/armnn/issues/68) from another user also having trouble building with AndroidNDK and Ubuntu 18.04.

Telmo

**Comment by TelmoARM** [comment]
Hi @praisonjoshua,

Have you been able to resolve this issue?

**Comment by praisonjoshua** [comment]
Sorry sir , I will update you in a day or two.

**Comment by praisonjoshua** [comment]
Sorry for delay,
I dont know what happend but when i  re-did the whole again the error stopped showing up.
