### ISSUE TITLE
Support for pytorch?

### ISSUE THREAD

**Issue by EilersJan** [ARM-software/armnn#713]
Hey guys, are there any news to executing pytorch models with ArmNN?

On pytorch mobile they only mention XNNPack and QNNPack..

**Comment by MikeJKelly** [comment]
Hi @EilersJan 

At the moment we have no plans to support pytorch from within ArmNN. At the moment we are evaluating the use of TinyNeuralNetwork to convert from PyTorch to a TfLite model. Maybe you can give that a go and let us know how it works for you?

https://github.com/alibaba/TinyNeuralNetwork

Best regards,
Mike

**Comment by EilersJan** [comment]
Thanks Mike, was hoping you might be working on a delegate for pytorch mobile
