### ISSUE TITLE
build-armnn.sh doesn't get ACL tag correctly

### ISSUE THREAD

**Issue by alvoron** [ARM-software/armnn#715]
Arm NN branch name parsing is failed since `$armnn_branch` equals `main` but not a version number:
https://github.com/ARM-software/armnn/blob/5446a4d6d02002515fc58fafe33d74ae6dca5787/build-tool/scripts/build-armnn.sh#L182

**Comment by FrancisMurtagh-arm** [comment]
Hi @alvoron,

Thanks for reporting, what architecture are you building on and for?

What is the full command you called resulting in the issue?

Thanks,
Francis.

**Comment by alvoron** [comment]
I'm building on aarch64, RaspberryPi 4 (Ubuntu 22.04).

I used the command from your [README](https://github.com/ARM-software/armnn/tree/main/build-tool#docker-build-steps):

```
docker build \
--build-arg SETUP_ARGS="--target-arch=aarch64 --all" \
--build-arg BUILD_ARGS="--target-arch=aarch64 --all --neon-backend --cl-backend" \
--tag armnn:aarch64 \
--file docker/Dockerfile .
```

**Comment by FrancisMurtagh-arm** [comment]
Hi @alvoron,

Yes the README.md is incorrect unfortunately, it's expecting that the latest tagged version of ArmNN is checked out not main.

Then it tries to checkout Arm Compute Library using the same tag, I'm not sure this assumption would be enough either.

As we had a patch release for our latest release resulting in an ArmNN v22.11.01, this doesn't have a corresponding ACL v22.11.01.

I've added a ticket which we are looking into to fix the logic, in the mean time you could hardcode the versions in build-armnn.sh like so:

```
diff --git a/build-tool/scripts/build-armnn.sh b/build-tool/scripts/build-armnn.sh
index 865b16fad..a27400051 100755
--- a/build-tool/scripts/build-armnn.sh
+++ b/build-tool/scripts/build-armnn.sh
@@ -158,6 +158,7 @@ download_armnn()
   git clone https://github.com/ARM-software/armnn.git armnn
 
   cd "$ARMNN_SRC"
+  git checkout v22.11
   local armnn_branch="$(git rev-parse --abbrev-ref HEAD)"
 
   echo -e "\n***** Arm NN Downloaded: $armnn_branch *****"
@@ -182,7 +183,7 @@ download_acl()
   acl_tag="$(echo "$armnn_branch" | tr '\n' ' ' | sed -e 's/[^0-9]/ /g' -e 's/^ *//g' -e 's/ *$//g' | tr -s ' ' | sed 's/ /./g')"
 
   cd "$ACL_SRC"
-  git checkout v"$acl_tag"
+  git checkout v22.11
 
   echo -e "\n***** ACL Downloaded: $acl_tag *****"
 }
```


Regards,
Francis.

**Comment by FrancisMurtagh-arm** [comment]
Hi @alvoron,

We've reverted a change that was made to configuration of GitHub Repo so that, by default, we clone the latest release branch again.

I've tested the above command and it successfully clones branches/armnn_22_11 and then ACL v22.11.


```
***** Downloading Arm NN *****
Cloning into 'armnn'...

***** Arm NN Downloaded: branches/armnn_22_11 *****

***** Downloading corresponding ACL version using Arm NN branch: branches/armnn_22_11 *****
Cloning into 'acl'...
Note: checking out 'v22.11'.
```

Thanks,
Francis.
