### ISSUE TITLE
How to test TfInceptionV3-Armnn.cpp?

### ISSUE THREAD

**Issue by leeanzel** [ARM-software/armnn#72]
Hi, all.

I'm trying to run tests/TfInceptionV3-Armnn/TfInceptionV3-Armnn.cpp
(https://github.com/ARM-software/armnn/tree/master/tests/TfInceptionV3-Armnn)

To do this I did
1. cloned stb from github(https://github.com/nothings/stb) and added include path and fixed some defines from cmake/GlobalConfig.cmake
(When I included stb library for build, it occured some errors belong -Werror option, so turned off.)
2. Download and read descriptions for InceptionV3 from https://www.tensorflow.org/tutorials/images/image_recognition#usage_with_the_c_api
  -> downloaded **inception_v3_2016_08_28_frozen.pb**
3. Transformed frozen graph refered https://www.tensorflow.org/lite/tfmobile/prepare_models#using_the_graph_transform_tool
But I couldn't which transform options needed so just used same command from example, like this.
```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
	--in_graph=inception_v3_2016_08_28_frozen.pb \
	--out_graph=inception_v3_2016_08_28_frozen_transformed.pb \
	--inputs=input --outputs=InceptionV3/Predictions/Reshape_1 \
--transforms='strip_unused_nodes(type=float, shape="1,299,299,3") fold_constants(ignore_errors=true) fold_batch_norms fold_old_batch_norms'

```
I've got transformed graph(inception_v3_2016_08_28_frozen_transformed.pb) and this is 'summarize_graph' tool's result of that.
```
 TfInceptionV3-Armnn $ $TF_HOME/bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=inception_v3_2016_08_28_frozen_transformed.pb 
Found 1 possible inputs: (name=input, type=float(1), shape=[1,299,299,3]) 
No variables spotted.
Found 1 possible outputs: (name=InceptionV3/Predictions/Reshape_1, op=Reshape) 
Found 23824684 (23.82M) const parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: 231 Const, 95 Conv2D, 94 Add, 94 Relu, 24 Mul, 15 ConcatV2, 10 AvgPool, 4 MaxPool, 2 Reshape, 1 BiasAdd, 1 Identity, 1 Placeholder, 1 Softmax, 1 Squeeze
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=inception_v3_2016_08_28_frozen_transformed.pb --show_flops --input_layer=input --input_layer_type=float --input_layer_shape=1,299,299,3 --output_layer=InceptionV3/Predictions/Reshape_1

```

4. Run with this command line from target and it makes errors
```
# pwd
/root/armnn/tests
# ls
CMakeFiles
ExecuteNetwork
Makefile
TfInceptionV3-Armnn
cmake_install.cmake
data
inception_v3_2016_08_28_frozen_transformed.pb
libinferenceTest.a
#
# ls data/
Cat.jpg
Dog.jpg
grace_hopper.jpg
imagenet_slim_labels.txt
inception_v3_2016_08_28_frozen_transformed.pb
shark.jpg
#
# ./TfInceptionV3-Armnn --data-dir=./data --model-dir=./
ArmNN v20180800

Armnn Error: Input tensor has incorrect size. Expected 268203 elements but got 0.
#
```

This is where I stucked.
I read almost of github history about this and trying googling but couldn't get any solution.
Could anyone tell me how did you run InceptionV3 with armnn?

**Comment by MatthewARM** [comment]
Hi @leeanzel maybe the test data is in an unexpected format?  I get:
<pre>
MatthewARM@workstation:~/gits/devenv/build-x86_64/release/armnn/tests$ ./TfInceptionV3-Armnn --data-dir=../../../../testdata --model-dir=../../../../models
ArmNN v20180800

= Prediction values for test #0
Top(1) prediction is 208 with confidence: 58.8273%
Top(2) prediction is 209 with confidence: 28.6083%
Top(3) prediction is 853 with confidence: 0.600391%
Top(4) prediction is 223 with confidence: 0.537345%
Top(5) prediction is 160 with confidence: 0.180722%
= Prediction values for test #1
Top(1) prediction is 283 with confidence: 48.1306%
Top(2) prediction is 282 with confidence: 31.6746%
Top(3) prediction is 286 with confidence: 10.227%
Top(4) prediction is 288 with confidence: 0.167736%
Top(5) prediction is 284 with confidence: 0.108078%
= Prediction values for test #2
Top(1) prediction is 3 with confidence: 98.6568%
Top(2) prediction is 148 with confidence: 0.0831896%
Top(3) prediction is 234 with confidence: 0.0260615%
Top(4) prediction is 149 with confidence: 0.0158389%
Top(5) prediction is 4 with confidence: 0.0120914%
Total time for 3 test cases: 48.072 seconds
Average time per test case: 16023.922 ms
Overall accuracy: 1.000
MatthewARM@workstation:~/gits/devenv/build-x86_64/release/armnn/tests$ file ../../../../testdata/Cat.jpg
../../../../testdata/Cat.jpg: JPEG image data, baseline, precision 8, 767x1024, frames 3
MatthewARM@workstation:~/gits/devenv/build-x86_64/release/armnn/tests$ file ../../../../testdata/Dog.jpg
../../../../testdata/Dog.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=0], baseline, precision 8, 960x720, frames 3
MatthewARM@workstation:~/gits/devenv/build-x86_64/release/armnn/tests$ file ../../../../testdata/shark.jpg
../../../../testdata/shark.jpg: JPEG image data, JFIF standard 1.02, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=10, description=SHK0120.  great White Shark; Carcharodon cacharias; most famous, orientation=upper-left, xresolution=236, yresolution=244, resolutionunit=2, software=Adobe Photoshop CS Macintosh, datetime=2006:01:02 08:45:34], baseline, precision 8, 1024x685, frames 3
</pre>

**Comment by leeanzel** [comment]
Hi @MatthewARM  and @myth01 
When I failed I used 299x299 sized JPEG file and failed, maybe it makes kind of size align or any other problems,... I don't know anyway
And succeed with other sized image (e.g. 512x512 JPEG).
I think my input image size is not suitable for that.
Thank you for advices :)

Then @MatthewARM,
My progress to run TfInceptionV3-Armnn is right?; transform command and execute command?

**Comment by MatthewARM** [comment]
Hi @leeanzel your transform and execute commands look good to me. Are you still having problems?

**Comment by leeanzel** [comment]
Hi @MatthewARM.
Now I'm fine to run TfInceptionV3-Armnn.  But it makes miss result.
From TfInceptionV3-Armnn.cpp, this source code have to input images for {Dog, Cat, shark} and result label must  {208, 283, 3}.

So I tested with some dog images but it makes result label like this log.
```
= Prediction values for test #0
Top(1) prediction is 163 with confidence: 77.7477%
Top(2) prediction is 168 with confidence: 3.76775%
Top(3) prediction is 167 with confidence: 0.81855%
Top(4) prediction is 165 with confidence: 0.264387%
Top(5) prediction is 429 with confidence: 0.221858%
Prediction for test case 0 (163) is incorrect (should be 208)
= Prediction values for test #1
Top(1) prediction is 283 with confidence: 54.5648%
Top(2) prediction is 286 with confidence: 19.6256%
Top(3) prediction is 282 with confidence: 13.144%
Top(4) prediction is 288 with confidence: 5.86075%
Top(5) prediction is 729 with confidence: 0.73744%
= Prediction values for test #2
Top(1) prediction is 3 with confidence: 82.1478%
Top(2) prediction is 4 with confidence: 2.87447%
Top(3) prediction is 5 with confidence: 0.357717%
Top(4) prediction is 149 with confidence: 0.159937%
Top(5) prediction is 154 with confidence: 0.10502%
Total time for 3 test cases: 2.756 seconds
Average time per test case: 918.534 ms
One or more test cases failed
```
And this is an example image what I used
(https://m.post.naver.com/viewer/image.nhn?src=https%3A%2F%2Fpost-phinf.pstatic.net%2FMjAxODAxMDRfMzAw%2FMDAxNTE1MDMwMDA3ODk1.74n16yS0o_UUIdvdgKFZGMO4SLjOK6BExbtC9g46QyEg.htDW6Qp6eZnw8hai7kWuwIAMzvLPPdYRZwZxdEAHa1wg.PNG%2FTJYTYUKU.png)


I couldn't find what cause this problem.
When build this test code, stb library made some errors caused by -Werror option(almost of errors related with type casting)  so I ignored this error by removed -Werror option.
But I don't know this ignoring could make this kind of miss result.

Do you have some clues or opinions why this problem happen?

Thank you for your effort :)

**Comment by MatthewARM** [comment]
Hi @leeanzel, looks like your network is working fine. class 163 is "beagle" which is exactly the dog picture you are using! In our test we just happen to use a picture of a golden retriever which is class 208.

**Comment by leeanzel** [comment]
Hi @MatthewARM.
Thank you for kind reply.  I tried found class label but couldn't found so I confused that.
Now I'm so clear with this issue.

**Comment by MatthewARM** [comment]
Glad we could help, good luck with your work.

**Comment by mibrahimali** [comment]
@leeanzel : can you mentions how did you build tests , how did you add stb to includes and what changes did you made in globalconfig.cmake
