### ISSUE TITLE
Armnn ImageClassIfication sample Requested unknown backnd GpuAcc

### ISSUE THREAD

**Issue by Chernobyl81** [ARM-software/armnn#721]
I tested Armnn Image classification sample with armnn 23.02, I get outputs:
`Info: ArmNN v32.0.0
 Info: Initialization time: 7.36 ms.
INFO: TfLiteArmnnDelegate: Requested unknown backend GpuAcc
INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.`

I used rk3399 with mali-T860GPU, why it outputs 'Request unknown backend GPUAcc' ?

**Comment by MikeJKelly** [comment]
Hi @Chernobyl81 

Where did you get your version of ArmNN from? An error like this indicates that ArmNN was not built with Gpu support. 

Best regards,
Mike

**Comment by Chernobyl81** [comment]
Hi, @MikeJKelly，thanks for the reply. I download ArmNN from [https://github.com/ARM-software/armnn/releases/download/v23.02/ArmNN-linux-aarch64.tar.gz](url)

**Comment by TeresaARM** [comment]
Hi @Chernobyl81 

Could you send us the command you used for running the sample?

Thank you!

**Comment by MikeJKelly** [comment]
I'm closing this issue, if you're still having an issue then please reopen it or else raise a new issue.
Thanks,
Mike.
