### ISSUE TITLE
Add rknpu2 support into armnn

### ISSUE THREAD

**Issue by podarok** [ARM-software/armnn#722]
https://github.com/rockchip-linux/rknpu2 just released

Related issues
- https://github.com/rockchip-linux/rknpu2/issues/65
- https://github.com/blakeblackshear/frigate/pull/5733/files#diff-19c2d5c5cd8efa16c105dce5a243d311eefdd7412be831e655fc392c0fb320c1R40

**Comment by MatthewARM** [comment]
Hi @podarok could you explain a bit more about what you are suggesting here?

**Comment by podarok** [comment]
Hi @MatthewARM 
I'm using orange pi 5 which is based on RK3588S CPU for frigate NVR. There is a tensor lite ML detection.
With Armnn I was able to accomplish good performance from ARM core and MALI 610 GPU, but NPU - not used.
Above I posted a link to library, created by rockchip team that would be great to incorporate  in armnn in order to use 6TOPS NPU for ML tasks

**Comment by MatthewARM** [comment]
Understood. Needs someone to volunteer to add the new backend and maintain it.

**Comment by podarok** [comment]
For Frigate we succeeded with rknpu2 here https://github.com/blakeblackshear/frigate/pull/5733#issuecomment-1479317334

But this means we should have both armnn and rknpu2 detectors, which is not good long term

I still think rknpu2 is better to have as a part of armnn.
But as  you said @MatthewARM - depends of human resources at this point

**Comment by MikeJKelly** [comment]
Hi @podarok 

I'm going to close this ticket as it's outside of the scope of the ArmNN project. 

Best regards,
Mike
