### ISSUE TITLE
error during linking libarmnnTFParser.so

### ISSUE THREAD

**Issue by gunjupark** [ARM-software/armnn#73]
**Cmake result** 
![image](https://user-images.githubusercontent.com/36186765/46466145-6fbf4d80-c805-11e8-973b-84b2c3845403.png)

**make result** 
![image](https://user-images.githubusercontent.com/36186765/46466115-5b7b5080-c805-11e8-8512-1177a7edc831.png)

How can I resolve it?

**Comment by Surmeh** [comment]
Hi @gunjupark, Could you please share your results with us.

**Comment by MatthewARM** [comment]
Hi @gunjupark I hope you were able to get this working. Please let us know if you are still having problems.
