### ISSUE TITLE
Handle ONNX topography structure

### ISSUE THREAD

**Issue by IDownToEarth** [ARM-software/armnn#731]
Hi Just a quick question about the ONNX parsing. According to my understanding, if we do inference, we will need to know the topography of the net, so we will have a module to handle the topography. I find the file IOnnxParser.hpp, but I don't find the detailed code to handle the node info and node order in this file. So I just want to know does there exist such a module to handle the topography structure of ONNX. Thanks a lot.

**Comment by MikeJKelly** [comment]
Hi @IDownToEarth 
I think the code you want is in armnn/src/armnnOnnxParser/OnnxParser.cpp . Our support for ONNX operations is quite limited at the present but you may find what you want there. 

Best regards,
Mike

**Comment by KevinARM** [comment]
Hi @IDownToEarth 

There is also a list of supported layers here:
https://arm-software.github.io/armnn/23.05/parsers.xhtml#S5_onnx_parser

Regards,
Kevin

**Comment by John-ARM** [comment]
Closed due to inactivity, if you need any more information please reopen the issue or create a new one.
Thank you,
John
