### ISSUE TITLE
How to add new operator in armnn and acl?

### ISSUE THREAD

**Issue by zxros10** [ARM-software/armnn#732]
The link [Add a new operator to Arm NN](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/add-a-new-operator-to-arm-nn?_ga=2.88925011.950990763.1602664103-1666118367.1557236955) in document https://community.arm.com/arm-community-blogs/b/ai-and-ml-blog/posts/new-arm-ml-guide-add-a-new-operator-to-arm-nn is invalid.

**Comment by nikraj01** [comment]
Hi @zxros10 ,

Thanks for the question. Unfortunately we don't have a current external document on how to add a new operator to Arm NN. But you can find some example reviews in our gerrit on how we added some operators to Arm NN, for example https://review.mlplatform.org/c/ml/armnn/+/9368. If you like to contribute to Arm NN kindly follow guidelines in https://arm-software.github.io/armnn/23.08/md__c_o_n_t_r_i_b_u_t_i_n_g.html

I will also try to remove the link given in the blog to the guide, which doesn't exist anymore. I hope this helps.
Thanks

**Comment by zxros10** [comment]
Thanks
