### ISSUE TITLE
CpuAcc and GpuAcc not working (but CpuRef is)

### ISSUE THREAD

**Issue by Jonezia** [ARM-software/armnn#734]
Hi,

I'm running a resnet50 model with armnn. The model is a Firefly ROC-RK3588S-PC. The CPU is a Cortex-A55. clinfo has device name as Mali-LODX r0p0. With 50 samples, I get 80% accuracy with CpuRef runtime. However, when I switch to using CpuAcc runtime I get 4% accuracy. Is there any reason why this might be the case? I looked through the issues but couldn't find any similar ones.

When I switch to the GpuAcc runtime, it fails to run at all, with the following output:

```
<source>:1376:21: error: no matching function for call to 'select'
    res.s01234567 = select(res.s89abcdef, res.s01234567, CONVERT(idx_sel, int8));
                    ^~~~~~

note: candidate function not viable: no known conversion from 'int __attribute__((ext_vector_type(8)))' (vector of 8 'int' values) to 'ulong  __attribute__((ext_vector_type(8)))' (vector of 8 'ulong' values) for 3rd argument
...
note: candidate function not viable: no known conversion from 'long4' (vector of 4 'long' values) to 'long  __attribute__((ext_vector_type(16)))' (vector of 16 'long' values) for 1st argument
<source>:1384:19: error: no matching function for call to 'select'
    res.s01     = select(res.s23, res.s01, CONVERT(idx_sel.s01, int2));
                  ^~~~~~

note: candidate function not viable: no known conversion from 'int __attribute__((ext_vector_type(2)))' (vector of 2 'int' values) to 'ulong  __attribute__((ext_vector_type(2)))' (vector of 2 'ulong' values) for 3rd argument
...
note: candidate function not viable: no known conversion from 'long2' (vector of 2 'long' values) to 'long  __attribute__((ext_vector_type(16)))' (vector of 16 'long' values) for 1st argument
<source>:1387:18: error: call to 'select' is ambiguous
    res.s0     = select(res.s1, res.s0, CONVERT(idx_sel.s0, int));
                 ^~~~~~

note: candidate function
...
note: candidate function
<source>:1450:38: error: call to 'select' is ambiguous
                local_results[lid] = select(
                                     ^~~~~~

note: candidate function
...
note: candidate function
error: Compiler frontend failed (error code 62)

terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)
```

The model can be found here:
https://drive.google.com/file/d/1XTLql-c79IUNPR2l8FkgH_KGlzJmSYKO/view?usp=sharing

Thanks for any help.
Please let me know if any more info is needed.

**Comment by MatthewARM** [comment]
Did you build Arm NN and ACL yourself, or are you using a prebuilt binary? Is there any way you can run the Arm NN unit tests?

**Comment by MatthewARM** [comment]
And what's the output of `clinfo`?

**Comment by Jonezia** [comment]
Hi Matthew,

I downloaded a pre-compiled aarch64 binary.

The DelegateUnitTests all pass but 30 of the UnitTests fail. It seems as if it is missing some files. Here's the Unit Tests output:

`[doctest] doctest version is "2.4.6"
[doctest] run with "--help" for options
arm_release_ver of this libmali is 'g6p0-01eac0', rk_so_ver is '5'.
===============================================================================
/devenv/armnn-internal-tests/ClDmaBuf/ClDmaBufInternalTests.cpp:38:
TEST SUITE: ClDmaBufInternalTests
TEST CASE:  ClDmaBufImport

/devenv/armnn-internal-tests/ClDmaBuf/ClDmaBufInternalTests.cpp:38: ERROR: test case THREW exception: Test exporter does not exist

===============================================================================
/devenv/armnn-internal-tests/ClDmaBuf/ClDmaBufInternalTests.cpp:117:
TEST SUITE: ClDmaBufInternalTests
TEST CASE:  ClDmaBufImportEndToEnd

/devenv/armnn-internal-tests/ClDmaBuf/ClDmaBufInternalTests.cpp:117: ERROR: test case THREW exception: Test exporter does not exist

open errno:No such file or directory
===============================================================================
/devenv/armnn-internal-tests/ClDmaBuf/ClDmaBufInternalTests.cpp:254:
TEST SUITE: ClDmaBufInternalTests
TEST CASE:  ClDmaBufCustomAllocatorSampleApp

/devenv/armnn-internal-tests/ClDmaBuf/ClDmaBufInternalTests.cpp:254: ERROR: test case THREW exception: DmaBufFdTestExporter: File descriptor has error value -1. No such file or directory

Warning: Timed out waiting on profiling service activation for 3000.35 ms
Warning: Timed out waiting on profiling service activation for 3000.13 ms
Warning: Timed out waiting on profiling service activation for 3000.31 ms
Warning: Timed out waiting on profiling service activation for 3000.13 ms
Warning: Timed out waiting on profiling service activation for 3000.09 ms
===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:14:
TEST SUITE: DynamicBackendTests
TEST CASE:  OpenCloseHandle

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:18:
TEST SUITE: DynamicBackendTests
TEST CASE:  GetValidEntryPoint

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:19:
TEST SUITE: DynamicBackendTests
TEST CASE:  GetNameMangledEntryPoint

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:20:
TEST SUITE: DynamicBackendTests
TEST CASE:  GetNoExternEntryPoint

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:21:
TEST SUITE: DynamicBackendTests
TEST CASE:  GetNotExistingEntryPoint

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:28:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateDynamicBackendObjectInvalidInterface1

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:30:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateDynamicBackendObjectInvalidInterface2

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:32:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateDynamicBackendObjectInvalidInterface3

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:34:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateDynamicBackendObjectInvalidInterface4

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:36:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateDynamicBackendObjectInvalidInterface5

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:38:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateDynamicBackendObjectInvalidInterface6

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:40:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateDynamicBackendObjectInvalidInterface7

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:42:
TEST SUITE: DynamicBackendTests
TEST CASE:  OpenNotSharedObjectFile

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:43:
TEST SUITE: DynamicBackendTests
TEST CASE:  GetSharedObjects

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:45:
TEST SUITE: DynamicBackendTests
TEST CASE:  GetBackendPaths

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:46:
TEST SUITE: DynamicBackendTests
TEST CASE:  GetBackendPathsOverride

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:48:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateDynamicBackends

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:51:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateDynamicBackendsMixedTypes

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:53:
TEST SUITE: DynamicBackendTests
TEST CASE:  RegisterMultipleInvalidDynamicBackends

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:58:
TEST SUITE: DynamicBackendTests
TEST CASE:  RuntimeDynamicBackends

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:59:
TEST SUITE: DynamicBackendTests
TEST CASE:  RuntimeDuplicateDynamicBackends

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:60:
TEST SUITE: DynamicBackendTests
TEST CASE:  RuntimeInvalidDynamicBackends

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:67:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateReferenceDynamicBackend

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/dynamic

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:68:
TEST SUITE: DynamicBackendTests
TEST CASE:  CreateValidDynamicBackendObject

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:69:
TEST SUITE: DynamicBackendTests
TEST CASE:  RegisterSingleDynamicBackend

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:70:
TEST SUITE: DynamicBackendTests
TEST CASE:  RegisterMultipleDynamicBackends

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

===============================================================================
/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.cpp:71:
TEST SUITE: DynamicBackendTests
TEST CASE:  RegisterMixedDynamicBackends

/devenv/armnn/src/backends/backendsCommon/test/DynamicBackendTests.hpp:149: FATAL ERROR: REQUIRE( exists(sharedObjectPath) ) is NOT correct!
  values: REQUIRE( false )
  logged: Base path for shared objects does not exist: /home/firefly/work_collection/extracted_ArmNN-linux-aarch64.tar.gz/extracted/src/backends/backendsCommon/test/

Warning: Timed out waiting on profiling service activation for 3000.31 ms
Warning: Timed out waiting on profiling service activation for 3000.31 ms
Warning: Timed out waiting on profiling service activation for 3000.32 ms
Warning: Timed out waiting on profiling service activation for 3000.12 ms
===============================================================================
[doctest] test cases:   5245 |   5215 passed | 30 failed | 5 skipped
[doctest] assertions: 812097 | 812070 passed | 27 failed |
[doctest] Status: FAILURE!`

Here's the clinfo output:

`Number of platforms                               1
  Platform Name                                   ARM Platform
  Platform Vendor                                 ARM
  Platform Version                                OpenCL 2.1 v1.g6p0-01eac0.efb75e2978d783a80fe78be1bfb0efc1
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_subgroups cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_il_program cl_khr_priority_hints cl_khr_create_command_queue cl_khr_spirv_no_integer_wrap_decoration cl_khr_extended_versioning cl_khr_device_uuid cl_arm_core_id cl_arm_printf cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_import_memory_dma_buf cl_arm_import_memory_host cl_arm_integer_dot_product_int8 cl_arm_integer_dot_product_accumulate_int8 cl_arm_integer_dot_product_accumulate_saturate_int8 cl_arm_scheduling_controls cl_arm_controlled_kernel_termination cl_ext_cxx_for_opencl
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             ARM

  Platform Name                                   ARM Platform
Number of devices                                 1
arm_release_ver of this libmali is 'g6p0-01eac0', rk_so_ver is '5'.
  Device Name                                     Mali-LODX r0p0
  Device Vendor                                   ARM
  Device Vendor ID                                0xa8670000
  Device Version                                  OpenCL 2.1 v1.g6p0-01eac0.efb75e2978d783a80fe78be1bfb0efc1
  Driver Version                                  2.1
  Device OpenCL C Version                         OpenCL C 2.0 v1.g6p0-01eac0.efb75e2978d783a80fe78be1bfb0efc1
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               4
  Max clock frequency                             1000MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             1024
  Preferred work group size multiple              16
  Max sub-groups per work group                   64
  Preferred / native vector sizes
    char                                                16 / 4
    short                                                8 / 2
    int                                                  4 / 1
    long                                                 2 / 1
    half                                                 8 / 2        (cl_khr_fp16)
    float                                                4 / 1
    double                                               0 / 0        (n/a)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    64, Little-Endian
  Global memory size                              16458850304 (15.33GiB)
  Error Correction support                        No
  Max memory allocation                           16458850304 (15.33GiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   No
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
  Max size for global variable                    65536 (64KiB)
  Preferred total size of global vars             0
  Global Memory cache type                        Read/Write
  Global Memory cache size                        1048576 (1024KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   32 bytes
    Pitch alignment for 2D image buffers          64 pixels
    Max 2D image size                             65536x65536 pixels
    Max 3D image size                             65536x65536x65536 pixels
    Max number of read image args                 128
    Max number of write image args                64
    Max number of read/write image args           64
  Max number of pipe args                         16
  Max active pipe reservations                    1
  Max pipe packet size                            1024
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max number of constant args                     128
  Max constant buffer size                        16458850304 (15.33GiB)
  Max size of kernel argument                     1024
  Queue properties (on host)
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Queue properties (on device)
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                2097152 (2MiB)
    Max size                                      16777216 (16MiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Sub-group independent forward progress        Yes
    IL version                                    SPIR-V_1.0
    SPIR versions                                 <printDeviceInfo:161: get CL_DEVICE_SPIR_VERSIONS size : error -30>
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_subgroups cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_il_program cl_khr_priority_hints cl_khr_create_command_queue cl_khr_spirv_no_integer_wrap_decoration cl_khr_extended_versioning cl_khr_device_uuid cl_arm_core_id cl_arm_printf cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_import_memory_dma_buf cl_arm_import_memory_host cl_arm_integer_dot_product_int8 cl_arm_integer_dot_product_accumulate_int8 cl_arm_integer_dot_product_accumulate_saturate_int8 cl_arm_scheduling_controls cl_arm_controlled_kernel_termination cl_ext_cxx_for_opencl

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  ARM Platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [ARM]
  clCreateContext(NULL, ...) [default]            Success [ARM]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-LODX r0p0
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-LODX r0p0
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-LODX r0p0

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1`

**Comment by MatthewARM** [comment]
Thanks. Those unit tests failures look OK to me - none of the failures are in the CpuAcc backend, and the few to do with DmaBuf and Dynamic Backends are due to running a precompiled binary without access to the full source tree.

So... Arm NN is working "correctly". The OpenCL driver looks working fine as well. 

Out of interest, how are you running the model in your test? Arm NN TfLite parser and Arm NN runtime? Or Arm NN TfLite delegate?

**Comment by Jonezia** [comment]
I'm using the TfLite parser and Arm NN runtime. Can provide code if required.

**Comment by davmon01** [comment]
Which version of ArmNN / CL are you using the binaries for? Those tests should not be included in the binaries as they require external files that we do not ship with ArmNN. It's a bug on our part.

**Comment by Jonezia** [comment]
ArmNN version 23.02.

**Comment by Jonezia** [comment]
Good news I upgraded to version 23.08 and the GpuAcc is working now with seemingly sensible accuracy. Sadly CpuAcc still gives me very low accuracy.

**Comment by nikraj01** [comment]
Hi @Jonezia ,

Thanks for reporting this. If I understood it correctly you got this Unittest errors from using the pre-built binaries from 23.02. We don't put Unittest in our binaries from 23.05 onwards as we realized it was a bug on our side to put Unittest in those pre-built binaries. So kindly use the latest binaries to build ArmNN.


Thanks

**Comment by Jonezia** [comment]
Yes I downloaded the prebuilt binary for version 23.08 and there were no Unit-tests. The GpuAcc now works but the CpuAcc still has poor accuracy. I can try building the latest version from source this afternoon.

**Comment by Jonezia** [comment]
I've built version 23.08 from source, and it seems to have the same result as the prebuilt binary. All the UnitTests pass and as well as the DelegateUnitTests for GpuAcc, but 2 of the DelegateUnitTests for CpuAcc fail with the following log
```
INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
INFO: TfLiteArmnnDelegate: Requested unknown backend CpuRef
===============================================================================
/home/firefly/armnn-build/armnn-23.08/build-tool/scripts/source/armnn/delegate/test/DelegateOptionsTest.cpp:243:
TEST SUITE: DelegateOptions_CpuAccTests
TEST CASE:  ArmnnDelegateSerializeToDot

/home/firefly/armnn-build/armnn-23.08/build-tool/scripts/source/armnn/delegate/test/DelegateOptionsTest.cpp:243: ERROR: test case THREW exception: TfLiteArmnnDelegate: No known backend specified.

INFO: TfLiteArmnnDelegate: Requested unknown backend CpuRef
===============================================================================
/home/firefly/armnn-build/armnn-23.08/build-tool/scripts/source/armnn/delegate/test/DelegateOptionsTest.cpp:315:
TEST SUITE: DelegateOptions_CpuAccTests
TEST CASE:  ArmnnDelegateStringParsingOptionReduceFp32ToFp16
  Fp16=1

/home/firefly/armnn-build/armnn-23.08/build-tool/scripts/source/armnn/delegate/test/DelegateOptionsTest.cpp:315: ERROR: test case THREW exception: exception thrown in subcase - will translate later when the whole test case has been exited (cannot translate while there is an active exception)

===============================================================================
/home/firefly/armnn-build/armnn-23.08/build-tool/scripts/source/armnn/delegate/test/DelegateOptionsTest.cpp:315:
TEST SUITE: DelegateOptions_CpuAccTests
TEST CASE:  ArmnnDelegateStringParsingOptionReduceFp32ToFp16

DEEPEST SUBCASE STACK REACHED (DIFFERENT FROM THE CURRENT ONE):
  Fp16=1

/home/firefly/armnn-build/armnn-23.08/build-tool/scripts/source/armnn/delegate/test/DelegateOptionsTest.cpp:315: ERROR: test case THREW exception: TfLiteArmnnDelegate: No known backend specified.
```

**Comment by John-ARM** [comment]
Hello,
Are you only using a single specific backend in running the tests?
Unfortunately the specific test suite which is failing contains tests for multiple different backends (both CpuAcc and CpuRef).
We will look in to renaming the test suite or changing its contents.
Thank you
John

**Comment by John-ARM** [comment]
I have now duplicated the accuracy issue with the model provided and found there to be a bug on our side for the CpuAcc backend implementation. I have created a ticket and escalated this to the relevant design team.
I also found an existing work item to realign certain test suites to allow them to be run on specific backends.
Thank you for your input and please let me know if there is anything else you need.
John
