### ISSUE TITLE
Error while building Armnn CrossCompilation

### ISSUE THREAD

**Issue by praisonjoshua** [ARM-software/armnn#74]
![screenshot 9](https://user-images.githubusercontent.com/33496837/46472580-4f8a9100-c7fb-11e8-939b-5c15430d3b7a.png)

this C compiler error is stopping us

**Comment by MatthewARM** [comment]
Hi @praisonjoshua to help figure out what is going wrong, please could you find out:

* Is aarch64-linux-gnu-gcc on your path?
* If you run "aarch64-linux-gnu-gcc -v" what is the output?
* Are there any useful error messages in CMakeFiles/CMakeError.log?

All the best,
Matthew
