### ISSUE TITLE
How Armnn deal with unsupport operator by armnn_delegate

### ISSUE THREAD

**Issue by zxros10** [ARM-software/armnn#740]
I execute command to execute my tflite model:

./aarch64_build/tests/ExecuteNetwork -N -I 5 -c CpuAcc -m xxx.tflite --reuse-buffers --tflite-executor delegate

And has error log:

INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
ERROR: Operator TILE [69] is not supported by armnn_delegate.
Info: ArmnnSubgraph creation

But the command execute successful. How armnn deal with the unsupport operator TILE ? The inference result is ok ?
Thanks!

**Comment by MikeJKelly** [comment]
Hi @zxros10 

If armnn doesn't support the Operator then it will be fall back to TfLite and run using their code so the inference result should be OK. 

Best regards,
Mike

**Comment by TeresaARM** [comment]
Hi @zxros10,

which ArmNN release are you using? Tile is supported in ArmNN from 23.08. We invite you to try our 23.11 release that will be published very soon and see if Tile runs on ArmNN.

Regards
Teresa

**Comment by MikeJKelly** [comment]
23.11 was just pushed yesterday so if you clone the repo again you'll get that version. It has support for TILE.

**Comment by zxros10** [comment]
> 23.11 was just pushed yesterday so if you clone the repo again you'll get that version. It has support for TILE.

Thanks，I update my project to 23.11 today
