### ISSUE TITLE
How to use the profiling data to improve my inference

### ISSUE THREAD

**Issue by zxros10** [ARM-software/armnn#741]
I get profiling data with ExecuteNetwork -e. Now I need improve my model inference time.
Is there practice example or document explain the data item in the json, and show how to improve profiling ?
Thanks

**Comment by TeresaARM** [comment]
Hi,
in the ExecuteNetwork command, what backend are you using "-c CpuRef" or -c "CpuAcc" or "-c GpuAcc" ?

**Comment by tracyn-arm** [comment]
This topic has come up before and  here are some links in case it helps:
- https://github.com/ARM-software/armnn/issues/464
- https://github.com/ARM-software/armnn/issues/615
Unfortunately, I am unaware of additional information on Arm NN profiling.
