### ISSUE TITLE
How to close optimization of graph or save optimized graph in dot/tflite format when I run test/executeNetwork and set --tflite-executor as delegate? Does armnn provide options?

### ISSUE THREAD

**Issue by hgy20** [ARM-software/armnn#745]

**Comment by tracyn-arm** [comment]
Hi. You can save a dot file using the "-v, --visualize-optimized-model" parameter of ExecuteNetwork. The saving of the dot file happens after the network is optimized and I think it is placed in the same directory of the model. This is done in the armnn_delegate.cpp file in the classic and opaque code paths after armnn::Optimize(...) is called. Please let us know if you are seeing something unexpected. Thanks.

**Comment by tracyn-arm** [comment]
Thank-you.  I am seeing the problem and looking for a fix.

**Comment by tracyn-arm** [comment]
A fix was returned: https://review.mlplatform.org/c/ml/armnn/+/10867. Thank-you for reporting this issue.
