### ISSUE TITLE
Do you have armnn profiling analyze tool? 

### ISSUE THREAD

**Issue by zxros10** [ARM-software/armnn#747]
I get the profiling data with ExecuteNetwork -e ，do you have tool to analyze the raw data, or turn data into visualization like chrom tracing ? Thanks

**Comment by morgolock** [comment]
Hi @zxros10 

I normally use a python script to analyze the output of the profiler,
please see https://github.com/ARM-software/ComputeLibrary/issues/950

**Comment by zxros10** [comment]
Thanks
