### ISSUE TITLE
Gather operator dimension check error

### ISSUE THREAD

**Issue by zxros10** [ARM-software/armnn#748]
![image](https://github.com/ARM-software/armnn/assets/40817806/10a23910-4fce-42d7-8c33-d9075b9817ff)

In my model have Gather operator node, input is (3, 384,4,144,32), parameter axis is 0, outpu shape is (384, 4, 144, 32). When inference the model with ExecuteNetwork parser, has error:

within subgraph #0 error: Operation has invalid output dimensions: 4 Output must be an (5 + 1 - 1) -D tensor  at function ParseGather [/home/arm-user/source/armnn/src/armnnTfLiteParser/TfLiteParser.cpp:4786]

In onnx  operator Documentation this this dimension check is right. But my model inference with onnxruntime and tflite is ok. I don't want use ExecuteNetwork delegate, it degrade performance of my model

**Comment by morgolock** [comment]
Hi @zxros10 

Could you please share the model ? Is it an `.onnx` file?

**Comment by zxros10** [comment]
![gather_dim_test](https://github.com/ARM-software/armnn/assets/40817806/f440f9c7-531f-40a9-8d9a-72a1a079a80c)
The attach is the test model I construct for this case

**Comment by MikeJKelly** [comment]
Hi @zxros10 

That Gather operator is actually a GatherND (it has both axis and batch_dims) but the Onnx Parser doesn't support GatherND so it's interpreting it as a Gather operator and so it's calculating the Output shape incorrectly. I'll see if we can add support for GatherND to the Onnx Parser. 

Best regards,
Mike

**Comment by zxros10** [comment]
Thanks
I think this is not only problem of armnn onnx parser. I convert this onnx model to tflite, and run in armnn gpu, and has this error.

**Comment by zxros10** [comment]
I have to resolve this problem in my project. The input model is tflite, and execute ExecuteNetwork with parameter --tflite-executor parser. 
Please give me some suggestion for modify the armnn code. Thanks

**Comment by tracyn-arm** [comment]
Hi. The link for gather_dim_test above is broken for me.  Can you please repost this file and provide the exact ExecuteNetwork line you are using?  Thanks.

**Comment by zxros10** [comment]
[gather_dim_test.zip](https://github.com/ARM-software/armnn/files/13902973/gather_dim_test.zip)

**Comment by tracyn-arm** [comment]
I ran the test with a very current version of Arm NN: ./ExecuteNetwork --compute GpuAcc --model-path ./gather_dim_test.onnx --tflite-executor parser
I am getting the following error: Fatal: Unsupported operation Slice for node 'Slice_13'  at function LoadGraph

This thread has been about Gather so wondering if Slice is now the issue  you are asking about?  Thanks.

**Comment by tracyn-arm** [comment]
Hi. Can you please close this issue and re-open another one with the right .tflite file and command line to reproduce?  The zip file provided 5 days ago had only the .onnx model which has additional issues in the parsing. Thanks.

**Comment by zxros10** [comment]
Ok, I will re-open another one and provide the models
