### ISSUE TITLE
Set number of threads

### ISSUE THREAD

**Issue by dimitryn** [ARM-software/armnn#75]
Hi , I am testing arm nn as part of our application and I need to set a number of thread = 1 for Neon
I only using hpp from \armnn\include .
I found NeonInterceptorScheduler have this option but how can use it using only interfaces from \armnn\include

Thanks.

**Comment by MatthewARM** [comment]
Hi @dimitryn we don't have a way to set the number of CPUs just using the armnn interface, but you should be able to include a header file from Compute Library to get access to the scheduler?
Something like:
<pre>
#include <arm_compute/runtime/Scheduler.h>

arm_compute::Scheduler::get().set_num_threads(1);
</pre>

Hope that helps,
Matthew

**Comment by dimitryn** [comment]
Thanks

**Comment by kk2496** [comment]
Where should we add this statement? Also, after adding the statement do I have to build the whole library again or is there custom SConscript to build just the required part? Thanks

**Comment by MikeJKelly** [comment]
Hi @kk2496 

You should put this in your own application code, you don't have to add it to armnn or the CL library. You could add it to the start of your main method but anywhere should work so long as it's called before the Scheduler is used. 

Best regards,
Mike

**Comment by Mo-Abdelgawad** [comment]
Hi @MatthewARM  and @MikeJKelly  

I followed your guidance to change the number of threads, but got errors related to the scope. In addition, `get` does not seem to be a member of `Scheduler`.
I added the following lines in the [mnist.caffe.cpp](https://github.com/ARM-software/ML-examples/blob/master/armnn-mnist/mnist_caffe.cpp)
`#include <arm_compute/runtime/Scheduler.h>`
`arm_compute::Scheduler::get().set_num_threads(2);` //put in the main. 

Errors: 

```
In file included from mnist_caffe.cpp:20:
./arm_compute/runtime/Scheduler.h:50:37: error: ‘IScheduler’ was not declared in this scope; did you mean ‘Scheduler’?
   50 |     static void set(std::shared_ptr<IScheduler> scheduler);
      |                                     ^~~~~~~~~~
      |                                     Scheduler
./arm_compute/runtime/Scheduler.h:50:47: error: template argument 1 is invalid
   50 |     static void set(std::shared_ptr<IScheduler> scheduler);
      |                                               ^
./arm_compute/runtime/Scheduler.h:55:12: error: ‘IScheduler’ does not name a type; did you mean ‘Scheduler’?
   55 |     static IScheduler &get();
      |            ^~~~~~~~~~
      |            Scheduler
./arm_compute/runtime/Scheduler.h:78:28: error: ‘IScheduler’ was not declared in this scope; did you mean ‘Scheduler’?
   78 |     static std::shared_ptr<IScheduler> _custom_scheduler;
      |                            ^~~~~~~~~~
      |                            Scheduler
./arm_compute/runtime/Scheduler.h:78:38: error: template argument 1 is invalid
   78 |     static std::shared_ptr<IScheduler> _custom_scheduler;
      |                                      ^
./arm_compute/runtime/Scheduler.h:79:43: error: ‘IScheduler’ was not declared in this scope; did you mean ‘Scheduler’?
   79 |     static std::map<Type, std::unique_ptr<IScheduler>> _schedulers;
      |                                           ^~~~~~~~~~
      |                                           Scheduler
./arm_compute/runtime/Scheduler.h:79:43: error: template argument 1 is invalid
./arm_compute/runtime/Scheduler.h:79:43: error: template argument 2 is invalid
./arm_compute/runtime/Scheduler.h:79:53: error: template argument 2 is invalid
   79 |     static std::map<Type, std::unique_ptr<IScheduler>> _schedulers;
      |                                                     ^~
./arm_compute/runtime/Scheduler.h:79:53: error: template argument 4 is invalid
mnist_caffe.cpp: In function ‘int main(int, char**)’:
mnist_caffe.cpp:42:28: error: ‘get’ is not a member of ‘arm_compute::Scheduler’
   42 |    arm_compute::Scheduler::get().set_num_threads(2);
      |                            ^~~
make: *** [Makefile:7: mnist_caffe] Error 1
```
Could you help with that?

Thanks,
Mohamed
