### ISSUE TITLE
I want config the gpu core number for armnn

### ISSUE THREAD

**Issue by zxros10** [ARM-software/armnn#750]
My device is mali G610. Now I can't monopolize all cores. Does Armnn provid the way to config gpu cores for the model inference? 
Thanks

**Comment by xiaotongnii** [comment]
Armnn use acl to call cl kernel，Opencl map cl kernel to gpu core. Armnn maybe not support config gpu cores dirtectly。

**Comment by tracyn-arm** [comment]
Hi. I have to agree with the answer above also.  Arm NN creates a workload that is passed on to ACL and I could not see a way of controlling the gpu cores that are used.  Thanks.
