### ISSUE TITLE
ScatterND not support

### ISSUE THREAD

**Issue by zxros10** [ARM-software/armnn#753]
Do you have plan to support Scatter/ScatterND operator ? Thanks

**Comment by tracyn-arm** [comment]
Hi. We have a similar request for ScatterND and I added your information(Scatter + ScatterND) to this ticket.  The current version of the Compute Library (used by Arm NN) does not seem to support either Scatter operator so it's a bit of a long road and it is unclear if this work would go forward.  Thanks for raising this.

**Comment by zxros10** [comment]
Thanks， I am trying to impletement ScatterND currently

**Comment by TeresaARM** [comment]
Hello, ScatterNd is now supported in ArmNN in main, it will be part of 24.05 release
