### ISSUE TITLE
onnx  deployment fail

### ISSUE THREAD

**Issue by tianyashu2020** [ARM-software/armnn#761]
I tried to use armnn to deploy my onnx model,but failed. Could anyone help me?
![image](https://github.com/ARM-software/armnn/assets/79447803/fe4b15de-8ed8-4a01-8e27-e8d032f9306a)

**Comment by tianyashu2020** [comment]
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Unsupported operation Transpose for node '/Transpose'  at function LoadGraph [/home/shuqinjun/arm_nn/armnn/build-tool/scripts/source/armnn/src/armnnOnnxParser/OnnxParser.cpp:966]
Aborted (core dumped)

**Comment by catcor01** [comment]
Hello @tianyashu2020,

It seems you are using build-tool. Are you running the model through ExecuteNetwork? You might be able provide details how you are running the model including target backend, ArmNN SHA/branch and details about the Transpose operator that is failing in your model. Additionally, if the model is publicly available, please post a link to it here and I can attempt to reproduce it.

**Comment by tianyashu2020** [comment]
> Hello @tianyashu2020,
> 
> It seems you are using build-tool. Are you running the model through ExecuteNetwork? You might be able provide details how you are running the model including target backend, ArmNN SHA/branch and details about the Transpose operator that is failing in your model. Additionally, if the model is publicly available, please post a link to it here and I can attempt to reproduce it.

hello，this is my code，I  compiled the armnn so lib in my X64 platform,using ubuntu 22.04  operating system,
I just want to test my model   in "armnn::Compute::CpuRef"  mannaer.

the attached file is my onnx model.

[tru_net_phase_32k_no_dereverb_sim.zip](https://github.com/ARM-software/armnn/files/14716060/tru_net_phase_32k_no_dereverb_sim.zip)


![image](https://github.com/ARM-software/armnn/assets/79447803/ac15de7e-9303-47ed-9a2a-2d4c88c7ee49)
![image](https://github.com/ARM-software/armnn/assets/79447803/0eac29a1-277f-46d3-8820-838151a2a72b)

**Comment by catcor01** [comment]
Hello,

Thank you for your reply. Unfortunately, I am restricted in downloading user supplied models and can only interact with models that are publicly available under an appropriate license. Would the model be available somewhere? Else, if you could supply me with the operator info such as datatype etc. I can find more into why it is not supported on our side.

**Comment by catcor01** [comment]
Hello again,

I just wanted to suggest you can use ONNX runtime with ACL as an option to accelerate your model also. See here: https://onnxruntime.ai/docs/execution-providers/community-maintained/ACL-ExecutionProvider.html.

Kind Regards,
Cathal.

**Comment by tianyashu2020** [comment]
@catcor01  problem fixed，the reason is  the transpose with groups parameter in my model is not supported, I fixed the transpose  operator，it worked
very thanks for you relpay.

**Comment by tianyashu2020** [comment]
@catcor01 problem fixed，the reason is the transpose with groups parameter in my model is not supported, I fixed the transpose operator，it worked
very thanks for you reply
