### ISSUE TITLE
nvalid attempt to construct ConstTensor from non-constant TensorInfo

### ISSUE THREAD

**Issue by tianyashu2020** [ARM-software/armnn#765]
os:ubuntu 18.04
model formate：tflite

Anybody help me？

![image](https://github.com/ARM-software/armnn/assets/79447803/ef2b5d5f-bddf-4065-b51a-63643705c65e)
![image](https://github.com/ARM-software/armnn/assets/79447803/dc8d3d26-105a-4069-9183-a7c01248516c)

**Comment by Colm-in-Arm** [comment]
Hello,

I don't see anything wrong with the first block of code. It is logically similar to our SimpleSample.cpp code.

There is no indication that the error you're seeing is coming from that code. I suggest you put a breakpoint in the ConstTensor constructors of Tensor.hpp and see where the problem originates.

Colm.
