### ISSUE TITLE
Error during NDK build

### ISSUE THREAD

**Issue by d-b-h** [ARM-software/armnn#77]
I am compiling the Boost C++ libraries using Boost For Android.  The compilation is happening, but I am facing trouble in the last step i.e running ndk-build.

I am getting the following error messege:

Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
/home/deeptihegde/armnn-devenv/toolchains/android-ndk-r18/build/core/build-local.mk:151: *** Android NDK: Aborting    .  Stop.

![screenshot from 2018-10-10 05-42-20](https://user-images.githubusercontent.com/29578828/46691344-5877ca00-cc22-11e8-87b8-d8ccdf927126.png)

I am unable to locate  the NDK_PROJECT_PATH variable, and I am running the script from the appropriate directories.

**Comment by Surmeh** [comment]
Hi @d-b-h,

I hope you're following the instructions https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md. Could you please append NDK path to ~/.bashrc (or ~/.bash_profile in Mac OS) i.e. export NDK=~/armnn-devenv/toolchains/android-ndk-r18 and see if that works.

Thanks,
Surabhi

**Comment by d-b-h** [comment]
Hi @Surmeh , thanks for the reply.
I am following the instructions, however the Boost C++ step was not working, so I am using Boost for Android.  The instruction for ndk-build comes from that repo.
I appended "export NDK=~/armnn-devenv/toolchains/android-ndk-r18"  to ~/.bashrc but I am getting the same error.

**Comment by MatthewARM** [comment]
Hi @d-b-h it seems you are having trouble with Boost for Android, have you tried asking them for help?

We don't have any experience using Boost for Android, we compile Boost using the steps described in https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md

Hope that helps,
Matthew

**Comment by Surmeh** [comment]
HI @d-b-h,

Let us know if you require any more information from us, if not I'll close this ticket. Hope you've got your answer.
