### ISSUE TITLE
How to set priority of the application running on GPU?

### ISSUE THREAD

**Issue by qianfei11** [ARM-software/armnn#775]
I want to test the job preemption on Mali GPU, and I find the `cl_khr_priority_hints` extension on OpenCL, but my GPU (Mali-G71) does not have this feature. Is there any way in armnn to set the priority of a GPU application? Or, is there any where else I can ask for the answer?

**Comment by Colm-in-Arm** [comment]
Hello again.

The GPU is a black box to Arm NN. We interact with it through Arm Compute library.

Maybe you could ask the question over there: https://github.com/ARM-software/ComputeLibrary/issues

Colm.

**Comment by qianfei11** [comment]
Thanks Colm, I will try to ask the question in ACL's repo.
