### ISSUE TITLE
memory alignment

### ISSUE THREAD

**Issue by skane1024** [ARM-software/armnn#777]
In the BuildArmComputeTensor(Tensor& tensor, const armnn::TensorInfo& tensorInfo) function in the ArmComputeTensorUtils.hpp file, I tried to modify the alignment value of ComputeTensor memory, that is,

`tensor.allocator()->init(BuildArmComputeTensorInfo(tensorInfo));` 
modified to 
`tensor.allocator()->init(BuildArmComputeTensorInfo(tensorInfo),4096);,`

making the allocated memory can be 4K aligned(default 64), but in the test found that the execution speed of some operators has slowed down, I don't quite understand why?

**Comment by Colm-in-Arm** [comment]
Hi,

Superficially I can't see any obvious reason why inference performance would decrease by changing the tensor alignment.  Is it CpuAcc or GpuAcc you're using? If you can tell me the hardware too that might be relevant too.

Colm.
