### ISSUE TITLE
Linking Error while Building Armnn using Android NDK

### ISSUE THREAD

**Issue by VinayKarnam** [ARM-software/armnn#78]
[  4%] Built target armnnUtils
[  5%] Linking CXX shared library libarmnn.so
/usr/local/cuda/lib64/libOpenCL.so: error adding symbols: File in wrong format
clang50++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libarmnn.so] Error 1
make[1]: *** [CMakeFiles/armnn.dir/all] Error 2
make: *** [all] Error 2

**Comment by VinayKarnam** [comment]
![screenshot from 2018-10-10 17-29-26](https://user-images.githubusercontent.com/35588771/46735060-ac31f400-ccb2-11e8-8c9a-3b6272d597d5.png)

**Comment by VinayKarnam** [comment]
Thank you for the response , we added the patch and it is resoloved and we are moving further towards running unit tests on Android .

**Comment by praisonjoshua** [comment]
Thank you it solved our problem.
