### ISSUE TITLE
`clGetEventProfileInfo` raises error in `ClConvolution2dWorkload`

### ISSUE THREAD

**Issue by mertalev** [ARM-software/armnn#782]
Running inference with [this](https://huggingface.co/immich-app/buffalo_l/resolve/f14832a53c936d4602564c26cdf392d763a4d63d/detection/model.armnn) ARM NN model converted from [this](https://huggingface.co/immich-app/buffalo_l/resolve/95eead1b8478f4b0b4d866b194a6e7ed249fbd36/detection/model_float32.tflite) TFLite model using only GpuAcc produces the following error for Rockchip RK3588:
```
Error: An error occurred attempting to execute a workload: CL error: clGetEventProfileInfo. Error code: -58 at function Execute [/devenv/armnn/src/backends/cl/workloads/ClConvolution2dWorkload.cpp:162]
```
I don't have an ARM device to test this with, but several users have reported this behavior. The input shape is NCHW (1, 3, 640, 640), internally transposed to NHWC (1, 640, 640, 3).

Conversion and inference was done with version 23.11. Let me know if this seems like something that could be fixed by using a later version. You can use the `ghcr.io/immich-app/immich-machine-learning:v1.108.0-armnn` Docker image for the specific environment. The Mali firmware itself is mounted as such:
```yaml
devices:
  - /dev/mali0:/dev/mali0
volumes:
  - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro
  - /usr/lib/libmali.so:/usr/lib/libmali.so:ro
```

The TFLite model was also converted from an ONNX model. Interestingly, a different approach to conversion to [TFLite](https://huggingface.co/immich-app/buffalo_l/resolve/4a5bd86787f59231932fdaa6ba9813314a890f51/detection/buffalo_l_det.tflite) works as expected with [this](https://huggingface.co/immich-app/buffalo_l/resolve/4a5bd86787f59231932fdaa6ba9813314a890f51/detection/buffalo_l_det.armnn) ARM NN model. I'm not sure if this is due to it being float16 or something else since this TFLite model otherwise looks too similar to the problematic one. The [problematic TFLite model in float16](https://huggingface.co/immich-app/buffalo_l/resolve/95eead1b8478f4b0b4d866b194a6e7ed249fbd36/detection/model_float16.tflite) still produces the same error. It does have `Dequantize` nodes with the ops in float32, however.

P.S. Is there a way to force the converted model to be fully float16, ignoring any dequantization? TFLite makes it extremely difficult to output a float16 model without those nodes.

**Comment by Colm-in-Arm** [comment]
Hello,

To avoid me having to go looking again in the future: both models are licensed by InsightFace which uses MIT.

Fundamentally both of the models are fine. They execute without error on a hikey960 using an older Mali G71.

From Open CL I can see that clGetEventProfileInfo relates to GPU profiling and as part of that line of code we will try to begin kernel timing but only when profiling is active. Have you explicitly enabled profiling? If so try disabling it. It is also possible that profiling is not enabled in your configuration of OpenCL.

I think the FP16 conversion you're referring to is [FP16 post training quantization](https://www.tensorflow.org/lite/performance/post_training_float16_quant). Arm NN does not have a mechanism to execute these models as FP16. I believe the Tensorflow runtime default GPU backend does include such a mechanism.

Colm.

**Comment by Colm-in-Arm** [comment]
I managed to find a Redmi K60E containing a Dimensity 8200 which includes a Mali G610. I ran the model and it executed correctly. I also ran with internal profiling enabled and it still worked correctly.

Colm.

**Comment by mertalev** [comment]
Hi Colm! Thanks for testing and pointing us toward profiling. Both models work as expected when we explicitly disable profiling.

> I think the FP16 conversion you're referring to is [FP16 post training quantization](https://www.tensorflow.org/lite/performance/post_training_float16_quant). Arm NN does not have a mechanism to execute these models as FP16. I believe the Tensorflow runtime default GPU backend does include such a mechanism.

We tried the `SetReduceFp32ToFp16` runtime option to solve this, and it makes the model performance match the fully FP16 ARM NN model. The downside is that it ends up using much more RAM. Is there a way to serialize this model so we can load it without doing this conversion at runtime?

**Comment by Colm-in-Arm** [comment]
Hello,

SetReduceFp32ToFp16 is a runtime optimization flag. We don't have a mechanism to save an optimized network for later inference as optimizations can be backend specific and that data isn't contained in the Arm NN format. Really what you're looking for is to fully convert a trained model to FP16. Arm NN doesn't have any tools for that.

Colm.

**Comment by mertalev** [comment]
Thanks Colm! Closing this issue since the OpenCL issue is fixed.

> Really what you're looking for is to fully convert a trained model to FP16. Arm NN doesn't have any tools for that.

This is tough since TFLite doesn't like FP16 ops, but it has the best op coverage to convert to ARMNN. The fully FP16 TFLite model was through yet another converter to produce an invalid model that converts correctly to ARM NN (and that converter itself doesn't have great op support). For now we can use the runtime flag, but it'd be great if there were an easier way to do what you're describing.
