### ISSUE TITLE
Clarification on python `tflite-runtime.interpreter.load_delegate` for Opaque Delegate in Arm NN

### ISSUE THREAD

**Issue by aoi127** [ARM-software/armnn#790]
Hello Arm NN Team,

I am currently using tflite-runtime in Python and utilizing Arm NN tflite delegate. I have a question regarding the use of `tflite.load_delegate` when the `library` parameter is set to an opaque delegate. Specifically, I would like to know how to set the `options` parameter in this case. Should the `options` parameter be configured the same way as when the `library` parameter is set to a classic delegate?

I have reviewed the Arm NN documentation but couldn't find the information I was looking for. Could you please provide guidance?

Thank you for your assistance!

**Comment by orlmon01** [comment]
Hiya,
Yes, the options parameter is the same for both of our delegates. They both use the options defined under armnn/delegate/common/include/DelegateOptions.hpp
I hope this answers your question.

**Comment by aoi127** [comment]
> Hiya, Yes, the options parameter is the same for both of our delegates. They both use the options defined under armnn/delegate/common/include/DelegateOptions.hpp I hope this answers your question.

Thanks for the help 😄
