### ISSUE TITLE
Please describe -DBUILD_TF_PARSER Tensorflow build options

### ISSUE THREAD

**Issue by rmey** [ARM-software/armnn#8]
Hello,
I successfully build ARM NN SDK on Odroid HC-2 with the Caffee Parser described here: [https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-caffe/testing-the-build](url)
But I don't find any more detailed option what I need to enable and build for Tensorflow Parser Option -DBUILD_TF_PARSER. Could you share how you build Tensorflow on ARM for being used by ARM NN SDK please?

**Comment by MatthewARM** [comment]
Hi @rmey the official documentation for building the TensorFlow parser has been delayed but will be ready quite soon.

In the meantime, I hope I can assist you directly.

You need to process the TensorFlow protobuf files with protoc, and then when you run cmake for armnn, pass `-DTF_GENERATED_SOURCES=<path to tensorflow generated sources>` to tell the armnn build system where to find the files.

There is a script for running protoc on the tensorflow protobuf files at armnn/scripts/generate_tensorflow_protobuf.sh.

Apart from those things, the build process is the similar to building the Caffe parser.

**Comment by MatthewARM** [comment]
Hi @rmey I'm closing this issue since I think the question has been answered. Please get back in touch if you have any more problems.
