### ISSUE TITLE
cmake error while building armnn using Android-NDK

### ISSUE THREAD

**Issue by VinayKarnam** [ARM-software/armnn#81]
I got a cmake  error while building armnn . It says that ndk is not found but i didn't get any error while building ndk and i have exported the PATH variable.
i got the below error:

lenovo@lenovo-Lenovo-ideapad-300-15ISK:~/armnn-devenv/armnn/build$ CXX=aarch64-linux-android-clang++  CC=aarch64-linux-android-clang  CXX_FLAGS="-fPIE -fPIC"  cmake ..   -DCMAKE_SYSTEM_NAME=Android   -DCMAKE_EXE_LINKER_FLAGS="-pie -llog"   -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/   -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build   -DBOOST_ROOT=$HOME/armnn-devenv/boost/install/   -DARMCOMPUTENEON=1 -DARMCOMPUTECL=1   -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1   -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/
CMake Error at /usr/share/cmake-3.10/Modules/Platform/Android-Determine.cmake:135 (message):
  Android: Neither the NDK or a standalone toolchain was found.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:130 (include)
  CMakeLists.txt:2 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

-Thank you

**Comment by praisonjoshua** [comment]
Yes , help us in this regard

**Comment by Surmeh** [comment]
Hi @VinayKarnam,

The https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md guide incorrectly specifies Ubuntu 18.04, currently, we only test the Android NDK build with Ubuntu 16.04 which I have verified working with the ArmNN 18.08 release. In the current state, the linked guide does not work for Ubuntu 18.04.

Apologies for any delays caused by the typo. We'll update the documentation to reflect the correct version of Ubuntu.

**Comment by VinayKarnam** [comment]
Ok thank you for your reply

**Comment by georgeokelly** [comment]
It's still incorrect.

> They have been tested on a clean install of Ubuntu 18.04.

**Comment by MatthewARM** [comment]
@georgeokelly are you seeing problems? We do some testing on 18.04 now and all issues are supposed to be resolved.

**Comment by georgeokelly** [comment]
yes. I met with the same issue. @MatthewARM 
OS:  Ubuntu 18.04.2 LTS
cmake version: 3.10.2

```
ndk@ubuntu:~/armnn-devenv/armnn/build$ CXX=aarch64-linux-android-clang++  CC=aarch64-linux-android-clang  CXX_FLAGS="-fPIE -fPIC"  cmake ..   \
-DCMAKE_SYSTEM_NAME=Android   \
-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a   \
-DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=$HOME/armnn-devenv/toolchains/aarch64-android-r18b/   \
-DCMAKE_EXE_LINKER_FLAGS="-pie -llog"   \
-DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary/   \
-DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build   \
-DBOOST_ROOT=$HOME/armnn-devenv/boost/install/   \
-DARMCOMPUTENEON=1 -DARMCOMPUTECL=0   \
-DTF_GENERATED_SOURCES=$HOME/armnn-devenv/google/tf_pb/ -DBUILD_TF_PARSER=1   \
-DPROTOBUF_ROOT=$HOME/armnn-devenv/google/arm64_pb_install/

CMake Warning at /usr/share/cmake-3.10/Modules/Platform/Android-Determine.cmake:125 (message):
  Android: Did not detect API level from

    /home/ndk/armnn-devenv/toolchains/aarch64-android-r18b//bin/clang

  or

    /home/ndk/armnn-devenv/toolchains/aarch64-android-r18b//sysroot/usr/include/android/api-level.h

Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:130 (include)
  CMakeLists.txt:6 (project)


CMake Error at /usr/share/cmake-3.10/Modules/Platform/Android-Determine.cmake:195 (message):
  Android: The API specified by CMAKE_SYSTEM_VERSION='' is not an integer.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:130 (include)
  CMakeLists.txt:6 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

```

**Comment by MatthewARM** [comment]
OK thanks I'll reopen this issue.

**Comment by MatthewARM** [comment]
Hi @georgeokelly I can see that you are using NDK r18b rather than r16b as in the guide. Have you tried with r16b and do you require r18b for your project?

**Comment by MatthewARM** [comment]
Ahah I've found the problem, the armnn_19_02 release has an updated guide, but the master branch has not been updated. The release can be found here: https://github.com/ARM-software/armnn/tree/branches/armnn_19_02

I'll look into why the master branch is out of date.

**Comment by georgeokelly** [comment]
Hi. I try with NDK r17c and it works. Thanks a lot.

**Comment by MatthewARM** [comment]
I've made the master branch on github track the master branch from gerrit, so this sort of discrepancy should not happen again.

All the best,
Matthew
