### ISSUE TITLE
How to build armnnTfLiteParser ? 

### ISSUE THREAD

**Issue by WenguoLi** [ARM-software/armnn#83]
Hi,

How to build armnnTfLiteParser ? 

 I revised some defines from cmake/GlobalConfig.cmake

```
option(BUILD_TF_LITE_PARSER "Build Tensorflow Lite parser" OFF) to ON
option(TF_LITE_GENERATED_PATH "Tensorflow lite generated C++ schema location" OFF) to ON
option(FLATBUFFERS_ROOT "Location where the flatbuffers 'include' and 'lib' folders to be found" OFF) to ON
```
But I'm not sure how to specify TF_LITE_GENERATED_PATH and FLATBUFFERS_ROOT ?

Do you have any suggestions?

Thanks!

**Comment by MatthewARM** [comment]
Hi @WenguoLi we're working on improving the documentation for this.

The armnnTfLiteParser has two specific dependencies: 1) the .tflite file definition, and 2) the flatbuffers library.

When you build TfLite, it will generate the .tflite file definition. This is in two files called "schema.fbs and schema_generated.h". For me they are at:  `/home/MatthewARM/work/install/aarch64/tensorflow/tensorflow/contrib/lite/schema/` although the exact location will depend on where and how you built TFlite. Pass this path to TF_LITE_GENERATED_PATH.

You can download the flatbuffers library from https://github.com/google/flatbuffers/
You need to build flatbuffers, then pass the location of the 'include' and  'lib' folders in FLATBUFFERS_ROOT for armnn.

Hope that helps,
Matthew

**Comment by WenguoLi** [comment]
@MatthewARM , Thanks for your reply !

I have successfully built the armnnTfLiteParser according to your suggestion.

Thanks a lot.

**Comment by TelmoARM** [comment]
Closing issue

**Comment by lwu025** [comment]
May I know how to build flatbuffers on a x86_64 machine for my arm64 board?

**Comment by nullbyte91** [comment]
@lwu025 You no need to cross compile flatbuffers. Install on the X86 System and Pass the path to -DFLATBUFFERS_ROOT.
