### ISSUE TITLE
error: no member named 'to_string' in namespace 'std' 

### ISSUE THREAD

**Issue by Zenonxiu** [ARM-software/armnn#84]
I got an "error: no member named 'to_string' in namespace 'std'" when tried to build armnn. 

CXX=aarch64-linux-android-clang++ CC=aarch64-linux-android-clang CXX_FLAGS="-fPIE -fPIC" cmake ..  -DCMAKE_SYSTEM_NAME=Linux  -DCMAKE_EXE_LINKER_FLAGS="-pie -llog" -DARMCOMPUTE_ROOT=/home/zenxiu01/work/NewDisk/armnn-18.08/ComputeLibrary/  -DARMCOMPUTE_BUILD_DIR=/home/zenxiu01/work/NewDisk/armnn-18.08/ComputeLibrary/build  -DBOOST_ROOT=/home/zenxiu01/work/NewDisk/armnn-18.08/boost/install/ -DARMCOMPUTENEON=1 -DARMCOMPUTECL=0 -DTF_GENERATED_SOURCES=/home/zenxiu01/work/NewDisk/armnn-18.08/google/tf_pb/ -DBUILD_TF_PARSER=1 -DPROTOBUF_ROOT=/home/zenxiu01/work/NewDisk/armnn-18.08/google/arm64_pb_install/

[  4%] Built target armnnUtils
[  5%] Building CXX object CMakeFiles/armnn.dir/src/armnn/SerializeLayerParameters.cpp.o
[  6%] Building CXX object CMakeFiles/armnn.dir/src/armnn/Network.cpp.o
[  7%] Building CXX object CMakeFiles/armnn.dir/src/armnn/memory/BlobLifetimeManager.cpp.o
[  7%] Building CXX object CMakeFiles/armnn.dir/src/armnn/memory/BlobMemoryPool.cpp.o
[  8%] Building CXX object CMakeFiles/armnn.dir/src/armnn/Optimizer.cpp.o
[  8%] Building CXX object CMakeFiles/armnn.dir/src/armnn/NeonInterceptorScheduler.cpp.o
[  9%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/NeonWorkloadUtils.cpp.o
[  9%] Building CXX object CMakeFiles/armnn.dir/src/armnn/NeonTimer.cpp.o
[ 10%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/ArmComputeTensorUtils.cpp.o
[ 10%] Building CXX object CMakeFiles/armnn.dir/src/armnn/backends/NeonWorkloads/NeonSplitterUint8Workload.cpp.o
[ 10%] Building CXX object CMakeFiles/armnn.dir/src/armnn/memory/OffsetLifetimeManager.cpp.o
[ 10%] Building CXX object CMakeFiles/armnn.dir/src/armnn/memory/PoolManager.cpp.o
[ 11%] Building CXX object CMakeFiles/armnn.dir/src/armnn/memory/OffsetMemoryPool.cpp.o
[ 11%] Building CXX object CMakeFiles/armnn.dir/src/armnn/memory/BaseMemoryManager.cpp.o
/home/zenxiu01/work/NewDisk/armnn-18.08/armnn/src/armnn/SerializeLayerParameters.cpp:49:17: error: no member named 'to_string' in namespace 'std'
    fn("A",std::to_string(desc.m_A));
           ~~~~~^
/home/zenxiu01/work/NewDisk/armnn-18.08/armnn/src/armnn/SerializeLayerParameters.cpp:50:17: error: no member named 'to_string' in namespace 'std'
    fn("B",std::to_string(desc.m_B));
           ~~~~~^
/home/zenxiu01/work/NewDisk/armnn-18.08/armnn/src/armnn/SerializeLayerParameters.cpp:77:19: error: no member named 'to_string' in namespace 'std'
    fn("Eps",std::to_string(desc.m_Eps));
             ~~~~~^
/home/zenxiu01/work/NewDisk/armnn-18.08/armnn/src/armnn/SerializeLayerParameters.cpp:132:21: error: no member named 'to_string' in namespace 'std'
    fn("Beta", std::to_string(desc.m_Beta));
               ~~~~~^
4 errors generated.

**Comment by Zenonxiu** [comment]
The toolchain is NDK_r17

**Comment by MatthewARM** [comment]
Hi at @Zenonxiu I'm pretty sure that this happens when using the gnustl. Please could you try using libc++ following the instructions here: https://github.com/ARM-software/armnn/blob/master/BuildGuideAndroidNDK.md

**Comment by MatthewARM** [comment]
Hi @Zenonxiu I hope you were able to solve this problem. Please feel free to get back in touch if you have any more questions.
