### ISSUE TITLE
Error while running UnitTests

### ISSUE THREAD

**Issue by VinayKarnam** [ARM-software/armnn#86]
WARNING: linker: /data/local/tmp/UnitTests: unsupported flags DT_FLAGS_1=0x8000000
Running 735 test cases...
Pass
/home/praison/armnn-devenv/armnn/src/armnn/test/JsonPrinterTests.cpp(163): error: in
"JsonPrinterTests/SoftmaxProfilerJSONPrinterGpuAccTest": check error == Status::Success has
failed [Status::Failure != Status::Success]
unknown location(0): fatal error: in "JsonPrinterTests/SoftmaxProfilerJSONPrinterGpuAccTest":
std::out_of_range: unordered_map::at: key not found
/home/praison/armnn-devenv/armnn/src/armnn/test/JsonPrinterTests.cpp(163): last checkpoint
Pass
unknown location(0): fatal error: in "Compute_ArmComputeCl/SimpleSoftmaxBeta1Uint8":
cl::Error: clCreateKernel
/home/praison/armnn-devenv/armnn/src/armnn/backends/test/ArmComputeCl.cpp(35): last
checkpoint: "SimpleSoftmaxBeta1Uint8" entry.
Pass
unknown location(0): fatal error: in "Compute_ArmComputeCl/SimpleSoftmaxBeta2Uint8":
cl::Error: clCreateKernel
/home/praison/armnn-devenv/armnn/src/armnn/backends/test/ArmComputeCl.cpp(36): last
checkpoint: "SimpleSoftmaxBeta2Uint8" entry.
/home/praison/armnn-devenv/armnn/src/armnn/test/UnitTests.hpp(42): error: in
"Compute_ArmComputeCl/IgnorePaddingSimpleMaxPooling2d": check
CompareTensors(testResult.output, testResult.outputExpected) has failed. 1 different values at:
[0,0,0,0] (0 != -1)
/home/praison/armnn-devenv/armnn/src/armnn/test/UnitTests.hpp(42): error: in
"Compute_ArmComputeCl/IgnorePaddingMaxPooling2dSize3": check
CompareTensors(testResult.output, testResult.outputExpected) has failed. 1 different values at:
[0,0,0,0] (0 != -1)
/home/praison/armnn-devenv/armnn/src/armnn/test/UnitTests.hpp(42): error: in
"Compute_ArmComputeCl/CompareNormalizationWithinWithReference": check
CompareTensors(testResult.output, testResult.outputExpected) has failed. 11492 different values at:
[0,0,0,1] (-0.00200003 != -0.00177878), [0,0,0,2] (0.00567451 != 0.00522907), [0,0,0,3] (-
0.0105134 != -0.0103978), ... (and 11489 other differences)
Pass
unknown location(0): fatal error: in "Compute_ArmComputeCl/CompareSoftmaxUint8": cl::Error:
clCreateKernel
/home/praison/armnn-devenv/armnn/src/armnn/backends/test/ArmComputeCl.cpp(239): last
checkpoint: "CompareSoftmaxUint8" entry.
BC-src-code:398:82: error: use of undeclared identifier 'HALF_MAX'
...8) type_min_ = (VEC_DATA_TYPE(DATA_TYPE, 8))(MINVAL);
^
BC-src-code:376:17: note: expanded from macro 'MINVAL'
#define MINVAL -HALF_MAX1
^
BC-src-code:409:83: error: use of undeclared identifier 'HALF_MAX'
...16) type_min = (VEC_DATA_TYPE(DATA_TYPE, 16))(MINVAL);
^
BC-src-code:376:17: note: expanded from macro 'MINVAL'
#define MINVAL -HALF_MAX
^
BC-src-code:672:86: error: use of undeclared identifier 'HALF_MAX'
...4) type_min4 = (VEC_DATA_TYPE(DATA_TYPE, 4))(MINVAL);
1

^
BC-src-code:376:17: note: expanded from macro 'MINVAL'
#define MINVAL -HALF_MAX
^
3 diagnostic(s) generated.
unknown location(0): fatal error: in "CreateWorkloadCl/CreateSoftmaxFloat16WorkloadTest":
cl::Error: clCreateKernel
/home/praison/armnn-devenv/armnn/src/armnn/backends/test/CreateWorkloadCl.cpp(362): last
checkpoint: "CreateSoftmaxFloat16WorkloadTest" entry.
*** 9 failures are detected in the test module "UnitTests"

**Comment by MatthewARM** [comment]
Hi @VinayKarnam looks like the OpenCL code is not compiling properly. Can you tell us anything about the GPU and drivers that you are using?

All the best,
Matthew

**Comment by VinayKarnam** [comment]
We ran UnitTests on an android device
device name:Xiaomi Redmi Note 4
cpu :  Snapdragon 625 8x 2.0 GHz Cortex-A53
gpu:      Mali-T880 MP4

**Comment by msuryadeekshith** [comment]
Hi @VinayKarnam , as @MatthewARM suggested, it is a problem of OpenCL code compilation as it could not find the definition of certain macros. So, as a quick hack to resolve this issue, you can define the macro directly in the .cl file, wherever required. 
[https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/macroLimits.html](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/macroLimits.html)

you can check where all "HALF_MAX" is needed in the kernels, and define there.

**Comment by praisonjoshua** [comment]
Hi @msuryadeekshith  we (@VinayKarnam ) have resolved the half max issue , and error has reduced to 8 failures .

**Comment by praisonjoshua** [comment]
mido:/ $ LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/UnitTests
WARNING: linker: /data/local/tmp/UnitTests: unsupported flags DT_FLAGS_1=0x8000000
Running 735 test cases...
Pass
/home/praison/armnn-devenv/armnn/src/armnn/test/JsonPrinterTests.cpp(163): error: in "JsonPrinterTests/SoftmaxProfilerJSONPrinterGpuAccTest": check error == Status::Success has failed [Status::Failure != Status::Success]
unknown location(0): fatal error: in "JsonPrinterTests/SoftmaxProfilerJSONPrinterGpuAccTest": std::out_of_range: unordered_map::at: key not found
/home/praison/armnn-devenv/armnn/src/armnn/test/JsonPrinterTests.cpp(163): last checkpoint
Pass
unknown location(0): fatal error: in "Compute_ArmComputeCl/SimpleSoftmaxBeta1Uint8": cl::Error: clCreateKernel
/home/praison/armnn-devenv/armnn/src/armnn/backends/test/ArmComputeCl.cpp(35): last checkpoint: "SimpleSoftmaxBeta1Uint8" entry.
Pass
unknown location(0): fatal error: in "Compute_ArmComputeCl/SimpleSoftmaxBeta2Uint8": cl::Error: clCreateKernel
/home/praison/armnn-devenv/armnn/src/armnn/backends/test/ArmComputeCl.cpp(36): last checkpoint: "SimpleSoftmaxBeta2Uint8" entry.
/home/praison/armnn-devenv/armnn/src/armnn/test/UnitTests.hpp(42): error: in "Compute_ArmComputeCl/IgnorePaddingSimpleMaxPooling2d": check CompareTensors(testResult.output, testResult.outputExpected) has failed. 1 different values at: [0,0,0,0] (0 != -1)
/home/praison/armnn-devenv/armnn/src/armnn/test/UnitTests.hpp(42): error: in "Compute_ArmComputeCl/IgnorePaddingMaxPooling2dSize3": check CompareTensors(testResult.output, testResult.outputExpected) has failed. 1 different values at: [0,0,0,0] (0 != -1)
/home/praison/armnn-devenv/armnn/src/armnn/test/UnitTests.hpp(42): error: in "Compute_ArmComputeCl/CompareNormalizationWithinWithReference": check CompareTensors(testResult.output, testResult.outputExpected) has failed. 11492 different values at: [0,0,0,1] (-0.00200003 != -0.00177878), [0,0,0,2] (0.00567451 != 0.00522907), [0,0,0,3] (-0.0105134 != -0.0103978), ... (and 11489 other differences)
Pass
unknown location(0): fatal error: in "Compute_ArmComputeCl/CompareSoftmaxUint8": cl::Error: clCreateKernel
/home/praison/armnn-devenv/armnn/src/armnn/backends/test/ArmComputeCl.cpp(239): last checkpoint: "CompareSoftmaxUint8" entry.

*** 8 failures are detected in the test module "UnitTests"

**Comment by MatthewARM** [comment]
Are you sure you have a Mali-T880 MP4? I thought that the Snapdragon 625 used an Adreno GPU? I suspect that the OpenCL drivers that you are using cannot support the Arm Compute Library.

**Comment by praisonjoshua** [comment]
> Are you sure you have a Mali-T880 MP4? I thought that the Snapdragon 625 used an Adreno GPU? I suspect that the OpenCL drivers that you are using cannot support the Arm Compute Library.

@MatthewARM 
Sorry sir , the gpu spec is as follows
Gpu : Adreno 506

**Comment by KevinRodrigues05** [comment]
.

**Comment by MatthewARM** [comment]
@praisonjoshua I'll pass on your question to a member of the Compute Library team. I'm not sure whether anyone has tried running the Compute Library on an Adreno 506 before so this is an interesting experiment. I believe that it supports an OpenCL 2.0 profile which should be sufficient, although your error messages indicate that something is missing.

**Comment by GeorgeARM** [comment]
Hello @praisonjoshua,

Theoretically yes if you have an OpenCL 2.0 capable device the kernels should work. Not that efficiently though as they are optimized for Mali GPUs. Eitherway, you might have some compilation issues due to different driver implementation details but these should be easy to fix once you understand them. Can you get more information on the `clCreateKernel` errors?

**Comment by aonaiyong** [comment]
> Hi @msuryadeekshith we (@VinayKarnam ) have resolved the half max issue , and error has reduced to 8 failures .

Hi @praisonjoshua , could u explain the solution in detail？

**Comment by Surmeh** [comment]
Hi @praisonjoshua, Could you please update us with the information.

**Comment by MatthewARM** [comment]
Hi @praisonjoshua I hope you were able to resolve the issue. I'm closing this ticket for now but feel free to re-open if you are still having problems.

**Comment by mathpopo** [comment]
> Are you sure you have a Mali-T880 MP4? I thought that the Snapdragon 625 used an Adreno GPU? I suspect that the OpenCL drivers that you are using cannot support the Arm Compute Library.

hi,if mali G-xx  can satisfy the  opencl2.0?satisfy the arm computer library?
