### ISSUE TITLE
UnitTest error

### ISSUE THREAD

**Issue by vinayonchip** [ARM-software/armnn#88]
When I run the cross compiled UnitTests executable on raspberry pi3, I am getting the following error. 

Running 358 test cases...

*** No errors detected
*** Error in `./UnitTests': corrupted double-linked list: 0x00c81f88 ***
Aborted

**Comment by MatthewARM** [comment]
Hi @vinayonchip in order to for us to help debug this could you provide your 'cmake' command line, and would you be able try with a debug build and running under a debugger so that we can see a stack trace?

All the best,
Matthew

**Comment by sbalpande1990** [comment]
@MatthewARM I have tried setting variable for debug is -DCMAKE_BUILD_TYPE=debug32.
Is this the right variable for debug mode or need to set different variable?

**Comment by MatthewARM** [comment]
Hi @sbalpande1990 it should be `-DCMAKE_BUILD_TYPE=Debug`

All the best,
Matthew

**Comment by sbalpande1990** [comment]
Hi MatthewARM,

Thanks for the quick response.

Please find bellow back trace in debug mode and cmake command
 
Cmake commnad line  : CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ cmake .. -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ -DCMAKE_BUILD_TYPE=release32 -DARMCOMPUTE_ROOT=/home/linux64/ARM64/ComputeLibrary-master -DARMCOMPUTE_BUILD_DIR=/home/linux64/ARM64/ComputeLibrary-master/build -DBOOST_ROOT=/home/linux64/armnn-devenv/boost_arm64_install -DTF_GENERATED_SOURCES=/home/linux64/armnn-devenv/Tensorflow/ -DBUILD_TF_PARSER=1 -DPROTOBUF_ROOT=/home/linux64/armnn-devenv/google/x86_64_pb_install -DPROTOBUF_LIBRARY_DEBUG=/home/linux64/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.15.0.1 -DPROTOBUF_LIBRARY_RELEASE=/home/linux64/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.15.0.1


![trace](https://user-images.githubusercontent.com/13729453/48623374-74b01900-e9cf-11e8-8d60-e95fceaf4768.png)


Regards,
Swapnil

**Comment by MatthewARM** [comment]
Hi @sbalpande1990 from the stack trace it looks like this is a problem with the boost unit test framework itself. Can I ask what version of boost you are using and how you are compiling it?

Many thanks,
Matthew

**Comment by sbalpande1990** [comment]
Hi MatthewARM,

I am using boost version 1.64.0.
I have used following steps for building the boost library for cortex A53
1. tar -zxvf boost_1_64_0.tar.gz
2. cd boost_1_64_0
3. echo "using gcc : arm : arm-linux-gnueabihf-g++ ;" > user-config.jam
4.  ./bootstrap.sh --prefix=/home/administrator/users_local/Mamta/TSR/armnn-raspberry-pi/armnn-devenv/boost_arm64_install
5. ./b2 install toolset=gcc-arm link=static cxxflags=-fPIC --with-filesystem --with-test --with-log --with-program_options -j32 --user-config=user-config.jam 

Please let me know if I am missing anything in above steps.

Regards,
Swapnil

**Comment by Surmeh** [comment]
Hi @sbalpande1990, were you able to resolve your problem? Please get back in touch if require any help.

**Comment by vinayonchip** [comment]
Hi..! @MatthewARM @sbalpande1990 @Surmeh  the issue still exists.
 Checking the https://github.com/ARM-software/armnn/blob/branches/armnn_18_11/README.md there is a 
Note that **Arm NN needs to be built against a particular version of ARM's Compute Library**. The get_compute_library.sh in the scripts subdirectory will clone the compute library from the review.mlplatform.org github repository into a directory alongside armnn named 'clframework' and checkouts the correct revision.

but running the script get_compute_library.sh gives me an error:
setting GITHUB_USERNAME: vinay use -g command line option to change
+++ Cloning clframework
Cloning into 'clframework'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning CL Framework failed
+++ Command exited with code 128. Please fix the above errors and re-run

I am creating a new issue regarding the script get_compute_library.sh

Thank you,
Vinay

**Comment by MatthewARM** [comment]
Hi @vinayonchip we've found exactly which test causes the problem now:

```
pi@raspberrypi:~/armnn-dist $ ./UnitTests -t Profiler/RegisterUnregisterProfilerMultipleThreads
Running 1 test case...

*** No errors detected
*** Error in `./UnitTests': corrupted double-linked list: 0x00b6d628 ***
Aborted
```
and running without that test:

```
pi@raspberrypi:~/armnn-dist $ ./UnitTests -t \!Profiler/RegisterUnregisterProfilerMultipleThreads
Running 1106 test cases...

*** No errors detected
```

We are continuing to analyse the underlying issue

**Comment by vinayonchip** [comment]
@MatthewARM Thanks for the update.!

**Comment by FrancisMurtagh-arm** [comment]
Closing due to age and lack of activity. Also a fix for test has been merged:
Id69ab3cc0aa8c61021642b7250e30c255f144a3a
