### ISSUE TITLE
Dataset for TfLiteParser testing

### ISSUE THREAD

**Issue by yetToLearn** [ARM-software/armnn#89]
As mentioned in the documentation,

"Arm tested these operators with the following TensorFlow Lite neural network:

Quantized MobileNet"

What was the dataset used for testing this parser and how was it tested. Can you explain more on this.

**Comment by MatthewARM** [comment]
Hi @yetToLearn we use MobileNet_v1_1.0_224 from https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md

We use the test code at TfLiteMobilenetQuantized-Armnn to run a few test images through the model, and we check that the same results are generated through ArmNN and Tensorflow Lite.

**Comment by MatthewARM** [comment]
Hi @yetToLearn I hope I was able to answer your question.
All the best,
Matthew
