### ISSUE TITLE
Unsupported operation Rsqrt in tensorflow::GraphDef  at function LoadNodeDef

### ISSUE THREAD

**Issue by qsu2014** [ARM-software/armnn#90]
I am seeing this problem while using armnn v18.08 and my tensorflow network models of inceptionnet_v1.pb and mobilenet_v1_224.pb. Please advice on how to resolve the problem. Thanks!

**Comment by MatthewARM** [comment]
Hi @qsu2014 please try following the steps documented here: https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/optimizing-neural-networks-for-mobile-and-embedded-devices-with-tensorflow

You need to follow these steps to combine rsqrt operations into 'batch_normalization' layers which will be supported by ArmNN.

**Comment by MatthewARM** [comment]
Closing this ticket as I believe the original issue has been resolved. If you are still having problems please open a new ticket.
