### ISSUE TITLE
Testing fails with properly cropped images

### ISSUE THREAD

**Issue by xiaomin05** [ARM-software/armnn#91]
in armnn/tests/InferenceTestImage.cpp, lin 225 (Release 10.08)

 226     if (newWidth == m_Width && newHeight == m_Height)
 227     {
 228         // Nothing to do.
 229         return out;
 230     }

This results in random output, instead of the original image it. Please fix it.

**Comment by Surmeh** [comment]
Hi @xiaomin05, were you able to try the fix? I'll close this issue if your issue has been resolved.

**Comment by xiaomin05** [comment]
yes, it works with provided patch.

**Comment by Surmeh** [comment]
Thanks for the update @xiaomin05.
