### ISSUE TITLE
How many threads does the arm nn run?

### ISSUE THREAD

**Issue by Wayne-pw** [ARM-software/armnn#92]
How many threads does the arm nn run? Can I modify the number of threads?

**Comment by MatthewARM** [comment]
Hi @Wayne-pw if you mean the number of threads in the Neon code, it's set by the Compute Library and you can modify it using the Compute Library API.  I think this answer will be helpful to you: https://github.com/ARM-software/armnn/issues/75

**Comment by MatthewARM** [comment]
I'll see if I can get a Compute Library person to answer this question.

**Comment by GeorgeARM** [comment]
Hello @Wayne-pw,

[By default ](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/CPUUtils.cpp#L353) we look at how many cores of each type you've got on your system (in case of mixed-core system e.g. Big-Little) and set the number of threads to the minimum: (i.e if you've got 2 cores of one type and 4 of another, the default number of threads will be 2).

You can set the number of threads manually just like @MatthewARM mentioned in #75
