### ISSUE TITLE
fail to produce .dot file to visualize optimized model

### ISSUE THREAD

**Issue by xiaomin05** [ARM-software/armnn#95]
from the testcase CLI:
"-v [ --visualize-optimized-model ] arg (=0)
                                        Produce a dot file useful for
                                        visualizing the graph post
                                        optimization.The file will have the
                                        same name as the model with the .dot
                                        extention.
"
However, no dot file was produced when -v 1 is specified:
"./TfMobileNet-Armnn -d imagenet -m model/ -v 1"

**Comment by MatthewARM** [comment]
Hi @xiaomin05 this is very mysterious, we are investigating to see under which circumstances this might happen.

**Comment by dbeck-arm** [comment]
Hi @xiaomin05 , can you please check if the .dot file was created in the models folder, next to the model?

**Comment by xiaomin05** [comment]
thanks! it was indeed generated in the model dir, instead of the cur dir. sorry for the confusion.

**Comment by xiaomin05** [comment]
thanks! it was indeed generated in the model dir, instead of the cur dir. sorry for the confusion.
