### ISSUE TITLE
unsupported operation 'Variablev2'

### ISSUE THREAD

**Issue by jinzequn** [ARM-software/armnn#98]
1. When i trying to run my own model in ARMNN library, the error is  "unsupported operation 'Variablev2'", how could i solve this problem?
2. Could i set the input node in ARMNN? I want to put my data into the model from layer 3 not Placeholder.

thank you!

**Comment by MatthewARM** [comment]
Hi @jinzequn I guess you are using the Tensorflow parser?

Variablev2 cannot be parsed by the parser, as ArmNN has no support for variables yet. You need to use Tensorflow (or toco) to prune it from the graph before passing to ArmNN.

Probably the easiest way to set the input node is to use toco to prune off the bit of the graph that you don't need.  

toco is part of tensorflow and has pretty good command-line help. You will need to use the `--input_arrays`, `--input_shapes`, and `--output_arrays` options.

Best regards,
Matthew

**Comment by jinzequn** [comment]
I'm using  the Tensorflow parser, I'm sorry I forgot mention it in my issue.

Thanks a lot for your replay, I will try it.
