### ISSUE TITLE
build failed, dangerous relocation: unsupported relocation

### ISSUE THREAD

**Issue by shawnhsy** [ARM-software/armnn#99]
Got a bunch of errors when building on a rk3399, system is ubuntu 18, arch is aarch64. 
Computelibrary and Caffe are successfully built.

errors looks like this, when Linking CXX shared library libarmnn.so
```
/usr/bin/ld: /home/pi/code/ComputeLibrary/build/libarm_compute_core-static.a(depthwise_4x4_3x3_1x1_fp32_fp32.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN9depthwise24DepthwiseConvolutionImplILi4ELi4ELi3ELi3ELi1ELi1EffE12process_tileILb1ELi0ELi1ELi0ELi0ELi0ELi0EEEviPKfiiS4_iiPfiiiiiiii' which may bind externally can not be used when making a shared object; recompile with -fPIC
depthwise_4x4_3x3_1x1_fp32_fp32.cpp:(.text._ZN9depthwise20DepthwiseConvolutionILi4ELi4ELi3ELi3ELi1ELi1EffE16process_tile_rowEiPKfiiS3_iiPfiiiiiiiii[_ZN9depthwise20DepthwiseConvolutionILi4ELi4ELi3ELi3ELi1ELi1EffE16process_tile_rowEiPKfiiS3_iiPfiiiiiiiii]+0x1f8): dangerous relocation: unsupported relocation

```

tried adding CXXFLAGS="-fPIE -fPIC" cmake ... and still got the same result.

**Comment by MatthewARM** [comment]
HI @shawnhsy it looks like the Compute Library build needs -fPIC, are you sure that Compute Library got the -fPIC flag (not just armnn)?  You can force that by adding `extra_cxx_flags="-fPIC"`  on the scons command line for Compute Library

**Comment by shawnhsy** [comment]
@MatthewARM you are right! Rebuild ACL fix this. Thanx
